### ISSUE TITLE
Rebase from Geth 1.6

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#100]
Now that Geth 1.6 is out, I'm wondering what the timeline is for porting Quorum to Geth 1.6.

It has an abstracted consensus layer, so it should be easier to incorporate the Quorum consensus mechanisms.

Would fix #87, #93, ...

**Comment by patrickmn** [comment]
Duplicate of https://github.com/jpmorganchase/quorum/issues/93
