### ISSUE TITLE
Add config parameter to set RAFT folders base path

### ISSUE THREAD

**Issue by melihbirim** [Consensys-Incorporated/quorum#1002]
In any RAFT protocol there are 3 folders, **quorum-raft-state**, **raft-wal** and **raft-snap**

These folders contain RAFT related content and written under dd folder in quorum node, which is near geth folder.

In some case, where RAFT election takes time or network problems, these log files become huge and need to be rotated and backed up with different storage mounted for security reasons. 

So instead to write these logs files to "datadir" folder a new config parameter needed to specify where it could be written. 

Possible problems for the folder specified in config could be a problem regarding read and write operations but this could be checked at initialization phase and a warning can be thrown at start time.

**Comment by melihbirim** [comment]
@fixanoid I will start on this issue. Are there any requirements or requests for us to consider or think about it before I start?

**Comment by baptiste-b-pegasys** [comment]
closing this, please open a separate issue for the other options
