### ISSUE TITLE
How to recompile

### ISSUE THREAD

**Issue by SoftProgramLX** [Consensys-Incorporated/quorum#1003]
I simply modified the string returned by a function and ran
`./build/clean_go_build_cache.sh`
`make all`
The string returned after the call does not change. 
What can I do to make the modified code effective? thanks

**Comment by SoftProgramLX** [comment]
Modified line 3930 of "internal/jsre/deps/web3.js" file, and still returned "invalid address" in geth
```
> eth.getBalance("--")
Error: invalid address
    at web3.js:3930:15
    at web3.js:5025:28
    at map (<native code>)
    at web3.js:5024:12
    at web3.js:5050:18
    at web3.js:5075:23
    at <anonymous>:1:1
```

**Comment by fixanoid** [comment]
@SoftProgramLX Could you explain what you are trying to do?

**Comment by SoftProgramLX** [comment]
> @SoftProgramLX Could you explain what you are trying to do?

How to make the modified code take effect. What steps need to be taken？

**Comment by fixanoid** [comment]
@SoftProgramLX if you have modified something, rebuilding client is all thats needed. Build instructions are here: https://geth.ethereum.org/docs/install-and-build/cross-compile -- see make file section. And here are the makefile options: https://github.com/jpmorganchase/quorum/blob/master/Makefile


As you do not explain what modifications you are making, I cannot comment on the errors you are running into, but from my knowledge of the client, editing web3.js is rarely needed as it only affects `geth console` -- if you need to change web3.js interface, start with quorum.js here: https://github.com/jpmorganchase/quorum.js
