### ISSUE TITLE
New node joining the existing quorum faild

### ISSUE THREAD

**Issue by lyonnee** [Consensys-Incorporated/quorum#1005]
Hello, I have a problem adding new nodes to the network
Geth
Version: 1.8.18-stable
Git Commit: b9e886c4e59b8bb8bb35b6bf3f98f0940078f562
Quorum Version: 2.5.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.4
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.10

I have deployed 4 node programs on a server, and successfully run them. I can deploy smart contracts and complete transactions.
Now I need to add a new node to the network. I use the same quorum version according to the normal process of adding new nodes genesis.json File, and pass raft.addPeer Method and update static- nodes.json file.

I have added raft.addPeer(enodeId) into my cluster
![image](https://user-images.githubusercontent.com/30852031/82795178-36d65f80-9ea6-11ea-8c7f-aabe6ec938aa.png)

and started new geth node with the flag --raftjoinexisting
![image](https://user-images.githubusercontent.com/30852031/82795299-5f5e5980-9ea6-11ea-8782-8e9a84de1395.png)

the running node has this error
![image](https://user-images.githubusercontent.com/30852031/82795463-a3515e80-9ea6-11ea-9588-7cb5da39764b.png)

the new node has this error
![image](https://user-images.githubusercontent.com/30852031/82795722-fb886080-9ea6-11ea-8410-4143618aa702.png)

the new node geth console info
![image](https://user-images.githubusercontent.com/30852031/82796033-78b3d580-9ea7-11ea-9317-8e768ca20527.png)

**Comment by amalrajmani** [comment]
Hi @LyonNee 
I tried to simulate what you are doing and it works fine for me. This is what I did:
1. started a 4 node raft network (quorum-2.5.0) without permission feature enabled. All nodes running in the same machine(my laptop). 
2. Added the 5th node via raft.addPeer and brought it up with --raftjoinexisting flag. as per [doc](http://docs.goquorum.com/en/latest/How-To-Guides/adding_nodes/) 

**To analyse your issue further please provide the following details:**
1. are all nodes running in the same machine? 
2. geth log of all nodes including the newly added node
3. contents of datadir/static-nodes.json from all nodes
4. if you are running in permissioned mode contents of datadir/permissioned-nodes.json from all nodes
5. command line arguments of all the geth nodes running
