### ISSUE TITLE
Update containers/{docker,vagrant} for Quorum and Constellation

### ISSUE THREAD

**Issue by Anatoliy4041** [Consensys-Incorporated/quorum#101]
#### System information

Geth version: 1.5.0-unstable

OS & Version: Ubuntu 16.04.1 LTS

Branch, Commit Hash or Release: `master`

#### Expected behaviour

Successfully built image

#### Actual behaviour

E: Unable to locate package geth

#### Steps to reproduce the behaviour
1. Clone repo
2. Opden folder /path/to/repo/quorum/containers/docker/develop-ubuntu
3. run - $ sudo docker build . 

#### Comments

Error when building docker image on the stage in Dockerfile - 

>apt-get install -q -y ethereum

**Comment by patrickmn** [comment]
Those still need to be updated for Quorum.

Right now the recommended container is the Vagrant image here: https://github.com/jpmorganchase/quorum-examples

You could probably repurpose the bootstrap.sh pretty easily, but this should be available out of the box.

**Comment by Anatoliy4041** [comment]
@patrickmn Thanks for the reply!

In addition, is there any docker-iamge on docker-hub? Couldn't fine anyone official

**Comment by patrickmn** [comment]
Nothing official yet since the dockerfile needs to be updated.

Some unofficial ones:
  - https://github.com/search?q=quorum+docker
  - https://hub.docker.com/r/agriessel/quorum/
  - https://hub.docker.com/r/cbainnovationlab/docker-quorum/

**Comment by timxor** [comment]
Hey @patrickmn, would it be alright if I help build an official dockerfile for Quorum? =)

**Comment by RobTS** [comment]
Any updates in regards to "official" docker containers?

**Comment by trung** [comment]
@RobTS , @tcsiwula : the [official docker containers](https://hub.docker.com/u/quorumengineering/):

`quorumengineering/quorum:latest`
`quorumengineering/constellation:latest`
`quorumengineering/tessera:latest`

Noted that there's no released tag yet.
