### ISSUE TITLE
Slack channel down

### ISSUE THREAD

**Issue by schouwlars** [Consensys-Incorporated/quorum#1011]
Hi there,

The link to slack on your webpage leads to a dead link that says {"message":"Forbidden"}
webpage: [https://goquorum.com/developers](https://goquorum.com/developers)
links to this button that says [Join us on slack](https://clh7rniov2.execute-api.us-east-1.amazonaws.com/Express/)

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by jpmsam** [comment]
Thank you for reporting this, we had missed it when we migrated hosts.
