### ISSUE TITLE
How to solve the CAS problem of Storage in TxManager and Quorum node?

### ISSUE THREAD

**Issue by smartiov** [Consensys-Incorporated/quorum#1012]
As we known, The private transaction will be storaged in TxManager local db, but if the transaction failed when executed in Quorum node, the private data has been storaged will rollback or not? how to gurantee this process?
Thanks.

**Comment by prd-fox** [comment]
If the transaction data failed to be saved in the Transaction Manager (either on the sending node, or any of the recipients) then the Quorum transaction will not be added to the chain, and so it will not be executed. This is the process when calling `eth_sendTransaction`.

If you are using raw transactions, then you should check the response from the transaction manager on whether to succeeded on saving and distributing the private transaction data *before* sending the Quorum transaction.

Therefore, if saving the private transaction data failed, we don't send the Quorum transaction and thus there is nothing to rollback. There will be a bit of orphaned data in the transaction manager, but the only downside to that is some extra disk usage.

**Comment by smartiov** [comment]
sorry, i mean , the transaction data saved firstly succeed in Transaction Manager, what's i mentioned is when the transaction executed failed, the transaction data has been saved. saved transaction data before the transaction executed? how to guaranteed this CAS.



At 2020-06-08 20:22:49, "Peter Fox" <notifications@github.com> wrote:

If the transaction data failed to be saved in the Transaction Manager (either on the sending node, or any of the recipients) then the Quorum transaction will not be added to the chain, and so it will not be executed. This is the process when calling eth_sendTransaction.

If you are using raw transactions, then you should check the response from the transaction manager on whether to succeeded on saving and distributing the private transaction data before sending the Quorum transaction.

Therefore, if saving the private transaction data failed, we don't send the Quorum transaction and thus there is nothing to rollback. There will be a bit of orphaned data in the transaction manager, but the only downside to that is some extra disk usage.

**Comment by prd-fox** [comment]
The transaction manager just stores the transaction input data. If the Quorum transaction fails to execute for some reason, then no update to any contracts/accounts as a result of that transaction is made.

So the private contract data (changes to contracts) that is stored in Quorum is rolled back, but the private transaction input data that is stored in the transaction manager is not changed at all.

I think I may have misunderstood some of your question - what is CAS? I was thinking of CAP when reading before.
