### ISSUE TITLE
cannot create account at run time

### ISSUE THREAD

**Issue by dungtctin4** [Consensys-Incorporated/quorum#102]
#### System information

Geth version: ` We use docker container here to launch 7 nodes program
https://github.com/agriessel/quorum-docker.git`

OS & Version: Linux Ubuntu 16.04 for host and guest machine

Branch, Commit Hash or Release: `git status`

#### Expected behaviour

We have already created and unlock a new account at run time using
personal.newAccount
personal.unlockAccount
in Javascript console of the node 1 in 7 nodes program
All is successful, a new file appears in keystore directory of the node 1

Then we try to send transaction to Simplestorage contract from this account

#### Actual behaviour
The error we receive "Account doesn't exist"

We tried to create and unlock new account using JSON RPC API by sending REST request to JSON RPC of the node 1. 
The result is the same

#### Steps to reproduce the behaviour
We stop 7 nodes program, declare the address new account in the genesis.json file
Now, we are successful to send transaction to Simplestorage contract from the new account

#### Backtrace
HOW CAN WE CREATE AND USE ACCOUNT AT THE RUN TIME, AFTER LAUNCHING QUORUM?
We need to create runtime account from Java code, not only create new account in Javascript console
THANKS

````
[backtrace]
````

**Comment by patrickmn** [comment]
You do currently need to fund the account to send transactions (even though transactions are free.) See https://github.com/jpmorganchase/quorum/issues/91
