### ISSUE TITLE
getTransctionReceipt() logs empty when contract is deployed privately

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#103]
#### System information

Geth version: `geth version` : 1.5.0-unstable

OS & Version: Windows/Linux/OSX : Linux

Branch, Commit Hash or Release: `git status` : Git Commit: 85327f743b9735c32ae9231cbdde509e243ba0df

#### Expected behaviour 
getTransactionReceipt should display the events raised in contract under logs

#### Actual behaviour
logs is coming as blank if the contract is deployed privately

Logs when contract is deployed as public
logs: [{
      address: "0xc43a77a5439dd8f5b1fa9dabd2f5fc71bbeed51f",
      blockHash: "0xbb36401a003b5ddacaf35426af2a4d46a11979cb5057cb575ec63a6bc544
895e",
      blockNumber: 74,
      data: "0x00000000000000000000000000000000000000000000000000000000000000200
00000000000000000000000000000000000000000000000000000000000000b434f4e53545255435
44f52000000000000000000000000000000000000000000",
      logIndex: 0,
      topics: ["0x51a7f65c6325882f237d4aeb43228179cfad48b868511d508e24b4437a8191
37"]

Logs when contract is deployed privately. getTranscationReceipt() output
 blockNumber: 451,
 contractAddress: "0xc8569777e141f3156a9e20be9f631e3dcf40d920",
 cumulativeGasUsed: 0,
 from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
 gasUsed: 0,
 logs: [],
 logsBloom: "0x000000000000000000000000000000000000000000000000000000
000000000000000000000000000000000000000000000000000000000000000000000

#### Steps to reproduce the behaviour
1. Run the 7Node example
2. From node 1 deploy contract as private to node 2. Scripts attached here with.
3. check the getTransactionScript

[script1.txt](https://github.com/jpmorganchase/quorum/files/942695/script1.txt)

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
hi @paliwalg, this issue was fixed in v1.0.3.  quorum-examples has been updated with the [latest ](https://github.com/jpmorganchase/quorum/releases/tag/v1.1.0)release so you shouldn't be seeing this issue. do you mind fetching the latest repo and trying again?

**Comment by paliwalg** [comment]
Hi Tyrone,

I tried it with v1.0.3. I can see now logs populated when I deploy the contract privately, then I try to call the set function privately. And then don’t see logs being populated in the corresponding transaction receipt.

Here is the same smart contract

contract simplestorage
{
uint public storedData;
event Message(string _message);
function simplestorage(uint initVal)
{
Message("CONSTRUCTOR");
storedData = initVal;
}
function set(uint x)
{
storedData = x;
Message("SET VALUE" );
}
function get() constant returns (uint retVal) {
return storedData;
}
}

Thanks
-Gourav

**Comment by tylobban** [comment]
Hi @paliwalg, please can you confirm the command you used to call the set method privately?  Keep in mind you need to specify privateFor in the transaction, i.e.:

privateContract.set(4,{from:eth.coinbase,privateFor:["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]});

**Comment by paliwalg** [comment]
Hi Tyrone,

I did that only.
Also I just setup the version 1.1.0, trying with it now…

**Comment by paliwalg** [comment]
Hi Tyron, got it working with 1.1.0 release.
Might be some issue with 1.0.3 or I might be doing something wrong.
Thanks
-Gourav

From: Gourav Paliwal
Sent: Tuesday, April 25, 2017 8:07 PM
To: 'jpmorganchase/quorum' <reply@reply.github.com>; jpmorganchase/quorum <quorum@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [jpmorganchase/quorum] getTransctionReceipt() logs empty when contract is deployed privately (#103)

Hi Tyrone,

I did that only.
Also I just setup the version 1.1.0, trying with it now…
