### ISSUE TITLE
Can I upgrade quorum version?

### ISSUE THREAD

**Issue by ssbg2** [Consensys-Incorporated/quorum#1038]
Hi there,
I've used a previous version(v2.2.1) for almost a year,It was awsome,thanks for the great work.
Recently,I want add some new node into this network,I noticed the last quorum version is 2.7.0.
Is it possible for me to upgrade the version from 2.2.1 to 2.7.0?And if answer is yes,How to upgrade the system without damaging the data?
Thank you. I really appreciate your help.

#### System information

Geth version: `v1.8.12`

OS & Version: Centos 7.5

Release version:v2.2.1

**Comment by vsmk98** [comment]
Hi @ssbg2 - please refer to the documentation on migration https://github.com/jpmorganchase/quorum/blob/master/docs/Getting%20Started/migration.md. This page details the things to keep in mind while migrating from an any older version (v2.2.1 in your case) to v2.6.0 and above.

**Comment by fixanoid** [comment]
Hi @ssbg2, also don't forget to upgrade your Tessera if its used.
