### ISSUE TITLE
Should I manually sync keystore file to other peer?

### ISSUE THREAD

**Issue by ssbg2** [Consensys-Incorporated/quorum#1041]
Hi,I've used quorum-7node-example to study quorum knowledge for almost a year,at first,I lack planning for the entire system,so there is already a lot of real data on this study demo project.
Yesterday I migrate a node to a new server and it succeded(block can sync),but when I use web3j to unlock account in the new server,an error message occurred:
Error: unknown wallet
This node datadir does not contain the keystore data,So Should I manually sync this folder from node 1?
Thank you. I really appreciate your help.

#### System information

Geth version: `v1.9.7-stable-6005360c`

OS & Version: centos7.5

**Comment by vsmk98** [comment]
Hi @ssbg2, yes in this case you will have to manually move the keystore data to new server. From 2.6.0 onwards Quorum supports `clef` which is a standalone account manager and signer. Please refer to http://docs.goquorum.com/en/latest/Account-Key-Management/Quorum/Overview/ for further information on Quorum account management. 
I am closing this issue. Please reopen, if any further information is required.
