### ISSUE TITLE
Use the go-quorum package to write a program and compile an error

### ISSUE THREAD

**Issue by lyonnee** [Consensys-Incorporated/quorum#1050]
Hi there,

#### System information
OS & Version: Windows 10

#### 

Hi, I want to write my program by referencing the go-quorum package, but there is such an error.
![image](https://user-images.githubusercontent.com/30852031/89603454-c1bad980-d89b-11ea-9cd5-790d2f5dfef6.png)

![image](https://user-images.githubusercontent.com/30852031/89605245-a651cd80-d89f-11ea-80aa-3d80ae3e4195.png)

````

````

**Comment by chris-j-h** [comment]
Hi - this appears to be an issue when developing go module-enabled apps and using certain quorum packages.  Quorum does not use go modules yet but these issues should be resolved when we do.

Please try the following:

1. Ensure the `import` statements in your code use `github.com/ethereum/go-ethereum` and not `github.com/jpmorganchase/quorum`, e.g.:
    ```go
   import (
       "github.com/ethereum/go-ethereum/accounts/abi/bind"
   )
    ```
1. Update your `go.mod`:
    ```
    module <your-module>
    
    go 1.13
    
    replace github.com/ethereum/go-ethereum => github.com/jpmorganchase/quorum v2.7.0+incompatible
    
    replace github.com/ethereum/go-ethereum/crypto/secp256k1 => github.com/jpmorganchase/quorum/crypto/secp256k1 v0.0.0-20200804194033-c8f07379f487
    
    replace github.com/syndtr/goleveldb => github.com/syndtr/goleveldb v1.0.1-0.20190923125748-758128399b1d
    
    replace github.com/hashicorp/go-hclog => github.com/hashicorp/go-hclog v0.9.3-0.20190514033442-f1d61ad5398f
    ```
   (I recommend removing all `require` statements to ensure a fresh start)
1. `go test` to download all dependencies, populate the `require` statements and test your app works
1. If the tests pass then the dependency issues have been resolved

Depending on the quorum packages used by your app, this may only be a partial fix.  I'll provide a follow up answer with more details that should provide the necessary info for you to resolve any additional dependency issues.

**Comment by chris-j-h** [comment]
In case you come up against similar issues that need resolving let me explain why you need these `replace` statements and how to determine them yourself.

1. quorum is a fork of go-ethereum and so has the same package import statements as go-ethereum.  Your code must do the same, e.g.:
    ```go
   import (
       "github.com/ethereum/go-ethereum/accounts/abi/bind"
   )
    ```
   The `replace` statement 
   ```go
    replace github.com/ethereum/go-ethereum => github.com/jpmorganchase/quorum v2.7.0+incompatible
    ``` 
   ensures your app actually uses `quorum` and not `go-ethereum`.

1. From quorum 2.7.0 onwards, the package `github.com/jpmorganchase/quorum/crypto/secp256k1` is defined as a standalone module.  
    
    This means that `github.com/jpmorganchase/quorum` no longer contains the  `crypto/secp256k1` package and we need to tell quorum to instead use the standalone module.  
   
   To do this:  
    
    1. Run:
        ```shell
        cd my-project 
        go get github.com/jpmorganchase/quorum/crypto/secp256k1
         
        # require github.com/jpmorganchase/quorum/crypto/secp256k1 v0.0.0-20200804194033-c8f07379f487 // indirect
        # will have been added to your go.mod
        ```
    1.  Chang the generated `require` statement to a `replace` statement:
        ```
        replace github.com/ethereum/go-ethereum/crypto/secp256k1 => github.com/jpmorganchase/quorum/crypto/secp256k1 v0.0.0-20200804194033-c8f07379f487
        ``` 

1. Quorum does not use `go modules` yet.  We use `govendor` and vendor dependencies in the `vendor/` directory.  

    It appears that `go mod` does not download the contents of `vendor/` directories.  When it has to resolve quorum's dependencies it defaults to using the latest available versions instead of those defined in quorum's `vendor/` directory.

    This introduces problems when the version resolved by `go mod` is incompatible with the versions required by quorum.

    The solution is to use `replace` statements to force `go mod` to use the versions that quorum requires.

    The `DisableSeeksCompaction` error you reported is due to `go.mod` resolving `github.com/syndtr/goleveldb/leveldb` to version `v1.0.0` whereas quorum requires commit version`758128399b1df3a87e92df6c26c1d2063da8fabe` (found by looking in `github.com/ethereum/go-ethereum/vendor/vendor.json`).

    To tell quorum to use the correct version we do similar steps to those described earlier:  
    
    1. Run:
        ```shell
        cd my-project 
        go get github.com/syndtr/goleveldb/leveldb@758128399b1df3a87e92df6c26c1d2063da8fabe
     
        # require github.com/syndtr/goleveldb v1.0.1-0.20190923125748-758128399b1d // indirect
       # will have been added to your go.mod
        ```
    1.  Change the generated `require` statement to a `replace` statement:
        ```
        replace github.com/syndtr/goleveldb => github.com/syndtr/goleveldb v1.0.1-0.20190923125748-758128399b1d
        ```

1. In my local testing I also encountered similar errors for `hclog.Logger`: 
    ```
    &logDelegate literal (type *logDelegate) as type hclog.Logger in field value:
            *logDelegate does not implement hclog.Logger (missing ImpliedArgs method)
    ```
    This is basically the same problem.  To fix, I looked for `hclog` in `vendor.json`, got the `revision` hash, ran `go get`, and changed the resulting `require` statement to a `replace`:
    ```
    replace github.com/hashicorp/go-hclog => github.com/hashicorp/go-hclog v0.9.3-0.20190514033442-f1d61ad5398f
    ```

#### Summary
Doing all this gave me the `go.mod` at the top.

Depending on the quorum packages your app uses, its likely you'll encounter the same issue for other dependencies, but hopefully the method to resolve is explained clearly enough here for you to be able to fix them.  If you do encounter the same issue for other dependencies please let us know and we'll see if there's a better way of replacing the dependencies in bulk.

**Comment by lyonnee** [comment]
@chris-j-h 

Sorry, my English is not very good, but this is how I understand

![image](https://user-images.githubusercontent.com/30852031/89734585-9d275300-da8f-11ea-9edf-789212e5bd43.png)
 
![image](https://user-images.githubusercontent.com/30852031/89734630-dbbd0d80-da8f-11ea-9a47-6625b56ba352.png)

**Comment by lyonnee** [comment]
@chris-j-h 
I think my problem has been solved, thank you very much!

**Comment by chris-j-h** [comment]
Great!  

Just in case anyone encounters the same issues, I'll type out the errors you were getting here so that this post is searchable

unknown field 'DisableSeeksCompaction' in struct literal of type opt.Options

undefined: bind.PrivateTxArgs
