### ISSUE TITLE
quorum examples 

### ISSUE THREAD

**Issue by Mohammed-alzuharey** [Consensys-Incorporated/quorum#1051]
Hi there,
I have problem when run 7nodes example locally on linux  get the output 

waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc
Node 2 is not yet listening on tm.ipc
Node 3 is not yet listening on tm.ipc
Node 4 is not yet listening on tm.ipc
Node 5 is not yet listening on tm.ipc
Node 6 is not yet listening on tm.ipc
Node 7 is not yet listening on tm.ipc
Tessera is taking a long time to start.  Look at the Tessera logs in qdata/logs/ for help diagnosing the problem.
Waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc
Node 2 is not yet listening on tm.ipc
Node 3 is not yet listening on tm.ipc
Node 4 is not yet listening on tm.ipc
Node 5 is not yet listening on tm.ipc
Node 6 is not yet listening on tm.ipc
Node 7 is not yet listening on tm.ipc
Tessera is taking a long time to start.  Look at the Tessera logs in qdata/logs/ for help diagnosing the problem.
Waiting until all Tessera nodes are running...

Can any one help me ?

**Comment by SatpalSandhu61** [comment]
This can be caused by any number of issues. What do you see in the tessera logs (under qdata/logs/).

Also, please supply details of your environment - what OS & version, which version of Java and which version of tessera.
**Note that latest version of Tessera requires JDK 11 (V0.10.2 and earlier use JDK 8).**

**Comment by Mohammed-alzuharey** [comment]
![Screenshot from 2020-08-07 15-16-09](https://user-images.githubusercontent.com/62842470/89655630-4b7d9d80-d8c2-11ea-860d-85bfa0d4896b.png)

OS .Ubunto 20.LTS

Java openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

tessera version 0.10.6

**Comment by SatpalSandhu61** [comment]
You've pasted a picture of the logfiles, which doesn't really help.
What do you see *in* the logfiles? Are there any errors?
If the Tessera process fails to start then it will log an error which will help you determine the issue.

**Comment by Mohammed-alzuharey** [comment]
![Screenshot from 2020-08-07 17-05-52](https://user-images.githubusercontent.com/62842470/89666078-a8cd1b00-d8d1-11ea-827a-d438c1aafa22.png)
![Screenshot from 2020-08-07 17-05-40](https://user-images.githubusercontent.com/62842470/89666081-a9fe4800-d8d1-11ea-8613-b49cdb4f1468.png)
![Screenshot from 2020-08-07 17-05-23](https://user-images.githubusercontent.com/62842470/89666083-aa96de80-d8d1-11ea-8619-17290ad2f565.png)
![Screenshot from 2020-08-07 17-05-05](https://user-images.githubusercontent.com/62842470/89666084-ab2f7500-d8d1-11ea-9714-e2d16d44c69b.png)
![Screenshot from 2020-08-07 17-04-51](https://user-images.githubusercontent.com/62842470/89666086-abc80b80-d8d1-11ea-80d5-e09dfdcd0380.png)
![Screenshot from 2020-08-07 17-04-43](https://user-images.githubusercontent.com/62842470/89666089-ac60a200-d8d1-11ea-976a-8836f1440ac5.png)
![Screenshot from 2020-08-07 17-04-14](https://user-images.githubusercontent.com/62842470/89666091-acf93880-d8d1-11ea-889e-142283a03916.png)

**Comment by SatpalSandhu61** [comment]
Those log screenshots are all from different times and don't all show the part of the log with the error. Without seeing the error I can't help you.
However, I notice a couple of the screenshots show a 'Database already in use' error which suggests that there is already a Tessera process running. I suggest the following:

1. Kill any currently running tessera/geth processes. You can do this by running the 'stop.sh' script.
2. Make sure there are no tessera/geth processes still running. Check this using:
```
ps -ef  | grep -i geth
ps -ef | grep -i tessera
```
If there are any still running then kill them using `kill -9` with the relevant process id.
3. Delete any existing log files `rm qdata/logs/*.log'
4. Restart the 7nodes.
5. If the tessera processes still fail to start, then attach the full log file for tessera 1 to this ticket (qdata/logs/tessera1.log).

**Comment by Mohammed-alzuharey** [comment]
HI sir 
I killed running tessera/geth processes and when run to command it will get 
![Screenshot from 2020-08-08 11-33-08](https://user-images.githubusercontent.com/62842470/89708106-39583980-d96c-11ea-9827-0896e82891d0.png)
x-special/nautilus-clipboard
copy
[tessera1.log](https://github.com/jpmorganchase/quorum/files/5045132/tessera1.log)
this tessera 1.log file to see it ..

**Comment by SatpalSandhu61** [comment]
Ok, so looking at that log file I can see that you started Tessera on node 1 ***four times*** (without stopping any of them):
- First at 2020-08-06 18:22:51.613
- Then again at 2020-08-06 18:55:04.877
- Then again at 2020-08-06 19:56:32.447
- Then again at 2020-08-06 20:26:39.183

Your first attempt started up Tessera fine and it is running. The further three attempts failed as tessera is already running.
So I don't know what you're attempting to do here.

I notice from your screenshot that it says `mohammed@mohammed-VirtualBox`. So, are you attempting to run **locally** or on a virtual machine?

Perhaps you can also paste **exactly** what commands you are running.

**Comment by Mohammed-alzuharey** [comment]
Yes , I use linux os on VirtualBox and I want to run 7nodes example locally . Can do that ?

**Comment by Mohammed-alzuharey** [comment]
OK now it work , but still face error when need to identified the contract address, after run the command in terminal:
> var address = "0x1932c48b2bf8102ba33b4a6b545c32236e342f34"; //replace with your contract address 
get undefined
how to solve that error ?
![Screenshot from 2020-08-08 14-44-12](https://user-images.githubusercontent.com/62842470/89712005-e3908b00-d985-11ea-8b2a-34280b574db8.png)

**Comment by chris-j-h** [comment]
This is a quirk of the javascript console and is not an error - you can continue with the example

(see these answers if you're interested https://stackoverflow.com/questions/22844840/why-does-javascript-variable-declaration-at-console-results-in-undefined-being)

**Comment by Mohammed-alzuharey** [comment]
@chris-j-h 
but when send transaction and need to check it using private.get() the output is 0 this result in any terminal of . the correct get the value 42 
![Screenshot from 2020-08-09 22-41-11](https://user-images.githubusercontent.com/62842470/89742475-3f483a80-da92-11ea-83fc-f72308427ed8.png)
![Screenshot from 2020-08-09 22-42-32](https://user-images.githubusercontent.com/62842470/89742480-4a9b6600-da92-11ea-98b9-1f0d91382f54.png)
how to can fix this issue
thanks

**Comment by SatpalSandhu61** [comment]
Looking at your screenshots, it looks like you've created a contract which is at that "0xe273f..." address. And you are now trying to call that contract.
What you're doing in the screen shot all looks correct. The reason why you are not getting the expected value of `42` could be any of the following:

1. You have the wrong contract address. Are you sure that "0xe273f..." is the correct address where the contract was created? I do notice that this is not the contract address you posted in the earlier screenshots (0x1932...).
2. When the contract was created, it wasn't constructed with an initial value of `42`.
3. The node where you are running `private.get()` isn't a participant of the private transaction.

How did you actually create the contracts? If you paste that here, then it would help.

**Comment by Mohammed-alzuharey** [comment]
Hello @SatpalSandhu61
I repeated it from the beginning and solved the problem , it is now working  
Thank you very much sir
