### ISSUE TITLE
RLPx handshake error in private net

### ISSUE THREAD

**Issue by hagishun** [Consensys-Incorporated/quorum#1056]
I created private network in AWS.
There are two networks.

1st : validator network. There are 7 validator's node. And thease validator are working. BlockNumber is increasing.
2nd: non-validator network. There is only 1 non-validato node. This node will connect 7validators.
(I use ibft)

The two networks have the following configurations.
non-validator -> internet 
     -> NLB(Listener:80,taget:5000) -> nginx proxy(waitng port 5000 and forwarding 30303) -> validator(waiting 30303).

I did this command. But doesn't work.
"enode://6d3fe7806fb71beb306058af7913ab8eae30b6073d1a433dd003592a2429b7c55734f08de694770f08fc15805e0120a0171b2576e49c142f27fb6bd09a5a751d@NLB DNS:80"
admin.peers -> []

I checked the log and gat this message.
TRACE[08-18|15:46:44.872] Failed RLPx handshake                    addr=XX.XX.XX.XX:80 conn=staticdial err=EOF
TRACE[08-18|15:46:44.872] Setting up connection failed             addr=XX.XX.XX.XX:80 err=EOF

Why can't nodes connect?

#### System information
Geth version:Geth/v1.9.7-stable-9339be03(quorum-v2.6.0)/linux-amd64/go1.13.15
OS & Version: Amazon linux2
Branch, Commit Hash or Release: v2.6 latest
#### Expected behaviour
When I typed "admin.addPeer" and "net" command, I got "peerCount: 1"

#### Actual behaviour
When I typed "admin.addPeer" and "net" command, I got "peerCount: 0"
And I got this message
TRACE[08-18|15:46:44.872] Failed RLPx handshake                    addr=XX.XX.XX.XX:80 conn=staticdial err=EOF
TRACE[08-18|15:46:44.872] Setting up connection failed             addr=XX.XX.XX.XX:80 err=EOF

**Comment by fixanoid** [comment]
@hagishun have you been able to resolve this? Generally 99% of RLPx issues are connectivity issues between the nodes.

**Comment by fixanoid** [comment]
Please reopen if further help is required.
