### ISSUE TITLE
require, assert and revert are not working properly

### ISSUE THREAD

**Issue by coolcode** [Consensys-Incorporated/quorum#1061]
Hi, I found an issue while calling a contract's function on quorum: require, assert and revert are not working properly.

quorum: v2.3.0 and v2.7.0
tessera: v0.10.0

solidity code:
```
pragma solidity >=0.4.24 <0.7.0;

contract Simple { 
  uint public v;
  
  function set_v(uint _v) public {
      require(_v<100, "v must be lower than 100");
      v = _v;
  }
}
```

I called 'set_v' and passed an integer value 123 to '_v'. If it did in Ethereum, it will throw an EVM exception: revert v must be lower than 100. But in quorum, it hasn't throw any exception.

This was the similar issue posted on quorum's github page in 2017. But I haven't found any solution.

https://github.com/jpmorganchase/quorum/issues/234
#### System information

Geth version: 
```
Version: 1.9.7-stable
Quorum Version: 2.7.0
Architecture: amd64
Protocol Versions: [64 63]
Network Id: 1337
Go Version: go1.12.5
Operating System: linux
```

OS & Version: `Ubuntu`

Branch, Commit Hash or Release: `v2.3.0 and v2.7.0`

#### Expected behaviour
It will throw an EVM exception: revert v must be lower than 100. 

#### Actual behaviour
But in quorum, it hasn't throw any exception.

#### Steps to reproduce the behaviour
1. deploy an contract to quorum chain
solidity code:
```
pragma solidity >=0.4.24 <0.7.0;

contract Simple { 
  uint public v;
  
  function set_v(uint _v) public {
      require(_v<100, "v must be lower than 100");
      v = _v;
  }
}
```
2. call 'set_v' and pass an integer value 123 to '_v'.

#### Backtrace

````
[backtrace]
````

**Comment by amalrajmani** [comment]
hi @coolcode 
When I tested `Simple` contract with Quorum, `require` worked fine.  I could see the error message `VM returned with error                   err="evm: execution reverted"` in the log file.

Please clarify the below questions to debug this issue further:
1. where are you calling `set_v` method from? (`geth console` or `javascript client` etc)
2. Which component is throwing the exception `EVM exception: revert v must be lower than 100` ? 
3. Give me more details about your genesis and network configuration.

**Comment by coolcode** [comment]
1.  where are you calling `set_v` method from? (`geth console` or `javascript client` etc)  
    python web3.py https://web3py.readthedocs.io/en/stable/
2.  Which component is throwing the exception `EVM exception: revert v must be lower than 100` ?  
    python web3.py https://web3py.readthedocs.io/en/stable/
3.  Give me more details about your genesis and network configuration.  
    genesis.json

{

  "alloc": {

    "0xf14a807e0911391c17fbd8c9d25f4571d4eedc37": {

      "balance": "1000000000000000000000000000"

    },

    "0xfda89e65aae1610321f036e0218bf23e26af5c66": {

      "balance": "1000000000000000000000000000"

    },

    "0x4442fc7faa48ea7d594a661108df50d2a9a6253f": {

      "balance": "1000000000000000000000000000"

    }

  },

  "coinbase": "0x0000000000000000000000000000000000000000",

  "config": {

    "homesteadBlock": 0,

    "byzantiumBlock": 0,

    "constantinopleBlock":0,

    "chainId": 10,

    "eip150Block": 0,

    "eip155Block": 0,

    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",

    "eip158Block": 0,

    "isQuorum":true

  },

  "difficulty": "0x0",

  "extraData": "0x",

  "gasLimit": "0xFFFFFFFFFFFFFFFF",

  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",

  "nonce": "0x0",

  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",

  "timestamp": "0x00"

}

**Comment by ricardolyn** [comment]
@amalrajmani is this still valid? thank you

**Comment by amalrajmani** [comment]
> @amalrajmani is this still valid? thank you

@ricardolyn its not valid anymore.
