### ISSUE TITLE
quorum-wizard select quickstart get error : unexpected end of file

### ISSUE THREAD

**Issue by huahuayu** [Consensys-Incorporated/quorum#1064]
## environment
mac os 10.15.6
node v12.18.3

## problem
`quorum-wizard -q -v` to quickstart get error

```text
error: uncaughtException: unexpected end of file
Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:180:17)
```

![image](https://user-images.githubusercontent.com/1725060/91940621-57764700-ed2a-11ea-89d7-e73b1f365c67.png)

**Comment by bmcd** [comment]
Can you try deleting the /Users/shiming/.quorum-wizard folder and trying again? It's a hidden folder

**Comment by huahuayu** [comment]
hi, I believe it's related to node version (but I didn't test).

I have node version 8.x installed (by hand) and added to PATH, also I have nvm to manage multi version(automaticly),  after I use nvm change node version to 10.0.0, and remove 8.x, the problem is gone.

**Comment by bmcd** [comment]
Yes, nodejs 10+ is required for wizard. I'll update the docs to make that clear
