### ISSUE TITLE
Update links in README.md

### ISSUE THREAD

**Issue by NicolasMassart** [Consensys-Incorporated/quorum#1070]
Quorum README.md has many links pointing to old doc sites.
Update them to the new doc.goquorum and doc.tessera doc sites.

**Comment by ricardolyn** [comment]
only this link https://docs.goquorum.consensys.net/en/latest/Cakeshop/Overview/ of  `Cakeshop: An integrated development environment and SDK for Quorum` seems to be broken

**Comment by NicolasMassart** [comment]
Yes some links were fixed since September. We should have a redirect on the cakeshop one, I will add one in the doc site.
Does redirecting to https://docs.goquorum.consensys.net/HowTo/GetStarted/Cakeshop seem fine for you?

**Comment by ricardolyn** [comment]
yes, that link seems fine.

**Comment by NicolasMassart** [comment]
It's going to redirect to https://docs.goquorum.consensys.net/en/latest/Reference/Cakeshop/GettingStarted/ as it's in reference now.
