### ISSUE TITLE
Deploying private contract with Truffle

### ISSUE THREAD

**Issue by rohitgkr** [Consensys-Incorporated/quorum#108]
I had asked this in the Truffle site but couldn't get a response. Has anyone deployed a private contract using Truffle? If so was it done using any dynamic calls on the deployer object within migrations javascript? There is no documentation around this or even if it is somehow possible? The deployer API in Truffle only takes contructor arguments for the contract. So it appears that there is no way to get this to work.  If someone has figured out a way please let me know how.

**Comment by patrickmn** [comment]
Based on [their docs](http://truffleframework.com/docs/getting_started/contracts):

> Option 1: Send a transaction directly to a contract via instance.sendTransaction(). This is promisified like all available contract instance functions, and has the same API as web3.eth.sendTransaction but without the callback. The to value will be automatically filled in for you if not specified.
> 
> instance.sendTransaction({...}).then(function(result) {
>   // Same transaction result object as above.
> });

If a sendTransaction passthrough is available (is it only for operations on a contract?) it may be possible to specify privateFor=[constellationpubkey1, constellationpubkey2, ...] as an argument, just like in Quorum proper.

**Comment by rohitgkr** [comment]
Thanks @patrickmn. However I don't think that will work because the instance here is the deployed contract. whereas in my case I am looking to deploy a contract using [Truffle migrate](http://truffleframework.com/docs/getting_started/migrations) as a private transaction (so there's no instance yet).

**Comment by tylobban** [comment]
@hermanjunge have you used Truffle on Quorum in your work? Agree with @rohitgkr that this doesn't look to be supported yet.

**Comment by ghost** [comment]
@tylobban Truffle was used in a project. No problems deploying public contracts. @rohitgkr, you need to find a way to add the `privateFor` field using truffle.

**Comment by tylobban** [comment]
The Truffle team have published a post on using Truffle with Quorum, great news! http://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains
