### ISSUE TITLE
How to calculate mixHash in the istanbul concensus?

### ISSUE THREAD

**Issue by movxx** [Consensys-Incorporated/quorum#1084]
I wrote a test case like this：
```
func TestHash(t *testing.T) {
	src := []byte("Istanbul practical byzantine fault tolerance")
	fmt.Printf("sha3 hash : %x\n", Keccak256(src))

	h := sha256.New()
	h.Write(src)
	fmt.Printf("sha256 hash : %x\n", h.Sum(nil))

}
```
And it print this:
```
sha3 hash : 01c335602a9bb4eff135d2e5a063b631bbfd1f589ae13d62ceea41a2732ca2ae
sha256 hash : 92738e249a9ed02e0b062fdc7e3d32a0fcb055a6d0a6879537c5532fad1d0632
```
However，it is not the same as in the code
```
// IstanbulDigest represents a hash of "Istanbul practical byzantine fault tolerance"
// to identify whether the block is from Istanbul consensus engine
IstanbulDigest = common.HexToHash("0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365")
```
So，It confused me，could you please tell me the calculation process.

**Comment by jbhurat** [comment]
Hi @tkblack, you are right, `IstanbulDigest` is not `Keccak256` or `sha256` hash of `Istanbul practical byzantine fault tolerance`. From the original [IBFT EIP](https://github.com/ethereum/EIPs/issues/650), it is a fixed magic number for Istanbul block identification and the original EIP doesn't mention how the hash is derived.

**Comment by jbhurat** [comment]
Closing the issue due to inactivity. Please reopen for any follow up questions or queries.

**Comment by movxx** [comment]
@jbhurat Sorry for the late reply and thanks for your answer.
