### ISSUE TITLE
no mining in raft................

### ISSUE THREAD

**Issue by ssscott2019** [Consensys-Incorporated/quorum#1089]
https://docs.goquorum.consensys.net/en/latest/Tutorials/Creating-A-Network-From-Scratch/
GoQuorum with Raft consensus
new-node-1 it can running, but no mining, what's wrong....

**Comment by vsmk98** [comment]
@ssscott2019 please share the following information:
#### System information

- Geth version: `geth version`
- OS & Version: Windows/Linux/OSX
- Branch, Commit Hash or Release: `git status`
- geth logs
- `genesis.json` and `static-nodes.json` 

Also please check the `geth` logs for any obvious errors.

**Comment by ssscott2019** [comment]
I give up raft, I use istanbul it's ok.
