### ISSUE TITLE
What meaning for this？

### ISSUE THREAD

**Issue by movxx** [Consensys-Incorporated/quorum#1094]
I saw some code in miner/worker.go, line 315:
```
	// commit aborts in-flight transaction execution with given signal and resubmits a new one.
	commit := func(noempty bool, s int32) {
		if interrupt != nil {
			atomic.StoreInt32(interrupt, s)
		}
		interrupt = new(int32)
		w.newWorkCh <- &newWorkReq{interrupt: interrupt, noempty: noempty, timestamp: timestamp}
		timer.Reset(recommit)
		atomic.StoreInt32(&w.newTxs, 0)
	}
        ......
```
What does this "if" do? I don't think it makes sense.
```   
if interrupt != nil {
			atomic.StoreInt32(interrupt, s)
}
```
So, i think `s int32` is also redundant.
Could you please tell me the reason for this, thanks?

**Comment by SatpalSandhu61** [comment]
That anonymous function is used in the `for` loop at line 356 and is called whenever an event is received.
The value of `interrupt` is set if an event is received which interrupts the execution of the transaction. The value of `s` passed into the function gives the type of interrupt.

In any case, this code is picked up from upstream [ethereum](https://github.com/ethereum/go-ethereum/blob/master/miner/worker.go#L345).

**Comment by movxx** [comment]
@SatpalSandhu61 if we `interrupt = new(int32)` , the `interrrupt` will reassignment address and the value is equal to 0.So,the block of `if` is not going to work, and neither will the `s`.
