### ISSUE TITLE
raft.removePeer() can hang if raft network doesn't have consensus

### ISSUE THREAD

**Issue by SatpalSandhu61** [Consensys-Incorporated/quorum#1099]
This ticket replaces  #1096 and gives clearer details of the issue and the cause.

#### System information

Version: 1.9.7-stable
Quorum Version: 20.10.0

#### Observed behaviour

This ticket describes an issue whereby a user called `raft.removePeer()` twice within the same geth console to remove a 'dead' node, and observed that the second call hangs such that any further user input is ignored.

#### Steps to reproduce the behaviour

To reproduce the issue you need to have a raft network with insufficient nodes running to achieve consensus, then try to remove a node from the cluster. For simplicity, the steps below will use a 2 node network.
- Create and start the network with 2 nodes.
- Ensure that both nodes are running as expected and minting. Running `raft.cluster` in a geth console should show both nodes active. One of the nodes will have role "minter", the other one will have role "verifier".
- Kill both nodes.
- Restart node 1 **only**. Running `raft.cluster` in the geth console will now show role as "" as there are insufficient nodes to vote in a minter.
- Now run the following commands in the geth console for node 1:
raft.removePeer(2)              //as expected, this returns null
raft.removePeer(2)              //this will hang

#### Root cause

The etcd raft implementation only allows there to be one raft configuration change pending. Any further requests will wait until the first one completes. In the observed issue, the first `removePeer` request 'sticks' on the queue as there is no minter due to a lack of consensus. Therefore further requests will hang.

You can see this is explicitly described in etcd/raft/node.go:
```
// ProposeConfChange proposes config change.
// At most one ConfChange can be in the process of going through consensus.
// Application needs to call ApplyConfChange when applying EntryConfChange type entry.
ProposeConfChange(ctx context.Context, cc pb.ConfChange) error
```

Configuration change requests are processed using a blocking channel in raft/handler.go ProposePeerRemoval():
```
pm.confChangeProposalC <- raftpb.ConfChange{
   Type:   raftpb.ConfChangeRemoveNode,
   NodeID: uint64(raftId),
}
```

Since the first removePeer is still pending, any further requests will block on the channel.

**Comment by antonydenyer** [comment]
This is a problem that needs to be fixed upstream in https://github.com/etcd-io/etcd/issues/13306 first before we can pull any changes into GoQuorum. The reality is that raft only support crash fault tolerance and not byzantine fault tolerance.
