### ISSUE TITLE
Unlock account error

### ISSUE THREAD

**Issue by chriswsq** [Consensys-Incorporated/quorum#1101]
When unlocking the account, I made a mistake. The password is the password used to create the account. Isn't the password entered to unlock the account the password used to create the account?What is that?

> eth.accounts
["0xed249b11989b12057b2197abad8d1ce597a9d28e"]
> personal.unlockAccount("0xed249b11989b12057b2197abad8d1ce597a9d28e");
Unlock account 0xed249b11989b12057b2197abad8d1ce597a9d28e
Password: 
Error: account unlock with HTTP access is forbidden

**Comment by SatpalSandhu61** [comment]
The issue is not that you entered the wrong password, but that you need to explicitly enable `personal.unlockAccount()` to be executed via HTTP.
In order to enable that, you need to add `--allow-insecure-unlock` on the geth command line when starting up the node.

See: https://github.com/ethereum/go-ethereum/issues/19507#issuecomment-487453981

**Comment by chriswsq** [comment]
There's still a problem


[root@test-2 istanbul-tools]# geth --allow-insecure-unlock attach node0/data/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/v1.9.7-stable-322755c5(quorum-v20.10.0)/linux-amd64/go1.15.1
coinbase: 0xe9b7d16eaf8c1c18f0e1cfcd9833393c910658e5
at block: 569 (Mon, 30 Nov 2020 17:40:45 CST)
 datadir: /bsn/quorum/fromscratchistanbul/istanbul-tools/node0/data
 modules: admin:1.0 debug:1.0 eth:1.0 istanbul:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.accounts
["0xed249b11989b12057b2197abad8d1ce597a9d28e"]
> personal.unlockAccount("0xed249b11989b12057b2197abad8d1ce597a9d28e");
Unlock account 0xed249b11989b12057b2197abad8d1ce597a9d28e
Password: 
Error: account unlock with HTTP access is forbidden
> personal.unlockAccount("0xed249b11989b12057b2197abad8d1ce597a9d28e");
Unlock account 0xed249b11989b12057b2197abad8d1ce597a9d28e
Password: 
Error: account unlock with HTTP access is forbidden

**Comment by SatpalSandhu61** [comment]
You need to set `--allow-insecure-unlock on the geth node itself (i.e. the one you are connecting to, not on the console instance).
