### ISSUE TITLE
Upgrade ethclient and abigen to support privateFor

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#112]
Currently the `privateFor` parameters is supported by the JSON-RPC API. The Go bindings in ethclient and abigen (that uses ethclient under the hood) do not yet.

Depends on: #90

**Comment by stevenroose** [comment]
I'm looking into how hard it is to do.

**Comment by stevenroose** [comment]
Back then, I realised it would be possible once #90 was solved, since abigen primarily relies on sendRawTransaction. Anyone else trying to solve this?

**Comment by conor10** [comment]
I'm planning to take a look at https://github.com/jpmorganchase/quorum/issues/90, unless any of you guys are already @patrickmn? I saw the help wanted label was removed.

**Comment by patrickmn** [comment]
@conor10 Please feel free. I was going to, but haven't started.

**Comment by stevenroose** [comment]
There's two parts of the problem. One is the server, which allowing the sendRawTransaction JSON-RPC call to have a privateFor field somewhere. The other is incorporating that in the ethclient package. The latter should be more straightforward, but makes no sense if the former is not yet done. 

It's not easy to find how and where there were modifications to geth regarding private transactions. F.e. I can only see `private.P.Send` being called with the `data` field being contract code, not when making normal non-deployment transactions. 

Let me open a WIP PR with what I got.

**Comment by patrickmn** [comment]
Regarding modifications, see https://github.com/jpmorganchase/quorum/pull/146#issuecomment-315831913

**Comment by prd-fox** [comment]
This has been implemented in https://github.com/jpmorganchase/quorum/pull/819
