### ISSUE TITLE
Support EIP-155 signatures for private transactions

### ISSUE THREAD

**Issue by alexkoeberl** [Consensys-Incorporated/quorum#1139]
#### System information

Geth version: v20.10.0

OS & Version: Linux

#### Expected behaviour
The following shows the workflow of externally signing transactions and submitting them through the 'eth_sendRaw<Private>Transaction' API.

1) Preparing of transaction data:
Public transaction: The payload (e.g. function call, contract deployment) is directly added to the transaction dictionary.
Private transaction: The hash returned from tessera ('storeraw' API) is used as payload.

2) External signer encodes the transaction dicionary, hashes and signs the data as specified by [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md).

3) Send transaction to Quorum:
Public transaction: eth_sendRawTransaction API
Private transaction: Add static value (e.g. 0xA) to V-value of resulting signature to mark the transaction as private.  Use eth_sendRawPrivateTransaction API.

#### Actual behaviour
In 2) of the expected sequence, the same approach can not be used for both transaction types.
Modifying the V value of an EIP-155 signatuer for a private transaction results in an invalid recovery of the sender address. The transaction will not be mined or already rejected by quorum.

The old hash/signature format needs to be explicitly enforced for private transactions as a workaround.

**Comment by baptiste-b-pegasys** [comment]
It should be solved in the v22.1.0 with geth 1.10.0 merge
