### ISSUE TITLE
constellation error

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#114]
#### System information

Geth version: `geth version` 1.5.0-unstable

OS & Version: Windows/Linux/OSX Linux

Branch, Commit Hash or Release: `git status` 85327f7

#### Actual behaviour
In our 5 nodes quorum setup, we are seeing this errors in the log files when doing private transactions

2017 May-08 14:45:30495777 [WARN] Error performing API request: ApiReceive (Receive {rreqKey = "dRVsr1UpJ4JjSdzskWsBN4H8WVkwKWMPcdDaNO0biLGGEVdZIQ07UFfHjqm0iOXwSsP4sbIhsDruPtUHe/SrVA==", rreqTo = "w/Fpyv4pgHc0mk2cTAyKq9h7y8RioPxy37OrelMTKGY="}); Key not found in BerkeleyDb payload.db

Not sure what exactly this means and how to resolve it.

#### Backtrace

````
[backtrace]
````

**Comment by patrickmn** [comment]
This is the normal warning when a node is trying to fetch a payload it wasn't a party to (that its Constellation node didn't receive.) Are you putting that Constellation node's public key in privateFor?

**Comment by paliwalg** [comment]
I have specified the receipients public key in privateFor and I see this error in the sender’s constellation log.

**Comment by patrickmn** [comment]
Could you please generate throwaway keypairs with `constellation-enclave-keygen` and upload a set of configs that reproduce the issue, e.g. in a [gist](https://gist.github.com/)?
