### ISSUE TITLE
Block validate Problem about Raft-based consensus

### ISSUE THREAD

**Issue by bigstar119** [Consensys-Incorporated/quorum#115]
hi . i have a Block validate Problem about Raft-based consensus to ask.
if leader node mint a new block and send it to follower,but follower validate the block failed(eg.. the leader node was Malicious tampering).   then what will happen?

**Comment by patrickmn** [comment]
Hi @bigstar119,

Currently, the node will panic, stopping the geth process. In the future, we plan to make the handling of that error condition more robust.
