### ISSUE TITLE
Unexpected error when unauthorized node calls a private contract

### ISSUE THREAD

**Issue by vjrantal** [Consensys-Incorporated/quorum#117]
#### System information

Geth version: `geth version`

`Version: 1.5.0-unstable`

OS & Version: Windows/Linux/OSX

OS is `ubuntu/xenial64` and environment setup using https://github.com/jpmorganchase/quorum-examples/blob/master/Vagrantfile.

Branch, Commit Hash or Release: `git status`

Using tag `v1.1.0`.

#### Expected behaviour

When unauthorized node makes a call to a private contract, the return value via the JSON RPC endpoint should be aligned regardless of the function return value type. In https://github.com/jpmorganchase/quorum-examples/blob/afa4986fc36648d68682247464dcf295f826654a/examples/7nodes/README.md#testing-privacy it is expected that when a function with return value type `uint256` is called unauthorized, the return value is 0. If that is the wanted behavior, the return value should probably be an empty string when function is returning a string.

As off-topic to this particular issue, I was thinking whether 0 (or empty string) is the optimal return value for privacy error cases since then, the caller can't determine the difference between a contract function that happened to return 0 (or empty string) and a privacy-related transaction error.

#### Actual behaviour

When function return value type is string, the response via JSON RPC is unexpected and results into `BigNumber Error: new BigNumber() not a base 16 number` when using web3.js.

#### Steps to reproduce the behaviour

Run the test as per https://github.com/vjrantal/telemetry-contract/tree/dbf0438064b2ed1e1a22dd5de2437901de228dbe#testing-with-quorum and observe that this line is hit https://github.com/vjrantal/telemetry-contract/blob/dbf0438064b2ed1e1a22dd5de2437901de228dbe/test/telemetry.js#L96.

#### Backtrace

```
BigNumber Error: new BigNumber() not a base 16 number
```

**Comment by vjrantal** [comment]
After debugging a bit, it seems like this issue might be fixed upstream in go-ethereum and could get fixed after https://github.com/jpmorganchase/quorum/pull/105 is merged.

Leaving here as reference that a diff as follows seems to fix the issue:

```
diff --git a/internal/ethapi/api.go b/internal/ethapi/api.go
index 445685c..bf68855 100644
--- a/internal/ethapi/api.go
+++ b/internal/ethapi/api.go
@@ -660,12 +660,12 @@ type CallArgs struct {
 	Data     string          `json:"data"`
 }
 
-func (s *PublicBlockChainAPI) doCall(ctx context.Context, args CallArgs, blockNr rpc.BlockNumber) (string, *big.Int, error) {
+func (s *PublicBlockChainAPI) doCall(ctx context.Context, args CallArgs, blockNr rpc.BlockNumber) ([]byte, *big.Int, error) {
 	defer func(start time.Time) { glog.V(logger.Debug).Infof("call took %v", time.Since(start)) }(time.Now())
 
 	state, header, err := s.b.StateAndHeaderByNumber(blockNr)
 	if state == nil || err != nil {
-		return "0x", common.Big0, err
+		return nil, common.Big0, err
 	}
 
 	// Set the account address to interact with
@@ -702,24 +702,24 @@ func (s *PublicBlockChainAPI) doCall(ctx context.Context, args CallArgs, blockNr
 	// Execute the call and return
 	vmenv, vmError, err := s.b.GetVMEnv(ctx, msg, state, header)
 	if err != nil {
-		return "0x", common.Big0, err
+		return nil, common.Big0, err
 	}
 	gp := new(core.GasPool).AddGas(common.MaxBig)
 	res, gas, err := core.ApplyMessage(vmenv, msg, gp)
 	if err := vmError(); err != nil {
-		return "0x", common.Big0, err
+		return nil, common.Big0, err
 	}
 	if len(res) == 0 { // backwards compatability
-		return "0x", gas, err
+		return nil, gas, err
 	}
-	return common.ToHex(res), gas, err
+	return res, gas, err
 }
 
 // Call executes the given transaction on the state for the given block number.
 // It doesn't make and changes in the state/blockchain and is usefull to execute and retrieve values.
 func (s *PublicBlockChainAPI) Call(ctx context.Context, args CallArgs, blockNr rpc.BlockNumber) (string, error) {
 	result, _, err := s.doCall(ctx, args, blockNr)
-	return result, err
+	return common.ToHex(result), err
 }
```

**Comment by tylobban** [comment]
@vjrantal hi, thanks for raising this and doing the further digging. Work on 1.6 upgrade is in-flight so will post back when ready.

> As off-topic to this particular issue, I was thinking whether 0 (or empty string) is the optimal return value for privacy error cases since then, the caller can't determine the difference between a contract function that happened to return 0 (or empty string) and a privacy-related transaction error.

Yes this is something that has been discussed internally before and agreed that there is risk in this approach.  Always happy to hear alternative solutions.

On your Telemetry test, looks interesting. We have some planned changes to provide further security around interacting with private contracts so watch this space...

**Comment by vjrantal** [comment]
@tylobban Thanks for your comment - I'll monitor the 1.6 upgrade PR and will test again once it lands.

If you are interested, there is a little bit more information about the telemetry contract available in [my blog post](https://blog.vjrantal.net/2017/05/12/testing-quorum-transaction-privacy-with-truffle/).

**Comment by vjrantal** [comment]
> Yes this is something that has been discussed internally before and agreed that there is risk in this approach. Always happy to hear alternative solutions.

I tend to think it would be better to return one of the [standard errors](https://github.com/ethereum/wiki/blob/master/JSON-RPC-Error-Codes-Improvement-Proposal.md#json-rpc-standard-errors) in case of all permission violations. Perhaps the code of `Invalid Request` with clear description in the `message` property that indicates that the caller tried something that they don't have permission for.

**Comment by sivachaitanya** [comment]
@vjrantal In my case the error is happening when I'm trying to read data from node 3(which is neither blockmaker or voter). The data has been added in node 1(block maker and voter) where I'm able to read it, but trying to get contract instance from contract address that is created in node 1 from node 3 in web3.js started to throw me "BigNumber Error: new BigNumber() not a base 16 number:" error, I've no clue if the contract instance is there on it or I'm unable to access it. NOTE - there is no privatefor between any nodes in my setup so usually I should be able to read data from any node ?

**Comment by patrickmn** [comment]
Please indicate if this is still an issue as of Quorum 2.0.0
