### ISSUE TITLE
Update Docker labelling

### ISSUE THREAD

**Issue by nmvalera** [Consensys-Incorporated/quorum#1170]
#### Summary

This PR update Docker tagging so

|  Docker Tag |       Git Ref      |                                                                                    Comment                                                                                    |
|:-----------:|:------------------:|:-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| YY.MM.Patch | tag YY.MM.Patch    | Image is created when pushing git tag YY.MM.Patch and then it is never overridden                                                                                             |
| YY.MM       | latest tag YY.MM.* | Image is created for the first time when pushing git tag YY.MM.0 then it is overridden on every new YY.MM.* git tag Once bumping to YY’.MM’.0 image is not overridden anymore |
| latest      | latest tag         | Image is built for the first time when pushing first git tag then it is overridden on every new git tag                                                                       |
| develop     | master             | Image is built for the first time when pushing to master then is overridden on every new push/merge into master                                                               |

**Comment by ricardolyn** [comment]
looks good
