### ISSUE TITLE
Add GasFee in the GoQuorum does not work

### ISSUE THREAD

**Issue by Xen0n6291** [Consensys-Incorporated/quorum#1176]
Hi there,

I would like to add GasFee in GoQuorum setup i used the 7-node example with quorum-wizard from: (https://docs.goquorum.consensys.net/en/stable/HowTo/GetStarted/Wizard/GettingStarted/)

I put this setup on 7 Servers (VMs) around the world. 
I can now make free transactions to the network with my own etherium wallet (metamask). (after I transferd funds to my eth wallet form one of the nodes wallets)

I don't see any option to add a GasFee, because with a setup like this anyone can send transactions and spam my network.

I dont find anything in the offical documentation about this.

**Comment by prd-fox** [comment]
GoQuorum networks do not use a gas fee - it is briefly mentioned [here](https://docs.goquorum.consensys.net/en/stable/Concepts/Architecture/).
A GoQuorum network is expected to run in a permissioned environment, where the users of the private network are known and so it is not likely that one of them will be maliciously spamming transactions.

If it could still be the case that one them could spam transactions, then using the [enhanced permissioning system](https://docs.goquorum.consensys.net/en/stable/Concepts/Permissioning/Enhanced/EnhancedPermissionsOverview/) will allow users to see who the offender is, and take action as appropriate (e.g. removing them from the network, revoking the ability to send transactions etc).

**Comment by cppfuns** [comment]
If it is really needed, how can I support it?

**Comment by antonydenyer** [comment]
This is not currently supported in GoQuorum at the moment. It may be added in the future. Alternatively, you can use https://besu.hyperledger.org/ to create a private network that has gas enabled.

**Comment by antonydenyer** [comment]
Gas was added/renabled in https://github.com/ConsenSys/quorum/releases/tag/v22.7.0
