### ISSUE TITLE
CAKESHOP "DASHBOARD" Public Access Problem // security problem

### ISSUE THREAD

**Issue by Xen0n6291** [Consensys-Incorporated/quorum#1177]
Hi there,

I installed 7-node-example via quorum-wizard and put it on public vps.

No I have a general security problem with CAKESHOP i can install "CAKESHOP "DASHBOARD" on any server outside the network and just add the nodes. 

When i do so i can add peers and spend the Nodes wallet how I want. What is the concept with this. Is there a possiblity to secure this. 
Because anyone could install CAKESHOP "DASHBOARD at his server/computer and make stuff in my networks nodes.  

Sorry for the Quesion but i don't see anything in the documenation. Or do i use Quorum wrong.

**Comment by prd-fox** [comment]
You are right, but that should not be how a system should be set up in a production environment.

Cakeshop makes good use of the RPC APIs, and they should not be exposed directly to the Internet.
Using some controls, such as adding a reverse proxy with some sort of auth, or creating a security group (e.g. on AWS) to specify where traffic should be accepted from.
