### ISSUE TITLE
upload latest version badge in README

### ISSUE THREAD

**Issue by trung** [Consensys-Incorporated/quorum#1183]
Fix the badge (to  use cloudsmith) in README.md in quorum repo. However, it’s tricky as it seems with current raw repo setup in Cloudsmith, we can’t obtain latest version dynamically.

**Comment by antonydenyer** [comment]
This is a real pain :smile: been looking through the docs for cloudsmith and there's no nice way to do this without scripting. I've removed the link from the readme and suspect most people use docker anyway.
