### ISSUE TITLE
Issue in a quorum production network while adding a new node

### ISSUE THREAD

**Issue by Purbaja** [Consensys-Incorporated/quorum#1191]
In a running production network we suddenly facing problem while adding a new node. Here are the steps we did -
1.A PRD Quorum node (single node in a network) that was running since last 6 months, say X
2We wanted to add a new Quorum node (say Y) in the same Quorum network (same chainId etc.), but while doing that the peering failed i.e. the raft peering happened but admin.peers did not return anything. This was due to the nodes in different Docker version
3.A raft node (raftId - 2) was added to the cluster but it complained that it cannot find the peer in the logs
4.We tried to do raft.removePeer(2); but it failed. Error -"propose conf type:EntryConfChange Data \..\.. ignored since pending unapplied configuration"
5.We tried to add a THIRD new node (say Z), that also did not go through. Please see the log below
Log statement in Leader node X
"propose conf Type:EntryConfChange Data:"\010\025\020\001\030\002" ignored since pending unapplied configuration"
Log in third node (Z)
err="no leader is currently  elected"
6. Having said all this, the leader node is still active and when we run the command raft.leader in node X, we can see a value being returned while doing "raft.leader"

So, what we wanted to know, how can we remove the dead raft node from the raft cluster. And what can be the possible reason we faced this issue.

**Comment by MadelineMurray** [comment]
hi @Purbaja - wanted to confirm you're still having this issue before looking into it.  Thanks

**Comment by abhib3012** [comment]
Hi @MadelineMurray :

I see many are facing this issue of not being able to remove dead raft nodes from a cluster. Please clarify.

**Comment by ricardolyn** [comment]
@Purbaja could you let us know if this issue is still present? that will helps us prioritise it for investigation. thank you

**Comment by Purbaja** [comment]
@ricardolyn yes the issue is still open

**Comment by Purbaja** [comment]
Additionial info -

when we tried restarting the quorum node got below error - 

Add peer result {"jsonrpc":"2.0","id":3,"result":3}
INFO [10-07|09:53:20.096] Maximum peer count                       ETH=50 LES=0 total=50
INFO [10-07|09:53:20.096] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
ERROR[10-07|09:53:20.097] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-07|09:53:20.097] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-07|09:53:20.097] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=1 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-07|09:53:20.097] Failed to enumerate USB devices          hub=ledger vendor=11415 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-07|09:53:20.097] Failed to enumerate USB devices          hub=trezor vendor=21324 failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
ERROR[10-07|09:53:20.097] Failed to enumerate USB devices          hub=trezor vendor=4617  failcount=2 err="failed to initialize libusb: libusb: unknown error [code -99]"
INFO [10-07|09:53:20.097] Allocated cache and file handles         database=/qdata/dd/geth/chaindata cache=16.00MiB handles=16
INFO [10-07|09:53:20.123] Persisted trie from memory database      nodes=7 size=1.02KiB time=40.9µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [10-07|09:53:20.124] Successfully wrote genesis state         database=chaindata                hash=6a6605…6243a2
INFO [10-07|09:53:20.124] Allocated cache and file handles         database=/qdata/dd/geth/lightchaindata cache=16.00MiB handles=16
INFO [10-07|09:53:20.152] Persisted trie from memory database      nodes=7 size=1.02KiB time=34.6µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [10-07|09:53:20.152] Successfully wrote genesis state         database=lightchaindata                hash=6a6605…6243a2
WARN [10-07|09:53:20.213] Using deprecated resource file /qdata/dd/nodekey, please move this file to the 'geth' subdirectory of datadir.
WARN [10-07|09:53:20.213] Found deprecated node list file /qdata/dd/static-nodes.json, please use the TOML config file instead.
WARN [10-07|09:53:20.249] Ethash used in full fake mode
WARN [10-07|09:53:20.375] Using deprecated resource file /qdata/dd/nodekey, please move this file to the 'geth' subdirectory of datadir.
WARN [10-07|09:53:20.375] Found deprecated node list file /qdata/dd/static-nodes.json, please use the TOML config file instead.
WARN [10-07|09:53:20.434] Removing static dial candidate           id=0x9981c0 addr=23.97.142.219:21001 err="is self"
raft2021/10/07 09:53:20.439996 INFO: newRaft storagehardState{1 0 0 []} confState{[] [] []}
raft2021/10/07 09:53:20.440021 INFO: newRaft config.peers[] config.learners[]
raft2021/10/07 09:53:20.440680 INFO: 3 became follower at term 1
raft2021/10/07 09:53:20.440710 INFO: newRaft 3 learner: false [peers: [], term: 1, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
WARN [10-07|09:53:20.443] -------------------------------------------------------------------
WARN [10-07|09:53:20.443] Referring to accounts by order in the keystore folder is dangerous!
WARN [10-07|09:53:20.443] This functionality is deprecated and will be removed in the future!
WARN [10-07|09:53:20.443] Please use explicit addresses! (can search via `geth account list`)
WARN [10-07|09:53:20.443] -------------------------------------------------------------------



Request you to look into this issue and help with a solution.

**Comment by antonydenyer** [comment]
This is a problem that needs to be fixed upstream in https://github.com/etcd-io/etcd/issues/13306 first before we can pull any changes into GoQuorum. The reality is that raft only supports crash fault tolerance and not byzantine fault tolerance.
