### ISSUE TITLE
Missing header from ancient or level db should not be logged as error

### ISSUE THREAD

**Issue by jbhurat** [Consensys-Incorporated/quorum#1193]
In `core/rawdb/accessors_chain.go::ReadHeader()` if the call to `readHeaderRLP()` returns `nil` header it is logged as an `error`. This should be not logged as an `error` as it is completely valid to not have a recent header in ancient or level db. 

Consider the scenario where a block was just mined on node 1 and the block was propagated to node 2, `block_fetcher.go::importBlocks()` spawns a goroutine to import/insert this block.  As part of the insert, it checks if the block header is present in ancient/level db, which obviously is not the case. An error `Invalid block header RLP`, is then logged and the `block_fetcher.go::importBlocks()` continues with the block insertion.

The log in question is https://github.com/ConsenSys/quorum/blob/c862562528104dfd3c266771d30c3e645be6f8a7/core/rawdb/accessors_chain.go#L342

**Comment by ricardolyn** [comment]
checking the original code from `geth` then we should check if the data len==0 to return `nil` and don't show the error: https://github.com/ConsenSys/quorum/blob/v21.4.0/core/rawdb/accessors_chain.go#L308

does it make sense?

**Comment by jbhurat** [comment]
Yeah that makes sense, currently we are ignoring `data`, we can check it and if it is `nil` then don't show the error
