### ISSUE TITLE
[MPS][Plugin] x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by preetanandvakt** [Consensys-Incorporated/quorum#1200]
**Geth**
Geth
Version: 1.9.20-stable
Quorum Version: 21.4.2
Architecture: amd64
Protocol Versions: [65 64 63]
Network Id: 1337
Go Version: go1.15.5
Operating System: linux
GOPATH=
GOROOT=go

Tessera
21.4.1

**Actual Behaviour**

2021-05-20 10:34:17,032 DEBG 'geth' stdout output:
INFO [05-20|10:34:17.031] extension service registered
INFO [05-20|10:34:17.031] Starting all plugins                     count=1
INFO [05-20|10:34:17.031] Starting plugin                          provider=security plugin=quorum-security-plugin-enterprise version=0.1.2
DEBUG[05-20|10:34:17.031] Starting plugin: Loading                 provider=security plugin=quorum-security-plugin-enterprise version=0.1.2

2021-05-20 10:34:17,033 DEBG 'geth' stdout output:
DEBUG[05-20|10:34:17.032] checking plugin zip file                 path=/quorum/plugins/quorum-security-plugin-enterprise-0.1.2-linux-amd64.zip exist=true

2021-05-20 10:34:17,036 DEBG 'geth' stdout output:
INFO [05-20|10:34:17.035] verifying plugin integrity               provider=security plugin=quorum-security-plugin-enterprise version=0.1.2 checksum=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
DEBUG[05-20|10:34:17.035] downloading plugin signature file        url=https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.2/quorum-security-plugin-enterprise-0.1.2-linux-amd64-sha256.checksum.asc

2021-05-20 10:34:17,690 DEBG 'geth' stdout output:
DEBUG[05-20|10:34:17.690] download completed                       url=https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.2/quorum-security-plugin-enterprise-0.1.2-linux-amd64-sha256.checksum.asc err="Get \"https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.2/quorum-security-plugin-enterprise-0.1.2-linux-amd64-sha256.checksum.asc\": x509: certificate signed by unknown authority" took=654.804756ms
ERROR[05-20|10:34:17.690] Plugin failed to start                   provider=security plugin=quorum-security-plugin-enterprise version=0.1.2 error="unable to verify plugin signature: Get \"https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.2/quorum-security-plugin-enterprise-0.1.2-linux-amd64-sha256.checksum.asc\": x509: certificate signed by unknown authority" took=658.568233ms

**Further Debugging**

Tried accessing the certs for the server to manually add it to the docker image (alpine)

Command
openssl s_client -connect artifacts.consensys.net:443  -showcerts

Response

CONNECTED(00000007)
4429250156:error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.140.1/libressl-2.8/ssl/ssl_pkt.c:386:

no peer certificate available

No client certificate CA names sent

SSL handshake has read 5 bytes and written 0 bytes

New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
Protocol  : TLSv1.2
Cipher    : 0000
Session-ID:
Session-ID-ctx:
Master-Key:
Start Time: 1621506967
Timeout   : 7200 (sec)
Verify return code: 0 (ok)

**Comment by preetanandvakt** [comment]
**Further PGP issues** 

2021-05-20 12:31:46,082 DEBG 'geth' stdout output:
DEBUG[05-20|12:31:46.081] download completed                       url=https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.1/quorum-security-plugin-enterprise-0.1.1-linux-amd64-sha256.checksum.asc err=nil took=227.12558ms
DEBUG[05-20|12:31:46.081] downloading public key                   url=https://artifacts.consensys.net/public/quorum-go-plugins/gpg.key

2021-05-20 12:31:46,160 DEBG 'geth' stdout output:
DEBUG[05-20|12:31:46.159] download completed                       url=https://artifacts.consensys.net/public/quorum-go-plugins/gpg.key err=nil took=77.600291ms

2021-05-20 12:31:46,161 DEBG 'geth' stdout output:
DEBUG[05-20|12:31:46.161] unable to verify signature with original checksum. Now add \n to the end and try checksum=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 error="openpgp: invalid signature: hash tag doesn't match"

2021-05-20 12:31:46,162 DEBG 'geth' stdout output:
ERROR[05-20|12:31:46.161] Plugin failed to start                   provider=security plugin=quorum-security-plugin-enterprise version=0.1.1 error="unable to verify plugin signature: openpgp: invalid signature: hash tag doesn't match" took=310.126306ms

**Comment by trung** [comment]
@preetanandvakt are you using docker image or binary?

**Comment by preetanandvakt** [comment]
I am using binary build from source for quorum v21.4.2. Its getting built in golang:1.15.5-alpine base and getting used in alpine:3.12 base

**Comment by trung** [comment]
@preetanandvakt thanks.

For the issue with `x509: certificate signed by unknown authority`, can you try to update ca certificates in your VM? It could be that the CA store doesn't include the latest CA which is used for `artifacts.consensys.net` cert.
Also, for `openssl` command, you need to have additional argument to show the cert correctly. i.e.: 

```
openssl s_client -connect artifacts.consensys.net:443 -showcerts -servername artifacts.consensys.net
```

For the second issue with GPG signature verification, can you use plugin version 0.1.2 binary and try?
I'll double check the 0.1.1 to see why the signature not matched with our signing key.

**Comment by preetanandvakt** [comment]
CA cert was a straightforward one. That's good.

Tried v0.1.2, same issue

2021-05-20 14:09:39,706 DEBG 'privacy_manager' stdout output:
2021-05-20 14:09:39.706 [pool-3-thread-1] INFO  c.q.t.p.p.PartyInfoBroadcaster - Finished PartyInfo polling round

2021-05-20 14:09:40,419 DEBG 'geth' stdout output:
DEBUG[05-20|14:09:40.418] download completed                       url=https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.2/quorum-security-plugin-enterprise-0.1.2-linux-amd64-sha256.checksum.asc err=nil took=2.206342531s
DEBUG[05-20|14:09:40.419] downloading public key                   url=https://artifacts.consensys.net/public/quorum-go-plugins/gpg.key

2021-05-20 14:09:40,818 DEBG 'privacy_manager' stdout output:
2021-05-20 14:09:40.818 [qtp2130054146-28] INFO  c.q.t.api.common.UpCheckResource - Enter Request : GET : /upcheck

2021-05-20 14:09:40,820 DEBG 'privacy_manager' stdout output:
2021-05-20 14:09:40.819 [qtp2130054146-28] INFO  c.q.t.api.common.UpCheckResource - GET upcheck

2021-05-20 14:09:40,822 DEBG 'privacy_manager' stdout output:
2021-05-20 14:09:40.821 [qtp2130054146-28] INFO  c.q.t.api.common.UpCheckResource - Exit Request : GET : /upcheck
2021-05-20 14:09:40.821 [qtp2130054146-28] INFO  c.q.t.api.common.UpCheckResource - Response for upcheck : 200 OK

2021-05-20 14:09:41,140 DEBG 'geth' stdout output:
DEBUG[05-20|14:09:41.139] download completed                       url=https://artifacts.consensys.net/public/quorum-go-plugins/gpg.key err=nil took=720.604221ms

2021-05-20 14:09:41,142 DEBG 'geth' stdout output:
DEBUG[05-20|14:09:41.141] unable to verify signature with original checksum. Now add \n to the end and try checksum=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 error="openpgp: invalid signature: hash tag doesn't match"

2021-05-20 14:09:41,144 DEBG 'geth' stdout output:
ERROR[05-20|14:09:41.142] Plugin failed to start                   provider=security plugin=quorum-security-plugin-enterprise version=0.1.2 error="unable to verify plugin signature: openpgp: invalid signature: hash tag doesn't match" took=2.934458234s

2021-05-20 14:09:44,709 DEBG 'privacy_manager' stdout output:
2021-05-20 14:09:44.707 [pool-3-thread-1] INFO  c.q.t.p.p.PartyInfoBroadcaster - Started PartyInfo polling round

**Comment by trung** [comment]
From the log, I can see that checksums of 0.1.1 and 0.1.2 are the same: `e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855` and it's not the correct checksum either.

```
› curl https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.2/quorum-security-plugin-enterprise-0.1.2-linux-amd64-sha256.checksum
a3422511bbf4b85b66a89472c5473dbf2cef8dfd9da8d421a9a6d880ec4a442f

> curl https://artifacts.consensys.net/public/quorum-go-plugins/maven/bin/quorum-security-plugin-enterprise/0.1.1/quorum-security-plugin-enterprise-0.1.1-linux-amd64-sha256.checksum
0b4a8ba08ccfce06248c6fe43488d4606e7cae6df4c64ce13741e97bbfb1a4ee
```

Can you make sure you see the plugin is freshly downloaded instead of using cached one? You can delete the `plugins` folder under `<data_dir>`.

**Comment by preetanandvakt** [comment]
Gone past that. v0.1.2 works. Can close this ticket. I will raise others if there are more issues
