### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cuongtv-0172** [Consensys-Incorporated/quorum#1210]
Dear team, 
I've built a GoQuorum network on local machine with GoQuorumWizard (7 nodes) with this guide: https://docs.goquorum.consensys.net/en/stable/HowTo/GetStarted/Wizard/GettingStarted/ . 
I've monitor my machine with 4vCPU and 32G RAM and doesn't have any alarm for overload RAM or CPU for server. It's always from 20% CPU and 20% RAM utilizations. But I've checked log containers tessera have many lines with OOM like this. 
 
```
{"log":"2021-05-20 03:15:28.332 [qtp198024918-228591] WARN  o.e.j.u.t.strategy.EatWhatYouKill - \n","stream":"stdout","time":"2021-05-20T03:15:28.332348656Z"}
{"log":"java.lang.OutOfMemoryError: Java heap space\n","stream":"stdout","time":"2021-05-20T03:15:28.332361906Z"}
{"log":"Exception in thread \"pool-2-thread-6\" java.lang.OutOfMemoryError: Java heap space\n","stream":"stderr","time":"2021-05-20T03:15:28.332405507Z"}
{"log":"Exception in thread \"pool-1-thread-1\" java.lang.OutOfMemoryError: Java heap space\n","stream":"stderr","time":"2021-05-20T03:15:28.332644809Z"}
```

Do you have any solution for this? 

Thanks all for help!

#### System information

OS & Version: Ubuntu 16.04
Docker-compose with GoQuorumWizard

**Comment by ricardolyn** [comment]
Issue moved to [ConsenSys/tessera #1300](https://github.com/ConsenSys/tessera/issues/1300) via [**ZenHub**](https://www.zenhub.com/)
