### ISSUE TITLE
Error migrating contracts using Truffle to AWS EC2 hosted Quorum

### ISSUE THREAD

**Issue by kallolborah** [Consensys-Incorporated/quorum#1212]
Hi
I followed the [instructions here](https://docs.goquorum.consensys.net/en/stable/Tutorials/Create-IBFT-Network/) to set up a IBFT based node on an Amazon AWS EC2 instance. 

However, when I deploy contracts using Truffle, I get this error
```
D:\Code\verified-payments-quorum\node_modules\request\request.js:848
          var e = new Error('ETIMEDOUT')
                  ^
Error: PollingBlockTracker - encountered an error while attempting to update latest block:
Error: ETIMEDOUT
    at Timeout.<anonymous> (D:\Code\verified-payments-quorum\node_modules\request\request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
    at PollingBlockTracker._performSync (D:\Code\verified-payments-quorum\node_modules\eth-block-tracker\src\polling.js:51:24)  
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

My truffle config is as follows 

```
test: {
            provider: () => new HDWalletProvider(mnemonic, "https://EC2 public IP"),
            port: 22000,
            network_id: "*",
            gasPrice: 0,
            gas:4500000,
            timeoutBlocks: 200, 
            networkCheckTimeout: 10000000
            type: "quorum"
        },
```

Quorum nodes were set up first on 127.0.0.1 and I also tried setting them up on EC2 private IP address (mapped to the public IP address) as I thought that perhaps there is an issue accessing the Quorum nodes using the EC2 public IP ? However, nothing has worked. 

#### System information

Truffle v5.1.6
Node v14.15.3
web3 v1.2.9
HDWallet v1.2.6
EC2 instance: Geth/v1.9.20-stable-f6612bd0(quorum-v21.4.2)/linux-amd64/go1.15.8

**Comment by antonydenyer** [comment]
I suspect that this is related to a certificate error when connecting over https. You probably need to configure truffle to ignore certificate errors when connecting. 

Try connecting with `geth attach https://EC2 public IP:port --rpcclitls.insecureskipverify` first.
