### ISSUE TITLE
util.go:45: exit status 1 when run "make test" command

### ISSUE THREAD

**Issue by abloxity01** [Consensys-Incorporated/quorum#1222]
Hello good evening, I am trying to install the git consensys quorum, I clone it, I do the make all.
I export to the path variable that takes the binaries, but when testing, I get the following error.

If I get this error, can I continue creating the istanbul network?
I am using the version of go 1.13.3 of linux, everything will be for the linux server environment

alexleo@bloxity:~/quorum/quorum$ make test
env GO111MODULE=on go run build/ci.go install
>>> /usr/local/go/bin/go install -ldflags -X main.gitCommit=d543cd6a7e0606438ed872a1e2071bae0                                                                                                19eb554 -X main.gitDate=20210621 -trimpath -v ./...
env GO111MODULE=on go run build/ci.go test
>>> /usr/local/go/bin/go test -ldflags -X main.gitCommit=d543cd6a7e0606438ed872a1e2071bae019e                                                                                                b554 -X main.gitDate=20210621 -p 1 --short github.com/ethereum/go-ethereum github.com/ethereu                                                                                                m/go-ethereum/accounts github.com/ethereum/go-ethereum/accounts/abi github.com/ethereum/go-et                                                                                                hereum/accounts/abi/bind github.com/ethereum/go-ethereum/accounts/abi/bind/backends github.co                                                                                                m/ethereum/go-ethereum/accounts/external github.com/ethereum/go-ethereum/accounts/keystore gi                                                                                                thub.com/ethereum/go-ethereum/accounts/pluggable github.com/ethereum/go-ethereum/accounts/plu                                                                                                ggable/internal/testutils github.com/ethereum/go-ethereum/accounts/pluggable/internal/testuti                                                                                                ls/mock_plugin github.com/ethereum/go-ethereum/accounts/scwallet github.com/ethereum/go-ether                                                                                                eum/accounts/usbwallet github.com/ethereum/go-ethereum/accounts/usbwallet/trezor github.com/e                                                                                                thereum/go-ethereum/cmd/abidump github.com/ethereum/go-ethereum/cmd/abigen github.com/ethereu                                                                                                m/go-ethereum/cmd/bootnode github.com/ethereum/go-ethereum/cmd/checkpoint-admin github.com/et                                                                                                hereum/go-ethereum/cmd/clef github.com/ethereum/go-ethereum/cmd/devp2p github.com/ethereum/go                                                                                                -ethereum/cmd/devp2p/internal/ethtest github.com/ethereum/go-ethereum/cmd/devp2p/internal/v4t                                                                                                est github.com/ethereum/go-ethereum/cmd/devp2p/internal/v5test github.com/ethereum/go-ethereu                                                                                                m/cmd/ethkey github.com/ethereum/go-ethereum/cmd/evm github.com/ethereum/go-ethereum/cmd/evm/                                                                                                internal/compiler github.com/ethereum/go-ethereum/cmd/evm/internal/t8ntool github.com/ethereu                                                                                                m/go-ethereum/cmd/faucet github.com/ethereum/go-ethereum/cmd/geth github.com/ethereum/go-ethe                                                                                                reum/cmd/p2psim github.com/ethereum/go-ethereum/cmd/puppeth github.com/ethereum/go-ethereum/c                                                                                                md/rlpdump github.com/ethereum/go-ethereum/cmd/utils github.com/ethereum/go-ethereum/common g                                                                                                ithub.com/ethereum/go-ethereum/common/bitutil github.com/ethereum/go-ethereum/common/compiler                                                                                                 github.com/ethereum/go-ethereum/common/fdlimit github.com/ethereum/go-ethereum/common/hexuti                                                                                                l github.com/ethereum/go-ethereum/common/http github.com/ethereum/go-ethereum/common/math git                                                                                                hub.com/ethereum/go-ethereum/common/mclock github.com/ethereum/go-ethereum/common/prque githu                                                                                                b.com/ethereum/go-ethereum/consensus github.com/ethereum/go-ethereum/consensus/clique github.                                                                                                com/ethereum/go-ethereum/consensus/ethash github.com/ethereum/go-ethereum/consensus/istanbul                                                                                                 github.com/ethereum/go-ethereum/consensus/istanbul/backend github.com/ethereum/go-ethereum/co                                                                                                nsensus/istanbul/core github.com/ethereum/go-ethereum/consensus/istanbul/validator github.com                                                                                                /ethereum/go-ethereum/consensus/misc github.com/ethereum/go-ethereum/console github.com/ether                                                                                                eum/go-ethereum/console/prompt github.com/ethereum/go-ethereum/contracts/checkpointoracle git                                                                                                hub.com/ethereum/go-ethereum/contracts/checkpointoracle/contract github.com/ethereum/go-ether                                                                                                eum/core github.com/ethereum/go-ethereum/core/asm github.com/ethereum/go-ethereum/core/bloomb                                                                                                its github.com/ethereum/go-ethereum/core/forkid github.com/ethereum/go-ethereum/core/mps gith                                                                                                ub.com/ethereum/go-ethereum/core/rawdb github.com/ethereum/go-ethereum/core/state github.com/                                                                                                ethereum/go-ethereum/core/state/snapshot github.com/ethereum/go-ethereum/core/types github.co                                                                                                m/ethereum/go-ethereum/core/vm github.com/ethereum/go-ethereum/core/vm/runtime github.com/eth                                                                                                ereum/go-ethereum/crypto github.com/ethereum/go-ethereum/crypto/blake2b github.com/ethereum/g                                                                                                o-ethereum/crypto/bls12381 github.com/ethereum/go-ethereum/crypto/bn256 github.com/ethereum/g                                                                                                o-ethereum/crypto/bn256/cloudflare github.com/ethereum/go-ethereum/crypto/bn256/google github                                                                                                .com/ethereum/go-ethereum/crypto/ecies github.com/ethereum/go-ethereum/eth github.com/ethereu                                                                                                m/go-ethereum/eth/downloader github.com/ethereum/go-ethereum/eth/fetcher github.com/ethereum/                                                                                                go-ethereum/eth/filters github.com/ethereum/go-ethereum/eth/gasprice github.com/ethereum/go-e                                                                                                thereum/eth/tracers github.com/ethereum/go-ethereum/eth/tracers/internal/tracers github.com/e                                                                                                thereum/go-ethereum/ethclient github.com/ethereum/go-ethereum/ethdb github.com/ethereum/go-et                                                                                                hereum/ethdb/dbtest github.com/ethereum/go-ethereum/ethdb/leveldb github.com/ethereum/go-ethe                                                                                                reum/ethdb/memorydb github.com/ethereum/go-ethereum/ethstats github.com/ethereum/go-ethereum/                                                                                                event github.com/ethereum/go-ethereum/extension github.com/ethereum/go-ethereum/extension/ext                                                                                                ensionContracts github.com/ethereum/go-ethereum/extension/privacyExtension github.com/ethereu                                                                                                m/go-ethereum/graphql github.com/ethereum/go-ethereum/internal/build github.com/ethereum/go-e                                                                                                thereum/internal/cmdtest github.com/ethereum/go-ethereum/internal/debug github.com/ethereum/g                                                                                                o-ethereum/internal/ethapi github.com/ethereum/go-ethereum/internal/flags github.com/ethereum                                                                                                /go-ethereum/internal/guide github.com/ethereum/go-ethereum/internal/jsre github.com/ethereum                                                                                                /go-ethereum/internal/jsre/deps github.com/ethereum/go-ethereum/internal/plugin github.com/et                                                                                                hereum/go-ethereum/internal/testlog github.com/ethereum/go-ethereum/internal/utesting github.                                                                                                com/ethereum/go-ethereum/internal/web3ext github.com/ethereum/go-ethereum/les github.com/ethe                                                                                                reum/go-ethereum/les/checkpointoracle github.com/ethereum/go-ethereum/les/flowcontrol github.                                                                                                com/ethereum/go-ethereum/les/lespay/client github.com/ethereum/go-ethereum/les/lespay/server                                                                                                 github.com/ethereum/go-ethereum/les/utils github.com/ethereum/go-ethereum/light github.com/et                                                                                                hereum/go-ethereum/log github.com/ethereum/go-ethereum/metrics github.com/ethereum/go-ethereu                                                                                                m/metrics/exp github.com/ethereum/go-ethereum/metrics/influxdb github.com/ethereum/go-ethereu                                                                                                m/metrics/librato github.com/ethereum/go-ethereum/metrics/prometheus github.com/ethereum/go-e                                                                                                thereum/miner github.com/ethereum/go-ethereum/mobile github.com/ethereum/go-ethereum/multiten                                                                                                ancy github.com/ethereum/go-ethereum/node github.com/ethereum/go-ethereum/p2p github.com/ethe                                                                                                reum/go-ethereum/p2p/discover github.com/ethereum/go-ethereum/p2p/discover/v4wire github.com/                                                                                                ethereum/go-ethereum/p2p/discover/v5wire github.com/ethereum/go-ethereum/p2p/discv5 github.co                                                                                                m/ethereum/go-ethereum/p2p/dnsdisc github.com/ethereum/go-ethereum/p2p/enode github.com/ether                                                                                                eum/go-ethereum/p2p/enr github.com/ethereum/go-ethereum/p2p/nat github.com/ethereum/go-ethere                                                                                                um/p2p/netutil github.com/ethereum/go-ethereum/p2p/nodestate github.com/ethereum/go-ethereum/                                                                                                p2p/rlpx github.com/ethereum/go-ethereum/p2p/simulations github.com/ethereum/go-ethereum/p2p/                                                                                                simulations/adapters github.com/ethereum/go-ethereum/p2p/simulations/examples github.com/ethe                                                                                                reum/go-ethereum/p2p/simulations/pipes github.com/ethereum/go-ethereum/params github.com/ethe                                                                                                reum/go-ethereum/permission github.com/ethereum/go-ethereum/permission/core github.com/ethere                                                                                                um/go-ethereum/permission/core/types github.com/ethereum/go-ethereum/permission/v1 github.com                                                                                                /ethereum/go-ethereum/permission/v1/bind github.com/ethereum/go-ethereum/permission/v1/contra                                                                                                ct/gen github.com/ethereum/go-ethereum/permission/v2 github.com/ethereum/go-ethereum/permissi                                                                                                on/v2/bind github.com/ethereum/go-ethereum/permission/v2/contract/gen github.com/ethereum/go-                                                                                                ethereum/plugin github.com/ethereum/go-ethereum/plugin/account github.com/ethereum/go-ethereu                                                                                                m/plugin/account/internal/testutils github.com/ethereum/go-ethereum/plugin/gen github.com/eth                                                                                                ereum/go-ethereum/plugin/gen/proto_common github.com/ethereum/go-ethereum/plugin/helloworld g                                                                                                ithub.com/ethereum/go-ethereum/plugin/initializer github.com/ethereum/go-ethereum/plugin/secu                                                                                                rity github.com/ethereum/go-ethereum/private github.com/ethereum/go-ethereum/private/cache gi                                                                                                thub.com/ethereum/go-ethereum/private/engine github.com/ethereum/go-ethereum/private/engine/c                                                                                                onstellation github.com/ethereum/go-ethereum/private/engine/notinuse github.com/ethereum/go-e                                                                                                thereum/private/engine/tessera github.com/ethereum/go-ethereum/raft github.com/ethereum/go-et                                                                                                hereum/rlp github.com/ethereum/go-ethereum/rpc github.com/ethereum/go-ethereum/signer/core gi                                                                                                thub.com/ethereum/go-ethereum/signer/fourbyte github.com/ethereum/go-ethereum/signer/rules gi                                                                                                thub.com/ethereum/go-ethereum/signer/rules/deps github.com/ethereum/go-ethereum/signer/storag                                                                                                e github.com/ethereum/go-ethereum/tests github.com/ethereum/go-ethereum/tests/fuzzers/abi git                                                                                                hub.com/ethereum/go-ethereum/tests/fuzzers/keystore github.com/ethereum/go-ethereum/tests/fuz                                                                                                zers/rlp github.com/ethereum/go-ethereum/tests/fuzzers/trie github.com/ethereum/go-ethereum/t                                                                                                ests/fuzzers/txfetcher github.com/ethereum/go-ethereum/trie
go: downloading gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: downloading github.com/stretchr/objx v0.1.0
go: extracting github.com/stretchr/objx v0.1.0
go: extracting gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: downloading github.com/kr/pretty v0.1.0
go: extracting github.com/kr/pretty v0.1.0
go: downloading github.com/kr/text v0.1.0
go: extracting github.com/kr/text v0.1.0
go: finding github.com/stretchr/objx v0.1.0
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/kr/text v0.1.0
?       github.com/ethereum/go-ethereum [no test files]
ok      github.com/ethereum/go-ethereum/accounts        0.014s
ok      github.com/ethereum/go-ethereum/accounts/abi    0.030s
ok      github.com/ethereum/go-ethereum/accounts/abi/bind       22.217s
ok      github.com/ethereum/go-ethereum/accounts/abi/bind/backends      0.093s
?       github.com/ethereum/go-ethereum/accounts/external       [no test files]
ok      github.com/ethereum/go-ethereum/accounts/keystore       22.528s
ok      github.com/ethereum/go-ethereum/accounts/pluggable      0.016s
?       github.com/ethereum/go-ethereum/accounts/pluggable/internal/testutils   [no test file                                                                                                s]
?       github.com/ethereum/go-ethereum/accounts/pluggable/internal/testutils/mock_plugin   [                                                                                                no test files]
?       github.com/ethereum/go-ethereum/accounts/scwallet       [no test files]
?       github.com/ethereum/go-ethereum/accounts/usbwallet      [no test files]
?       github.com/ethereum/go-ethereum/accounts/usbwallet/trezor       [no test files]
?       github.com/ethereum/go-ethereum/cmd/abidump     [no test files]
?       github.com/ethereum/go-ethereum/cmd/abigen      [no test files]
?       github.com/ethereum/go-ethereum/cmd/bootnode    [no test files]
?       github.com/ethereum/go-ethereum/cmd/checkpoint-admin    [no test files]
?       github.com/ethereum/go-ethereum/cmd/clef        [no test files]
ok      github.com/ethereum/go-ethereum/cmd/devp2p      0.018s
ok      github.com/ethereum/go-ethereum/cmd/devp2p/internal/ethtest     0.033s
?       github.com/ethereum/go-ethereum/cmd/devp2p/internal/v4test      [no test files]
?       github.com/ethereum/go-ethereum/cmd/devp2p/internal/v5test      [no test files]
ok      github.com/ethereum/go-ethereum/cmd/ethkey      0.228s
?       github.com/ethereum/go-ethereum/cmd/evm [no test files]
?       github.com/ethereum/go-ethereum/cmd/evm/internal/compiler       [no test files]
?       github.com/ethereum/go-ethereum/cmd/evm/internal/t8ntool        [no test files]
?       github.com/ethereum/go-ethereum/cmd/faucet      [no test files]
ok      github.com/ethereum/go-ethereum/cmd/geth        18.000s
?       github.com/ethereum/go-ethereum/cmd/p2psim      [no test files]
ok      github.com/ethereum/go-ethereum/cmd/puppeth     0.018s
?       github.com/ethereum/go-ethereum/cmd/rlpdump     [no test files]
ok      github.com/ethereum/go-ethereum/cmd/utils       0.030s
ok      github.com/ethereum/go-ethereum/common  0.003s
ok      github.com/ethereum/go-ethereum/common/bitutil  0.003s
ok      github.com/ethereum/go-ethereum/common/compiler 0.005s
ok      github.com/ethereum/go-ethereum/common/fdlimit  0.006s
ok      github.com/ethereum/go-ethereum/common/hexutil  0.003s
ok      github.com/ethereum/go-ethereum/common/http     0.004s
ok      github.com/ethereum/go-ethereum/common/math     0.002s
ok      github.com/ethereum/go-ethereum/common/mclock   0.002s
ok      github.com/ethereum/go-ethereum/common/prque    0.513s
?       github.com/ethereum/go-ethereum/consensus       [no test files]
ok      github.com/ethereum/go-ethereum/consensus/clique        0.142s
ok      github.com/ethereum/go-ethereum/consensus/ethash        6.698s
ok      github.com/ethereum/go-ethereum/consensus/istanbul      0.019s
ok      github.com/ethereum/go-ethereum/consensus/istanbul/backend      6.556s
ok      github.com/ethereum/go-ethereum/consensus/istanbul/core 16.605s
ok      github.com/ethereum/go-ethereum/consensus/istanbul/validator    0.020s
?       github.com/ethereum/go-ethereum/consensus/misc  [no test files]
ok      github.com/ethereum/go-ethereum/console 1.257s
?       github.com/ethereum/go-ethereum/console/prompt  [no test files]
ok      github.com/ethereum/go-ethereum/contracts/checkpointoracle      0.907s
?       github.com/ethereum/go-ethereum/contracts/checkpointoracle/contract     [no test file                                                                                                s]
ok      github.com/ethereum/go-ethereum/core    53.874s
ok      github.com/ethereum/go-ethereum/core/asm        0.014s
ok      github.com/ethereum/go-ethereum/core/bloombits  3.068s
ok      github.com/ethereum/go-ethereum/core/forkid     0.011s
ok      github.com/ethereum/go-ethereum/core/mps        0.053s
ok      github.com/ethereum/go-ethereum/core/rawdb      4.290s
ok      github.com/ethereum/go-ethereum/core/state      8.467s
ok      github.com/ethereum/go-ethereum/core/state/snapshot     2.601s
ok      github.com/ethereum/go-ethereum/core/types      0.107s
ok      github.com/ethereum/go-ethereum/core/vm 1.896s
ok      github.com/ethereum/go-ethereum/core/vm/runtime 0.019s
ok      github.com/ethereum/go-ethereum/crypto  0.026s
ok      github.com/ethereum/go-ethereum/crypto/blake2b  0.020s
ok      github.com/ethereum/go-ethereum/crypto/bls12381 0.526s
?       github.com/ethereum/go-ethereum/crypto/bn256    [no test files]
ok      github.com/ethereum/go-ethereum/crypto/bn256/cloudflare 0.068s
ok      github.com/ethereum/go-ethereum/crypto/bn256/google     0.382s
ok      github.com/ethereum/go-ethereum/crypto/ecies    0.015s
ok      github.com/ethereum/go-ethereum/eth     60.522s
ok      github.com/ethereum/go-ethereum/eth/downloader  325.376s
ok      github.com/ethereum/go-ethereum/eth/fetcher     8.965s
ok      github.com/ethereum/go-ethereum/eth/filters     4.787s
ok      github.com/ethereum/go-ethereum/eth/gasprice    0.045s
ok      github.com/ethereum/go-ethereum/eth/tracers     0.227s
?       github.com/ethereum/go-ethereum/eth/tracers/internal/tracers    [no test files]
ok      github.com/ethereum/go-ethereum/ethclient       0.056s
?       github.com/ethereum/go-ethereum/ethdb   [no test files]
?       github.com/ethereum/go-ethereum/ethdb/dbtest    [no test files]
ok      github.com/ethereum/go-ethereum/ethdb/leveldb   0.015s
ok      github.com/ethereum/go-ethereum/ethdb/memorydb  0.002s
?       github.com/ethereum/go-ethereum/ethstats        [no test files]
ok      github.com/ethereum/go-ethereum/event   0.748s
ok      github.com/ethereum/go-ethereum/extension       0.026s
?       github.com/ethereum/go-ethereum/extension/extensionContracts    [no test files]
ok      github.com/ethereum/go-ethereum/extension/privacyExtension      0.019s
ok      github.com/ethereum/go-ethereum/graphql 0.475s
ok      github.com/ethereum/go-ethereum/internal/build  0.003s
?       github.com/ethereum/go-ethereum/internal/cmdtest        [no test files]
?       github.com/ethereum/go-ethereum/internal/debug  [no test files]
ok      github.com/ethereum/go-ethereum/internal/ethapi 0.021s
?       github.com/ethereum/go-ethereum/internal/flags  [no test files]
ok      github.com/ethereum/go-ethereum/internal/guide  11.154s
ok      github.com/ethereum/go-ethereum/internal/jsre   0.110s
?       github.com/ethereum/go-ethereum/internal/jsre/deps      [no test files]
?       github.com/ethereum/go-ethereum/internal/plugin [no test files]
?       github.com/ethereum/go-ethereum/internal/testlog        [no test files]
ok      github.com/ethereum/go-ethereum/internal/utesting       0.002s
?       github.com/ethereum/go-ethereum/internal/web3ext        [no test files]
ok      github.com/ethereum/go-ethereum/les     73.136s
?       github.com/ethereum/go-ethereum/les/checkpointoracle    [no test files]
ok      github.com/ethereum/go-ethereum/les/flowcontrol 5.958s
ok      github.com/ethereum/go-ethereum/les/lespay/client       0.681s
ok      github.com/ethereum/go-ethereum/les/lespay/server       0.202s
ok      github.com/ethereum/go-ethereum/les/utils       1.387s
ok      github.com/ethereum/go-ethereum/light   0.478s
?       github.com/ethereum/go-ethereum/log     [no test files]
ok      github.com/ethereum/go-ethereum/metrics 0.215s
?       github.com/ethereum/go-ethereum/metrics/exp     [no test files]
?       github.com/ethereum/go-ethereum/metrics/influxdb        [no test files]
?       github.com/ethereum/go-ethereum/metrics/librato [no test files]
ok      github.com/ethereum/go-ethereum/metrics/prometheus      0.004s
ok      github.com/ethereum/go-ethereum/miner   22.711s
ok      github.com/ethereum/go-ethereum/mobile  0.020s
ok      github.com/ethereum/go-ethereum/multitenancy    0.012s
ok      github.com/ethereum/go-ethereum/node    0.167s
ok      github.com/ethereum/go-ethereum/p2p     3.731s
ok      github.com/ethereum/go-ethereum/p2p/discover    173.670s
ok      github.com/ethereum/go-ethereum/p2p/discover/v4wire     0.012s
ok      github.com/ethereum/go-ethereum/p2p/discover/v5wire     0.041s
ok      github.com/ethereum/go-ethereum/p2p/discv5      8.441s
ok      github.com/ethereum/go-ethereum/p2p/dnsdisc     0.658s
--- FAIL: TestParseNode (0.00s)
    urlv4_test.go:191: test "enode://1dd9d65c4552b5eb43d5ad55a2ee3f56c6cbc1c64a5c8d659f51fcd5                                                                                                1bace24351232b8d7821617d2b29b54b81cdefb9b3e9c37d7fd5f63270bcc9e1a6f6a439@invalid.:3":
          got error `lookup invalid.: Temporary failure in name resolution`, expected `no suc                                                                                                h host`
FAIL
FAIL    github.com/ethereum/go-ethereum/p2p/enode       1.127s
ok      github.com/ethereum/go-ethereum/p2p/enr 0.005s
ok      github.com/ethereum/go-ethereum/p2p/nat 2.644s
ok      github.com/ethereum/go-ethereum/p2p/netutil     0.006s
ok      github.com/ethereum/go-ethereum/p2p/nodestate   0.422s
ok      github.com/ethereum/go-ethereum/p2p/rlpx        0.017s
ok      github.com/ethereum/go-ethereum/p2p/simulations 2.135s
ok      github.com/ethereum/go-ethereum/p2p/simulations/adapters        0.025s
?       github.com/ethereum/go-ethereum/p2p/simulations/examples        [no test files]
?       github.com/ethereum/go-ethereum/p2p/simulations/pipes   [no test files]
ok      github.com/ethereum/go-ethereum/params  0.014s
ok      github.com/ethereum/go-ethereum/permission      2.554s
ok      github.com/ethereum/go-ethereum/permission/core 0.022s
?       github.com/ethereum/go-ethereum/permission/core/types   [no test files]
?       github.com/ethereum/go-ethereum/permission/v1   [no test files]
?       github.com/ethereum/go-ethereum/permission/v1/bind      [no test files]
?       github.com/ethereum/go-ethereum/permission/v1/contract/gen      [no test files]
?       github.com/ethereum/go-ethereum/permission/v2   [no test files]
?       github.com/ethereum/go-ethereum/permission/v2/bind      [no test files]
?       github.com/ethereum/go-ethereum/permission/v2/contract/gen      [no test files]
--- FAIL: TestPluginInterfaceName_UnmarshalJSON_whenTypical (0.00s)
    settings_test.go:189:
                Error Trace:    settings_test.go:189
                Error:          "map[BAR:a2 Foo:a1]" does not contain "foo"
                Test:           TestPluginInterfaceName_UnmarshalJSON_whenTypical
    settings_test.go:190:
                Error Trace:    settings_test.go:190
                Error:          "map[BAR:a2 Foo:a1]" does not contain "bar"
                Test:           TestPluginInterfaceName_UnmarshalJSON_whenTypical
FAIL
FAIL    github.com/ethereum/go-ethereum/plugin  0.022s
ok      github.com/ethereum/go-ethereum/plugin/account  0.012s
?       github.com/ethereum/go-ethereum/plugin/account/internal/testutils       [no test file                                                                                                s]
?       github.com/ethereum/go-ethereum/plugin/gen      [no test files]
?       github.com/ethereum/go-ethereum/plugin/gen/proto_common [no test files]
ok      github.com/ethereum/go-ethereum/plugin/helloworld       0.005s
ok      github.com/ethereum/go-ethereum/plugin/initializer      0.005s
ok      github.com/ethereum/go-ethereum/plugin/security 0.005s
ok      github.com/ethereum/go-ethereum/private 0.013s
?       github.com/ethereum/go-ethereum/private/cache   [no test files]
ok      github.com/ethereum/go-ethereum/private/engine  0.004s
?       github.com/ethereum/go-ethereum/private/engine/constellation    [no test files]
ok      github.com/ethereum/go-ethereum/private/engine/notinuse 0.002s
ok      github.com/ethereum/go-ethereum/private/engine/tessera  0.014s
ok      github.com/ethereum/go-ethereum/raft    3.373s
ok      github.com/ethereum/go-ethereum/rlp     0.005s
ok      github.com/ethereum/go-ethereum/rpc     13.550s
ok      github.com/ethereum/go-ethereum/signer/core     3.896s
ok      github.com/ethereum/go-ethereum/signer/fourbyte 3.081s
ok      github.com/ethereum/go-ethereum/signer/rules    0.170s
?       github.com/ethereum/go-ethereum/signer/rules/deps       [no test files]
ok      github.com/ethereum/go-ethereum/signer/storage  0.008s
ok      github.com/ethereum/go-ethereum/tests   0.020s
ok      github.com/ethereum/go-ethereum/tests/fuzzers/abi       0.011s
?       github.com/ethereum/go-ethereum/tests/fuzzers/keystore  [no test files]
?       github.com/ethereum/go-ethereum/tests/fuzzers/rlp       [no test files]
?       github.com/ethereum/go-ethereum/tests/fuzzers/trie      [no test files]
?       github.com/ethereum/go-ethereum/tests/fuzzers/txfetcher [no test files]
ok      github.com/ethereum/go-ethereum/trie    66.202s
FAIL
util.go:45: exit status 1
exit status 1
Makefile:41: fallo en las instrucciones para el objetivo 'test'
make: *** [test] Error 1

**Comment by ricardolyn** [comment]
hello!

You need to use Go 1.15
