### ISSUE TITLE
How to open the transaction fee setting

### ISSUE THREAD

**Issue by cppfuns** [Consensys-Incorporated/quorum#1251]
I'm trying to deploy a private chain, test the use of raft and ibft, and there is no transaction fee. I want to ask if there is a configuration that can open the transaction fee that is the same as the original Ethereum?

https://github.com/ConsenSys/quorum/pull/624  https://github.com/ConsenSys/quorum/issues/1176

**Comment by ricardolyn** [comment]
@cppfuns if your goal is to have a positive gas price, I recommend using https://github.com/hyperledger/besu/ with QBFT. 
it's already supported, tested, and ready to use.

let me know if you have any questions about the feature diff between GoQuorum and Besu.

**Comment by cppfuns** [comment]
> @cppfuns if your goal is to have a positive gas price, I recommend using https://github.com/hyperledger/besu/ with QBFT. it's already supported, tested, and ready to use.
> 
> let me know if you have any questions about the feature diff between GoQuorum and Besu.

Thanks for your reply, I am looking for a solution compatible with Ethereum and high TPS

**Comment by ricardolyn** [comment]
Besu is Ethereum based so should fit your requirements

**Comment by cppfuns** [comment]
> Besu is Ethereum based so should fit your requirements

Thank you for your reply, I will follow up the Besu plan first, close this question at this moment, and open it again if necessary
