### ISSUE TITLE
Contract access control based on initial privateFor array contents

### ISSUE THREAD

**Issue by patrickmn** [Consensys-Incorporated/quorum#126]
Currently operations on contracts are not restricted by `privateFor`; that only restricts who will run a given transaction. To ensure integrity of a contract, it must still implement the typical access controls (using Ethereum accounts,) otherwise other parties (including ones that were not part of the initial `privateFor` array) may send transactions that act on the contract.

Related to https://github.com/jpmorganchase/quorum/issues/110

Suggested actions:

  1. Improve documentation to highlight this, emphasizing the need for access control for public as well as private contracts.

  2. Given https://github.com/jpmorganchase/quorum/issues/110, restrict operations against a contract to parties "registered" for it.

However, it should be noted that even with the above, contracts still need to implement normal access controls to manage who among the `privateFor` peers can do what.

**Comment by CLDH214** [comment]
May I know if the fix is scheduled? 1 upvote to fix this issue from me

**Comment by tylobban** [comment]
Hi - yes an approach to help prevent this is in flight, thanks for the interest!

**Comment by nixonie** [comment]
Hi, are there any news on this one?

**Comment by dorosevski** [comment]
im also interested about this issue

**Comment by Himanshu-Pandey** [comment]
Any work around for this?

**Comment by karthik137** [comment]
What is the status?

**Comment by fixanoid** [comment]
Hey all, this is currently on our roadmap and an update will be coming later this year.

**Comment by heypran** [comment]
Is this issue fixed? If not then I am interested

**Comment by ricardolyn** [comment]
Implemented by the Privacy Enhancements feature.

**Comment by antonydenyer** [comment]
https://consensys.net/docs/goquorum//en/latest/concepts/privacy/privacy-enhancements/
