### ISSUE TITLE
node clustering is not consistent

### ISSUE THREAD

**Issue by selvarajdh** [Consensys-Incorporated/quorum#132]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Actual behaviour
Downloaded the 7 nodes example and started quorum as per the given steps. When we start for the first time all the nodes join network. In the geth console when we run the net command we are able to see the peercount 6

After few contracts created and private transactions made when we restart the 7 nodes using the start.sh and stop.sh,  the nodes are not joining the network. Again it is expecting to delete the qdata and run init.sh. 

In the geth console peerCount is shown as 0

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
@selvarajdh hi, are you able to reproduce this issue? When I run `stop.sh` and later run `start.sh`  the peers reconnect and the blockchain continues where it left off. Perhaps you can provide information from the logs for one of the nodes or bootnode under qdata/logs that might indicate why the peers can't connect? (you may need to increase the verbosity for the `bootnode` and `geth` commands in start.sh)

**Comment by sekharkumarroy** [comment]
@selvarajdh what version of geth are you using ?
