### ISSUE TITLE
init.sh failed: Fatal: invalid genesis file: missing 0x prefix for hex data

### ISSUE THREAD

**Issue by yanmingcao** [Consensys-Incorporated/quorum#136]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Branch, Commit Hash or Release: `git status`

Geth
Version: 1.6.6-stable
Git Commit: 10a45cb59bd9bc9f717817afc029a57b222e558d
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.1
Operating System: linux
GOPATH=
GOROOT=/usr/lib/go-1.8

#### Expected behaviour

./init.sh should succeed.

#### Actual behaviour

./init.sh failed at:
  geth --datadir qdata/dd1 init genesis.json

with error:

ubuntu@ubuntu-xenial:/vagrant/examples/7nodes$ ./init.sh
[*] Cleaning up temporary data directories
[*] Configuring node 1
Fatal: invalid genesis file: missing 0x prefix for hex data

#### Steps to reproduce the behaviour

run ./init.sh

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
Hi - Quorum is still on geth 1.5.0, it looks like you are running geth not Quorum.  You should be running from the quorum-examples dir. Please see the instructions on the Quorum-examples repo:  https://github.com/jpmorganchase/quorum-examples/blob/master/README.md#running

**Comment by vxavictor513** [comment]
Hi, how to downgrade geth to 1.5.0-unstable?

**Comment by jpmsam** [comment]
@yanmingcao Please refer to the instructions @tylobban posted or https://github.com/jpmorganchase/quorum#quickstart
