### ISSUE TITLE
Ability to reveal a contract to/add a participant to a contract post-creation

### ISSUE THREAD

**Issue by patrickmn** [Consensys-Incorporated/quorum#142]

**Comment by smart-t** [comment]
You have my vote on this one. This will give a big boost to the usability of smart contracts in Quorum. It looks like when all parties in a private contract vote in favor of extended the visibility of that contract to a list of new participants, that this list get's extended where the contract details are pushed to the constellation db of the new participants. I love to be involved in making this possible.

**Comment by xuguojie** [comment]
Any timeframe for this big enhancement? This enables the contract(digital asset) to be verified by the new participants and transferred between them.

**Comment by ashfaq-shaik** [comment]
Team Quorum, @jpmsam @tylobban 

Has there been any update in regards to this enhancement. This is a feature that's pivotal in maintaining and extending private enterprise networks. As the participant base for a use case grows, we would have to add more nodes to the network and this also means that they would have to participate in existing private contracts.

**Comment by ashfaq-shaik** [comment]
@jpmsam @tylobban 

Apologies for the bump. Could someone from Team Quorum provide an update about this feature request? Is this in the roadmap?

**Comment by fixanoid** [comment]
Hey @ashfaq-shaik this feature is actively being worked on. We've some ideas on how this may work, but the implementation is not due out for a while, tho probably this year.

**Comment by ItayPodhajcer** [comment]
Hi, it's been more than a year since the last comment, any update on this?

**Comment by fixanoid** [comment]
@ItayPodhajcer hello there! As said last year, this is a very non-trivial issue to tackle. The good news is that we are close to a release of a framework as part of Tessera that will address it. While I don't have final ETA, this is expected before the year end.

**Comment by ricardolyn** [comment]
Implemented by the Privacy Smart Contrac Extensions feature.
