### ISSUE TITLE
callHelper.MakeCall doesn't create private transactions as advertised

### ISSUE THREAD

**Issue by gsalgado** [Consensys-Incorporated/quorum#143]
That method is supposed to simulate private transactions, but it doesn't. Although it does create a privateTestTx with its private attribute set, [this type assertion](https://github.com/jpmorganchase/quorum/blob/856c9fe43e3eb675678c55ceda7eb4d298a7ca7d/core/state_transition.go#L239) will always fail for privateTestTx because the IsPrivate method is declared on *privateTestTx.

Changing the declaration of privateTestTx.IsPrivate() makes the type assertion succeed, thus correctly simulating a private tx, but then the [test that uses that method](https://github.com/jpmorganchase/quorum/blob/856c9fe43e3eb675678c55ceda7eb4d298a7ca7d/core/private_state_test.go#L49) panics because it doesn't have a consetellation set-up.

Since that test is not actually creating private transactions as it should, and it's the only place where callHelper.MakeCall() is used, I think it might make sense to remove both the test and all the code in call_helper.go. Another alternative would be to fix the test to set up a mock constellation so that it doesn't panic, but I imagine that won't be trivial

**Comment by gsalgado** [comment]
In #144 I fixed callHelper.MakeCall and TestPrivateTransaction, but for that it needs to run constellation-node in a subprocess

**Comment by patrickmn** [comment]
This is a pretty good argument for an in-memory PrivateTransactionManager to remove the hard dependency on Constellation: https://github.com/jpmorganchase/quorum/issues/145

We should still merge this, and in any case it'd be nice to keep the Constellation scaffolding to test the Quorum + Constellation interaction -- just in a way that doesn't require Constellation to be present to run *any* tests, as you said.

**Comment by gsalgado** [comment]
@patrickmn do you think #144 could be merged as is (i.e. requiring Constellation to be installed to run the tests), or would you like me to change it so that the test that depends on constellation is not executed by default? One way to achieve that would be to change ci.go to always pass the -short flag to go test, and use that to disable the test. Then a bare 'make test' would not depend on constellation, but one could still run all the tests via a separate makefile target

**Comment by patrickmn** [comment]
Think it makes sense to merge for now, but would like somebody else to chime in for sanity.
