### ISSUE TITLE
Feat: `static-nodes.json` doesn't support DNS/hostnames

### ISSUE THREAD

**Issue by dan-turner** [Consensys-Incorporated/quorum#147]
It would be **awesome** if we could use hostnames/DNS in our `static-nodes.json` file.  At the moment the `ParseNode` function does not support this:

https://github.com/jpmorganchase/quorum/blob/436fc8d76a4871d67a61dc86c1a635e20594a0e6/p2p/discover/node.go#L133

I would have a crack myself but I'm clueless when it comes to golang :)

It would greatly simplify our runtime configuration as we would be able to ditch all the static IP requirements here:
https://github.com/CBAInnovationLab/quorum-examples/blob/master/examples/7nodes/docker-compose.yml

**Comment by patrickmn** [comment]
This is a deliberate design decision by upstream Ethereum that has come up a couple times before.

Will leave this open for discussion, but previously we've leaned toward not addressing this by making Quorum deviate, at least directly (some external scaffolding could potentially be added.)

**Comment by jpmsam** [comment]
For reference: https://github.com/ethereum/wiki/wiki/enode-url-format

**Comment by dan-turner** [comment]
Yeah, it says similar in the code comments. Why is that though?

**Comment by dhyansraj** [comment]
use --nat extip:<Ip> if you are using docker. Again if you are using docker compose, this not a big problem, since all nodes are in same network. Have a look at Quorum Maker in third party tools.

**Comment by patrickmn** [comment]
It would be great to have a script that translates static-nodes.json with FQDNs to IP addresses.
