### ISSUE TITLE
Load test issue

### ISSUE THREAD

**Issue by Anatoliy4041** [Consensys-Incorporated/quorum#151]
I was trying to perform quorum's load test by genereting big sized array, coping elements in another one and getting all of that to be displayed (via loop in Remix) to check the possibility of using quorum as the high load platform in my company. Doing that, I come across the issue where genereating array to be size 10, 100 and 1000 returned all of the elements, whereas if i tried to do more, e.g. 10000 or 100000, I was getting zero elements.

Stepes to reproduce the issue:

1. Open remix.
2. Copy and paste there the contract below;

pragma solidity ^0.4.8;
 
contract SimpleStorageA {
    uint[] storedDataA; 
    function set(uint x) payable {
        for (uint i=0; i<x; i++){
            storedDataA.push(i);   
        }
    } 
    function getAll() constant returns (uint[]) {
        return storedDataA;
    }   
    function get(uint n) returns (uint) {
        return storedDataA[n];
    }
}
contract SimpleStorageB {
    uint[] storedDataB; 
    function set(uint x) payable {
        SimpleStorageA temp = new SimpleStorageA();
        temp.set(x);
        for (uint i=0; i<x; i++){
            storedDataB.push(temp.get(i));   
        }       
    } 
    function get() constant returns (uint[]) {
        return storedDataB;
    }
}
3. Create contract SimpleStorageB, fill the set method with 10000
4. Call the get method in SimpleStorageB

**Comment by patrickmn** [comment]
Please indicate if this is still an issue as of Quorum 2.0.0.
