### ISSUE TITLE
Provide ability to transfer assets whilst maintaining privacy

### ISSUE THREAD

**Issue by tylobban** [Consensys-Incorporated/quorum#152]
We should be able to transfer an asset from A->B->C whilst:

1.  maintaining privacy of the A->B and B->C transactions
2. guaranteeing to C that B did in fact rightfully own the asset 
3. ensuring that B can't double spend the asset to D
4. ensuring that no party can increase the total asset supply

**Comment by patrickmn** [comment]
https://github.com/jpmorganchase/zsl-q
