### ISSUE TITLE
Enode creation for nodes other than bootnode

### ISSUE THREAD

**Issue by carnelius8888** [Consensys-Incorporated/quorum#153]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX    Linux

Branch, Commit Hash or Release: `git status` raft.

#### Steps to reproduce the behaviour
Hi,
I am trying generate static-nodes.json for private network. How can i generate enode for the same?

#### Backtrace

````
[backtrace]
````

**Comment by jpmsam** [comment]
@bts @joelburget did you use any script to generate the enode address or did you start and stop the geth node to get an enode address assigned?

**Comment by carnelius8888** [comment]
I am not using script to generate Enode , i want to know if there is any command which would let me create Enode so as to add it into static-json for Raft installation.

**Comment by carnelius8888** [comment]
Can anyone answer this question?
raft.addpeer also has enode as variable, so even there i have to generate enode.
I am currently starting node and then picking enode from there, add it in static-nodes.json and restart using --raft.

**Comment by dhyansraj** [comment]
enode is based on nodekey found the in --datadir. So if you can place static nodekey file, the enode for that node will always be same.

**Comment by patrickmn** [comment]
After attaching to the node:

```
> admin.nodeInfo.enode
"enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000"
```

**Comment by FabriceDosSantos** [comment]
OK, then how to find a static nodekey file, how to generate it ?

**Comment by BlkchainQ** [comment]
you can use this command to generate nodekey :
bootnode --genkey=nodekey
