### ISSUE TITLE
Quorum event watch not trigger

### ISSUE THREAD

**Issue by wtam** [Consensys-Incorporated/quorum#154]
#### System information

Geth version: Version: 1.5.0-unstable, Go Version: go1.7.3

OS & Version: Linux

Branch, Commit Hash or Release: 6d0bd810484f4c56f7c9aebc229e1bdc56832ced

#### Expected behaviour
Event watch should be trigger when writing private Txn to Quorum node

#### Actual behaviour
Event watch didn't trigger and no error when writing private Txn.  But when change its to Ethereum/public Txn, the event trigger will work?  Is its because the private Txn break the web3 event watch?  Any suggestion?

#### Steps to reproduce the behaviour
use the  Quorum SimpleStorage sample with 7 nodes and add event to watch the storeData in the set method call

#### Backtrace

````
[backtrace]
````

**Comment by jpmsam** [comment]
@wtam please update to master or the latest release.

**Comment by wtam** [comment]
@jpmsam Thank You! it's working now after replacing the latest geth and bootnode from Quorum.
