### ISSUE TITLE
issue with private contract deployment with the factory model

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#156]
#### System information
Quorum version : 1.1.0

#### Scenario
Facing problem while creating the contract in a private way using the factory contract.
I have two contracts SampleContractFactory and SampleContract. SampleContractFactory provides a function to create the SampleContract instance.
Deployment :
Step 1. SampleContractFactory is deployed as an private contract from Node1 to Node2, Node3, Node4, Node 5.
Step 2. From Node2, Factory contract function CreateSampleContract() is called as private to Node1. New contract gets deployed at address say 0xXXXX at Node1 & Node2.
Till now results are as expected.
Step 3. From Node3, Factory contract function CreateSampleContract() is called as private to Node1.  Now new contract is getting deployed at address 0xXXXX at Node 3 and 0xYYYYY at Node1. 

#### Steps to reproduce the behaviour 

Solidity smart contract code is 

contract SampleContract {
    uint counter;
    function SampleContract(uint i){
        counter = i;
    }
}

import "./SampleContract.sol";
contract SampleContractFactory {
    address[] addresses;
    function SampleContractFactory(){  }
    function CreateSampleContract(){
        SampleContract ob = new SampleContract(10);
        addresses.push(address(ob));
    }
    function getSampleContract(uint index) constant returns (address _sampleContract){
        return addresses[index];
    }
 }

Looking at the behavior I think the nounce of the Factory contract that is one of the factor to calculate the new contract address is getting different at different nodes causing this inconsistency.

Thanks
-Gourav

**Comment by dhyansraj** [comment]
We figured out the problem. Nodes which are not part of the transaction has a different nonce. Nonce are used to calculate the contract address, so different nodes calculate different address eventually. This is an inherent nature of Quroum.

The solution is to instatiate the Contract outside quorum using byteCode (check web3 methods). This way all nodes would have same address.
