### ISSUE TITLE
Bad luck picking those V values...

### ISSUE THREAD

**Issue by martyall1** [Consensys-Incorporated/quorum#157]
I have a question about your geth-1.6 rebase branch. In the quorum specs it says that you are using the translated `V` value in the ECDSA output to case on whether or not a transaction is private, 
27 and 28 being reserved for the public net, 37 or 38 being reserved for private transactions in a quorum network. However, due to (changes to protect replay attacks with Ethereum Classic)[https://github.com/ethereum/eips/issues/155], those exact numbers are now being reserved for use on the main-net. It's unclear to me how much work has been done to compensate for this, can someone please tell me what has been done and was is still in progress.

**Comment by patrickmn** [comment]
cc @obscuren @bas-vk

**Comment by martyall1** [comment]
cc @joelburget

**Comment by joelburget** [comment]
My current solution is to use an impossibly large number for `eip155Block` in my `genesis.json`. I use the same impossibly large number for `homesteadBlock` and `eip158Block`. I've also experimented with setting all of them to 0 and setting `V` to something else, like 47 or 48, but there were some issues I haven't worked through. I don't think we gain from EIPs 155 or 158 and only (maybe) care about DELEGATECALL from homestead.

**Comment by martyall1** [comment]
Can you explain why homestead or 158 directly impacts the quorum changes? Or is it just that they aren't prioritized for some reason?

**Comment by joelburget** [comment]
I want to start by matching the behavior of Quorum today, then adding EVM enhancements from there.
