### ISSUE TITLE
How to use the api quorum.runPorosity and quorum.getPrivatePayload

### ISSUE THREAD

**Issue by bigstar119** [Consensys-Incorporated/quorum#158]
Hi ,who can explain How to use the api quorum.runPorosity and quorum.getPrivatePayload?

**Comment by prd-fox** [comment]
Rather late, but just for future ref -

`runPorosity` is no longer part of the Quorum API, and `getPayload` is under the `eth` API, with instructions here: http://docs.goquorum.com/en/latest/Getting%20Started/api/
