### ISSUE TITLE
SSL Support for Communication Between Nodes

### ISSUE THREAD

**Issue by web3rover** [Consensys-Incorporated/quorum#168]
We are using Quorum in production for a multi entity use-case. The problem is all these entities quorum nodes sits behind a firewall which only allows TLS traffic. 

The node that's broadcasting transactions has to use TLS otherwise the firewalls are blocking the packets. The receiving node's firewall acts as a reverse proxy therefore it doesn't need to have SSL. But how do I make Quroum's geth use TLS while broadcasting transactions. 

Is there a way in ubuntu which will automatically encrypt the unencrypted connections or any sort of proxy based solution?

**Comment by sivachaitanya** [comment]
+1

**Comment by patrickmn** [comment]
It might be interesting to make Constellation support proxying geth traffic over TLS, but right now your best bet is probably [stunnel](https://www.stunnel.org/index.html) or OpenVPN.

**Comment by jpmsam** [comment]
@narayanprusty would you be able to share what the use case was ?

**Comment by nathanawmk** [comment]
hello, would like to know if anyone has used stunnel for this purpose of enabling 2-way SSL between nodes? Is it even possible architecturally? Regulatory requirement dictates 2-way SSL
