### ISSUE TITLE
Can't generate bootnode key

### ISSUE THREAD

**Issue by erNail** [Consensys-Incorporated/quorum#169]
#### System information

Geth version: `1.5.0-unstable`

OS & Version: `Provided Vagrant VM`

Branch, Commit Hash or Release: `Master, 5dfdecef4cc0ce7543e2dd5eb7aa167f3e143e60`

#### Expected behaviour
Executing `bootnode –genkey tmp_file.txt` should create a text file with a key.

#### Actual behaviour
Executing `bootnode –genkey tmp_file.txt` returns `Fatal: Use -nodekey or -nodekeyhex to specify a private key`.

#### Steps to reproduce the behaviour
1. Start quorum-examples vagrant vm.
2. (Optional) Create `genesis.json` or switch to directory with `genesis.json`
3. Enter `bootnode –genkey tmp_file.txt`

#### Backtrace

````
I0831 13:06:56.909341 cmd/geth/main.go:232] successfully wrote genesis block and/or chain rule set: 38fe1ed0ea21a87103ced98121ff4f2e54203f546675e273dabc5c46cbe43a61
ubuntu@ubuntu-xenial:~/shared$ ls
quorum-genesis.json
ubuntu@ubuntu-xenial:~/shared$ bootnode –genkey tmp_file.txt
Fatal: Use -nodekey or -nodekeyhex to specify a private key
````

**Comment by erNail** [comment]
I found the issue. When entering the command `bootnode -genkey tmp_file.txt` by hand (not via copy and paste), no error is thrown. It seems like the hyphen in the `README.md` is "broken". In my shell it's slightly longer than the normal hyphen. See below:

```
ubuntu@ubuntu-xenial:~/quorum-examples$ bootnode –genkey tmp_file.txt
Fatal: Use -nodekey or -nodekeyhex to specify a private key
ubuntu@ubuntu-xenial:~/quorum-examples$ bootnode -genkey tmp_file.txt
I0831 13:27:43.583236 p2p/discover/udp.go:217] Listening, enode://f548124ab24c205cde5540a291ccb983a36eadeb81046608892bedc3facff491d364ba275807fd835845b60ae7da2e6eed71ece173724b5a5552d1b863b1ca82@[::]:30301
```
Please consider updating your `README.md`.

**Comment by patrickmn** [comment]
That's unfortunate. Thank you for pointing it out.

Fix: https://github.com/jpmorganchase/quorum/pull/182
