### ISSUE TITLE
Error deploying contracts using Raft

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#170]
#### System information

Geth version: 
```
Geth
Version: 1.5.0-unstable
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.5
OS: linux
GOPATH=
GOROOT=/usr/local/go
```

OS & Version: RedHat Linux

Branch, Commit Hash or Release: *looking for it*

We recently migrated from QuorumChain consensus to Raft consensus and suddenly we were no longer able to deploy contracts. Quorum panics on the RPC call with the following stack trace:
https://gist.github.com/stevenroose/5775bcf2b17b2ea28b9b967777caf578

While the response from the abigen binding is `failed to retrieve account nonce: EOF`.

(cc @alvarosevilla95 @kubasiemion)

**Comment by stevenroose** [comment]
After updating to the latest version of Quorum, the error changed to a more informative one:

`failed to retrieve account nonce: Raft mode has no Pending block. Use latest instead.`

The thing is that the Go bindings from abigen don't allow specifying the state where to look for the account nonce, it does it under the hood.

So Raft breaks abigen and ethclient. Why doesn't it default to using latest when pending is specified using Raft? I think that would be the easiest fix.

**Comment by stevenroose** [comment]
We tried to do that, use latest instead of pending when using Raft, but got the old error back.

Diff:
[deprecated]

Error: `failed to retrieve account nonce: EOF`

Stack trace: https://gist.github.com/stevenroose/547022551cc677635e8bdaf4fb219577

**Comment by stevenroose** [comment]
Ok, I made a mistake in the patch. This one does the trick. Should I submit it as a PR?
```diff
diff --git a/eth/api_backend.go b/eth/api_backend.go
index bf8d5451c..d27341a51 100644
--- a/eth/api_backend.go
+++ b/eth/api_backend.go
@@ -20,6 +20,7 @@ import (
 	"math/big"
 
 	"fmt"
+
 	"github.com/ethereum/go-ethereum/accounts"
 	"github.com/ethereum/go-ethereum/common"
 	"github.com/ethereum/go-ethereum/core"
@@ -62,7 +63,8 @@ func (b *EthApiBackend) BlockByNumber(ctx context.Context, blockNr rpc.BlockNumb
 	// Pending block is only known by the miner
 	if blockNr == rpc.PendingBlockNumber {
 		if b.eth.protocolManager.raftMode {
-			return nil, raftHasNoPending
+			// Use latest instead.
+			return b.eth.blockchain.CurrentBlock(), nil
 		}
 		block, _, _ := b.eth.blockVoting.Pending()
 		return block, nil
@@ -78,7 +80,13 @@ func (b *EthApiBackend) StateAndHeaderByNumber(blockNr rpc.BlockNumber) (ethapi.
 	// Pending state is only known by the miner
 	if blockNr == rpc.PendingBlockNumber {
 		if b.eth.protocolManager.raftMode {
-			return nil, nil, raftHasNoPending
+			// Use latest instead.
+			header := b.HeaderByNumber(rpc.LatestBlockNumber)
+			if header == nil {
+				return nil, nil, nil
+			}
+			publicState, privateState, err := b.eth.BlockChain().StateAt(header.Root)
+			return EthApiState{publicState, privateState}, header, err
 		}
 		block, publicState, privateState := b.eth.blockVoting.Pending()
 		return EthApiState{publicState, privateState}, block.Header(), nil
```

**Comment by joelburget** [comment]
I'm mostly okay with this, but I'd like to hear what @bts and @patrickmn think.

**Comment by patrickmn** [comment]
Are there cases where you would get unexpected or unintuitive behavior because of this?

**Comment by stevenroose** [comment]
@patrickmn It totally breaks all the abi-gen generated code... So yeah, when using abigen and the ethclient Go client, you don't know where it's using the pending block or the latest block. Often it's also not possible to specify that. 

F.e. to get the account nonce before signing, it makes no sense to use the latest block instead of the pending one because that would mean you can only make one transaction per block.

**Comment by patrickmn** [comment]
Sorry -- I meant if your fix might not be what people want in some cases. In other words, is there a case where you'd actually want to get the error that there's no pending because you're explicitly looking for that and not the current block?

**Comment by stevenroose** [comment]
Oh unexpected behavior of the fix? Well, in the JS client I think you can explicitly set the block to `pending` or `latest`. So in the case someone sets in to `pending` explicitly, it will use `latest` instead. That's a but unintuitive. But since Raft doesn't have a pending block, it might be easily documented in the API that when using Raft, pending is always replaced by latest.

**Comment by alvarosevilla95** [comment]
According to [this](https://ethereum.stackexchange.com/questions/3400/filters-whats-latest-and-pending) and [this](https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethdefaultblock), `pending` refers to the currently mined block plus pending transactions, while `latest` refers just to the current block. Since Raft has no pending transactions, I would say the two are equivalent and therefore it should not be a problem to return the latest block when asked for `pending`

**Comment by patrickmn** [comment]
Ok, makes sense. @stevenroose could you execute CLA (https://github.com/jpmorganchase/cla) and submit a pull request so we can merge?

**Comment by bts** [comment]
Yeah, we should merge this -- it also prevents proper functioning of `web3.eth.estimateGas`.

**Comment by stevenroose** [comment]
@patrickmn Made the PR, feel free to pull it. I agree with the CLA and its terms, but I'm not comfortable with filling in my personal details and signing the document. I hope that's ok. I've had earlier PRs accepted without a problem.

**Comment by patrickmn** [comment]
Unfortunately we (currently at least) need an executed copy to merge contributions.

**Comment by stevenroose** [comment]
@patrickmn Apparently I didn't make earlier PRs to Quorum but to upstream geth. My apologies for the confusion!
