### ISSUE TITLE
Miner in Quorum missing 

### ISSUE THREAD

**Issue by andrew-tud** [Consensys-Incorporated/quorum#172]
#### System information

Geth version:  1.5.0-unstable-647025ed

OS & Version: Linux (using the example about vagrant 7nodes)

Branch, Commit Hash or Release: `git status`

No Miner in quorum geth

![image](https://user-images.githubusercontent.com/19533263/30091721-adccf8fa-92ed-11e7-9689-6c783e146d3f.png)

Please advice what to do as I cannot deploy any contract using quorum examples.

````
[backtrace]
````

**Comment by patrickmn** [comment]
Quorum has replaced Proof-of-Work and has no concept of mining. Please see https://github.com/jpmorganchase/quorum/wiki
