### ISSUE TITLE
difference between ethereum and quorum

### ISSUE THREAD

**Issue by KamnaJ** [Consensys-Incorporated/quorum#176]
Hello there ,

I want to know how quorum differs from ethereum ?
Does the voting consensus algorithm completely replace Proof of Work ?
How will be geth be used in quorum ? 
Amongst the maker and voter nodes , which nodes perform mining ?
How to create block explorer for quorum ?

**Comment by tylobban** [comment]
Hi - your answers are found on the Quorum wiki https://github.com/jpmorganchase/quorum/wiki. Thanks!

**Comment by stefek99** [comment]
One of the top Google search results for "quorum ethereum difference"

Some good links I was able to find:
- https://ethereum.stackexchange.com/questions/73580/about-key-and-address-difference-between-quorum-and-ethereum-blockchain
- https://akeo.tech/blog/blockchain-and-dlt/quorum-an-improved-ethereum-blockchain/
- https://blockgeeks.com/guides/quorum-a-blockchain-platform-for-the-enterprise/
