### ISSUE TITLE
private transaction check

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#177]
If I have the transaction hash value of a private transaction, how can i verify at a quorum node if that node is the recipient of that private transaction and it has the transaction payload in its constellation which it can decrypt and execute.
Is there something in transaction receipt or in transaction object that indicates this.

I did checked V value in transaction but it only indicates if the transaction is private or public.

Thanks

**Comment by patrickmn** [comment]
`quorum.getPrivatePayload(hashDigest)` returns something other than `0x`.
