### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by SebLKMa** [Consensys-Incorporated/quorum#178]
Hi quorum fans,
Has anyone built quorum successfully on Windows 10 before?
Any pre-requisites on what the machine must have installed first?
I tried using mingw32 and failed below at util.go:42: exit status 2.
Thank you.

$ make all
build/env.sh go run build/ci.go install
>>> C:\tools\go\bin\go install -ldflags -X main.gitCommit=663710f4133bc0e80b9894a368999df0cf0339ac -v ./...
github.com/ethereum/go-ethereum/common
github.com/ethereum/go-ethereum/crypto/randentropy
github.com/ethereum/go-ethereum/rlp
github.com/ethereum/go-ethereum/crypto/sha3
github.com/ethereum/go-ethereum/crypto/secp256k1
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/ripemd160
github.com/ethereum/go-ethereum/logger/glog
github.com/ethereum/go-ethereum/params
github.com/ethereum/go-ethereum/vendor/github.com/hashicorp/golang-lru/simplelru
# github.com/ethereum/go-ethereum/crypto/secp256k1
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/util
github.com/ethereum/go-ethereum/vendor/github.com/hashicorp/golang-lru
github.com/ethereum/go-ethereum/logger
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/cache
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/comparer
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/storage
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/filter
github.com/ethereum/go-ethereum/vendor/github.com/golang/snappy
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/opt
github.com/ethereum/go-ethereum/vendor/github.com/rcrowley/go-metrics/exp
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/errors
github.com/ethereum/go-ethereum/vendor/gopkg.in/karalabe/cookiejar.v2/collections/prque
golang.org/x/net/context
github.com/ethereum/go-ethereum/metrics
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/iterator
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/journal
github.com/ethereum/go-ethereum/vendor/github.com/pborman/uuid
github.com/ethereum/go-ethereum/vendor/github.com/rjeczalik/notify
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/memdb
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb/table
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/pbkdf2
github.com/ethereum/go-ethereum/vendor/golang.org/x/tools/go/ast/astutil
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt
github.com/ethereum/go-ethereum/event
github.com/ethereum/go-ethereum/vendor/github.com/BurntSushi/toml
github.com/ethereum/go-ethereum/vendor/github.com/syndtr/goleveldb/leveldb
github.com/ethereum/go-ethereum/vendor/golang.org/x/tools/imports
github.com/ethereum/go-ethereum/vendor/github.com/patrickmn/go-cache
github.com/ethereum/go-ethereum/vendor/github.com/tv42/httpunix
github.com/ethereum/go-ethereum/vendor/gopkg.in/fatih/set.v0
github.com/ethereum/go-ethereum/private/constellation
github.com/ethereum/go-ethereum/vendor/github.com/rs/xhandler
github.com/ethereum/go-ethereum/vendor/golang.org/x/net/websocket
github.com/ethereum/go-ethereum/private
github.com/ethereum/go-ethereum/vendor/github.com/rs/cors
github.com/ethereum/go-ethereum/vendor/gopkg.in/natefinch/npipe.v2
github.com/ethereum/go-ethereum/ethdb
github.com/ethereum/go-ethereum/vendor/github.com/huin/goupnp/httpu
github.com/ethereum/go-ethereum/vendor/github.com/huin/goupnp/scpd
github.com/ethereum/go-ethereum/rpc
github.com/ethereum/go-ethereum/trie
github.com/ethereum/go-ethereum/vendor/github.com/huin/goupnp/soap
github.com/ethereum/go-ethereum/vendor/github.com/huin/goupnp/ssdp
github.com/ethereum/go-ethereum/vendor/golang.org/x/net/html/atom
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/internal/identifier
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/transform
github.com/ethereum/go-ethereum/vendor/golang.org/x/net/html
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/internal/utf8internal
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/internal/tag
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/runes
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/language
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/internal
github.com/ethereum/go-ethereum/vendor/github.com/jackpal/go-nat-pmp
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/charmap
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/japanese
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/korean
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/simplifiedchinese
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/traditionalchinese
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/unicode
github.com/ethereum/go-ethereum/vendor/gopkg.in/sourcemap.v1/base64vlq
github.com/ethereum/go-ethereum/vendor/gopkg.in/sourcemap.v1
github.com/ethereum/go-ethereum/vendor/github.com/robertkrimen/otto/token
github.com/ethereum/go-ethereum/vendor/github.com/robertkrimen/otto/file
github.com/ethereum/go-ethereum/vendor/github.com/robertkrimen/otto/dbg
github.com/ethereum/go-ethereum/vendor/github.com/robertkrimen/otto/registry
github.com/ethereum/go-ethereum/vendor/github.com/robertkrimen/otto/ast
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/encoding/htmlindex
github.com/ethereum/go-ethereum/vendor/gopkg.in/urfave/cli.v1
github.com/ethereum/go-ethereum/vendor/github.com/golang/protobuf/proto
github.com/ethereum/go-ethereum/vendor/github.com/robertkrimen/otto/parser
github.com/ethereum/go-ethereum/vendor/golang.org/x/net/html/charset
github.com/ethereum/go-ethereum/vendor/github.com/huin/goupnp
github.com/ethereum/go-ethereum/internal/debug
github.com/ethereum/go-ethereum/vendor/github.com/robertkrimen/otto
github.com/ethereum/go-ethereum/vendor/github.com/huin/goupnp/dcps/internetgateway1
github.com/ethereum/go-ethereum/vendor/github.com/huin/goupnp/dcps/internetgateway2
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raftpb
github.com/ethereum/go-ethereum/vendor/github.com/eapache/queue
github.com/ethereum/go-ethereum/vendor/github.com/eapache/channels
github.com/ethereum/go-ethereum/p2p/nat
github.com/ethereum/go-ethereum/vendor/github.com/coreos/pkg/capnslog
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/types
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/fileutil
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/httputil
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/ioutil
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/logutil
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/pbutil
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/tlsutil
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/etcdserver/stats
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/snap/snappb
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/transport
github.com/ethereum/go-ethereum/vendor/github.com/beorn7/perks/quantile
github.com/ethereum/go-ethereum/vendor/github.com/prometheus/client_model/go
github.com/ethereum/go-ethereum/vendor/github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/ethereum/go-ethereum/vendor/github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
github.com/ethereum/go-ethereum/vendor/github.com/prometheus/common/model
github.com/ethereum/go-ethereum/vendor/github.com/prometheus/procfs
github.com/ethereum/go-ethereum/vendor/github.com/coreos/go-semver/semver
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/version
github.com/ethereum/go-ethereum/vendor/github.com/prometheus/common/expfmt
github.com/ethereum/go-ethereum/vendor/github.com/xiang90/probing
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/pkg/crc
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/wal/walpb
github.com/ethereum/go-ethereum/vendor/gopkg.in/oleiade/lane.v1
github.com/ethereum/go-ethereum/vendor/github.com/prometheus/client_golang/prometheus
github.com/ethereum/go-ethereum/event/filter
github.com/ethereum/go-ethereum/vendor/github.com/mattn/go-isatty
github.com/ethereum/go-ethereum/vendor/github.com/mattn/go-colorable
github.com/ethereum/go-ethereum/internal/web3ext
github.com/ethereum/go-ethereum/vendor/github.com/peterh/liner
github.com/ethereum/go-ethereum/vendor/github.com/mattn/go-runewidth
github.com/ethereum/go-ethereum/vendor/github.com/fatih/color
github.com/ethereum/go-ethereum/vendor/github.com/mitchellh/go-wordwrap
github.com/ethereum/go-ethereum/internal/jsre
github.com/ethereum/go-ethereum/vendor/github.com/nsf/termbox-go
github.com/ethereum/go-ethereum/cmd/rlpdump
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/snap
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/wal
github.com/ethereum/go-ethereum/console
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/rafthttp
github.com/ethereum/go-ethereum/vendor/github.com/gizak/termui
github.com/ethereum/go-ethereum/common/math
github.com/ethereum/go-ethereum/common/number
github.com/ethereum/go-ethereum/swarm/services/swap/swap
github.com/ethereum/go-ethereum/errs
github.com/ethereum/go-ethereum/generators
github.com/ethereum/go-ethereum/internal/build
github.com/ethereum/go-ethereum/pow/dagger
github.com/ethereum/go-ethereum/swarm/network/kademlia
github.com/ethereum/go-ethereum/vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder
github.com/ethereum/go-ethereum/vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder
github.com/ethereum/go-ethereum/vendor/github.com/BurntSushi/toml/cmd/tomlv
github.com/ethereum/go-ethereum/vendor/github.com/cespare/cp
github.com/ethereum/go-ethereum/vendor/github.com/coreos/go-systemd/journal
github.com/ethereum/go-ethereum/vendor/github.com/davecgh/go-spew/spew
github.com/ethereum/go-ethereum/vendor/golang.org/x/sys/unix
# github.com/ethereum/go-ethereum/vendor/github.com/coreos/go-systemd/journal
vendor\github.com\coreos\go-systemd\journal\journal.go:99: undefined: syscall.UnixRights
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/unicode/cldr
github.com/ethereum/go-ethereum/vendor/gopkg.in/check.v1
github.com/ethereum/go-ethereum/vendor/golang.org/x/text/internal/gen
util.go:42: exit status 2
exit status 1
make: *** [all] Error 1

**Comment by patrickmn** [comment]
Windows isn't currently supported directly, although Quorum runs fine in the Linux Subsystem for Windows, available for Windows 10.

Are you able to use e.g. Ubuntu on Windows?

**Comment by SebLKMa** [comment]
Patrick, thank you for your response. In the meantime, I will explore the alternatives you suggested, and inform all.
PS: Thanks also for adding this to Later milestone

**Comment by fixanoid** [comment]
Windows support in Quorum is available starting 2.2.1.
