### ISSUE TITLE
Allow adding non-consensus-participating nodes to a network using Raft consensus

### ISSUE THREAD

**Issue by jcgarridosanlab** [Consensys-Incorporated/quorum#180]
#### System information

Geth version: 1.5.0-unstable

OS & Version: Ubuntu 16.04 

Branch, Commit Hash or Release: Quorum 1.1.0 Constellation 0.1.0

#### Expected behaviour
We have a 7 nodes network and we want 5 of them ("core") to be participating in the raft consensus algorithm and creating new blocks. The two "relay" nodes left should have a copy of the blockchain updated with the transactions and should be able to send transactions to the network but they don't participate on the raft consensus.

¿Is it possible to have such a kind of network (with nodes sending transactions but not participating in the raft consensus?

#### Actual behaviour
The "core" nodes (that use raft consensus) are seeing each other and can perform transactions (the block number increases when a transaction is made). The "relay" nodes block number does not increase although the admin.peers shows the "core" nodes only if we add them as boot nodes on the geth start script.

#### Steps to reproduce the behaviour
-Create a network using raft with 5 nodes. The static-nodes.json file of these nodes contains the enodes of these 5 nodes.
-Add 2 more nodes ("relay") without the --raft flag including the former 5 nodes in the boot node parameter. They do not have static-nodes.json file
-Send a transaction to one of the 5 core nodes
-Check that the "relay" node blocknumber does not increase
-Unlock an account in one of the relay nodes
-Send a transaction to this relay node and check that it says the account is locked

**Comment by patrickmn** [comment]
This is not possible in Raft at the moment, but is a desired feature. What you want is possible using the Istanbul consensus option.

**Comment by fixanoid** [comment]
Implemented as of Quorum v2.4.0
