### ISSUE TITLE
raftport flag issue

### ISSUE THREAD

**Issue by RuchikaChakala** [Consensys-Incorporated/quorum#188]
#### System information

Geth version: `geth version`
1.5.0-unstable 
Git Commit: 647025ed8a504decfb11ac29bb44b3b2db703071

OS & Version: Windows/Linux/OSX
Linux Ubuntu 16.04 LTS

Branch, Commit Hash or Release: `git status`

we are using Quorum version 1.2.0.
We started raft node with flag --raftport but it failed to start giving error:
flag provided but not defined: -raftport

Could you please let us know whether we can use --raftport flag in geth command to start node?

**Comment by bts** [comment]
It looks like you're using a [version of Quorum from July](https://github.com/jpmorganchase/quorum/commit/647025ed8a504decfb11ac29bb44b3b2db703071) that doesn't yet have the `--raftflag` support that was [merged in August](https://github.com/jpmorganchase/quorum/commit/5dfdecef4cc0ce7543e2dd5eb7aa167f3e143e60). Try using the latest code from `master` and you should be all set.
