### ISSUE TITLE
What is the default sync mode in quorum?

### ISSUE THREAD

**Issue by thpun** [Consensys-Incorporated/quorum#191]
In Ethereum, there are 3 sync modes to choose: full, fast, light. And fast mode is default in ethereum (`geth`) for the 1st sync.

So what about Quorum? (Does Quorum make any changes on sync mode?) And is there any difference in the sync mode if i use different consensus algorithm (QuroumChain, Raft)?

**Comment by thpun** [comment]
I'm not familiar with golang so please forgive me asking the following question:
By looking at [`eth/config.go`](https://github.com/jpmorganchase/quorum/blob/quorum-2-rc/eth/config.go) and [`eth/downloader/modes.go`](https://github.com/jpmorganchase/quorum/blob/quorum-2-rc/eth/downloader/modes.go), does it imply that if I run sth like `PRIVATE_CONFIG=node1.conf geth --datadir qdata --raft --nodiscover --port 21000` right after `geth init`, full sync mode is used since I don't specify `syncmode` in the arguments?

For the subsequent syncs, Quorum's fast sync mode is also disabled just like `geth`, if I didn't missed any other codes. (Ref: [eth/handler](https://github.com/jpmorganchase/quorum/blob/quorum-2-rc/eth/handler.go#L129))

I would also like to ask about the purpose of having a special sync mode called `boundedfullsync` for Raft.

**Comment by bts** [comment]
@thpun the bounded full sync mode was added so that we could have peers sync up to and including a particular block without going any further. This is to make sure that the state in ethereum is entirely dictated by, and consistent with, the raft state.
