### ISSUE TITLE
Nodes are not getting connected with bootnode with exception "useless nodes"

### ISSUE THREAD

**Issue by karnawat83** [Consensys-Incorporated/quorum#193]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

We were having 5 nodes setup. We have observed that one of the node was giving error while making connection(adding peers) with boot node. From the logs we found some errors and it was saying "retrieved hash chain is invalid" or "useless nodes.". I am not sure how a node can be useless or in which scenario a hash chain can be invalid.

Request you to please suggest on this.

Below are a log snapshot:

I0927 07:57:08.331769 eth/downloader/downloader.go:796] Peer 23a981d09058a3c5 [hs 4203.34/s, bs 1877.59/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 7.760457189s]: header download terminated
I0927 07:57:08.331780 eth/downloader/downloader.go:393] Synchronisation terminated after 255.572659ms
I0927 07:57:08.331792 eth/downloader/downloader.go:301] Removing peer 23a981d09058a3c5: retrieved hash chain is invalid
I0927 07:57:08.331798 eth/handler.go:192] Removing peer 23a981d09058a3c5
I0927 07:57:08.331802 eth/downloader/downloader.go:267] Unregistering peer 23a981d09058a3c5
I0927 07:57:08.331843 p2p/peer.go:180] Peer 23a981d09058a3c5 10.35.231.102:22001: locally requested disconnect: Useless peer
I0927 07:57:08.332000 eth/peer.go:209] Peer 23a981d09058a3c5 [eth/63] fetching 192 headers from #1258342, skipping 0 (reverse = false)
I0927 07:57:08.332022 eth/handler.go:309] Peer 23a981d09058a3c5 [eth/63]: message handling failed: EOF
I0927 07:57:08.332036 p2p/server.go:740] Removed Peer 23a981d09058a3c5 10.35.231.102:22001 (Useless peer)
I0927 07:57:08.332052 p2p/server.go:527] <-delpeer: Peer 23a981d09058a3c5 10.35.231.102:22001
I0927 07:57:08.335754 eth/fetcher/fetcher.go:252] [eth/62] filtering 128:128 bodies
I0927 07:57:08.335793 eth/handler.go:522] no sync active
I0927 07:57:09.135461 p2p/discover/udp.go:453] >>> 10.35.231.188:22001 discover.neighbors
I0927 07:57:09.135524 p2p/discover/udp.go:521] <<< 10.35.231.188:22001 *discover.findnode: ok
I0927 07:57:09.409361 core/state/statedb.go:431] (+) 3c327ce9818d24c56de8805a74922206a5d269cd
I0927 07:57:09.409431 core/state/statedb.go:431] (+) 3c327ce9818d24c56de8805a74922206a5d269cd

#### Backtrace

````
[backtrace]
````

**Comment by sivachaitanya** [comment]
Are you sure you have the correct network id for all the nodes ? what is the result you are getting when performing admin.addPeer('enode..')  inside your geth console ?

**Comment by getsachmail** [comment]
Hi, 

Getting 'Useless peer" error and node is not sychronizing

Scenario: 
We have set up of 5 nodes all other node processed this block and transactions in #92843 block but one of the node is stuck on this block and not syching now. 

I think one of the transaction in bock #92843 is not able to execute on this node and syncing fails.

@patrickmn 
for admin.addPeer("") it got successful and not giving any error. and I can see peer in admin.peers list

Geth block
 eth.getBlock(92843)
{
  difficulty: 4.3468422602254367116471e+22,
  extraData: "0xac065991f4e920e487cca3e383fc12940cc9ae194152b25658966fd0e1456c717c97c9eba1b102be4c5d624feaa0ad237b06e02d13e39b8004ca4438fb8bfbff00",
  gasLimit: 800000000,
  gasUsed: 217736,
  hash: "0x87958a6f4f8f784d5e6b6978426ad3472fe5595412f1bcc76c5a5b65d639057d",
  logsBloom: "0x00000000080000000000000000000000000000000000000000000100000000000000000000000000800000000000000100000020001000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000400000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x67dfc9f75948217d13494775c31ac87494e7553b",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 92843,
  parentHash: "0xf9b1110c2b5c7e0b5fb9477ec6e13eb2a325f7b387db958401352b729c24d322",
  receiptsRoot: "0x7daf36a2198953744f5ec92bd695310df0d320dd70d1fa5b6a2dedad5656eb30",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 1604,
  stateRoot: "0x58aa00136f952a6ba4acfe6ea63fc3a01fbae88da3ada44fb348137c6679c551",
  timestamp: 1522161701,
  totalDifficulty: 9.5385824456373832306235717e+25,
  transactions: ["0xcf8549dbcecf0ee13bcce69ceaa7bda6c875f216603b9da63e28695afc9dc290", "0x5b686081418fd0a4de12b3ca7e7401cb9eab2078695d2e2456d77f9f58d9bac5", "0x2a9be55ae13b1b82d4d45d6949e457d6aa5929c20f78c3929b365ca264f827c4", "0xbf8c7f56ed641a18801a36e4aa45915d910f170e709f98a9e4da558080ef2e3a", "0xafd52a78f3859886885dd21536ac0d29dc1ae38486ff773ed2d9f84ec8958b83", "0xcce166e3a6f9e1265259917e486040b76fc405a18eb517ca14c526a05392bfaa"],
  transactionsRoot: "0x46c1490bac7d23840c974acac36703e21e6250a23e277203a2658ba8cbe4d285",
  uncles: []
}



Error log:
I0328 13:47:01.772144 eth/downloader/downloader.go:876] Downloading block bodies from #92843
I0328 13:47:01.772163 eth/downloader/downloader.go:900] Downloading receipts from #92843
I0328 13:47:01.772152 eth/downloader/downloader.go:734] Peer 09accfe64477bd7d [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: directing header downloads from #92843
I0328 13:47:01.772252 eth/downloader/downloader.go:749] Peer 09accfe64477bd7d [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: fetching 192 skeleton headers from #92843
I0328 13:47:01.772277 eth/peer.go:209] Peer 09accfe64477bd7d [eth/63] fetching 128 headers from #93034, skipping 191 (reverse = false)
I0328 13:47:01.776796 eth/downloader/downloader.go:845] Filling up skeleton from #92843
I0328 13:47:01.877140 eth/downloader/downloader.go:1126] Peer 09accfe64477bd7d [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: requesting header(s) from #92843
I0328 13:47:01.877209 eth/peer.go:209] Peer 09accfe64477bd7d [eth/63] fetching 192 headers from #92843, skipping 0 (reverse = false)
I0328 13:47:01.886831 p2p/discover/udp.go:453] >>> 10.35.231.38:33445 discover.findnode
I0328 13:47:01.887094 p2p/discover/udp.go:453] >>> 172.17.0.1:45342 discover.findnode
I0328 13:47:01.892554 p2p/discover/udp.go:453] >>> 10.35.231.107:22001 discover.findnode
I0328 13:47:01.892956 p2p/discover/udp.go:521] <<< 10.35.231.38:33445 *discover.neighbors: ok
I0328 13:47:01.893253 p2p/discover/udp.go:521] <<< 172.17.0.1:45342 *discover.neighbors: ok
I0328 13:47:01.894677 eth/downloader/queue.go:920] 09accfe64477bd7d: pre-scheduled 192 headers from #92843
I0328 13:47:01.894713 eth/downloader/downloader.go:1040] Peer 09accfe64477bd7d [hs 1096.26/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 18.001751413s]: delivered 192 header(s)
I0328 13:47:01.894752 eth/downloader/downloader.go:1126] Peer 09accfe64477bd7d [hs 1096.26/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 18.001751413s]: requesting header(s) from #93035
I0328 13:47:01.894784 eth/peer.go:209] Peer 09accfe64477bd7d [eth/63] fetching 192 headers from #93035, skipping 0 (reverse = false)
I0328 13:47:01.896099 eth/downloader/downloader.go:1128] Peer 09accfe64477bd7d [hs 1096.26/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 18.001751413s]: requesting 2 body(s), first at #92843
I0328 13:47:01.896146 eth/peer.go:216] Peer 09accfe64477bd7d [eth/63] fetching 2 block bodies
I0328 13:47:01.896574 p2p/discover/udp.go:521] <<< 10.35.231.107:22001 *discover.neighbors: ok
I0328 13:47:01.904488 eth/fetcher/fetcher.go:252] [eth/62] filtering 2:2 bodies
I0328 13:47:01.904664 eth/downloader/downloader.go:1040] Peer 09accfe64477bd7d [hs 1096.26/s, bs 23.44/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.202429397s]: delivered 2:2 body(s)
I0328 13:47:01.905479 eth/downloader/downloader.go:1128] Peer 09accfe64477bd7d [hs 1096.26/s, bs 23.44/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 16.202429397s]: requesting 128 body(s), first at #92845
I0328 13:47:01.906212 eth/peer.go:216] Peer 09accfe64477bd7d [eth/63] fetching 128 block bodies
I0328 13:47:01.909944 eth/downloader/queue.go:920] 09accfe64477bd7d: pre-scheduled 192 headers from #93035
I0328 13:47:01.909973 eth/downloader/downloader.go:1040] Peer 09accfe64477bd7d [hs 2250.13/s, bs 23.44/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 14.583706042s]: delivered 192 header(s)
I0328 13:47:01.910002 eth/downloader/downloader.go:1126] Peer 09accfe64477bd7d [hs 2250.13/s, bs 23.44/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 14.583706042s]: requesting header(s) from #93227
I0328 13:47:01.910030 eth/peer.go:209] Peer 09accfe64477bd7d [eth/63] fetching 192 headers from #93227, skipping 0 (reverse = false)
I0328 13:47:01.910380 eth/downloader/downloader.go:1340] Inserting chain with 2 items (#92843 [87958a6f…] - #92844 [f3ab8b93…])
I0328 13:47:01.911134 core/state/statedb.go:431] (+) 0000000000000000000000000000000000000000
I0328 13:47:01.911257 core/vm/vm.go:120] running byte VM 60e64bcb
I0328 13:47:01.911531 core/vm/vm.go:123] byte VM 60e64bcb done. time: 258.741µs instrc: 136
I0328 13:47:01.912183 core/vm/vm.go:120] running byte VM ec3a6737
I0328 13:47:01.912254 core/vm/vm.go:123] byte VM ec3a6737 done. time: 53.264µs instrc: 9
I0328 13:47:01.912270 core/state_transition.go:284] VM call err: invalid jump destination (PUSH1) 0
E0328 13:47:01.912630 core/blockchain.go:1262] Bad block #92843 (0x87958a6f4f8f784d5e6b6978426ad3472fe5595412f1bcc76c5a5b65d639057d)
E0328 13:47:01.912645 core/blockchain.go:1263]     GasLimit reached. Have 0 gas, transaction requires 92060
I0328 13:47:01.912668 eth/downloader/downloader.go:1382] Result #92843 [87958a6f…] processing failed: GasLimit reached. Have 0 gas, transaction requires 92060
I0328 13:47:01.912705 eth/downloader/downloader.go:866] Skeleton fill terminated: block header download canceled (requested)
I0328 13:47:01.912722 eth/downloader/downloader.go:892] Block body download terminated: block body download canceled (requested)
I0328 13:47:01.912736 eth/downloader/downloader.go:973] Node state data download terminated: state data download canceled (requested)
I0328 13:47:01.912717 eth/downloader/downloader.go:795] Peer 09accfe64477bd7d [hs 2250.13/s, bs 23.44/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 14.583706042s]: skeleton chain invalid: block header download canceled (requested)
I0328 13:47:01.912765 eth/downloader/downloader.go:796] Peer 09accfe64477bd7d [hs 2250.13/s, bs 23.44/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 14.583706042s]: header download terminated
I0328 13:47:01.912747 eth/downloader/downloader.go:916] Receipt download terminated: receipt download canceled (requested)
I0328 13:47:01.912787 eth/downloader/downloader.go:393] Synchronisation terminated after 143.880721ms
I0328 13:47:01.912804 eth/downloader/downloader.go:301] Removing peer 09accfe64477bd7d: retrieved hash chain is invalid
I0328 13:47:01.912814 eth/handler.go:192] Removing peer 09accfe64477bd7d
I0328 13:47:01.912822 eth/downloader/downloader.go:267] Unregistering peer 09accfe64477bd7d
I0328 13:47:01.912866 p2p/peer.go:180] Peer 09accfe64477bd7d 10.35.231.107:56114: locally requested disconnect: Useless peer
I0328 13:47:01.912948 eth/handler.go:309] Peer 09accfe64477bd7d [eth/63]: message handling failed: EOF
I0328 13:47:01.913029 p2p/server.go:740] Removed Peer 09accfe64477bd7d 10.35.231.107:56114 (Useless peer)
