### ISSUE TITLE
Remote connection disconnect

### ISSUE THREAD

**Issue by anistark** [Consensys-Incorporated/quorum#194]
#### System information

Geth version: `geth version`

```
Geth
Version: 1.6.5-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.8.3
Operating System: darwin
```

OS & Version: OSX

#### Expected behaviour

Should have just connected

#### Actual behaviour

```
    default: Warning: Connection reset. Retrying...
    default: Warning: Remote connection disconnect. Retrying...
```

#### Steps to reproduce the behaviour

* Cloned the repo.
* Ran `vagrant up`

**Comment by patrickmn** [comment]
If this is during `vagrant up`, it's pretty normal for the SSH connection to fail a couple of times before it succeeds. Have you tried letting it retry for a while?

**Comment by anistark** [comment]
I did. After multiple times of retry, I posted this.

**Comment by patrickmn** [comment]
Can't reproduce this
