### ISSUE TITLE
Tokens on quorum

### ISSUE THREAD

**Issue by arshbucks** [Consensys-Incorporated/quorum#199]
(note: this is def more of a question than an issue, so if there is a better place to ask, please let me know.)

As described in the discussion in #98  , Quorum has the ability to set gas limit per transaction, but just to stop infinite execution. **I am wondering if it is possible to issue a token on Quorum, in order to control usage of the network** -- even in a permissioned blockchain, party A might create 1000 transactions per hour, and party B only 10; so shouldn't A pay more for the use of the network?

Is there an existing **proper** way in Quorum to do this, that differs from Ethereum - and what are the security/integrity implications to be aware of, based on the difference in consensus mechanism?
**Maybe another way of asking this is, if there is no POW or POS+other method, and it doesn't cost any gas to confirm a transaction, what is the proper way to spend/award tokens?**
 Am new to this so please forgive ignorance - my thoughts are below & would appreciate any insight. 

1) We can't do this by asking A to run multiple voting nodes, because this could violate integrity if A is large enough - right?
2) But could we use tokens as a way to **"meter"** the network usage - and how would we create/issue these tokens? Perhaps controlled by the network itself via a Voting Smart Contract?  Could they be issued to each node upon block creation by each node?
3) And if party A wants to buy additional tokens via USD, because they are early & there aren't enough blocks to give them all the tokens they need, there would need to be a mechanism, perhaps by the network creators/initial members to transfer those tokens outside of the network, similar to trading after an ICO. 

Thank you!

**Comment by crackcomm** [comment]
One solution that comes to my mind is to create a contract that would count additional fees per transaction.

**Comment by patrickmn** [comment]
Quorum doesn't currently have a good story for network metering. As @crackcomm mentioned, you could possibly encapsulate some of these controls via a proxy contract.

Leaving this open as a feature request since this will become important for semi-public networks.

**Comment by ghost** [comment]
Why shouldn't it be possible to create a token on Quorum? As soon as I deploy a contract with the functionality of a token I have created a token, haven't I?

Or would there be any problem to deploy the following basic contract on Quorum??

```
contract MyToken {
    /* This creates an array with all balances */
    mapping (address => uint256) public balanceOf;

    /* Initializes contract with initial supply tokens to the creator of the contract */
    function MyToken(
        uint256 initialSupply
        ) {
        balanceOf[msg.sender] = initialSupply;              // Give the creator all initial tokens
    }

    /* Send coins */
    function transfer(address _to, uint256 _value) {
        require(balanceOf[msg.sender] >= _value);           // Check if the sender has enough
        require(balanceOf[_to] + _value >= balanceOf[_to]); // Check for overflows
        balanceOf[msg.sender] -= _value;                    // Subtract from the sender
        balanceOf[_to] += _value;                           // Add the same to the recipient
    }
}
```

Also check this application [https://github.com/blk-io/erc20-rest-service](https://github.com/blk-io/erc20-rest-service). It also runs on Quorum.

**Comment by arshbucks** [comment]
@saitam1 my takes is, that is fine in cases where you trust the network to use it as the governing contract for tokens, but part of my point was that there is a "gradient" of trust in the network, which a token could help mitigate by enforcing metering...so perhaps token usage for transactions should be enabled in the protocol instead of setting the gas price to 0.

Alternatively, I suppose you could issue tokens on the Ethereum network ("ico") and and validate them via a contract on the quorum network? (the erc20-rest-service you mention could be handy here - will check it out thanks)

Correct me if i'm wrong on any of the above...

**Comment by bansatya** [comment]
I am working on similar stubs but facing issue in private state if I add 'require' check within the transfer.
Lets take an example within 3 quorum node A,B and C.

I have deployed similar private contract in B by keeping the 'private for' as A, C . Next I minted some token (500) for B (Access mint function) from B by keeping  the 'private for' as A.
Checked the balance at B(account[0]), it displayed correctly at B i.e. 500.

Now I transferred few tokens (100) to C (account[0]) by executing transfer function and keeping the party as 'C' in the private transaction. Checked the balance of B at B  -> 400 and balance of C at B ->100(as expected).

However, while checking the balance of C at C, it is showing as 0, although C is the party (in 'private for') in the transfer transaction!!!
However, if we remove the 'require' check from transfer function, the state at 'C' updated properly and display the correct balance of C at C node.

Not sure why the state at C is not updated correctly if we add require check.

**Comment by ghost** [comment]
What does your contract look like? Is it an ERC20 token?

**Comment by bansatya** [comment]
@saitam1 yes, It's ERC20 token

**Comment by ricardolyn** [comment]
Closing. Duplicate of https://github.com/ConsenSys/quorum/issues/173
