### ISSUE TITLE
Windows: quorum-examples *.sh line endings not compatible with Linux subsystem

### ISSUE THREAD

**Issue by ushakrishnan** [Consensys-Incorporated/quorum#20]
Helpful changes / additions to readme -

1. Minor directory error
`ubuntu@ubuntu-xenial:~$ cd quorum-examples/examples/7nodes`
should read
`ubuntu@ubuntu-xenial:~$ cd quorum-examples/7nodes`

2. On Windows while downloading from git, line returns (^M) are added to .sh / bash scripts.  This causes issues when doing ./init.sh or ./start.sh . . . 
Easy fix - install dos2unix
`sudo apt-get install dos2unix`
Run dos2unix on all .sh files before executing bash commands

**Comment by patrickmn** [comment]
Fixed 1. Could you pull the latest quorum-examples repository and tell me if the line ending problem persists?

**Comment by ushakrishnan** [comment]
Item 2 issue still exists with the latest pull.  Images attached.
![basherror](https://cloud.githubusercontent.com/assets/18739265/20625284/5e3d8536-b2e0-11e6-922a-1382fecffa5a.JPG)
![afterdos2unix](https://cloud.githubusercontent.com/assets/18739265/20625283/5e39868e-b2e0-11e6-8dda-56dd53ba69e4.JPG)

**Comment by patrickmn** [comment]
Try removing the repo and cloning it from scratch again?

I've attempted to apply autocrlf to *.sh files in that repo: https://github.com/jpmorganchase/quorum-examples/commit/97f462924636156508827a793bd47df506db05d0

You can also apply that setting globally for your git with `git config --global core.autocrlf true`

By the way: you may find it easier to work with the [Vagrant environment](https://github.com/jpmorganchase/quorum-examples/blob/master/README.md), especially on Windows.

**Comment by ushakrishnan** [comment]
Attempt 1:
Completely destroyed vagrant and recloned from scratch - issue still exits (but works after dos2unix)

Attempt 2:
Completely destroyed vagrant again; globally set cleanup command -  `git config --global core.autocrlf true`; recloned from scratch - issue still exists, but was able to continue with dos2unix on init, have not gone through rest of the clean up.  Will do one by one (of .sh) looking through the code for invoking scripts.  Will that help?

*thanks for the tip on global config :-)

**Comment by chetan** [comment]
I think git for Windows has an option to autoconvert line endings on checkout/commit. That might be what's going on here.

**Comment by ushakrishnan** [comment]
Here is the config on git - note: core.autocrlf=true
![gitconfig](https://cloud.githubusercontent.com/assets/18739265/20633777/08884a62-b318-11e6-9f23-4b4a52d9bca0.JPG)

**Comment by chetan** [comment]
I think it should actually be set to false so that the line endings aren't modified on checkout:

http://stackoverflow.com/a/2825829

**Comment by ushakrishnan** [comment]
Ok, let me try that.  I probably misunderstood an earlier comment. Thanks, will try.

Another option would be to add it to gitattributes for the project like mentioned here - https://help.github.com/articles/dealing-with-line-endings/

**Comment by patrickmn** [comment]
Did autocrlf=false work?

**Comment by ushakrishnan** [comment]
Sorry for the delay.  Did not work.
![capture](https://cloud.githubusercontent.com/assets/18739265/20652109/4d44a740-b4c1-11e6-96bf-90d11ce99a03.JPG)

**Comment by patrickmn** [comment]
I made another attempt to fix this issue and I can no longer reproduce it. Could you try pulling the examples repo and rebuilding the vagrant environment? Hopefully for the last time.

**Comment by ushakrishnan** [comment]
Perfect, it worked.  Thank you very much.  Love the way the fabric is extended, enjoying experimenting quorum.  Cheers!!
