### ISSUE TITLE
Private contract mining giving error when nodes running in distributed environment

### ISSUE THREAD

**Issue by Purbaja** [Consensys-Incorporated/quorum#206]
Hi All,
I have made a setup where multiple quorum nodes are running in different servers and I am able to establish peering between them,
but when I am trying to mine a private contract, getting below error :
"Error: Invalid JSON RPC response: {"error":{"EOF":"EOF","code":-32603},"id":9,"version":"2.0"} undefined"

Here is my contract abi :
var testContract = web3.eth.contract([{"constant":false,"inputs":[],"name":"getValue","outputs":[{"name":"a","type":"uint256"}],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":false,"inputs":[{"name":"a","type":"uint256"}],"name":"setValue","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"}]);
var test = testContract.new(
   {
     from: web3.eth.accounts[0], 
     data: '0x6060604052341561000f57600080fd5b60ce8061001d6000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063209652551460465780635524107714606c57600080fd5b3415605057600080fd5b6056608c565b6040518082815260200191505060405180910390f35b3415607657600080fd5b608a60048080359060200190919050506098565b005b60008054905080905090565b80600081905550505600a165627a7a7230582024e016d5e5847222cc207652bed2e9ed9b95abe6ae8f9e2acf46d6ac5f401d740029', 
     gas: '4700000',
     privateFor: ["BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="]
   }, function (e, contract){
    console.log(e, contract);
    if (typeof contract.address !== 'undefined') {
         console.log('Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);
    }

**Comment by patrickmn** [comment]
Please run `constellation-node` with `-vv` and paste the logs for the sending node.
