### ISSUE TITLE
Why make empty blocks?

### ISSUE THREAD

**Issue by joeb000** [Consensys-Incorporated/quorum#21]
I am wondering why block making in quorum still makes (mines) empty blocks with no transactions (bloating the state storage). I can't imagine any use cases where this is necessary. When mining on a private network with ethereum geth, there's a way to use a javascript "[hack](https://github.com/ethereum/go-ethereum/wiki/bitchin-tricks#mining)" to prevent empty blocks from being mined. Hoping this feature will be baked into the client for quorum. I'd be happy to take a crack at developing it and creating a pull request, just wondering if theres any reason its not viable.

**Comment by davoell** [comment]
Having the ability to prevent mining empty blocks is a great idea. We leveraged the feature you describe ourselves in our pre-Quorum work. It just wasn't a high enough priority for us given the use cases we're considering for Quorum which are all in the multiple tx/sec range but it would be terrific if you would like to take a crack at developing this. We expect to be able to accept pull requests very soon.
