### ISSUE TITLE
Geth attach: quorum API is not available

### ISSUE THREAD

**Issue by andr11111** [Consensys-Incorporated/quorum#221]
#### System information

Geth version: `quorum 2.0.0 (geth 1.7.2-stable)`

OS & Version: OSX

Branch, Commit Hash or Release: `3d91976f08074c1f7f605beaadf4b37783026d85`

#### Expected behaviour
Quorum API is available after `geth attach ipc:qdata/dd2/geth.ipc`

#### Actual behaviour
Quorum API is not available after `geth attach ipc:qdata/dd2/geth.ipc`. 
I see the following output (note `quorum` is not in the list of modules):
```
ubuntu@ubuntu-xenial:~/quorum-examples/7nodes$ geth attach ipc:qdata/dd2/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/vquorum 2.0.0 (geth 1.7.2-stable)-3d91976f/linux-amd64/go1.7.3
coinbase: 0xca843569e3427144cead5e4d5999a3d0ccf92b8e
at block: 1 (Fri, 05 May 47866856254 07:10:55 UTC)
 datadir: /home/ubuntu/quorum-examples/7nodes/qdata/dd2
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 raft:1.0 rpc:1.0 txpool:1.0 web3:1.0

> quorum.nodeInfo
ReferenceError: 'quorum' is not defined
    at <anonymous>:1:1
```

#### Steps to reproduce the behaviour
Follow regular steps for 7nodes example. 
```
cd quorum-examples/7nodes
./raft-init.sh
./raft-start.sh
geth attach ipc:qdata/dd2/geth.ipc
```

**Comment by 0xAozora** [comment]
Did you Cross-Compile Quorum?

**Comment by andr11111** [comment]
I used the exact steps outlined in the Readme:
```
git clone https://github.com/jpmorganchase/quorum-examples
cd quorum-examples
vagrant up
vagrant ssh
ubuntu@ubuntu-xenial:~$ cd quorum-examples/7nodes
./raft-init.sh
./raft-start.sh
```

**Comment by thpun** [comment]
Is it because QuorumChain consensus is not currently supported by Quorum 2.0.0?

**Comment by simonmullaney** [comment]
I have the same issue:


geth attach http://localhost:22001
Welcome to the Geth JavaScript console!

instance: Geth/v1.5.0-unstable-ddb011f3/linux/go1.8
coinbase: 0x0273a34fb1908b818c09e7f0806bd6195c1d2b46
at block: 15 (Tue, 21 Nov 2017 17:11:50 GMT)
 datadir: /node2/qdata
 modules: admin:1.0 debug:1.0 eth:1.0 net:1.0 personal:1.0 quorum:1.0 rpc:1.0 txpool:1.0 web3:1.0

> quorum
ReferenceError: 'quorum' is not defined
    at <anonymous>:1:1

**Comment by r-nv** [comment]
I have the same issue and it throws "EOF undefined" error when using privateFor: in creating contract object. I think both are connected issues.

**Comment by amanuelz91** [comment]
Same issue for me ...

**Comment by ijazm** [comment]
Have any one sorted this issue? I am also facing the same issue ReferenceError: 'quorum' is not defined

**Comment by kaizenlabs** [comment]
Any update on this? Feel like this is a pretty big hole...

**Comment by patrickmn** [comment]
The `quorum` namespace was mostly for dealing with QuorumChain, which is not included currently in Quorum 2.0. However, there are some other utility functions like `getPrivatePayload` and `runPorosity` which will be likely be re-added under `quorum` in the near future.

**Comment by pindaroso** [comment]
Same issue.

**Comment by didil** [comment]
same issue

**Comment by conor10** [comment]
@patrickmn any idea how far off this is?

**Comment by evan-morgan** [comment]
quorum.nodeInfo still returning a "ReferenceError: 'quorum' is not defined"

**Comment by patrickmn** [comment]
@conor10 ~1 week or so

**Comment by EdsonAlcala** [comment]
any updates? :D

**Comment by fixanoid** [comment]
Merging into #520
