### ISSUE TITLE
Node SYN Floods? Local Network

### ISSUE THREAD

**Issue by 0xAozora** [Consensys-Incorporated/quorum#222]
#### System information

Geth version: `1.5.0-unstable-949b5c0d` and `1.7.2-stable`
OS & Version: Any
Branch, Commit Hash or Release: `master`

#### Expected behaviour

 Browsing the web just fine with the node running in the background

#### Actual behaviour

"Private" Node tries to find other nodes in the internet, sends a wave of SYN Packets, and other clients in the LAN experience tcp packet loss.

#### Steps to reproduce the behaviour

I ran geth in raft mode, without nodiscover parameter . here is my genesis.json:

{
  "config": {
		"chainId": 15,
		"homesteadBlock": 0,
		"eip155Block": 0,
		"eip158Block": 0
  },
  "alloc": {
    "621146c31e24c852d23234a95ae0f49839bca1d9": { 
        "balance": "1606938044258990275541962092341162602522202993782792835301376"
    }
  },
  "nonce": "0x000000000000002a",
  "difficulty": "0x020000",
  "mixhash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "extraData": "0x",
  "gasLimit": "0x2fefd8"
}

#### Backtrace

````
[backtrace]
````

Here is a screenshot instead:
![78a98136eaf3bf9256b6f6250526e8e0](https://user-images.githubusercontent.com/12783903/32739173-5cc98436-c89f-11e7-982a-a3f65ade6e69.jpg)

I am running a tcping test on windows while having the node on the vm and listing all tcp connections.
UDP and ICMP connections work just fine, just TCP packets get lost.

**Comment by patrickmn** [comment]
Is this still an issue on Quorum 2.0.0?
