### ISSUE TITLE
Cross Compiling Geth doesnt offer full Quorum Functionality

### ISSUE THREAD

**Issue by 0xAozora** [Consensys-Incorporated/quorum#223]
#### System information

Geth version: `1.7.2-stable`
OS & Version: Any
Branch, Commit Hash or Release: `master`

#### Expected behaviour

Node is supposed to work fine I guess

#### Actual behaviour

Examples:
-  --permissioned parameter doesnt work,

Including standard compilation:
-  out of gas errors ( --gasprice "0" parameter doesnt help either )
-  quorum api not available

#### Steps to reproduce the behaviour

make geth-cross

#### Backtrace

````
[backtrace]
````

**Comment by 0xAozora** [comment]
Turns out I was using the newer version on my raspberry pi and the 1.5 one on the linux vm.
--permissioned parameter does in fact not work on cross compiled nodes, but the other two issues I found apply to linux 64bit aswell, compiled with 'make all'

**Comment by patrickmn** [comment]
- out of gas: Do you mean when sending a transaction? Currently you still need to fund accounts with ether even if gasprice is 0.

- `quorum` api is not available: https://github.com/jpmorganchase/quorum/issues/221

**Comment by 0xAozora** [comment]
I prefunded the address in the genesis block.

**Comment by patrickmn** [comment]
The `--permissioned` issue should be fixed by https://github.com/jpmorganchase/quorum/pull/261

**Comment by fixanoid** [comment]
Please reopen if this is still an issue. Thanks.
