### ISSUE TITLE
Unable to vote: no contract code at given address

### ISSUE THREAD

**Issue by anupamj** [Consensys-Incorporated/quorum#224]
#### System information

Geth version: `geth version`
Geth
Version: 1.5.0-unstable
Git Commit: 647025ed8a504decfb11ac29bb44b3b2db703071
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Steps to reproduce the behaviour
Did a setup for the 7node example using the default genesis file.  The transaction got submitted successfully but it remains in the pending state and doesnot get completed. 

==> qdata/logs/1.log <==
E1115 12:23:47.961911 core/quorum/block_voting.go:280] Unable to vote: Node is not configured for voting

==> qdata/logs/2.log <==
E1115 12:23:47.230187 core/quorum/block_voting.go:280] Unable to vote: no contract code at given address

==> qdata/logs/constellation1.log <==
2017 Nov-15 06:45:04587975 [INFO] Log level is LevelWarn

==> qdata/logs/constellation2.log <==
2017 Nov-15 06:50:23210279 [WARN] Error performing API request: ApiReceive (Receive {rreqKey = "4hbFBpqMpsFfQDtICcoHtbp20zwD6NxP0zFe4tBnCPONRdGntGe3WerrsSbEsNcBleSKO5LNY5MS2WInyTh9Hw==", rreqTo = "QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="}); Key not found in BerkeleyDb payload.db

Can someone please guide on what might be wrong with the setup. Looks like the voting nodes are not able to find the contract. How can I fix this ?

**Comment by joelburget** [comment]
The version of quorum-examples you're using was probably for quorum 2.0, which removed QuorumChain. The easiest fix is to upgrade your quorum to 2.0.0 and use Raft or Istanbul consensus.

**Comment by john-osullivan** [comment]
@joelburget @patrickmn 

I'm a developer working on a fork of Quorum which still uses QuorumChain consensus, but adds on an additional governance layer which is in another smart contract.  This change also required a small modification to one of the modifiers in the `BlockVoting` contract.  

I've made a modified version of the genesis block with the `unlinked_binary` from both of the contracts, `BlockVoting` is at its initial address.  However, when I turn on the chain, I get this same error right here -- this is the only issue I've found online related to it.

Based on my debugging and error tracing, this probably means the `BlockVoting` contract couldn't be found at its given address.  I haven't changed its address in the genesis block, though, and I can't find any hardcoded addresses in `core/quorum/block_voting.go`.

Any tips on what the underlying issue might be here?  

--- 
**Update:** I've now tried regenerating the `core/quorum/binding.go` using my new ABI, but that unfortunately didn't change the error.  The error's source is the `bv.isBlockMaker` called in `core/quorum/block_voting.go`, which eventually traces back through to a `VotingContractCaller` which has a `BoundContract`.

---
**Update 2:** Should've trusted the error message -- inspecting the block voting address (`0x0000000000000000000000000000000000000020`) with `eth.getCode()` showed that it is in fact empty.  The listed `gasLimit` on the block is pretty astronomical, so we ought to be able to deploy this contract, but it looks like nothing got there.  

Is there another gas limit specifically on the genesis block someplace?

---
**Update 3:** Just verified that both contracts were compiled via `solc --bin-runtime`, eliminating one other failure case.  Still not seeing any code there, even though it's very clearly shown in the genesis block.

---
**Update 4:** Resolved!  In case future debuggers come across this path, I did need all of the previous changes (modifying `binding`, running with `--bin-runtime`), but the last problem ended up being dead simple.  `alloc.address.code` values in the genesis block should not be pre-pended with an `0x`, as other hex values in Ethereum typically are.  Just put in exactly what comes out of `solc` and you should be good to go!
