### ISSUE TITLE
Read Error for permissioned-nodes.json file.

### ISSUE THREAD

**Issue by sumitr-tech** [Consensys-Incorporated/quorum#225]
#### System information

Geth version: `geth version`

Geth
Version: 1.7.2-stable
Git Commit: a6f117d13818d3e685181533404297ff61dbbd42
Quorum Version: 2.0.0
Architecture: amd64
Network Id: 1
Go Version: go1.8.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

#### Expected behavior
admin.peers show nodes define in permissioned-nodes.json file.

#### Actual behaviour
ERROR[11-14|16:50:33] Read Error for permissioned-nodes.json file. This is because 'permissioned' flag is specified but no permissioned-nodes.json file is present. err="stat permissioned-nodes.json: no such file or directory"

#### Steps to reproduce the behaviour
Have setup two nodes quoram permissioned network based on Raft Consensus
But when Start node I got following error 

ERROR[11-14|16:50:33] Read Error for permissioned-nodes.json file. This is because 'permissioned' flag is specified but no permissioned-nodes.json file is present. err="stat permissioned-nodes.json: no such file or directory"

I already added permissioned-nodes.json file in datadir.

**Comment by sumitr-tech** [comment]
Resolve issue by downgrade quoram version
Use v1.2.1

**Comment by patrickmn** [comment]
cc @joelburget

**Comment by zean00** [comment]
I have same issue, and after enabling debug, turns out the DataDir variable is empty since I execute geth command from root path. It seems that the DataDir variable is refer to the Working Directory when execute geth and it's looking for permissioned-nodes.json on the working directory not from argument --datadir

**Comment by joelburget** [comment]
Fixed by #261
