### ISSUE TITLE
flag provided but not defined: -voteaccount

### ISSUE THREAD

**Issue by sivachaitanya** [Consensys-Incorporated/quorum#229]
#### System information

Geth version: `geth version`
1.7.3

OS & Version: Windows/Linux/OSX
Ubuntu 1.6

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
when I run "PRIVATE_CONFIG=tm6.conf nohup geth --datadir qdata/dd6 $GLOBAL_ARGS --rpcport 8545 --rpccorsdomain "*" --port 21000 --unlock 0 --password passwords.txt --voteaccount "0xf3c66ab8c520230654190df0048d49fd0a1502ae" --votepassword ""  2>>qdata/logs/6.log &"  geth should start without any error

#### Actual behaviour
nohup: appending output to 'nohup.out'
flag provided but not defined: -voteaccount

#### Steps to reproduce the behaviour
1. I downloaded the 7 nodes example
2. Because I'm installing manual 1 node setup, commented out other script lines
3. Followed steps - https://github.com/jpmorganchase/quorum/issues/69
cd
mkdir -p go/src/github.com/ethereum
cd go/src/github.com/ethereum
git clone https://github.com/jpmorganchase/quorum go-ethereum
export GOPATH=~/go
go get github.com/ethereum/go-ethereum/cmd/geth
cd ~/go/bin
./geth version

#### Backtrace

````
[backtrace]
````

**Comment by xiaohua0921** [comment]
I meet the same question ， and I tried to do it with the above method , but it still has the question.
My command is   " geth --datadir=~/chain-data-quorum_vote  --rpccorsdomain "*" --nodiscover --voteaccout "0xeb6902c98ed64b7b16f743a7c09b36b8fa-votepassword "" --rpc --rpcaddr 0.0.0.0 --rpcport 8000 "

**Comment by akkiensama** [comment]
I met the same issue when i follow the Quorum setup step https://github.com/jpmorganchase/quorum/wiki/From-Scratch. I stuck at step 9 and this is file node.log:
```
nohup: ignoring input and appending output to 'nohup.out'
flag provided but not defined: -raft
```

I found that geth command line actually do not have -raft, -raftport, -emitcheckpoints.
@sivachaitanya how did you solve the problem

**Comment by prd-fox** [comment]
@akkiensama Can you open a new issue with all the details please?

**Comment by akkiensama** [comment]
I solve the issue now. The problem is my system confuse "geth Ethereum" and "geth Quorum".
@prd-fox thanks a lot for your attention

**Comment by Krish1979** [comment]
➤ Trung Kien commented:

I met the same issue when i follow the Quorum setup step https://github.com/jpmorganchase/quorum/wiki/From-Scratch. I stuck at step 9 and this is file node.log:

nohup: ignoring input and appending output to 'nohup.out'
flag provided but not defined: -raftI found that geth command line actually do not have -raft, -raftport, -emitcheckpoints.
sivachaitanya how did you solve the problem

**Comment by Xychun** [comment]
> "

How to solve this confusion? Having same issue..

**Comment by Xychun** [comment]
> I solve the issue now. The problem is my system confuse "geth Ethereum" and "geth Quorum".
> @prd-fox thanks a lot for your attention

How to solve this confusion? Having same issue..

**Comment by prd-fox** [comment]
You need to configure your system paths, or rename the executable. Again, please open new tickets, even for small issues.
