### ISSUE TITLE
Error to start the node

### ISSUE THREAD

**Issue by ferrhcp2017** [Consensys-Incorporated/quorum#231]
#### System information

Geth version: 1.7.2 - Stable

OS & Version: Linux Ubuntu 17

Branch, Commit Hash or Release: `git status`
Hi, I'm trying to start the node but I'm getting the following error message.

_**Fatal: invalid genesis file: json: can not unmarshal hex string without 0x prefix into Go struct field Genesis.alloc of type hexutil.Bytes**_

I'm using the genesis.json from the example page:

https://github.com/jpmorganchase/quorum/blob/master/docs/running.md

can anybody help me?
tks

**Comment by 0xAozora** [comment]
Try removing the 0x from the addresses you want to prefund. Thats what I did in my genesis.json.

Obviously the developers are getting paid to badly by jpmorgan to actually deal with questions, or working on a more detailed, up to date wiki

**Comment by SebLKMa** [comment]
Have a look at the commit history of examples/7nodes/genesis.json

  "alloc": {
    ...
      "code": "0x606060..." <-- 0x hex prefix added
      "storage": {
         ...
      },
      "balance": "1000000000000000000000000000" <-- added
  ...
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000", <-- corrected

HTHs
