### ISSUE TITLE
Can not get events from a public contract: invalid argument 0: hex number with leading zero digits

### ISSUE THREAD

**Issue by naddison36** [Consensys-Incorporated/quorum#235]
#### System information

Geth version: `geth version`
Version: quorum 2.0.0 (geth 1.7.2-stable)
Git Commit: 3d91976f08074c1f7f605beaadf4b37783026d85
Go Version: go1.9

OS & Version: Windows/Linux/OSX
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
Architecture: amd64

Branch, Commit Hash or Release: `git status`
Quorum 2.0.0

#### Expected behaviour
I should be able to get events from a deployed public contract with the following
`{"method":"eth_getLogs","params":[{"fromBlock":"0x01","toBlock":"latest","address":"0x868CE5acab25122B977398d23060eF40e47250e1","topics":["0x7c13173c065e3a307058ee9baa4a75e787d82d38348af6720b8aca2c2c5222fd"]}],"id":42,"jsonrpc":"2.0"}`

#### Actual behaviour
The following is being returned from the above rpc call
`{"jsonrpc":"2.0","id":42,"error":{"code":-32602,"message":"invalid argument 0: hex number with leading zero digits"}}`

#### Steps to reproduce the behaviour
I can make a simple contract to replicate the behaviour if that's needed.
I'm using the latest version of the Ethers.js library to get the events.

#### Backtrace

````
[backtrace]
````

**Comment by ygnr** [comment]
#github.com/ethers-io/ethers.js/pull/91

**Comment by ygnr** [comment]
Should be fixed by [this](https://github.com/ethers-io/ethers.js/pull/91) PR in ethers.js

**Comment by patrickmn** [comment]
Please confirm if this is not the case or another solution is needed.
