### ISSUE TITLE
Quorum module not exists

### ISSUE THREAD

**Issue by stevenooi** [Consensys-Incorporated/quorum#238]
quorum module doesnt seems to exist after running this command : geth attach ipc:qdata/dd1/geth.ipc

ubuntu@ubuntu-xenial:~/quorum-examples/7nodes$ geth attach ipc:qdata/dd1/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/vquorum 2.0.0 (geth 1.7.2-stable)-3d91976f/linux-amd64/go1.7.3
coinbase: 0xed9d02e382b34818e88b88a309c7fe71e65f419d
at block: 1 (Mon, 25 Apr 47913855892 20:09:35 UTC)
 datadir: /home/ubuntu/quorum-examples/7nodes/qdata/dd1
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 raft:1.0 rpc:1.0 txpool:1.0 web3:1.0

does anyone has this issue?

**Comment by patrickmn** [comment]
Refer to https://github.com/jpmorganchase/quorum/issues/221
