### ISSUE TITLE
Is there a mechanism to control the production of stale blocks ?

### ISSUE THREAD

**Issue by sivachaitanya** [Consensys-Incorporated/quorum#239]
#### System information

Geth version: 1.5.0

OS & Version: Ubuntu Linux

Branch, Commit Hash or Release: 0.10

#### Expected behaviour
Stale blocks can be controlled by some means

#### Actual behaviour
Stale blocks are eating up lot of disk space

#### Steps to reproduce the behaviour

I am running quroum on different cloud instances, the problem is for 3 days 3-4 GB of disk space has been consumed, my block times defined in genesis are 2-4 seconds. Is there a mechanism to controlthe production of stale blocks to optmise by disk space ?

**Comment by ashfaq-shaik** [comment]
@sivachaitanya 

I assume you are using Quorumchain as your consensus mechanism. Change your consensus to "RAFT". 

RAFT would create blocks on demand i,e. blocks will be created only if there are pending transactions in the network.

**Comment by Krish1979** [comment]
➤ Ashfaq Ahmed commented:

sivachaitanya

I assume you are using Quorumchain as your consensus mechanism. Change your consensus to "RAFT". 

RAFT would create blocks on demand i,e. blocks will be created only if there are pending transactions in the network.
