### ISSUE TITLE
About zsl_createABCProof

### ISSUE THREAD

**Issue by zyliutw** [Consensys-Incorporated/quorum#242]
I would like to know quorum how to generate the zsl-proof
In DApp server/adapter/networkAdapter.js  line359 call post method : zsl_createABCProof
But I couldn't find where the quorum node to handle this post method

Can anyone help me to solve this question?
Thanks a lot !

**Comment by mkqaimari** [comment]
I can't find zsl_createABCProof anywhere either!

I will look at the giy history of quorum as it might have been removed :|

**Comment by patrickmn** [comment]
Please make sure you're looking in either the `zsl_geth1.5` or `zsl_geth1.6` branch. `master` does not have ZSL yet (and that is what the Github UI indexes/searches.)

**Comment by zyliutw** [comment]
Yes, I searched the zsl_createABCProof in zsl_geth1.6 branch.
But I could not find it. THX

**Comment by mkqaimari** [comment]
zsl_createABCProof exists only is a custom-built binary provided with ubin-quorum.

I reverse-engineered the binary (geth) and it's calling the following zk-snark which I can't find on github either:

 github.com/ethereum/go-ethereum/vendor/github.com/Electric-Coin-Company/zsl-quorum/zsl-golang/zsl/snark.ProveABC

**Comment by fixanoid** [comment]
Closing as we've no intention at the moment to revisit ZSL prototype.
