### ISSUE TITLE
Contract deployment scenario breaks the networks and requires a restart

### ISSUE THREAD

**Issue by mkqaimari** [Consensys-Incorporated/quorum#244]
#### System information

Geth version: 1.7.2-stable-0905eda4

OS & Version: Linux -- Vagrant VBox instance

#### Expected behaviour

 I'm deploying a smart contract on the 7node quorum-example configuration with the privateFor array set to have 7 public keys of representing all nodes on the network including the contract-deploying node.

 The contract should be deployed and the private state should be visible to all nodes.

#### Actual behaviour
I'm receiving the following error:
Error deploying the smart contract:  Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Server:[Warp/3.2.13] Date:[Tue, 05 Dec 2017 08:32:02 GMT]] Body:0xc4250409c0 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc4355f12c0 TLS:<nil>}

This error is persistent. Once you receive it, the node will keep giving you this error until you restart the whole network.
 
#### Steps to reproduce the behaviour
Deploy any simple smart contract with the following privateFor attribute:

privateFor: [
                            "BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=",
                             "QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=",
                             "1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg=",
                             "oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8=",
                             "R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=",
                             "UfNSeSGySeKg11DVNEnqrUtxYRVor4+CvluI8tVv62Y=",
                             "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="
                             ]}

#### Backtrace

````
Error deploying the smart contract:  Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Server:[Warp/3.2.13] Date:[Tue, 05 Dec 2017 08:32:02 GMT]] Body:0xc4250409c0 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc4355f12c0 TLS:<nil>}
    at Object.InvalidResponse (/Users/mac/Desktop/Quorum/web3/node_modules/web3quorum/lib/web3/errors.js:38:16)
    at /Users/mac/Desktop/Quorum/web3/node_modules/web3quorum/lib/web3/requestmanager.js:86:36
    at XMLHttpRequest.request.onreadystatechange (/Users/mac/Desktop/Quorum/web3/node_modules/web3quorum/lib/web3/httpprovider.js:122:7)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:64:18)
    at XMLHttpRequest._setReadyState (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:354:12)
    at XMLHttpRequest._onHttpResponseEnd (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:509:12)
    at IncomingMessage.<anonymous> (/Users/mac/Desktop/Quorum/web3/node_modules/xhr2/lib/xhr2.js:469:24)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
````

**Comment by patrickmn** [comment]
Could you please provide the constellation logs and version as well?

**Comment by patrickmn** [comment]
This is due to https://github.com/jpmorganchase/quorum/issues/253#issuecomment-362651082

Please try with a `privateFor` array that does not include your own public key.

**Comment by robinbryce** [comment]
We have redundantly deployed quorum nodes for a single legal entity. We would like to failover transactions between the two. This bug means that we have to *dynamically* detect which tessera we are talking to. As tessera (or constelation) know which public key(s) are there own, what is the downside of simply droping the 'self' public keys before attempting the naCl operations ? We would very much appreciate it if this issue were re-opened

**Comment by robinbryce** [comment]
Ah, not this works. We can include the public tessera keys for the same tessera node we submit thirdparth/storeraw to without issue.
