### ISSUE TITLE
URL link for block_voting.sol is broken in docs/running.md

### ISSUE THREAD

**Issue by SebLKMa** [Consensys-Incorporated/quorum#246]
The URL link is broken in
https://github.com/jpmorganchase/quorum/blob/master/docs/running.md

Search for "voting smart contract", locate the paragraph below:

From the above example, the `<256 bit aligned key value>` is the ethereum account address that should be added to the voting map, ed9d02e382b34818e88b88a309c7fe71e65f419d, padded to 256bits. The `<256 bit variable index>` is the index(3) of the canVote mapping in the solidity [voting smart contract](https://github.com/jpmorganchase/quorum/blob/master/core/quorum/block_voting.sol#L42) padded to 256bits.

Shouldn't the URL link be ?
https://github.com/jpmorganchase/quorum/blob/3a9ef674b76acf981da26739c7795e6e8accd489/core/quorum/block_voting.sol

**Comment by patrickmn** [comment]
The just-merged https://github.com/jpmorganchase/quorum/pull/241 changes the docs to reflect the removal of Quorumchain consensus and thus the voting smart contract.
