### ISSUE TITLE
private contract event not reveive

### ISSUE THREAD

**Issue by fatel-openlev** [Consensys-Incorporated/quorum#250]
#### System information

Geth version: `1.7.2-stable`

OS & Version: Linux

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
I create a Contract without privateFor，transfer can receiver
 I create a Contract with privatefor param，transfer can not receiver
this is my Contract
contract CreditTest  {
  event transfer( uint types,bool result,address addr);
  int public status;
  function setStatus(int _status) public returns (bool){
    status=_status;
    transfer(0,true,this);
    return true;
  }

}

````
[backtrace]
````

**Comment by patrickmn** [comment]
Is this the same as https://github.com/jpmorganchase/quorum/issues/256 ?
