### ISSUE TITLE
Add "Connection" HTTP header with the value "close"

### ISSUE THREAD

**Issue by mkqaimari** [Consensys-Incorporated/quorum#251]
https://github.com/jpmorganchase/quorum/blob/0905eda48eb07a4ce0e7072c1a2ecbf690ddff77/private/constellation/node.go#L96

 The following line should be added so the server would close the connection once it's done sending back the response. Lingering connections from the client-side may cause the server to run out of connections (file descriptors to be specific).

req.Header.Set("Connection", "close")

**Comment by patrickmn** [comment]
I don't think this is the right solution. The open file descriptors limit shouldn't be saturated to begin with. What is your `ulimit -n` and are you sending a lot of transactions at once, or does this happen even under low load after a period of time?

**Comment by mkqaimari** [comment]
Hi!

 The ulimit got saturated in no time in a simple stress test since the cap is on file handles is 2048 in the ethereum code base.

I was trying to measure the max TPS I can get from Quorum and we achieved 120-140 tx/sec on the raft consensus method.
