### ISSUE TITLE
Is Quorum a good tool for secure a constant flow of data?

### ISSUE THREAD

**Issue by Xavopls** [Consensys-Incorporated/quorum#254]
Greets,

I am thinking about implementing a DLT for this scenario:

I have multiple devices with not constant internet connection (from 50 to 200 devices aprox.)
This devices get data constantly and then as soon as they are fed up, they send it to a No SQL server stored in the cloud.
The objective is implement Quorum to make this data private and only visible for the sender and the receiver entities.

The data is stored in JSON, so what would be uploaded to the blockchain? the file itself? (Huge amount of data)
Or some kind of identificator for the file?

Thank you very much, you really save my life and sorry for the novice question, I tried to contact Quorum support but got no response.

**Comment by patrickmn** [comment]
Is the purpose merely to authenticate the data later (i.e. prove that the data hashes to the same value that was published to the chain earlier), or also to back it up?

Constellation (i.e. private transactions) do work in a way that may be suitable for your use case: The transaction payloads are encrypted and transferred between Constellation nodes, and only a hash of that encrypted data is published to the chain. So in your case the data would be backed up in Constellation and authenticated by the hashes that are published to the Quorum network.
