### ISSUE TITLE
Are the Quorum command line arguments in quorum/docs/running.md valid ?

### ISSUE THREAD

**Issue by SebLKMa** [Consensys-Incorporated/quorum#255]
#### System information

Geth
Version: 1.7.2-stable
Git Commit: 0905eda48eb07a4ce0e7072c1a2ecbf690ddff77
Quorum Version: 2.0.0
Architecture: amd64
Network Id: 1
Go Version: go1.9.2
Operating System: linux

There is geth runtime error - 
Incorrect Usage. flag provided but not defined: -voteaccount

Is the document on Quorum command line args correct?

Refer to quorum/docs/running.md

QUORUM OPTIONS:
  --voteaccount value         Address that is used to vote for blocks
  --votepassword value        Password to unlock the voting address
  --blockmakeraccount value   Address that is used to create blocks
  --blockmakerpassword value  Password to unlock the block maker address
  --singleblockmaker          Indicate this node is the only node that can create blocks
  --minblocktime value        Set minimum block time (default: 3)
  --maxblocktime value        Set max block time (default: 10)

**Comment by cfengliu** [comment]
These args are for QuorumChain consensus, which has been depreciated but docs aren't updated

**Comment by patrickmn** [comment]
Yeah, https://github.com/jpmorganchase/quorum/pull/241 should have been merged. Doing it now.
