### ISSUE TITLE
scalability issue due to private channels?

### ISSUE THREAD

**Issue by arshbucks** [Consensys-Incorporated/quorum#258]
Trying to figure out  realness of/solution to scalability issue due to the way privateFor causes separate states. http://www.bitfwd.xyz/2017/09/28/battle-of-the-enterprise-chains-corda-vs-quorum/

Are there any improvements planned that would address this issue, or is it accepted by design (Or is this not really an issue altogether)?  Does this make quorum more suitable for say, securities that are generally "buy and hold" rather than "traded frequently"? 

> "In private contract channels each transaction payload is encrypted and a transaction containing only the encrypted transaction hash is broadcast to the public ledger, this ensures that the order of transactions in the private channel is established and agreed upon.
> 
> This channel based approach to privacy has some major issues for privacy and scalability. Let's say I want to form a private contract channel with ten banks and then want to trade with each one individually, all ten banks must update their private states to account for this change even though only two were involved, not only that but the public ledger needs a copy of the hash too.
> 
> Conversely, what happens when I want to trade an asset from one private contract channel to another? To do this I would have to create an intermediary contract which updates the state of both contracts. This is overly complex and highly inefficient."

**Comment by patrickmn** [comment]
This is a reason why we partnered with Zcash to add ZSL to Quorum. ZSL allows you to create and transact ERC20 tokens in public (not private) transactions whilst retaining privacy, mass preservation and prevention of double spend. A combination of business logic in (Constellation/privateFor) private transactions and public (but shielded) ZSL token transfers is how we recommend solving the problem you describe.

Please see the documentation at https://github.com/jpmorganchase/zsl-q
