### ISSUE TITLE
 coinbase & accounts 0 are diiferent when trying to setup istanbul network 

### ISSUE THREAD

**Issue by abhayar** [Consensys-Incorporated/quorum#259]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by abhayar** [comment]
I'm using istanbul tools only for extradata creation, but problem i'm facing problem with accounts..coinbase & account0 both are different.This is my genesis file:

{
  "config": {
    "chainId": 1234,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "istanbul": {
            "epoch": 30000,
            "policy": 0
        },
    "isQuorum": true
  },
  "alloc": {},
  "nonce": "0x0",
  "timestamp": "0x5982d805",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f86fea941cd6d479eda90f876366c32a7932eaf7116aa39394294fc7e8f22b3bcdcf955dd7ff3ba2ed833f8212b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

when i remove  "istanbul": {"epoch": 30000,"policy": 0 }  from genesis file , coinbase & accounts0 both are same, but it is no more istanbul protocol

**Comment by patrickmn** [comment]
@yutelin @markya0616 thoughts?

**Comment by yutelin** [comment]
@abhayar coinbase address has been repurposed for validator voting. Please refer to [EIP 650](https://github.com/ethereum/EIPs/issues/650) Block header section. 

- beneficiary: Address to propose modifying the list of validator with.
    - Should be filled with zeroes normally, modified only while voting.
    - Arbitrary values are permitted nonetheless (even meaningless ones such as voting out non validators) to avoid extra complexity in voting mechanics implementation.

**Comment by abhayar** [comment]
ERROR[02-11|06:28:21] Failed to decode message from payload    address=0x2D7fa275D93006d80B07f03Cd678E84eA2CB57A5 err="unauthorized address"...getting this error, this is coinbase address

**Comment by ijazm** [comment]
@abhayar Have you solved the issue
ERROR[02-11|06:28:21] Failed to decode message from payload address=0x2D7fa275D93006d80B07f03Cd678E84eA2CB57A5 err="unauthorized address"...getting this error, this is coinbase address

**Comment by abhayar** [comment]
No, not yet..any solution on this...?
So to create extradata, we are using istanbul-tools, so because of this, tools itself create coinbase account & I'm also creating new account..Is this so..?

**Comment by ijazm** [comment]
@abhayar yes, exactly that is the problem. What I did to overcome this problem is I created the nodekey and genesis file using the istanbul tool. I used that nodekey on all the nodes i have  and finally my manual setup was successful and I am able to deploy contracts

**Comment by colindog** [comment]
@ijazm But if you use istanbul-tools, there is no way to get the private keys for the node addresses,right?

**Comment by Krish1979** [comment]
➤ Patrick Mylund Nielsen commented:

yutelin markya0616 thoughts?

**Comment by abhayar** [comment]
@Krish1979 facing same account issue..?

**Comment by AUQIB92** [comment]
> @abhayar yes, exactly that is the problem. What I did to overcome this problem is I created the nodekey and genesis file using the istanbul tool. I used that nodekey on all the nodes i have and finally my manual setup was successful and I am able to deploy contracts

please provide some more information on this i m facing same error

**Comment by abhayar** [comment]
@AUQIB92 Hi , Yeah I solved the problem in similar way before.
