### ISSUE TITLE
raft-start.sh: MustNew error

### ISSUE THREAD

**Issue by crilofer** [Consensys-Incorporated/quorum#262]
#### System information

Geth version: `1.7.2-stable`

OS & Version: OSX 10.12.6

Branch, Commit Hash or Release: `0905eda48eb07a4ce0e7072c1a2ecbf690ddff77`

#### Expected behaviour

Contract transaction send.

#### Actual behaviour

MustNew error

#### Steps to reproduce the behaviour

git clone https://github.com/jpmorganchase/quorum-examples
cd quorum-examples
sudo vagrant up
sudo vagrant ssh
cd quorum-examples/7nodes
sudo ./raft-init.sh
sudo ./raft-start.sh

#### Backtrace

````
vagrant@ubuntu-xenial:/home/ubuntu/quorum-examples/7nodes$ sudo ./raft-start.sh
[*] Starting Constellation nodes
[*] Starting node 1 (permissioned)
[*] Starting node 2 (permissioned)
[*] Starting node 3 (permissioned)
[*] Starting node 4 (permissioned)
[*] Starting node 5 (unpermissioned)
[*] Starting node 6 (unpermissioned)
[*] Starting node 7 (unpermissioned)
[*] Waiting for nodes to start
[*] Sending first transaction
panic: MustNew error: Get http+unix://c/upcheck: dial unix qdata/tm1.ipc: connect: no such file or directory

goroutine 1 [running]:
panic(0xe9db80, 0xc4201e1430)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/private/constellation.MustNew(0xc42000e00f, 0x8, 0xc42000e00f)
	/home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:63 +0x114
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0x1047c20, 0xe, 0xc4201ea040, 0xc4201ea020)
	/home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:19 +0x52
github.com/ethereum/go-ethereum/private.init()
	/home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:22 +0x67
github.com/ethereum/go-ethereum/core.init()
	/home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/types.go:49 +0x110
github.com/ethereum/go-ethereum/cmd/utils.init()
	/home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/flags.go:1240 +0x6c
main.init()
	/home/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/geth/usage.go:331 +0x76````

**Comment by araskachoi** [comment]
Geth version: `1.7.2-stable`
OS & Version: Windows 10, version 1709
Branch, Commit Hash or Release: `0905eda48eb07a4ce0e7072c1a2ecbf690ddff77`


getting this same exact error produced above as well.

**Comment by cfengliu** [comment]
This error happened when node1 geth haven't started. Try modifying `sleep 1` to `sleep 10` in `raft-start.sh` .

**Comment by archana209** [comment]
I tried that but it did not helped. Anyone managed to get past this problem?

**Comment by jpmsam** [comment]
@archana209 any errors in  your constellation logs under quorum-examples/7nodes/qdata/logs?

**Comment by MasX** [comment]
@jpmsam `constellation-node: bind: permission denied (Operation not permitted)`. This happens both when running as vagrant user as well as running as root.

Both on Debian and Ubuntu. Only on zsl_1.6 (which runs geth 1.7, not 1.6!); zsl_1.5 seems to work.

**Comment by SatpalSandhu61** [comment]
This appears to be a stale issue, so I'm closing it.
The original issue reported here looks like some faulty config setup, the error message:
   "MustNew error: Get http+unix://c/upcheck: dial unix **qdata/tm1.ipc**"
Indicates that it's looking in the wrong directory for the socket file (it should be under qdata/c*).

I've tested Quorum Examples on the Mac and can confirm that it works under vagrant using sudo (as per the steps to reproduce the behaviour).

**Comment by Krish1979** [comment]
➤ Samer Falah commented:

archana209 any errors in  your constellation logs under quorum-examples/7nodes/qdata/logs?
