### ISSUE TITLE
add import comments

### ISSUE THREAD

**Issue by rogpeppe** [Consensys-Incorporated/quorum#264]
It's not clear at first glance that the Go files in this repository will only work correctly if they are imported under the `github.com/ethereum/go-ethereum` namespace. It might be a good idea to add import comments to prevent mistakes and make this clear.

**Comment by patrickmn** [comment]
@rogpeppe, nice to see you again :)

Agreed about import comments. Geth never got away from makefiles, and we kept the namespace for the sake of smaller diffs. Perhaps the best solution is to just rename the import paths so you can actually `go get` quorum and have both vanilla geth and quorum available...

**Comment by ricardolyn** [comment]
Closing. New release v21.1.1 will use Go Modules.
