### ISSUE TITLE
Read from public Ethereum

### ISSUE THREAD

**Issue by lucashenning** [Consensys-Incorporated/quorum#265]
Hi everyone, I was wondering if there are any plans on implementing a mechanism to read a transaction from the public Ethereum blockchain. I think being able to read the public Ethereum state could be beneficial in many ways (e.g. it could be useful to validate ETH payments in a smart contract on Quorum). 

Any ideas on how to implement this feature? I'd be more than happy to do the coding myself and would appreciate someone pointing me in the right direction.

Thank you

**Comment by patrickmn** [comment]
This is an interesting feature and something we've thought about. Obviously it would be nice to avoid a dependency on downloading the entire Ethereum public chain, but it would be a great optional feature to have.

I will add some more thoughts on how this could be done shortly.

**Comment by antonydenyer** [comment]
@lucashenning what you are looking for is some kind of "token bridge".

There are people running https://chainbridge.chainsafe.io/chains/ethereum/ on Quorum network successfully. There are a bunch of other bridge implementations. 

Another other option would be to run an Oracle on your Quorum network that could be queried.

Having GoQuorum directly query mainnet will never be possible as you can't run GoQuorum on mainnet! 

Drop me a chat in discord if you want some more info.
