### ISSUE TITLE
Call for feedback: Quorumchain consensus removed in Quorum 2.0.0

### ISSUE THREAD

**Issue by patrickmn** [Consensys-Incorporated/quorum#266]
Quorum 2.0.0 onwards does not have support for the Quorumchain consensus algorithm.

This issue is meant to track feedback/requests related to this omission to see if the option should be re-added.

  - Are there users who need this option in addition to the existing `raft` and `istanbul` options?
  - What properties are the other options missing?

**Comment by pindaroso** [comment]
Don't need it, Istanbul is more than sufficient. Curious if others can recommend other consensus candidates though... Thanks!

**Comment by coeniebeyers** [comment]
I also don't think we need QuorumChain consensus. Between Istanbul and Raft, we are sorted for now. 

This is not the right place to discuss, but would like to use this post to mention what I would rather focus on:    
1. Getting Raft to fail gracefully: pushing too many tx'es (several 1000/s) through it causes the node to crash (which was expected as we wanted to test recoverability from a crash), however it ends up in an unrecoverable state, which is not okay and we need to restart the whole network. With Istanbul we've always been able to simply restart the node and continue where we left off (sometimes we need to delete transaction.rlp, though).
2. Consider allowing nodes onto a Raft network that won't participate in consensus, and only allow a node to participate in consensus once it has been voted in. Currently any node can break the network by simply calling "raft.addPeer(\<random enode\>)" until there are more offline nodes than online and new blocks can't be created.
3. Keep up the good work :)

**Comment by patrickmn** [comment]
#1: Is there a separate issue for this? Agreed that data corruption should not happen.

#2: https://github.com/jpmorganchase/quorum/issues/180

#3: No ticket for that but we'll try :)

**Comment by kkarski** [comment]
We are interested in continuing with QuorumChain given that we have different participants in our permissioned network and different levels of membership. Some participants are only interested in observing and verifying transactions while others would have to obtain a higher level of partnership and trust to become block makers or voters. 

In a permissioned network with participants of various levels of trust, QuorumChain provides a nice solution to our use case.

**Comment by colinp8** [comment]
I would very much like continued support of QuorumChain, for similar reasons to @kkarski. We also need on-demand block creation but raft is not suitable for our purposes.

**Comment by jpmsam** [comment]
@kkarski @colinp8  Please look into using Clique and Istanbul as both are supported in Quorum.
