### ISSUE TITLE
Tests are failing on OSX

### ISSUE THREAD

**Issue by jrgleason** [Consensys-Incorporated/quorum#268]
OS: OSX
Branch: Master

#### Expected behavior:

Per instruction `make test` should pass after `make all`

#### Actual behaviour

```
--- FAIL: TestDeliverHeadersHang64Fast (6.50s)
	downloader_test.go:1737: sync failed: state data download canceled (requested)
--- FAIL: TestDeliverHeadersHang63Fast (7.90s)
	downloader_test.go:1737: sync failed: state data download canceled (requested)
	downloader_test.go:1737: sync failed: state data download canceled (requested)
FAIL
FAIL	github.com/ethereum/go-ethereum/eth/downloader	66.782s
```

**Comment by jrgleason** [comment]
The Hang64Fast seems to be random in terms of failure 63 seems more constant. Also we should probably add something in the build readme about needing to install constellation first.

**Comment by xiaods** [comment]
need some build docs to guide macos user to make test passing. thanks a lot.

**Comment by xiaods** [comment]
@jrgleason the team told me , it not bug but design.

```
Some tests will fail in Quorum due to the modifications we made to support the private state and not supporting the light client.
```

**Comment by jpmsam** [comment]
@xiaods its not by design. We haven't cleaned up the tests that would fail due the private state and the unsupported features from geth.

**Comment by xiaods** [comment]
@jpmsam  got it. that's fine.

**Comment by fixanoid** [comment]
Please reopen if this is still an issue. Thanks.
