### ISSUE TITLE
Node which is not in private party changes the state of the private contract.

### ISSUE THREAD

**Issue by karthik137** [Consensys-Incorporated/quorum#273]
We have set up  three nodes by name ABC, XVZ, LPV.

XVZ deployed a private contract for ABC node. LPV is not in the private party. Following is the contract code:

`contract SamplePrivateContract{
    uint public value;
    function setValue(uint newValue)public {
        value = newValue;
    }
    function getValue()constant public returns(uint){
        return value;
    }
}`

Contract at XVZ node was deployed by giving public key of ABC node.

Invoked contract methods at ABC, XVZ and LPV nodes using  contract address and contract abi.

Following are the steps which were performed 

Step 1)

XVZ Node ---> setValue(125) , privateFor[ABC.pub]

Result ---> 

XVZ ---> getValue() = 125.
                  ABC ---> getValue() = 125.
                   LPV ---> getValue() = 0.

Step 2)

ABC Node ---> setValue(126) , privateFor[XVZ.pub]

Result --->

 XVZ ---> getValue() = 126.
                  ABC ---> getValue() = 126.
                   LPV ---> getValue() = 0.

Step 3)

LPV Node ---> setValue(127) , privateFor[ABC.pub]  (This should have given an error. But it was executed successfully and gave txId.  Private ledger state was changed  in ABC node.)

Result ---> 

XVZ ---> getValue() = 126.
                  ABC ---> getValue() = 127.
                   LPV ---> getValue() = 0.

Step 4)

LPV Node ---> setValue(128) , privateFor[XVZ.pub]  (This should have given an error. But it was executed successfully and gave txId. Private ledger state was changed  in XVZ node.)

Result ---> 

XVZ ---> getValue() = 128.
                  ABC ---> getValue() = 127.
                   LPV ---> getValue() = 0.

I thought steps 3 and 4 should not have been successful. As LPV node is not involved in the private party.  But LPV node was able to change the state of contract variable, And ABC node and XVZ node private ledger had different values. 

#### System information

Geth version: `geth version`

`Version: 1.5.0-unstable`

OS & Version: Windows/Linux/OSX

`Ubuntu 16.04.1 LTS`

#### Expected behaviour
`It should throw error`

#### Actual behaviour
Successfully invokes the contract method and gives transaction id. 

#### Steps to reproduce the behaviour

Set up three nodes by name ABC, XVZ and LPV. Deploy the smart contract from XVZ node 
which is pasted above with `privateFor["ABC node public key"]` . Use the generated contract address and repeat above mentioned steps.

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/126

**Comment by karthik137** [comment]
Thank you @patrickmn for quick response. :)
