### ISSUE TITLE
TX failed, will be removed 

### ISSUE THREAD

**Issue by fatel-openlev** [Consensys-Incorporated/quorum#275]
INFO [02-08|16:27:33] Submitted transaction                    fullhash=0xf44a0d68221a8ffbc8612c88dd69c32e6cca943c91ef66280accfa7ad65e4ce8 recipient=0xF12C5F43d4d55C4d39f369fe7508976129752FF7
INFO [02-08|16:27:33] QUORUM-CHECKPOINT                        name=TX-CREATED    tx=0xf44a0d68221a8ffbc8612c88dd69c32e6cca943c91ef66280accfa7ad65e4ce8 to=0xF12C5F43d4d55C4d39f369fe7508976129752FF7
INFO [02-08|16:27:33] TX failed, will be removed               hash=c282af…c2a495 err="out of gas"
INFO [02-08|16:27:33] Generated next block                     block num=14063 num txes=1
INFO [02-08|16:27:33] 🔨  Mined block                           number=14063 hash=a2b7543d      elapsed=1.939768ms
INFO [02-08|16:27:33] QUORUM-CHECKPOINT                        name=TX-ACCEPTED   tx=0xf44a0d68221a8ffbc8612c88dd69c32e6cca943c91ef66280accfa7ad65e4ce8
INFO [02-08|16:27:33] Imported new chain segment               blocks=1 txs=1 mgas=0.046 elapsed=15.310ms   mgasps=3.033   number=14063 hash=a2b754…1de578
INFO [02-08|16:27:33] QUORUM-CHECKPOINT                        name=BLOCK-CREATED block=a2b7543de5594aed70c5541628282a9b79f876bf2ab5d2cc818f54f7031de578
INFO [02-08|16:27:33] persisted the latest applied index       index=49
INFO [02-08|16:27:33] TX failed, will be removed               hash=c282af…c2a495 err="out of gas"
INFO [02-08|16:27:33] Not minting a new block since there are no pending transactions

**Comment by jpmsam** [comment]
@Fatel999 Have you increased the amount of gas being passed to the transaction? We'll be working on simplifying or automating that process for Quorum.

**Comment by fatel-openlev** [comment]
all transaction it working in gas with 4700000 before，but every transaction faild by surprise，  I created  transaction gas with 1,0000,0000；it failed yet，

**Comment by fixanoid** [comment]
Please reopen if this is still an issue. Thanks.
