### ISSUE TITLE
"read error invalid character 'P' looking for beginning of value" on private transaction

### ISSUE THREAD

**Issue by kekomal** [Consensys-Incorporated/quorum#277]
#### System information

Geth version: `geth version`
1.7.2-stable

OS & Version: Windows/Linux/OSX
Ubuntu 16.04

Branch, Commit Hash or Release: `git status`
master

#### Expected behaviour
Private transaction successful?

#### Actual behaviour
"read error invalid character 'P' looking for beginning of value"
"read error invalid character 'G' looking for beginning of value"

#### Steps to reproduce the behaviour
eth.sendTransaction({from:eth.accounts[0], privateFor:["Hniwqqpw1SE0BDpxAhp7w0Q6NLMCh4x77xA83iM6amk="]});

...or something like https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/script1.js

#### Backtrace

````
TRACE[02-08|16:37:15] Dial task done                           task="discovery lookup"
TRACE[02-08|16:37:15] New dial task                            task="discovery lookup"
INFO [02-08|16:37:18] sending private tx                       data= privatefrom= privatefor="[Hniwqqpw1SE0BDpxAhp7w0Q6NLMCh4x77xA83iM6amk=]"
DEBUG[02-08|16:37:18] read error invalid character 'P' looking for beginning of value
 
INFO [02-08|16:37:18] sent private tx                          data= privatefrom= privatefor="[Hniwqqpw1SE0BDpxAhp7w0Q6NLMCh4x77xA83iM6amk=]"

````
Hi everybody,

Line 97 of https://github.com/jpmorganchase/quorum/blob/master/private/constellation/node.go in my deployment causes:
```
"read error invalid character 'P' looking for beginning of value" on private transaction
```

I have checked that the "P" comes from the method name "POST". "GET" causes the same error but with a "G". It looks a little weird...

Ethereum regular transactions work as expected.

Any idea?

**Comment by wozney** [comment]
Hey,

Did you resolve this issue and if so how?

I'm running GETH, mining ETC "solo pool"

Keep getting the same error message "P" & "G"

Thanks

/u/kekomal
@kekomal
