### ISSUE TITLE
Quorum Continually creating blocks

### ISSUE THREAD

**Issue by parthadc** [Consensys-Incorporated/quorum#279]
Hi

I am new to quorum. I am unable to map the nodes to the application like addvoter, removevoter etc. Quorum is continually creating blocks irrespective of user's votes. I am have tried web3-quorum as well as from solc. It might sound naive still help would be much appreciated.

Thanks

#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by joelburget** [comment]
Sounds like you're using QuorumChain consensus on Quorum v1. I recommend upgrading to Quorum v2 and Raft or Istanbul consensus.
