### ISSUE TITLE
Can votes be casted from API ?

### ISSUE THREAD

**Issue by tamalsen** [Consensys-Incorporated/quorum#280]
Geth version: `geth version`: 1.7.2

OS & Version: Windows/Linux/OSX: Linux

Branch, Commit Hash or Release: `git status`: 2.0.0

I have just started tinkering with blockchain and found this really awesome library. I have a very basic confusion about using various consensus algorithms. Can the votes be casted through API and delay creating a block until a threshold (lets say n/2 + 1) is reached. If so, how can I do that while using Istanbul BFT on Quorum?

**Comment by jpmsam** [comment]
@tamalsen this is handled on the consensus engine level and isn't exposed as an API.
