### ISSUE TITLE
MustNew: Failed to connect to Constellation (tm1.conf)

### ISSUE THREAD

**Issue by archana209** [Consensys-Incorporated/quorum#286]
Iam trying to run 7Nodes with ZSL integrated. 
On my ubuntu VirtualBox instance I have successfully built ZSL and Quorum.
I want to run 7Nodes example locally on my VirtualBox ubuntu instance.

Once I run ./raft-start from 7Nodes example(zsl_geth1.5 branch) I get following output 

from 1.log 
nohup: appending output to 'nohup.out'
panic: MustNew: Failed to connect to Constellation (tm1.conf): Get http+unix://c/upcheck: dial unix qdata/tm1.ipc: connect: no such file or directory

from constellation1.log
nohup: appending output to 'nohup.out'
nohup: failed to run command 'constellation-node': No such file or directory

#### System information

Geth
Version: 1.7.2-stable
Git Commit: 32147054808d62bc9735a2513a01da4ae3909322
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.8
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

Geth version: `geth version`

OS & Version: Windows/Linux/OSX : 

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by archana209** [comment]
Duplicate of raft-start.sh: MustNew error #262

**Comment by Bobby122333** [comment]
Connect to the genesis.json inside/7nodes  using geth, that fixed it for me.
