### ISSUE TITLE
Use the permissioned nodes for discovery

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#287]
The usage of a permissioned network with `--permissioned` and the `permissioned-nodes.json` file, should make it unnecessary to have bootnodes. Nodes should use this list as the initial source of new peers instead of bootnodes.

**Comment by stevenroose** [comment]
So with Istanbul, it seems that when `--mine` is provided, peers actually already do this. However, I struggle to get my non-mining peers to join. When I force them (from either side) to add a peer, they start syncing fine, but without a manual trigger, they stay stale.

**Comment by Open-Rawi** [comment]
Hi @fixanoid can we close this issue , this is a dupe of #378
