### ISSUE TITLE
Istanbul consensus failure: inconsistent environment variables

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#289]
This issue continues #285.

So, I managed to find a small transaction that triggers Istanbul validators to create wrong blocks (i.e. one that the other validators don't accept).

Situation:
- observed both with 3 and 7 nodes
- **not** observed with `--istanbul.blockperiod 1 --istanbul.blockpausetime 2` (default)
- observed with `--istanbul.blockperiod 7 --istanbul.blockpausetime 8`
- every validator creates invalid blocks rejected by the others, so the block created process halts entirely
- no issues when using Raft

The interesting thing about the triggering tx is that it combines all environment variables into a hash and emits it in an event. This means that somehow the validators don't agree on the environment set for tx execution for block validation. This might be because the execution environment the validator has for building the block is wrong.

```solidity
pragma solidity ^0.4.6;

contract Test {
    event TestEvent(bytes32 hash);
    function test() public payable {
        var h = sha256(this);
        h = sha256(h, block.blockhash(block.number-1));
        h = sha256(h, block.coinbase);
        h = sha256(h, block.difficulty);
        h = sha256(h, block.gaslimit);
        h = sha256(h, block.number);
        h = sha256(h, block.timestamp);
        h = sha256(h, msg.data);
        h = sha256(h, msg.gas);
        h = sha256(h, msg.sender);
        h = sha256(h, msg.sig);
        h = sha256(h, msg.value);
        h = sha256(h, now);
        h = sha256(h, tx.gasprice);
        h = sha256(h, tx.origin);
        TestEvent(h);
    }
}
```

I build the contract with solc and generated Go bindings with abigen. This is the code (including generated code) that I used to deploy and execute the transaction:
https://gist.github.com/stevenroose/a722f360e11d23ca6032a0fa5a8477b0

**Comment by stevenroose** [comment]
Helping you out, I narrowed it down even more. These are the ones that fail:

```solidity
pragma solidity ^0.4.6;

contract Test {
    event TestEvent(bytes32 hash);
    function test() public payable {
        var h = sha256(bytes32(0));
        //h = sha256(h, this);
        //h = sha256(h, block.blockhash(block.number-1));
        //h = sha256(h, block.coinbase);
        //h = sha256(h, block.difficulty);
        //h = sha256(h, block.gaslimit);
        //h = sha256(h, block.number);
        h = sha256(h, block.timestamp);
        //h = sha256(h, msg.data);
        //h = sha256(h, msg.gas);
        //h = sha256(h, msg.sender);
        //h = sha256(h, msg.sig);
        //h = sha256(h, msg.value);
        h = sha256(h, now);
        //h = sha256(h, tx.gasprice);
        //h = sha256(h, tx.origin);
        TestEvent(h);
    }
}
```

Since `now` is an alias for `block.timestamp`, they both fail. So the variable that causes the inconsistency between the validators is the block timestamp.

**Comment by markya0616** [comment]
The root cause is we change the block header timestamp in Seal(). It will cause different root hash in proposer and validators' side. Please check our PR https://github.com/jpmorganchase/quorum/pull/297.

**Comment by kikoncuo** [comment]
I don't think this has been fixed, got the same problem, with 10s blockTimes transactions using now cause a consensus failure, if they don't, they work properly.
