### ISSUE TITLE
Unable to deploy contract while running start.sh

### ISSUE THREAD

**Issue by ushakrishnan** [Consensys-Incorporated/quorum#29]
Q1: When running init - No etherbase / account is set.  Is that right?
Q2: When running start - account[0] is not unlocked (does not exist?) and also deploying contract fails

![capture](https://cloud.githubusercontent.com/assets/18739265/20996006/920f9b96-bcc8-11e6-83d2-01ad84817378.JPG)

What has failed and how do I set up the scripts to work as intended?

**Comment by patrickmn** [comment]
Yes, the warning is fine. It just means that some of the nodes don't have accounts.

I can't reproduce the second issue.

`init.sh` should only be run once, the first time you're setting up the example. Then use `start.sh` and `stop.sh` after that.

If you'd like to re-initialize, delete the qdata folder with `rm -rf qdata`, then run `./init.sh`.

**Comment by ushakrishnan** [comment]
I am able to geth attach to all nodes except 1 (dd1).  

![capture](https://cloud.githubusercontent.com/assets/18739265/21028669/3262c99c-bd64-11e6-82ed-ef7803228121.JPG)

The failure to deploy to dd1 is due to inability to connect to  that node.  What can I do to check or fix the connectivity to that node?  Not sure why that one node would have issues but all the others run as intended.  I completely destroyed the vagrant and recreated it too with the same outcome.

**Comment by patrickmn** [comment]
My guess is that issue is a duplicate of https://github.com/jpmorganchase/quorum/issues/24

Because node 1 is not fully initialized when the transaction is sent, it crashes. Try increasing the sleep duration before sending the transaction in start.sh as a temporary workaround.

**Comment by ushakrishnan** [comment]
There probably is something more than just the delay -

I was able to start node1 manually.  worked well.  tried several eth js commands, and they work.  However unable to deploy contract.

I am able to deploy the contract (script1.js) to all other nodes where account (account[0]) exists.  However, node1 does have an account but never able to deploy to it.

A success response from other nodes
![success](https://cloud.githubusercontent.com/assets/18739265/21033721/9c13fdb8-bd80-11e6-9b57-e4e3cd0e59ae.JPG)

Successful login into node1
![logged](https://cloud.githubusercontent.com/assets/18739265/21033737/bb8a86e4-bd80-11e6-92ca-7b483b042527.JPG)


Failure response from node1
![failure](https://cloud.githubusercontent.com/assets/18739265/21033730/ae631706-bd80-11e6-826b-17fb86bc053a.JPG)

**Comment by ilmistra** [comment]
Getting this error when starting 

[*] Starting Constellation nodes
[*] Starting bootnode
wait for bootnode to start...
[*] Starting node 1
[*] Starting node 2
[*] Starting node 3
[*] Starting node 4
[*] Starting node 5
[*] Starting node 6
[*] Starting node 7
[*] Sending first transaction
err: TypeError: Cannot access member 'info' of undefined
false

I tried to increase sleep time, but no results. Init seems ok...a part from node 5 where I sse this warning..

You're one of the lucky few that will try out the JIT VM (random). If you get a consensus failure please be so kind to report this incident with the block hash that failed. You can switch to the regular VM by setting --jitvm=false

**Comment by tylobban** [comment]
@ilmistra this looks like a different issue.  We will investigate and revert back, thanks for raising.

**Comment by tylobban** [comment]
@ilmistra the issue that you reported was due to a [change](https://github.com/ethereum/solidity/releases/tag/v0.4.9) in the return object from the solidity compiler.  A fix has now been committed in the quorum-examples repo.
