### ISSUE TITLE
vagrant ssh is not working 

### ISSUE THREAD

**Issue by SudeepSinghRawat** [Consensys-Incorporated/quorum#290]
Dear Team,
Need help while running vagrant ssh it gives me error that he cannot connect with private 

Thanks and regards
Sudeep singh Rawat

**Comment by jpmsam** [comment]
@SudeepSinghRawat Please provide more details on how you are starting vagrant and the error that you are seeing. You should be following the instructions on [this page](https://github.com/jpmorganchase/quorum-examples).

**Comment by jpmsam** [comment]
@SudeepSinghRawat Please reopen if the instructions didn't help.
