### ISSUE TITLE
Couldn't see the payload of private transactions on node 7

### ISSUE THREAD

**Issue by MajjigaDeepak** [Consensys-Incorporated/quorum#291]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

Followed Quorum-examples

#### Expected behaviour
Using "private for" node 7 in migrations json 
After doing private transaction between node 1 and node 7, the payload should be visible at both nodes

Node 1 : Big Number 21
Node 4 : Big Number 0
Node 7 : Big Number 21

#### Actual behaviour
The payload is getting visible on at node 1 , the payload in not visible at node 7.

Node 1 : Big Number 21
Node 4 : Big Number 0
Node 7 : Big Number 0

#### Steps to reproduce the behaviour
Followed this 
https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/README.md

#### Backtrace

````
[backtrace]
````

**Comment by patrickmn** [comment]
Please try again with the latest 7nodes/quorum-examples (Quorum 2.0.1 and Constellation 0.3.2). This issue should be resolved.

**Comment by patrickmn** [comment]
For reference: https://github.com/jpmorganchase/quorum-examples/issues/79

**Comment by MajjigaDeepak** [comment]
Thanks @patrickmn , It worked.

Have few questions.

1. How to add more nodes instead of 7 ?
2. I am planning to create a team chat application within group of nodes (more nodes can be added as new people join the team), public and private chat should be possible with instant message transfer capabilities?

is this right framework to work on?

Thanks in advance.

**Comment by obbaeiei** [comment]
Hi. It has occurs again on version 2.2.3

**Comment by fixanoid** [comment]
> Hi. It has occurs again on version 2.2.3

Please open a new ticket with description of the issue. Thanks
