### ISSUE TITLE
Execution of fund transfer between EOAs' privately, makes the quorum node network unstable- public transaction is not getting confirmed

### ISSUE THREAD

**Issue by bansatya** [Consensys-Incorporated/quorum#292]
Strange behavior while transferring funds between EOA's privately.

Scenario with Quorum 2.0.1/Constellation 0.3.0

1. Update genesis.json to allocate some balance to the 1st node coinbase

2. Started 7 nodes  with raft consensus and ensured all quorum nodes and constellations are up and running.

3. Connected to first node and verified the Coinbase balance.It displayed the balance as allocated in genesis.json

4. Try to transfer funds between two EOAs' publicly
eth.sendTransaction({from:eth.accounts[0],to:"0x8b0d76e01ecc08070b140bc431d4e7834e22a691",value:44400000000})
The transaction confirmed  an balances updated in EOAs' properly.

5. Try to transfer funds privately as below.. 
eth.sendTransaction({from:eth.accounts[0],to:"0xca843569e3427144cead5e4d5999a3d0ccf92b8e",gas:4700000,value:30000000,privateFor:["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="]})

The transaction stays as **pending transaction** and not getting confirmed.

6.Try to execute step 4 again, the transaction is executed but not getting confirmed and remains as 'pending' 

All transaction is getting queued but not confirmed.

7. Verified the Geth and constellation processes. All are up and running

If the same steps repeats in quorum 2.0.0/constellation 0.2.0,  
The Step 4 executed successfully. However, step 5 throws error in Geth console.

**Comment by patrickmn** [comment]
So, private value transfers are not supported, but balance-tracking in a private smart contract is. See https://github.com/jpmorganchase/quorum/issues/201

However, sending a private value transaction should not be causing txpool "clogging" like you describe. Are you using Raft or Istanbul consensus? Which error does step 5 give you?

**Comment by bansatya** [comment]
No error in Quorum 2.0.1 with constellation 0.3.0.
However, getting error as 'connection refused' with Quorum 2.0.0 &  constellation 0.2.0

**Comment by bansatya** [comment]
I am using Raft concensus.

**Comment by fixanoid** [comment]
This has been resolved in master. Please reopen if this is still an issue. Thanks.
