### ISSUE TITLE
[Questions] How could I prevent from ledger attack

### ISSUE THREAD

**Issue by KimiWu123** [Consensys-Incorporated/quorum#293]
We use the permission file to control permission. We set gas price to 0 so that we don't need to give money to members all the time. But if any one of node is hacked, how could I prevent from the hacked node broadcasts garbage txs? remove the node from permission list? Is any other way to minimize the damage?
We use Raft as our consensus. 

Thanks.

**Comment by daveracer** [comment]
Today that's a way to do it.  We're working on a way to auto-detect these issues and do a revocation.  There are a bunch of other issues we are working on regarding cloning of private keys and how to detect and then remediate.

**Comment by KimiWu123** [comment]
@daveracer , 
Thanks for your quick reply. 
So, that means we couldn't prevent from attack in the situation I described now (Quorum v2.0). Is that correct?

Very looking forward to the auto-detection and revocations.
Thanks.

**Comment by patrickmn** [comment]
@KimiWu123 FYI gas price is being re-introduced soon: https://github.com/jpmorganchase/quorum/pull/288 This at least will provide a primitive mechanism to prevent spam: accounts being funded. That funding would be manual initially, but we're also looking at a system that can do that funding automatically based on past behavior (e.g. no bad behavior but fairly high transaction ratio normally gets a higher amount of ether every 5 minutes...) Would be happy to hear more of your thoughts about what properties of such a system would be useful to you.

**Comment by KimiWu123** [comment]
Awesome! It's great. 
We're also considering use non-zero gas price, but funding is not easy for us to manage. The most important is if we can't detect abnormal behavior, it's useless to use non-zero gas price or funding.

**Comment by adfortia** [comment]
I also guess non-zero gas price is useless when it's not possibile to detect abnormal behavior and it will also add the problem of funding legitimate accounts. According to me, it will be more useful to create a sort of "node profile" containing statistical parameters of node behavior (for example the average txn number per minute). Every node in the network will elaborate a profile for every other peers and when a parameter (or a group of parameters) exceeds  a reference thresold it will take actions (log the unexpected behavior, drop the peer and so on).
