### ISSUE TITLE
Private Transaction - Event (transaction receipt) Missing

### ISSUE THREAD

**Issue by mindraker** [Consensys-Incorporated/quorum#294]
I was confused on Quorum behavior. Please suggest per below information.

System information
Geth version: 1.7.2-stable-ee498061
OS & Version: Ubuntu 16.04.3 LTS
Quorum: tag v2.0.1

Test Case
Create Private Transaction from Node 1 to Node 2,3,4        100 transactions
All Transactions execute successfully on both ends (ledger updated).
While event (transaction receipts) are missing randomly

Blockchain information
6 node on azure VM
Consensus: Istanbul
Expected behaviour
When create 100 transaction from node1, then all node should got event

-node1 100
-node2 100
-node3 100
-node4 100
-node5 100
-node6 100
Actual behaviour
Public transaction and Public contract (log in logPublic.zip)
When create 100 public transaction from node1, then all node should got event 

-node1 100 [completely]
-node2 100 [completely]
-node3 100 [completely]
-node4 100 [completely]
-node5 100 [completely]
-node6 100 [completely]

Private transaction and Private contract (log in logPrivate.zip)
When create 100 private transaction from node1 to node4, node5 and node6, then all node should got event 

-node1 12 [not completely]
-node2 0 [completely] that's ok because don't see private transaction
-node3 0 [completely] that's ok because don't see private transaction
-node4 98 [not completely]
-node5 90 [not completely]
-node6 100 [completely]

node1, node4 and node5 not got event completely

Example code 

Deploy contract
  deployer
    .deploy(Benchmark, {
      privateFor: [
        'oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8=',
        'R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=',
        'UfNSeSGySeKg11DVNEnqrUtxYRVor4+CvluI8tVv62Y='
      ]
    })
    .then(() => {
      objJSON[Benchmark.contractName] = Benchmark.address;
    });

Send transaction
  var instance = Benchmark.at(addressObj.Benchmark);
  console.log(now + '|' + seq + '|' + data.length + '|' + 'sendTx');
  instance.writeData
    .sendTransaction(seq, data, {
      from: account,
      gas: '50000000',
      privateFor: [
        'oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8=',
        'R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY=',
        'UfNSeSGySeKg11DVNEnqrUtxYRVor4+CvluI8tVv62Y='
      ]
    })
    .then(function(txhash) {
      now = moment()
        .tz('Asia/Bangkok')
        .format('YYMMDDHHmmss.SSS');
      console.log(now + '|' + seq + '|' + data.length + '|gotTx');
    });

Watch event
var benchmarkInstance = Benchmark.at(addressObj.Benchmark);
var event = benchmarkInstance.FinishWrite(
  {},
  { fromBlock: 0, toBlock: 'latest' }
);
event.watch(function(error, events) {
  var now = moment()
    .tz('Asia/Bangkok')
    .format('YYMMDDHHmmss.SSS');
  var seq = events.args.sequence.valueOf();
  var data = events.args.data.valueOf();
  var sha1 = events.args.sha1.valueOf();
  var sha2 = events.args.sha1.valueOf();
  var sha3 = events.args.sha1.valueOf();
  console.log(now + '|' + seq + '|' + data.length + '|' + 'completedTx');
  logger(now + '|' + seq + '|' + sha1 + '|' + sha2 + '|' + sha3);
});

**Comment by patrickmn** [comment]
Thank you for the comprehensive bug report.

This is likely due to https://github.com/jpmorganchase/quorum/pull/283

**Comment by jpmsam** [comment]
@mindraker This should have been resolved in Quorum v2.0.2. Please reopen if it hasn't.
