### ISSUE TITLE
Tokens on Quorum with Serial Numbers

### ISSUE THREAD

**Issue by Rogerbut** [Consensys-Incorporated/quorum#295]
Hi,
I have a simple, but awkward question.
Is it possible to create tokens on Quorum that will be serial numbered ?

I know that its not possible within the ERC20 standard, but can we create custom tokens that have extra features like that using quorum?

Thanks for taking the time to answer

**Comment by jsimnz** [comment]
I am not yet too familiar with Quorum specifically, but I believe what you are referring is a non-fungible token, IE a system where each token is unique. Thankfully you aren't the first one to have a need for such a token in the Ethereum community.

There is the [ERC721](https://medium.com/crypto-currently/the-anatomy-of-erc721-e9db77abfc24) & [ERC875](https://github.com/ethereum/EIPs/issues/875)

Both of these create a token with a sense of uniqueness, and more imporantly, ownership, where as the ownership of MyToken:A (The token MyToken, with the identifier A), is different then the ownership of MyToken:B.

Hope that helps.

**Comment by jpmsam** [comment]
@Rogerbut Quorum doesn't provide natively any extra features for tokens. It implements that same standard EVM.
