### ISSUE TITLE
Logs aren't currently visible in private transactions

### ISSUE THREAD

**Issue by StevenBerryman** [Consensys-Incorporated/quorum#30]
I have got our Ethereum smart contracts up and running in Quorum and can interact with them in a limited way using the Mist wallet. Am I right in that events won't work if the contracts are marked as private? If that is the case will events be added in the future assuming that even makes sense to do so?

**Comment by jpmsam** [comment]
@StevenBerryman That is correct, events aren't currently working on private contracts and that is due to logs missing in private transactions. We are looking into adding them.

**Comment by tylobban** [comment]
@StevenBerryman this feature has now been included in the [latest](https://github.com/jpmorganchase/quorum/releases/tag/v1.0.3) Quorum release. Please let us know if you see any issues.  Thanks!
