### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by SebLKMa** [Consensys-Incorporated/quorum#301]
git clone today and build failed:
cmd/geth/usage.go:25: imported and not used: "strings"
util.go:44: exit status 2
exit status 1
Makefile:25: recipe for target 'all' failed
make: *** [all] Error 1

Removed unused "strings" package below from cmd/geth/usage.go and make all succeeded
import (
	"io"
	"sort"

	"strings" <-- remove this

	"github.com/ethereum/go-ethereum/cmd/utils"
	"github.com/ethereum/go-ethereum/internal/debug"
	"gopkg.in/urfave/cli.v1"
)

**Comment by patrickmn** [comment]
Whoops. Fixed.
