### ISSUE TITLE
Smart contract deployment using truffle, error 'Gas price not 0'

### ISSUE THREAD

**Issue by yifon** [Consensys-Incorporated/quorum#304]
#### System information

Geth version: `geth version`
Version: 1.7.2-stable
Quorum Version: 2.0.1
OS & Version: Windows/Linux/OSX
Ubuntu 16.0.4 (32bit)
Branch, Commit Hash or Release: `git status`

#### Expected behaviour
Smart contract can be deployed successfully using truffle

#### Actual behaviour
The balance of every node is 0, when using truffle to deploy the contract, 'truffle migrate', I will hit the 'Gas price not 0' error

#### Steps to reproduce the behaviour
1.After install quorum, run "geth --datadir qdata/dd1 --rpc --rpcaddr localhost --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --rpcport 7101 --port 7301 --networkid 999 console"
2.Run 'miner.start()'
3. All the geth node will be terminated, with the error 'goroutine [chan receive]' error

#### Backtrace

````
[backtrace]
````

**Comment by moda20** [comment]
You probably need to set your network gasPrice like i did here : 
```
networks: {
    development: {
      host: 'localhost',
      port: 22000,
      network_id: '*',
      gas: 4500000,
      gasPrice:0
    }
  }
```

**Comment by yifon** [comment]
yes,I fixed after change. @moda20
