### ISSUE TITLE
Issue with private transaction with version 2.0.0

### ISSUE THREAD

**Issue by renuseabhaya** [Consensys-Incorporated/quorum#306]
#### System information
Quorum Version : 2.0.0
Geth version: `1.7.2-stable-0905eda4`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
Private contract deployment should happen correctly  

#### Actual behaviour

Trying to deploy the contract specifying privateFor, the contract is getting deployed. Viewing the transaction receipt "from" is showing the address incorrectly. It is not matching with the account from which the contract is getting deployed.

Deploy it once again, it shows even different address in "from" field then before.

This behaviour causes issue with the actual application contract where we have the logic of contract owner and transferring ownership.

#### Steps to reproduce the behaviour
1. Setup 7 node example in RAFT consensus mode.
2. Deploy simpleStorage as a private contract.
3. Check transaction receipt "from" field. 

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
Thanks for raising this, investigating...

**Comment by patrickmn** [comment]
This was fixed in 2.0.1. See https://github.com/jpmorganchase/quorum/pull/271
