### ISSUE TITLE
migrations stuck in waiting queue when using truffle

### ISSUE THREAD

**Issue by moda20** [Consensys-Incorporated/quorum#308]
I am using last version of trufle and trying to migrate (deploy) to a single node running the quorum geth fork.

#### System information

Geth version:
 ```Geth
Version: 1.7.2-stable
Git Commit: df4267a25637a5497a3db9fbde4603a3dcd6aa14
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=/home/ronin/go
GOROOT=/usr/lib/go
```

OS & Version: `Arch Linux 4.15.4-1-zen`

Branch, Commit Hash or Release:
 ```On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

#### Expected behaviour
Migrate, and deploy the contract

#### Actual behaviour
stuck at  migrating 
```Running migration: 1_initial_migration.js
  Replacing Migrations...
  ... 0x9722d218160f4880aed141621a9fffd6b98756cd344277b0375d7f42376584f8
````

#### Steps to reproduce the behaviour
run a node with `geth --rpc --rpcport 22000`
run any kind of migration with truffle.

**Comment by fixanoid** [comment]
Tracked in #309
