### ISSUE TITLE
Underpriced transactions get stuck in tx pool

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#309]
Possible duplicate of #308.

I haven't experienced this problem myself, but it has been described to me by a colleague.

It appears that, when a tx is submitted that has a gas price lower than the network minimum gas price, Quorum does not return an error to the user, but broadcasts it, causing it to be stuck in the tx pool forever. (Not 100% sure it is the gas price exactly, or perhaps the gas limit.)

Subsequent transactions for this account (which will have increasing nonces), will also get stuck waiting for the underpriced one to get confirmed first.

A solution for the user is to resubmit the stuck transaction (*using the same nonce*) with a higher gas price. However, I believe it should be the node that refuses the tx from the user instead of broadcasting it, knowing it will be stuck.

**Comment by stevenroose** [comment]
@marcossanlab Detected this issue, perhaps he can provide more detailed information..

**Comment by nottherealbatman** [comment]
To add to this issue you cannot resubmit with a higher `gasPrice` with the same nonce as the `gasPrice` is always set to `0`.

Using the follow command in geth console:
`eth.sendTransaction({ from: '0x39ca937cff7818cc34153fe2092a9e9352ecd47e', to: '0x39ca937cff7818cc34153fe2092a9e9352ecd47e', value: 0, gasPrice: 24000, gasLimit: 24000, nonce: '82'});`

will result in the following error:
```
Error: Gas price not 0
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

setting the `gasPrice` to `0` will result in the following error
```
Error: replacement transaction underpriced
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1
```

**Comment by marcosio** [comment]
To reproduce this issue I used Ubuntu 16.04 with Quorum v2.0.1 and Constellation 0.3.2.
The bootstrapping script that we used for the installation of all the system is in https://github.com/alastria/alastria-node/blob/feature/ibft/scripts/bootstrap.sh.
For testing, I used https://github.com/alastria/test-environment/tree/master/threenodes that desploys 3 nodes with IBFT consensus: 1 validator, 2 regulars.
We use a truffle project to reproduce the bug, I changed in truffle.js the gas as:
```

module.exports = {
	  solc: {
	    optimizer: {
	      enabled: true,
	      runs: 200
	    }
	  },
	  networks: {
	    general1: {
	      host: "localhost",
	      port: 22001,
	      network_id: "*", // Match any network id
	      gas: 0xffff,
	      gasPrice: 0x0,
	      from: "0x0defda53d6e0ba7627a4891b43737c5889e280cc"
	    },
	    general2: {
	      host: "localhost",
	      port: 22002,
	      network_id: "*", // Match any network id
	      gas: 0xfffff,
	      gasPrice: 0x0,
	      from: "0xd2202fba136c2c57d55bfcf83a376ac2914954cb"
	    }
	  }
	};
```
As you can see, I only changed the gas value from 0xfffff to 0xffff.
Then, from the bash shell:
```
truffle$ truffle migrate --network general1
Using network 'general1'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x5d9f28ba758eb68f56d6c389b9cbc275389e2d9f61a68ee24a6b23d279affb57
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Contract transaction couldn't be found after 50 blocks
```
If I access the node:
```
truffle$ geth attach $HOME/alastria/general1/geth.ipc
Welcome to the Geth JavaScript console!

instance: Geth/General1/v1.7.2-stable-ee498061/linux-amd64/go1.8.3
coinbase: 0xd55a8ceb5502a9e5019db17b5a13b152d2255724
at block: 2602 (Wed, 21 Mar 2018 11:19:36 CET)
 datadir: /home/marcos/alastria/general1
 modules: admin:1.0 debug:1.0 eth:1.0 istanbul:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> txpool
{
  content: {
    pending: {
      0x0deFDA53d6E0BA7627A4891B43737c5889e280cc: {
        0: {...}
      }
    },
    queued: {
      0x0deFDA53d6E0BA7627A4891B43737c5889e280cc: {
        4: {...}
      }
    }
  },
  inspect: {
    pending: {
      0x0deFDA53d6E0BA7627A4891B43737c5889e280cc: {
        0: "contract creation: 0 wei + 65535 × 0 gas"
      }
    },
    queued: {
      0x0deFDA53d6E0BA7627A4891B43737c5889e280cc: {
        4: "contract creation: 0 wei + 3000000 × 0 gas"
      }
    }
  },
  status: {
    pending: 1,
    queued: 1
  },
  getContent: function(callback),
  getInspect: function(callback),
  getStatus: function(callback)
}
```

If we try to make the same deployment in general2:
```
truffle$ truffle migrate --network general2
Compiling ./contracts/B.sol...
Writing artifacts to ./build/contracts

Using network 'general2'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x4c8fb075910c63b259573464527663c169b80e040be5ce15a44e90a8d50eb248
  Migrations: 0x7f58a69af22720d522b3989efd4513f9aad01d56
Saving artifacts...
Running migration: 2_deploy_A.js
  Deploying A...
  ... 0xafef06bdbbd40020f5efcf8294230224bb66abe65f9788de89daf6f29a808dcb
  A: 0x77422edd1397ce3a79345e5960d5859d1b8ebe63
Saving artifacts...
```

The conclusion of all this process is that the account that operates general1 can't generate more transactions after one of them gets queued.

**Comment by marcosio** [comment]
Hi!

After performing many tests we realized that the error occurred when the assigned gas was ridiculously small but greater than 0.

Searching for the quorum code, we observe that this value could be the one represented by 'intrinsic gas'.

Checking the source code of 'core / tx_pool.go', on its line 587, we realized that this verification was disabled if Quorum was not activated.

We remove the change and try again the same error, resulting in the transaction being rejected.

This change is published in our fork of quorum in https://github.com/alastria/quorum/commit/af59943283e1abb39b4e4a27ec0062d59f3291ec#diff-8fecce9bb4c486ebc22226cf681416e2

Bye!

**Comment by 15035673705** [comment]
`> eth.sendTransaction({from:eth.coinbase,to:eth.coinbase,value:1,gasPrice:0})
"0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11"
> eth.getTransaction('0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11')
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gas: 90000,
  gasPrice: 0,
  hash: "0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11",
  input: "0x",
  nonce: 298,
  r: "0xfaec83bbe9d5d4474f3c89b09770df8d08e041dc93a2af6f4bba7e8d94b7b569",
  s: "0x7837e6c17b061e3b52a0e01f03ec138f472e032571ccec568f272720bedcda34",
  to: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  transactionIndex: 0,
  v: "0x1c",
  value: 1
}
`

**Comment by ghost** [comment]
`
> eth.sendTransaction({from:eth.coinbase,to:eth.coinbase,value:1,gasPrice:0})
"0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11"
> eth.getTransaction('0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11')
{
  blockHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  blockNumber: null,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gas: 90000,
  gasPrice: 0,
  hash: "0x72245225887e34a88a197003a4ef6edc46e56fb5c3cb74e4a73b397409408f11",
  input: "0x",
  nonce: 298,
  r: "0xfaec83bbe9d5d4474f3c89b09770df8d08e041dc93a2af6f4bba7e8d94b7b569",
  s: "0x7837e6c17b061e3b52a0e01f03ec138f472e032571ccec568f272720bedcda34",
  to: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  transactionIndex: 0,
  v: "0x1c",
  value: 1
}

`
