### ISSUE TITLE
Why do all nodes run blockvoting strategy

### ISSUE THREAD

**Issue by magooster** [Consensys-Incorporated/quorum#31]
All nodes irrespective of their block making and/or voting rights run the BlockVoting strategy (Generate block creation events, create a block, vote, apply transactions to pending state, reset pending state & pause/resume block making scheduler). Aren't quorum nodes without a block generation key and/or vote key 'wasting' processing cycles from a consensus perspective.

**Comment by davoell** [comment]
Thanks for posting this issue, this is currently being reviewed.

**Comment by bas-vk** [comment]
From a consensus point of view there are no resources wasted. There is an internal event mechanism that dictates when a new vote tx must be broadcasted or a new block must be created. When that event is raised the vote/block maker logic is notified. That logic will check if the node is configured as a voter or block maker node. And if not it does nothing.

**Comment by magooster** [comment]
But doesn't that mean non blockmaker nodes are applying new transactions (executing) to the pending state, only to redo this once a new block comes in. Shouldn't only block makers be building on the pending state?

**Comment by gsalgado** [comment]
The non blockmakers still need the pending state to validate any transactions submitted through them, no?

**Comment by sivachaitanya** [comment]
Where can I learn about your complete consensus strategy ?

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/266

**Comment by patrickmn** [comment]
@sivachaitanya please see https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md and https://github.com/ethereum/EIPs/issues/650
