### ISSUE TITLE
Clarification of status of on-chain permissioning

### ISSUE THREAD

**Issue by jmcnevin** [Consensys-Incorporated/quorum#311]
The first item on the short-term roadmap is to move node permissioning into smart contracts, but I'm having a difficult time determining what the status of this feature is, or the timeline of its release.  To me, this current permissioned-nodes.json-based system creates a weakest-link security issue that is difficult to mitigate in multi-organization networks, and would like to know if this is an issue will be resolved, or if it is even under active development.

**Comment by jpmsam** [comment]
@jmcnevin this feature is under active development, we'll have an update soon on the ETA.
