### ISSUE TITLE
Event fires twice on a contract randomly.

### ISSUE THREAD

**Issue by hikaru-taka** [Consensys-Incorporated/quorum#314]
OS: Ubuntu 16.04.2
Quorum Version: 1.2.0 7-node cluster

Geth
Version: 1.5.0-unstable
Git Commit: 647025ed8a504decfb11ac29bb44b3b2db703071
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

block Number: 3198239

If you execute the following event from the contract, it will fire normally once, but it may ignite twice with a probability of 20%.
Is this a bug?

````
event Debug (string msg);
````

**Comment by jpmsam** [comment]
@hikaru-taka An event shouldn't fire twice on the same node. You seem to be running a very early version of Quorum `1.5.0-unstable`. Please upgrade to 2.0.2 and let us know if you see the same issue.

**Comment by jpmsam** [comment]
@hikaru-taka please reopen if the upgrade didn't fix the issue.
