### ISSUE TITLE
Cannot Make Using Go 1.10

### ISSUE THREAD

**Issue by Paul-Haley** [Consensys-Incorporated/quorum#315]
#### System information

Geth version: `geth version`

OS & Version: OSX 10.13.3

Branch, Commit Hash or Release: `On branch master
Your branch is behind 'origin/master' by 11 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
nothing to commit, working tree clean`
Release 2.0.1

#### Expected behaviour
Should be able to make Quorum, instead it cannot understand that the go version I have is newer than 1.7

#### Actual behaviour
Error about having a version of go 1.10 that is falsely claimed to be older. 

#### Steps to reproduce the behaviour
`make all`

#### Backtrace

````
quorum$ go version
go version go1.10 darwin/amd64
quorum$ make all
build/env.sh go run build/ci.go install
ci.go:180: You have Go version go1.10
ci.go:181: go-ethereum requires at least Go version 1.7 and cannot
ci.go:182: be compiled with an earlier version. Please upgrade your Go installation.
exit status 1
make: *** [all] Error 1
````

**Comment by Paul-Haley** [comment]
Don't worry, it is fixed in the latest master commit. There is no release that supports the latest stable version of Go lang.

**Comment by patrickmn** [comment]
Thanks. Will tag a new release soon.

**Comment by patrickmn** [comment]
https://github.com/jpmorganchase/quorum/releases/tag/v2.0.2
