### ISSUE TITLE
Support moving the raft-wal directory to another location

### ISSUE THREAD

**Issue by mnd999** [Consensys-Incorporated/quorum#317]
#### System information

Geth version: 1.7.2-stable-df4267a2

OS & Version: Linux

Branch, Commit Hash or Release: df4267a25637a5497a3db9fbde4603a3dcd6aa14

#### Expected behaviour

In raft mode, the raft-wal directory, which is sensitive to IO latency is always under datadir. As it's so sensitive to IO latency, it is sometimes desirable to store it elsewhere. If this is a desirable feature, I can probably provide a PR as I have locally added a commandline flag --raftwaldir to override the location of the raft wal directory.

#### Actual behaviour

raft-wal is always stored in the data directory.

#### Steps to reproduce the behaviour

Run quorum in raft mode.

**Comment by jpmsam** [comment]
@mnd999 We liked the approach of having everything under the geth datadir for simplicity and to stay close to the geth design. I can see having the raft-wal under an optional path as a good feature, please feel free to make the update and submit a PR for it and we'll review it. It should be only used in quorum raft mode.
