### ISSUE TITLE
How to start Quorum Network Manually

### ISSUE THREAD

**Issue by rushikeshacharya** [Consensys-Incorporated/quorum#319]
I want to start the Private Quorum Networks manually on local machine with 2-3 nodes for testing, so

- what is the procedure to do this.
- how to generate public and private key files i.e **tm.key tm.pub** given in 7Node example
- which are the mandatory parameters that has to be passed while starting nodes using geth 

I was trying to create a permissioned node using raft ``--raft --permissioned`` but it is asking for at least one enode in static-node.json, but how will I get the enode before creating the node

can you give me the process in detail..?

**Comment by jpmsam** [comment]
@HrishikeshFC Please follow the [7 nodes](https://github.com/jpmorganchase/quorum-examples) example scripts and you should be able to modify them to start 3 nodes. You can reference the [constellation wiki](https://github.com/jpmorganchase/constellation#generating-keys) for key generation.
