### ISSUE TITLE
tests failing (v2.0.2)

### ISSUE THREAD

**Issue by drandreaskrueger** [Consensys-Incorporated/quorum#322]
Following [BUILDING.md](https://github.com/jpmorganchase/quorum/blob/master/BUILDING.md) ...
not all tests are passing.

E.g.:

```
--- FAIL: TestSequentialAnnouncements62 (0.00s)
panic: insufficient balance for transfer [recovered]
	panic: insufficient balance for transfer
```

Don't I need quorum coins to run that test?

I guess an intermediate step needs to be done, after `make all` and before running `make test`, right?

Something like: run geth, wait for sync, fund wallet address?

#### System information

Geth version: `geth version`

```
quorum-geth version
Geth
Version: 1.7.2-stable
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.7.3
```
odd ^ version number because I was compiling from release `quorum-2.0.2.zip`

OS & Version: Linux

Branch, Commit Hash or Release: `git status`
``` git status
fatal: Not a git repository (or any of the parent directories)
```

#### Expected behaviour
tests all OK

#### Actual behaviour
```
--- FAIL: TestFastVsFullChains (0.00s)
panic: insufficient balance for transfer [recovered]
	panic: insufficient balance for transfer

...

FAIL	github.com/ethereum/go-ethereum/core	1.420s

...

--- FAIL: TestEIP155SigningVitalik (0.00s)

...

--- FAIL: TestChainId (0.00s)

...

--- FAIL: TestThrottling62 (0.00s)
panic: insufficient balance for transfer [recovered]
	panic: insufficient balance for transfer

...

FAIL	github.com/ethereum/go-ethereum/eth/downloader	0.024s
--- FAIL: TestSequentialAnnouncements62 (0.00s)
panic: insufficient balance for transfer [recovered]
	panic: insufficient balance for transfer

...

FAIL	github.com/ethereum/go-ethereum/eth/fetcher	0.024s

...

util.go:44: exit status 1
exit status 1
Makefile:38: recipe for target 'test' failed
make: *** [test] Error 1
```

#### Steps to reproduce the behaviour
```
wget https://github.com/jpmorganchase/quorum/archive/v2.0.2.zip
unzip v2.0.2.zip
cd quorum-2.0.2
make all
make test
```

**Comment by drandreaskrueger** [comment]
N.B.: Not so urgent for us, as I have just found the vagrant approach: [quorum-examples](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/README.md).

**Comment by jpmsam** [comment]
Hi @drandreaskrueger , please follow the vagrant example. I believe that should answer all your questions. There is no need to get a coin to create a transaction, you can either update the genesis block with accounts that you want to prefund before bootstrapping the network or transfer a balance from an existing account to a new account.

**Comment by drandreaskrueger** [comment]
@jpmsam - thanks a lot.

> please follow the vagrant example

yes, doing that now. Interesting stuff.

Thanks for the hints.   
The 7nodes example seems to work with accounts that have `eth.getBalance(eth.coinbase)` == 0, probably because of gas price zero, right?

---

This still needs fixing, I think:

>    Quorum Version: 2.0.1
> odd ^ version number because I was compiling from release quorum-2.0.2.zip
