### ISSUE TITLE
Option to configure the Min / Max Block Size Limits

### ISSUE THREAD

**Issue by nottherealbatman** [Consensys-Incorporated/quorum#323]
A parametrized option to set the blocksize would be useful to experiment with. As quorum is used in a private setting I think this option should be available

**Comment by lumian2015** [comment]
You could change the "gasLimit" field in genesis.json file. The block size depends on the gasLimit field

**Comment by mushketyk** [comment]
@jpmsam Is this task still relevant? If yes, I would like to give it a try.

**Comment by jwasinger** [comment]
> You could change the "gasLimit" field in genesis.json file. The block size depends on the gasLimit field

Block size is not determined by the `gasLimit`.

**Comment by fixanoid** [comment]
@mushketyk, this is still an open and a desired issue. If you would like to take a crack at it, please feel free to do so. We think this would be best to add through genesis config as well not dissimilar to the merge done here: https://github.com/jpmorganchase/quorum/pull/636/

**Comment by Magicking** [comment]
It looks like the `2.2.2` patch imported this commit https://github.com/jpmorganchase/quorum/commit/e8f229b82ef99213f8f84b8a71f752b236024494, that changes the default target gas limit to `8,000,000` (ATOW: public ethereum mainnet) instead of the previous higher defined gas limit.

You need with the `2.2.2+` version to use `--miner.gastarget XXX` and `--miner.gaslimit XXX` to set an other `gasLimit` per block

**Comment by Open-Rawi** [comment]
@fixanoid i would like to work on this if not already completed.

**Comment by fixanoid** [comment]
@Open-Rawi all of the tickets in open state are ready to be worked on by the community, please feel free to help us out.

**Comment by ashish10677** [comment]
As it is a good first issue, I, (being a newbie to opensource) would love to try it out. Can someone help me get started?
Thank you

**Comment by fixanoid** [comment]
@ashish10677 as mentioned in my comment, it should be similar to modifications done in #636 and #786. Excpet this time, we want the options for overwriting block size.

**Comment by sakshamk6999** [comment]
Hi, is this issue still open ?
if so, I'd like to contribute

**Comment by antonydenyer** [comment]
This has been implemented in https://github.com/ConsenSys/quorum/releases/tag/v22.7.0 using transitions

e.g 

```
"transitions": [{
  "block" : 100,
  "miner.gasLimit": 10000
}]
```
