### ISSUE TITLE
Contract Deployed but contract code not saved in block

### ISSUE THREAD

**Issue by gstylianou** [Consensys-Incorporated/quorum#324]
I deploy a contract, a block is generated, the transaction receipt contains its address. However the contract's code is empty. requested using eth.getCode. 
After looking for the reason, it looks like the contract's code is too large to fit in the block (maxCodeSizeExceeded in core/vm/evm.go). 
How can this problem be fixed?

**Comment by jpmsam** [comment]
@gstylianou , this limit was introduced by [EIP 170](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-170.md ) due to concerns of a DOS attack on the public net, it can be adjusted in the core params. We'll also be looking into increasing the limit or disabling it while in Quorum mode.

**Comment by brajeshawasthi** [comment]
max code size option in genesis config PR #786
submitted a PR  #786 to add config option in genesis file to provide maxCodeSize, similar to txnSizeLimit. 

add "maxCodeSize": 64  (value 24 - 128 ) in genesis config
