### ISSUE TITLE
Getting "Certificate validation failed" error when using Constellation version 0.3.2

### ISSUE THREAD

**Issue by Purbaja** [Consensys-Incorporated/quorum#327]
Quorum version : 2.0.1
Constellation version: 0.3.2

When running multiple Quorum nodes with public ip in the constellation start script, getting error ""certificate rejected: Certificate validation failed".
Detail error log trace ::
06:36:15 [WARN] No TLS certificate or key found; generating tls-client-cert.pem/tls-client-key.pem
06:36:21 [WARN] No TLS certificate or key found; generating tls-server-cert.pem/tls-server-key.pem
06:36:25 [WARN] tls-known-clients (ca-or-tofu trust mode): Adding new fingerprint "69:87:33:C3:B0:DC:56:A5:76:E2:0D:30:48:D1:62:69:DF:B8:92:BC:A0:13:F1:AD:63:8E:03:23:74:90:A3:D6:A6:94:EC:BE:CE:B2:4C:62:9B:40:0D:70:14:52:AD:8D:A3:3F:75:AB:DB:84:A6:27:56:10:45:3B:0A:81:7A:A4" for host 52.91.134.142
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))
HandshakeFailed (Error_Protocol ("certificate rejected: Certificate validation failed",True,CertificateUnknown))

How these certificates are getting generated?

**Comment by jpmsam** [comment]
Hi @Purbaja , the certificates are auto-generated when you first launch constellation. Please provide more details on your setup and OS.

I am closing this issue under Quorum, please open it under [constellation](https://github.com/jpmorganchase/constellation/issues) issues.
