### ISSUE TITLE
Can't open database 7nodes example

### ISSUE THREAD

**Issue by Sebastiaandb** [Consensys-Incorporated/quorum#328]
![image](https://user-images.githubusercontent.com/37935662/38143098-4baa89e6-343f-11e8-8473-35ba2ac26b7c.png)

I've been trying all day long to get this working but just don't seem to get where to problem is and how to fix it. Can somebody here help me out? I've reinstalled everything like 7 times already >_< and just want to make one of the examples run to see how it works :-).

**Comment by jpmsam** [comment]
@Sebastiaandb please try running raft-init.sh from **/home/vagrant/quorum-examples**/7nodes.

**Comment by Sebastiaandb** [comment]
@jpmsam Awesome! You just made my day :-).
