### ISSUE TITLE
Cannot do remote call from one contract to another

### ISSUE THREAD

**Issue by upers** [Consensys-Incorporated/quorum#332]
Geth: v1.7.2-stable-ee498061
Operating System: linux-amd64
Go Version: 1.9.3

I am try to do remote call from contract "Controller" to contract "Mode".
If I am invoke function Model#defaultMethod() direct. Transaction gone good and I have got event: Simple.
But if I invoke method Controller#remoteCall() or Controller#remoteCall2(). No events.
It's a simple example for discussing a problem.

All contracts are public. I send signed transactions to node.
Here are my contracts:

contract Controller {
    address model;

    Model contractModel;

    function Controller(address _model) {
        model = _model;
        contractModel = Model(_model);
    }

    function remoteCall() {
        contractModel.defaultMethod(); 
    }

    function remoteCall2() {
        model.call(bytes4(keccak256("defaultMethod()")));
    }
}

contract Model {
    function Model() {}

    event Simple(address from);

    function defaultMethod() {
        Simple(msg.sender);
    }
}

**Comment by jpmsam** [comment]
@upers can you please let us know which Quorum version you are using? Also, do you see any exceptions in the logs?

**Comment by wilcob** [comment]
I experienced a similar issue when running on Quorum version 2.0.1 using Istanbul consensus. In my case I made an ERC-20 token transfer call from another contract. The transaction was made successfully but the actual token transfer never happened and I didn't get any error or whatsoever. After upgrading to 2.0.2, the problem disappeared and it seems I can now make a remote call from one contract to another. 

Judging by the changelog of version 2.0.2, which states various fixes were made for the Istanbul consensus, I guess it just was an issue with the Istanbul consensus.

**Comment by saradotramli** [comment]
@jpmsam  I could confirm that this issue still persists with Quorum 2.0.2 with Raft consensus. 
A method call from one contract instance to an **_existing_** instance of another contract fails.
However able to **_instantiate_** one Contract from another contract.

**Comment by saradotramli** [comment]
>I could confirm that this issue still persists with Quorum 2.0.2 with Raft consensus.
A method call from one contract instance to an existing instance of another contract fails.
However able to instantiate one Contract from another contract.

To be precise, there is no EVM error in the console, however there is no "status" attribute in the transaction receipt and there are no events in the logs array in my case (though they are raised). 

Could also confirm that this was earlier working with Quorum 2.0.0.

**Comment by fixanoid** [comment]
Please reopen if this is still an issue. Thanks.

@saradotramli status attribute was added post 1.7.2 and will become available after we merge upstream 1.8.x release.
