### ISSUE TITLE
What if Party A does not receive a response from Party B  because B is offline.

### ISSUE THREAD

**Issue by tzaika** [Consensys-Incorporated/quorum#333]
Hi Guys. 

I want to try quorum and read the documentation. 
I have a question. 
The documentation says:
> Note that if Party A does not receive a response/receives a Nack from Party B then the Transaction will not be propagated to the network. It is a prerequisite for the recipients to store the communicated payload.

The question is:
What if party A does not get a response from party B because party B is dropped, but we still want to do the private transaction? Let's say there's party C, which returns an answer, and we want the transaction to be saved for A and C, even though B did not return a response.

Thank you in advance for your response.

**Comment by jpmsam** [comment]
@tzaika in this case, you will need to create a new transaction with only party A and C.
