### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by jmcnevin** [Consensys-Incorporated/quorum#335]
Given the news/rumors coming out that JP Morgan may be spinning Quorum off into its own company, and seeing as commit activity in this repo (and Constellation) has been pretty light over the past few months, I'm genuinely curious as to the status of this project.

Would anyone here have any insight?

**Comment by jpmsam** [comment]
@jmcnevin we have been actively working on many use cases with people that are using Quorum across industries. Be confident that we are building Quorum features and on Quorum. More to come!
