### ISSUE TITLE
How to query private stateDB?

### ISSUE THREAD

**Issue by mlmonk** [Consensys-Incorporated/quorum#34]
I am creating private smart contracts. I am trying to list all the private transactions linked to a particular account. I do not want to query the entire blockchain.

Is there is a way (or the best approach) to query just the private stateDB (.ldb) of a node to find all transactions of an account?

**Comment by davoell** [comment]
Typically this would be the job of a blockchain explorer and we're considering adding this feature to Cakeshop. In the mean time you could record the info you need into the contract or generate an event that some off chain process catches to record the transaction. We don't expose any API's to query leveldb.
