### ISSUE TITLE
BFT Raft Algorithm (E.g., Tangaroa) in planned roadmap?

### ISSUE THREAD

**Issue by nathanawmk** [Consensys-Incorporated/quorum#342]
#### System information

Hi all. 

Three questions:

1. Beyond Raft and Instabul, are there plans for other pluggable consensus? 
 
2. BFT Raft Algorithm (E.g., Tangaroa) is in the planned roadmap? Is there a need for BFT algorithm? 

Thanks!

Nathan Aw

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by jpmsam** [comment]
@nathanawmk 

1. Not currently but a variation of Tendermint was an option that we reviewed with the Tendermint  team.
2.Istanbul BFT is currently our supported BFT consensus algo.

Thanks,
Sam
