### ISSUE TITLE
empty blocks are created in istanbul consensus with quorum v2.0.2

### ISSUE THREAD

**Issue by renuseabhaya** [Consensys-Incorporated/quorum#343]
#### System information

Geth version: `geth version`
eth/v1.7.2-stable-df4267a2
OS & Version: Windows/Linux/OSX
Ubuntu16.04
Branch, Commit Hash or Release: `git status`

#### Expected behaviour
block should be created on transactions

#### Actual behaviour
Empty blocks are created on zero transactions, transactions.length is '0'

#### Steps to reproduce the behaviour
created node setup using istanbul tools 

#### Backtrace

````
[backtrace]
````

**Comment by jpmsam** [comment]
@renuseabhaya That's expected with istanbul. @markya0616 can provide more insight.

**Comment by markya0616** [comment]
Yes, we followed the original Ethereum design. Blocks with 0 transactions are allowed.
