### ISSUE TITLE
How can I create private Contract from Contract?

### ISSUE THREAD

**Issue by tzaika** [Consensys-Incorporated/quorum#345]
Hi Guys.

I am trying quorum and read the documentation.
My Smart Contract for normal Ethereum network looks like this one:

```
contract Factory {
    address[] newContracts;

    function createContract (bytes32 name) {
        address newContract = new Contract(name);
        newContracts.push(newContract);
    } 
}

contract Contract {
    bytes32 public name;

    function Contract (bytes32 _name) {
        name = _name;
    }
}
```
So, if I want to create contract from contract  I call method : `createContract(...);` 

But can I do something like:

```
function createContract (bytes32 name) {
    address newContract = new Contract(name, {privateFor: ['ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc=']});
    newContracts.push(newContract);
}
``` 
???
Solidity Compiler threw : `ParserError: Expected primary expression.`
I have tried to find something in Solidity docs but not successful.

Thank you in advance for your response.

**Comment by jpmsam** [comment]
hi @tzaika , that's currently unsupported.

**Comment by tzaika** [comment]
@jpmsam Thanks for your quick answer. I have already found a way to get around the problem. Are you planning to support it in feature actually?

**Comment by drandreaskrueger** [comment]
> currently unsupported.

@jpmsam Does that have hard reasons? i.e.: Or do you think it would be possible to implement?


>  found a way to get around the problem. 

What is your workaround, @tzaika  ?

**Comment by tzaika** [comment]
@drandreaskrueger I deploy the second contract separately with needed (privateFor) and then in my first contract I created function
```
function addContract (address newContract) {
    newContracts.push(newContract);
}
```
So i can get Contract-instance with 
`Contract instance = Contract(newContracts[index]); // contract address is strored under 'index'`

**Comment by omkarkhair** [comment]
If I have deployed a private contract that deploys a new contract. Does the new contract also remain private for the same parties?

**Comment by jpmsam** [comment]
@omkarkhair Yes

**Comment by dbccdeloitte** [comment]
@tzaika - Hi, I came across your question during solution findings. Can you please explain more specifically how does the workaround works? Let says, I have a Factory contract(Public) to create private transactions. Please advise.
