### ISSUE TITLE
Cannot Deploy Contract to RHEL7 Release

### ISSUE THREAD

**Issue by shaunnbarron** [Consensys-Incorporated/quorum#347]
#### System information

Geth version: `geth version`
1.7.2

OS & Version: Windows/Linux/OSX
client - macOS Sierra 10.12.6
quorum network - RHEL7

Branch, Commit Hash or Release: `git status`
name = "github.com/ethereum/go-ethereum"
revision = "df4267a25637a5497a3db9fbde4603a3dcd6aa14"
source = "github.com/jpmorganchase/quorum"
version = "v2.0.2"

#### Expected behaviour
Successful contract deployment

#### Actual behaviour
`2018/04/18 08:59:56 failed to retrieve account nonce: Raft mode has no Pending block. Use latest instead.`

#### Steps to reproduce the behaviour
Here's a gist of the code I'm using to deploy contracts:
https://gist.github.com/barrongineer/395e8a67043ba1d7f73fe0ea8db057a5

This code will successfully deploy to the quorum-examples 7nodes raft vagrant box. However, when trying to deploy to the Quorum RHEL7 release, we get the error above. If we try to get around it by setting `bind.TransactOpts.Nonce` to the latest block, the transaction never completes. `bind#WaitDeployed` will wait forever.

#### Backtrace

````
[backtrace]
````

**Comment by jpmsam** [comment]
This has to do with the custom build you have and the network setup.
