### ISSUE TITLE
[Question] How to add Peers in Quorum Single Member Blockchain Network in Azure?

### ISSUE THREAD

**Issue by danbale** [Consensys-Incorporated/quorum#348]
I tried to add it with the option it gives but only displays a message 
![image](https://user-images.githubusercontent.com/25161964/38945504-83e77ac0-42eb-11e8-8798-8a4720251698.png)

But it does not add the peer do I have to do something else?

**Comment by fixanoid** [comment]
@danbale, are you setting up cakeshop nodes or quorum nodes?

**Comment by danbale** [comment]
@fixanoid, Hello, i tried to add quorum node, does it has to be cakeshop node? thanks for your answer

**Comment by jpmsam** [comment]
@caleteeter would you be able to help on this please ?

**Comment by caleteeter** [comment]
@danbale  sorry for the silence here.  I took a look at this.  The adding peers via the Cakeshop interface would require you to setup the peer first and get the enode from the peer (and it have connectivity and the same genesis block).  We are in the process of migrating this offering to the latest bits Quorum bits (along with moving to RAFT/iBFT consensus).  This is already available in the [demo](https://portal.azure.com/#create/enterprise-ethereum-alliance.quorum-demoquorum-demo).  You might try this out as well if you haven't tried it.  There is a good tutorial over [here](https://medium.com/getamis/istanbul-bft-ibft-c2758b7fe6ff).  Also, I will take a crack at documenting the process of adding a peer to the single network template, and publish along with the updates template.

**Comment by fixanoid** [comment]
Please reopen if this is still an issue. Thanks.

**Comment by eman-22** [comment]
Hello, I tried to add peers via the cakeshop interface ("add peers" button), but it is not working.
Where can I find a good guide showing all the steps required for this

**Comment by SatpalSandhu61** [comment]
Hi, please don't ask questions on closed issue tickets. Instead, raise a new ticket with details of the behaviour, how to reproduce and any error message you see. Or you can ask the question on our Slack channel: https://www.goquorum.com/slack-inviter
