### ISSUE TITLE
Quorum block maker node creating transactions automatically. 

### ISSUE THREAD

**Issue by karthik137** [Consensys-Incorporated/quorum#355]
I am using quorum-maker a third party tool to set up the chain. I have noticed that block maker node is creating transactions ( 4 to 5 per block) on its own. Why block maker is creating transactions on its own?. 

Here is the  transaction receipt

`
{
  blockHash: "0xd23f067e64a2652fd4754b3f24f9224d1312a1d8d5894983358c00d82037e698",
  blockNumber: 1,
  from: "0x1fff79296e2dbd3965053c4e24423156f2329213",
  gas: 106932,
  gasPrice: 0,
  hash: "0xbaced6d31207960f85d56032714ed6356943d53e73c64e2d6686a155ac63c40b",
  input: "0x68bb8bb60000000000000000000000000000000000000000000000000000000000000001990bef97701e3c419e15e11d6c59fe491b95b7fb092fb13484de4c2a1df0f475",
  nonce: 0,
  r: "0x7de63826446588eb2915c39e132e15169d981a2118f0b4a6531f2ed4ee00df65",
  s: "0x19bee19566076b739329fbd4f88cd8dc4243e4ddccbc6ee8f2eee9c94b8c3ce2",
  to: "0x0000000000000000000000000000000000000020",
  transactionIndex: 0,
  v: "0x1b",
  value: 0
}
`

Why are these transactions created?. We see that these transactions are created in every block.

#### Geth version: geth version

Version: 1.5.0-unstable

#### OS & Version: Windows/Linux/OSX

Ubuntu 16.04.1 LTS

**Comment by jpmsam** [comment]
@karthik137 It seems that Quorum Maker has deployed an old version of Quorum which has QuorumChain running. QuorumChain created blocks based on a block time interval regardless of whether transactions existed or not.
