### ISSUE TITLE
Still can send transactions when balance is zero on v.2.0

### ISSUE THREAD

**Issue by KimiWu123** [Consensys-Incorporated/quorum#356]
#### System information
Quorum version: 2.0.1
OS & Version: Linux (Ubuntu 16.04)

#### Description
If an account's balance is zero, it's not allowed to send txs in v.1.2. However, we upgraded to 2.0 and txs could be sent even if the balance is zero. Is it configurable? or it's a new spec in 2.0? 

Thanks.

**Comment by jpmsam** [comment]
@KimiWu123 This was updated in V2 when running in Quorum mode given that the price of gas is 0.

**Comment by KimiWu123** [comment]
@jpmsam , 
sorry, what is Quorum mode? How can I change or config this behavior? If someone's balance is zero and still can send txs, how to could we prevent from garbage txs attacking? BTW, we are using raft as our consensus, is there any different?  Thanks.
