### ISSUE TITLE
Why do you use a voting system instead of Tendermint or BFT?

### ISSUE THREAD

**Issue by pipaman** [Consensys-Incorporated/quorum#36]
I want to know why you decided to implement your own voting system instead of Terdermint for Ethereum.

**Comment by davoell** [comment]
A little over a year ago Jeff Wilcke began describing to us his idea for a smart contract based consensus algorithm. He and Bas are the experts on this but the really cool and unique feature of this approach is that you can easily change the rules of consensus, block makers, voters, etc. without the need of a hard fork with explicit code for the old rules and at a specific block number the code for the new rules. In a permissioned network having this ability to precisely control the block makers and voters, in an extremely transparent manner (using the protocol itself) makes a lot of sense. That being said the longer term goal here is to support multiple consensus algorithms and allow the network creators decide which consensus algo work best for their specific use case. Tendermint has some excellent properties and we'd love to see it and other consensus algo's available on Quorum.
