### ISSUE TITLE
Add feature to get decrypted transaction input for parties privy to aforementioned private txn

### ISSUE THREAD

**Issue by rjbanner** [Consensys-Incorporated/quorum#360]
I am trying to decode the input string returned from a transaction using the simple storage contract's set() function.
For a sample public transaction(contractobject.set(99)) input string is coming as

0x6060604052341561000c57fe5b6040516020806100fa83398101604052515b60008190555b505b60c6806100346000396000f300606060405263ffffffff60e060020a6000350416632a1afcd98114603457806360fe47b11460535780636d4ce63c146065575bfe5b3415603b57fe5b60416084565b60408051918252519081900360200190f35b3415605a57fe5b6063600435608a565b005b3415606c57fe5b60416093565b60408051918252519081900360200190f35b60005481565b60008190555b50565b6000545b905600a165627a7a72305820dd78f3524b7023f728792f08d13c21b31c1c85f6e949db71bafe10ae2cbc75170029000000000000000000000000000000000000000000000000000000000000002a

I am not able to decode it using soliditycoder.decodeparams.

In case of private transactions, for the same function call the input string showing up is completely different.

Shouldn't  the input string be visible on the node which is privy to that transaction ? 
Since logs are available for private transactions at a node if the node is privy to that transaction, the input field returned from the getTransaction function call could display similar behavior

**Comment by jpmsam** [comment]
@rjbanner No, the input string won't be visible on the transaction, only the hash will be visible and the payload will only be available in the transaction manager. You can use the [GetQuorumPayload](https://github.com/jpmorganchase/quorum/blob/f651c1befa8ea020f762d9d35ef0027846db2d3d/internal/ethapi/api.go#L1549) RPC call to get the payload details.
