### ISSUE TITLE
Synchronisation failed in geth --fast mode.

### ISSUE THREAD

**Issue by teambc123** [Consensys-Incorporated/quorum#362]
#### System information

Geth version: `Geth Version: 1.7.2-stable
Quorum Version: 2.0.1
Go Version: go1.7.3

OS & Version: Linux

Branch, Commit Hash or Release: `git status`
Git Commit: ee498061b5a74bf1f3290139a53840345fa038cb

#### rename your chaindata in one of the node (I did in dd2)
Edit the script in raft-start.sh as below: (Using geth --fast mode for synchonization)
PRIVATE_CONFIG=qdata/c1/tm.ipc nohup geth --datadir qdata/dd1 $ARGS --permissioned --raftport 50401 --rpcport 22000 --port 21000 --unlock 0 --password passwords.txt 2>>qdata/logs/1.log &
PRIVATE_CONFIG=qdata/c2/tm.ipc nohup geth --fast --datadir qdata/dd2 $ARGS --permissioned --raftport 50402 --rpcport 22001 --port 21001 2>>qdata/logs/2.log &
PRIVATE_CONFIG=qdata/c3/tm.ipc nohup geth --fast  --datadir qdata/dd3 $ARGS --permissioned --raftport 50403 --rpcport 22002 --port 21002 2>>qdata/logs/3.log &
PRIVATE_CONFIG=qdata/c4/tm.ipc nohup geth --datadir qdata/dd4 $ARGS --permissioned --raftport 50404 --rpcport 22003 --port 21003 2>>qdata/logs/4.log &
PRIVATE_CONFIG=qdata/c5/tm.ipc nohup geth --datadir qdata/dd5 $ARGS --raftport 50405 --rpcport 22004 --port 21004 2>>qdata/logs/5.log &
PRIVATE_CONFIG=qdata/c6/tm.ipc nohup geth --datadir qdata/dd6 $ARGS --raftport 50406 --rpcport 22005 --port 21005 2>>qdata/logs/6.log &
PRIVATE_CONFIG=qdata/c7/tm.ipc nohup geth --datadir qdata/dd7 $ARGS --raftport 50407 --rpcport 22006 --port 21006 2>>qdata/logs/7.log &

#### Logs from 2.log file:
INFO [05-02|08:22:28] synchronizing with peer                  peer id=1                                                                                                                                hash=314fee…a41176
WARN [05-02|08:22:28] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [05-02|08:22:28] failed to synchronize with peer          peer id=ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef
INFO [05-02|08:22:28] synchronizing with peer                  peer id=3                                                                                                                                hash=314fee…a41176
WARN [05-02|08:22:28] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [05-02|08:22:28] failed to synchronize with peer          peer id=579f786d4e2830bbcc02815a27e8a9bacccc9605df4dc6f20bcc1a6eb391e7225fff7cb83e5b4ecd1f3a94d8b733803f2f66b7e871961e7b029e22c155c3a778
INFO [05-02|08:22:29] synchronizing with peer                  peer id=4                                                                                                                                hash=314fee…a41176
WARN [05-02|08:22:29] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [05-02|08:22:29] failed to synchronize with peer          peer id=3d9ca5956b38557aba991e31cf510d4df641dce9cc26bfeb7de082f0c07abb6ede3a58410c8f249dabeecee4ad3979929ac4c7c496ad20b8cfdd061b7401b4f5
INFO [05-02|08:22:29] synchronizing with peer                  peer id=5                                                                                                                                hash=314fee…a41176
WARN [05-02|08:22:29] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [05-02|08:22:29] failed to synchronize with peer          peer id=3701f007bfa4cb26512d7df18e6bbd202e8484a6e11d387af6e482b525fa25542d46ff9c99db87bd419b980c24a086117a397f6d8f88e74351b41693880ea0cb
INFO [05-02|08:22:30] synchronizing with peer                  peer id=6                                                                                                                                hash=314fee…a41176
WARN [05-02|08:22:30] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [05-02|08:22:30] failed to synchronize with peer          peer id=eacaa74c4b0e7a9e12d2fe5fee6595eda841d6d992c35dbbcc50fcee4aa86dfbbdeff7dc7e72c2305d5a62257f82737a8cffc80474c15c611c037f52db1a3a7b
INFO [05-02|08:22:30] synchronizing with peer                  peer id=7  

````
````

**Comment by jpmsam** [comment]
@subhasis-dgsl due to the privacy requirements, Quorum doesn't currently support fast sync.
