### ISSUE TITLE
State tree location

### ISSUE THREAD

**Issue by nottherealbatman** [Consensys-Incorporated/quorum#363]
According to the wiki https://github.com/jpmorganchase/quorum/wiki/Transaction-Processing, the state tree is saved locally and not synchronized to the network. Where is this state tree saved as this is usually stored in the block.

**Comment by jpmsam** [comment]
Its configurable based on the --datadir flag. This [answer](https://ethereum.stackexchange.com/questions/359/where-is-the-state-data-stored) should give you a quick good overview on the differences between the local state and the transactions that are synced from other nodes.
