### ISSUE TITLE
Disk Space - Storage Optimization - Quorum 1.1

### ISSUE THREAD

**Issue by sanbalj919** [Consensys-Incorporated/quorum#365]
#### System information

Geth version: Quorum 1.1

OS & Version: Linux

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
I am not reporting an issue but trying to find what options are available to optimize disk storage in Quorum. With Pruning or light mode not feasible with Quorum, I would like what other options are available to reduce the amount of space consumed by underlying Level DB to store the entire Ethereum' state.

#### Actual behaviour
We have a permissioned network running on Quorum 1.1 with RAFT consensus. Smart contract has 2 mappings where key is keccak hash in both cases with the value being a struct holding - bytes32, address.

Concern is around disk space which is already past 150 GB because both mappings now hold 16 millions of hashes and is expected to grow 1.5 million every month
#### Backtrace
Could you please suggest how we can optimize the data storage given this volume and smart contract can't be changed?

In our case, we don't have to store the blockchain state for each block mined? Most recent state or the states for last 'n' blocks should be fine?
````
[backtrace]
````

**Comment by jpmsam** [comment]
You can look at the [eth pruner](https://github.com/blockapps/eth-pruner) tool from blockapps for reference, it might not be up to date but it provided a process to prune the local DB.
