### ISSUE TITLE
Question: Is the underlying LevelDB in Quorum enabled by default with Snappy compression? 

### ISSUE THREAD

**Issue by sanbalj919** [Consensys-Incorporated/quorum#366]
#### System information

Geth version: Quorum 1.1

OS & Version: Linux

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
Question: Compression in Level DB

#### Actual behaviour
Is the underlying LevelDB in Quorum enabled by default with Snappy compression? Or should we enable with special config?
````
[backtrace]
````

**Comment by jpmsam** [comment]
LevelDB by default uses Snappy to compress all the data.
