### ISSUE TITLE
Private transactions and setting PrivateFor - Question

### ISSUE THREAD

**Issue by davebryson** [Consensys-Incorporated/quorum#37]
In the 7 nodes example, when deploying the simple contract the `privateFor` is set to the public key of the constellation node running on Node7.   

Is `privateFor` always set to the public key(s) of  the intended constellation node(s)?  Or can I send a private transaction to any user in the Quorum network by setting the`privateFor` to the public key associated with a specific user (externally owned account)?

**Comment by patrickmn** [comment]
Indeed, `privateFor` is always an array of public keys of Constellation nodes. It isn't possible to specify an Ethereum signing key, although you could imagine having a contract that resolves Constellation public keys to Ethereum account addresses. The participants in a network can choose to map Constellation keys 1:1 with the Ethereum signing keys, or use a different scheme that makes sense based on the use case.

**Comment by davebryson** [comment]
Thanks for the response and great work.  So in that case, *who* is allowed to read a private contract on a given node?  Only coinbase on that node and the creator of the private transaction?  Or anyone with an account *known* ( in the keystore directory) to that specific geth node and the creator of the private contract?

**Comment by patrickmn** [comment]
The state updates of private transactions, whether contact creations or not, are visible to all accounts on a node, as long as that node's private transaction manager was party to the transactions (its public key was listed in privateFor.)

**Comment by davebryson** [comment]
Thanks.  One thing I have noticed is that if RPC is enabled on the node, anyone (that has the ABI and contract address) can view the private state of a private contract via normal web3 json-rpc calls.

**Comment by patrickmn** [comment]
Indeed, this is the intended behavior. Transaction/contract privacy is at the node (not account) level, at least currently.
