### ISSUE TITLE
Solidity 0.4.23 does not work properly on latest quorum release (2.0.2)

### ISSUE THREAD

**Issue by nottherealbatman** [Consensys-Incorporated/quorum#371]
When compiling with 0.4.23 quorum contracts return null responses
See full issue posted at truffle https://github.com/trufflesuite/truffle/issues/936 as it was though to be an truffle issue

**Comment by fixanoid** [comment]
@nottherealbatman Quorum is currently up to Geth 1.7.2 which limits its Solidity to 0.4.18 (need to confirm breaking changes). We've plans for updating Geth, but this is an ongoing long term project that will take time before we pulled in Solidity changes.

**Comment by kyriediculous** [comment]
Seems to me that this is not really worth it to migrate until a major release aka 0.50.0? 
 although slowly preparing the changes in between 0.4.18 and 0.50.0 for a PR isn't a bad idea I think. 

I do like that quorum is using more up to date geth versions than hyperledger burrow (still no require, revert and assert :( )

**Comment by nottherealbatman** [comment]
The reason why I brought this up because 0.4.23 brings a lot of nice new features with it like returning dynamic arrays and custom error messages. And it is building up to the 0.5.0 release so maybe slowly preparing isn't a bad idea.

**Comment by jpmsam** [comment]
@nottherealbatman  0.4.23 is supported, I have tested a few contracts and it works. Please make sure you are using the latest quorum-examples with the updated genesis block. I recently made an [update to the genesis](https://github.com/jpmorganchase/quorum-examples/commit/6094f9e3aae42a2ed137d84dd765ee592acc85e4) file to enable byzantium at block 1.

**Comment by nottherealbatman** [comment]
@jpmsam In our test it was not reliable, we encountered strange bugs which we didn't had with 0.4.18. See link in opening post to the truffle issue.

**Comment by jpmsam** [comment]
@nottherealbatman which genesis file were you using and was it on a new network? I will try to replicate using the steps provided on the truffle issue.

**Comment by arnoudbevers** [comment]
Just to chime in here, since I was the one submitting the truffle issue:

- It was an 'old network', set up a few months ago and started with the same versions as in the truffle issues, using Solidity 0.4.18 initially.
- The genesis file was generated in a setup.sh script allocationg the balance to every account in the network (hence the ${account}.

```
{
	 "alloc": {
	 "${account}": {
		  "balance": "1000000000000000000000000000"
		}
	  },
	  "coinbase": "0x0000000000000000000000000000000000000000",
	  "config": {
		"homesteadBlock": 0
	  },
	  "difficulty": "0x0",
	  "extraData": "0x",
	  "gasLimit": "0xFFFFFFFFFFFF",
	  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
	  "nonce": "0x0",
	  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
	  "timestamp": "0x00"
}
```

**Comment by jpmsam** [comment]
@arnoudbevers thanks for chiming in. Would you be able to do run the same test using the latest [genesis](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/genesis.json) block?

**Comment by fixanoid** [comment]
Hi, so I've tested this just now on our quorum-examples repo in local mode. I'm on a mac running quorum / constellation master builds, latest 10x node and latest truffle. The findings:

1. In raft mode, with new genesis config that specifies "byzantiumBlock" the contracts compile and test runs as expected
2. In IBFT mode, with missing "byzantiumBlock" the contracts behave as you point out and error with 0x
3. In IBFT mode, when editing the genesis config to include "byzantiumBlock" the contracts and test run as expected

So, looks like you may need to re-init your Quorum with genesis config "byzantiumBlock": 1.


Curiously, when testing in raft mode, truffle repeatedly timed out during migration and test. I've yet to find out why this is happening but it seems that if I execute another txn in the geth console, before it timed out, truffle chugs along.

@arnoudbevers @jpmsam

**Comment by jpmsam** [comment]
@fixanoid Thanks! Please patch the Istanbul genesis block and you should be able to close this issue.

**Comment by fixanoid** [comment]
Patched just now.

**Comment by arnoudbevers** [comment]
Thank you, I haven't had much time to look into the issue the last couple of weeks. I'll keep it in mind for the next deployment! 
Thanks for your help!
