### ISSUE TITLE
Wrong information on the wiki

### ISSUE THREAD

**Issue by bkolad** [Consensys-Incorporated/quorum#373]
From Wiki

Transaction-Processing section
https://github.com/jpmorganchase/quorum/wiki/Transaction-Processing

Point 5:
> Party A's Transaction manager then stores the encrypted payload (encrypted with the symmetric key) and encrypted symmetric key using the hash as the index, and then **_securely transfers_** (via HTTPS) the **_hash_** .. 

However in constellation wiki:
https://github.com/jpmorganchase/constellation

Point 6:

> 
> The recipient node returns a SHA3-512 hash digest of the encrypted payload, which represents its storage address.
> 
> **_(Note that it is not possible for the sender to dictate the storage address. Every node generates it independently by hashing the encrypted payload.)_** 

Which seems to contradict information on this wiki.

**Comment by jpmsam** [comment]
@bkolad , that is correct. Constellation rehashes the encrypted payload to guarantee that its the same hash for the payload.

**Comment by bkolad** [comment]
If that is the case, is it ok to remove the misleading information from this wiki (about transferring the hash)?
