### ISSUE TITLE
Storage optimization: Quorum 1.1.0 vs 2.0.1

### ISSUE THREAD

**Issue by teambc123** [Consensys-Incorporated/quorum#374]
#### System information

Geth version: `geth version`
Geth
Version: 1.7.2-stable
Git Commit: ee498061b5a74bf1f3290139a53840345fa038cb
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.7.3

#### Expected behaviour
Storage expected to be 1.5 GB 

#### Actual behaviour
Storage : 150 MB

#### Steps to reproduce the behaviour
deployed the project in Quorum 1.1.0 and then 2.0.1

#### Backtrace
Hi,
We have created our project using quorum 1.1.0. From then till now we have processed 15Million records and it is occupied 150+GB space.
Now we are deployed the same project using quorum 2.0.1 but there will be a huge difference in storage place.

Could you please let me know wether there was storage optimization is introduced after 1.1.0 and give some reference.

[backtrace]
````

**Comment by jpmsam** [comment]
@subhasis-dgsl in Quorum 2.x, we removed support for QuorumChain. QuorumChain generated blocks continuously whereas raft only generates blocks when transactions are present.

**Comment by teambc123** [comment]
Hi jpmsam,

We are using Raft consensus in Quorum1.x . 
Please find below script for raft-init:
geth --datadir qdata/dd2 --rpccorsdomain "*" --rpcport 22001 --port 23001 --raftport 21001 --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum console

Can you please advise?
