### ISSUE TITLE
 TxPool increases when block maker is paused.

### ISSUE THREAD

**Issue by karthik137** [Consensys-Incorporated/quorum#376]
#### Description of problem

When block-maker is paused pending transactions in txPool increases. Nodes are voting when block-maker is stopped. According to the quorum's documentation `After successfully validating a block, Voters will cast a vote for the block by calling the BlockVoting contract.` Why voter nodes are executing the block voting contract when block maker node is paused?. Are they checking the status of block maker?. I am using quorum-maker tool to setup quorum network.
#### Expected behavior

Voting nodes should not vote. They should check block-maker node status.
#### Steps to reproduce the behavior

Setup quorum chain using quorum-maker tool. Stop the block maker (quorum.pauseBlockMaker()). Check txPool status.
##### Geth version: geth version

Version: 1.5.0-unstable
#### OS & Version: Windows/Linux/OSX

Ubuntu 16.04.1 LTS

**Comment by jpmsam** [comment]
@karthik137 We have deprecated QuorumChain in V2 of Quorum and the quorum-maker team will be releasing an updated version for Quorum. 
cc @dhyansraj for the quorum maker update.

**Comment by dhyansraj** [comment]
Quorum Maker version 1 supports Raft in development mode. We will soon release a new version of Quorum Maker that supports Raft in production grade environment as well.
