### ISSUE TITLE
Istanbul BFT node shows "old message" error when it received a lot of TXs.

### ISSUE THREAD

**Issue by andybclee** [Consensys-Incorporated/quorum#381]
#### System information

Geth version: `geth version`
1.7.2, Quorum 2.0.2
OS & Version: Windows/Linux/OSX
Ubuntu 16.04

Branch, Commit Hash or Release: `git status`
branch master

#### Expected behaviour
Handle a lot of txs smoothly =)

#### Actual behaviour
We are testing quorum with Istanbul BFT. 9 nodes are running, and only one of them are receiving TXs from client.
We sent 150 txs/sec (contract call) to the receiving node and it worked fine to some point. But after some point, the receiving node couldn't handle txs. 
And it shows "unexpected request" with "old message" error message. 

I've found the error happened at core.handleRequest in istanbul consensus but cannot understand the reason exactly.

When it showed the message, the number of pending txs are above 40,000

But all other nodes worked fine except that the receiving node can't propose its block properly.

#### Backtrace

````
[backtrace]
````

**Comment by vietlq** [comment]
Do you have script that sends the tx for testing? I would like to use it to play with Quorum examples

**Comment by fixanoid** [comment]
@vietlq we use [chainhammer](https://github.com/drandreaskrueger/chainhammer) for txn spam / testing.

**Comment by fixanoid** [comment]
@andybclee please re-confirm the issue with newest Quorum and reopen if its still there. Thank you.
