### ISSUE TITLE
Not able to execute complex contract functions

### ISSUE THREAD

**Issue by vasa-develop** [Consensys-Incorporated/quorum#384]
#### System information

Geth version: `geth version`
Geth
Version: 1.7.2-stable
Git Commit: d4a1b09581359100d51ecc43c81868955806a782
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.10.1
Operating System: linux
GOPATH=/root/gopath
GOROOT=/root/go

OS & Version: Windows/Linux/OSX
Linux

#### Expected behavior
I am not able to execute complex functions(say functions with more than 1 parameter). The transactions are failing when I execute a big function, but when I break it into smaller functions then it starts working. 

My concern is that the same complex functions are executing successfully in Remix IDE on Rinkeby testnet. So, is this some problem with Quorum or there is some problem with my side?
[Here](https://gist.github.com/vasa-develop/885583d0852110587a1e311665980a0f) is the contract I am using and [here](https://gist.github.com/vasa-develop/ec2a9fbbbfad15bd63ec335f232b4747) is the js script I am using to execute the function. 
. 

P.S. the contract is public, not private.
#### Actual behaviour
When I read the values in the js script, the result comes out to be blank.

#### Steps to reproduce the behaviour
Deploy [this](https://gist.github.com/vasa-develop/885583d0852110587a1e311665980a0f) contract as a public contract and execute `createAccount` and read the values from contract using [this](https://gist.github.com/vasa-develop/ec2a9fbbbfad15bd63ec335f232b4747) script.

**Comment by jpmsam** [comment]
@vasa-develop you should change the amount of default gas being passed to the `contract.createAccount` transaction. You can include something similar to `,{from: web3.eth.accounts[0],gas: '800000'},` after the bool parameter.
