### ISSUE TITLE
block in the future

### ISSUE THREAD

**Issue by yacc2007** [Consensys-Incorporated/quorum#385]
I just let one node be the block maker, and the other node sync the block , but why appear this problem? 
![image](https://user-images.githubusercontent.com/6888202/40636636-961511e6-6332-11e8-8a16-1f8dde69ba50.png)

**Comment by stevenroose** [comment]
We had this problem. We were in AWS and solved it by using NTP with Chrony.

https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/

**Comment by lumian2015** [comment]
You need to sync the time in all the machines before you run the program

**Comment by fixanoid** [comment]
tracked via #389
