### ISSUE TITLE
How to cover transactions with nonce

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#398]
Because gas is set to be fixed, gas cannot be changed.

**Comment by ghost** [comment]
`
> eth.sendTransaction({from:eth.coinbase,to:eth.coinbase,value:1,nonce:264,gas:90000000,gasPrice:0})
Error: replacement transaction underpriced
    at web3.js:3143:20
    at web3.js:6347:15
    at web3.js:5081:36
    at <anonymous>:1:1

`

**Comment by dmytronasyrov** [comment]
I have the same issue right now.
Quorum version - today's master branch
Constellation 0.3.2
Truffle works fine - migrations passed from coinbase account, transactions can be send, blocks are created. Config below:
```
networks: {
    KIM1: {
      host: "127.0.0.1",
      port: 22000,
      network_id: "10",
      gasPrice: 0,
      gas: 4612388
    }}
```

From iOS with the same config I get:
1. When send transaction the first time - it passed with transaction hash returned, but receipt is null and by inspecting blocks there is no transaction done.
2. The next time I send the same transaction and get "replacement transaction underpriced". I have tried to increase nonce and this will back me to the step 1.
3. Then I send new transaction via geth - it passed.
4. Back to step 1.
I have even sniff HTTP requests with Wireshark to be sure the response is from Quorum and not from cache of iOS library.

Note: this is only when I send transactions to smart contract(existing address). In case of unused address Quorum sends back a receipt and block is created.

Any suggestions?

**Comment by fixanoid** [comment]
@dmytronasyrov whats in the genesis? Please take a look at quorum examples genesis config and make sure it matches:  https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/genesis.json
