### ISSUE TITLE
IBFT based set up does not result in consistent firing of events

### ISSUE THREAD

**Issue by skarred14** [Consensys-Incorporated/quorum#400]
#### System information
Geth version: `1.7.2`
OS & Version: Linux/OSX
Quorum: 2.0.2
Consensus: IBFT
Set Up: 3 quorum nodes (along with constellation nodes) and a bootnode (for discovery)
Web3: 1.0.0.23 beta
#### Expected behaviour
Upon executing a transaction on the chain, an associated event is to be emitted whenever the function in the smart contract is invoked.

#### Actual behaviour
Events are emitted sporadically, even though there is a state change on the blockchain

#### Steps to reproduce the behaviour
Consider the following smart contracts:
```
pragma solidity ^0.4.18;

contract Product {
  bytes32 public name;
  bytes12 public productId;

  function Product (bytes32 _name, bytes12 _productId) public {
    name = _name;
    productId = _productId;
  }

  function getInfo () external view returns (bytes32, bytes12) {
    return (name, productId);
  }
}

```

```
pragma solidity ^0.4.18;

import './Product.sol';

contract ProductCatalog {
  Product[] public products;
  mapping(bytes12 => Product) public productIdToProduct;

  event ProductCreated(address productAddress, bytes32 name, bytes32 productId);

  function createProduct(bytes32 name, bytes12 productId) external returns (address) {
    Product product = new Product(name, productId);
    products.push(product);
    productIdToProduct[productId] = product;

    ProductCreated(product, name, productId);
  }

  function getProductCount () external view returns (uint) {
    return products.length;
  }
}
```
And here is the corresponding `products.js` code to capture the results:
```
import express from 'express';
import get from 'lodash/get';
import Web3 from '../web3'; //using an http provider
import { hexToUtf8, utf8ToHex } from '../utils';
import productContractMetadata from '../../contracts/Product.json';
import productCatalogMetadata from '../../contracts/ProductCatalog.json';

const router = express.Router({ mergeParams: true });
const web3 = Web3();

const productCatalogInstance = new web3.eth.Contract(
  productCatalogMetadata.abi,
  productCatalogMetadata.networks['5'].address,
);

router.post('/', async (req, res) => {
  const { name, productId } = req.body;

  if (!name || !productId) {
    return res.sendStatus(400);
  }

  try {
    const accounts = await web3.eth.getAccounts();
    const product = await productCatalogInstance.methods
      .createProduct(utf8ToHex(name), utf8ToHex(productId))
      .send({
        from: accounts[0],
        gas: 1000000,
      });

    const event = get(product, 'events.ProductCreated.returnValues');

    if (!event) {
      return res.status(520).json({
        error: 'ProductCreated event not returned properly from ProductCatalog contract.',
      });
    }

    return res
      .status(201)
      .location(`/products/${event.productAddress}`)
      .json({
        address: event.productAddress,
        name: hexToUtf8(event.name),
        productId: hexToUtf8(event.productId),
      });
  } catch (err) {
    console.error(err);
    return res.status(500).json({ error: err.message });
  }
});

router.get('/', async (req, res) => {
  const { start = 0, count = 20 } = req.query;

  const totalCount = 
    productCatalogInstance.methods.getProductCount().call();
  return res.json('Total-Count', totalCount);
});

export default router;
```
We notice that upon calling the products post end point, we get `520` from product creation calls, about 50% of the time. We have tried numerous variations of changing web3 version, upgrading quorum, having a timeout between receipt capture and event extraction, and several other methods such as `getPastEvents` and `allEvents`, all to no avail. Additionally, to provide more context we have run several creation of product calls, and a test api that runs the following code, sequentially for a few test runs. In 2.0.1 we observed, exactly 66.6% of the times we are able to view the event logs, and the remaining times, the event logs are empty for that particular invocation. but after upgrading to 2.0.2 it has become even more sporadic. 
```
const productsCreated = await productCatalogInstance.getPastEvents('ProductCreated', {
      fromBlock: 0,
      toBlock: 'latest',
    });
```

Example of a failed event capture result:
```
"transactionHash": "0x759483e1d5a3c0eda51bc6c7ef4746406f1795c46e6293116e0199b90cee8485",
        "transactionIndex": 0,
        "events": {}
```
Example of a successful event capture result:
```
"transactionHash": "0xe277bad91a11915d2f24927d478376e8ec3a3b750f38f8e1163d28f9e8a2fb00",
        "transactionIndex": 0,
        "events": {
            "0": {
                "address": "0x471a243720f361E83B2E5AA7d84fB3A83B9763B1",
                "blockNumber": 1688,
                "transactionHash": "0xe277bad91a11915d2f24927d478376e8ec3a3b750f38f8e1163d28f9e8a2fb00",
                "transactionIndex": 0,
                "blockHash": "0x7f55f0c040272ab7c688a1301ef3d74ce1aed6f3e2e01970f1974920be1ec768",
                "logIndex": 0,
                "removed": false,
                "id": "log_e1dabab2",
                "returnValues": {},
                "signature": null,
                "raw": {
                    "data": "...",
                    "topics": ["0x49639abe88f56d8c551d4c9f2fd689325918c1c32ff6d9d8082e503b66af694b"]
                }
```

**Comment by fotesco** [comment]
Exactly the same issue on my end. Events are fired, however only 2/3 are being captured.

**Comment by aj-may** [comment]
Also seeing this issue for events emitted by contracts deployed using `privateFor`.  Calling the same method with the same arguments each time.  Sometimes the event fires and sometimes it doesn't.

**Comment by jpmsam** [comment]
@skarred14 can you please confirm for the missing logs if the transaction receipts has the log populated but they are failing to be emitted? Also, how fast are you sending TXs?

**Comment by jpmsam** [comment]
@aj-may is it the same application as @skarred14 ?

**Comment by skarred14** [comment]
@jpmsam, we don’t see the logs in the tx receipt in case of event firing fails. the minimal config we used was to fire one transaction at a time and varied the delays from a second to a minute between subsequent transactions

**Comment by skarred14** [comment]
@jpmsam we have made some progress in researching this issue, and found that the missing events are extractable from other nodes in the network. We have 2 forms of the consensus set up for a test of 10 subsequent transactions:
1. 3 nodes all of them are set to validators: Events expected to be emitted for tx's private between nodes 1 and 2 show up with 7 of them on node 1 and 3 of them on node 2 (extracted events using `getPastEvents`).
2. 3 nodes in which node 1 is set to be the validator: All 10 are extracted from node 2 and node 1 has 0 events. However, after a certain point, `getPastEvents` returns an empty array.
Could it be possible to configure the consensus in genesis block, or at the quorum level to ensure consistent event capture? Or would it still vary and all nodes have to be listened to? How can we identify the nodes where we can see the events?

**Comment by jpmsam** [comment]
>3 nodes all of them are set to validators: Events expected to be emitted for tx's private between nodes 1 and 2 show up with 7 of them on node 1 and 3 of them on node 2 (extracted events using getPastEvents).

This would be a bug, we are looking into it. If it's a private transaction between node 1 and 2, then both nodes should have the same events.

**Comment by fotesco** [comment]
@jpmsam any updates on the event bug?

**Comment by jpmsam** [comment]
@fotesco We are seeing that the events are captured in the transaction receipts. After the transaction is committed in a block, you can execute `eth.getTransactionReceipt` on any of nodes that are partied to the transaction and you should see the logs populated. If you run the same call on any of the nodes that aren't partied to the transaction, then the logs will be empty. My assumption is that he listener is failing to capture the events.

**Comment by ghost** [comment]
Just something we are experiencing on our end. The logs are not even captured in the transaction receipt sometimes which results in no firing of events. This happens abruptly on any of the nodes randomly which are a part of the private transaction. In our setup, both of the nodes are validators.

**Comment by skarred14** [comment]
Thanks for the update @preetgsanand. We had encountered similar results for the receipt, where there was a random occurrence of the `logs` object not being null (`[]`). The team at our end is working to create simplified examples, so that the issue can be reproduced. Will keep the thread here posted based on the progress and related findings.

**Comment by libby** [comment]
Hello @skarred14,  @aj-may, et al., could you please try the same test runs with an increased block creation time for IBFT `--istanbul.blockperiod 5` and/or `--istanbul.blockperiod 10`  passed into geth at startup and report back the result? (I'm presuming that you are running with the default block time of 1 second, let me know if that isn't the case).

**Comment by grepfruit19** [comment]
Hi @libby , I'm working with @skarred14 and @aj-may on this bug. Upon adding the flags you suggested, I run into the following error: 

<img width="1865" alt="screen shot 2018-07-27 at 11 16 31 am" src="https://user-images.githubusercontent.com/10924177/43329546-aee2c21a-918e-11e8-8cee-65481237bebe.png">

Here is the geth startup script that we're using:

<img width="380" alt="screen shot 2018-07-27 at 11 16 42 am" src="https://user-images.githubusercontent.com/10924177/43329561-bb3593b2-918e-11e8-8776-1231165fd9e9.png">
