### ISSUE TITLE
GetQuorumPayload RPC call signature

### ISSUE THREAD

**Issue by rjbanner** [Consensys-Incorporated/quorum#403]
I am trying to use the GetQuorumPayload RPC call to get the payload details of a particular transaction.
I have provided quorum in the list of rpcapis
--rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft
What is the exact signature of the RPC call. Is it eth_getQuorumPayload?

**Comment by jpmsam** [comment]
@rjbanner The digest from the private transaction.  [eth_getQuorumPayload](GetQuorumPayload) is correct.
