### ISSUE TITLE
cannot deploy contracts to Quorum with standard default web3.py example code

### ISSUE THREAD

**Issue by drandreaskrueger** [Consensys-Incorporated/quorum#406]
*perhaps* this is related to Quorum, and not to a flaw in the Web3.py example code?

Have a look at 

* the description of the problem https://github.com/ethereum/web3.py/issues/898
* the simple code which throws the error https://gist.github.com/drandreaskrueger/f85314a856a6f17f828384559138a41b

Thanks a lot!

**Comment by drandreaskrueger** [comment]
The solution to this is important, probably for **anyone deploying contracts to Quorum with Python**.

Study the last comments in that issue over there - https://github.com/ethereum/web3.py/issues/898#issuecomment-397983124

at web3.py they say

> closing it as there is no web3 bug.

so ... it's quorum's responsibility to take care of this flaw, right?

**Comment by jpmsam** [comment]
In Istanbul and QuorumChain, we had to use an extraData field larger than the default 32bytes. In geth's Clique POA implementation, extraData is > 32bytes as well. I see that web3.py have implemented a work [around](http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority ) in  but we haven't tested it for Quorum.

**Comment by drandreaskrueger** [comment]
closed = solved?
