### ISSUE TITLE
Quorum nodes are not syncing ("Genesis block mismatch - d4e56740f876aef8 (!= 098383aff2d20d5f)"

### ISSUE THREAD

**Issue by Ajaysethi136** [Consensys-Incorporated/quorum#407]
#### System information

Geth
Version: 1.7.2-stable
Git Commit: fd0e3b9d13f9b9563e7d5b3b1aba51f035f9cf0d
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.9.1
Operating System: linux

#### Expected behaviour
I have created 4 nodes on different different VM's but one of the node(has 61 blocks while others has 100 blocks) was down for few hours and have less blocks now, when I brought that node up, so it's not able to sync with other nodes.

It's throwing the following error "Removing p2p peer      id=c6454da5d5d conn=inbound    duration=561.977µs peers=1 req=false err="Genesis block mismatch - d4e56740f876aef8 (!= 098383aff2d20d5f)"

I'm not using bootnode, I'm keeping all the enode id's of all nodes in static-nodes.json file to connect all quorum nodes and have placed in each node's directory.

Can anybody help on this.

````

**Comment by fixanoid** [comment]
Likely that you have not initialized the node with the same genesis block. Please reset and reinit geth with the same genesis block.

**Comment by Ajaysethi136** [comment]
I re-initialized geth with the same genesis block but still facing the same error. When you say 'reset the geth', If i do that, wouldn't the node data be deleted, so how can i reset the geth without losing data.

Please suggest.

**Comment by Ajaysethi136** [comment]
@fixanoid what do u exactly mean when you reset the geth, deleting the chaindata of the node?
