### ISSUE TITLE
Quorum Nodes Not Syncing, Getting Failed RLPx handshake error 

### ISSUE THREAD

**Issue by Ajaysethi136** [Consensys-Incorporated/quorum#408]
Geth
Version: 1.7.2-stable
Git Commit: fd0e3b9d13f9b9563e7d5b3b1aba51f035f9cf0d
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.9.1
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
*************************************************************************

I have created 4 nodes on different different machines, due to some issue, one of the node was down for few hours but when i restarted the geth, it's not syncing with other nodes, it's still having less blocks.

**Comment by fixanoid** [comment]
@Ajaysethi136 this is likely due to mis-configuration in ports. Please ensure that rpc port and raft port are correct in static nodes files or when you add it via raft.addPeer.

**Comment by Ajaysethi136** [comment]
@fixanoid  I have cross -checked the raft and rpc ports, there is no issue with that, when i do admin.peers, I'm able to see all the nodes but all nodes are not in sync, one node has 61 blocks while other has 109 blocks. 

I tried changing the raftports but no luck. Nodes are connected to each other but the new node is not able to sync with other nodes.
