### ISSUE TITLE
Can't add anode dynamically to Quorum Blockchain running with Istanbul BFT

### ISSUE THREAD

**Issue by cvkonduru** [Consensys-Incorporated/quorum#412]
I have a node running Quorum Blockchain with IBFT as it's consensus. Now I am trying to add another node to it. But I am unable to add the node and the two nodes are running two different blockchains. I am suspecting there is an issue in the **genesis.json's ExtraData Field** . I would like an advice on this or any possible solutions if somebody has already faced this issue and resolved it.

Kindly let me know if any other inputs for this issue are needed.

Cheers,
Chaitanya

**Comment by fixanoid** [comment]
Hi @cvkonduru could you explain how your new node is attempting to join the existing IBFT running blockchain?

**Comment by MrHmP** [comment]
Process of adding a new node in Istanbul is different than raft, you'll need validators and voting to add a new node.

Maybe if you can share your process of adding new node, then it would be helpful.

**Comment by cvkonduru** [comment]
Hello @fixanoid @MrHmP 

Thanks for your kind response. I am approaching the situation with two step process that is mentioned below.

Step 1

I first installed Quorum and Constellation, then generated the keys required for Constellation. Then I generated a nodekey and created enode and saved it in a file named permissioned-nodes.json. Created a validator address and created a genesis.json file manually with the extradata field value as the encoded value of the validator address. After all this procedure I am initiating the geth with the genesis file and starting the blockchain in permissioned mode.

Until this step, blockchain is running successfully and I am able to mine the blocks.
************************************************************************
step 2
************************************************************************
Now I am following the same process to configure one more node and added the enode info of firstnode in the second node's Permissioned-json file and vice versa. Next I am copying the genesis file from node 1 to node2 and changed the extradata field equal to the encoded value of the second node's validator address. Then I started running the blockchain. 

*************************************************************************************

This is the process I followed and the two nodes are not syncing with each other.

If you guys don't understand my description above kindly ask me questions, I am ready to give clear info about the process that I am following. 
Thanks in advance.

**Comment by fixanoid** [comment]
@cvkonduru initial nodes must run --syncmode "full" to sync. Theres some public work on this topic from Alastria, have you examined this repo? https://github.com/alastria/alastria-node

**Comment by cvkonduru** [comment]
@fixanoid  I will look into it for sure. I will get back to you for any issues. 

Cheers,
Chaitanya

**Comment by fixanoid** [comment]
@cvkonduru please reopen as needed.

**Comment by yangmiok** [comment]
> Process of adding a new node in Istanbul is different than raft, you'll need validators and voting to add a new node.
> 
> Maybe if you can share your process of adding new node, then it would be helpful.

I want the node become a validator automatic, no election required？How to configure？
