### ISSUE TITLE
Interledger communication across quorum networks

### ISSUE THREAD

**Issue by aroommen** [Consensys-Incorporated/quorum#414]
Once we start seeing widespread adoption of Quorum and deployments in the form of multiple consortiums utilizing the tech, how can we facilitate transfer of assets across two seperate Quorum ledgers?
Hyperledger consortium is using Hyperledger Quilt which is built on underlying ILP (Inter Ledger Protocol ) technology that claims to enable transfer of assets acroos ledgers. I did not see anything similar in the Quorum product roadmap and am curious to know if there are any existing solutions that could enable this crucial feature

**Comment by tylobban** [comment]
Hey @aroommen, this is on our product roadmap as key item and we have a number of other plans in the interop space. ILP, however, should be implementable on Quorum.

**Comment by aroommen** [comment]
@tylobban Wonderful. Thanks! 
Do share pointers to any repository/team that have actually worked on ILP with Quorum (if they are available)
