### ISSUE TITLE
Is there any API for constellation key rotation in case of key leaked?

### ISSUE THREAD

**Issue by a651694192** [Consensys-Incorporated/quorum#418]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
Not at the moment, thos this feature is planned for this year.

At the moment, our recommendation is to create new node with new keys and re-create private contracts between the parties. After this, destroy legacy private contracts and clean up retired node.
