### ISSUE TITLE
Is sendRawTransaction support private transaction now?

### ISSUE THREAD

**Issue by a651694192** [Consensys-Incorporated/quorum#419]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
Not yet, but this is planned for this year.

**Comment by muthu-param** [comment]
Is sendRawTransaction support private transaction now?
