### ISSUE TITLE
ZSL Error : The network is terminating forcefully 

### ISSUE THREAD

**Issue by saipraveen23** [Consensys-Incorporated/quorum#420]
#### System information

Geth version: `geth 1.6`

OS & Version: Ubuntu 16.04

Branch, Commit Hash or Release: `branch :zsl_geth1.6`

Link : https://github.com/jpmorganchase/quorum-examples

In the above link , in Example 2, while executing the command : 
zdemo.submit_payment(tracker, ztoken_usd, zprivatecontract, uuid),
The network is closing forcefully whenever this command is executing. 

Error: 
 
> zdemo.submit_payment(tracker, ztoken_usd, zprivatecontract, uuid)
***************************************************************
[*] Generating proof for shielded transfer
Error: EOF
    at web3.js:3104:20
    at web3.js:6191:15
    at web3.js:5004:36
    at _zdemo_submit_funds_to_contract (ztracker.js:151:18)
    at _zdemo_submit_payment (ztracker.js:224:12)
    at ztracker.js:316:20
    at <anonymous>:1:1

> Error: Error: write unix @->/home/ubuntu/projects/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc:                                                                  use of closed network connection
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
> Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
> Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
> Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
> Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused
Error: Error: dial unix qdata/dd1/geth.ipc: connect: connection refused

**Comment by saipraveen23** [comment]
@jpmsam can you help me in getting the issue to be resolved ?

**Comment by saipraveen23** [comment]
@jpmsam any response on the above issue ? or can you redirect it to the concerned person ?

**Comment by benediamond** [comment]
hi @saipraveen23, I encountered this error as well. The issue is is low memory allocated to the Vagrant VirtualBox (see e.g. https://github.com/Zerocash/libzerocash/issues/1).

The easiest way to fix this should be to `git checkout zsl_geth1.6` in the `quorum-examples` directory on your host box before launching Vagrant. you can run `vagrant reload` to restart your virtual box.

Notice that the memory limit has been changed here:
https://github.com/jpmorganchase/quorum-examples/blob/5c4f3d50a4417c5e06fc678d87a09b06d7cc152c/Vagrantfile#L11-L13
Cheers!

**Comment by saipraveen23** [comment]
Hi @benediamond , 

I am not using vagrant. so i there any other solution to solve this problem ?

**Comment by benediamond** [comment]
Maybe you are simply running out of memory. The only alternative would be to run `nano qdata/logs/1.log` and try to see if you can identify the error more precisely.

**Comment by benediamond** [comment]
Hi @saipraveen23 any luck on this? If not, please check `qdata/logs/1.log` and report if you can see any errors.
