### ISSUE TITLE
Zsl : fetching uuid 

### ISSUE THREAD

**Issue by saipraveen23** [Consensys-Incorporated/quorum#422]
### system Information : 

Geth version: geth 1.6

OS & Version: Ubuntu 16.04

Branch, Commit Hash or Release: branch :zsl_geth1.6

Link : https://github.com/jpmorganchase/quorum-examples

In the above link , in Example 2, while executing the command :
Node : Alice 
tracker.list(ztoken_usd)
Output : 
 tracker.list(ztoken_usd)
***************************************************************
Found 1 USD notes >= 0
[
    {
        "rho": "0x8e3b1ff5d8617722b3f28f5c93e1d38f170a9d565545997a5ade443ef9f7061a",
        "uuid": "0xe0855d998dbca7e939d66958979093e42e2436e13c5fad3bb96072c425413341",
        "value": 10000,
        "ztoken": "0x521087278e9eed99c3215fa8a87d44ab9d6eedd2"
    }
]

1. how to  fetch uuid which acts as a identifier , for the notes ? 
Is the above o/p is stored as JSON format ? yes , command to fetch uuid which can be used in the next steps.

Q2.  
since tracker.notes is also displaying the uuid as same : 

tracker.notes
{
  0xe0855d998dbca7e939d66958979093e42e2436e13c5fad3bb96072c425413341: {
    rho: "0x8e3b1ff5d8617722b3f28f5c93e1d38f170a9d565545997a5ade443ef9f7061a",
    uuid: "0xe0855d998dbca7e939d66958979093e42e2436e13c5fad3bb96072c425413341",
    value: 10000,
    ztoken: "0x521087278e9eed99c3215fa8a87d44ab9d6eedd2"
  }
}
can we use var uuid = tracker.notes['0xe0855d998dbca7e939d66958979093e42e2436e13c5fad3bb96072c425413341'].uuid

Q 3.. can we manually declare uuid value in a variable like 

var uuid = ""0xe0855d998dbca7e939d66958979093e42e2436e13c5fad3bb96072c425413341".

**Comment by jpmsam** [comment]
@bitcartel for his input on the ZSL integration.

**Comment by benediamond** [comment]
Hi @saipraveen23, yes, all of those things you suggested work. Sorry for the delay. Is there anything specific we can help you with? If not I will close this.

**Comment by fixanoid** [comment]
Closing. Please reopen if there is a question
