### ISSUE TITLE
Syncing issues when a new node joins the existing cluster in Quorum Using RAFT.

### ISSUE THREAD

**Issue by Ajaysethi136** [Consensys-Incorporated/quorum#424]
I'm running 4 nodes on separate VM's, I have reset one of the node from the cluster. Now that node is not able to sync with other nodes. 

New node has 0 blocks while other nodes has 323 blocks, they all are in sync except the new reset node.

when I do admin.peers, I'm able to see the new node in list but blocks are 0.

Could anyone please suggest do we need to give some extra parameters to get all from blocks from the existing cluster?

**Comment by Ajaysethi136** [comment]
@fixanoid can you please suggest

**Comment by fixanoid** [comment]
@Ajaysethi136 any new node joining Raft mode quorum cluster must use --raftjoinexisting flag. Please read here: https://github.com/jpmorganchase/quorum/blob/master/docs/raft.md#initial-configuration-and-enacting-membership-changes

**Comment by Ajaysethi136** [comment]
@fixanoid but using --raftjoinexisting flag, that is dynamic way of adding a new node to the cluster.

But what I'm doing is adding the enode of new node into each node's static-nodes.json file, static way of adding a new node, it's able to join but syncing not happening,wouldn't it work?

**Comment by saikatsain** [comment]
@fixanoid The link provided does not work. 

I am facing the same problem. Please elaborate as I have used the --raftjoinexisting parameter as well as the --syncmode parameter set to full but the blocknumber on the new node remains zero.

**Comment by fixanoid** [comment]
@saikatsain link has been updated.

**Comment by jimbarritt** [comment]
I think the raft.md moved to here: https://github.com/jpmorganchase/quorum/blob/master/docs/Consensus/raft.md#initial-configuration-and-enacting-membership-changes
