### ISSUE TITLE
Block time

### ISSUE THREAD

**Issue by dmytronasyrov** [Consensys-Incorporated/quorum#425]
Is it possible for the Raft consensus to increase block closing time? They are closing too fast for us.

PS: I know, this sounds weird.

**Comment by fixanoid** [comment]
Hi @dmytronasyrov, just for completeness, the flag is explained here: https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md and its --raftblocktime

**Comment by dmytronasyrov** [comment]
we have fixed the issue. It was related to web3j. Not to Quorum raftblocktime
