### ISSUE TITLE
 Permission denied

### ISSUE THREAD

**Issue by kengan** [Consensys-Incorporated/quorum#427]
I run the   quorum-examples on window 10 with  vagrant up ,everything is OK,but  when I run  vagrant ssh I get  vagrant@127.0.0.1: Permission denied (publickey).  Can you tell me how can I solve this problem? Thank you!

**Comment by fixanoid** [comment]
hi @kengan this is a windows issue. Please try using vagrant from Git Bash or cygwin. If neither works, google for the best solution.
