### ISSUE TITLE
a new node joining  the existing quorum cluster using RAFT error

### ISSUE THREAD

**Issue by alexsplashex** [Consensys-Incorporated/quorum#429]
#### System information

Geth version: `geth version`
 1.7.2-stable-52f137c8
OS & Version: Windows/Linux/OSX
13~16.04.2-Ubuntu SMP Wed May 30 01:39:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Hello. I have 3-node quorum claster. I have to add additional nodes to it. 
I have added raft.addPeer(enodeId) into my cluster
![screen shot 2018-07-03 at 3 29 49 pm](https://user-images.githubusercontent.com/39257074/42219878-fabe16d8-7ed5-11e8-9357-86e50eac98c2.png)

and started new geth node with the flag --raftjoinexisting 
![screen shot 2018-07-03 at 3 31 45 pm](https://user-images.githubusercontent.com/39257074/42219968-463c78ac-7ed6-11e8-83a6-c47f57a60076.png)

But I have the errors:

`root@QuorumVM:~/kim1# tail ./qdata/logs/kim1.log
TRACE[07-03|12:33:14] Accepted connection                      addr=51.144.101.16:33026
TRACE[07-03|12:33:14] Quorum permissioning                     EnableNodePermission=false DataDir=/home/lesha/kim1/qdata Current Node ID=78a8dc60c9b4abd41851c0aa023445d8d910628fd0ea081f476e3e9d7e7e2c447f083ecb4ef8cb9f3f20b6eda7e133f5ec485c94c4cf977406f7f2aedc103d47 Node Name=Geth/v1.7.2-stable-52f137c8/linux-amd64/go1.10.2 Dialed Dest=nil                                                                                                                                                                                     Connection ID=5b1e916006d428a5 Connection String=5b1e916006d428a514eb7b6e4e647dbba0eb735c06e4f9835b7937416f2e651635c15c526fbb2016a7a3782d993bef0a003637f6fef3d9186173678c5de8cf3d
TRACE[07-03|12:33:14] Node Permissioning is Disabled.
DEBUG[07-03|12:33:14] Adding p2p peer                          id=5b1e916006d428a5 name=Geth/v1.7.2-stable-5...                          addr=51.144.101.16:33026  peers=3
TRACE[07-03|12:33:14] Starting protocol eth/63                 id=5b1e916006d428a5 conn=inbound
DEBUG[07-03|12:33:14] Ethereum peer connected                  id=5b1e916006d428a5 conn=inbound    name=Geth/v1.7.2-stable-52f137c8/linux-amd64/go1.10.2
DEBUG[07-03|12:33:14] Ethereum handshake failed                id=5b1e916006d428a5 conn=inbound    err="Genesis block mismatch - f4b742f3d8ecce27 (!= 042ceeeb98d0d5ca)"
TRACE[07-03|12:33:14] Protocol eth/63 failed                   id=5b1e916006d428a5 conn=inbound    err="Genesis block mismatch - f4b742f3d8ecce27 (!= 042ceeeb98d0d5ca)"
DEBUG[07-03|12:33:14] Removing p2p peer                        id=5b1e916006d428a5 conn=inbound    duration=358.502µs peers=2 req=false err="Genesis block mismatch - f4b742f3d8ecce27 (!= 042ceeeb98d0d5ca)"
DEBUG[07-03|12:33:18] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s`

![screen shot 2018-07-03 at 3 39 33 pm](https://user-images.githubusercontent.com/39257074/42220362-61d1fe6a-7ed7-11e8-9e5f-16f8f868d276.png)

on the cluster node and 

`root@NewVM:~/newkim1# tail ./qdata/logs/newkim1.log
INFO [07-03|12:35:50] failed to synchronize with peer          peer id=78a8dc60c9b4abd41851c0aa023445d8d910628fd0ea081f476e3e9d7e7e2c447f083ecb4ef8cb9f3f20b6eda7e133f5ec485c94c4cf977406f7f2aedc103d47
INFO [07-03|12:35:50] synchronizing with peer                  peer id=1                                                                                                                                hash=726c42…015968
WARN [07-03|12:35:50] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-03|12:35:50] failed to synchronize with peer          peer id=78a8dc60c9b4abd41851c0aa023445d8d910628fd0ea081f476e3e9d7e7e2c447f083ecb4ef8cb9f3f20b6eda7e133f5ec485c94c4cf977406f7f2aedc103d47
INFO [07-03|12:35:51] synchronizing with peer                  peer id=2                                                                                                                                hash=726c42…015968
WARN [07-03|12:35:51] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-03|12:35:51] failed to synchronize with peer          peer id=bc4a36b9409ef5533d5dfb9e9c45d4419e0a9ae09f776235fcc43cd4b742e603481e00a307427ff0aafc3c20f7e5b2de7d742a6475c06fbf3d74ac8708d4e544
INFO [07-03|12:35:51] synchronizing with peer                  peer id=3                                                                                                                                hash=726c42…015968
WARN [07-03|12:35:51] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-03|12:35:51] failed to synchronize with peer          peer id=8e98c45435ced74dcf454814c6347624fe28bbb01ecbfa3159dee6f7fd4186b3466c16d0d10f9f01885cb69b126aff52a189329e063df4cc702168a17aa8e4b1`
![screen shot 2018-07-03 at 3 39 47 pm](https://user-images.githubusercontent.com/39257074/42220375-6cf915a8-7ed7-11e8-9c80-7df94393df08.png)

on new geth node

Help me please

**Comment by fixanoid** [comment]
Seems like you have a mismatch in the genesis, ensure they are using the same.

**Comment by alexsplashex** [comment]
@fixanoid thanks for your answer. I have fixed mismatch in the genesis error. Now its better, 
I can watch new node from cluster:
![screen shot 2018-07-04 at 3 57 18 pm](https://user-images.githubusercontent.com/39257074/42278295-fe5a6274-7fa2-11e8-871a-5c8de4de9cb2.png)

and vise versa

![screen shot 2018-07-04 at 3 59 03 pm](https://user-images.githubusercontent.com/39257074/42278361-39a90f9c-7fa3-11e8-887f-7f59d053c27a.png)

but I steel have some errors:

on cluster node
`TRACE[07-04|12:47:21] New dial task                            task="wait for dial hist expire (28.023195343s)"
DEBUG[07-04|12:47:27] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[07-04|12:47:47] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[07-04|12:47:49] Dial task done                           task="wait for dial hist expire (28.023195343s)"
TRACE[07-04|12:47:49] New dial task                            task="staticdial 5b1e916006d428a5 10.0.1.8:21000"
TRACE[07-04|12:47:49] Failed RLPx handshake                    addr=10.0.1.8:21000       conn=staticdial err=EOF
TRACE[07-04|12:47:49] Dial task done                           task="staticdial 5b1e916006d428a5 10.0.1.8:21000"`

![screen shot 2018-07-04 at 4 01 33 pm](https://user-images.githubusercontent.com/39257074/42278482-a1f0a79a-7fa3-11e8-8bf1-c72a6b0a4adf.png)
 
on new node
`DEBUG[07-04|12:47:02] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[07-04|12:47:03] Accepted connection                      addr=10.0.1.6:55088
TRACE[07-04|12:47:03] Failed RLPx handshake                    addr=10.0.1.6:55088        conn=inbound    err="ecies: invalid message"
TRACE[07-04|12:47:19] Accepted connection                      addr=10.0.1.5:51578
TRACE[07-04|12:47:19] Failed RLPx handshake                    addr=10.0.1.5:51578        conn=inbound    err="ecies: invalid message"
DEBUG[07-04|12:47:22] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[07-04|12:47:24] Accepted connection                      addr=10.0.1.7:42940
TRACE[07-04|12:47:24] Failed RLPx handshake                    addr=10.0.1.7:42940        conn=inbound    err="ecies: invalid message"`

![screen shot 2018-07-04 at 4 03 51 pm](https://user-images.githubusercontent.com/39257074/42278550-e360ba8a-7fa3-11e8-9c94-66ba420b11c7.png)

Thanks in advance for your reply
