### ISSUE TITLE
Too many external connections to geth-node

### ISSUE THREAD

**Issue by mmshihov** [Consensys-Incorporated/quorum#435]
We launch Quorum cluster (Istanbul BFT consensus used) on our public server. After some amount of time, we found that our nodes communicate with unknown (i.e not ours) external nodes.

We use standart 7nodes example. (But, if necessary, we can generate our own cluster (new genesis.json, unique nodekeys, etc.) and launch nodes on separated public server)

So there is a general question - how quorum blockchains see each other and distinguish each other? 

And subquestion: Is it possible to restrict (amount of) communications with external nodes on the Internet? By any means - administrative or quorum-built-in ones (what should we define in genesis.json to make our blockchain to not communicate with alien nodes?).

**Comment by fixanoid** [comment]
Hi @mmshihov please take a look at this doc: https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

Specifically, you should test with --nodiscover, but --netrestrict option could also be useful to you.
