### ISSUE TITLE
Unable to send private transaction.  Unknown recipient error

### ISSUE THREAD

**Issue by prashantprabhakar** [Consensys-Incorporated/quorum#439]
#### System information

Geth version: `1.7.2-stable`

OS & Version: Linux

#### Expected behavior
I should be able to send transaction
#### Actual behaviour
Getting ** unknown recipient error**

#### Steps to reproduce the behaviour
Setting up 5RTGS node example.
Trying to send private tx from node1 to node2.
```
contract1.sendValue(1234567,7654321,2222222,3333333,9898989,8888888,"Cash",4000,"05122017",1010101,{from:eth.coinbase,gas:500000,privateFor:["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=", "R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY="]});
```
where QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc= is public key corresponding to node2  (checked using `less tm2.pub`)
and 
R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY= is public key corresponding to node 4 -rgulator (checked using `less tm4.conf`)

#### Backtrace

````
2018 Jul-11 06:08:56953263 [WARN] Error performing API request: ApiSend (Send {sreqPayload = "7\GSc\SO\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC2\214\135\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NULt\203\177\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL!\232\142\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL2\220\213\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\151\v\237\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\135\162\&8\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH@\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SI\160\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\128\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SIi\181\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\EOTCash\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\b05122017\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL", sreqFrom = "BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo=", sreqTo = ["QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="]}); sendRequest: Errors while running sendPayload: [Left "Unknown recipient\nCallStack (from HasCallStack):\n  error, called at ./Constellation/Node.hs:164:21 in constellation-0.1.0.0-bO6yomQcNv4mJID9Sq40H:Constellation.Node"]
````
EDIT:

The peers are connected. I can see logs of constellation4 : 

> 2018 Jul-11 06:21:58273689 [INFO] Finished synchronization with http://127.0.0.1:9001/
> 2018 Jul-11 06:21:58273736 [INFO] Starting synchronization with http://127.0.0.1:9002/
> 2018 Jul-11 06:21:58274205 [INFO] Finished synchronization with http://127.0.0.1:9002/
> 2018 Jul-11 06:21:58274247 [INFO] Starting synchronization with http://127.0.0.1:9004/
> 2018 Jul-11 06:21:58274648 [INFO] Finished synchronization with http://127.0.0.1:9004/

**Comment by john-osullivan** [comment]
Any idea what the root issue is here?  Running into something similar.

EDIT for future debuggers: My underlying issue here was that my `othernode` value in the Constellation file was misconfigured.  My tip-off that something was wrong (and not the issue from this thread) was that my logs had `Starting synchronization with...`, but not `Finished synchronization with...`.

**Comment by fixanoid** [comment]
@prashantprabhakar you need to follow the example. You are putting too many values into the method and I think this is why its failing. Follow this: https://github.com/bacen/quorum-examples/blob/master/examples/5nodesRTGS/README.md#testing-transactions-confirmed-by-the-regulator

@john-osullivan please open a separate issue with description of the issue.
