### ISSUE TITLE
BlockVoting contract getCanonHash function exception

### ISSUE THREAD

**Issue by magooster** [Consensys-Incorporated/quorum#44]
The getCanonHash function does not guard against all input (height) scenarios . For example, when a blockmaker attempts to create its first block, it will call the function with a height of 1, this will throw an exception as no voting periods will have been completed. 

The function should check that enough voting periods have been recorded for the height being requested. 

There is also an edge-case for the input (height) zero.

**Comment by tylobban** [comment]
Hi @magooster, do you mind providing the key issue-investigation pieces per the [issue template](https://github.com/jpmorganchase/quorum/blob/master/.github/ISSUE_TEMPLATE.md) ? Particularly steps to reproduce.  Thanks for continuing to look at Quorum!

**Comment by magooster** [comment]
System information

Geth version: geth version

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: git status 

On branch master

Expected behaviour

Would expect empty hash

Actual behaviour

exceptiom

Steps to reproduce the behaviour

The issue can be reproduce by loading the voting contract into a tool like browser-solidity. Then just call the getCanonHash function using that tool.

Backtrace

VM Exception: invalid JUMP at bc23a9dc67e69866001adeb3f9cc6b459959be743174cd8987f85623b808cb0c/ef55bfac4228981e850936aaf042951f7b146e41:1635

**Comment by bas-vk** [comment]
This function was not designed to be fool proof and is used internally where the caller code takes care of errors. The contract is designed to emit interesting data through events and users should normally not call the contract direct.

Could you describe why you would want to use this function?

**Comment by magooster** [comment]
I don't want to use the function externally but was expecting the contract logic  to guard against such cases.

In the quorum, a block maker won't create a block if this function returns an error, so if voting worked in accordance to the description on the wiki, i.e. in response to new blocks (ChainHeadEvent in code), the chain would never progress. From my observations, The chain only progresses because nodes with voting rights are voting at a random interval  defined by the block times. (CreateBlock event)

For the case where a block maker is building on the genesis block shouldn't the function return its hash?

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/266
