### ISSUE TITLE
Unable to start node. udp :21001: bind: address already in use

### ISSUE THREAD

**Issue by prashantprabhakar** [Consensys-Incorporated/quorum#440]
#### System information

Geth version: `1.7.2-stable`

OS & Version: Linux

#### Expected behaviour
The nodes should start with a `geth.ipc` file in `qdata/dd1`.

#### Actual behaviour
No geth.ipc file is created. 

#### Steps to reproduce the behaviour

- bash bootstrap.sh

- bash raft-init.sh

- bash raft-start.sh

#### Backtrace

````
Fatal: Error starting protocol stack: listen udp :21001: bind: address already in use
````
#### Reproducitibility
Sometimes

#### Extra Info
By checking losg seems that port is already in use. But I can not check any process running on port 21001-21004. I checked using `lsof -i :21001`

**Comment by kjroger94** [comment]
This is not a bug, your last geth process did not close properly. 

Run:
`netstat -nlp | grep 21001`

you will get an output like this:
`tcp6       0      0 :::22001                :::*                    LISTEN      913/geth`

then just run:

`kill -9 913`

replace 913 with the pid you get for your process. 

You might just get it by running "ps" and seeing a geth process running. You can also try `killall -9 geth` given your are running this as a geth processes.

**Comment by prashantprabhakar** [comment]
Accidently clicked reopen. Yes, I could identify the issue The geth process was not stopped properly.
