### ISSUE TITLE
How to generate keys of a block maker/voter?

### ISSUE THREAD

**Issue by cosimoth** [Consensys-Incorporated/quorum#441]
Hi there. Quorum is quite fantastic. I've successfully set up a 7-nodes network following the Quick-start.  I'm now a little confused about the keys involved, and have several questions:
1. Does a key (i.e., key1-8 in `keys` folder) refer to an Ethereum account? 
2. According to [ReadMe](https://github.com/jpmorganchase/quorum/blob/master/docs/running.md), Quorum nodes with key1,2,3 are voters, and those with key 4,5 are block makers. How to generate more voter keys or maker keys?
3. Why does node 3 need key3 and key6 at the same time?

I appreciate any answers or documents provided. Thanks a lot :)

**Comment by jpmsam** [comment]
Hi @pynchon-sjtu please use raft or Istanbul as QuorumMaker has been deprecated in 2.0. We will be updating the ReadMe in the next few days.
