### ISSUE TITLE
[Question] Constellation communication with different incoming and outgoing IPs.

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/quorum#442]
We have set up a quorum cluster on AWS with Quorum nodes kept in a private subnets and to enable communication between them we are using NAT gateway and network load balancer, but this is resulting into separate public IPs for incoming and outgoing traffic. Geth processes are able to communicate with each other since they identify each other with enode addresses, but constellation communication is not getting established because the broadcast IPs does not matches with the ip provided in “—othernodes” list. 

So, please suggest a work around for this, so that we can enable constellation communication when IPs are different for incoming and outgoing traffic.

**Comment by fixanoid** [comment]
Closing this for now. Answered on slack. Another set of solutions will be posted on Constellation in the future.
