### ISSUE TITLE
How to solve single point of failure

### ISSUE THREAD

**Issue by jengy** [Consensys-Incorporated/quorum#444]
#### System information

Geth version: `1.7.2` / quorum 2.0

OS & Version: Ubuntu 16.04

Branch, Commit Hash or Release: `git status`

#### Expected behaviour

Attempt to deploy two constellation node using same key (--publickeys, --privatekeys) for a party and then send a private transaction to it from another party.  Expected the two nodes have the same storage stat.

#### Actual behaviour
Only one node of the party behaved as expected, and the other node don't change the storage stat. Check the constellation log of the node, error exist as below:

09:41:28 [WARN] Error performing API request: ApiReceiveRaw (Receive {rreqKey = "MGVz33pWBZkZZJhRQWHSz+Y+9qa/kDcb
/PNJ+llWV8AOGApkZWEgo+RXHW5drB9bJskz/N21jD8YOdiCFPiz6g==", rreqTo = Nothing}); Payload not found in directory sto
rage: storage/payloads/GBSXHX32KYCZSGLETBIUCYOSZ7TD55VGX6IDOG746NE7UWKWK7AA4GAKMRSWCIFD4RLR23S5VQPVWJWJGP6N3NMMH4
MDTWECCT4LH2Q=: openBinaryFile: does not exist (No such file or directory)

#### Steps to reproduce the behaviour
Using the sample quorum chain 7nodes.
1) cp  7nodes/keys/tm7.pub 7nodes/keys/tm6.pub
2) cp 7nodes/keys/tm7.key 7nodes/keys/tm6.key
* simulate a party has 2 nodes: node 6, node 7
3) raft-init.sh
4) raft-start.sh
5) runscript.sh script1.js

#### Backtrace

````
[backtrace]
````

**Comment by jengy** [comment]
Well，maybe I should use two node with different key for each party to face the single point of failure.

**Comment by fixanoid** [comment]
Hey @jengy, constellation nodes are not meant to be shared between 2 or more quorum nodes. In the perfect world we do 1-1, each with its own key set. The current implementation stops sending txns once it finds the other node, so this is the reason that only one node receives the payload.

Whats the use case here? Is this for DR or some other replication / recovery?

**Comment by jengy** [comment]
Hey @fixanoid , it's clear for me about the exception.
The use case is to avoid the single point fail of a quorum node. I think a Quorum Node's Private StateDB is unique in  quorum net, so it is the case for DR as you think. 
Would u give me some advice on it ? thanks.

**Comment by fixanoid** [comment]
@jengy there are various DR strategies, easiest is to ensure that multiple nodes are mirroring each other and are party to the same private contracts and transactions.

In terms of recovery, ensure correct backup of quorum client and its data directory and constellation client and its data directory, and of course, all the keys. If such a node goes down, recovery is possible from whatever block the backup was taken on.

Additionally, we are releasing a new client that will include output of private payloads into a non-file database of your choosing. Expect it in the next several weeks.

**Comment by jengy** [comment]
Thanks for your reply and hope for the new release.
