### ISSUE TITLE
On Quorum 2.0.2, send ether from a funded node by genesis, to a non-funded, failed!

### ISSUE THREAD

**Issue by horca17** [Consensys-Incorporated/quorum#445]
Geth
Version: 1.7.2-stable
Git Commit: 87d7c906e9eba93b618651ab5a427746506e2f30
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.10
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.10/libexec

Expected behaviour
Trying to send som ether from node2 to node5:
eth.sendTransaction({from:eth.coinbase, to: "0x328f660b0233d2322837cedbaeb4523cdddcc400", value: web3.toWei(1000,'ether'), gas: 150000})
"0xd3838c18360ae42d0d61b7e4ab4a95de60df9042fe79b50277af1c384dbe80d0"

Actual behaviour
Nothing happens:

eth.getTransactionReceipt("0xd3838c18360ae42d0d61b7e4ab4a95de60df9042fe79b50277af1c384dbe80d0")
{
  blockHash: "0x6e3e798cb37a678857cd092f04b6d3493bb56b8fbaea33804bbe5993dac40f2c",
  blockNumber: 35,
  contractAddress: null,
  cumulativeGasUsed: 0,
  from: "0x46f50ca5623c968da2926a6b9ddfaa123fb4faf9",
  gasUsed: 0,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  status: "0x1",
  to: "0x328f660b0233d2322837cedbaeb4523cdddcc400",
  transactionHash: "0xd3838c18360ae42d0d61b7e4ab4a95de60df9042fe79b50277af1c384dbe80d0",
  transactionIndex: 0
}

and 

eth.getBalance(eth.coinbase, function (err, cb){console.log(cb)})
1e+27

Steps to reproduce the behavior
Just try moving ether from one node to another.

Moving back to Quorum 2.0.1 will make the tick, but not able to repeat the same method on 2.0.2

Any help?

**Comment by horca17** [comment]
Solved, Use eip155 signer for public transactions (#375).

**Comment by fixanoid** [comment]
Hi @horca17. Value transfer between accounts should work as expected on ethereum, with limitations during private use: no value transfer is allowed in private mode.
