### ISSUE TITLE
PrivateFor unable to work with structs of structs (nested structs) / arrays within structs in solidity

### ISSUE THREAD

**Issue by nathanawmk** [Consensys-Incorporated/quorum#453]
#### System information

Geth version: `geth version`
1.7.2

OS & Version: Windows/Linux/OSX
RHEL

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
The use of PrivateFor  with structs of structs (nested structs) / arrays within structs in solidity

#### Actual behaviour
PrivateFor unable to work with structs of structs (nested structs) / arrays within structs in solidity

#### Steps to reproduce the behaviour
https://ethereum.stackexchange.com/questions/54999/quorum-privatefor-unable-to-work-with-structs-of-structs-nested-structs-arra

#### Backtrace
https://ethereum.stackexchange.com/questions/54999/quorum-privatefor-unable-to-work-with-structs-of-structs-nested-structs-arra

````
[backtrace]
````

**Comment by fixanoid** [comment]
@nathanawmk could you please provide sample contract that showcases the issue? Thanks.

**Comment by fixanoid** [comment]
Please reopen with samples.
