### ISSUE TITLE
How to setup a private chain step by step?

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#456]
Recently, I research Quorum.I want to know whether have some document about how to  setup a private chain from source code step by step. Thank you!

**Comment by SatpalSandhu61** [comment]
Hi, please note that Github issues should only be raised for *actual issues with Quorum*.
If you have questions then you can raise them on the Quorum channel on slack (https://slack.com/).

I suggest you follow the 7-nodes examples: https://github.com/jpmorganchase/quorum-examples

**Comment by matrixoneken** [comment]
Thank you for your answer. I had run 7-nodes examples without any problem.Now I want to setup a private chain network which may be 3 nodes or 2 nods and so on. In 7-nodes examples I see many key files and pub files. These files save the address and public key of nodes.I want to know how to make  key files and pub files and how to get the address and public key about  nodes  with only the source code ? Thank you !

**Comment by matrixoneken** [comment]
For detail, I run 7-nodes examples and find  for node1 initialization，  it must have files in directory key  such as  key1 , tm1.key ,tm1.pub ,tm1a.key,tm1a.pub and also need the file  nodekey1 in directory raft. Besides it also need the enode hash in  permissioned-nodes.json. 
I want to know how I can get the content  in all above files.

**Comment by fixanoid** [comment]
Hi @matrixoneken there are various keys in there, but essentially, they either come in from constellation (privacy) or they are generated by geth during init phase (nodekeys, accounts).

For constellation keys, please look into `--genkeys` part of constellation-node executable, for everything else, please look into cli options for geth.
