### ISSUE TITLE
Quorum to support hardware security modules (HSM) 

### ISSUE THREAD

**Issue by nathanawmk** [Consensys-Incorporated/quorum#459]
#### System information

Geth version: `geth version`
v1.7.2

OS & Version: Windows/Linux/OSX
RHEL 

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
Requirement to generate and store private keys on hardware security modules (HSM) 

#### Backtrace

````
[backtrace]
````

**Comment by type4ranjan** [comment]
Is there any update on this or any timeline when this feature will be implemented?

**Comment by antonydenyer** [comment]
This has been implemented through [quorum key manager](https://docs.quorum-key-manager.consensys.net/en/latest/) currently we support:

- HashiCorp Vault
- Azure Key Vault
- AWS Key Management Service
