### ISSUE TITLE
How to add a new  node

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#464]
I have a quorum network run by raft_init and raft_start in 7 nodes examples .Now I want to add a new node to this network. I know the permission about connection of two nodes is set in a json file like the static-nodes.json in 7nodes example.
I want to know whether quorum has a web api to add the new node address to the  existing network and whether the existing network need to be restarted after adding the new node address?Thank you!

**Comment by fixanoid** [comment]
@matrixoneken after initialization of a Quorum cluster, to add new node, you should distribute the genesis file to the new node and provide static-nodes.json with the list of the nodes in the cluster at the moment.

After node init, you will be asked to join existing cluster via --raftjoinexisting, please read the instructions for this here: https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md#initial-configuration-and-enacting-membership-changes. The only node that will need to be started is the new node, no restart is required on any other cluster node.

Web API for raft.addPeer exists, but as mentioned above, you also need 2 other files that are not accessible through any APIs.

**Comment by matrixoneken** [comment]
Thank you for your answere
**I use the --raftjoinexisting to open a new node. the sh file is as following:**

!/bin/bash
set -u
set -e

nodeindex=1
raftport=50401
rpcport=22000
port=21000



mkdir -p qdata/logs
echo "[*] Starting Constellation nodes"
./constellation-start.sh $nodeindex

echo "[*] Starting Ethereum nodes"
set -v
ARGS="--nodiscover --raft --raftjoinexisting --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints"
PRIVATE_CONFIG=qdata/c1/tm.ipc nohup geth --datadir qdata/dd$nodeindex $ARGS  --raftport $raftport --rpcport $rpcport --port $port --unlock 0 --password passwords.txt 2>>qdata/logs/$nodeindex.log &

set +v

echo "All nodes configured. See 'qdata/logs' for logs, and run e.g. 'geth attach qdata/dd$nodeindex/geth.ipc' to attach to the first Geth node."

**I get the error from log as following:**
invalid value "--rpc" for flag -raftjoinexisting: strconv.ParseInt: parsing "--rpc": invalid syntax

Can you tell how to solve thie problem? Thank you!

**Comment by fixanoid** [comment]
Hey @matrixoneken you need raft_id after raftjoin existing. Please read the doc in detail and follow it.
