### ISSUE TITLE
new release please

### ISSUE THREAD

**Issue by drandreaskrueger** [Consensys-Incorporated/quorum#466]
The last release (2.0.2, Mar 19) is almost half a year old.

https://github.com/jpmorganchase/quorum/releases

and there have been quite a few commits since then

https://github.com/jpmorganchase/quorum/commits/master

thanks

**Comment by jpmsam** [comment]
@drandreaskrueger we are working on it for the next 2 weeks with a new version of constellation, documentation update and interdependent Quorum fixes.

**Comment by drandreaskrueger** [comment]
thanks a lot

**Comment by drandreaskrueger** [comment]
for now, just use the HEAD of the repo master, or would you advise against that, @jpmsam ?

**Comment by jpmsam** [comment]
@drandreaskrueger HEAD should be table for development, please report any issues you might see.

**Comment by drandreaskrueger** [comment]
I want to try **a new benchmarking of IBFT** - but this time with larger gas limit, as I seem to have simply hit the max gas in my last IBFT experiments --> https://gitlab.com/electronDLT/chainhammer/blob/master/chainreader/blocksDB_analyze_quorum-istanbul.ipynb (scroll all the way down in that notebook, or see below)

*And some of the recent quorum commits are about Istanbul, right?  
So better compile from the newest HEAD?*

---

![https://gitlab.com/electronDLT/chainhammer/blob/master/chainreader/img/quorum-istanbul_tps-bt-bs-gas_blks3680-3755.png](https://gitlab.com/electronDLT/chainhammer/raw/master/chainreader/img/quorum-istanbul_tps-bt-bs-gas_blks3680-3755.png)

**Comment by drandreaskrueger** [comment]
Actually, slightly different situation, @jpmsam - sorry.

I am using the https://github.com/jpmorganchase/quorum-examples and not quorum directly.

And it looks like `quorum-examples` is always going back to a tagged version 2.0.2, no?

Is [this line](https://github.com/jpmorganchase/quorum-examples/blob/master/vagrant/bootstrap.sh#L29)

    git checkout tags/v2.0.2

the only place that I would have to change, to get the quorum code at master HEAD?

**Comment by fixanoid** [comment]
@drandreaskrueger comment this line, and rebuild your vagrant environment. Alternatively, inside vagrant, cd into quorum, and git checkout master, then run make all.

Once thats done, replace geth with the one from build/bin.
