### ISSUE TITLE
Stop generate blocks after delete a validator 

### ISSUE THREAD

**Issue by a651694192** [Consensys-Incorporated/quorum#468]
#### System information
Azure

Geth version: `geth version 1.7.2`

OS & Version: Linux

1. I initialized 3 nodes in the cluster, two of which participated in the consensus
2. Add a new node and join the validator list by voting, succeeding
3. Delete the newly added node. After a period of time, the validator list shows that the node was successfully removed. At this point, the geth attach to other nodes is also alive, but the cluster no longer produces blocks.

Also: I geth attach to the current two v
Here is my configuration file:
{"alloc":{},"config":{"chainId":100,"homesteadBlock":0,"eip155Block":0,"eip158Block":0,"istanbul":{"epoch":3000000,"policy ": 0}," isQuorum ": true}," difficulty ":" 0x1 "," mixhash ":" 0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365 "," nonce ":" 0x0000000000000000 "," coinbase ":" 0x0000000000000000000000000000000000000000 "," timestamp ":" 0x0 "," parentHash ":" 0x0000000000000000000000000000000000000000000000000000000000000000 "," gasLimit ":" 0x0E0000000 "," extraData ":" 0x0000000000000000000000000000000000000000000000000000000000000000f86fea9432bc592bfe1083cea38fe5e247ecc68fcec8d465943f63f47d16277f08ffba60dc38f26f9c00e4dcbcb8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0 "}

blocks stop generate after number 4967, this logs may help
log:

7] Received a final committed proposal      address=0x814ee266C42D0f8c0aA59589D043470E263A1835 state=Committed
TRACE[08-08|08:19:07] Catch up latest proposal                 address=0x814ee266C42D0f8c0aA59589D043470E263A1835 old_round=0  old_seq=4967 number=4967 hash=74fe5c…ae9013
DEBUG[08-08|08:19:07] New round                                address=0x814ee266C42D0f8c0aA59589D043470E263A1835 old_round=0  old_seq=4967 old_proposer=0x814ee266C42D0f8c0aA59589D043470E263A1835 new_round=0 new_seq=4968 new_proposer=0xb5b5Efcff64a909e84049EdC81C7A340FC2f4452 valSet="[0x814ee266C42D0f8c0aA59589D043470E263A1835 0xb5b5Efcff64a909e84049EdC81C7A340FC2f4452]"                                            size=2 isProposer=false
DEBUG[08-08|08:19:07] Ethereum message handling failed         id=f77f8908556d994a conn=inbound    err=EOF
DEBUG[08-08|08:19:07] Removing Ethereum peer                   peer=f77f8908556d994a
TRACE[08-08|08:19:07] Unregistering sync peer                  peer=f77f8908556d994a
DEBUG[08-08|08:19:07] Removing p2p peer                        id=f77f8908556d994a conn=inbound    duration=6m27.703s          peers=2 req=false err=EOF
TRACE[08-08|08:19:08] handleRequest                            address=0x814ee266C42D0f8c0aA59589D043470E263A1835 state="Accept request" seq=4968 number=4968 hash=aaab73…507c3d
DEBUG[08-08|08:19:08] FS scan times                            list=144.499µs set=2.4µs    diff=2.2µs
TRACE[08-08|08:19:08] Handled keystore changes                 time=1µs
TRACE[08-08|08:19:08] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"
DEBUG[08-08|08:19:10] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[08-08|08:19:11] FS scan times                            list=88.4µs    set=2.5µs    diff=2.1µs
TRACE[08-08|08:19:11] Handled keystore changes                 time=1.1µs
TRACE[08-08|08:19:11] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"
DEBUG[08-08|08:19:14] FS scan times                            list=88.2µs    set=2.9µs    diff=2.5µs
TRACE[08-08|08:19:14] Handled keystore changes                 time=1.2µs
TRACE[08-08|08:19:14] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"
TRACE[08-08|08:19:17] Catch up round                           address=0x814ee266C42D0f8c0aA59589D043470E263A1835 old_round=0  old_seq=4968 old_proposer=0xb5b5Efcff64a909e84049EdC81C7A340FC2f4452 new_round=1 new_seq=4968 new_proposer="&{validators:[0xc424dd1080 0xc424dd10a0] policy:0 proposer:0xc424dd10a0 validatorMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} selector:0xbbf9f0}"
ERROR[08-08|08:19:17] Failed to decode message from payload    address=0x814ee266C42D0f8c0aA59589D043470E263A1835 err="unauthorized address"
TRACE[08-08|08:19:17] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"
DEBUG[08-08|08:19:17] FS scan times                            list=113.199µs set=2µs      diff=2.5µs
TRACE[08-08|08:19:17] Handled keystore changes                 time=1.3µs
TRACE[08-08|08:19:17] Dial task done                           task="wait for dial hist expire (29.9999976s)"
TRACE[08-08|08:19:17] New dial task                            task="staticdial 8a3b8106db4dfb6c 10.0.11.4:30303"
TRACE[08-08|08:19:17] Accepted connection                      addr=10.0.11.4:52332
TRACE[08-08|08:19:17] Quorum permissioning                     EnableNodePermission=false DataDir=/working-dir/dd Current Node ID=8a3b8106db4dfb6c2f89281ebc9e489966593dd80ddec4a2af1ec1c5ccf2c1327d01f87c27122beb3836f84bcf67e0766aedf19b6c434e3e27d785dc32d7a981 Node Name=Geth/v1.7.2-stable-df4267a2/linux-amd64/go1.9.3 Dialed Dest=nil
                   Connection ID=8a3b8106db4dfb6c Connection String=8a3b8106db4dfb6c2f89281ebc9e489966593dd80ddec4a2af1ec1c5ccf2c1327d01f87c27122beb3836f84bcf67e0766aedf19b6c434e3e27d785dc32d7a981
TRACE[08-08|08:19:17] Node Permissioning is Disabled.
TRACE[08-08|08:19:17] Rejected peer before protocol handshake  id=8a3b8106db4dfb6c addr=10.0.11.4:52332 conn=inbound    err="connected to self"
TRACE[08-08|08:19:17] Quorum permissioning                     EnableNodePermission=false DataDir=/working-dir/dd Current Node ID=8a3b8106db4dfb6c2f89281ebc9e489966593dd80ddec4a2af1ec1c5ccf2c1327d01f87c27122beb3836f84bcf67e0766aedf19b6c434e3e27d785dc32d7a981 Node Name=Geth/v1.7.2-stable-df4267a2/linux-amd64/go1.9.3 Dialed Dest="enode://8a3b8106db4dfb6c2f89281ebc9e489966593dd80ddec4a2af1ec1c5ccf2c1327d01f87c27122beb3836f84bcf67e0766aedf19b6c434e3e27d785dc32d7a981@10.0.11.4:30303?discport=0" Connection ID=8a3b8106db4dfb6c Connection String=8a3b8106db4dfb6c2f89281ebc9e489966593dd80ddec4a2af1ec1c5ccf2c1327d01f87c27122beb3836f84bcf67e0766aedf19b6c434e3e27d785dc32d7a981
TRACE[08-08|08:19:17] Node Permissioning is Disabled.
TRACE[08-08|08:19:17] Rejected peer before protocol handshake  id=8a3b8106db4dfb6c addr=10.0.11.4:30303 conn=staticdial err="connected to self"
TRACE[08-08|08:19:17] Dial task done                           task="staticdial 8a3b8106db4dfb6c 10.0.11.4:30303"
TRACE[08-08|08:19:17] New dial task                            task="wait for dial hist expire (29.9999977s)"
DEBUG[08-08|08:19:20] FS scan times                            list=93.6µs    set=2.4µs    diff=10.3µs
TRACE[08-08|08:19:20] Handled keystore changes                 time=1.1µs
TRACE[08-08|08:19:20] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"
DEBUG[08-08|08:19:23] FS scan times                            list=87.1µs    set=3µs      diff=2.4µs
TRACE[08-08|08:19:23] Handled keystore changes                 time=1.1µs
TRACE[08-08|08:19:23] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"
DEBUG[08-08|08:19:26] FS scan times                            list=104.1µs   set=3µs      diff=2.6µs
TRACE[08-08|08:19:26] Handled keystore changes                 time=1µs
TRACE[08-08|08:19:26] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"
TRACE[08-08|08:19:29] Catch up round                           address=0x814ee266C42D0f8c0aA59589D043470E263A1835 old_round=1  old_seq=4968 old_proposer=0xb5b5Efcff64a909e84049EdC81C7A340FC2f4452 new_round=2 new_seq=4968 new_proposer="&{validators:[0xc424dd1080 0xc424dd10a0] policy:0 proposer:0xc424dd10a0 validatorMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} selector:0xbbf9f0}"
ERROR[08-08|08:19:29] Failed to decode message from payload    address=0x814ee266C42D0f8c0aA59589D043470E263A1835 err="unauthorized address"
DEBUG[08-08|08:19:29] FS scan times                            list=53.8µs    set=2.3µs    diff=2.2µs
TRACE[08-08|08:19:29] Handled keystore changes                 time=1.3µs
TRACE[08-08|08:19:29] Failed to watch keystore folder          path=/working-dir/dd/keystore err="no space left on device"

It seems that round change will happen all the time and won't agree. The list of validators is also very strange.

**Comment by fixanoid** [comment]
@a651694192 it looks like you may have ran out of space on your device -- this would affect quorum client in a variety of ways. See if you can retry after a cleanup.

**Comment by a651694192** [comment]
Actually it is not the reason, because I just run a few minutes, and the space I take is less than 1GB, while my computer has 500GB disk.

**Comment by fixanoid** [comment]
@a651694192 its not necessarily the space, but also where you point the work dir. If you see the type of error you point to it generally means a misconfiguration. Perhpaps /working-dir/dd/keystore is not the right place where the workdir is?
