### ISSUE TITLE
IBFT scale down bugs

### ISSUE THREAD

**Issue by a651694192** [Consensys-Incorporated/quorum#472]
#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
Hi @a651694192 could you provide details of the issue please? Thank you.

**Comment by a651694192** [comment]
Details is here https://github.com/jpmorganchase/quorum/issues/468.
And I'm pretty sure that is not a no space problem.

**Comment by fixanoid** [comment]
Please keep in thread.

**Comment by a651694192** [comment]
Sorry I don't know what this mean clearly, could you make it more understandable?
