### ISSUE TITLE
After adding new node to the exist network, privatefor does not take effect

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#473]
I have a network with only one node. I can add node2 and node3 to this network with "raft.addpeer" and  -"-raftjoinexisting raftID"
After adding this two new node, I deploy a smart contract to node1 and set privateFor to the public key of node2. I found node3 can also see this contract.
Some time the contract can not be deloyed, The log in node1 is following:

INFO [08-09|19:14:22] 🔨  Mined block                           number=4 hash=33b4eb67      elapsed=1.149177ms
INFO [08-09|19:14:22] QUORUM-CHECKPOINT                        name=TX-ACCEPTED   tx=0x69226810391d6d264c38df541c0e1538896ef743a6b7aea833dd14bc72cc51a3
INFO [08-09|19:14:22] Imported new chain segment               blocks=1 txs=1 mgas=0.000 elapsed=629.277µs  mgasps=0.000 number=4 hash=33b4eb…3c1ab2
INFO [08-09|19:14:22] QUORUM-CHECKPOINT                        name=BLOCK-CREATED block=33b4eb67db0488a3e3d0dbbcaeaf08cd35ea8afc6fcfb23f768141ccd23c1ab2
INFO [08-09|19:14:22] persisted the latest applied index       index=8
INFO [08-09|19:14:22] TX failed, will be removed               hash=692268…cc51a3 err="nonce too low"
INFO [08-09|19:14:22] Not minting a new block since there are no pending transactions 

Can you tell me how to solve this two problem? Thank you!

**Comment by fixanoid** [comment]
@matrixoneken When new nodes join the cluster, did you also point the constellation config's otherNodes to the node1? If not, then private txns will fail. Additionally, when new nodes join, it takes up to 5 minutes to synchronize shadow constellation network.

If at all possible, please join our slack since these types of questions would be easier to answer in a chat context. Slack inviter: https://clh7rniov2.execute-api.us-east-1.amazonaws.com/Express/

**Comment by matrixoneken** [comment]
I have try your url and get "Failed! Invalid captcha."

**Comment by fixanoid** [comment]
The inviter has recaptcha on it, so if you are using an ad blocker of some sort, it might be getting blocked...

Constellation also contains peer 2 peer discovery mechanism, but you need to point all of the new / other nodes to the origin / first node. You do this by setting `othernodes` attribute, heres the sample: https://github.com/jpmorganchase/constellation/blob/79a2a2a4396229543640bb64b1a9dbed2c1ae33b/sample.conf#L26 and here is how we set it in our examples: https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/constellation-start.sh#L13

The process is described in detail here: https://github.com/jpmorganchase/constellation#how-it-works
