### ISSUE TITLE
Always get random port from local address or remote address

### ISSUE THREAD

**Issue by zhangds007** [Consensys-Incorporated/quorum#475]
Hi, 

Sometimes I get random port of remote address, and sometimes I get random port of local address.
Do you know why? Is it normal because of P2P protocol? How to fix this port as I configured when I start up GETH? thank you.

Here are some random ports I get in my test lab.
1. Random port 50432: in remote address: 
 "192.168.1.9:50432"
2. Random port 38018 in localAddress: "192.168.1.9:38018",

#### System information
    caps: ["eth/63"],
    id: "397cd74fc002570ac70fdee1796c059a930f49185bb835a6c3e78d50b0ae76dfe3f87743cb680d2002a7855cf0c85c0f074629d49b5146942043f621efed8c0b",
    name: "Geth/v1.7.2-stable-fd0e3b9d/linux-amd64/go1.10.1",
    network: {
      localAddress: "192.168.1.9:21000",
      remoteAddress: "192.168.1.9:50432"
    },
    protocols: {
      eth: {
        difficulty: 0,
        head: "0x6a6605601e17bbfbc0a199104a05f222d11da37fe2320c023394ff1e516243a2",
        version: 63
      }
    }
}, {
    caps: ["eth/63"],
    id: "4f566c5a754e319eb6a45414cda4ce56bad22106870bfa29888adb55f5814fd592a71bd540a2736afb49e0acf1e1c8d49940d8ecd6f07f3e1f17a16360826f94",
    name: "Geth/v1.7.2-stable-fd0e3b9d/linux-amd64/go1.10.1",
    network: {
      localAddress: "192.168.1.9:38018",
      remoteAddress: "192.168.1.13:21001"
    },
    protocols: {
      eth: {
        difficulty: 0,
        head: "0x6a6605601e17bbfbc0a199104a05f222d11da37fe2320c023394ff1e516243a2",
        version: 63
      }
    }

Br
Zhangds

**Comment by fixanoid** [comment]
This is normal behaviour. Node will pick a port for its udp/tcp communication on its own.
