### ISSUE TITLE
always get "rafthttp: health check for peer 4 could not connect: dial tcp 192.168.1.9:50404: connect: connection refused"

### ISSUE THREAD

**Issue by zhangds007** [Consensys-Incorporated/quorum#476]
Hi,

When I run quorum examples, I always get "rafthttp: health check for peer 4 could not connect: dial tcp 192.168.1.9:50404: connect: connection refused". but it is strange that all transaction and block can be synchronized correctly.

TRACE[08-12|18:44:42] New dial task                            task="wait for dial hist expire (29.999997023s)"
2018-08-12 18:44:47.390703 W | rafthttp: health check for peer 3 could not connect: dial tcp 192.168.1.9:50403: connect: connection refused
2018-08-12 18:44:47.403708 W | rafthttp: health check for peer 2 could not connect: dial tcp 192.168.1.9:50402: connect: connection refused
2018-08-12 18:44:47.424743 W | rafthttp: health check for peer 4 could not connect: dial tcp 192.168.1.9:50404: connect: connection refused
2018-08-12 18:44:47.430602 W | rafthttp: health check for peer 5 could not connect: dial tcp 192.168.1.9:50405: connect: connection refused

Br
ZhangDs

**Comment by fixanoid** [comment]
@zhangds007 could you describe how are you running the examples? is this happening in your vagrant env or?

**Comment by zhangds007** [comment]
@fixanoid ， I do not use vagrant but use different port number to differentiate each quorum node.  
for example, I set 192.168.1.9:50404 as raft connection for node4 and 192.168.1.9:50405 for node5.
Is this configuration allowed to setup multi-node test bed in one PC?

thank you.

**Comment by fixanoid** [comment]
@zhangds007 its fine and it would work, tho you may have issues with constellation TLS. That said, you are likely running into one of the raft misconfigs. Please see: #410 and #411

**Comment by ssudhir123** [comment]
@zhangds007 <https://github.com/zhangds007>  one quick way I go
about debugging these type errors (specially, if you have created your own
setup) is run the 'netstat -a | grep 50404'..just to make to sure Quorum is
listening on this port... eg, as below.. if you don't find the output as
below.. perhaps the process hasn't come up correctly and hence the other
nodes can't connect to it.

$ netstat -a | grep 50404 | grep LISTEN
tcp6       0      0 [::]:50404              [::]:*                  LISTEN
