### ISSUE TITLE
2 Way SSL Between Nodes and between Web3 and Node - Possible Enhancement? 

### ISSUE THREAD

**Issue by nathanawmk** [Consensys-Incorporated/quorum#477]
#### System information

Geth version: `geth version`
Geth 1.7.2

OS & Version: Windows/Linux/OSX
RHEL 7.4

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
To further enhance security and to comply to regulatory requirements, there is a need to enable HTTPS / 2 Way SSL Communication between Quorum Nodes.

Understand that Quorum uses existing Ethereum p2p transport layer to communicate transactions between nodes, but communicate blocks only through the Raft transport layer.

Can all the communication between nodes (inter/intra nodes and clients) and between a web3 client and node be SSL enabled?

https://ethereum.stackexchange.com/questions/56359/enabling-https-2-way-ssl-communication-between-ethereum-quorum-nodes

#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
Hi @nathanawmk we are considering securing json-rpc endpoints that geth exposes, but we haven't looked into securing devp2p. Stay tuned.

**Comment by nathanawmk** [comment]
Thanks @fixanoid!

**Comment by gtt116** [comment]
I'm wondering It there any progresses for this feature?

**Comment by antonydenyer** [comment]
Duplicate of https://github.com/ConsenSys/quorum/issues/477
