### ISSUE TITLE
please rename binary from `geth` to something else

### ISSUE THREAD

**Issue by drandreaskrueger** [Consensys-Incorporated/quorum#478]
## please rename binary from `geth` to something else
see comment below
https://github.com/jpmorganchase/quorum/issues/478#issuecomment-412482202

---
---
---
old issue, left here to demonstrate to what kind of confusion this wrong naming can lead:

---
---
---

# ReferenceError: 'istanbul' is not defined

istanbul module not accessible:

```
istanbul
ReferenceError: 'istanbul' is not defined
    at <anonymous>:1:1
```

see https://github.com/getamis/istanbul-tools/issues/111

```
geth attach http://localhost:8545
Welcome to the Geth JavaScript console!

instance: Geth/validator-0/v1.8.0-unstable/linux-amd64/go1.9.2
coinbase: 0xe4ca3432480a17778c20c6d203cc20263d5c0355
at block: 267 (Mon, 13 Aug 2018 11:29:39 BST)
 modules: eth:1.0 istanbul:1.0 net:1.0 personal:1.0 rpc:1.0 web3:1.0
> 

```

these APIs are working fine:
```
net
{
  listening: true,
  peerCount: 3,
  version: "2017",
  getListening: function(callback),
  getPeerCount: function(callback),
  getVersion: function(callback)
}
```

or e.g. 

```
rpc
{
  modules: {
    eth: "1.0",
    istanbul: "1.0",
    net: "1.0",
    personal: "1.0",
    rpc: "1.0",
    web3: "1.0"
  },
  getModules: function(callback)
}
```

do work fine, but

```
istanbul
ReferenceError: 'istanbul' is not defined
    at <anonymous>:1:1
```

#### System information

Geth version: 

inside JSRE console:

`Geth/validator-0/v1.8.0-unstable/linux-amd64/go1.9.2`  

from `docker-compose.yml`:
```
 validator-0:
    hostname: validator-0
    image: quay.io/amis/geth:latest 
```
--> https://quay.io/repository/amis/geth?tag=latest&tab=tags

my local geth:
```
geth version
Version: 1.8.14-unstable
Go Version: go1.10.3
```

OS & Version: Linux  
istanbul version v1.0.0

**Comment by drandreaskrueger** [comment]
ahhhh .... found the problem

What the [medium article](https://medium.com/getamis/istanbul-bft-ibft-c2758b7fe6ff) is not telling us:

we must use 
```
geth_quorum attach http://localhost:8545
```

instead of 

```
geth attach http://localhost:8545
```

**Comment by drandreaskrueger** [comment]
Actually, I always thought it is suboptimal to call the quorum binary `geth`. Please consider to rename it to `quorum` or `geth_quorum` or `quorum_geth`. 

This problem here and [there](https://github.com/getamis/istanbul-tools/issues/111) is an example of what can happen, inadvertently. Those instructions in the medium article told us to connect to the JSRE console via `geth attach http://...:8545` and because `geth` on my system is the vanilla geth, and not quorum geth ... this problem appeared.   
The medium article author forgot to mention that difference.    
And looking through the comments below the medium article ... other people encountered the same problem.  

So, please consider to rename the quorum binary from the already taken `geth`, thanks. 

(And those who never work with vanilla geth can then simply add a softlink `ln -s /usr/local/bin/quorum /usr/local/bin/geth`).

**Comment by drandreaskrueger** [comment]
Similar story: Why does Quorum pretend to be Geth over the RPC API ?

https://github.com/jpmorganchase/quorum/issues/507 *`Quorum/v2.1.0-stable-159d813f/linux-amd64/go1.9.3`*

**Comment by drandreaskrueger** [comment]
https://github.com/jpmorganchase/quorum/issues/505 *please consider to return more standardized answers about consensus algorithms*

**Comment by drandreaskrueger** [comment]
I have just tried your newest release https://github.com/jpmorganchase/quorum/releases/tag/v2.2.1 but still the 

* binary is called `geth` (https://github.com/jpmorganchase/quorum/issues/478)
* instance calls itself `Geth/v1.8.12-stable-c6f0ae4e/linux-amd64/go1.9.7` (https://github.com/jpmorganchase/quorum/issues/507)

Why? It is not geth. If it were geth, I would have downloaded it here: https://github.com/ethereum/go-ethereum/releases right?

Please consider to name your excellent fork properly. Or alternatively, do a pull request of all of your code to https://github.com/ethereum/go-ethereum - and once they have merged, then of course geth can be called geth, and provide Quorum abilities. But I think the latter is difficult by now, no? So what about calling `quorum` `quorum`, and calling "Quorum/v2.2..." by its name & version, which should be "Quorum/v2.2...", right?

Thanks for considering this. Or closing this issue, then I give up.

**Comment by drandreaskrueger** [comment]
Ah sorry - I just realized this is probably tracked here: https://github.com/jpmorganchase/quorum/issues/520 no?

**Comment by jbhurat** [comment]
Hi @drandreaskrueger, this is fixed under https://github.com/jpmorganchase/quorum/pull/616
