### ISSUE TITLE
bootnode 7nodes example

### ISSUE THREAD

**Issue by jaguarg** [Consensys-Incorporated/quorum#48]
Hi, 

In the 7 nodes example, the bootnode's enode is pre-defined. How did this get generated ? 

Is the bootnode simply used as a discovery mechanism?

Also, can I start my quorum network without a bootnode. I guess, I can add peers "manually" after each individual node is started ? 

Thanks

**Comment by tylobban** [comment]
Hi @jaguarg, answers below.  We'll add this to the documentation.

Thanks!

> “In the 7 nodes example, the bootnode's enode is pre-defined. How did this get generated ?”

In the vagrant  env, do the below:

1-	To generate the key for the first time:
`bootnode –genkey tmp_file.txt  //this will generate a key inside a “tmp_file.txt” file`
2-	To start using the key when you start your bootnode:
`bootnode –nodekey tmp_file.txt`
                or
`bootnode –nodekeyhex 77bd02ffa26e3fb8f324bda24ae588066f1873d95680104de5bc2db9e7b2e510 // This should be read from tmp_file.txt`


> “Is the bootnode simply used as a discovery mechanism?”

Yes, it’s a bootstrap node for the Ethereum discovery protocol.  See [here](https://godoc.org/github.com/ethereum/go-ethereum/cmd/bootnode).

> “Also, can I start my quorum network without a bootnode. I guess, I can add peers "manually" after each individual node is started ?”

Yes, though bootnode simplifies that for you.

**Comment by jaguarg** [comment]
Thanks !
