### ISSUE TITLE
The memory utilization is increasing in Istanbul BFT

### ISSUE THREAD

**Issue by hagishun** [Consensys-Incorporated/quorum#481]
#### System information
* ENV1
Version: 1.7.2-stable
Git Commit: 4a77480371683da5e56e48712d694c53d123b61a
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.7.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

* ENV2
Version: 1.7.2-stable
Git Commit: fd0e3b9d13f9b9563e7d5b3b1aba51f035f9cf0d
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.7.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

#### Expected behaviour
The memory utilization is periodically released.

#### Actual behaviour
Mamory utilization is increasing.
Only one node is periodically released.

#### Steps to reproduce the behaviour
Evnr

#### Backtrace
[log.zip](https://github.com/jpmorganchase/quorum/files/2285605/log.zip)

````
[backtrace]
````

**Comment by fixanoid** [comment]
@hagishun could you give me some details of the cluster: whats the configuration like and what hardware was used? Also, are you getting same issued when building quorum client from master?

**Comment by tharun-allu** [comment]
![image](https://user-images.githubusercontent.com/18491937/44354270-3d78ad00-a45e-11e8-94b6-53c8aee8e988.png)
This shows the memory utilization on the nodes I am running. Looks to me there might be some memory leak. 
The graph is 1 week utilization.

**Comment by fixanoid** [comment]
@tharun-allu thanks for the metrics. Whats the load on the chain and how far did it advance blockwise?

**Comment by tharun-allu** [comment]
@fixanoid the above graphs are from a network of nodes with 16G memory each and block height is 4 million.

I have restarted geth process in a different network yesterday with 7 million blocks and attached is the memory graph of the nodes (there are 4 in the network
![image](https://user-images.githubusercontent.com/18491937/44415998-a75c8980-a526-11e8-8833-f00e51115a1e.png)

What I noticed is 2 of the nodes shot up their memory and one node died and other will soon die.

**Comment by namtruong** [comment]
Hi @tharun-allu I've been trying to replicate this issue but unable to. Did you get this only after it reached 4 million blocks? From the graph attached it seems quite stable for sometime before going up - was there any incident observed in the log?

**Comment by tharun-allu** [comment]
![image](https://user-images.githubusercontent.com/18491937/44804817-62b09e00-ab77-11e8-97d7-c3ffd0fec2ce.png)
@namtruong The 2nd graph was  from my development network. Attached is the same nodes graphs for this week. Unfortunately I only implemented monitoring for blockheight last week and the block height for the second graph is 7.9 million now. 

My suspicion is that the more transactions that go through the network the faster the growth is. I currently run 3 sets of networks and the rate of growth seems to correlate with how busy (transactions) the network is. If you want me to give you any additional data or collect any new metrics I can do that and post here. 

Also to reduce confusion, I can only post data from only one environment. Let me know your thoughts

**Comment by namtruong** [comment]
@tharun-allu thank you for the info.

I've put up a change for this - https://github.com/namtruong/quorum/tree/bugfix/istanbul-storeBacklog-memory-leak
Could you please test it on the branch and let me know if this has fixed the issue?

Many thanks!

**Comment by tharun-allu** [comment]
![image](https://user-images.githubusercontent.com/18491937/45120201-4fbb4200-b112-11e8-8674-dcc120297f82.png)
This is the latest pattern, I have not tested the fix yet. As I notice only one node jumping up and then sort of stable after. I am going to restart that node to see if other nodes behave differently. I will keep you posted on my observations.

**Comment by tharun-allu** [comment]
@namtruong I updated my dev network with the code from branch and I will keep you updated how it goes today.
```
# ./geth version
Geth
Version: 1.7.2-stable
Git Commit: 891c6c5e5c2a38c2a2982587bc12b282422929a4
Quorum Version: 2.1.0
Architecture: amd64
Go Version: go1.10.4
Operating System: linux
GOPATH=
```

**Comment by namtruong** [comment]
@tharun-allu have you got any update?

**Comment by tharun-allu** [comment]
![image](https://user-images.githubusercontent.com/18491937/45318132-d3997380-b4f0-11e8-95fc-3abdf00158e7.png)

Looks like this has resolved this issue. I will confirm by downloading the 2.1.0 from upstream and seeing whether the issue come back.  I upgraded from 2.0.1 to 2.1.0 from @namtruong branch.

**Comment by namtruong** [comment]
@tharun-allu thanks for your update. Fyi, me and my colleague were also working on a different patch here https://github.com/jpmorganchase/quorum/compare/master...trung:f-istanbul-backlogs?expand=1 . We're in the process of testing the changes - but they are ultimately solving the same issue. Please feel free to test either of the solutions and let us know your feedback

**Comment by fixanoid** [comment]
@tharun-allu the new pull that addresses the issue is here: https://github.com/jpmorganchase/quorum/pull/521

**Comment by tharun-allu** [comment]
![image](https://user-images.githubusercontent.com/18491937/45716077-b4cb5a80-bb4a-11e8-93e5-a114cba0e3ce.png)
The PR seems to have resolved this issue.
