### ISSUE TITLE
How can I call  the  raft.addPeer with http

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#482]
I want to call the raft.addPeer with jsonrpc API as following
post  http://node1 ip:22000
{
	"jsonrpc":"2.0",
	"method":"raft_addPeer",
	"params":["enode://5442838d787dbb5314bec567034447ca11927fd8f63aba0dee6f067c3473804ab4c1005ab1f05437dc122494d73b19151cf1b9de87ef09de6170d66399b29cb1@127.0.0.1:21001?discport=0&raftport=50402"],
	"id":1
}

and get the result "The method raft_addPeer does not exist/is not available"
 Can I call this api by http? Thank you !

**Comment by fixanoid** [comment]
@matrixoneken this api should be available in quorum running --raft. Check if your --rpc is enabled and --rpcapi list contains raft.

**Comment by matrixoneken** [comment]
[3nodeexample.zip](https://github.com/jpmorganchase/quorum/files/2289138/3nodeexample.zip)


Thank you for your answer. I have uploaded a zip file. Please upzip  the file and run following the step

1, Run cd directory node 1 , run raft-init.sh and raft-start.sh . After running the node 1 is staring

2, In directory node 1, run geth attach qdata/dd1/geth.ipc  and  add the node 2 address as following   

raft.addPeer("enode://b6e3846d244d3ba190b59818b6dcdbd435093d3eb2bdf25dad48b03661f72574e90be58d6b5098781ece61f65acdc673b2086ba9a5df26ef8743e858cd8f48b2@127.0.0.1:21001?discport=0&raftport=50402")
 
the node 2 address can be found in the 'permissioned-nodes.json' in directory node 2 and you will get the raftid 

3 , Run cd  directory node 2, replace the raftid in 'raft-start.sh' after  --raftjoinexisting  and then  run raft-init.sh and raft-start.sh. After running the node 2 is staring

4, Run  cd directory node 1 then run  geth attach qdata/dd1/geth.ipc  and  add the node 3 address as following

raft.addPeer("enode://0c4dbda15656e208a75f09a86cdaafe1db2519df871e7b33e35261c04e20ab8ff13ef324b3c4d0c1894e3a2c485259f07563eae7d0dc4047acc5e76bc4c9f3a5@127.0.0.1:21002?discport=0&raftport=50403")

the node 3 address can be found in the 'permissioned-nodes.json' in directory node 3 and you will get the raftid 


5, Run cd  directory node 3, replace the raftid in 'raft-start.sh' after  --raftjoinexisting  and then  run raft-init.sh and raft-start.sh. After running the node 3 is staring

After these 5 steps , a network has been setup. 

The 'DeployMainContract.js' is the source code about  a private contract deployment with web3.js to above network.
Now the 'privatefor' setting can be take effect.

But I can not call raft.addPeer with jsonrpc API as following 
post http://node1 ip:22000
{
	"jsonrpc":"2.0",
	"method":"raft_addPeer",
	"params":["enode://5442838d787dbb5314bec567034447ca11927fd8f63aba0dee6f067c3473804ab4c1005ab1f05437dc122494d73b19151cf1b9de87ef09de6170d66399b29cb1@127.0.0.1:21003?discport=0&raftport=50404"],
	"id":1
	
}

and get the result "The method raft_addPeer does not exist/is not available"

I want to know which point I make a mistake. Thank you!
