### ISSUE TITLE
Run 7 nodes example,only 6 geth can be run.

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#483]
I run the 7nodes example with raft-init and raft-start
I find only 6 geth service can be run. the geth 7 can not be opened, I find the error in the 7.log  as following. Can you tell my why?  Thank you!

raft2018/08/14 08:06:57 INFO: newRaft 7 [peers: [1,2,3,4,5,6,7], term: 9, commit: 250, applied: 249, lastindex: 250, lastterm: 9]
INFO [08-14|08:06:57] HTTP endpoint opened: http://0.0.0.0:22006 
INFO [08-14|08:06:57] IPC endpoint opened: /home/supwin/quorum/examples/7nodes/qdata/dd7/geth.ipc 
INFO [08-14|08:06:57] QUORUM-CHECKPOINT                        name=TX-ACCEPTED tx=0x5113ac596834e9a0d1fb75629a7ba82b8cbccced47753f49032e34fe6ea68237
ERROR[08-14|08:06:57] 
########## BAD BLOCK #########
Chain config: {ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 1 EIP155: 0 EIP158: 1 Byzantium: 1 IsQuorum: true Engine: unknown}

Number: 236
Hash: 0xcb5393f0d6f7b338055104b9adfac24805360ee7ef4ddfb38788e575c21ab79d
	receipt{status=0 cgas=0 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}

Error: invalid receipt root hash (remote: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0 local: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c)
##############################
 
panic: failed to extend chain: invalid receipt root hash (remote: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0 local: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c)

goroutine 211 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).applyNewChainHead(0xc420079080, 0xc4216ce090)
	/home/supwin/quorum/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:869 +0x898
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).eventLoop(0xc420079080)
	/home/supwin/quorum/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:723 +0x5e5
created by github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft
	/home/supwin/quorum/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:482 +0x789

**Comment by fixanoid** [comment]
@matrixoneken there are several issues that may cause this, and we're tracking one thats most likely to cause it in #434.

If you simply need to fix it, then run stop.sh and then raft-init / raft-start again.
