### ISSUE TITLE
Getting error while trying to attach with first node using "geth attach qdata/dd1/geth.ipc" command

### ISSUE THREAD

**Issue by Prabhat-Sutar** [Consensys-Incorporated/quorum#485]
#### System information

Geth version: 1.8.13-stable
OS & Version: linux/ ubuntu 16.04 LTS
Go Version: go1.10

#### Expected behaviour
I trying to attach with the first node using "geth attach qdata/dd1/geth.ipc" command. It should attach me with first node, but it return error which I reported below.

#### Actual behaviour
While trying to attach with the first node using "geth attach qdata/dd1/geth.ipc" command I am getting this error.
Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory

**Comment by fixanoid** [comment]
@Prabhat-Sutar its likely that you are not running the command inside the vagrant examples vm. Please read and follow the instructions here: https://github.com/jpmorganchase/quorum-examples#vagrant-usage

**Comment by princesinha19** [comment]
@fixanoid so how can I run "geth attach qdata/dd1/geth.ipc" locally.
I have successfully run the command "raft-init.sh". Here is the output:-
![quorum raft succesful](https://user-images.githubusercontent.com/28489437/47548095-7d07bd80-d915-11e8-87b1-266fca917c0d.png)
But when I run next command "geth attach qdata/dd1/geth.ipc" in new terminal then it gives the error:
**Fatal: Unable to attach to remote geth: dial unix qdata/dd1/geth.ipc: connect: no such file or directory**

So, How can I run quorum (eg.. 7nodes) locally without vagrant?
