### ISSUE TITLE
Regarding EIP 155 changes and private transactions

### ISSUE THREAD

**Issue by akscanb** [Consensys-Incorporated/quorum#487]
Hi,
I was looking through some of pr namely the commits that involve eip 155 that were made to this repo, and I have question as to how you rectify the issue regarding transactional v values. The newest version of geth changed the mainnet v value to reflect 37 and 38 whereas these were the exact same v values that indicated a transaction was private within quorum. How is this not utterly breaking private transactions? Is that why the message struct was introduced?

**Comment by fixanoid** [comment]
@akscanb Quorum is not meant to be ran with chainId 1 to avoid collisions with the mainnet. Its not yet a hard restriction, but we may enforce it in the code.
