### ISSUE TITLE
How can I call raft.addPeer by Http

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#489]
I have another question in a close issue
https://github.com/jpmorganchase/quorum/issues/482
Please see it again. Thank you!
I want to know  How can I call raft.addPeer by Http with my setting in attachement. Thank you！

**Comment by foxhound313** [comment]
The RPC method **raft_addPeer** has to be exposed before it an be called via HTTP. This can be done via the --rpc and --rpcapi flags when starting a quorum node.

Going by the 7node example https://github.com/jpmorganchase/quorum-examples

Open quorum-examples/7nodes/raft-start.sh and go to line 69. Add "raft" to the --rpcapi flag. E.g:

ARGS="--nodiscover --verbosity 5 --networkid $NETWORK_ID --raft --rpc --rpcaddr 0.0.0.0 --rpcapi **raft**,admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints"

Start the network.

From cmd line, issue curl as follows:
curl -X POST --data '{"jsonrpc":"2.0", "method":"raft_addPeer", "params":["enode://22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222@127.0.0.1:45000?discport=0&raftpor=45001"], "id":67}' http://127.0.0.1:22000

you will see result:
{"jsonrpc":"2.0","id":67,"result":9}

where 9 is the returned RaftID.
