### ISSUE TITLE
Adding a new node to existing quorum network doesn't work, Getting the following error "unable to find peer1 in a cluster of 1000"

### ISSUE THREAD

**Issue by Ajaysethi136** [Consensys-Incorporated/quorum#494]
Adding a new node to existing quorum network doesn't work, Getting the following error "unable to find peer1 in a cluster of 1000".

Still Quorum is filled with lots of bugs, most of the things doesn't work at all. Adding a new node to existing network is a basic requirement, it should work.

**Comment by jpmsam** [comment]
@Ajaysethi136 adding a peer in Quorum is simple and it works. The issues we normally see reported are due to misconfiguration. Please provide more details on your configuration, network setup and any relevant details that can help us to replicate the issue so we can give some guidance.
