### ISSUE TITLE
Please consider to catch up with geth

### ISSUE THREAD

**Issue by drandreaskrueger** [Consensys-Incorporated/quorum#497]
because

> We've made 14 releases to go-ethereum since then, also I've no idea what modifications quorum made to our code.  I'd gladly debug Ethereum related issues, but I can't help debug a codebase that's a derivative of ours.
https://github.com/ethereum/go-ethereum/issues/17447#issuecomment-414279965

Please consider to update quorum to the newest geth

9,931 commits geth https://github.com/ethereum/go-ethereum
7,971 commits quorum https://github.com/jpmorganchase/quorum

Looks like a lot of work, yes.

**Comment by jpmsam** [comment]
@drandreaskrueger we are working on the pulling the upstream changes #496
