### ISSUE TITLE
[Question] How to authenticate/verify requests coming to quorum for private transactions

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/quorum#499]
Since offline signing of transactions is not yet supported in quorum ( #90 ). How to authenticate requests coming to quorum.

The only solution which is available with me is to unlock account with password. But it has it's own security issues.

**Comment by fixanoid** [comment]
A common pattern is to control access to the chain through another dapp. Essentially, your Quorum network should be running and should only face off to this app and the app would be the only one authorized to write txns onto the chain.
