### ISSUE TITLE
How can I recover an existing node to an  existing network

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#506]
I have 3 machines and each one opens a quorum node,such as node1,node2,node3.  Everything about the network is ok.
Now the second machine is down and the data file about the node2 is lost. But the key file about node2 has been backup  and the raftid、the node address of node2 are all stored in database.
I want to  use the key file, raftid and the node address to recover the node2.
 I have build the work dir with the key file. I think I don't need to  add peer to node1 again because node 1 always know the node2 address. How can I recover the node2 and make the network run as before ?

**Comment by matrixoneken** [comment]
My problem is same as following url
https://github.com/jpmorganchase/quorum/issues/97
The quorum work dir and constellation work dir are all loss. But I use the backup key files to init these dir. I want to open the node2 and recover private transaction contents. I open node2 without   --raftjoinexisting  and don't call node1 addPeer. I found geth about node 2 can not be run and I got following error in 2.log:


raft2018/08/29 00:19:24 INFO: 1 became follower at term 0
raft2018/08/29 00:19:24 INFO: newRaft 1 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
raft2018/08/29 00:19:24 INFO: 1 became follower at term 1
raft2018/08/29 00:19:24 INFO: 1 [term: 1] received a MsgHeartbeat message with higher term from 1 [term: 2]
raft2018/08/29 00:19:24 INFO: 1 became follower at term 2
raft2018/08/29 00:19:24 tocommit(5) is out of range [lastIndex(1)]. Was the raft log corrupted, truncated, or lost?
panic: tocommit(5) is out of range [lastIndex(1)]. Was the raft log corrupted, truncated, or lost?

goroutine 119 [running]:
log.(*Logger).Panicf(0xc420298280, 0x10aae4c, 0x5d, 0xc42023d7c0, 0x2, 0x2)
	/usr/local/go/src/log/log.go:219 +0xdb
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*DefaultLogger).Panicf(0x1abef50, 0x10aae4c, 0x5d, 0xc42023d7c0, 0x2, 0x2)
	/root/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/logger.go:121 +0x60
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raftLog).commitTo(0xc42017c850, 0x5)
	/root/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/log.go:191 +0x15c
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raft).handleHeartbeat(0xc420b86000, 0x8, 0x2, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:1095 +0x54
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.stepFollower(0xc420b86000, 0x8, 0x2, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:1041 +0x2a7
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*raft).Step(0xc420b86000, 0x8, 0x2, 0x1, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/raft.go:778 +0x1051
github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.(*node).run(0xc42017c930, 0xc420b86000)
	/root/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/node.go:346 +0x1189
created by github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft.StartNode
	/root/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/github.com/coreos/etcd/raft/node.go:215 +0x3db

I want to know how can I open node2 and how can I recover the private transaction contents which send to node2 before? Thank you!

**Comment by fixanoid** [comment]
The error is related to #411. My take on this is that the node that went out and needs to be recovered should be started with --raftjoinexisting after its initialized.

**Comment by matrixoneken** [comment]
Now my step about recover node 2 is following:
1)  Get the node 2 address and raftid from database
2)  Call  node 1 raft.removePeer with raftid from setp 1
3)  Initialize  the work dir and constellation work dir  of node 2
4)  Call node 1 raft.addPeer with the node 2 address setp 1 and getn a new raftId
5)  run node 2 with  --raftjoinexisting and new raftid from step 4

Follwoing above step node 2 can recover without any error. But when I get  the private contract which send to node2 before with web3.js, I get exception. I want to know how can I  recover the private contract which send to node2 before?

Thank you
