### ISSUE TITLE
`Quorum/v2.1.0-stable-159d813f/linux-amd64/go1.9.3`

### ISSUE THREAD

**Issue by drandreaskrueger** [Consensys-Incorporated/quorum#507]
At the moment Quorum pretends to be Geth over the RPC API:

    Geth/v1.7.2-stable-159d813f/linux-amd64/go1.9.3

That is ... sub-optimal.

Please instead return a string like

    Quorum/v2.1.0-stable-159d813f/linux-amd64/go1.9.3

or perhaps if you do not want to let go of the info from where exactly you forked `geth`:

    Quorum/v2.1.0-stable-159d813f/Geth-v1.7.2/linux-amd64/go1.9.3

Thanks for considering it.

**Comment by drandreaskrueger** [comment]
Why?

Just have a look at this (sorry, ugly) code mess when my chainhammer tries to figure out what exactly it is connected to:

[clienttype.py](https://gitlab.com/electronDLT/chainhammer/blob/master/clienttype.py) --> scroll down to `clientType(w3)`

**Comment by fixanoid** [comment]
EEA spec defines something we will adhere to soonish. Take a look: https://entethalliance.github.io/client-spec/spec.html#web3_clientcapabilities

**Comment by drandreaskrueger** [comment]
Thx, interesting.

> EEA spec defines something we will adhere to soonish.

But that is for the Enterprise Ethereum world - right?

How will that be kept coherent with the public chain Ethereum world?

---

Plus, the problem is much more profane:

Please simply instead return a string like 

    Quorum/v2.1.0-stable-159d813f/Geth-v1.7.2/linux-amd64/go1.9.3

instead of the misleading

    Geth/v1.7.2-stable-159d813f/linux-amd64/go1.9.3

Thanks.

**Comment by drandreaskrueger** [comment]
Why have you closed this?

In my latest experiments the quorum node is still reporting that it is pretending to be geth:

` Geth/v1.7.2-stable-3f1817ea/linux-amd64/go1.10.1`

**Comment by fixanoid** [comment]
@drandreaskrueger its being tracked via #520

**Comment by drandreaskrueger** [comment]
ah, thanks a lot!

I need a bit more patience ;-)

Are you on the web3summit.com or devcon?
