### ISSUE TITLE
Unable to join a network started by a v2.0.0 node from a v2.1.0 node

### ISSUE THREAD

**Issue by coeniebeyers** [Consensys-Incorporated/quorum#509]
#### System information

Geth version: `geth version`
```bash
$ geth version
Geth
Version: 1.7.2-stable
Git Commit: 99a83767ccf0384a3b58d9caffafabb5b49bd73c
Quorum Version: 2.1.0
Architecture: amd64
Network Id: 1337
Go Version: go1.10.3
Operating System: linux
GOPATH=/home/adhara/projects/go
GOROOT=/usr/local/go
```
OS & Version: Windows/Linux/OSX
Ubuntu 18.04

Branch, Commit Hash or Release: `git status`
On tag v2.1.0

#### Expected behaviour
Node should be able to join a network started by nodes with the below version of Quorum:
```bash
$ geth version
Geth
Version: 1.7.2-stable
Git Commit: 0905eda48eb07a4ce0e7072c1a2ecbf690ddff77
Quorum Version: 2.0.0
Architecture: amd64
Network Id: 1
Go Version: go1.7
Operating System: linux
GOPATH=/home/adhara/projects/go
GOROOT=/usr/local/go
```
Note that nodes started with the below version can join a network started with the above version of quorum:
```bash
$ geth version
Geth
Version: 1.7.2-stable
Git Commit: df4267a25637a5497a3db9fbde4603a3dcd6aa14
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.10.3
Operating System: linux
GOPATH=/home/adhara/projects/go
GOROOT=/usr/local/go
```
#### Actual behaviour
Nodes on v2.1.0 doesn't join a network started by v2.0.0

#### Steps to reproduce the behaviour
1. cd to `quorum` folder
2. `$ git checkout v2.1.0`
3. `$ make all`
4. Attempt to join existing IBFT network, however it doesn't join the network and geth logs the following:
```
INFO [08-31|08:27:59] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-99a83767/linux-amd64/go1.10.3
INFO [08-31|08:27:59] Allocated cache and file handles         database=/home/adhara/workspace/QuorumNetworkManager/Blockchain/geth/chaindata cache=128 handles=1024
WARN [08-31|08:27:59] Upgrading database to use lookup entries
INFO [08-31|08:27:59] Initialised chain configuration          config="{ChainID: 4058 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1 IsQuorum: true Engine: istanbul}"
INFO [08-31|08:27:59] Database deduplication successful        deduped=0
INFO [08-31|08:27:59] Initialising Ethereum protocol           versions="[63 62]" network=1337
INFO [08-31|08:27:59] Loaded most recent local header          number=0 hash=bf39d5…263d38 td=1
INFO [08-31|08:27:59] Loaded most recent local full block      number=0 hash=bf39d5…263d38 td=1
INFO [08-31|08:27:59] Loaded most recent local fast block      number=0 hash=bf39d5…263d38 td=1
INFO [08-31|08:27:59] Regenerated local transaction journal    transactions=0 accounts=0
INFO [08-31|08:27:59] Starting P2P networking
INFO [08-31|08:27:59] started whisper v.5.0
INFO [08-31|08:27:59] RLPx listener up                         self="enode://8c3bf6075f77ce3302e241b19de74a30b1b2d974406380b7209b16a0651cd22f376f535aafccdfbcc89e592336217c8e99b396613bb9f74dcce65447fc4fc0ae@[::]:20000?discport=0"
INFO [08-31|08:27:59] HTTP endpoint opened: http://0.0.0.0:20010
INFO [08-31|08:27:59] IPC endpoint opened: /home/adhara/workspace/QuorumNetworkManager/Blockchain/geth.ipc
INFO [08-31|08:27:59] WebSocket endpoint opened: ws://[::]:20020
WARN [08-31|08:27:59] message loop                             peer=b0a461273de85f5a err=EOF
INFO [08-31|08:27:59] Unlocked account                         address=0x3B9e66d31aa5f99d324dA480b2b9f47717141487
INFO [08-31|08:27:59] Transaction pool price threshold updated price=18000000000
INFO [08-31|08:27:59] Starting mining operation
INFO [08-31|08:27:59] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=196.2µs
WARN [08-31|08:27:59] Block sealing failed                     err=unauthorized
WARN [08-31|08:28:03] message loop                             peer=a336aafe8a5e72d5 err=EOF
WARN [08-31|08:28:03] message loop                             peer=a336aafe8a5e72d5 err=EOF
WARN [08-31|08:28:04] message loop                             peer=16b12f06459e3953 err=EOF
ERROR[08-31|08:28:09] Failed to decode message from payload    address=0xDc8e23e850a334bBe5aed3183723b496a922b975 err="unauthorized address"
WARN [08-31|08:28:12] message loop                             peer=b0a461273de85f5a err=EOF
ERROR[08-31|08:28:21] Failed to decode message from payload    address=0xDc8e23e850a334bBe5aed3183723b496a922b975 err="unauthorized address"
WARN [08-31|08:28:29] message loop                             peer=b0a461273de85f5a err=EOF
WARN [08-31|08:28:33] message loop                             peer=a336aafe8a5e72d5 err=EOF
WARN [08-31|08:28:33] message loop                             peer=a336aafe8a5e72d5 err=EOF
WARN [08-31|08:28:33] message loop                             peer=16b12f06459e3953 err=EOF
WARN [08-31|08:28:34] message loop                             peer=16b12f06459e3953 err=EOF
ERROR[08-31|08:28:35] Failed to decode message from payload    address=0xDc8e23e850a334bBe5aed3183723b496a922b975 err="unauthorized address"
WARN [08-31|08:28:42] message loop                             peer=b0a461273de85f5a err=EOF
ERROR[08-31|08:28:53] Failed to decode message from payload    address=0xDc8e23e850a334bBe5aed3183723b496a922b975 err="unauthorized address"

```

Note: reverting to previous version enables the node to join the network:
1. cd to `quorum` folder
2. `$ git checkout v2.0.2`
3. `$ make all`
4. Attempt to join existing IBFT network, in the same manner as above. The node joins the network and is able to sync: 
```bash
> eth.syncing
false
> eth.blockNumber
122673
```
With geth's logs not reporting any ERROR messages.

Please let me know if I can provide any additional information to assist with debugging, assuming this is not the expected behaviour.

**Comment by prd-fox** [comment]
Changes made in version v2.1.0 disallow a network ID of 1, which was the default prior to v2.1.0,
and all nodes must be using the same network ID in order to communicate.

Are you including the ```--networkid <id>``` in the ```geth``` startup command?
If not, can you try adding it with a value other than 1?

**Comment by coeniebeyers** [comment]
Thanks for the response. I use a `chainId` different than those specified in [EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) and assumed this was sufficient for separating the public chains from private ones. Why was the _forced_ `networkid` separation also introduced? Are all of the network IDs specified the [EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md) list (except 1337) prevented?

This effectively prevents any legacy quorum network from upgrading to the latest client quorum.

**Comment by prd-fox** [comment]
The ```chainId``` is only used for signing of transactions. The ```networkId``` is what separates public chains from private ones.
Any ```chainId``` or ```networkId``` can be used, except for 1.

Both older clients (pre-2.1.0) and new clients (2.1.0+) can specify a new network ID on startup, so it shouldn't prevent older Quorum networks from upgrading, although it will need some coordination between involved parties.

**Comment by coeniebeyers** [comment]
> The chainId is only used for signing of transactions. The networkId is what separates public chains from private ones.

Sure, but using a Chain ID other than 1 prevents transactions created on private networks from being used on the main ethereum network, thereby providing some separation. 

> Any chainId or networkId can be used, except for 1.

Shouldn't Quorum then prevent some of the other `networkid`/`chainId`s in EIP55 as well?

> Both older clients (pre-2.1.0) and new clients (2.1.0+) can specify a new network ID on startup, so it shouldn't prevent older Quorum networks from upgrading, although it will need some coordination between involved parties.

Can they do this while keeping the old blockchain, or will they need to start a new blockchain?

**Comment by coeniebeyers** [comment]
> > Both older clients (pre-2.1.0) and new clients (2.1.0+) can specify a new network ID on startup, so it shouldn't prevent older Quorum networks from upgrading, although it will need some coordination between involved parties.

> Can they do this while keeping the old blockchain, or will they need to start a new blockchain?

I've just tested this and can confirm that that passing in the same `networkid` seems to allow newer (>= 2.1.0) Quorum clients to connect to a older (< 2.1.0) clients, once the older clients have upgraded to a >= 2.1.0 Quorum version and pass in `--networkid` > 1. This also allows the old blockchain to be kept.

**Comment by coeniebeyers** [comment]
Closing this issue and continuing here: https://github.com/jpmorganchase/quorum/pull/502#issuecomment-417848827
