### ISSUE TITLE
I can not mine a private contract

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#511]
First I setup a node 1
Second I setup a node 2 with raft.addPeer and  --raftjoinexisting and  join node 1
Third   I setup a node 3 with raft.addPeer and  --raftjoinexisting and  join node 1

Now I setup a network with 3 nodes

I delopy a smart contract on node1 and set privateFor is the public key of node3
I can not get the contract address  and get following error in log file of node1

 TX failed, will be removed               hash=ee5098…b4f96c err="nonce too low"
INFO [09-03|11:04:57] Not minting a new block since there are no pending transactions 

I want to know why? Thank you!

**Comment by matrixoneken** [comment]
I also get another error
I have another network with 3 nodes. After run for a long time and I get following error:
        

  privatefrom= privatefor="[wms0ck7qhhOvl0hPFfHPurST50Ss7vhoAgexvhuF3gw=]"
2018-09-01 10:51:09.886549 I | http: Accept error: accept tcp [::]:22000: accept4: too many open files; retrying in 5ms
2018-09-01 10:51:09.891785 I | http: Accept error: accept tcp [::]:22000: accept4: too many open files; retrying in 5ms
INFO [09-01|10:51:09] TX failed, will be removed               hash=635974â€¦ba259d err="nonce too high"
INFO [09-01|10:51:09] Not minting a new block since there are no pending transactions 
2018-09-01 10:51:10.000292 I | http: Accept error: accept tcp [::]:22000: accept4: too many open files; retrying in 5ms
2018-09-01 10:51:10.005860 I | http: Accept error: accept tcp [::]:22000: accept4: too many open files; retrying in 10ms
2018-09-01 10:51:10.042058 I | http: Accept error: accept tcp [::]:22000: accept4: too many open files; retrying in 5ms
2018-09-01 10:51:10.049006 I | http: Accept error: accept tcp [::]:22000: accept4: too many open files; retrying in 10ms
INFO [09-01|10:51:10] Submitted contract creation              fullhash=0x769919877684f690dd92931117eaec63d2ce0b034a8bdf7cbfa530dae039f598 to=0x49CdFaEa680219212bee8427c49a6c1b882E5DD6
INFO [09-01|10:51:10] QUORUM-CHECKPOINT                        name=TX-CREATED      tx=0x769919877684f690dd92931117eaec63d2ce0b034a8bdf7cbfa530dae039f598 to=0x49CdFaEa680219212bee8427c49a6c1b882E5DD6
INFO [09-01|10:51:10] sending private tx       


I want to know whether  the quorum has the limit about files?

**Comment by fixanoid** [comment]
@matrixoneken please upgrade to Quorum v2.1.0 to address this issue

**Comment by shikharka** [comment]
Hello, I am facing same problem. How can i check my Quorum version?

**Comment by SatpalSandhu61** [comment]
You can get the version using:
geth version

**Comment by shikharka** [comment]
Thanks!! The version is 2.1.1 but still getting same error. Tried passing nonce during contract function call(web3) still same error.

Though if I try calling contract function from truffle console it works. Any idea where should i look? 

web3 0.20.0,  truffle -1.4.14

**Comment by SatpalSandhu61** [comment]
Since this issue is closed, can you create a new issue ticket please - with details of the actions you're taking, the behaviour you're seeing and what you expect to see.
You also need to mention the geth version and details of your genesis block.
Thanks.
