### ISSUE TITLE
new peers cannot join cluster

### ISSUE THREAD

**Issue by lantianqiongfeng** [Consensys-Incorporated/quorum#512]
when I start one peers,I want to add new peer.
at first ipc ,I use raft.addPeer to add new peer,but when use to start second peer ,it was wrong
like this:
peer is unknown or unhealthy

Please ,where I was wrong?

I was deployed two machine
one:192.168.1.248 two:192.168.1.243
1.start quorum one merchine;
2.add two merchine,raft.addPeers can get raft_id ;
3.raftjoinexisting raft_id 
but logs is 
![image](https://user-images.githubusercontent.com/4092651/44979074-ba4b7100-af9e-11e8-8783-60334847826d.png)
why?

**Comment by fixanoid** [comment]
@lantianqiongfeng Please share connection information as the log above is insufficient. These types of issues are generally caused by network mis-configuration.
