### ISSUE TITLE
bootnode -writeaddress is not working

### ISSUE THREAD

**Issue by kinfkong** [Consensys-Incorporated/quorum#513]
When I run command:
`/usr/local/bin/bootnode -genkey /tmp/tmp.txt -writeaddress`
The -writeaddress is not working (no address output).
I view the code:
there is a `return` statement in the switch branch when -genkey is provided.
That is wrong.
See the following code line:
https://github.com/jpmorganchase/quorum/blob/06342c9490f9fe644c66dfe60d798b285e17338c/cmd/bootnode/main.go#L71

**Comment by prd-fox** [comment]
Hi Kinfkong,

This is part of the upstream go-ethereum codebase.
It seems they intended bootnode key generation and bootnode application startup to be intentionally run separately.

I see you created an issue with upstream at https://github.com/ethereum/go-ethereum/issues/17579

I will leave this issue open to track the status of the upstream issue, but this is not directly related to Quorum.
