### ISSUE TITLE
The geth will auto exit

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#514]
I have a network about 3 node. Recently the geth will auto exit and can not be recovered. I found the following in log, can you tell me why? Thank you!

raft2018/09/04 18:00:12 INFO: 2 became follower at term 221
raft2018/09/04 18:00:12 INFO: newRaft 2 [peers: [1,2,3], term: 221, commit: 80, applied: 79, lastindex: 80, lastterm: 221]
INFO [09-04|18:00:12] IPC endpoint opened: /root/QuorumSetup/qdata/dd2/geth.ipc 
INFO [09-04|18:00:12] HTTP endpoint opened: http://0.0.0.0:22001 
2018-09-04 18:00:12.358088 I | rafthttp: established a TCP streaming connection with peer 1 (stream MsgApp v2 writer)
INFO [09-04|18:00:12] QUORUM-CHECKPOINT                        name=TX-ACCEPTED tx=0x60e7f7400ca9975c82429bc2ce5c5879555593c1013f3d8eb52affc1099c78d7
2018-09-04 18:00:12.358654 I | rafthttp: established a TCP streaming connection with peer 1 (stream Message writer)
ERROR[09-04|18:00:12] 
########## BAD BLOCK #########
Chain config: {ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 1 EIP155: 0 EIP158: 1 Byzantium: 1 IsQuorum: true Engine: unknown}

Number: 74
Hash: 0x05d072248127470856a8d3e69b6417e1476a116c371cf16483086c186ccf5af3
	receipt{status=0 cgas=0 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}

Error: invalid receipt root hash (remote: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0 local: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c)
##############################
 
panic: failed to extend chain: invalid receipt root hash (remote: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0 local: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c)

goroutine 194 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).applyNewChainHead(0xc4200a9a20, 0xc4210aa1b0)
	/home/supwin/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:869 +0x898
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).eventLoop(0xc4200a9a20)
	/home/supwin/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:723 +0x5e5
created by github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft
	/home/supwin/quorum-examples/vagrant/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:482 +0x78

**Comment by prd-fox** [comment]
Hi,

Can you reproduce this consistently?
A minimal example that we can run to reproduce this would be useful for diving into this issue.

Also, if the contract being rejected on some nodes? There is a known issue here https://github.com/jpmorganchase/quorum/issues/434 for contracts that need reverting.

**Comment by matrixoneken** [comment]
@prd-fox 
 Do you have email. I write a nodejs program to deployment the quorum node . Please get me an email, I will send you my program and the tutorial about the program . Thank you !

**Comment by prd-fox** [comment]
It would be preferable if you were able to attach a sample file to this issue (partly for documentation on the issue).

If you are unable to attach the program or a similar example, I can let you know when the above issue is solved and we can see if it applies to your issue and go from there.

**Comment by matrixoneken** [comment]
@prd-fox  Thank you for answer

[QuorumSetup.tar.gz](https://github.com/jpmorganchase/quorum/files/2364943/QuorumSetup.tar.gz)


I have uploaded a compressed file named  QuorumSetup.tar.gz which including my program, you can run by follwing step

1) Decompress the file and cd the root dir

2) Run the sh bootstrap.sh to install the quorum 

3) Install the nodejs on your machine

4) For the first node run "node SetupQuorum 1 21000 22000 50401 9001  0" .
 The SetupQuorum  is the program name. 
The 1 means the node number.
 The 21000 means the port of this node.
 The 22000 means the port for rpc.
 The 50401 means the port for raft.
 The 9001 means the port for constellation.
 The 0 means this is the first node.

5) For the second  node run "node SetupQuorum 2 21001 22001 50402 9002  1 http://192.168.160.129:9001/  http://192.168.160.129:22000/". 
The 2 means the node number. 
The 21001 means the port of this node. 
The 22001 means the port for rpc.
 The 50402 means the port for raft.
 The 9002 means the port for constellation. 
The 1 means this is not the first node. 
The http://192.168.160.129:9001/  is the constellaion url of the first  node which used by setting the --othernodes of  constellation command.  You can change the ip of your computer.
The http://192.168.160.129:22000/ is the first node rpc url which used by raft.addpeer. You can change the ip of your computer.

6) For the third node run "node SetupQuorum 3 21002 22002 50403 9003  1 http://192.168.160.129:9001/  http://192.168.160.129:22000/" 
The 3 means the node number.
 The 21002 means the port of this node.
 The 22002 means the port for rpc.
 The 50403 means the port for raft.
 The 9003 means the port for constellation. 
The 1 means this is not the first node. 
The http://192.168.160.129:9001/  is the constellaion url of the first node which used by setting the --othernodes of  constellation command. You can change the ip of your computer.
The http://192.168.160.129:22000/ is the first node rpc url which used by raft.addpeer. You can change the ip of your computer.

**Comment by prd-fox** [comment]
Thanks matrixoneken. I will get back to you when I have had a chance to go over it :)

**Comment by fixanoid** [comment]
@matrixoneken also, what version of Quorum are you running? Please paste results of `geth version`

**Comment by matrixoneken** [comment]
Following is the geth version

Geth
Version: 1.7.2-stable
Git Commit: df4267a25637a5497a3db9fbde4603a3dcd6aa14
Quorum Version: 2.0.1
Architecture: amd64
Network Id: 1
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

**Comment by prd-fox** [comment]
Thanks @fixanoid.
@matrixoneken can you retry with the latest version of Quorum (v2.1.0).

I also took a look at the sample you provided, but it didn't manage to get through the setup script properly.

I didn't see any contracts or transaction deployment code, nor did your instructions specify any. Since you are using raft, you can only create new blocks on new transactions - are you implying this occurs with any transaction?
If not, it would be useful to see what contract you have that results in the issue.

**Comment by matrixoneken** [comment]
I want to know how to update from v 2.0.2 to v2.10 thank you!

**Comment by matrixoneken** [comment]
I have installed v 2.0.2 on a machine. How can I update to 2.1.0
The contrace is deploy by web3.js on another program which is as following


var Web3 = require('web3')
var web3 = new Web3(new Web3.providers.HttpProvider('http://192.168.135.67:22000')) //node1 rpc address
var version = web3.version.node;
console.log("version:"+version);
var mainAbi=[{"constant":false,"inputs":[{"name":"strVal","type":"string"}],"name":"Set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"Get","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"constant":true,"inputs":[],"name":"holdings","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"strVal","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}];
var mainBytecode ="0x608060405234801561001057600080fd5b50604051610514380380610514833981018060405281019080805182019291905050508060009080519060200190610049929190610050565b50506100f5565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061009157805160ff19168380011785556100bf565b828001600101855582156100bf579182015b828111156100be5782518255916020019190600101906100a3565b5b5090506100cc91906100d0565b5090565b6100f291905b808211156100ee5760008160009055506001016100d6565b5090565b90565b610410806101046000396000f300608060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806334541fcd1461005c578063b1976a02146100c5578063e79bf13b14610155575b600080fd5b34801561006857600080fd5b506100c3600480360381019080803590602001908201803590602001908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505091929192905050506101e5565b005b3480156100d157600080fd5b506100da6101ff565b6040518080602001828103825283818151815260200191508051906020019080838360005b8381101561011a5780820151818401526020810190506100ff565b50505050905090810190601f1680156101475780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34801561016157600080fd5b5061016a6102a1565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156101aa57808201518184015260208101905061018f565b50505050905090810190601f1680156101d75780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b80600090805190602001906101fb92919061033f565b5050565b606060008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102975780601f1061026c57610100808354040283529160200191610297565b820191906000526020600020905b81548152906001019060200180831161027a57829003601f168201915b5050505050905090565b60008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156103375780601f1061030c57610100808354040283529160200191610337565b820191906000526020600020905b81548152906001019060200180831161031a57829003601f168201915b505050505081565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061038057805160ff19168380011785556103ae565b828001600101855582156103ae579182015b828111156103ad578251825591602001919060010190610392565b5b5090506103bb91906103bf565b5090565b6103e191905b808211156103dd5760008160009055506001016103c5565b5090565b905600a165627a7a723058204e0f342b1d9b9db66f0d458a7d24ac3a066a5919d1c5c3011f4453a5f78dfb6e0029";
var maincontractContract = web3.eth.contract(mainAbi);
var coinbase = web3.eth.accounts[0];
console.log("coinbase:"+coinbase);

var strVal="BTC-10,ETH-10"
var maincontract = maincontractContract.new(
    strVal,
    {
        from: coinbase,
        data: mainBytecode,
        gas: '0x47b760',
        privateFor: ["fkZkKWjFV0qI2YAAc+A6wgWlYuzvLhtcLOX3P6a9TUE="]  //set contract private for node2
    }, function (e, contract) {
        // console.log(e, contract);
        try {


            if (typeof contract.address !== 'undefined') {
                console.log('Main Contract mined! address: ' + contract.address + ' transactionHash: ' + contract.transactionHash);

           }
            else {
                if (e != null) {

                    console.log('Main Contract mined error'+ e.toString());

                }


            }
        }catch(e)
        {
            console.log('Main Contract mined error'+ e.toString());
        }
    });

**Comment by fixanoid** [comment]
@matrixoneken since you are running quorum in vagrant, please follow these instructions. They are intended to be executed from vagrant guest env.

```
cd ~/quorum
make all
sudo cp build/bin/geth /usr/local/bin/geth
```

After this you'll need to restart your quorum nodes. I'm also a bit confused: how come you are running manual node joins when an example stands up 7 nodes fro you? Thanks.
