### ISSUE TITLE
Contract to contract calling not working

### ISSUE THREAD

**Issue by carnelius8888** [Consensys-Incorporated/quorum#518]
#### System information

Geth version: `geth version` 1.7.2

OS & Version: Windows/Linux/OSX04

Branch, Commit Hash or Release: `git status`
[Client.txt](https://github.com/jpmorganchase/quorum/files/2366541/Client.txt)

#### Steps to reproduce the behaviour
We are trying to call methods of CustomerImpl using interface Customer from another contract Client.
We are not able to do so and events are not being raised.
Please find attached Client.txt having all contracts
#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
@carnelius8888 what version of Quorum are you using? Could you provide exactly what you are running and how on the client?

**Comment by fixanoid** [comment]
Please reopen if this is an issue.
