### ISSUE TITLE
Implement eth_clientCapabilities and RPC info updates.

### ISSUE THREAD

**Issue by fixanoid** [Consensys-Incorporated/quorum#520]
EEA spec definition https://entethalliance.github.io/client-spec/spec.html#web3_clientcapabilities

Main implementation ticket for #507 and #505

**Comment by drandreaskrueger** [comment]
would https://github.com/jpmorganchase/quorum/issues/369 fit here too?

**Comment by antonydenyer** [comment]
Removed form spec
