### ISSUE TITLE
For v 2.1.0, how to add peer to tessera-config.json

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#522]
For v2.1.0, I found a tessera-config.json in 7nodes example. But 7nodes example open 7 nodes at the same time.
For my business. I open a node on  a machine. And after a few day I open another node on another machine. I want to kown how to add the second node address to the peer list in tessera-config.json of first node .

**Comment by matrixoneken** [comment]
If I open another node , how to add the new node address to the peer list?

{
    "useWhiteList": false,
    "jdbc": {
        "username": "sa",
        "password": "",
        "url": "jdbc:h2:./qdata/c1/db1;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0"
    },
    "server": {
        "port": 9001,
        "hostName": "http://localhost",
        "sslConfig": {
            "tls": "OFF",
            "generateKeyStoreIfNotExisted": true,
            "serverKeyStore": "/root/quorum-examples/examples/7nodes/qdata/c1/server1-keystore",
            "serverKeyStorePassword": "quorum",
            "serverTrustStore": "/root/quorum-examples/examples/7nodes/qdata/c1/server-truststore",
            "serverTrustStorePassword": "quorum",
            "serverTrustMode": "TOFU",
            "knownClientsFile": "/root/quorum-examples/examples/7nodes/qdata/c1/knownClients",
            "clientKeyStore": "/root/quorum-examples/examples/7nodes/qdata/c1/client1-keystore",
            "clientKeyStorePassword": "quorum",
            "clientTrustStore": "/root/quorum-examples/examples/7nodes/qdata/c1/client-truststore",
            "clientTrustStorePassword": "quorum",
            "clientTrustMode": "TOFU",
            "knownServersFile": "/root/quorum-examples/examples/7nodes/qdata/c1/knownServers"
        }
    },
    **"peer": [
        {
            "url": "http://localhost:9001"
        },
        {
            "url": "http://localhost:9002"
        },
        {
            "url": "http://localhost:9003"
        },
        {
            "url": "http://localhost:9004"
        },
        {
            "url": "http://localhost:9005"
        },
        {
            "url": "http://localhost:9006"
        },
        {
            "url": "http://localhost:9007"
        }
    ],**
    "keys": {
        "passwords": [],
        "keyData": [
            {
                "config": {"data":{"bytes":"Wl+xSyXVuuqzpvznOS7dOobhcn4C5auxkFRi7yLtgtA="},"type":"unlocked"},
                "publicKey": "BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="
            }
        ]
    },
    "alwaysSendTo": [],
    "unixSocketFile": "/root/quorum-examples/examples/7nodes/qdata/c1/tm.ipc"
}

**Comment by prd-fox** [comment]
You can add the 2nd node to the peers list of the 1st, but for this to take effect you will need to restart the 1st node.
However, this is just the initial list of peers. After starting up, it will query the peers in this list for any other known peers they know of.

If you add the 1st nodes address to the peers list of the 2nd node, then upon starting up, the 2nd node will broadcast itself to node 1 and node 1 will add it to its list of known nodes.

This way, node 1 doesn't need to be restarted or aware of node 2 at startup time.

---

I feel like I've said 'node' and 'peer' too many times :)
