### ISSUE TITLE
Is there a more elaborate getting started document? 

### ISSUE THREAD

**Issue by Eithcowich** [Consensys-Incorporated/quorum#527]
I'm looking to set up quorum on several nodes, all hosted on Azure. Planning to use Ubuntu, or CentOs, and I have some questions. 

1. Is there a more elaborate getting started document than [this one](https://github.com/jpmorganchase/quorum/wiki/Getting-Set-Up)? 

2. Is there a preference to a particular OS? 

3. Which minimal size should a machine be?

**Comment by fixanoid** [comment]
Hi @Eithcowich 

1. https://github.com/jpmorganchase/quorum-examples is a more detailed environment to get acquainted with Quorum. It comes with setup and configs that you may explore and modify in your own networks

2. Default OS we use is Ubuntu, but Quorum should run on anything else with exception of Windows. That said, you will need to build your own executables off the sources we provide in our repos.

3. This depends on the size of expected chain, tho in AWS terms, t3.small+ will work just fine

**Comment by Eithcowich** [comment]
So you're saying I could use the 7nodes example as a template, while building each node from scratch? 

Is [this guide](https://github.com/ConsenSys/quorum-docker-Nnodes/tree/master/Nnodes) reliable? Note that I don't want the nodes to run in a container but directly on the machine. Unless there is a built in advantage to `Docker`. 

Thanks for the answers on the two other points.

**Comment by fixanoid** [comment]
@Eithcowich the guide is fine, tho its a bit dated -- we recommend tessera as a replacement for constellation at this point.

quorum-examples is an example of how to run everything albeit in a single machine. The setup is the same if you spread it across multiple machines tho. Docker is not required tho our stance is that Quorum performance metrics appear to be the same vs running on bare os. There are several tools out there that help automate initial configuration, they are https://github.com/ConsenSys/QuorumNetworkManager, https://github.com/synechron-finlabs/quorum-maker/, and our own https://github.com/jpmorganchase/quorum-aws
