### ISSUE TITLE
Does tessera support mysql

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#529]
I see the jdbc url in  tessera config file but it uses the H2. I want to know wether it can use mysql?  And how to config? Thank you!

**Comment by prd-fox** [comment]
Yes you can.

You will need to add the MySQL driver to the classpath when executing the java command, and set the JDBC URL accordingly, and setup the database tables prior to running the application.
You see how to achieve that [here](https://github.com/jpmorganchase/tessera#running-tessera).

---

Also, for issues relating to Tessera, could you open them on the Tessera repositoty issues page please? This helps keep the issues section clean for each individual project.

Thanks.
