### ISSUE TITLE
http: panic serving: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by dhakad-rakesh** [Consensys-Incorporated/quorum#531]
#### System information

Geth version: `Geth
Version: 1.7.2-stable
Git Commit: 0af7ad0664e1d5d7367eaa47e00dbe0501a526dd
Quorum Version: 2.1.0
Architecture: amd64
Network Id: 1337
Go Version: go1.10.2
Operating System: linux
GOPATH=
GOROOT=/usr/local/go`

OS & Version: Linux

Branch, Commit Hash or Release: `Latest master branch`

#### Expected behaviour
Should working file

#### Actual behaviour
[Same issue](https://github.com/jpmorganchase/quorum/issues/352)
http: panic serving: runtime error: invalid memory address or nil pointer dereference

#### Steps to reproduce the behaviour
Setup and connected 3 nodes based on Raft consensus. Send bulk Tx on any node, after some time (maybe after 20000tx ) got the error.

#### Backtrace
![screenshot from 2018-09-18 20-14-57](https://user-images.githubusercontent.com/13905129/45703680-a99c1d00-bb92-11e8-8e1f-43ed9872e79f.png)

**Comment by fixanoid** [comment]
Is this something you are able to reproduce all the time? The txn load, are these public or private and value or smart contract calls?

**Comment by dhakad-rakesh** [comment]
> Is this something you are able to reproduce all the time?

Yes.
> The txn load, are these public or private and value or smart contract calls?

Public value tx. I run script to send eth from one account to another.

**Comment by fixanoid** [comment]
@rakeshdhakad please reopen this on https://github.com/synechron-finlabs/quorum-maker. I suspect this is something in their node manager code
