### ISSUE TITLE
Single-party private contract

### ISSUE THREAD

**Issue by ijxy** [Consensys-Incorporated/quorum#532]
I was following [this guide on using quorum](https://truffleframework.com/tutorials/building-dapps-for-quorum-private-enterprise-blockchains) with truffle to deploy contracts and make transactions.

It all worked perfectly, until...

... I tried to deploy a contract with `privateFor: ['<the deploying node's pub key>']`, at which point I got an error:

```
Using network 'quorum1'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x7ec7a03c50fc1e93a9fb61c39dc9c73d6cab57380805bdb5421d7426b13f08ca
  Migrations: 0x3950943d8d86267c04a4bba804f9f0b8a01c2fb8
Saving artifacts...
Running migration: 2_deploy2.js
  Replacing SimpleStorage...
  ... undefined
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Tue, 18 Sep 2018 23:46:30 GMT] Server:[Warp/3.2.13]] Body:0xc435306600 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc4356b4c00 TLS:<nil>}
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The deployment succeeds with any of the 6 other pub-keys at my disposal.

I'm essentially wondering whether this is desired behaviour, i.e. whether quorum intentionally doesn't allow a contract to be visible by only the deploying node, or whether it is a bug. 

Personally, unless there is a compelling technical reason for why it can't be done, then it would be a feature I'd like to see. I already have a use in mind for "completely private" contracts in a project I'm working on (in financial markets infrastructure).

**Comment by fixanoid** [comment]
Hi @jdparkinson93 thats a correct observation: originating node should not be included in the privateFor and if it is, that would throw an error. At the moment, this is how Quorum is designed.

**Comment by ijxy** [comment]
@fixanoid Hi, I appreciate the fast response.

Is there any official way to achieve this?

I could have a second node owned by the same entity that existed purely to deploy a contract, but that isn't an elegant way to go.

I'm open to suggestions; do you think there is any scope for this behaviour to be changed? Is it for a technical reason/limitation that it is this way currently?

**Comment by fixanoid** [comment]
Well, in our view the idea of privacy on blockchain was intended to ensure that the contents of private txns are still verifiable by N participating parties. In your use case, a blockchain may not be required at all -- why record it at all if the data belongs to you only?

It is possible to achieve this as the code is open for others to fork and commit to. Best place to discuss such an implementation would be our slack and it would likely require modification to both Quorum client and corresponding txn manager.

**Comment by ijxy** [comment]
@fixanoid In essence, the reason for wanting to do this is that if I want to change the privacy on an existing contract (i.e. amend `privateFor` post-deployment) I would have to redeploy the contract with a new `privateFor` list and migrate all the data stored in it with the correct privacy between participants (which, to the best of my knowledge, can't be done).

If instead we had several 'pure private' contracts that did all the storage and a proxy contract that exposed API (_which could easily be redeployed_), then we could allow participants to save and query data to that 'pure private' contract based on access control so they could only see what is intended for them to see. Any time a new participant joined/left, then the proxy contract would be redeployed but the 'pure private' contracts wouldn't need to be.

I'm no so bothered about the feature, more the functionality it allows me (theoretically) to achieve as described above. If there is an established pattern for this sort of thing on Quorum then I'd be more than happy to hear about it - otherwise I may take your suggestion and pose it on the slack channel.

**Comment by fixanoid** [comment]
@jdparkinson93 @jpmsam has corrected me by pointing out this pull: https://github.com/jpmorganchase/quorum/pull/165. In short, you should disregard my previous claims as it is possible and works well -- I've just tested it myself.
