### ISSUE TITLE
Dynamically add a new peer to my quorum network

### ISSUE THREAD

**Issue by Aghorb** [Consensys-Incorporated/quorum#545]
@fixanoid @jpmsam, I setup my quorum network using the 7nodes examples. Now, I want to dynamically add a peers to my network without restart the blockchain. After doing some research, I realized that it is not possible to do? 
Hence, I want to know if it is technically possible to do and what are the required changes to be made in the actual version of quorum to make it possible.
A last question, have you an idea if this will be considered in the future versions?

**Comment by fixanoid** [comment]
Hi @Aghorb, its possible to add members of cluster post initialization. Please read Raft docs here: https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md#initial-configuration-and-enacting-membership-changes. IBFT follow regular geth commands, tho inacting changes in validators is a bit more involved.

**Comment by diestrin** [comment]
This document no longer exists

**Comment by chris-j-h** [comment]
Hi - this info can now be found on our docs site: https://docs.goquorum.com/en/latest/Consensus/raft/#initial-configuration-and-enacting-membership-changes
