### ISSUE TITLE
Getting bad block exception in geth logs and geth quits

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/quorum#548]
#### System information

Version: 1.7.2-stable
Quorum Version: 2.1.0
Architecture: amd64
Network Id: 1337
Go Version: go1.9.3
Operating System: linux

#### Expected behaviour
Quorum should start

#### Actual behaviour
Showing BAD BLOCK exception and geth **exits**
2018-10-07 04:21:29,347 DEBG 'geth' stdout output:
ERROR[10-07|04:21:29] 
########## BAD BLOCK #########
Chain config: {ChainID: 2018 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 1 IsQuorum: true Engine: unknown}

Number: 2566
Hash: 0x7a20a5935a8dae00ba9cf375f96cff56f55432898243cb005660fe23a4299424
receipt{status=1 cgas=0 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}

Error: invalid receipt root hash (remote: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c local: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0)
##############################

2018-10-07 04:21:29,351 DEBG 'geth' stdout output:
panic: failed to extend chain: invalid receipt root hash (remote: 703c035562d8e37c66f2f9461219b45c710e59c8d0d234f6b062107de627758c local: b64408da6b8fe39ab764af88ece1e8cca1c35fd988db57806e99138c629365a0)

goroutine 130 [running]:
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).applyNewChainHead(0xc4202591e0, 0xc4203f7710)
/quorum-2.1.0/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:876 +0x898
github.com/ethereum/go-ethereum/raft.(*ProtocolManager).eventLoop(0xc4202591e0)
/quorum-2.1.0/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:730 +0x5e5
created by github.com/ethereum/go-ethereum/raft.(*ProtocolManager).startRaft
/quorum-2.1.0/build/_workspace/src/github.com/ethereum/go-ethereum/raft/handler.go:485 +0x789

2018-10-07 04:21:29,370 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 140624303110264 for <Subprocess at 140624303356240 with name geth in state RUNNING> (stdout)>
2018-10-07 04:21:29,370 INFO exited: geth (exit status 2; expected)

**Comment by SatpalSandhu61** [comment]
Can you post details of the transaction that is causing this to happen please?
There is a known issue that can cause this failure if the specified gas is marginally insufficient, so you could also try with a higher gas value.

**Comment by Himanshu-Pandey** [comment]
I am doing some transactions in parallel, all the transactions are private for all. These transactions are private contracts deployed dynamically.

**Comment by SatpalSandhu61** [comment]
Looking into this a bit further, I realise it's not the issue I was thinking of.
It's more likely related to issue #434 .
I suggest you you check out Quorum from master and running against that. I'm closing this issue for now, but please re-open it if the issue still occurs on master.
