### ISSUE TITLE
Quorum node panic when starting with local constellation node stopped

### ISSUE THREAD

**Issue by magooster** [Consensys-Incorporated/quorum#55]
#### System information

Geth version: `geth version`
Geth
Version: 1.5.0-unstable
Git Commit: 85327f743b9735c32ae9231cbdde509e243ba0df
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Linux ubuntu-xenial 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Branch, Commit Hash or Release: `git status`
HEAD detached at q1.0.1

#### Expected behaviour
Quorum node should generate a error/warning event that can be readily monitored. This is inconsistent with error handling if constellation node goes down after quorum node has started. If both Quorum and Constellation nodes are expected to be up then shouldn't Quorum node actively check status of its 'paired' Constellation node.

#### Actual behaviour
Quorum node fails to start with a panic

#### Steps to reproduce the behaviour
Start quorum node with local constellation node stopped.

#### Backtrace

nohup: appending output to 'nohup.out'
panic: MustNew error: Get http+unix://c/upcheck: dial unix qdata/tm7.ipc: connect: connection refused

goroutine 1 [running]:
panic(0xc20d20, 0xc4201d2b90)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/ethereum/go-ethereum/private/constellation.MustNew(0xc42000e00f, 0x8, 0xc42000e00f)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/constellation/constellation.go:76 +0x114
github.com/ethereum/go-ethereum/private.FromEnvironmentOrNil(0xd5bfeb, 0xe, 0x153bf40, 0xc420045ea0)
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:19 +0x52
github.com/ethereum/go-ethereum/private.init()
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/private/private.go:22 +0x67
github.com/ethereum/go-ethereum/core.init()
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/core/vm_env.go:165 +0xf4
github.com/ethereum/go-ethereum/cmd/utils.init()
	/home/ubuntu/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/cmd/utils/version.go:65 +0x76
main.init()
	github.com/ethereum/go-ethereum/cmd/geth/_obj/_cgo_import.go:6 +0x58

**Comment by tylobban** [comment]
Hi @magooster - in this case, since the quorum node has been set to expect a constellation node, but no constellation node is available, a panic error is thrown to indicate to the user that their set up is not as expected and hence needs to be addressed.  It is a different scenario (incorrect setup) to the case you highlight wherein constellation goes down at a later point (connectivity/node failure) and so is treated differently.  Of course we are open to improving the use of these components so happy to hear your thoughts (or review a PR).
