### ISSUE TITLE
How many Transaction manager and Enclave a node can have?

### ISSUE THREAD

**Issue by princesinha19** [Consensys-Incorporated/quorum#551]
I want to know how many transaction manager and enclave a node can have? If we create multiple account let's say 3 account in a single node as like ethereum using eth.accounts.create() then the private key and public key must be different for all the three account as in ethereum. I am new to Quorum.
So, My doubt is :-
1. Transaction manager and enclave will also be 3-3 ?
2. If there will be only one transaction manager and enclave then, how transaction processing is done in case of private transaction if we sent a transaction from account 1 to account 2 in the same node ?

**Comment by preetgsanand** [comment]
According to my understanding, private transactions are performed using constellation keys which are hosted by a constellation node. Each constellation node can host only one pair of keys for now (there might be a functionality for a node to host multiple key pair).

Each quorum node has a one to one mapping to a constellation node. So here is the depiction of the setup -:
Constellation Key Pair - Constellation Node - Quorum Node

In context of your question -:
1. One constellation node has only one transaction manager and enclave
2. Private transaction are not ethereum account specific but constellation key specific and we just established that constellation keys have a one to one mapping to quorum node. So if you all the accounts hosted in a single quorum node will be able to see all the private information queried from the constellation node of that quorum node.

**Comment by princesinha19** [comment]
Thanks @vince16 
So, if i will create multiple accounts in a single node network using eth.accounts.create() then all accounts will use same constellation key for private transactions ?

**Comment by princesinha19** [comment]
> ` So if you all the accounts hosted in a single quorum node will be able to see all the private information queried from the constellation node of that quorum node.`


From my perspective this is not good. If the account is different then the constellation (Transaction manager and Enclave) should be different.
**If it is not intended behavior then it should be solved.**

**Comment by SatpalSandhu61** [comment]
That is not correct. When you submit a private transaction, the 'privateFor' field specifies which accounts are party to that transaction.
I suggest you read the wiki section on private transactions: https://github.com/jpmorganchase/quorum/wiki/Transaction-Processing
The Tessera documentation gives more detail around how the transaction manager works: https://github.com/jpmorganchase/tessera

Instead of raising an issue for questions, then it's better for you to ask them on the Quorum Slack channel, where you'll find a large community of folks who can assist.

**Comment by preetgsanand** [comment]
@SatpalSandhu61 I think he is talking about ethereum accounts. When you perform private transactions, you do not mention ethereum accounts but you supply constellation public key which for the time being can only be one for one constellation node which makes it one for each quorum node. Correct me if I am wrong somewhere.

**Comment by princesinha19** [comment]
@vince16 you are right. This is the issue i want to raise.
@SatpalSandhu61 you didn't understood my problem. I have read `I suggest you read the wiki section on private transactions: https://github.com/jpmorganchase/quorum/wiki/Transaction-Processing` many times. Then only i have raised the issue.

**Comment by SatpalSandhu61** [comment]
Apologies, @vince16 is quite correct.
The privacy model implements privacy at the node level - not the account level. This is the expected behaviour.

**Comment by princesinha19** [comment]
@SatpalSandhu61 But can you please describe why it is so ? 
If there will be multiple Transaction manager and enclave then this issue might be solved.

> The privacy model implements privacy at the node level - not the account level. This is the expected behaviour.

I can think of many use cases where this behavior can harm overall system. So, the multiple account option like ethereum in the single node is of no use. Correct me if i am wrong.

**Comment by SatpalSandhu61** [comment]
It is something that we expect to do as a future enhancement to allow multiple transaction managers.
As a workaround I guess you could ensure the accounts are on different quorum nodes (you'd have to run extra nodes, each with a transaction manager).

**Comment by princesinha19** [comment]
So, @SatpalSandhu61 @fixanoid it's better to tag this issue as **enhancement**.

**Comment by fixanoid** [comment]
@princesinha19 At the moment Quorum node maps to a single private txn manager like @vince16 and @SatpalSandhu61 point out. We don't see this changing in the short term primarily because Quorum node is the one responsible for maintaining the actual state and txn manager is only responsible for passing payloads around the private parties.

Private and public states currently only exist inside Quorum client and its a single chain thus even the private state is represented across all private contracts for the given node (and all the accounts that belong to it) even if its communicating with many other nodes privately.

In the short term, we do have a set of enhancements in the txn manager space such as ability to support multiple keys (for example to use different key with different partner / use case) and we are thinking about supporting a single txn manager across several Quorum nodes. These enhancements are already on the roadmap and are ticketed on the tessera repo.

**Comment by princesinha19** [comment]
Okay. Thank you @fixanoid

**Comment by princesinha19** [comment]
> In the short term, we do have a set of enhancements in the txn manager space such as ability to support multiple keys (for example to use different key with different partner / use case) and we are thinking about supporting a single txn manager across several Quorum nodes. These enhancements are already on the roadmap and are ticketed on the tessera repo.

@fixanoid can you please send the ticket detail ?

**Comment by fixanoid** [comment]
@princesinha19 non-detailed road map is here: https://github.com/jpmorganchase/quorum/wiki/Product-Roadmap

@Krish1979 any way to expose our tessera todos?

**Comment by Krish1979** [comment]
@princesinha19 - Could you please elaborate on your use case on why you need each eth account to be linked to unique pair of transaction manager key ?

If you want to send transaction from one eth account to another in same node, then it doesn't even need quorum. Geth can do that using eth.sendTransaction({from: <<acct>>, to: <<acct>>, value:<'value'>})

@fixanoid - Hi Felix , I have added enhancement item to our Tessera repo,

https://github.com/jpmorganchase/tessera/issues/491

This will provide the ability for Quorum to continue transaction processing even if one Tessera node is down but it is not an enhancement to support a transaction manager key to ethereum account,.
Each Tessera node can support multiple key pairs even now but they are there for key rotation and NOT for account segregation.

**Comment by princesinha19** [comment]
> If you want to send transaction from one eth account to another in same node, then it doesn't even need quorum. Geth can do that using eth.sendTransaction({from: <>, to: <>, value:<'value'>})

@Krish1979 Yes, you are right i can use eth.sendTransaction but it will not make private transaction so anybody can see the transaction.

> Could you please elaborate on your use case on why you need each eth account to be linked to unique pair of transaction manager key ?

Actually I want to create multiple accounts in a single node. Consider, I have hosted one node so i can create any number of accounts through eth.accounts.create(). The accounts will be different for each user so that the transaction will be signed through their private key. Consider there are three accounts (A,B & C) are hosted in single node and the users of account don't want that third person will see transaction if A and B are transacting then we need to host multiple transaction manager and enclave.
(It can be a case with a company hosted a single node and allow user to do private transaction where there are 1000 number of users)

Also it will be needed in case anyone wants to create Consortium network.

**Comment by Krish1979** [comment]
@princesinha19 - I don't see that as not a valid use case using Quorum. All accounts in a node are privy to transactions in their transaction manager.

**Comment by princesinha19** [comment]
@Krish1979 I am making a system where user can create accounts. For that purpose i don't have so much system/resources to create separate node for each user. I will provide feature for private transactions using Quorum. 
Consider if a user in my system do private transaction to another user and third person got the payload so able to see transactions. Which is from my perspective is not right. Correct me if i am wrong.

**Comment by princesinha19** [comment]
> jpmorganchase/tessera#491
> 
> This will provide the ability for Quorum to continue transaction processing even if one Tessera node is down but it is not an enhancement to support a transaction manager key to ethereum account,.
> Each Tessera node can support multiple key pairs even now but they are there for key rotation and NOT for account segregation.

@fixanoid I think it is not that things which we have discussed.

> In the short term, we do have a set of enhancements in the txn manager space such as ability to support multiple keys (for example to use different key with different partner / use case) and we are thinking about supporting a single txn manager across several Quorum nodes. These enhancements are already on the roadmap and are ticketed on the tessera repo.

I think this feature (multiple keys in a single transaction manager) should be added so please take a look and think what we can add.

**Comment by Krish1979** [comment]
@princesinha19 - like I said your use case is not valid to use Quorum and multiple txn manager supporting one geth node is only to enhance resiliency. We don't have a roadmap item to support multiple instance of txn manager supporting each geth account.

**Comment by princesinha19** [comment]
okay @Krish1979
