### ISSUE TITLE
Is it possible to replicate a private smart contract to a new node after the contract is deployed?

### ISSUE THREAD

**Issue by schatekar** [Consensys-Incorporated/quorum#552]
This is a question than an issue. If it is against the contributing guidelines to ask questions through issues, please let me know. I did not find anything in contributing guidelines hence posting a question here. 

I am exploring Quorum for a business use case. I have this peculiar situation where there is a private contract `Contract X` shared between `Node A` and `Node B`. A new node `Node C` joins the network. `Node C` needs to have access to the private contract `Contract X` which is already deployed on `Node A` and `Node B`.

Is there any way to get `Contract X` along with its current state on `Node C`?

I know that if I have access to the source code or ABI of `Contract X`, I can just deploy `Contract X` on `Node C`. However, as per my understanding, this will give `Contract X` on `Node C` a different address than what it has on the other nodes. So any transaction I send to all three nodes targeting `Contract X` with fail on `Node C`.

**Comment by fixanoid** [comment]
@schatekar the board is for everything, feel free to ask questions.

Quorum v2.1 currently does not support this -- a private contract shared on A and B cannot be extended to node C -- we have a solution that we are working on but this is still pretty early in the pipeline.

Our recommendation for when you need to add participants is to create a new contract Z with A, B, and C nodes, move the data over through a private txn on that contract, and then finally kill the original X.

**Comment by schatekar** [comment]
Am I right that the job of moving the data needs to be done from outside of the network by using a combination of querying the state of the current contract and sending a number of private transactions to all three nodes till all of them have the same state as the previous contract?

**Comment by fixanoid** [comment]
@schatekar that is correct at the moment.

**Comment by jiten-balla** [comment]
@fixanoid any update on this issue

**Comment by fixanoid** [comment]
Hi @jiten-balla this is still being very actively worked on. Expect a release in the next several months that adds private smart contract provenance extension to new nodes.

**Comment by RubensGitHub** [comment]
Hi, are there any news on this?

**Comment by 0xrubes** [comment]
hi @fixanoid, is there an update on this?

**Comment by fixanoid** [comment]
> hi @fixanoid, is there an update on this?

This is still being worked on. We're currently looking at EOY release that will cover this.

**Comment by jatinbhadra-vakt** [comment]
Hello @fixanoid , wonder if any update on this?

**Comment by antonydenyer** [comment]
This was released in https://github.com/ConsenSys/quorum/releases/tag/v2.7.0 you can find the documentation for it [here](https://consensys.net/docs/goquorum/en/latest/concepts/privacy/contract-extension/)
