### ISSUE TITLE
What is "isQuorum" key in genesis file?

### ISSUE THREAD

**Issue by nandakishorebhandari** [Consensys-Incorporated/quorum#553]
What is "isQuorum" key in genesis file?

What happens if  "isQuorum" is set to false?

What happens if  "isQuorum" is set to default (true)?

**Comment by fixanoid** [comment]
Hi @nandakishorebhandari how are you?

isQuorum is a flag in the config to hint that Quorum engine should be used. It was **required** and used in Quorum v1.x and there are uses for it in Quorum v2.x but its **not a requirement** to have it in the genesis file anymore.

**Comment by nandakishorebhandari** [comment]
doing good, thanks :)

Could you also clarify below observations @fixanoid 

What I observed is, setting isQuorum to TRUE, will allow gasless transactions and throws an error "gas not 0" if gas is mentioned in transactions.

Setting isQuorum to FALSE will allow transactions with gas.

Are there any other side effects other then allowing gas based transactions if isQuorum is to FALSE?
