### ISSUE TITLE
Signed transactions works only if gas is enabled (Setting isQuorum flag to true)

### ISSUE THREAD

**Issue by nandakishorebhandari** [Consensys-Incorporated/quorum#558]
#### System information

Geth version: `v1.7.2`

OS & Version: Linux

Branch, Commit Hash or Release: `v2.0.0`

#### Issue
Sending signed transaction getting failed when gas is disabled in the network and works when gas is enabled.

#### Expected behaviour
Signed transactions should work even when gas is disabled in network

#### Actual behaviour
When gas is disabled, in Web3 getting "nonce too low" & in geth logs, getting "out of gas" error.
When gas is enabled, no error is thrown and transaction got hashed successfully, 

#### Steps to reproduce the behaviour
    const keyJSON = fs.readFileSync(keyFile, 'utf8')
    const keyObj = JSON.parse(keyJSON)
    const password = ''
    const privateKey = keythereum.recover(password, keyObj)
    var nonce = await web3.eth.getTransactionCount(fromAcct)
    var nonceHex = '0x0' + nonce.toString(16).toUpperCase()

    let txParams = {
        nonce: 0x00,
        gas:'0x00',
        gasPrice: '0x00',
        gasLimit: '0x47b760',
        to: toAcct,
        value: '0x01'
    }
   
   const tx = new EthereumTx(txParams)

    tx.sign(privateKey)
    const serializedTx = tx.serialize()
    var rawTx = '0x' + tx.serialize().toString('hex')
    var sentTx = await web3.bxm.sendSignedTransaction(rawTx)

#### Backtrace

````
Geth logs:
DEBUG[10-23|12:58:30] Transaction failed, account skipped      hash=f9f20a…66db85 err="out of gas"

At web3, getting connection timeout and request is in pending transactions.

````

**Comment by nandakishorebhandari** [comment]
Issues fixed:
 By removing this field " gas:'0x00'," from tx params, the signed transaction worked for both gas and without the gas network.

Let me know, if this is correct?

**Comment by fixanoid** [comment]
This is correct: it lets the client pick the gas needed. A note is that only public txns may be done outside of the client.
