### ISSUE TITLE
A maker who is also a voter can vote twice for a block

### ISSUE THREAD

**Issue by magooster** [Consensys-Incorporated/quorum#56]
#### System information

Geth version: `geth version`

Geth
Version: 1.5.0-unstable
Git Commit: 85327f743b9735c32ae9231cbdde509e243ba0df
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Linux ubuntu-xenial 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Branch, Commit Hash or Release: `git status`
q1.0.1

#### Expected behaviour
A maker who is also a voter should only vote once for a particular block.

#### Actual behaviour
The maker nodes can vote twice, once when creating a block and again when a ChainHeadEvent occurs.

#### Steps to reproduce the behaviour
Using the 7-node example - with no other transactions the maker node will have generated twice as many vote transactions as the two other voting nodes.

See: block_voting.go case core.ChainHeadEvent and case CreateBlock.

#### Backtrace

````
[backtrace]
````

**Comment by gsalgado** [comment]
But in the CreateBlock case a block maker will only vote if createBlock() returns an error, which shouldn't happen as long as the node is properly configured and has been added as a block maker with the smart contract.

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/266
