### ISSUE TITLE
IBFT - Problem with Quorum 2.1.0 and only one validator

### ISSUE THREAD

**Issue by marcosio** [Consensys-Incorporated/quorum#560]
#### System information

Geth version: `2.1.1`

OS & Version: Ubuntu Linux x64

Branch, Commit Hash or Release: `0d0c507a5945ab63c8441007f022a143e2418f1e`

#### Expected behaviour

When I create a new network the first node must be online for a long time.

#### Actual behaviour

After a few minutes, the geth process consumes all memory and stops.

#### Steps to reproduce the behaviour

The sequence is:
1. `geth init` for initialize the data directory with this [genesis.json](https://github.com/alastria/alastria-node/blob/testnet2/data/genesis.json) and this [script](https://github.com/alastria/alastria-node/blob/testnet2/scripts/init.sh).
2. copy the nodekey who is included in validator's set. (We configure only one validator on the network)
3. [start](https://github.com/alastria/alastria-node/blob/testnet2/scripts/start.sh) the node as a miner.

We test this with Quorum 2.1.0, 2.1.1 and the merged version of pull request #542 `e679587e1f0059ff931d8a88f373b5336d25037a` commit.

With Quorum 2.1.0 or 2.1.1 the node stops in few minutes.

With #542 stay up during 12-24 hours.

EDIT - 20181026: Include memory profiling.
[memProfile_20181026071934.log](https://github.com/jpmorganchase/quorum/files/2518169/memProfile_20181026071934.log)

**Comment by jbhurat** [comment]
Hi @marcosio, from the attached mem prof, I see that the issue is happening during unlocking the account. Is it possible for you to test without providing the `--unlock 0` option and see if you get better result.

**Comment by marcosio** [comment]
Hi @jbhurat. we remove the flag and, test again.
The behavior of the node has not changed much.  The flags introduced in the node are:
```
geth --datadir /home/ubuntu/alastria/data --networkid 83584648538 --identity VAL_Alastria_Telsius_2_8_0_0 --permissioned --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --rpcport 22000 --port 21000 --istanbul.requesttimeout 10000 --ethstats VAL_Alastria_Telsius_2_8_0_0:bb98a0b6442386d0cdf8a31b267892c1@netstats.telsius.alastria.io:80 --verbosity 3 --vmdebug --emitcheckpoints --targetgaslimit 18446744073709551615 --syncmode full --vmodule consensus/istanbul/core/core.go=5 --maxpeers 100 --mine --minerthreads 2 --memprofilerate 524288 --metrics
```

And I include another memory profile of the node in case it helps in something. 
[memProfile_20181026212404.log](https://github.com/jpmorganchase/quorum/files/2521034/memProfile_20181026212404.log)

**Comment by jbhurat** [comment]
Hi @marcosio, is there any call that triggers this. Is the node executing any RPC call. Can you also attach the logs here. 
Can you also try adding `--nodiscover` option to starting `geth`

**Comment by marcosio** [comment]
Hi @jbhurat, we stop the validator node, and init again the chain. 

We start the node with the merged version of pull request #542 `e679587e1f0059ff931d8a88f373b5336d25037a` commit.

From this moment, the validator node is on-line.

We will test the network with the flag `--nodiscover` for identifying if the memory still goes down (At this moment the machine with Ubuntu and Quorum node uses 905M of main memory and 65.6M of swap).

**Comment by jbhurat** [comment]
Hi @marcosio Do you still see this issue?

**Comment by marcosio** [comment]
Hi @jbhurat,

We have initialized the test-net again by removing the `unlock` flag and adding `nodiscover`.

The network is online since last October 29 without any problem.

Thanks for the help
