### ISSUE TITLE
Unable to deploy private contract with gas enabled (IsQuorum set to true in genesis file)

### ISSUE THREAD

**Issue by nandakishorebhandari** [Consensys-Incorporated/quorum#564]
#### System information

Geth version: v1.7.2

OS & Version: Linux

Branch, Commit Hash or Release: v2.0.0

#### Expected behaviour
The private contract should be deployed successfully

#### Actual behaviour
Getting Error
**"Error: The contract code couldn't be stored, please check your gas limit."**

#### Steps to reproduce the behaviour
It's a 3 node cluster with gas enabled
Deploying private contract from node 1 to node2

Execute below Contract from Node1
  var bytecode = "0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029";
    
    var simpleContract = new Contract(abi);

    simpleContract
        .deploy({
            data: bytecode,
            arguments: [123]
        })
        .send(
            {
                from: fromAcc ,
                gas: 100000,
                gasPrice: 1,
                privateFor:["TIaXPkgN/v7PPt/P89C4S4rWZF7W6wn5YhlWPE1M8wg="]    

                
            },
            function (error, transactionHash) {
                console.log(transactionHash, error);
            }
        )
        .on("error", function (error) {
            console.log(error);
        })
        .on("transactionHash", function (transactionHash) {
            console.log(transactionHash);
        })
        .on("receipt", function (receipt) {
            console.log(receipt.contractAddress); // contains the new contract address
        })
        .on("confirmation", function (confirmationNumber, receipt) {
            console.log(confirmationNumber, receipt);
        })
        .then(function (newContractInstance) {
            console.log(newContractInstance.options.address); // instance with the new contract address
        });

#### Backtrace
**After Executing the above contract transaction:**
**From WEB3:**
````

0 { blockHash: '0x5f6ffc4442379a67718f9e5c23c8a71b10a36e1dc236b72e41b52e94110cc4cb',
  blockNumber: 6262,
  contractAddress: '0x8C37e3C7635c24015EA93e77981B33a2721bCAcE',
  cumulativeGasUsed: 2000000,
  from: '0xca843569e3427144cead5e4d5999a3d0ccf92b8e',
  gasUsed: 2000000,
  logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  root: '0x49da9a55b9661f028f10be585b81c7f1bcc5c5acdae985814bd30b3a08c680f4',
  to: null,
  transactionHash: '0x7b5c94290142c1edc6775067357976573415a071dbe2ee8c0e9e06697c8fdf00',
  transactionIndex: 0,
  events: {} }
Error: The contract code couldn't be stored, please check your gas limit.



````
**Participating Node 2: **
```
TRACE[11-08|11:20:20] << NEIGHBORS/v4                          addr=204.236.250.119:30301 err=nil
TRACE[11-08|11:20:20] Discarding invalid transaction           hash=7b5c94…8fdf00 err="transaction underpriced"
WARN [11-08|11:20:20] Failed to verify proposal                address=0x88Fd64a4dFa13EE37D7BeE60D4dd9072cF18EeE5 from=0x1b8E739591D8E4Cc8149392841D616279109a2eD state="Accept request" err="block in the future"                         duration=5.889391ms
```

**Comment by nandakishorebhandari** [comment]
I feel , this issues is similar to https://github.com/jpmorganchase/quorum/issues/562

**Comment by SatpalSandhu61** [comment]
Hi,
The supplied gas is insufficient for that contract. I believe you need a minimum of around 112806.
Depending on which version of quorum you are using, the contract will either fail to load with that error message "check your gas limit", or you'll get the crash described in #562.
I'll close the issue, but feel free to re-open it if you can't get the contract to load with more gas.

**Comment by nandakishorebhandari** [comment]
@SatpalSandhu61, I even tried till 200000, still getting the same error.

I'm using v2.0.0

**Comment by SatpalSandhu61** [comment]
The simple contract that come with the 7-nodes example works fine for me, using 112806 gas.
I'm using v2.0.2 quorum. If you can paste the exact script you are using then I can double-check whether it works on 2.0.2 (the one you pasted at the top appears incomplete).

**Comment by nandakishorebhandari** [comment]
@SatpalSandhu61: Did you enabled gas by setting isQuorum to false?
I have checked, it works fine when GAS is disabled, But the issues is when GAS is enabled.

@SatpalSandhu61  Please check required data to reproduce the same.

**Quorum Settings:**
- **Enable gas by setting isQuorum, to FALSE in genesis file**
- Make sure to have one account funded with some balance using genesis file.
- Quorum version any of 2.0.0
- Consense used: Istanbul


**Steps to Reproduce:**

- Connect to your cluster
- Unlock default account   web3.personal.unlockAccount(web3.eth.accounts[0]);
- create PRIVATE contract 
`var a = web3.eth.accounts[2];
            var abi = [{ "constant": true, "inputs": [], "name": "storedData4", "outputs": [{ "name": "", "type": "uint256" }], "payable": false, "type": "function" }, { "constant": false, "inputs": [{ "name": "x", "type": "uint256" }], "name": "set", "outputs": [], "payable": false, "type": "function" }, { "constant": true, "inputs": [], "name": "get", "outputs": [{ "name": "retVal", "type": "uint256" }], "payable": false, "type": "function" }, { "inputs": [{ "name": "initVal", "type": "uint256" }], "payable": false, "type": "constructor" }];

            var bytecode = "0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029";

            var simpleContract = web3.eth.contract(abi);
            var simple = simpleContract.new(42, { from: a, data: bytecode, gas: 0x112806, gasPrice:0x1 ,privateFor:["1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg="] }, function (e, contract) {
                if (e) {
                    console.log("err creating contract", e);    
                } else {
                    if (!contract.address) {
                        console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
                    } else {
                        console.log("Contract mined! Address: " + contract.address);
                        console.log(contract);
                        return contract;
                    }
                }
            });`

**Expected**:
contract should be deployed successfully like in non gas enabled network

**Actual**:
Gettng below error:

Web3 logs:
`err creating contract Error: The contract code couldn't be stored, please check your gas amount.
    at Object.callback (contract.js:142)
    at method.js:165
    at requestmanager.js:163
    at XMLHttpRequest.request.onreadystatechange (httpprovider.js:141)`

Geth logs:
`DEBUG[11-12|12:37:11] VM returned with error                   err="invalid opcode 0xc"`

**Comment by SatpalSandhu61** [comment]
Is there any particular reason you are setting isQuorum to false? It needs to be set to true if you want support for private transactions. If you set isQuorum to true then you'll find your contract will work if you do either of the following:
- set gasPrice to zero
- make the contract public (by removing privateFor)
Note that there's no point in setting gasPrice to non-zero on a private contract as Quorum doesn't actually deduct any ether for creating/running private contracts.

**Comment by nandakishorebhandari** [comment]
@SatpalSandhu61 

Thanks for the confirmation. 

Could you please also confirm:

**Set isQuorum to TRUE**: 

- Will  force to set gasPrIce to zero & enable private transactions with zero gas price only.
- No mining rewards

**Set isQuorum to FALSE:** 

- Will allow to set gasPrice to any value  & enable private transactions by setting gasPrice to zero only. 
- Miner rewords only for non private transactions

**Comment by SatpalSandhu61** [comment]
That's mostly correct:
Setting isQuorum to false will not allow private transactions to work correctly, so the following is not correct:
"enable private transactions by setting gasPrice to zero only"
In this case, even if you set the gasPrice to zero, private transactions won't work.

**Comment by fixanoid** [comment]
Just to add: this is a non fatal error. Ethereum has a limit to how big the
contract code can be, and when it's over, the source of the contract is not
stored, tho the contract is executed and is in the chain.
