### ISSUE TITLE
A minted transaction has consumed 0 gas

### ISSUE THREAD

**Issue by marcosio** [Consensys-Incorporated/quorum#566]
#### System information

Geth version: `geth version`

Geth version: 1.7.2-stable.
Quorum version: v2.0.2

OS & Version: Ubuntu Linux

Branch, Commit Hash or Release: `git status`

commit: df4267a25637a5497a3db9fbde4603a3dcd6aa14

#### Expected behaviour

When we call to a node with a transaction with 0 gas, it will be rejected.

#### Actual behaviour

In Alastria test-net `Arrakis` we got transactions with 0 gas in our BlockExplorer.

[This is the link to the issue](https://github.com/alastria/alastria-node/issues/304).

**Comment by jbhurat** [comment]
@marcosio I looked at the linked issue and it is working as expected. In quorum gas is disabled and is only required to prevent infinite loops. If you have noticed, even though gas is used, it is refunded back and this can be validated by running `eth.getBalance()` function against the account.

The first transaction in the linked issue is a private transaction and can be identified by the `v` parameter whose value is `37`. For private transactions we do not want to leak any information including gas used, hence the value you see is 0 where as for public transactions you see gas used. Gas price is both the instance is 0.
