### ISSUE TITLE
Pending Transactions issue

### ISSUE THREAD

**Issue by getsachmail** [Consensys-Incorporated/quorum#568]
#### System information
Geth version: `geth version`
Geth
Version: 1.7.2-stable
Git Commit: df4267a25637a5497a3db9fbde4603a3dcd6aa14
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Linux

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
Transactions going into pending Queue, even when one of the node is miner role. 

#### Actual behaviour
1. Transaction should not add to pending queue when one of node is miner
2. even if some transactions added to pending due to some data error, new transactions, which are not related to pending transaction and are from different smart contracts should mine

#### Steps to reproduce the behaviour
do not have root cause why some transactions are not able to mine, but will try to add logs in this ticket from Quorum

Temporary Solution:
stop the docker and deleted transactions.rlp file from node (for all nodes in private network) and restarted and pending transactions get cleared.  When we deleted transaction.rlp file from node which had done this transactions it not worked and need to do this for all private network node.

#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
What type of txns are these? Also, any reason you haven't upgraded to 2.1.1? There are several fixes that may affect this issue in the releases.

**Comment by teslashibe** [comment]
We are experiencing the sam issue as well. @fixanoid can you explain more about what you mean on upgrading to 2.1.1. 

Thanks

**Comment by glitch003** [comment]
Hi, I'm also experiencing this issue on v2.1.1 that I just deployed.  The first couple transactions will go through fine, then the rest are stuck pending.

**Comment by jpmsam** [comment]
Please provide more details on your network setup, consensus configuration and type of transactions that are getting stuck.

**Comment by fixanoid** [comment]
@teslashibe @glitch003 please open new issues with details such as version of Quorum, genesis config, and conditions of failure. Thank you.

**Comment by vinodreddy93** [comment]
The Transactions Are Showing Failed, But We Are Not Getting Any Receipt Regarding Failed Transactions And We Are Not Able To See In Pending Transactions Also
