### ISSUE TITLE
Voter nodes won't vote unless chain sync has occured

### ISSUE THREAD

**Issue by magooster** [Consensys-Incorporated/quorum#57]
In the setup of a new chain voter nodes wont vote unless a chain sync occurs.

#### System information

Geth version: `geth version`
Geth
Version: 1.5.0-unstable
Git Commit: 85327f743b9735c32ae9231cbdde509e243ba0df
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Linux ubuntu-xenial 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Branch, Commit Hash or Release: `git status`
q1.0.1

#### Expected behaviour
Voter node should vote for a block, when a ChainHeadEvent occurs in response to importing a new block provided they have synchronised with the chain (downloader.DoneEvent).

#### Actual behaviour
Voter nodes that are part of the initial chain never undertake a chain synchronisation, as by definition they are already in sync. They do still vote but only when a createBlock event occurs as a result of the fact they cannot create a block (See Issue #43) 

#### Steps to reproduce the behaviour
Code review block_voting.go 

```
case core.ChainHeadEvent: // got a new header, reset pending state
        bv.resetPendingState(e.Block)
        if bv.synced {
        number := new(big.Int)
                number.Add(e.Block.Number(), common.Big1)
                glog.Infof("ChainHeadEvent: Vote")
                if tx, err := bv.vote(number, e.Block.Hash()); err == nil {
                        if glog.V(logger.Debug) {
                                glog.Infof("Voted for %s on height %d in tx %s", e.Block.Hash().Hex(), number, tx.Hex())
                        }
                } else if glog.V(logger.Debug) {
                        glog.Errorf("Unable to vote: %v", err)
                }
        }

```

#### Backtrace

````
[backtrace]
````

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/266
