### ISSUE TITLE
[Question] How to recover private transactions

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/quorum#571]
How can we recover private transactions? 
Suppose we have backup till 1:00 and we restored it at 1:10 then what about the private transactions in 10 minutes. Is it possible to restore those?

**Comment by Krish1979** [comment]
@Himanshu-Pandey - Private transactions could be recovered using /resend API from other nodes which were also party to the transaction. It is to recover data loss when the dB of local node crashed. In the above example if the node was down till 1:10, any transactions where the local node were party would have failed anyway, so there is no need to a further sync till 1:10. The backup till 1:00 should suffice. Could you please provide us with the use case where it will deviate fro this behaviour ?

**Comment by Himanshu-Pandey** [comment]
@Krish1979 thanks for your reply. I am using constellation and not tessera. Is the resend api still there for it?

**Comment by fixanoid** [comment]
@Himanshu-Pandey its there, but the main difference between constellation is that you'll have to trigger / request /resend manually vs tessera that will do this upon startup.
