### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by samcrowindia** [Consensys-Incorporated/quorum#573]
#### System information

Geth version: `geth version`
Geth
Version: 1.7.2-stable
Git Commit: 01195280b4d8d9c91df7c500c74898f01c38209e
Quorum Version: 2.0.2
Architecture: amd64
Network Id: 1
Go Version: go1.9.1
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Ubuntu
Branch, Commit Hash or Release: `git status`

#### Expected behaviour
geth should process all transaction 

#### Actual behaviour
Geth crashes and runs out of memory

TRACE[11-16|09:47:10] New dial task                            task="wait for dial hist expire (29.704469526s)"
**fatal error: runtime: out of memory**

runtime stack:
runtime.throw(0x10744b9, 0x16)
	/usr/local/go/src/runtime/panic.go:605 +0x95
runtime.sysMap(0xc7b7400000, 0x10000000, 0xc420001200, 0x1aed318)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x1ad39e0, 0x10000000, 0x7fa90d15ace8)
	/usr/local/go/src/runtime/malloc.go:470 +0xd7
runtime.(*mheap).grow(0x1ad39e0, 0x8000, 0x0)
	/usr/local/go/src/runtime/mheap.go:887 +0x60
runtime.(*mheap).allocSpanLocked(0x1ad39e0, 0x8000, 0x1aed328, 0x0)
	/usr/local/go/src/runtime/mheap.go:800 +0x334
runtime.(*mheap).alloc_m(0x1ad39e0, 0x8000, 0xffffffffffff0101, 0x7fa90d15add8)
	/usr/local/go/src/runtime/mheap.go:666 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:733 +0x4d
runtime.systemstack(0x7fa90d15add0)
	/usr/local/go/src/runtime/asm_amd64.s:360 +0xab
runtime.(*mheap).alloc(0x1ad39e0, 0x8000, 0xc420010101, 0x7fa90c094200)
	/usr/local/go/src/runtime/mheap.go:732 +0xa1
runtime.largeAlloc(0x10000000, 0x7fa90d150101, 0x45dd3e)
	/usr/local/go/src/runtime/malloc.go:827 +0x98
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:722 +0x46
runtime.systemstack(0xc42001a000)
	/usr/local/go/src/runtime/asm_amd64.s:344 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1125

#### Steps to reproduce the behaviour
Deploy any smart contact and push 400 transactions or more from a load testing tool like Jmeter.Transactions are submitted from multiple threads concurrently

#### Backtrace

````
[backtrace]
````

**Comment by chrisciszak** [comment]
Same here, it's super unreliable.

**Comment by jpmsam** [comment]
Raft or Istanbul? We fixed a memory leak in Istanbul in 2.1 so you should consider upgrading but we only noticed it in network with more than 100k blocks. If you can provide a script and network setup details(number of nodes, server config, OS...) for us to replicate it, that might help.

**Comment by chrisciszak** [comment]
Raft :(

**Comment by fixanoid** [comment]
As mentioned, please upgrade to latest Quorum: v2.1.1 or master. There were several fixes that address out of memory errors.
