### ISSUE TITLE
Who spends resources while contracts execution?

### ISSUE THREAD

**Issue by Eugene282** [Consensys-Incorporated/quorum#574]
#### System information

Geth version: `geth version` - 2.1.1
OS & Version: Windows/Linux/OSX - Debian 9

#### Questions

When we send tx to a contract (i.e. call a contract's method) requesting specific quorum node - we see that 200mb of memory is allocated (it is released in 10 minutes).

1. Is it possible to reduce such big memory preallocation? (may be there are some constants in sources, we can change by ourselves)?
2. Assuming contracts are executed on every node - why we see resources (i.e. memory) consumption only for those node, which we request (regardless if it is a validator or not)?
3. What is stored in block.coinbase solidity global variable?

**Comment by prd-fox** [comment]
Hi Eugene,

1. There are a number of caches geth uses, and can be adjusted to fit your needs. See [here](https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options) under "PERFORMANCE TUNING OPTIONS"

2. Not entirely sure I understand the question, but important to note that not every node executes a private contract. All nodes process the transaction, and if that transaction is meant to call a private contract, that will only happen on the nodes who have access, which does not depend on whether it is a validator or not (from this I assume you are using IBFT?)

3. A nodes coinbase is the address that is used when minting blocks. This address is accessible inside a contract, so your contract can tell who created the block.

Hope this helps! If you want more explanation on these points or have other questions, feel free to reach out.

**Comment by Eugene282** [comment]
Thanks. Just couple of additional questions.

2. I've meant regular contracts (not private ones). And if each node executes contracts - then why much of memory is allocated only on the node, which accepts a client request?
(I played with command line options - looks like there was no impact)

3. Does coinbase have any practical sense (excepting curiosity purposes)? Meaning that any of validators on each round of consensus may be chosen as a minter. And minter spends same resources as other validators. Doesn't it?

**Comment by prd-fox** [comment]
I don't know why there is such a large allocation of memory off the top of my head.
The main difference is that the node that accepted the transaction has to establish a connection to the client (to accept the data for the tx) and perform signing and other transaction creation operations, which the other nodes do not. Whether that is 200mb worth of memory I do not know.
Is this allocation causing an issue?

The practicality of the using the coinable comes inside the contracts and DApps when using a Proof of Work consensus engine. It will tell you which address collected the block reward (some Ether), but this is not used in the consensus engines available in Quorum, so it is just a curiosity as you say.
You are right that the minter spends about the same resources (give or take a little bit) as other validators.

**Comment by Eugene282** [comment]
I found the solution. 

The reason of memory allocation was the scrypt's algorithm parameters. Scrypt is used to generate AES keys (against user password) for user private key encryption. The settings are stored in key-file. And by default (for Ethereum and Quorum) they are such as (pay attention to kdfparams):

```
{"address":"0709833ca65d49c0ece401b2759b58f2e6b8fe37","crypto":{"cipher":"aes-128-ctr","ciphertext":"2eb79daec5a3eb25828396739103fcc9b8a
af0cb93793a65ed57f71f1c147794","cipherparams":{"iv":"306ed34ca11a76ebe7bc85335d6a05b4"},"kdf":"scrypt","kdfparams":{"dklen":32,"n":26214
4,"p":1,"r":8,"salt":"18b5d5acec54f78c32b53a059a610681590129984c88ab3955454bfff984d62e"},"mac":"dafc975a52153219444dbf7ddfa9ff1e9b24b849
7e9fe25a19a47949da80f06f"},"id":"3c5d219d-e3b1-4173-a232-98bcfca53b9f","version":3} 
```            

Memory consumed may be calculated by formula:
`Bytes_of_memory = 128 * kdf.r * kdf.N`

**So for N=262144 and r=8 it will be 256Mb**

Conclusion. **To developers**:

There is no way to change these values in already created key-file, but you can write your own keyfile-creation code for your clients/customers as a service or as a part of your application. Using your own kdf settings. 

For our purposes we just changed it inside quorum source code.

In theory, making these settings more weak, simplifies attack on the cryptotext. But that part of algorithm is responsible only for key enthropy. It means if your/user password is strong itself (long and random), you may use more light version of the settings. (For example, for lightcoin blockchain it is N=1024 and r=1).

And, by the way, it impacts on speed of unlocking/signing transactions. So, if you use self-signed transactions, you may play with these values and see the effect.
