### ISSUE TITLE
make all fails

### ISSUE THREAD

**Issue by tamal-appsbee** [Consensys-Incorporated/quorum#578]
#### System information
vagrant-ubuntu-trusty-64 virtualbox
go version go1.11.2 linux/amd64

#### Backtrace
goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc01371e050 sp=0xc01371e048 pc=0x454b90
runtime.(*mcache).nextFree(0x2b4ecb6d0000, 0x5, 0x628ba0, 0x30, 0x28)
	/usr/local/go/src/runtime/malloc.go:748 +0xb6 fp=0xc01371e0a8 sp=0xc01371e050 pc=0x40b106
runtime.mallocgc(0x9, 0x0, 0xc013ffe600, 0x0)
	/usr/local/go/src/runtime/malloc.go:879 +0x5b4 fp=0xc01371e148 sp=0xc01371e0a8 pc=0x40b874
runtime.slicebytetostring(0x0, 0xc000c3719a, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:102 +0x9f fp=0xc01371e178 sp=0xc01371e148 pc=0x443f3f
cmd/link/internal/ld.decodetypeName(0xc00302e9c0, 0x98, 0x1, 0xc013ffe6f0)
	/usr/local/go/src/cmd/link/internal/ld/decodesym.go:244 +0xbe fp=0xc01371e1b8 sp=0xc01371e178 pc=0x5476ee
cmd/link/internal/ld.decodetypeStructFieldName(0x7d1c20, 0xc00302e9c0, 0x3, 0x12, 0x1)
	/usr/local/go/src/cmd/link/internal/ld/decodesym.go:249 +0x83 fp=0xc01371e1e8 sp=0xc01371e1b8 pc=0x5477c3
cmd/link/internal/ld.newtype(0xc0004d2000, 0xc00302e9c0, 0xc013fe68c0)
	/usr/local/go/src/cmd/link/internal/ld/dwarf.go:527 +0x1084 fp=0xc01371e3c0 sp=0xc01371e1e8 pc=0x54b8d4
cmd/link/internal/ld.defgotype(0xc0004d2000, 0xc00302e9c0, 0x5)
	/usr/local/go/src/cmd/link/internal/ld/dwarf.go:393 +0x1cc fp=0xc01371e460 sp=0xc01371e3c0 pc=0x54a64c
cmd/link/internal/ld.defdwsymb(0xc0004d2000, 0x0, 0xc000018670, 0xb, 0x7fcb61, 0x30, 0xc00302e9c0)
	/usr/local/go/src/cmd/link/internal/ld/dwarf.go:861 +0x17c fp=0xc01371e4c8 sp=0xc01371e460 pc=0x54f54c
cmd/link/internal/ld.genasmsym(0xc0004d2000, 0x657eb0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:2160 +0x919 fp=0xc01371e5e8 sp=0xc01371e4c8 pc=0x577939
cmd/link/internal/ld.dwarfgeneratedebugsyms(0xc0004d2000)
	/usr/local/go/src/cmd/link/internal/ld/dwarf.go:1749 +0x70f fp=0xc01371e7d0 sp=0xc01371e5e8 pc=0x55769f
cmd/link/internal/ld.(*Link).dodata(0xc0004d2000)
	/usr/local/go/src/cmd/link/internal/ld/data.go:1585 +0x3344 fp=0xc01371ece8 sp=0xc01371e7d0 pc=0x53d344
cmd/link/internal/ld.Main(0x7d1c20, 0x10, 0x20, 0x1, 0x7, 0x10, 0x64edf0, 0x1b, 0x64bf34, 0x14, ...)
	/usr/local/go/src/cmd/link/internal/ld/main.go:232 +0xb44 fp=0xc01371ee80 sp=0xc01371ece8 pc=0x5833f4
main.main()
	/usr/local/go/src/cmd/link/main.go:65 +0x227 fp=0xc01371ff98 sp=0xc01371ee80 pc=0x5db527
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc01371ffe0 sp=0xc01371ff98 pc=0x42bae7
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc01371ffe8 sp=0xc01371ffe0 pc=0x456af1
/usr/local/go/pkg/tool/linux_amd64/link: signal: killed
util.go:44: exit status 2
exit status 1
make: *** [all] Error 1

````
[backtrace]
````

**Comment by fixanoid** [comment]
Hi @tamal-appsbee. Current master branch should work on go 1.9 and will have issues with newer go. If you want to build with your current config, please switch to our 1.8.12 working branch: https://github.com/jpmorganchase/quorum/pull/542. Alternatively, please install go 1.9

**Comment by tamal-appsbee** [comment]
Ok Thanks
