### ISSUE TITLE
Can't create contract

### ISSUE THREAD

**Issue by jaguarg** [Consensys-Incorporated/quorum#58]
Hi, 
Is there a way to check why my contract creation is not happening ? 
This is what I get in the node logs 

`I0214 13:17:24.973787 internal/ethapi/api.go:1196] Tx(0xb26b50ed3454338f9245bbfac35c44b5293393dd51f8435cb7b530ee6fdddb0f) created: 0x573723618e03ab2d9e6dc3a445894603163cb81c
`
But when I query the Tx:

```
>eth.getTransaction("0xb26b50ed3454338f9245bbfac35c44b5293393dd51f8435cb7b530ee6fdddb0f")
null
```

I wonder if the node I am initiating the transaction from need to be a blockmaker node? Does it mean that no transaction should be created from observer nodes ?

I noticed that even simple transactions (eth transfer between account) don't work from this node. 

Thanks

**Comment by tylobban** [comment]
@jaguarg - Are you using the 7nodes example, and if so, what node are you sending transactions from? Per the later issue you've raised, Transactions should be sent to your local node, which does not need to be a maker.

Also note that Quorum does not support Eth.

**Comment by jaguarg** [comment]
all ok. i did rebuild my environment and working fine now .
