### ISSUE TITLE
Plans for eWASM?

### ISSUE THREAD

**Issue by alienatorZ** [Consensys-Incorporated/quorum#580]
Hello,

I am interested in the development of QUORUM and using it in small testnet. Are there any plans to integrate eWASM into Quorum? 

Thank you!

**Comment by fixanoid** [comment]
Hi @alienatorZ, how are you? This is a general topic of interest for us as well, and at the moment we're beginning to evaluate solutions in this space. The work on this is expected to progress through 2019.
