### ISSUE TITLE
Unable to install Quorum

### ISSUE THREAD

**Issue by MANOJKUMARCH** [Consensys-Incorporated/quorum#589]
Hi, I am trying to install Quorum as given in below link.
https://github.com/jpmorganchase/quorum/wiki/Getting-Set-Up

But its not being installed and I am facing below issue. I am using go version go1.11.2 linux/amd64.

github.com/ethereum/go-ethereum/crypto/bn256/cloudflare.gfpMul: relocation target runtime.support_bmi2 not defined
util.go:45: exit status 2
exit status 1
Makefile:29: recipe for target 'all' failed
make: *** [all] Error 1

Could someone help on how to resolve this

**Comment by jbhurat** [comment]
Hi @MANOJKUMARCH Quorum does not support go1.11.x yet. Can you please try building quorum using go1.9.7
