### ISSUE TITLE
Nodes can execute a transaction multiple times.

### ISSUE THREAD

**Issue by magooster** [Consensys-Incorporated/quorum#59]
#### System information

Geth version: `geth version`
Geth
Version: 1.5.0-unstable
Git Commit: 85327f743b9735c32ae9231cbdde509e243ba0df
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Linux ubuntu-xenial 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Branch, Commit Hash or Release: `git status`
q1.0.1

#### Expected behaviour
A node should only execute a transaction once when processing a block, the exception would be blockmaker nodes.

#### Actual behaviour
As all Quorum nodes run the vote strategy they execute transactions to update their pending state when 
1) They enter the pool (core.TxPreEvent),
2) When blocks are received from peers
3) When a new block is inserted (core.ChainheadEvent)
4) When attempting to create a block (createBlock)

#### Steps to reproduce the behaviour
N/A - code review

block_voting.go  function run
case core.TxPreEvent - applies the transaction to the pending state
case core.ChainHeadEvent - resetof pending state - causing pending transactions to be executed.
case.CreateBlock - non blockmaker and voting nodes - reset of pending state 

state_processor.go function process

Process processes the state changes according to the Ethereum rules by running the transaction messages using the statedb and applying any rewards to both the processor (coinbase) and any included uncles.

#### Backtrace

````
[backtrace]
````

**Comment by obscuren** [comment]
This is normal Ethereum behaviour. Internally the following happens:

* Recv tx
* Apply transaction against the pending state / update (1)
* As a block maker you wait for T, take txs and apply against P state (2)
* Add block to block chain and, as a side effect, re-process the block (3)

(3) might be an issue and I'll take a look at that. The other two are intentional.

**Comment by magooster** [comment]
My bad... I can see the need to process transactions when, i) they enter the pool  (TxPreEvent), ii) when applying a 'generated' block and iii) when resetting the pending state after a new block has been imported (ChainHeadEvent), in order to maintain the local pending state.

But nodes that are neither Makers or Voters also reset their pending state, every block maker timeout (CreateBlock event) which I believe is a bug.

**Comment by obscuren** [comment]
No, this is not a bug; this is also intended for normal participants. This is because you can create filters for the *pending* state as well as *next* state.

Please let me know if I misunderstood you @magooster

**Comment by tylobban** [comment]
@magooster do you need any further clarification here?

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/266
