### ISSUE TITLE
Failed to resume previous blockchain and unlock account after reboot at 7nodes Istanbul example

### ISSUE THREAD

**Issue by csfl** [Consensys-Incorporated/quorum#594]
Hi here,

I am deploying istanbul protocol following these steps, but I cannot resume it to the previous state, I tried 3 times, every time the result is the same, please give me some instructions about deploying it.

Thanks a lot!

#### System information

Geth version: `1.7.2`

OS & Version: Ubuntu 18

Branch, Commit Hash or Release: `master`

#### Expected behaviour
run the example seamlessly,
run ./istanbul-start.sh to restart the example blockchain

#### Actual behaviour
1. the geth always stops working after about 2 hours, it stucks at:

-----------------------
Welcome to the Geth JavaScript console!

instance: Geth/v1.7.2-stable-99a83767/linux-amd64/go1.10.4
-----------------------

2. RPC works fine and I could get feedbacks that blockchain is still working.

3. after reboot, I went to 7nodes folder, cannot resume the former blockchain.

#### Steps to reproduce the behaviour
1.
./istanbul-init.sh
./istanbul-start.sh

2.
wait for about 2 hours, then can't do geth attach anymore

3.
reboot, and go to 7nodes folder, cannot resume the former blockchain.

#### Backtrace

/qdata/logs/1.log

Init:

INFO [12-10|05:43:36] Starting P2P networking 
INFO [12-10|05:43:36] Database deduplication successful        deduped=0
INFO [12-10|05:43:36] RLPx listener up                         self="enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000?discport=0"
INFO [12-10|05:43:36] HTTP endpoint opened: http://0.0.0.0:22000 
INFO [12-10|05:43:37] IPC endpoint opened: /root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc 
INFO [12-10|05:43:39] Unlocked account                         address=0xed9d02e382b34818e88B88a309c7fe71E65f419d

INFO [12-10|05:43:39] Unlocked account                         address=0xed9d02e382b34818e88B88a309c7fe71E65f419d

After reboot:

self="enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000?discport=0"
INFO [12-10|12:26:44] HTTP endpoint opened: http://0.0.0.0:22000 
INFO [12-10|12:26:44] IPC endpoint opened: /root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc 
Fatal: Failed to unlock account 0 (could not decrypt key with given passphrase)

**Comment by csfl** [comment]
I just tried again, if the time is not long enough, everything seems to work fine, after reboot I ran istanbul-start.sh and I can use "geth attach" to conncect the node. 
It seems to be something wrong with the configuration file or the password changes after a certain amount of time and I don't know why

**Comment by fixanoid** [comment]
Hi @csfl, are you running as the same user and in the same folder? Is this in the vagrant env or did you run this externally on the host? The error is pretty generic and there are no passwords to unlock in the 7nodes -- this error indicates an issue with nodes keystore.

**Comment by dmytronasyrov** [comment]
Try this. Attach to your node with geth. Your account[0] is not 0 anymore. It's the last one in the list of eth.accounts. Use account[n-1], where n number of accounts or keys in directory qdata/keystore.

**Comment by csfl** [comment]
> Hi @csfl, are you running as the same user and in the same folder? Is this in the vagrant env or did you run this externally on the host? The error is pretty generic and there are no passwords to unlock in the 7nodes -- this error indicates an issue with nodes keystore.

@fixanoid Hello, I am running as the same user, I found there is some problems with .sh file, and I fixed it with changing the environment variables of sudo. I simply run the 7 nodes example with constellation-nodes, with no modifications of the keystore or qdata.

**Comment by csfl** [comment]
After "Cannot set etherbase in Istanbul consensus" error, I experienced the same situation (cannot resume the blockchain after reboot):

/qdata/logs/1.log

INFO [12-12|09:07:01] Commit new mining work                   number=14586 txs=0 uncles=0 elapsed=320.626µs
ERROR[12-12|09:07:02] Cannot set etherbase in Istanbul consensus 
INFO [12-12|09:07:06] Committed                                address=0xd8Dba507e85F116b1f7e231cA8525fC9008A6966 hash=e94c67…e9b0af number=14586
INFO [12-12|09:07:06] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=5.170ms   mgasps=0.000 number=14586 hash=e94c67…e9b0af
INFO [12-12|09:07:06] Commit new mining work                   number=14587 txs=0 uncles=0 elapsed=7.194ms
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xfcb6ad, 0x16)
	/usr/lib/go-1.10/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc43dcf0000, 0x10000000, 0x1a9cdb7a1b11f800, 0x19e1838)
	/usr/lib/go-1.10/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x19c7f20, 0x10000000, 0x7f8f98668498)
	/usr/lib/go-1.10/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x19c7f20, 0x8000, 0x0)
	/usr/lib/go-1.10/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x19c7f20, 0x8000, 0x19e1848, 0x7f8f99ffad88)
	/usr/lib/go-1.10/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x19c7f20, 0x8000, 0xffffffffffff0101, 0x7f8f99ffadb8)
	/usr/lib/go-1.10/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/lib/go-1.10/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x19c7f20, 0x8000, 0xc420010101, 0xc420218800)
	/usr/lib/go-1.10/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x10000000, 0x19e0101, 0x7f8f98364e18)
	/usr/lib/go-1.10/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/lib/go-1.10/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x0)
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/lib/go-1.10/src/runtime/proc.go:1175

goroutine 943844 [running]:
runtime.systemstack_switch()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:363 fp=0xc428988dc0 sp=0xc428988db8 pc=0x45dfc0
runtime.mallocgc(0x10000000, 0xde5500, 0xc428988e01, 0xc4371b5000)
	/usr/lib/go-1.10/src/runtime/malloc.go:720 +0x8a2 fp=0xc428988e60 sp=0xc428988dc0 pc=0x416c22
runtime.makeslice(0xde5500, 0x4000000, 0x4000000, 0xc4371b5000, 0x200, 0x200)
	/usr/lib/go-1.10/src/runtime/slice.go:61 +0x77 fp=0xc428988e90 sp=0xc428988e60 pc=0x4480d7
github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt.Key(0xc43817f4e0, 0xe, 0x10, 0xc430c2e660, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/vendor/golang.org/x/crypto/scrypt/scrypt.go:235 +0x152 fp=0xc428988f50 sp=0xc428988e90 pc=0x66cf52
github.com/ethereum/go-ethereum/accounts/keystore.EncryptKey(0xc431bbdf40, 0xc43817f480, 0xe, 0x40000, 0x1, 0x2, 0x2, 0xc437888fc0, 0x8d, 0xc420280c00)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:114 +0x117 fp=0xc428989250 sp=0xc428988f50 pc=0x684947
github.com/ethereum/go-ethereum/accounts/keystore.keyStorePassphrase.StoreKey(0xc420280c00, 0x3f, 0x40000, 0x1, 0xc437888fc0, 0x8d, 0xc431bbdf40, 0xc43817f480, 0xe, 0xc437888fc0, ...)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore_passphrase.go:94 +0x60 fp=0xc4289892b0 sp=0xc428989250 pc=0x684680
github.com/ethereum/go-ethereum/accounts/keystore.(*keyStorePassphrase).StoreKey(0xc4201f5b00, 0xc437888fc0, 0x8d, 0xc431bbdf40, 0xc43817f480, 0xe, 0x67c219, 0xc42027e258)
	<autogenerated>:1 +0x9e fp=0xc428989318 sp=0xc4289892b0 pc=0x689f2e
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).importKey(0xc4202be000, 0xc431bbdf40, 0xc43817f480, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:458 +0x139 fp=0xc4289893a0 sp=0xc428989318 pc=0x683df9
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).ImportECDSA(0xc4202be000, 0xc42d42a3f0, 0xc43817f480, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/accounts/keystore/keystore.go:453 +0x186 fp=0xc428989490 sp=0xc4289893a0 pc=0x683bf6
github.com/ethereum/go-ethereum/internal/ethapi.(*PrivateAccountAPI).ImportRawKey(0xc4245a2f20, 0xc435e92040, 0x40, 0xc43817f480, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:317 +0x146 fp=0xc428989590 sp=0xc428989490 pc=0xb09d96
runtime.call128(0xc42d42a390, 0xc4245f8660, 0xc43aa3b860, 0x2800000050)
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:575 +0x52 fp=0xc428989620 sp=0xc428989590 pc=0x45e4a2
reflect.Value.call(0xc420564580, 0xc4245f8660, 0x13, 0xf9bbd9, 0x4, 0xc43aa3b810, 0x3, 0x3, 0x2, 0xc43aa3b810, ...)
	/usr/lib/go-1.10/src/reflect/value.go:447 +0x969 fp=0xc4289898e0 sp=0xc428989620 pc=0x4bc959
reflect.Value.Call(0xc420564580, 0xc4245f8660, 0x13, 0xc43aa3b810, 0x3, 0x3, 0x2, 0x2, 0x2)
	/usr/lib/go-1.10/src/reflect/value.go:308 +0xa4 fp=0xc428989948 sp=0xc4289898e0 pc=0x4bbed4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4205e2b40, 0x1167900, 0xc431bbde80, 0x116d2e0, 0xc43aa3b720, 0xc431bc2660, 0xc43aa3b7e0, 0x0, 0xe313e0)
|
|
|
goroutine 543800 [select]:
github.com/ethereum/go-ethereum/p2p.(*protoRW).ReadMsg(0xc433397880, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x42085113c8e1)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:398 +0x130
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc4201e53b0, 0xc42d274630, 0x0, 0x0)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:336 +0x9e
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).handle(0xc4201e53b0, 0xc42d274630, 0x0, 0x0)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:325 +0x798
github.com/ethereum/go-ethereum/eth.NewProtocolManager.func1(0xc4336a46c0, 0x115e8c0, 0xc433397880, 0x0, 0x0)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/handler.go:156 +0x1db
github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc433397880, 0xc4336a46c0, 0x115e8c0, 0xc433397880)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:344 +0x66
created by github.com/ethereum/go-ethereum/p2p.(*Peer).startProtocols
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/p2p/peer.go:343 +0x201

goroutine 943845 [IO wait]:
internal/poll.runtime_pollWait(0x7f8fc61c0af0, 0x72, 0xc42051e658)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc432953698, 0x72, 0xffffffffffffff00, 0x115cd80, 0x18dafd8)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc432953698, 0xc42d42a200, 0x1, 0x1)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc432953680, 0xc42d42a251, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc432953680, 0xc42d42a251, 0x1, 0x1, 0xc4200e0780, 0x1, 0x0)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc42d33ddf0, 0xc42d42a251, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a
net/http.(*connReader).backgroundRead(0xc42d42a240)
	/usr/lib/go-1.10/src/net/http/server.go:668 +0x5a
created by net/http.(*connReader).startBackgroundRead
	/usr/lib/go-1.10/src/net/http/server.go:664 +0xce

goroutine 543414 [select]:
github.com/ethereum/go-ethereum/miner.(*RemoteAgent).loop(0xc42026d780, 0xc420e53bc0, 0xc430ff91a0)
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/remote_agent.go:176 +0x3a6
created by github.com/ethereum/go-ethereum/miner.(*RemoteAgent).Start
	/root/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/miner/remote_agent.go:86 +0xd2
nohup: appending output to 'nohup.out'INFO [12-13|12:32:57] Starting P2P networking 
INFO [12-13|12:32:57] RLPx listener up                         self="enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000?discport=0"
INFO [12-13|12:32:57] IPC endpoint opened: /root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc 
INFO [12-13|12:32:57] HTTP endpoint opened: http://0.0.0.0:22000 
INFO [12-13|12:32:57] WebSocket endpoint opened: ws://[::]:23000 
INFO [12-13|12:33:00] Unlocked account                         address=0xed9d02e382b34818e88B88a309c7fe71E65f419d
INFO [12-13|12:33:00] Transaction pool price threshold updated price=18000000000
INFO [12-13|12:33:00] Starting mining operation 
INFO [12-13|12:33:00] Commit new mining work                   number=14593 txs=0 uncles=0 elapsed=660.2µs
nohup: appending output to 'nohup.out'
Fatal: Error starting protocol stack: datadir already used by another process
nohup: appending output to 'nohup.out'
INFO [12-13|12:35:12] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-99a83767/linux-amd64/go1.10.4
INFO [12-13|12:35:12] Allocated cache and file handles         database=/root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth/chaindata cache=128 handles=1024
INFO [12-13|12:35:12] Initialised chain configuration          config="{ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 0 EIP158: 3 Byzantium: 1 IsQuorum: true Engine: istanbul}"
INFO [12-13|12:35:12] Initialising Ethereum protocol           versions="[63 62]" network=10
INFO [12-13|12:35:12] Loaded most recent local header          number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:35:12] Loaded most recent local full block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:35:12] Loaded most recent local fast block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:35:12] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-13|12:35:12] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-13|12:35:12] Starting P2P networking 
INFO [12-13|12:35:12] RLPx listener up                         self="enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000?discport=0"
INFO [12-13|12:35:12] IPC endpoint opened: /root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc 
INFO [12-13|12:35:12] HTTP endpoint opened: http://0.0.0.0:22000 
INFO [12-13|12:35:12] WebSocket endpoint opened: ws://[::]:23000 
Fatal: Failed to unlock account 0 (could not decrypt key with given passphrase)
nohup: appending output to 'nohup.out'
INFO [12-13|12:36:00] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-99a83767/linux-amd64/go1.10.4
INFO [12-13|12:36:00] Allocated cache and file handles         database=/root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth/chaindata cache=128 handles=1024
INFO [12-13|12:36:00] Initialised chain configuration          config="{ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 0 EIP158: 3 Byzantium: 1 IsQuorum: true Engine: istanbul}"
INFO [12-13|12:36:00] Initialising Ethereum protocol           versions="[63 62]" network=10
INFO [12-13|12:36:00] Loaded most recent local header          number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:00] Loaded most recent local full block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:00] Loaded most recent local fast block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:00] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-13|12:36:00] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-13|12:36:01] Starting P2P networking 
INFO [12-13|12:36:01] RLPx listener up                         self="enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000?discport=0"
INFO [12-13|12:36:01] IPC endpoint opened: /root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc 
INFO [12-13|12:36:01] HTTP endpoint opened: http://0.0.0.0:22000 
INFO [12-13|12:36:01] WebSocket endpoint opened: ws://[::]:23000 
Fatal: Failed to unlock account 0 (could not decrypt key with given passphrase)
nohup: appending output to 'nohup.out'
INFO [12-13|12:36:29] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-99a83767/linux-amd64/go1.10.4
INFO [12-13|12:36:29] Allocated cache and file handles         database=/root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth/chaindata cache=128 handles=1024
INFO [12-13|12:36:29] Initialised chain configuration          config="{ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 0 EIP158: 3 Byzantium: 1 IsQuorum: true Engine: istanbul}"
INFO [12-13|12:36:29] Initialising Ethereum protocol           versions="[63 62]" network=10
INFO [12-13|12:36:29] Loaded most recent local header          number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:29] Loaded most recent local full block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:29] Loaded most recent local fast block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:29] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-13|12:36:29] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-13|12:36:29] Starting P2P networking 
INFO [12-13|12:36:29] RLPx listener up                         self="enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000?discport=0"
INFO [12-13|12:36:29] IPC endpoint opened: /root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc 
INFO [12-13|12:36:29] HTTP endpoint opened: http://0.0.0.0:22000 
INFO [12-13|12:36:29] WebSocket endpoint opened: ws://[::]:23000 
Fatal: Failed to unlock account 0 (could not decrypt key with given passphrase)
nohup: appending output to 'nohup.out'
INFO [12-13|12:36:53] Starting peer-to-peer node               instance=Geth/v1.7.2-stable-99a83767/linux-amd64/go1.10.4
INFO [12-13|12:36:53] Allocated cache and file handles         database=/root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth/chaindata cache=128 handles=1024
INFO [12-13|12:36:53] Initialised chain configuration          config="{ChainID: 10 Homestead: <nil> DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 0 EIP158: 3 Byzantium: 1 IsQuorum: true Engine: istanbul}"
INFO [12-13|12:36:53] Initialising Ethereum protocol           versions="[63 62]" network=10
INFO [12-13|12:36:53] Loaded most recent local header          number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:53] Loaded most recent local full block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:53] Loaded most recent local fast block      number=14592 hash=339f17…ea9a53 td=14593
INFO [12-13|12:36:53] Loaded local transaction journal         transactions=0 dropped=0
INFO [12-13|12:36:53] Regenerated local transaction journal    transactions=0 accounts=0
INFO [12-13|12:36:53] Starting P2P networking 
INFO [12-13|12:36:53] RLPx listener up                         self="enode://ac6b1096ca56b9f6d004b779ae3728bf83f8e22453404cc3cef16a3d9b96608bc67c4b30db88e0a5a6c6390213f7acbe1153ff6d23ce57380104288ae19373ef@[::]:21000?discport=0"
INFO [12-13|12:36:53] IPC endpoint opened: /root/quorum/quorum-examples/examples/7nodes/qdata/dd1/geth.ipc 
INFO [12-13|12:36:53] HTTP endpoint opened: http://0.0.0.0:22000 
INFO [12-13|12:36:53] WebSocket endpoint opened: ws://[::]:23000 
Fatal: Failed to unlock account 0 (could not decrypt key with given passphrase)

[1.log](https://github.com/jpmorganchase/quorum/files/2676192/1.log)

**Comment by fixanoid** [comment]
@csfl please pull from master and rebuild. This bug was addressed a few days ago.
