### ISSUE TITLE
Nonexistent dependency breaks 'go get' and vending as a dependency

### ISSUE THREAD

**Issue by Lsquared13** [Consensys-Incorporated/quorum#599]
Hi, I am encountering issues using portions of this project as a dependency and using `go get`. After looking into it, it appears that [this change](https://github.com/jpmorganchase/quorum/commit/bea1e6de1dc3a61b83793727c7fc932bd9522050) attempts to import constellation from the main ethereum repository. I don't understand the rationale behind the decision considering that the main ethereum repository doesn't use constellation or have private transactions at all. That package is also not in the vendor folder. I'm not entirely sure how quorum manages to build that when I freshly clone the repository, but it breaks all my attempts to `go get` the `private` package, or to vend the package as a dependency. Even if I `go get github.com/jpmorganchase/quorum` and try to vend from there I eventually end up with `cannot find package "github.com/ethereum/go-ethereum/private/constellation"`

Details on how to reproduce the error included below

#### System information

Geth version: geth 1.18.16

OS & Version: OSX 10.14.1

Branch, Commit Hash or Release: master (trying to use `go get`)

#### Expected behaviour

`go get github.com/jpmorganchase/quorum/private` should succeed

#### Actual behaviour

`go get github.com/jpmorganchase/quorum/private` produces the following error:

`package github.com/ethereum/go-ethereum/private/constellation: cannot find package "github.com/ethereum/go-ethereum/private/constellation" in any of:`

`	/usr/local/Cellar/go/1.11.1/libexec/src/github.com/ethereum/go-ethereum/private/constellation (from $GOROOT)`

`	/Users/$USER/go/src/github.com/ethereum/go-ethereum/private/constellation (from $GOPATH)
`

#### Steps to reproduce the behaviour

`go get github.com/jpmorganchase/quorum/private`

**Comment by drequinox** [comment]
I have been able to reproduce the issue. this is under investigation.

**Comment by prd-fox** [comment]
Quorum masquerades under the go-ethereum namespace and has done for a while. With so many changes to the upstream repo, we need to make sure that we only use our own files and not any of the upstream ones, and the easiest way to do that is to take over the namespace.
So you would need to have a GOPATH where quorum is checked out under the go-etheruem namespace currently, (and this of course means you wouldn't be able to `go get` the upstream geth repo under the same GOPATH).

In the case of the 'private' package, it is true that it could be moved to its own package and namespace to enable easier use for importing like your use case above.

So even though you cannot `go get` the package, I will still mark as an enhancement as you can still checkout the dependency manually.

**Comment by trung** [comment]
As we fork from upstream, `github.com/ethereum/go-ethereum` base package has to exist.

Unfortunately `go get` doesn't have a way to specify the target repository. One option that i have not tried yet is to use git `insteadOf` configuration. So when `go get github.com/ethereum/go-ethereum`, git would rewrite and clone from `github.com/jpmorganchase/quorum`

Other tools like `dep` or `go mod` provide the configuration that allows sourcing from different repository.

[1] https://golang.github.io/dep/docs/Gopkg.toml.html#source
[2] https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive
[3] https://git-scm.com/docs/git-config#git-config-urlltbasegtinsteadOf
