### ISSUE TITLE
make all fails with Go 1.11.3

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#600]
#### System information

Golang Version: go1.11.3 

OS & Version: Ubuntu 16.04.5 LTS

#### Actual behaviour
make all fails!

#### Steps to reproduce the behaviour
Install the newest Go version go1.11.3.linux-amd64.tar.gz and try to make all quorum v2.2

**Comment by prd-fox** [comment]
Hey Saitam1,

Quorum doesn't yet support go1.11

I'm using go1.10.3 to build, which works fine, and others are using go1.9.x
