### ISSUE TITLE
Docker run failed with quorumengineering/quorum

### ISSUE THREAD

**Issue by falconwoods** [Consensys-Incorporated/quorum#601]
Hi there,

docker run failed with quorumengineering/quorum:

```
docker run -it quorumengineering/quorum
```
then get the error:
```
Fatal: Consensus not specified. Exiting!!
```
how should I specify the consensus when running docker ?

#### System information

OS & Version: MacOS Mojave

#### Expected behaviour
running quorum in docker

#### Actual behaviour
failed

#### Steps to reproduce the behaviour
```
docker pull quorumengineering/quorum
docker run -it quorumengineering/quorum
```

**Comment by falconwoods** [comment]
![image](https://user-images.githubusercontent.com/3508825/50052525-6edd5d00-0160-11e9-9ff6-0e5a8501a877.png)

**Comment by fixanoid** [comment]
@wxlcat Please look at this compose file to see how we use it. https://github.com/jpmorganchase/quorum-examples/blob/master/docker-compose.yml
