### ISSUE TITLE
Cannot update value from another contract 

### ISSUE THREAD

**Issue by pccr10001** [Consensys-Incorporated/quorum#602]
Hi there

I want to call a function from another contract.

Contract 1
```
pragma solidity ^0.5.0;
contract Test1 {

    uint256 public count=0;

    function test() public {
        count = count + 1;
    }

    function get() view public returns (uint256){
        return count;
    }

    constructor() public {
        count=0;
    }

}
```

Contract 2
```
pragma solidity ^0.5.0;
contract Test2 {

    function test(address con) public {
        con.call(abi.encodeWithSignature("test()"));
    }

}
```

Test1 -> Deploy to 0x111
Call Test1.test() to update the counter to 1.
Call Test1.get() to verify the counter equals to 1.

**Call Test2.test(0x111) to update the counter to 2;** <-- All gas used and counter didn't update.

#### System information

Geth version:
Version: 1.8.12-stable
Git Commit: 8f678278aab02529cc56d934606e5b275b94f6cf
Quorum Version: 2.2.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.7
Operating System: linux

Branch, Commit Hash or Release: v2.2.0

**Comment by fixanoid** [comment]
@pccr10001 are these private or public contracts?

**Comment by pccr10001** [comment]
@fixanoid there are public contracts, the "privateFor" parameter is empty.

**Comment by SatpalSandhu61** [comment]
@pccr10001 I tried out your example and it works for me. Test2 successfully increments the counter in Test1.
One thing I'm not clear on - how do you 'deploy to 0x111'? AFAIK it's not possible to deploy to a specific address. I'm using the address returned by quorum after it creates the contract.

FYI here is my console output:
```
> loadScript("test1.js")
Contract transaction send: TransactionHash: 0x506b2c0464210ed3e39772638248cab25bffefe004a69f41a2adefd071078f01 waiting to be mined...
true
> Contract mined! Address: 0x15a33fba67b0fca73a7c988e00a1495cb281c747
[object Object]

> loadScript("test2.js")
Contract transaction send: TransactionHash: 0x0c381a32efc500107c0791f0e6c8f0768b7d4a48bcd380be7858ed1b76804049 waiting to be mined...
true
> Contract mined! Address: 0x5ab303af15a194e4f9e032f26ba90e87855972e5
[object Object]

> test1.get()
0
> test1.test()
"0x4a3e9af13269df2c9a51d9e382ec33775f0d66c4da5dfb90660a8195fbbead9d"
> test1.get()
1
> test2.test("0x15a33fba67b0fca73a7c988e00a1495cb281c747")
"0x988f70dbd27271297f90abddbc82f807b119da02e3fcfa063bbeded08565a011"
> test1.get()
2
```

**Comment by pccr10001** [comment]
@SatpalSandhu61 I tried solc v0.4.20 and everything works.
"call" is not working above solc v0.4.21.

Thanks for your help.

**Comment by fixanoid** [comment]
Can you share your genesis.json?

**Comment by SatpalSandhu61** [comment]
@pccr10001 I'm using solc v0.5.0

**Comment by pccr10001** [comment]
@fixanoid My genesis.json
```
{
  "alloc": {
    "f7c74daf67ae8fd8a1e40f6b2badcbaf601dffbd": {
      "balance": "1000000000000000000000000000"
    },
    "04a9b8721bdb2aa7609a156a542ed08cf063efbc": {
      "balance": "1000000000000000000000000000"
    },
    "751e216ba851d5c767d3b40855976a4991b326c6": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0
  },
  "difficulty": "0x0",
  "extraData": "0x",
  "gasLimit": "0x2FEFD800",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```

@SatpalSandhu61 I used Web3j-Quorum v4.0.3 to interative with contracts, I will try to use web3.js again

**Comment by fixanoid** [comment]
The issue with solc version here is due to the use of homestead instead of
byzantium block configuration. Please update your genesis and replace
homesteadBlock with byzantiumBlock and that will resolve your solc issue.

**Comment by pccr10001** [comment]
@fixanoid I modified my genesis.json and it works now.
Thanks you very much.
