### ISSUE TITLE
Which truffle version works with Quorum?

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#603]
I couldn't an official statement on this topic. I am currently trying to deploy some contracts on Quorum and using the following versions of truffle and solc:
Truffle v4.1.14 (core: 4.1.14)
Solidity v0.4.24 (solc-js)

Does the latest Quorum version support this version?

**Comment by fixanoid** [comment]
Officially, any version of truffle will work with Quorum. solc is a bit different matter, but at the moment, latest Quorum supports everything up to v0.5.x
