### ISSUE TITLE
Official web3.js for Quorum

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#604]
Since there are some changes in the API, is there an official web3 version for Quorum?
Is this the official one: [https://github.com/tdhman/web3.js](https://github.com/tdhman/web3.js) / [https://www.npmjs.com/package/web3-quorum](https://www.npmjs.com/package/web3-quorum) ?

**Comment by fixanoid** [comment]
@saitam1 web3-quorum is currently considered the most up to date, but it is not the official web3.js extension. The official release is coming shortly and will be labeled quorum.js.

**Comment by ghost** [comment]
Thank you! What about `web3` `v0.20.7` or best of all `v1.0` ? Is it possible to use it? 
And when will `quorum.js` be there? Is there an approximate timeline?

**Comment by fixanoid** [comment]
You may use web3 as well, heres a list of quorum extensions https://github.com/jpmorganchase/quorum/blob/df7eb273751a7465e002910b50bcfb1dd37d15dd/internal/web3ext/web3ext.go
