### ISSUE TITLE
For a new node can not get the address of smart contract

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#606]
I have a quorum network with 26 nodes. Today I add 27 node to this network, everything is ok. When I deploy a smart contract to the 27 node with web3.js, I can not get nothing callback. I found the log about the 27 node and get following error. I want to know the reason. Thank you!

INFO [12-21|02:31:24] failed to synchronize with peer          peer id=e3d4d7415f0afc2ace5d2eeeaa311b88315c9ce61e5b5d6c3d65e758c6856d16998d2858c08e1d8959d7af7d9acc5779f621a1ecc4d0afd0ba892bb61a88cc14
2018-12-21 02:31:24.083681 W | rafthttp: the clock difference against peer 8 is too high [51.309939988s > 1s]
2018-12-21 02:31:24.148376 W | rafthttp: the clock difference against peer b is too high [1.286862834s > 1s]
2018-12-21 02:31:24.148435 W | rafthttp: the clock difference against peer 9 is too high [51.328348311s > 1s]
2018-12-21 02:31:24.148457 W | rafthttp: the clock difference against peer a is too high [51.323893801s > 1s]
2018-12-21 02:31:24.148469 W | rafthttp: the clock difference against peer c is too high [51.313192867s > 1s]
2018-12-21 02:31:24.285304 W | rafthttp: the clock difference against peer e is too high [51.319167314s > 1s]
2018-12-21 02:31:24.294660 W | rafthttp: the clock difference against peer d is too high [1.290239987s > 1s]
2018-12-21 02:31:24.345259 W | rafthttp: the clock difference against peer f is too high [1.282703429s > 1s]
2018-12-21 02:31:24.373910 W | rafthttp: the clock difference against peer 10 is too high [51.313489771s > 1s]
2018-12-21 02:31:24.384667 W | rafthttp: the clock difference against peer 11 is too high [1.282016362s > 1s]
2018-12-21 02:31:24.524985 W | rafthttp: the clock difference against peer 12 is too high [51.317176369s > 1s]
2018-12-21 02:31:24.568702 W | rafthttp: the clock difference against peer 13 is too high [1.284566131s > 1s]
2018-12-21 02:31:24.568759 W | rafthttp: the clock difference against peer 14 is too high [51.308702593s > 1s]
INFO [12-21|02:31:24] synchronizing with peer                  peer id=26                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:24] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:24] failed to synchronize with peer          peer id=a81504f97215a6948fdc092b93204ffb33090ac7463395fca2e9166454c016c9eeb9f5cfdae41bf33e925d58167299fd37d1e90522f53674d2fd09c055967916
2018-12-21 02:31:24.964665 W | rafthttp: the clock difference against peer 18 is too high [51.314602391s > 1s]
INFO [12-21|02:31:25] synchronizing with peer                  peer id=17                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:25] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:25] failed to synchronize with peer          peer id=95c2882507fef9017b39d739b48f7b5aef65236bacdedb7f610ddff5a6a17ea177af52b952bdc1496c8274377e8c93dbc6eb816f188f352dd3f7fc9c8564872e
2018-12-21 02:31:25.160554 W | rafthttp: health check for peer 1d could not connect: dial tcp 192.168.199.41:21029: getsockopt: connection refused
INFO [12-21|02:31:25] synchronizing with peer                  peer id=20                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:25] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:25] failed to synchronize with peer          peer id=c604b406de7544afe792c689be78b7a91b183236475c42e3094ea0b5acba8a224314459a562708f92836912207822551a73731f0a2ab5dad8179fb4edd331f50
INFO [12-21|02:31:26] synchronizing with peer                  peer id=9                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:26] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:26] failed to synchronize with peer          peer id=74792ec6c1898a2e3c45d5309d0c8f13cef37a4e48004a43f56195a8b57bafd2c961346c00380b69e490ee6d8ee62fd40ac67814f64c9fdf740f924e85fbbe6e
INFO [12-21|02:31:26] synchronizing with peer                  peer id=23                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:26] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:26] failed to synchronize with peer          peer id=0b100dac783784e941a80e37579ca46a2730e5e4aac9cea4d6513e930c5280dc32be7f6375efb7ffcc8cf98f6163b4c72e1581f71eac5222d90a72f4896ca6f0
INFO [12-21|02:31:27] synchronizing with peer                  peer id=1                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:27] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:27] failed to synchronize with peer          peer id=6321a252681fbefe3a88caf27c9ef76d3bb21021090a8e754c2ed24ba7b4c9966456cfc3284305f2daa15ff19c1ed182f3ea29092d6291729ea53adce1c046e9
INFO [12-21|02:31:27] synchronizing with peer                  peer id=11                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:27] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:27] failed to synchronize with peer          peer id=26fc6ba74a647018f1f45a719fac90461660a1dc2402101d6af2a2fb959cd483bb3559688a719c047d1f20562574694a9b5460eb450f8d243882a1cdd4713d6a
INFO [12-21|02:31:28] synchronizing with peer                  peer id=18                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:28] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:28] failed to synchronize with peer          peer id=464c94804a09f50eb363cb0668a875953759fc96ab38c3bc6f8a730e60564740176f8af055b9ca6cdb6335224d5527c464f1ca79ef3f58d749b1746714f8be09
INFO [12-21|02:31:28] synchronizing with peer                  peer id=25                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:28] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:28] failed to synchronize with peer          peer id=5a058013f93cb2c24cbbce35aa56d4caadbd61d4dc3a4cf20ac3a32e4ee613408aa668f191778111916724a8558994ffba9fecb1bb2065f07b77bb744f3f83a1
INFO [12-21|02:31:29] synchronizing with peer                  peer id=7                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:29] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:29] failed to synchronize with peer          peer id=682d79b455d37a8ae07bfe6bb1f66aa1e54aa2094c4af72ed3ec33ff0018f1efe59f5eb87ce87dcd7787d9684b011e85a905365fff0c5595625e4db921242b50
INFO [12-21|02:31:29] synchronizing with peer                  peer id=12                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:29] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:29] failed to synchronize with peer          peer id=a70c3c273bdc0f5f0e2c7bd5ab10d841bc639eff3635e06e7505b62d38e7367df15850f455f9f18b488296ce99b609e9082b98113f2c2aa262812c00b7d13f4e
2018-12-21 02:31:30.163652 W | rafthttp: health check for peer 1d could not connect: dial tcp 192.168.199.41:21029: getsockopt: connection refused
INFO [12-21|02:31:30] synchronizing with peer                  peer id=16                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:30] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:30] failed to synchronize with peer          peer id=ca0beee5d4a9f101e54f52f80a161d2d1dd316c4c1fb56ae0fb3130df5e7da3894b14d838f2ff4ec734a33fe631b329bb43912972c6a876833ffd401930c0d1c
INFO [12-21|02:31:30] synchronizing with peer                  peer id=6                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:30] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:30] failed to synchronize with peer          peer id=1fcdd3e85746cb13b75ce914216fe0ec13e8f408d7a55f8531f1c034947b36b845ba098702f75d4b7b86ddfa95e7743a424fc8bc7988e161201eb81d2c7fd080
INFO [12-21|02:31:31] synchronizing with peer                  peer id=7                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:31] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:31] failed to synchronize with peer          peer id=682d79b455d37a8ae07bfe6bb1f66aa1e54aa2094c4af72ed3ec33ff0018f1efe59f5eb87ce87dcd7787d9684b011e85a905365fff0c5595625e4db921242b50
INFO [12-21|02:31:31] synchronizing with peer                  peer id=12                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:31] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:31] failed to synchronize with peer          peer id=a70c3c273bdc0f5f0e2c7bd5ab10d841bc639eff3635e06e7505b62d38e7367df15850f455f9f18b488296ce99b609e9082b98113f2c2aa262812c00b7d13f4e
INFO [12-21|02:31:32] synchronizing with peer                  peer id=16                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:32] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:32] failed to synchronize with peer          peer id=ca0beee5d4a9f101e54f52f80a161d2d1dd316c4c1fb56ae0fb3130df5e7da3894b14d838f2ff4ec734a33fe631b329bb43912972c6a876833ffd401930c0d1c
INFO [12-21|02:31:32] synchronizing with peer                  peer id=6                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:32] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:32] failed to synchronize with peer          peer id=1fcdd3e85746cb13b75ce914216fe0ec13e8f408d7a55f8531f1c034947b36b845ba098702f75d4b7b86ddfa95e7743a424fc8bc7988e161201eb81d2c7fd080
INFO [12-21|02:31:33] synchronizing with peer                  peer id=13                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:33] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:33] failed to synchronize with peer          peer id=6a7f7d8c6e29acab37668986fb52220cbefb6a31f9e3ad469945a469f531912af8c03c63af7f6c9b0846959f478a3add4648ec91ba26bafa26985456685d0b57
INFO [12-21|02:31:33] synchronizing with peer                  peer id=21                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:33] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:33] failed to synchronize with peer          peer id=ce3688bea9f52521b987caf571297560476b5d8729751f04703bb1ed962899cf2b75c5bc1b48913f06b7191485de6dc363ed072a91815c138c7354be3738d552
INFO [12-21|02:31:34] synchronizing with peer                  peer id=8                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:34] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:34] failed to synchronize with peer          peer id=448ab042526bd9c827b937f148966ecd44b76b8749e88d3b883c76a2f872c87789f5e7e50f69608a54136efe8f9e1f7ab31f616fbd6356588b58ca3dbb540bda
INFO [12-21|02:31:34] synchronizing with peer                  peer id=15                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:34] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:34] failed to synchronize with peer          peer id=bc3f563628d7e608837549c75f09e655688a113a47415e9cb854e8b3ac316e0de88ef48199c975a777872b851333ade5efc941e446acfff5791495d7eabff4a5
2018-12-21 02:31:35.173083 W | rafthttp: health check for peer 1d could not connect: dial tcp 192.168.199.41:21029: getsockopt: connection refused
INFO [12-21|02:31:35] synchronizing with peer                  peer id=5                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:35] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:35] failed to synchronize with peer          peer id=03266a25f710b8c9ffd80f66b4df020c53f08952721989a9fae98fadd5d76ffb290b8e38054e94d564842d342fe249863c5b9618bc0fe02fc9e4caf829d5bcf9
INFO [12-21|02:31:35] synchronizing with peer                  peer id=24                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:35] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:35] failed to synchronize with peer          peer id=f9db2721473d936bdafef151b28bcdcc174076ad3e82e07add20e50c77b510f73e4097922a93a80fcefab6776709d32a0a9d6372a6b04a6e0d2c38ff6efae199
INFO [12-21|02:31:36] synchronizing with peer                  peer id=4                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:36] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:36] failed to synchronize with peer          peer id=7e36ee1d5b460d9660b3bb49f046d6722eb5660afe85f9d291fe82d653fd121b4f2eef1db5e35c7c41a2d1a9357e220be29a9cde013288f7144449c9d61fe1a1
INFO [12-21|02:31:36] synchronizing with peer                  peer id=14                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:36] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:36] failed to synchronize with peer          peer id=09a4f2fb446bbc42abc51a14f138e149497478ebe466d0d6e12a28a3f63dfae846286c57936d6dfa5388a411be81df426027c8a989b7e64469e3ceba80a499eb
INFO [12-21|02:31:37] synchronizing with peer                  peer id=2                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:37] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:37] failed to synchronize with peer          peer id=b02bab8f662dd98f5a9449bac8a8ab5aedd4e3a9f95a42c203304a7a086f2048fc3c9f60ec973d53a2b6fdd6a43720a747f042256090e60ef05979e34c16fb88
INFO [12-21|02:31:37] synchronizing with peer                  peer id=19                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:37] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:37] failed to synchronize with peer          peer id=a5b0aefd5ee9e3b7c8767db9b13e4ad0559563b8f26e8590d4f52fe0640d5b50008e7e941a939be76dc82e9919902ae7d4b4b6d2a15785daae8a3af96979d893
INFO [12-21|02:31:38] synchronizing with peer                  peer id=29                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:38] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:38] failed to synchronize with peer          peer id=f38ca7c97de33e32ac310a0970fe0a833dbb8b63a420c8627898a02f893d5e6a376ed4a13a4f029ef14a2ff9ab2a949c6a5f036061b2b37ed6f13f1a1cc2a34d
INFO [12-21|02:31:38] synchronizing with peer                  peer id=3                                                                                                                                hash=c392c4…97a116
WARN [12-21|02:31:38] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:38] failed to synchronize with peer          peer id=8804cf230f841c2fccd9c048a5404d3263144016e2fca57139790b31ac9d26e22f67c7aa770526404fdf8e567ba360edb7dc32bbce41521757fce3a396f268d4
INFO [12-21|02:31:39] synchronizing with peer                  peer id=22                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:39] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:39] failed to synchronize with peer          peer id=354daaf55274590d4c4be9d904245afcedd2800eccc51a950da7e1a6e9190b07fc46b904464eff54a88d36462a8425b3c17c7b69f35e3ebc49e0e4a2218e91a0
INFO [12-21|02:31:39] synchronizing with peer                  peer id=10                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:39] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:39] failed to synchronize with peer          peer id=e3d4d7415f0afc2ace5d2eeeaa311b88315c9ce61e5b5d6c3d65e758c6856d16998d2858c08e1d8959d7af7d9acc5779f621a1ecc4d0afd0ba892bb61a88cc14
2018-12-21 02:31:40.174880 W | rafthttp: health check for peer 1d could not connect: dial tcp 192.168.199.41:21029: getsockopt: connection refused
INFO [12-21|02:31:40] synchronizing with peer                  peer id=26                                                                                                                               hash=c392c4…97a116
WARN [12-21|02:31:40] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-21|02:31:40] failed to synchronize with peer          peer id=a81504f97215a6948fdc092b93204ffb33090ac7463395fca2e9166454c016c9eeb9f5cfdae41bf33e925d58167299fd37d1e90522f53674d2fd09c055967916
INFO [12-21|02:31:40] synchronizing with peer                  peer id=17                                                                                                                               hash=c392c4…97a116

**Comment by Himanshu-Pandey** [comment]
I don't think it is about the smart contract at all, judging by the logs it seems like that your new node is not able to join the network correctly. And that too because of clock synchronization error, all the nodes should have clocks synchronized with each other.

Can you try to do eth.sendTransaction() from 27th node, it will fail according to me.

**Comment by matrixoneken** [comment]
I found a strage problem  as following:
First, I setup a quorum network with 26 nodes. Everything is OK
Then I open the 27 node, the 27 node can be opened without error. But I found the error in the log of 27 node

WARN [12-24|07:49:07] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:07] failed to synchronize with peer          peer id=d91ac4cc64364751f355788e0079f3e4def974eecba6d42a5f8a49ea882594af87da256561b12e6feaa02bb1327330740380c75ad523d4f597dbf95e93cb8cde
INFO [12-24|07:49:07] synchronizing with peer                  peer id=10                                                                                                                               hash=25b883…99b3e9
WARN [12-24|07:49:07] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:07] failed to synchronize with peer          peer id=a7ccbed24f97ad0ce8708797f00b8cf6d6341baa2f00bb9519eca2f92c2e491ae5955e1eeb611b0c449b8c5b5c6d7901d786448b8199bcff2cb4f994d8aaae6e
INFO [12-24|07:49:08] synchronizing with peer                  peer id=20                                                                                                                               hash=25b883…99b3e9
WARN [12-24|07:49:08] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:08] failed to synchronize with peer          peer id=c0c4f128d47b18a0bf4626ebcdd32290b846220d84a8cf8a7f968ce75e1f59a0b2480f1dd6ce2179ea3fe94ffe93d66af42b90e50d067840ef7d8892f381cfc5
2018-12-24 07:49:08.660158 W | rafthttp: health check for peer 1b could not connect: dial tcp 192.168.199.70:21036: getsockopt: connection refused
INFO [12-24|07:49:08] synchronizing with peer                  peer id=9                                                                                                                                hash=25b883…99b3e9
WARN [12-24|07:49:08] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:08] failed to synchronize with peer          peer id=725d00e1e3bd4ac332e3de379f6ff91379980dccebb15905ca9db6e45690b2d0eaddd23633ef67c00e079da8d9012f8fd98cab573c1da08d6b11baa2c66fc98c
INFO [12-24|07:49:09] synchronizing with peer                  peer id=21                                                                                                                               hash=25b883…99b3e9
WARN [12-24|07:49:09] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:09] failed to synchronize with peer          peer id=356eed053b576a0e9d023edcc40bcacd6afedf6029d8a9ec6c71b409695c32231aabc7b99e5af13f3e4c364f5da2a516ad0674c6fd757c09c0284ee3d2d63732
INFO [12-24|07:49:10] synchronizing with peer                  peer id=11                                                                                                                               hash=25b883…99b3e9
WARN [12-24|07:49:10] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:10] failed to synchronize with peer          peer id=0b0fbd91f0bcfd4442ed5059e9897d2e28e2b64eecbf0c4e76a677a59552b3023284c4738ddc2be089455bbee9b82dabdb623dec8953ad77c28aa5ded4811e72
INFO [12-24|07:49:10] synchronizing with peer                  peer id=8                                                                                                                                hash=25b883…99b3e9
WARN [12-24|07:49:10] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:10] failed to synchronize with peer          peer id=816573f1b5170f3830e172d2cd028e79679ed6d42595d4ea3baf48d614d52e7163030a763ab235bf8c8a611cf45f661bc75f4371fc072496892f925cc7306d20
INFO [12-24|07:49:11] synchronizing with peer                  peer id=2                                                                                                                                hash=25b883…99b3e9
WARN [12-24|07:49:11] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:11] failed to synchronize with peer          peer id=17fe7fe2069cf2bd8fac520508e778140d53eef0c0cf6297bd2188ab35636a083793915c2aba08cdc80bb9d4126931bd6c253bf2e0569db8552c92bc3a5565fa
INFO [12-24|07:49:11] synchronizing with peer                  peer id=13                                                                                                                               hash=25b883…99b3e9
WARN [12-24|07:49:11] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [12-24|07:49:11] failed to synchronize with peer          peer id=2cf2123b4e128e075b8860ce987f89dfac82bcce6f388fcf5654b63f8b6f6c838526ec9c4cdc13b205a7a78e2c3b8a80368324943d68765cdc33dfc9c1a32db7
.......

When I try to open 28,29 node, I also get above error. I have try on different server cluster and get the same problem. 
When I open node and the number is  less than or equal  26 everything is ok. But when the node number is bigger than 26, I will get above error which means the new node can not synchronize with other 26 nodes. Can you tell me how to solve this problem. Thank you.

**Comment by jbhurat** [comment]
Hi @matrixoneken, can you paste the command that you are using to start `geth` including all the command line options

**Comment by matrixoneken** [comment]
geth --datadir qdata/dd28 --nodiscover --raft --raftjoinexisting 28 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --raftport 21037 --rpcport 16037 --port 11037 --unlock 0 --password passwords.txt

constellation-node --url=http://192.168.199.72:26037/ --port=26037 --workdir=qdata/c28 --socket=tm.ipc --publickeys=tm.pub --privatekeys=tm.key --tls=off --othernodes=http://192.168.199.70:26010/


Above is the command which I used.  The 28 in "--raftjoinexisting 28" is the raftID which I get by calling the api of node 1. When I open  a new node, I  call the  the api of node 1 to get the raftID and then use the rafteID to join the network. The http://192.168.199.70:26010/ is the ip of node 1.

**Comment by fixanoid** [comment]
Hi, could you add --maxpeers 100 and see if this helps?

**Comment by matrixoneken** [comment]
@fixanoid  you mean using the command to open node 28 like this
geth --datadir qdata/dd28 --nodiscover --raft --raftjoinexisting 28 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum --emitcheckpoints --raftport 21037 --rpcport 16037 --port 11037 --unlock 0 --password passwords.txt --maxpeers 100
 
Or I need to add this setting to each node from node 1 to node 26

**Comment by fixanoid** [comment]
Yeap

**Comment by fixanoid** [comment]
Err, you may need this flag for all nodes in your cluster. Default geth
connectivity is topped at 25 peers and this flag raises it

**Comment by matrixoneken** [comment]
@fixanoid 
With --maxpeers 100 , I can add node27,node 28,node 29,node30 into my cluster. Thank you for you help.
But I want to know why the geth has this setting? For my system, I open a node for each user and  I can not estimate how many user will use my system, so I can not set the --maxpeers  accurately . For example now  I set 100 peers, after a year maybe I need to add node 101 for the user 101 . For this purose I need to reset my whole cluster . I think this is not reasonable.
And I also want to know the maximum value about this setting and whether it  has limitless setting.
Thank you very much.

**Comment by fixanoid** [comment]
@matrixoneken so, Ethereum and its clients are intended for a fully decentralized blockchain setup. Its possible with many of the BFT consensus mechanisms, but in return trades in the txn/block propagation speed. In Quorum, we bundle 3 consensus mechanisms that also affect networking: Raft is intended to be very fast, but in return it is a more finicky and demanding ops configuration that will require your network to be in time sync and physically close to each other. To achieve the speed it does, the raft implementation also requires the entire set of nodes in the chain to be able to talk to each other.

Geth client limits max peers to 25 to be a sensible solution -- all nodes will pass the data through themselves anyways. This is not the case with raft, and you will need to increase maxpeers to match the size of the network (or set it to a very large number you wont hit for a long time).

That said, it looks like you are setting up a more complex net with wide geography and varying number of nodes. In this case, I would suggest switching to the other consensus mechanisms Quorum bundles: Istanbul or Clique. Both are BFT tolerant and do not require full node interconnection (no maxpeers flag is needed). They're also a bit more tolerant of the timing and sync issues, tho in return they are just a tad harder to set up.
