### ISSUE TITLE
[Question] How to restore private transactions after restoring old quorum data.

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/quorum#607]
Basically what I am trying to do is to replace the existing /quorum directory for a node with a backup which is few transactions old.
To test this on the 7-node example I am replacing the qdata/c1 and qdata/dd1 folders with a backup which I took some transactions back. Following are the steps which I followed:

1. Started the vagrant version of 7-node example and provisioned the network (./raft-init.sh followed by ./raft-start.sh tessera)
2. Deployed a simpleNumber private contract between node 1 and node 7, with a value of ‘101’.
3. Did the get of this value from both node 1 and node 7 and got the value as ‘101’.
4. Copied the qdata/c1 and qdata/dd1 folders to qdata/c1_bk and qdata/dd1_bk folders
5. Set a new number privately for node 1 and node 7, new number is ‘9306’, did a get for both node 1 and node 7 and value was ‘9306’ as expected.
6. Stopped the cluster by running ./stop.sh.
7. Removed qdata/c1 and qdata/dd1, renamed qdata/c1_bk and qdata/dd1_bk to qdata/c1 and qdata/dd1 respectively.
8. Started the network again by ‘./raft-start.sh tessera’
9. Now when I am doing get then node 1 is showing old value ‘101’ and node 7 is showing new value ‘9306’.

**Comment by prd-fox** [comment]
Was the transaction setting the value to '9306' sent from node 1 originally?
Although Tessera will try to fetch missing transactions, it does not do that for transactions for which it originally sent.

**Comment by Himanshu-Pandey** [comment]
Yeah, it was sent from node 1. Just tried the same steps but I restored data for node 7  instead. It is also not working. Can you please confirm once.

**Comment by fixanoid** [comment]
@Himanshu-Pandey as explained by @prd-fox private txns originating from the node that died are not resent -- since the node was supposed to originate them, participants do not know the entirety of the list so they do not resend these.

We do see this as a severe issue and Tessera team is considering a way to share these txns as well, however at the moment thats not possible with Constellation or Tessera.
