### ISSUE TITLE
How to make raft ID unique

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#609]
I have deployed a quorum cluster with raft. If a node wants join the cluster, it need call api from node 1 to get a raft ID, and then joins the culster with --raftjoinexisting   setting.
Each node joins my cluster randomly. I found that some time if two node join my cluster at the same time and they will  get the same raft ID probably. For two node with the same rafte ID, I can not deploy smart contract to one of them.
I want  to know how to make raft ID unique?

**Comment by fixanoid** [comment]
@matrixoneken several notes. To join existing cluster, you need to hit the api on *any* running node, not necessarily node 1. If you do execute this api on the same node, the raft id is not reused and a new one will be issued -- the new nodes can join in any particular order, as long as their enode and raft id match the configuration you passed int `raft.addPeer`.
