### ISSUE TITLE
Block Creation Strategy inconsistent with documentation

### ISSUE THREAD

**Issue by magooster** [Consensys-Incorporated/quorum#61]
#### System information

Geth version: `geth version`
Geth
Version: 1.5.0-unstable
Git Commit: 85327f743b9735c32ae9231cbdde509e243ba0df
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Linux ubuntu-xenial 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Branch, Commit Hash or Release: `git status`
q1.0.1

#### Expected behaviour

From the Wiki, 
> each Maker generates a random duration (a timeout) that it has to wait before it can create a block

> If a Maker reaches its timeout before any other Maker does it will create a block, after which it will generate a new random timeout for itself and wait for that to elapse before attempting to create another block.

> Note that once a Maker begins the block creation process, the other Maker Nodes will reset their current timeout, generate a new random timeout, and wait until that expires before attempting to creating a block.

#### Actual behaviour
There is no random seed to the random function, so the random number sequence is deterministic.  

The Maker timeout is actually reset twice - once when it starts creating a block and again when it inserts the newly created block onto its canonical chain.

The other Maker nodes timeout is only reset after a ChainHeadEvent, that is after the node has inserted a new block onto its canonical chain.  

#### Steps to reproduce the behaviour

N/A - Code Review

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
@magooster great catch, thanks :)  The documentation certainly does not describe every single process exactly (in an effort to try to reduce maintenance overhead) however we will certainly update this.  Will provide a separate update re random seed.

**Comment by bas-vk** [comment]
Good catch, we will add a seed.

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/266
