### ISSUE TITLE
 How to deploy a quorum cluster with Istanbul or Clique.

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#610]
https://github.com/jpmorganchase/quorum/issues/606 
From above issue, I want to deploy a quorum cluster with  Istanbul or Clique. I want to know how to setup. Does it has any document or example? Thank you.

**Comment by SatpalSandhu61** [comment]
The easiest way is to follow the [Getting Set Up instructions](https://github.com/jpmorganchase/quorum-examples#getting-started) on the Quorum Examples github.
That has scripts for starting quorum with Istanbul or Clique.

**Comment by fixanoid** [comment]
Err, while quorum-examples is great,it glosses over a few set up things.
Please refer to this document instead:
https://github.com/jpmorganchase/quorum/wiki/From-Scratch#quorum-with-istanbul-bft-consensus
