### ISSUE TITLE
How to open a new node to a cluster with istanbul

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#612]
First I open a node 1 with following commad
geth --datadir qdata/dd1 --nodiscover --istanbul.blockperiod 5 --networkid 10 --syncmode full --mine --minerthreads 1 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --rpcport 22000 --port 21000 --unlock 0 --password passwords.txt

everything is Ok.

And then I open node 2 with following command:

geth --datadir qdata/dd2 --nodiscover --istanbul.blockperiod 5 --networkid 10 --syncmode full --mine --minerthreads 1 --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul --rpcport 22001 --port 21001 --unlock 0 --password passwords.txt

But I get following error and can not open node 2.

Fatal: Consensus not specified. Exiting!!

Please tell me how to solve this problem. Thank you.

**Comment by SatpalSandhu61** [comment]
It looks like the genesis block is not set up for istanbul on node 2. You should have something like the following in your genesis block:
```
      "istanbul": {
        "epoch": 30000,
        "policy": 0
      },
```

Please check if that is the case. If you do have genesis set up correctly then can you give us your genesis details, your system information, and the quorum version you are using pls.

**Comment by matrixoneken** [comment]
I can open node 2 now. Thank you
But I want to know how to add the node address into permissioned-nodes.json  ?
I found for a quorum cluster with raft, I only add the current node address into  permissioned-nodes.json. I don't need to consider address before the current node.But for the cluster with istanbul, I need to find the  address before the current node.

For example,  before opening node 1 , I only save the node 1 address into permissioned-nodes.json. Then when I want to open node 2, I don't need to add the node 1 address and only save the node 2 address into permissioned-nodes.json. Everything is OK.
But for a quorum cluster with istanbul, when I open node 1, I also save the node 1 address into permissioned-nodes.json. But when I open node 2, I need to add the node 1 address firstly and then append the node 2 address  into permissioned-nodes.json. If I do the same thing as deployment about the raft cluster, I can not get the address of smart contract with web3.js and the program keep waiting. 

I think this is a problem. If I have a cluster with 100 nodes, when I want to deploy node 101, I need to find the node address about 100 nodes. It is so hard.

**Comment by fixanoid** [comment]
@matrixoneken the details of how to generate enode ids are shown as examples in the docs here https://github.com/jpmorganchase/quorum/wiki/From-Scratch#quorum-with-istanbul-bft-consensus. Istanbul tools is a helper tool that you may use to prepare and set up a cluster with many istanbul nodes -- it generates all of the required genesis files, permissions, and node files.

**Comment by ManUnit** [comment]
# I got error  Fatal: Consensus not specified. Exiting!!


I have update  quorum  https://github.com/ManUnit/quorum 
 - Modify build/bin  change bin name geth to be quorumd 
 - Modify default --datadir .ethereum  to be .quorumd 
 - Modify default .ethash to be  .quorumhash
 - Modify all files imports module  from github.com/ethereum/go-ethereum to  github.com/ethereum/quorum 

==== My local node-1 genesis.json 
```
{
 "config": {
   "homesteadBlock": 0,
   "byzantiumBlock": 0,
   "chainId": 10,
   "eip150Block": 0,
   "eip155Block": 0,
   "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
   "eip158Block": 0,
   "isQuorum": true
  },
 "coinbase": "0x0000000000000000000000000000000000000000",
 "difficulty": "0x0",
 "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
 "gasLimit": "0xE0000000",
 "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
 "nonce": "0x0",
 "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
 "timestamp": "0x00",
  "alloc": { 
            "0x679fed8f4f3ea421689136b25073c6da7973418f": { "balance": "1000000000000000000000000000" },
            "0xc5c7b431e1629fb992eb18a79559f667228cd055": { "balance": "2000000000000000000000000000" }
           },
   "istanbul": {
        "epoch": 30000,
        "policy": 0
      }
} 
```
anybody know how to fixed Fatal: Consensus not specified. Exiting!!

**Comment by SatpalSandhu61** [comment]
Please don't add issues onto the end of closed tickets. You should raise a new ticket with the relevant title and we'll try to help you.
