### ISSUE TITLE
Problems with creating nodes using quorum-maker: New nodes cannot synchronize blocks

### ISSUE THREAD

**Issue by weiliin** [Consensys-Incorporated/quorum#613]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

**Geth**
Version: 1.7.2-stable
Git Commit:  "0d0c507a5945ab63c8441007f022a143e2418f1e"
Quorum Version: 2.1.1
Architecture: amd64
Network Id: 1337
Go Version: go1.10.2
Operating System: linux

**quorum-maker**
image version: syneblock/quorum-maker:2.1.1_2.5.1

#### Expected behaviour
Use quorum-maker to create a node, join the network, and synchronize the highest blocks

#### Actual behaviour
New nodes cannot synchronize the latest blocks when the block height is greater than 10,000

#### Steps to reproduce the behaviour
1. Using quorum-maker to build a new network
2. Normal operation of the network, so that the height of the block to 10,000
3. Using quorum-maker to join the current network
4. Check the health of the second node

**Comment by weiliin** [comment]
**Some screenshots：**

![image](https://user-images.githubusercontent.com/42464600/50625341-8428f880-0f62-11e9-8a71-4d6c37d5ba7a.png)

![image](https://user-images.githubusercontent.com/42464600/50625351-9145e780-0f62-11e9-981e-7d6f4b93d06b.png)

![image](https://user-images.githubusercontent.com/42464600/50625319-5e9bef00-0f62-11e9-88fd-279350e6be5d.png)

**Comment by SatpalSandhu61** [comment]
Can you post a copy of your genesis config and let us know which consensus mechanism you are using please.

**Comment by weiliin** [comment]
> Can you post a copy of your genesis config and let us know which consensus mechanism you are using please.

{
  "config": {
    "chainId": 27582,
    "byzantiumBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip158Block": 0,
    "isQuorum": true
  },
  "alloc": {
    "0xb65a53d46b3d21341f2cceb0734d5cab83efc00d": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0xE0000000",
  "nonce": "0x0",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}

**Comment by SatpalSandhu61** [comment]
You didn't say which consensus you are using, but from your genesis block I assume it's raft. In which case I believe this may be an issue we are currently investigating whereby > 8192 block difference causes resync to fail.

**Comment by prd-fox** [comment]
See https://github.com/jpmorganchase/quorum/issues/614

**Comment by SatpalSandhu61** [comment]
Closing this ticket, as the issue is captured in #614.
