### ISSUE TITLE
Deploying a contract from inside a contract returns status success if gas limit is reached

### ISSUE THREAD

**Issue by devedse** [Consensys-Incorporated/quorum#617]
#### System information

Geth version: `Quorum version 2.1.1`

OS & Version: ???

Branch, Commit Hash or Release: ???

#### Expected behaviour

When I submit a transaction that deploys a subcontract and the transaction runs out of gas. The root transaction should fail:
https://ropsten.etherscan.io/tx/0xc0de88c738bd2e5f19c555fd900005d3fd8bf49202061915e9bb9a0cd99e1b40

#### Actual behaviour

Executing the exact same transaction on the private network results in a succeeding transaction with a very low gas usage:

![image](https://user-images.githubusercontent.com/2350015/50834571-a81a7e80-1354-11e9-8739-0eb42999ca82.png)

Summary (The child contract needs about 1.5 mil gas to deploy):
![image](https://user-images.githubusercontent.com/2350015/50834650-edd74700-1354-11e9-84d4-fd2929e40e50.png)
In the bottom right image you can see the transaction succeeding even though it did not actually create the contract.

The strange thing is that the following code also returns a new address for "child". childCount is also increased but a contract was never actually deployed.

```
    function createChild(string memory _name, uint256 _id) public onlyOwner {
        requireContractExists(_id, false);
        
        ZZReproReportChild child = new ZZReproReportChild(_id, _name);
        children[_id] = child;
        childCount++;
    }
```

This functionality could be very heavily abused in contracts that deploy child contracts, as that step could simply be skipped by providing a gas limit set too low.

#### Steps to reproduce the behaviour

Deploy this contract and call the createChild method with too little gas:
https://ropsten.etherscan.io/address/0x24c35f4ed8461bd8f67ef51d2ff390a306bede55#code

#### Backtrace

````
[backtrace]
````

**Comment by fixanoid** [comment]
Hi @devedse could you also provide us with your genesis for the Quorum net you set up? Thanks

**Comment by SatpalSandhu61** [comment]
I'm not actually able to reproduce this (using the geth console).

I just appear to see expected behaviour when invoking createChild():
Either the child contract appears to be created and I get a success status, or (with insufficient gas) it fails to create the child, in which case I see a failure (zero) status.
I also find that only about 60,000 gas is required to deploy the child.

As requested by fixanoid, can you please supply your genesis?
Also, can you tell me how you actually can validate that the child contract has been created correctly?

**Comment by devedse** [comment]
Hi both, I had to make a request to be able to get the genesis block, here it is:

```
{"alloc":{},"config":{"chainId":152,"byzantiumBlock":1,"eip150Block":0,"eip155Block":0,"eip158Block":0,"eip160Block":0,"eip161Block":0,"eip145Block":0,"eip140Transition":0,"eip211Transition":0,"eip214Transition":0,"eip658Transition":0,"istanbul":{"epoch":3000000,"policy":0},"isQuorum":true},"difficulty":"0x1","mixhash":"0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365","nonce":"0x0000000000000000","coinbase":"0x0000000000000000000000000000000000000000","timestamp":"0x0","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","gasLimit":"0x0E0000000","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f86fea9427fbdf7d1a4ae322a787319e4f06130f9b94633d942b57fc40e3de4ef67cf5a9698e8d598af52078e4b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0"}
```

The way I verified if the child contract is deployed is checking if the variables that are supposed to be set by the constructor are actually filled.

The workaround I've done for this is to actually implement this in the solidity contract (the last line):

```
    function createChild(string memory _name, uint256 _id) public onlyOwner {
        requireContractExists(_id, false);
        
        ZZReproReportChild child = new ZZReproReportChild(_id, _name);
        children[_id] = child;
        childCount++;
        require(child.name() == _name, "The child contract was not created successfully");
    }
```

Edit:
@SatpalSandhu61 , one more question, did you deploy my contract? If so, 60.000 gas is definitely not enough to deploy my version of the child contract.

**Comment by SatpalSandhu61** [comment]
@devedse ok, so this took a while to dig into... the issue seems to be related to EIP150. If EIP150 is enabled then the parent will retain 1/64th of it's gas when creating a child contract. This means that the parent still has gas available after the OOG failure of the child, and will continue to execute after the failed child creation.
I managed to recreate the issue and have also confirmed that disabling EIP150 causes the transaction to fully fail if the child creation fails. I’m not sure why the Ropsten behaviour is different, as the quorum code in that area is the same as upstream geth. However, I'm continuing to look further into this issue a bit further.

**Comment by SatpalSandhu61** [comment]
Some further digging revealed that your issue could be related to the homesteadBlock setting in genesis. If you don't enable homestead, then ErrCodeStoreOutOfGas is not trapped in instructions.go::opCreate(), and the child creation will return a valid address:
```
	if evm.ChainConfig().IsHomestead(evm.BlockNumber) && suberr == ErrCodeStoreOutOfGas {
		stack.push(evm.interpreter.intPool.getZero())	//push zero address onto stack
	} else if suberr != nil && suberr != ErrCodeStoreOutOfGas {
		stack.push(evm.interpreter.intPool.getZero())	//push zero address onto stack
	} else {
		stack.push(addr.Big())	//push address of new contract onto stack
	}
```
I suspect Ropsten has homestead enabled, hence exhibits different behaviour.
I would suggest enabling homestead and then re-testing. That won't stop the parent contract from continuing execution, but it does mean that a zero address will be returned for the child contract.

**Comment by SatpalSandhu61** [comment]
Note that we have now enabled homestead in the quorum-examples.
I'm going to close this issue for now, as the observed behaviour looks to be the same as upstream geth.
