### ISSUE TITLE
How to set a cluster with istanbul and constellation

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#620]
[node-template.tar.gz](https://github.com/jpmorganchase/quorum/files/2754394/node-template.tar.gz)

The upload file includes the working directory and the key files about setting cluster with istanbul and constellation .

I first open 5 constellation with following command, everything is OK

constellation-node --url=https://127.0.0.1:9001/ --port=9001 --workdir=node1c/node1c1 --socket=tm.ipc --publickeys=tm1.pub --privatekeys=tm1.key --othernodes=https://127.0.0.1:9001/  >>constellation1.log 2>&1 &

constellation-node --url=https://127.0.0.1:9002/ --port=9002 --workdir=node2c/node2c2 --socket=tm.ipc --publickeys=tm2.pub --privatekeys=tm2.key --othernodes=https://127.0.0.1:9001/  >>constellation2.log 2>&1 &

constellation-node --url=https://127.0.0.1:9003/ --port=9003 --workdir=node3c/node3c3 --socket=tm.ipc --publickeys=tm3.pub --privatekeys=tm3.key --othernodes=https://127.0.0.1:9001/  >>constellation3.log 2>&1 &

constellation-node --url=https://127.0.0.1:9004/ --port=9004 --workdir=node4c/node4c4 --socket=tm.ipc --publickeys=tm4.pub --privatekeys=tm4.key --othernodes=https://127.0.0.1:9001/  >>constellation4.log 2>&1 &

constellation-node --url=https://127.0.0.1:9005/ --port=9005 --workdir=node5c/node5c5 --socket=tm.ipc --publickeys=tm5.pub --privatekeys=tm5.key --othernodes=https://127.0.0.1:9001/  >>constellation5.log 2>&1 &

And then I open 5 geth with following command, everything is OK too

PRIVATE_CONFIG=node1c/node1c1/tm.ipc nohup geth --datadir node1/new-node-1 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30303 --unlock 0 --password passwords.txt >> node1.log 2>&1 & 

PRIVATE_CONFIG=node2c/node2c2/tm.ipc nohup geth --datadir node2/new-node-2 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22001 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30304 --unlock 0 --password passwords.txt >> node2.log 2>&1 &

PRIVATE_CONFIG=node3c/node3c3/tm.ipc nohup geth --datadir node3/new-node-3 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22002 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30305 --unlock 0 --password passwords.txt >> node3.log 2>&1 &

PRIVATE_CONFIG=node4c/node4c4/tm.ipc nohup geth --datadir node4/new-node-4 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22003 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30306 --unlock 0 --password passwords.txt >> node4.log 2>&1 &

PRIVATE_CONFIG=node5c/node5c5/tm.ipc nohup geth --datadir node5/new-node-5 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22005 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30307 --unlock 0 --password passwords.txt >> node5.log 2>&1 &

But I get following error in the  constellation log as following and I can not deploy private smart contract with web3.js

 

08:13:36 [WARN] Synchronization failed: HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 9001
  secure               = True
  requestHeaders       = []
  path                 = "/partyinfo"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}

How can I solve this problem? Thank you.

**Comment by prd-fox** [comment]
Hi Matrixoneken,

The issue you are facing is a known issue with Constellation and TLS, see https://github.com/jpmorganchase/constellation/issues/104

To get around this issue, you could go the same route as the example script and start each Constellation node on a different local IP (i.e. 127.0.0.1, 127.0.0.2, 127.0.0.3 etc) which should solve the issue.

**Comment by matrixoneken** [comment]
I have changed the command as following:

constellation-node --url=https://127.0.0.1:9001/ --port=9001 --workdir=node1c/node1c1 --socket=tm.ipc --publickeys=tm1.pub --privatekeys=tm1.key --othernodes=https://127.0.0.1:9001/


constellation-node --url=https://127.0.0.2:9002/ --port=9002 --workdir=node2c/node2c2 --socket=tm.ipc --publickeys=tm2.pub --privatekeys=tm2.key --othernodes=https://127.0.0.1:9001/


 constellation-node --url=https://127.0.0.3:9003/ --port=9003 --workdir=node3c/node3c3 --socket=tm.ipc --publickeys=tm3.pub --privatekeys=tm3.key --othernodes=https://127.0.0.1:9001/


constellation-node --url=https://127.0.0.4:9004/ --port=9004 --workdir=node4c/node4c4 --socket=tm.ipc --publickeys=tm4.pub --privatekeys=tm4.key --othernodes=https://127.0.0.1:9001/

constellation-node --url=https://127.0.0.5:9005/ --port=9005 --workdir=node5c/node5c5 --socket=tm.ipc --publickeys=tm5.pub --privatekeys=tm5.key --othernodes=https://127.0.0.1:9001/


and I also have error as following:


09:50:42 [WARN] tls-client-cert.pem's hostname (127.0.0.1) is different from the one given in the configuration (127.0.0.3). This may cause connection problems.
09:50:42 [WARN] Synchronization failed: HttpExceptionRequest Request {
  host                 = "127.0.0.1"
  port                 = 9001
  secure               = True
  requestHeaders       = []
  path                 = "/partyinfo"
  queryString          = ""
  method               = "POST"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.sendBuf: resource vanished (Broken pipe))

**Comment by prd-fox** [comment]
Did you remove the existing key and trust stores? 
They will contain the old hostname information, so they will now contain incorrect data - remove them and try again

**Comment by matrixoneken** [comment]
[node-template.tar.gz](https://github.com/jpmorganchase/quorum/files/2762413/node-template.tar.gz)
The problem about constellation has been solved.But I still can not deploy the private contract.
The upload file node-template.tar.gz is my work directory and the key files about  setting cluster with istanbul and constellation .


1)  Unzip the file and cd node-template.
2)  Run geth init with following command:
    geth --datadir node1/new-node-1 init node1/genesis.json
   geth --datadir node2/new-node-2 init node2/genesis.json
    geth --datadir node3/new-node-3 init node3/genesis.json
   geth --datadir node4/new-node-4 init node4/genesis.json
   geth --datadir node5/new-node-5 init node5/genesis.json

3) Run constellation-node with follwing command:
  
 constellation-node --url=https://127.0.0.1:9001/ --port=9001 --workdir=node1c/node1c1 --socket=tm.ipc --publickeys=tm1.pub --privatekeys=tm1.key --othernodes=https://127.0.0.1:9001/  >>constellation1.log 2>&1 &

constellation-node --url=https://127.0.0.2:9002/ --port=9002 --workdir=node2c/node2c2 --socket=tm.ipc --publickeys=tm2.pub --privatekeys=tm2.key --othernodes=https://127.0.0.1:9001/  >>constellation2.log 2>&1 &

constellation-node --url=https://127.0.0.3:9003/ --port=9003 --workdir=node3c/node3c3 --socket=tm.ipc --publickeys=tm3.pub --privatekeys=tm3.key --othernodes=https://127.0.0.1:9001/  >>constellation3.log 2>&1 &

constellation-node --url=https://127.0.0.4:9004/ --port=9004 --workdir=node4c/node4c4 --socket=tm.ipc --publickeys=tm4.pub --privatekeys=tm4.key --othernodes=https://127.0.0.1:9001/  >>constellation4.log 2>&1 &

constellation-node --url=https://127.0.0.5:9005/ --port=9005 --workdir=node5c/node5c5 --socket=tm.ipc --publickeys=tm5.pub --privatekeys=tm5.key --othernodes=https://127.0.0.1:9001/  >>constellation5.log 2>&1 &

4) Run geth with following command:

PRIVATE_CONFIG=node1c/node1c1/tm.ipc nohup geth --datadir node1/new-node-1 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30303 --unlock 0 --password passwords.txt >> node1.log 2>&1 & 

PRIVATE_CONFIG=node2c/node2c2/tm.ipc nohup geth --datadir node2/new-node-2 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22001 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30304 --unlock 0 --password passwords.txt >> node2.log 2>&1 &

PRIVATE_CONFIG=node3c/node3c3/tm.ipc nohup geth --datadir node3/new-node-3 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22002 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30305 --unlock 0 --password passwords.txt >> node3.log 2>&1 &

PRIVATE_CONFIG=node4c/node4c4/tm.ipc nohup geth --datadir node4/new-node-4 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22003 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30306 --unlock 0 --password passwords.txt >> node4.log 2>&1 &

PRIVATE_CONFIG=node5c/node5c5/tm.ipc nohup geth --datadir node5/new-node-5 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22004 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30307 --unlock 0 --password passwords.txt >> node5.log 2>&1 &

Everything is OK . The cluster is running.

[TestProjectV2.10.tar.gz](https://github.com/jpmorganchase/quorum/files/2762448/TestProjectV2.10.tar.gz)

When I use the web3.js to deploy the private smart contract and set the privatefor  with the value of node 5 pub key (The detail please see the TestDeployMainContract.js in TestProjectV2.10.tar.gz), everything is Ok

But when I get the private contract with the node 5 IP address(The detail please see the TestGetMainContract.js in TestProjectV2.10.tar.gz) , I get following error and I do not find any error in the log files.


undefined
Error: Returned values aren't valid, did it run Out of Gas?



How to solve this problem ? Thank you.

**Comment by prd-fox** [comment]
You've got 5 different genesis files, so you're running 5 separate networks, not 5 nodes in 1 network. Thus the transaction sent into node 1 is not visible to any other node.
Also the `static-nodes.json` only contains each nodes own address, so the peers have no way of discovering each other - like in Constellation/Tessera, you could put node1 in all the files so node1 acts as a boot node, or you can run a dedicated `bootnode` to achieve this.

Did you use https://github.com/jpmorganchase/istanbul-tools to generate the files? If not, give it a try. If you need help on how to use it, let me know.

**Comment by matrixoneken** [comment]
I have used istanbul-tools to generate all files

As description in url https://github.com/jpmorganchase/quorum/wiki/From-Scratch#quorum-with-istanbul-bft-consensus, I edit genesis.json file and update alloc field with the account  address.
For each node, I do the job following the step so I have 5 genesis.json files. 
As your answer, you say for a network , it only has one genesis.json. Does it means the alloc address for 5 nodes need to save in one  genesis.json as the 7nodes example?
If all alloc address save in one genesis.json file and all nodes open in the same time ,I think it is OK.
But for my business, I open node one by one. For example, I open node 1 today and open node 2 at the next day and each node is at different client server.  I don't know how  the new node join the cluster and how to edit the genesis.json file. Do I need shutdown the node 1 and add the node 2 address to the node 1 genesis.json file and restart the node 1? Do I need to find each old node address  and add these addresses  to the genesis.json for the new node?

For static-nodes.json, do you mean as following for all node exception node 1?
[
	"enode://d4b156402525892d8cc8952bc9178d41944f2d3f7a9b27f20e6e11975227bfcd235a1f606766a80beb404b82f295f5d7f867771d6d69ecd3a9302c0045c673ce@127.0.0.1:30303?discport=0",
"enode://0fc2c5f8f8e5e6ddd4f0877a28ea4f00e119c29401b1fdf0992a0a70e249248d9394b9098c2d6c379def79a456be6bf0d74ef5ce0170164a20be5dc5f71abeab@127.0.0.1:30304?discport=0"
]

This example is the static-nodes.json for node 2 and the first line is the node 1 address and the second line is the node 2 address.

Thank you.

**Comment by prd-fox** [comment]
The genesis.json file contains a lot of startup information, some of it being what should go inside Block 0. All nodes that want to be part of the same network need to agree on what Block 0 contains, so they need to use the same genesis file. 
You would need to put all the `alloc` fields in a single file before initialising the nodes; as you noted, this is what happens in the 7-node example.

For the 5 nodes you have currently, they will all use the same genesis file, but they do not need to come online at the same time. Ignoring rules about IBFT (which requires >66% of validators online), there are no restrictions about when a node joins the network, so doing 1 per day (or 1 per month, etc) is absolutely fine, so long as they all used **the same** genesis file. There will no need to restart any existing nodes.

If, in the future, you want to add a new node (say, node number 6) to the network, you **will not** be able to allocate any funds for any account it manages in the genesis file. Instead, to give its account some ether, you must perform a value transaction transaction from one of the existing accounts to the new account.

The golden rule: never change the genesis file, so make sure it contains all the allocations you need before creating/starting the network!

---

For the `static-nodes.json`, yes that should work. All nodes will connect to node 1, so the network is well connected.

**Comment by matrixoneken** [comment]
@prd-fox  
Thank you for your answer
I want to kown more detail so I  give an example.

For example
Now I must open node 1 on server 1
I use  istanbul-tools to make the working directory and the key files.

The geneis.json for node 1 as following:

{
    "config": {
        "chainId": 10,
        "eip150Block": 1,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 1,
        "eip158Block": 1,
        "byzantiumBlock": 1,
        "istanbul": {
            "epoch": 30000,
            "policy": 0
        },
        "isQuorum": true
    },
    "nonce": "0x0",
    "timestamp": "0x5c3be7f5",
    "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f85ad59442ab53a6e26c82ec23beb3100a0b1395546a4fd7b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
    "gasLimit": "0xe0000000",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
        "59f5d6dc6f53d6e55b65246a51e0c17e86cfd7b4": {
            "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
        }
    },
    "number": "0x0",
    "gasUsed": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

and the static-nodes.json for node 1 as following:
[
	"enode://d4b156402525892d8cc8952bc9178d41944f2d3f7a9b27f20e6e11975227bfcd235a1f606766a80beb404b82f295f5d7f867771d6d69ecd3a9302c0045c673ce@127.0.0.1:30303?discport=0"
]




Next  I want to open node 2 on server 2 and join the cluster where the node 1 is deployed in.

I konw the static-nodes.json for node 2 as following:

[
"enode://d4b156402525892d8cc8952bc9178d41944f2d3f7a9b27f20e6e11975227bfcd235a1f606766a80beb404b82f295f5d7f867771d6d69ecd3a9302c0045c673ce@127.0.0.1:30303?discport=0",
"enode://0fc2c5f8f8e5e6ddd4f0877a28ea4f00e119c29401b1fdf0992a0a70e249248d9394b9098c2d6c379def79a456be6bf0d74ef5ce0170164a20be5dc5f71abeab@127.0.0.1:30304?discport=0"
]


and the node 2 acocunt address is ' e261ca910714047692a6b315018c329f5c9b8f13'

Can you tell me what the geneis.json  is?  Thank you.

**Comment by prd-fox** [comment]
The genesis file for node 2 will be the same as the one for node 1, which you posted above.
As I said, the same exact genesis file must be used for every node in the network.

There is an assigned balance for the account you set up under node 1 (in the `alloc` section), but there is not any balance assigned to the account for node 2, or indeed any other account.

This is fine, assuming you only want node1 account to have an initial balance. If you want all the nodes to have a starting balance, you need to add those under the `alloc` section too.

Below is a sample for that with node1's and node2's account:
```
"alloc": {
    "59f5d6dc6f53d6e55b65246a51e0c17e86cfd7b4": {
        "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
    "e261ca910714047692a6b315018c329f5c9b8f13": {
        "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
    },
},
```
This must be present in **all the nodes genesis file**, since they must be use the same file.

This of course works when you know all the accounts ahead of time, but what about adding a node (e.g. node 6) some time later, after the network is set up?
This new node **still has to use the same genesis**, but that doesn't specify any initial balance for the new account - the only way is to transfer some ether from one of the existing accounts to this new one using a value transfer transaction.

Hope this helps :)

**Comment by matrixoneken** [comment]
@prd-fox
All 5 nodes have the same genesis file which is like the node 1.
And the  static-nodes.json  for node 2 , node 3, node 4,node 5, I have added the address of node 1
I can run 5 constellation without  any problem.

But when I run the node2 with  following commad:

PRIVATE_CONFIG=node2c/node2c2/tm.ipc nohup geth --datadir node2/new-node-2 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22001 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 30304 --unlock 0 --password passwords.txt >> node2.log 2>&1 &


I got following error in node 2 log file and can not run the geth for node 2

Fatal: Could not list accounts: index 0 higher than number of accounts 0


Can you tell me how to solve this problem? Thank you.

**Comment by prd-fox** [comment]
It means there is no account in the Quorum keystore.
`--unlock 0` tells Quorum to unlock account number 0 on starting up, using the provided password file, but Quorum states that there is no account available to use.

The archive you uploaded had a key available for node 2 - did you remove it?

**Comment by matrixoneken** [comment]
@prd-fox
You are right and now I can deploy the cluster and deploy  smart contract. Thank you very much.
I also have problem to ask

As you saying if I want to the  node1 account to have an initial balance, I must set the alloc section of node 1.
But for my business, the smart contract is only for saving or getting some information. I don't want any initial balance for any node. How to set the following genesis file ? 


{
    "config": {
        "chainId": 10,
        "eip150Block": 1,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip155Block": 1,
        "eip158Block": 1,
        "byzantiumBlock": 1,
        "istanbul": {
            "epoch": 30000,
            "policy": 0
        },
        "isQuorum": true
    },
    "nonce": "0x0",
    "timestamp": "0x5c3be7f5",
    "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f85ad59442ab53a6e26c82ec23beb3100a0b1395546a4fd7b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
    "gasLimit": "0xe0000000",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
        "996a0299b92f60cc02b152e66a0fa7b07b7e3bd2": {
            "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
        }
    },
    "number": "0x0",
    "gasUsed": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

Thank you!

**Comment by prd-fox** [comment]
Leave the `alloc` section blank.
i.e.
```
"alloc": {
}
```

**Comment by prd-fox** [comment]
No new issues for a few days, so closing this. If you have more questions, feel free to open a new issue.
