### ISSUE TITLE
How to check private contract party?

### ISSUE THREAD

**Issue by a651694192** [Consensys-Incorporated/quorum#626]
If I'm one of the participate of a private contract, how can I check the member list of all participates? 
BTW, I saw this information is stored in transaction manager part packed with transaction payload, and there is a new API "eth_getQuorumPayload",  if this can help me get my info?

**Comment by prd-fox** [comment]
You cannot see the members of a private contract.

Only the user who created the transaction knows who the recipients are, so if the transaction that created a contract was sent from someone else, you have to way to recover that information.
If you were the user who sent the transaction, then the recipients are stored inside the Transaction Manager's database, but it is not accessible through any API.
