### ISSUE TITLE
How to open a cluster with istanbul and constellation

### ISSUE THREAD

**Issue by matrixoneken** [Consensys-Incorporated/quorum#627]
I want to set a cluster with istanbul and constellation
[tempwork.tar.gz](https://github.com/jpmorganchase/quorum/files/2791011/tempwork.tar.gz)
Above files are my working directory and key files which is built by istanbul-tool

Please upzip the file and cd  tempwork in terminal

First run init with following command
geth --datadir qdata/c1/node1 init istanbul-genesis.json
geth --datadir qdata/c2/node2 init istanbul-genesis.json
geth --datadir qdata/c3/node3 init istanbul-genesis.json
geth --datadir qdata/c4/node4 init istanbul-genesis.json
geth --datadir qdata/c5/node5 init istanbul-genesis.json

Second run constellation with following command

constellation-node --url=http://192.168.193.38:9001/ --port=9001 --workdir=qdata/dd1 --socket=tm.ipc --publickeys=tm1.pub --privatekeys=tm1.key --othernodes=http://192.168.193.38:9001/  --tls=off  >>logs/constellation1.log 2>&1 &

constellation-node --url=http://192.168.193.38:9002/ --port=9002 --workdir=qdata/dd2 --socket=tm.ipc --publickeys=tm2.pub --privatekeys=tm2.key --othernodes=http://192.168.193.38:9001/  --tls=off  >>logs/constellation2.log 2>&1 &

constellation-node --url=http://192.168.193.38:9003/ --port=9003 --workdir=qdata/dd3 --socket=tm.ipc --publickeys=tm3.pub --privatekeys=tm3.key --othernodes=http://192.168.193.38:9001/  --tls=off  >>logs/constellation3.log 2>&1 &

constellation-node --url=http://192.168.193.38:9004/ --port=9004 --workdir=qdata/dd4 --socket=tm.ipc --publickeys=tm4.pub --privatekeys=tm4.key --othernodes=http://192.168.193.38:9001/  --tls=off  >>logs/constellation4.log 2>&1 &

constellation-node --url=http://192.168.193.38:9005/ --port=9005 --workdir=qdata/dd5 --socket=tm.ipc --publickeys=tm5.pub --privatekeys=tm5.key --othernodes=http://192.168.193.38:9001/  --tls=off  >>logs/constellation5.log 2>&1 &

Finally run geth with following command

PRIVATE_CONFIG=qdata/dd1/tm.ipc nohup geth --datadir qdata/c1/node1 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 21000 --unlock 0 --password passwords.txt >> logs/node1.log 2>&1 &

PRIVATE_CONFIG=qdata/dd2/tm.ipc nohup geth --datadir qdata/c2/node2 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22001 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 21001 --unlock 0 --password passwords.txt >> logs/node2.log 2>&1 &

PRIVATE_CONFIG=qdata/dd3/tm.ipc nohup geth --datadir qdata/c3/node3 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22002 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 21002 --unlock 0 --password passwords.txt >> logs/node3.log 2>&1 &

PRIVATE_CONFIG=qdata/dd4/tm.ipc nohup geth --datadir qdata/c4/node4 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22003 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 21004 --unlock 0 --password passwords.txt >> logs/node4.log 2>&1 &

PRIVATE_CONFIG=qdata/dd5/tm.ipc nohup geth --datadir qdata/c5/node5 --nodiscover --istanbul.blockperiod 5 --syncmode full --mine --minerthreads 1 --verbosity 5 --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 22004 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul--emitcheckpoints --port 21005 --unlock 0 --password passwords.txt >> logs/node5.log 2>&1 &

In the directory log. I can find following error in each log about geth 

 Failed to decode message from payload    address=0x82d9fDb2E4c29A00A117256C73Dad15B76f8fCc3 err="unauthorized address"

 Node Permissioning is Disabled. 
TRACE[01-24|17:30:51] Rejected peer before protocol handshake  id=4dd5cfaccad8d849 addr=192.168.193.38:55488 conn=inbound    err="connected to self"

I want to know how to solve this problem. Thank you!

**Comment by matrixoneken** [comment]
How solve following error. Thank you

TRACE[01-31|12:18:42] Catch up round                           address=0xd789B0416659C224E2e2c633385E3e65F7506c29 old_round=2  old_seq=1 old_proposer=0x90C11f5620fD5d825c28a9252E88f33FcCE06D21 new_round=3 new_seq=1 new_proposer="&{validators:[0xc420254ce0] policy:0 proposer:0xc420254ce0 validatorMu:{w:{state:0 sema:0} writerSem:0 readerSem:0 readerCount:0 readerWait:0} selector:0xbc1730}"
ERROR[01-31|12:18:42] Failed to decode message from payload    address=0xd789B0416659C224E2e2c633385E3e65F7506c29 err="unauthorized address"
DEBUG[01-31|12:18:45] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s

**Comment by prd-fox** [comment]
If you run:
> istanbul.getValidators()

you will see that there is only one validator set up in the system.

This validator address is derived from the nodekey associated to one of the nodes, but it looks like none of the nodekeys correspond to that address.

Are you sure you used the the keys and genesis from the same run of istanbul-tools? How many nodes did you generate using the tool? If it was all 5 nodes, then there should be 5 validators in the validator list, instead of 1. If you only meant to have 1 validator, then the other 4 should not be mining where you would get this address.

Can you share what command you used for istanbul-tools?

I'm a bit confused as to why none of the addresses in your logs, validator list and nodekeys line up - the only reason I can think is if you used the files from multiple runs of the tool, which would not match each other.

**Comment by prd-fox** [comment]
Since there are no updates, I am closing this issue. Please open another ticket if you have other questions/issues.
