### ISSUE TITLE
Unable to get raft working with DNS, after changing IPs

### ISSUE THREAD

**Issue by pmitra43** [Consensys-Incorporated/quorum#628]
#### System information

Geth version: `geth version`

OS & Version: Linux

Quorum version: 2.1.1
Constellation version: 0.3.2, TLS: off

#### Expected behaviour
Quorum nodes, with DNS and IP's behind them. When the IP of a node changes, but not the DNS, geth, constellation and raft should keep working.

#### Actual behaviour
There are two scenarios tried:
1. Without raftjoinexisting:
Geth and constellation works for all the nodes. But, other nodes (for whom the IP were not changed) complains `rafthttp: health check for peer 1 could not connect: dial tcp <old_ip>:<raft_port>: getsockopt: no route to host`

2. With raftjoinexisting:
When raft.removePeer and raft.addPeer is executed, a new raftId is generated serially, and when updated IPs in static nodes, error appears as `rafthttp: rejected the stream from peer <raftID of older node> since it was removed`
To fix, we need to make another entry in static nodes, with duplicate enode ID, and the new IP.

Raft does not update the DNS's IP itself, and also to change IP of node, existing static nodes can only be appended, with duplicate enode IDs

**Comment by fixanoid** [comment]
@pmitra43, how are you? When an address of a node changes, it means that this is a brand new node from perspective of the raft network and that requires remove/add peer interaction. We'll test this scenario and update if its currently broken (your scenario #2 should be working correctly).

**Comment by pmitra43** [comment]
@fixanoid I am good, thank you. Hope you are doing well.
For the second scenario, does that mean that I will have to keep a duplicate enode entry with the older IP in its place, and append the new IP in permissioned-nodes and static-nodes file, before I do a restart of all the nodes(if needed)?

**Comment by fixanoid** [comment]
@pmitra43 having a duplicate entry in the static-nodes is fine. You may also recreate it by running raft.cluster on any node and using it to generate a new static-nodes file -- after a chain has been primed (that is, was up and had elected a leader at least once)

**Comment by jbhurat** [comment]
@pmitra43 I just verified and you do not need a duplicate entry in static-nodes file, you can replace the existing one, with new IP address and starting the new node with `--raftjoinexisting RAFT_ID` option

**Comment by pmitra43** [comment]
@jbhurat does that mean I don't even need to do a raft.removePeer? The IP address of the node will change in place, even if it is somewhere in between?

**Comment by jbhurat** [comment]
You will still have to do `raft.removePeer` and `raft.addPeer`, followed by updating static-nodes.json and starting `geth` using option `--raftjoinexisting RAFT_ID`
