### ISSUE TITLE
can a public smart contract invoke a function of a private contract 

### ISSUE THREAD

**Issue by Aghorb** [Consensys-Incorporated/quorum#629]
Hi, 
I know that public contracts cannot access the contents of the private contract, this is according to https://github.com/jpmorganchase/quorum/blob/06342c9490f9fe644c66dfe60d798b285e17338c/docs/design.md.
I want to know if this is applied even if the private and the public contract are deployed by the same node? In fact, I found that it is possible here: github.com/jpmorganchase/quorum/issues/357, : "On node 1 i can properly add SimpleStorage-contract to StorageContainer and also i can get private value 45 from it. On node 7 or 4 i get value 0. So all works properly."
any help please?

**Comment by fixanoid** [comment]
Hey, so public smart contracts are be unable to read values of private
contracts even on the same node. A dapp may do this when reading the from
the same node.

**Comment by Aghorb** [comment]
thx again fixanoid, if you can please explain why dapp are able to do this.

**Comment by fixanoid** [comment]
So a smart contract lives on the blockchain and is executed by the EVM of
every node - this is where we limit public vs private contract access.

In a dapp case, the code executed outside of evm, and connects to whatever
node is used to read the data. This connection is not open to the world and
means that the dapp may call quorum node to read data on any contract it
has access to.
