### ISSUE TITLE
Clarification blockmaker node

### ISSUE THREAD

**Issue by jaguarg** [Consensys-Incorporated/quorum#63]
Hi, 

Please can you clarify if all transactions API calls should be sent to blockmaker nodes ? 

I find that when sending to non-blockmaker nodes, transactions are not being processed. I would like to know if this the expected behaviour or if something is wrong with my setup . 

Thank you

**Comment by magooster** [comment]
Transactions should be sent to your 'local' node for signing...

A node will only accept remote transactions from the network if its synchronised with the chain, if your running a single maker you need to pass the --singleblockmaker flag to force this.

**Comment by tylobban** [comment]
@jaguarg hi, please provide steps to reproduce? Filling out the [Issue Template](https://github.com/jpmorganchase/quorum/blob/master/.github/ISSUE_TEMPLATE.md) will give the information needed. @magooster's comments above are correct.

**Comment by jaguarg** [comment]
Hello, 

I have rebuild my environment and it is good now. Thank you. I have an issue with private transactions which I will raise on a separate thread .
