### ISSUE TITLE
GasUsed is always 0 for private transaction

### ISSUE THREAD

**Issue by Himanshu-Pandey** [Consensys-Incorporated/quorum#630]
#### System information

Geth version: `Any version`

OS & Version: Linux

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
gasUsed should be some non zero value

#### Actual behaviour
gasUsed is always zero

**Comment by fixanoid** [comment]
@Himanshu-Pandey private txns are set to be gas-less -- so while initially submitted with gas, once they are placed on the chain with private v value, the gas is not accounted for with them. What are you trying to accomplish?
