### ISSUE TITLE
Failed to verify proposal 

### ISSUE THREAD

**Issue by EdsonAlcala** [Consensys-Incorporated/quorum#631]
#### System information

Geth version: Geth/Node 1/v1.8.12-stable/linux-amd64/go1.9.4

OS & Version: Linux Alpine

Branch, Commit Hash or Release:  Quorum v2.2.1

#### Expected behaviour

I should be able to deploy smart contracts

#### Actual behaviour

In 7 nodes sample:
"ERROR[01-28|12:40:02.056] Impossible reorg, please file an issue oldnum=2336 oldhash=67e897…9f12c9 newnum=2336 newhash=67e897…9f12c9"

In custom 4 nodes example running in same container:
WARN [01-28|12:31:38.979|consensus/istanbul/core/preprepare.go:85] Failed to verify proposal address=0x8304cB99e989EE34af465Db1CF15E369D8402870 from=0x8304cB99e989EE34af465Db1CF15E369D8402870 state="Accept request" err="block in the future" duration=20.260243ms

#### Steps to reproduce the behaviour

Try to deploy a contract using web3.js and without privateFor. 
Then the txhash is returned
But eth.getTransactionReceipt returns null

#### Backtrace

````
[backtrace]
````

**Comment by SatpalSandhu61** [comment]
It looks like the time is not sync'ed across your nodes. You need to ensure the clock is in sync across all nodes.

**Comment by EdsonAlcala** [comment]
Even when they are in the same docker container?

**Comment by SatpalSandhu61** [comment]
Weird, I can't see how it would happen if they are in the same container.
Are you adding a node to an already existing network (with an existing blockchain)? Is it possible that the blocks were minted with a different (future) time?

**Comment by EdsonAlcala** [comment]
ok, I found the problem, it was the timestamp value I was setting in the genesis file. Once I set to 0x00, it started to work properly.

**Comment by SatpalSandhu61** [comment]
Fantastic. Closing this ticket now.
