### ISSUE TITLE
Connect quorum tu tessera via tcp

### ISSUE THREAD

**Issue by alexsplashex** [Consensys-Incorporated/quorum#638]
Hi there.
I have 2 containers with tessera connected to each other.
The tessera-config.json configuration file that I use is [here](https://gist.github.com/dmytronasyrov/195d8f6525fe04dfb629fdcf8a28aea3).

Please help me connect the quorum with a running tessera cluster using TCP connection.

Quorum-tessera communication was taken from one of your examples
```
 {
       "app": "Q2T",
       "enabled": true
       "serverSocket": {
         "type": "INET",
         "port": 9100,
         "hostName": "http://10.50.1.2"
       },
       "communicationType": "GRPC"
```

**Comment by prd-fox** [comment]
Although Tessera supports listening for Quorum requests over HTTP, Quorum itself doesn't support making those requests at the moment, and will only do so over IPC files.

**Comment by fixanoid** [comment]
@alexsplashex theres an older pull that you may review to see if you could update your own fork: https://github.com/jpmorganchase/quorum/pull/405/files but as per @prd-fox this is currently not supported.
