### ISSUE TITLE
Provide Information about the Derivative Maintenance

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#640]
It would be of benefit if the project would provide information about:

* how is the original version of geth extended/altered ?

As an example:

* Module A was simply copied. Updates in the original code are applied manually (with every release)
* Module B is altered dynamically, via "monkey-patching"
* Module C uses a plugin-kind model, which was contributed back to the original Ethereum codebase
* etc. etc.

Naturally one could find those things out by reviewing the code-base, but the effort can become high, and the information is anyway of general interest.

As an example, an evaluator who needs to assess "how much effort is it for the team to keep Quorum in synch with the original Ethereum", will benefit from a ready presentation/document.

(It looks like such information would belong into the `/docs` folder.)

**Comment by fixanoid** [comment]
Hi @lazaridiscom, as pointed out, we currently don't keep a doc and expect developers to review geth vs quorum source bases when needed. Besides edification and familiarity, what would something like this be useful for? Thanks!

**Comment by ghost** [comment]
Edification and familiarity, as you say, could possibly be alreadey enough reason, especially when its an high-profile project.

See, your README is very good (compared to other projects in the blockchain-domain).

Getting an Architectural Overview would cost any interested party much time - but you provide a nice graphic for this.

But for this Derivative stuff, things are different:

## Current Situation

When I saw this:

> Quorum is a fork of go-ethereum and is updated in line with go-ethereum releases.

I was immediately wondring "what mechanisms do they use for the fork?".

I was wondering, because other projects do a "copy & modify" in a way that the effort to stay in synch with the original project becomes too high, leading e.g. the platform staying back, supporting only older versions of Solidity (e.g. AION, TRON).

In order to assess the quality of Quorum, the "Derivative Maintenance" is (for me a least) one of the most important factors.

And besides that, I'm just curious how a JPM related team solves this problem.

So, just think about if you could make something like this (note; this "Derivative Maintenance" I came up quickly, not sure if the terminology fits, but you get the idea)

## Expected

 Quorum is a fork of go-ethereum and is updated in line with go-ethereum releases (for the technical details about how keep up see [Derivative Maintenance](dummy-link)).

**Comment by jpmsam** [comment]
Hi @lazaridiscom we have a team that is dedicated to supporting Quorum and part of that support is following the upstream updates, how they will impact Quorum and identifying stable releases that we merge/pull into Quorum. You can typically follow that work as PRs and contribute to it.[1.8.18](https://github.com/jpmorganchase/quorum/pull/639) 
We also have a testing suite for Quorum features that we run for upgrades and Quorum enhancements.
I am closing this issue but please feel free to engage with the team on slack for more info.

**Comment by ghost** [comment]
> Quorum is designed to develop and evolve alongside Ethereum. Because it only minimally modifies Ethereum’s core, Quorum is able to incorporate the majority of Ethereum updates quickly and seamlessly.

Source: https://www.jpmorgan.com/country/us/en/Quorum#section_1320553542030

Essentially, I try to evaluate the above marketing-statement:

A "Highest-Quality" Project would provide the means to evaluate the above statement (e.g., in the semiconductor domain, companies/projects do this usually: providing means for super-simple evaluations).

That's why I asked for this document (which I really believe a project of this caliber should provide anyway).

Now, it is possible for me (and any other person with the relevant abilities) to extract this info by reviewing/monitoring https://github.com/jpmorganchase/quorum/pull/639, but the effort is quite high.

> I am closing this issue but please feel free to engage with the team on slack for more info.

You should not close issues that fast, especially when they address (possibly a bit indirectly) Product(!) Management (as this issue does).

I selected this medium (Issue-Tracker, Asynchronous) because I'm quite allergic to chat-systems, especially Slack.

But my sincere thanks for you offer.

.

**Comment by ghost** [comment]
@jpmsam, may I ask for a favor?

Can you please ping this issue on slack? Possibly some developer of yours has interest to document this further.

It would additionally help to reopen the issue. I really think this documentation is missing (especially because the marketing-statement within https://www.jpmorgan.com/country/us/en/Quorum#section_1320553542030 is not backed up by a demonstration of "how its done")
