### ISSUE TITLE
how to debug quorum codes?

### ISSUE THREAD

**Issue by jiebanghan** [Consensys-Incorporated/quorum#643]
Hi there,
I am a learner of quorum here, so I want to study the golang codes of it. I want to debug it.
My quesion is : 1. I have compiled quorum geth on windows,  so how could I debug the codes with constellation-node?
2. how to modify the makefile to make the geth contain debug information in linux, I don't know how to add the debug flag "-gcflags "-N -l"".I am ready to debug it with delve in linux.
3. would you please  give me some aggesion about how to debug the codes? thank you very much.

**Comment by SatpalSandhu61** [comment]
You mention windows and linux - are you trying on windows or linux? (Quorum isn't currently supported on native windows.)
Instead of using delve, are you able to use Intellij with the golang plugin?
I had issues when I tried to use delve (although that was an earlier version of delve). If you can use Intellij then it's really easy to run and debug geth within Intellij.
Also, if you want to debug and learn, you may find it easier to use Tessera rather than Constellation.

**Comment by jiebanghan** [comment]
thank you . I will try it.

**Comment by jiebanghan** [comment]
so you mean we can debug and learn codes of quorum with Intellij with the golang plugin on Windows？And the Tessera's function is similar with Constellation? thank you

**Comment by SatpalSandhu61** [comment]
Not natively on windows - currently we don't support windows build, but are working on it. You can run quorum under windows using vagrant; It is possible to debug quorum running under vagrant, but it's quite fiddly to set it up.
You're better off working on linux. The docs here may be of help to you: https://github.com/jpmorganchase/quorum-examples#getting-started

Tessera performs the same functionality as Constellation; however Tessera is the enterprise version, written in Java and is our preferred transaction manager.

**Comment by jiebanghan** [comment]
thank you

**Comment by jiebanghan** [comment]
My new question is how to modify the makefile in order to add debug information after running make all command? thank you.

**Comment by SatpalSandhu61** [comment]
Closing this ticket now. Please reopen if you have further questions relating to this.
Note that the quorum Slack channel is usually a better place to ask questions though.

**Comment by SatpalSandhu61** [comment]
Rather than try to modify the Makefile, you're better off building geth manually:
```
go build -o ./build/bin/geth   -gcflags=all='-N -l' -v ./cmd/geth
```
However, as I mentioned you'll find it tricky to debug using delve. Since geth runs multiple threads and needs to talk to the other nodes, as soon as you hit a breakpoint you will get behavioural issues.
When I want to work out what is happening in geth, I tend to use log statements. I only use the debugger if there is a specific issue and I need to investigate the behaviour at a particular point in the code.

**Comment by SatpalSandhu61** [comment]
Closing this ticket now.
Note that the quorum Slack channel is usually a better place to ask questions.

**Comment by jiebanghan** [comment]
Hi , When  I run  go build -o ./build/bin/geth   -gcflags=all='-N -l' -v ./cmd/geth, it shows below:
so whether should I rename quorum with ethereum and so on？thank you 

[root@zqh quorum]# go build -o ./build/bin/geth   -gcflags=all='-N -l' -v ./cmd/geth
cmd/geth/accountcmd.go:23:2: cannot find package "github.com/ethereum/go-ethereum/accounts" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/accounts (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/accounts (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/accounts (from $GOPATH)
cmd/geth/accountcmd.go:24:2: cannot find package "github.com/ethereum/go-ethereum/accounts/keystore" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/accounts/keystore (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/accounts/keystore (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/accounts/keystore (from $GOPATH)
cmd/geth/bugcmd.go:29:2: cannot find package "github.com/ethereum/go-ethereum/cmd/internal/browser" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/cmd/internal/browser (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/cmd/internal/browser (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/cmd/internal/browser (from $GOPATH)
cmd/geth/accountcmd.go:25:2: cannot find package "github.com/ethereum/go-ethereum/cmd/utils" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/cmd/utils (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/cmd/utils (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/cmd/utils (from $GOPATH)
cmd/geth/chaincmd.go:30:2: cannot find package "github.com/ethereum/go-ethereum/common" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/common (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/common (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/common (from $GOPATH)
cmd/geth/misccmd.go:27:2: cannot find package "github.com/ethereum/go-ethereum/consensus/ethash" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/consensus/ethash (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/consensus/ethash (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/consensus/ethash (from $GOPATH)
cmd/geth/accountcmd.go:26:2: cannot find package "github.com/ethereum/go-ethereum/console" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/console (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/console (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/console (from $GOPATH)
cmd/geth/chaincmd.go:32:2: cannot find package "github.com/ethereum/go-ethereum/core" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/core (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/core (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/core (from $GOPATH)
cmd/geth/chaincmd.go:33:2: cannot find package "github.com/ethereum/go-ethereum/core/state" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/core/state (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/core/state (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/core/state (from $GOPATH)
cmd/geth/chaincmd.go:34:2: cannot find package "github.com/ethereum/go-ethereum/core/types" in any of:
	/root/go_project/src/quorum/vendor/github.com/ethereum/go-ethereum/core/types (vendor tree)
	/usr/local/go/src/github.com/ethereum/go-ethereum/core/types (from $GOROOT)
	/root/go_project/src/github.com/ethereum/go-ethereum/core/types (from $GOPATH)

and when I rename the quorum with ethereum, it works ,but it did changed the name! I think it is not right if  the quorum be renamed with etherum.

**Comment by prd-fox** [comment]
Yep, this was done in order to drastically cut back on the amount of merge conflicts we would get from upstream when merging their changes. It isn't the more ideal solution, but it works well enough and only requires changing the GOPATH between different builds.

For future reference, there is this issue: https://github.com/jpmorganchase/quorum/issues/599

Please open new tickets (even for the same issue) instead of reusing old ones, as it may not be seen/responded to.
