### ISSUE TITLE
Incorrect args values from Events 

### ISSUE THREAD

**Issue by fabianoa** [Consensys-Incorporated/quorum#645]
Hi there,

I'm  having a problem when I  got  events arguments from quorum on  my app , using  web3 1.0.0-beta.46. I can get  the event and all attr,  but the args values are comming incorrectly.
When a catch the same event using truffle v4.1.15 (web3 v0.20.6) the args values are corrects.

My quorum version is 

Geth
Version: 1.8.12-stable
Git Commit: 8c4aea54d13d7ca6f148287d09aea9e0b6b0d8e6
Quorum Version: 2.1.1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.5

Ex.
On truffle I have :

identificadorResponsavel: '0x5625800f2ce8442fd7cf98aad38acafcce038d22'  //address type

On my app i got:

identificadorResponsavel: '0xF84cf49bcfb98bD6CA893FD0890453409eA4c57b'

Here , the full list of arguments, from truffle

{ address: '0x5ad9e197754bf0104a6b90e536e35bf098a6d605',
  blockNumber: 1291553,
  transactionHash: '0x6dc6e2af98ee0bd7feefec14399bee6dffbb1ef32bb5edc552762c659397832c',
  transactionIndex: 0,
  blockHash: '0x1a964e136dbfb24b8dc86d6d252468c0ce2446abdc5c3df8157b89f30594a1c5',
  logIndex: 0,
  removed: false,
  event: 'AtualizacaoEntidade',
  args:
   { identificadorResponsavel: '0x5625800f2ce8442fd7cf98aad38acafcce038d22',
     identificadorDaEntidade: BigNumber { s: 1, e: 9, c: [Array] },
     identificadorDoServidor: BigNumber { s: 1, e: 9, c: [Array] },
     atributo: '0x4e4f4d4500000000000000000000000000000000000000000000000000000000',
     valor: '0x46414249414e4f00000000000000000000000000000000000000000000000000',
     escopo: '0x5246420000000000000000000000000000000000000000000000000000000000',
     status: BigNumber { s: 1, e: 0, c: [Array] },
     nomeDaEntidade: '0x504553534f415f46495349434100000000000000000000000000000000000000' } }

From my app, I got 

![image](https://user-images.githubusercontent.com/8394387/53260631-b9bfa780-36b0-11e9-8aa0-915cc17d0466.png)

**Comment by fixanoid** [comment]
@fabianoa so web3 has been going through a series of some drastic changes recently. Would you be able to test this with an older release, lets say 1.0.0.beta37?

**Comment by fabianoa** [comment]
@fixanoid  It Works. Thank you!

**Comment by Krish1979** [comment]
➤ fixanoid commented:

fabianoa so web3 has been going through a series of some drastic changes recently. Would you be able to test this with an older release, lets say 1.0.0.beta37?
