### ISSUE TITLE
Geth options are not defined: flag provided but not defined: -unlock 0

### ISSUE THREAD

**Issue by DMALEXLEE** [Consensys-Incorporated/quorum#646]
Hi there,
Trying to run cluster of 3 nodes in K8s.

#### System information
Geth version: `geth version`
VERSION:
   1.8.12-stable-dadd8b0f

OS & Version: Windows/Linux/OSX
: OSX

Branch, Commit Hash or Release: `git status`
Pulling container image 
**image: quorumengineering/quorum**

#### Expected behaviour
It should Support raft speacific and geth speacific options.
Issue:
Incorrect Usage. flag provided but not defined: -unlock 0
Incorrect Usage. flag provided but not defined: -raftport 23000
flag provided but not defined: -nodekeyhex a19a79...

#### Actual behaviour
Should support All the above mentioned options.

**Comment by prd-fox** [comment]
Can you post the `geth` command you use? i.e. the whole startup command

**Comment by DMALEXLEE** [comment]
I actually messed up something in my K8s deployment script!! Its working fine now.
Appreciate quick response.
So closing!!
