### ISSUE TITLE
Incorrect value of homestead flag used before mining starts, can cause transaction to be stuck in pending state

### ISSUE THREAD

**Issue by SatpalSandhu61** [Consensys-Incorporated/quorum#651]
#### System information
 
Geth
Version: 1.8.12-stable
Git Commit: ef8187d0f70280d27cd42103e388bb05c2a0731a
Quorum Version: 2.2.1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.4
Operating System: darwin
 
#### Expected behaviour
 
If a transaction is submitted with insufficient gas then it should be rejected.
 
#### Actual behaviour
 
If the homestead flag is set and a transaction is submitted with marginally insufficient intrinsic gas, then it goes into pending state. Once in pending, there is currently no way to remove it from the pending queue, effectively blocking that node from processing further transactions.
This scenario only occurs if the transaction is submitted prior to any blocks having been minted. It can be reproduced under Raft, Clique, and Istanbul.
 
#### Steps to reproduce the behaviour
 
Easiest way to reproduce is under Raft:
* Start 7-nodes example with Raft consensus, ensuring that “homesteadBlock=1” is set in genesis.
* Edit public-contract.js to set gas=40620, and create the contract.
* If you run “eth.pendingTransactions” you will see that the transaction is stuck on the pending queue.
Same behaviour can also be seen for the private-contract.js, using gas=25352.
 
#### Explanation
 
The value of tx_pool.go::pool.homestead is initialised to ‘false’ and is only set to ‘true’ on a ChainHead event in tx_pool.go::loop(). Therefore, if the transaction is submitted before any block has been minted (or a resync performed), then:
* When transaction validation occurs, IntrinsicGas() is called with homestead == false; which gives an IntrinsicGas value of 40620, so the transaction is accepted.
* During minting, IntrinsicGas() is called with homestead == true.; which gives an IntrinsicGas value of 72620, so transaction has insufficient gas and is not included in the block.

I.e. A different intrinsic gas value is calculated between validation and minting.
The same behaviour can also be observed on upstream Ethereum (under ethhash & clique). However, in that case the transaction can simply be resubmitted with more gas and a higher gasPrice, which will clear the pending transaction.
 
#### Solution
 
There is no obvious code solution. In theory, instead of 'pool.homestead' we should use ‘pool.chainConfig.isHomestead(blockNumber)’ which returns the correct homestead flag value depending on the current block number; but when the transaction validation is performed, no blocks have been received/minted so we don’t know what block we’re on (and whether homestead is active now).
One solution would be to just initialise the homestead flag to “true”, since all chains should now be created with homestead enabled.
 
On Quorum there is currently no way to clear the stuck transaction, as we disallow gasPrice. However, once [PR#624](https://github.com/jpmorganchase/quorum/pull/624) to enable gasPrice is merged then this will no longer be an issue. Therefore my suggestion is to wait until the gasPrice PR is merged and then close this issue ticket.

**Comment by wenhuancai** [comment]
I'm using version V2.2.3, and I'll loop through the test cases.Trading will be suspended between 15 and 20w after two tests.Pending num is 30000. After I restart the node, the 30000 data can be synchronized.

**Comment by wenhuancai** [comment]
I also got a new error on the other nodes,when that node restarts.
![image](https://user-images.githubusercontent.com/20059816/58299506-ebf8b680-7e11-11e9-9f61-fbe8c5dc4ed9.png)

**Comment by SatpalSandhu61** [comment]
@wenhuancai did you mean to attach those comments to this issue ticket? They don't seem relevant.

**Comment by wenhuancai** [comment]
It seems a little inappropriate."can cause transaction to be stuck in pending state",This topic is consistent, because the previous version did not find this problem, I do not know whether the relevant modification caused this problem

**Comment by SatpalSandhu61** [comment]
@wenhuancai I believe my colleague @prd-fox has asked you to raise a separate issue ticket for your issue. Please do so - I will remove your comments from this ticket as they are unrelated to this issue.

**Comment by wenhuancai** [comment]
ok,I've reasked the question.

**Comment by baptiste-b-pegasys** [comment]
long term we are looking to re-enable gas price
