### ISSUE TITLE
Not able to make even ETH transfer transaction.

### ISSUE THREAD

**Issue by NEO2756** [Consensys-Incorporated/quorum#652]
Hi there,

Setup quorum-raft (with tessera) on K8s.

Able to connect Metamask, But sending ether (with GasFee == 0) from one account to another failed via:

ALERT: [ethjs-rpc] rpc error with payload {"id":3271335700028,"jsonrpc":"2.0","params":["0xf868808082520894ca843569e3427144cead5e4d5999a3d0ccf92b8e888ac7230489e800008081ada0d9008ab4af7587a74e9a9d3bfe4d305c1356531571acd6da0d3204d84965f98ca011199184887f1a706b6b1024b0d0c201a1b56fc0fa929556d5b9ed68c0d8d369"],"method":"eth_sendRawTransaction"} Error: oversized data]

what is this limitation?

#### System information

Geth version: `geth version`
-- 1.8.12-stable-af38cd13

OS & Version: Windows/Linux/OSX
-- k8s cluster

**Comment by prd-fox** [comment]
Are you able to share your Transaction Manager configuration, genesis file and your K8s configuration, please? I will replicate the environment which may be the cause.

**Comment by prd-fox** [comment]
Also, are you using a release version of Quorum, or building from master?

**Comment by NEO2756** [comment]
All the files are here  https://github.com/NEO2756/quorum-raft-k8s

**Comment by prd-fox** [comment]
I'm less familiar with Kubernetes, but I was hoping to just edit the paths to my local quorum-examples and run `kubectl apply -f k8sYamls/`, but this doesn't seem to work and unsure why.

Either way, communication should be the same inside or outside Kubernetes, and the error returned means that you did manage to contact the node, it was transaction validation error.

What version of metamask are you using? I am using 6.2.2.
Are you using Metamask with any other software? I assume not if it's just for an ether transfer and not a contract interaction.

---

For what it's worth, the payload specified is a valid payload and I called `eth_sendRawPayload` manually and it's works, so not sure why metamask is saying this error is returned.

If you setup the 7node example on the host machine (not in k8s), do you get the same error?

**Comment by NEO2756** [comment]
> I'm less familiar with Kubernetes, but I was hoping to just edit the paths to my local quorum-examples and run `kubectl apply -f k8sYamls/`, but this doesn't seem to work and unsure why.
>  **I think it should work. Leave it !!**
> Either way, communication should be the same inside or outside Kubernetes, and the error returned means that you did manage to contact the node, it was transaction validation error.
> **Ok. I was able to connect the node with metamask and it was showing the balance 10 ** 9 of the account also**.
> What version of metamask are you using? I am using 6.2.2.
**I am using the same version 6.2.2. :(**
> Are you using Metamask with any other software? I assume not if it's just for an ether transfer and not a contract interaction.
**Using Metamask chrome extension only. I tried to deploy contract using remix but got the same error. So tried ETH transfer but encountered the same error message.**
> For what it's worth, the payload specified is a valid payload and I called `eth_sendRawPayload` manually and it's works, so not sure why metamask is saying this error is returned.
 **Ohk..I will check this.**
> If you setup the 7node example on the host machine (not in k8s), do you get the same error?
**Not yet tried. Will try and update!!**

**Comment by fixanoid** [comment]
Please reopen if this is still an issue.
