### ISSUE TITLE
How can I set gas to zero?

### ISSUE THREAD

**Issue by ssbg2** [Consensys-Incorporated/quorum#654]
Hi,I want to send a transaction from address A to address B ,because this is a private chain network,So I want make sure the transaction amount is totally into address B,But sometimes the transaction will be fail and return:insufficient funds for gas * price + value.

This is my code(I already set the gasPrice to zero,but it seems doesn't work):
`Transaction.createEtherTransaction(fromAddress, nonce, gasPrice, gasLimit, toAddress, value);`

How can I set gas to zero?

Thank you!

#### System information

Version: 1.8.12-stable
Git Commit: a4580fc22e6d52ef3d175ce526e685bb6483a782
Quorum Version: 2.2.1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.6
Operating System: linux
GOPATH=/var/opt/golang
GOROOT=/usr/local/go

**Comment by SatpalSandhu61** [comment]
It works fine for me, however I notice that you seem to be using Transaction.createEtherTransaction(), whereas I use RawTransaction.createEtherTransaction(), as per the [web3j docs](https://web3j.readthedocs.io/en/latest/transactions.html?highlight=createethertransaction#transfer-of-ether-from-one-party-to-another).
Note that I'm using web3j-quorum version 4.0.6 (the latest release).

Here is my code:
'''
    public void transfer (String from, String to, BigInteger amount)
            throws InterruptedException, ExecutionException, IOException, CipherException {
        Credentials credentials1 = WalletUtils.loadCredentials(
                "",
                "/mypath/golang/src/quorum-examples/examples/7nodes/qdata/dd1/keystore/key1");

        EthGetTransactionCount ethGetTransactionCount = quorum.ethGetTransactionCount(
                from, DefaultBlockParameterName.LATEST).sendAsync().get();

        BigInteger nonce = ethGetTransactionCount.getTransactionCount();

        RawTransaction rawTransaction = RawTransaction.createEtherTransaction (
                nonce, BigInteger.ZERO, GAS_LIMIT, to, amount);
        byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials1);
        String hexValue = Numeric.toHexString(signedMessage);

        EthSendTransaction ethSendTransaction = quorum.ethSendRawTransaction(hexValue).sendAsync().get();
        if (ethSendTransaction.hasError()) {
            LOGGER.info("==== Transaction failed, error = {}", ethSendTransaction.getError().getMessage());
        } else {
            String transactionHash = ethSendTransaction.getTransactionHash();
            LOGGER.info("==== Transaction sent, transaction hash = {}", transactionHash);
        }
    }
'''
If I replace the "BigInteger.ZERO" with a non-zero value then it fails as expected with 'Gas price not 0'.

Closing the ticket based on my findings.

**Comment by ssbg2** [comment]
> It works fine for me, however I notice that you seem to be using Transaction.createEtherTransaction(), whereas I use RawTransaction.createEtherTransaction(), as per the [web3j docs](https://web3j.readthedocs.io/en/latest/transactions.html?highlight=createethertransaction#transfer-of-ether-from-one-party-to-another).
> Note that I'm using web3j-quorum version 4.0.6 (the latest release).
> 
> Here is my code:
> '''
> public void transfer (String from, String to, BigInteger amount)
> throws InterruptedException, ExecutionException, IOException, CipherException {
> Credentials credentials1 = WalletUtils.loadCredentials(
> "",
> "/mypath/golang/src/quorum-examples/examples/7nodes/qdata/dd1/keystore/key1");
> 
> ```
>     EthGetTransactionCount ethGetTransactionCount = quorum.ethGetTransactionCount(
>             from, DefaultBlockParameterName.LATEST).sendAsync().get();
> 
>     BigInteger nonce = ethGetTransactionCount.getTransactionCount();
> 
>     RawTransaction rawTransaction = RawTransaction.createEtherTransaction (
>             nonce, BigInteger.ZERO, GAS_LIMIT, to, amount);
>     byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials1);
>     String hexValue = Numeric.toHexString(signedMessage);
> 
>     EthSendTransaction ethSendTransaction = quorum.ethSendRawTransaction(hexValue).sendAsync().get();
>     if (ethSendTransaction.hasError()) {
>         LOGGER.info("==== Transaction failed, error = {}", ethSendTransaction.getError().getMessage());
>     } else {
>         String transactionHash = ethSendTransaction.getTransactionHash();
>         LOGGER.info("==== Transaction sent, transaction hash = {}", transactionHash);
>     }
> }
> ```
> '''
> If I replace the "BigInteger.ZERO" with a non-zero value then it fails as expected with 'Gas price not 0'.
> 
> Closing the ticket based on my findings.

Thank you.
I change my code just like you post,But it still show the same error:insufficient funds for gas * price + value.
Here is my code:

`          

            quorum = Quorum.build(new HttpService(quorumClientPath));

            Credentials credentials = WalletUtils.loadCredentials(<PWD>,<KEY_FILE>);

            EthGetTransactionCount ethGetTransactionCount = quorum.ethGetTransactionCount(from, DefaultBlockParameterName.LATEST).sendAsync().get();

            BigInteger nonce = ethGetTransactionCount.getTransactionCount();

            BigInteger value = Convert.toWei(BigDecimal.valueOf(8), Convert.Unit.MWEI).toBigInteger();

           
            RawTransaction rawTransaction = RawTransaction.createEtherTransaction(nonce,BigInteger.ZERO,BigInteger.valueOf(99999),toAccount,value);


            byte[] signedMessage = TransactionEncoder.signMessage(rawTransaction, credentials);
            String hexValue = Numeric.toHexString(signedMessage);

            EthSendTransaction ethSendTransaction = quorum.ethSendRawTransaction(hexValue).sendAsync().get();`

**Comment by SatpalSandhu61** [comment]
Ok, I think the issue is that the 'from' account doesn't have sufficient funds (the error message is a bit misleading).
I ran your code and it worked fine for me. However, if I run it against an account where the funds are < amount, then I get that error.

I've re-opened the ticket, let me know if I was correct and I can then close the ticket.

**Comment by ssbg2** [comment]
OK,I'll re-check the code and post my result later.
Thanks,It is so helpful to me.

**Comment by ssbg2** [comment]
I initialized the whole project,reimported all dependencies,after follow your suggestion,It finally worked!
So i guess it's my mistake.
Thank you so much for helping me out.
