### ISSUE TITLE
panic: failed to get parent state: missing trie node 

### ISSUE THREAD

**Issue by nurASingh** [Consensys-Incorporated/quorum#655]
Hi there,

I am using quorum RAFT to create a block chain network. Things worked fine till yesterday but failed while deploying a private contract. I got below error while contract deployment - 

> panic: failed to get parent state: missing trie node 239b3e5fe6bdf6bdcf3a8700977a3ade9626019e4ed7e243dda866cb687c8ed1 (path )
> 
> goroutine 59387689 [running]:
> github.com/ethereum/go-ethereum/raft.(*minter).createWork(0xc4202f65a0, 0x10e5b90)
> 	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:273 +0x5bf
> github.com/ethereum/go-ethereum/raft.(*minter).mintNewBlock(0xc4202f65a0)
> 	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:313 +0x8f
> github.com/ethereum/go-ethereum/raft.(*minter).mintingLoop.func1()
> 	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:234 +0x3c
> created by github.com/ethereum/go-ethereum/raft.throttle.func1
> 	/quorum/build/_workspace/src/github.com/ethereum/go-ethereum/raft/minter.go:216 +0xc0

#### System information

Geth version:  Geth/v1.8.12-stable

OS & Version: Amazon Linux

Other details -

1. Quorum nodes  ( total 5 ) running on AWS EC2 instances 
2. Solidity version for contract is -  pragma solidity ^0.4.8;
3. Failed on one node and all node stopped responding 

#### Expected behaviour
Contract should have deployed successfully

#### Actual behaviour
Got above error

Please refer to Log attached.

**Comment by nurASingh** [comment]
[log.zip](https://github.com/jpmorganchase/quorum/files/2970890/log.zip)

**Comment by SatpalSandhu61** [comment]
I suspect the failure is related to the earlier error in the logs:
    ERROR[03-14|07:57:43.510] Failed to reset txpool state             err="missing trie node
Which is described in [ethereum issue 16123](https://github.com/ethereum/go-ethereum/issues/16123).

Was the failing node out of sync with the rest of the network when the issue occurred?
You could try doing a resync of the failing node.

**Comment by nurASingh** [comment]
All 5 nodes failed at the same time , I am not sure if resync can help. We are getting same error on each node.

**Comment by SatpalSandhu61** [comment]
Could you share your genesis file please?

**Comment by nurASingh** [comment]
{
  "config": {
        "chainId": 17514,
        "byzantiumBlock": 0,
        "eip150Block": 0,
        "eip155Block": null,
        "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "eip158Block": null,
        "isQuorum": true
    },
  "alloc"      : {"0x983f000dc45b10a9b71a407e03b69705579bed28": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase"   : "0x0000000000000000000000000000000000000000",
  "difficulty" : "0x0",
  "extraData"  : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit"   : "0xE0000000",
  "nonce"      : "0x0",
  "mixhash"    : "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "parentHash" : "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp"  : "0x00"
}

**Comment by SatpalSandhu61** [comment]
Couldn't find any genesis-related issues.
The log you provided earlier is for one node only. Are you able to provide the logs for all nodes?

**Comment by fixanoid** [comment]
Could you also share your geth startup command / config?

**Comment by nurASingh** [comment]
I am using https://github.com/synechron-finlabs/quorum-maker to build the nodes  ( the same has been given on you wiki page )
Do you see any issue with this ?

**Comment by jbhurat** [comment]
Hi @nurASingh, as @SatpalSandhu61 suggested, is it possible to provide logs for all the nodes in the network?

**Comment by SatpalSandhu61** [comment]
Closing this issue for now due to inactivity.
Note that the recommendation now is to run raft with `--gcmode=archive` (see [issue # 683](https://github.com/jpmorganchase/quorum/issues/683) for details).
