### ISSUE TITLE
contract address undefined

### ISSUE THREAD

**Issue by felison692** [Consensys-Incorporated/quorum#659]
When submitting a creation of a contract. The block gets mined but the address is undefinded.
any idea?

> getSchwiftyPartialInstance
{
  abi: [{
      constant: false,
      inputs: [{...}],
      name: "set",
      outputs: [],
      payable: false,
      stateMutability: "nonpayable",
      type: "function"
  }, {
      constant: false,
      inputs: [],
      name: "get",
      outputs: [{...}],
      payable: false,
      stateMutability: "nonpayable",
      type: "function"
  }],
  address: undefined,
  transactionHash: "0xfc5af584a1888da41f373948e33e51d70acb5f42353c8a772cc603da039841dd"

**Comment by fixanoid** [comment]
@felison692 were you able to fix the issue?
