### ISSUE TITLE
Private Transaction from solidity code ?

### ISSUE THREAD

**Issue by jaguarg** [Consensys-Incorporated/quorum#66]
Hello, 

I have got a private contract that need to interact with another private contract (from within the code) 
Is this operation going to be seen as a private transaction ? 

How does Quorum handle this with regards to private / public transactions ?

Thank you

**Comment by obscuren** [comment]
This should be possible as long as the *transactor* has both contracts in it's *private* state:

Consider all contracts private.
```text
S -> [deploy] -> A
S -> [deploy] -> B

S -> [transact] -> A -> B
```

Or

```text
S -> [deploy] -> A
S -> [transact] -> A -> [deploy] -> B

S -> [transact] -> A -> B
```

Which isn't possible if two contracts are mutually excluded. Let's say `S_a` and `S_b`, being transactors, but not part of the same group (i.e. they can't decrypt each others transaction data):

```
S_a -> [deploy] -> A
S_b -> [deploy] -> B

S_a -> [transact] -> A -> B
```

That's simply not possible as `B` was created by `S_b` and `S_a` was not able to decrypt the payload which deployed `B`.

**Comment by tylobban** [comment]
@jaguarg happy for this to be closed?
