### ISSUE TITLE
remove raft peer

### ISSUE THREAD

**Issue by felison692** [Consensys-Incorporated/quorum#660]
in geth console I have tried raft.removePeer(2) to remove a peer but it hangs.

any idea?

**Comment by fixanoid** [comment]
@felison692 Hangs? Is there anything in the log or is there an error returned?

**Comment by felison692** [comment]
There is nothing in the log.
I have added a raft peer by using raft.adpeer(...) but I made a mistake and I want to delete the peer,so I invoke raft.removePeer(2) and I get no results in the console and I can´t type any more commands. It hangs

**Comment by felison692** [comment]
raft
{
  cluster: [{
      ip: "127.0.0.1",
      nodeId: "45908bca0415f356801f778e4dbdbcea3a4a23857071dc4315f1ded1e771b25d0cc42acf63eff5695081e629bda659be4023a5d930b1cea1fdfcb8cc28b66b94",
      p2pPort: 21005,
      raftId: 2,
      raftPort: 50005
  }, {
      ip: "127.0.0.1",
      nodeId: "702168c9c0eb3b7a98614b821573ffaca89942acc56271d43b5b5a5ec9ffbff8cd28c4e00d225eff63fe326f51e9e2f11762ee0651aa19b487ace92f78491f81",
      p2pPort: 21008,
      raftId: 1,
      raftPort: 50409
  }],

logs:
INFO [03-18|19:26:59.644] peer is currently unreachable            peer id=2
2019-03-18 19:27:00.454708 W | rafthttp: health check for peer 2 could not connect: dial tcp 127.0.0.1:50005: connect: connection refused


I want to delete the raftid 2

**Comment by felison692** [comment]
raft.deletePeer function is not working in quorum?

**Comment by felison692** [comment]
Solved creating the node again
