### ISSUE TITLE
permissions to connect to node

### ISSUE THREAD

**Issue by felison692** [Consensys-Incorporated/quorum#662]
Hi there,
is it possible to limit the public keys that can interact with quorum?
Imagine that in my quorum network I only want to allow a few defined accounts.
¿How can we control this?

thanks!

**Comment by fixanoid** [comment]
Hi @felison692, how are you? As of v2.2.1 such a feature does not yet exist in Quorum. We are working on a new permissions system that will also allow well defined permission restrictions that allow you to set up a system where only some ethereum accounts are the ones allowed to transact.

Another potential alternative is to use Quorum with gas enabled, see #624. In such a configuration, an un-funded account will not be able to send transactions and the operator of the chain funds the accounts either manually or through a faucet.
