### ISSUE TITLE
websocket connection to quorum

### ISSUE THREAD

**Issue by felison692** [Consensys-Incorporated/quorum#664]
Hi there,
¿How do you connect via web3 to quorum websocket? ¿What is the port used for websocket?

I want to perform a log subscription

const Web3 = require('web3')
var web3 = new Web3('wss://192.168.2.102:22000/_ws');
var subscription = web3.eth.subscribe('logs', {
        address: '0x4f375be47ba13af46045959eec6b2caf9b240b8a' // sales auction contract
    }, function(error, result) {
        if (!error) {
                console.log(result);
        }
    });

**Comment by prd-fox** [comment]
The options are listed here: 
https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

under `API AND CONSOLE OPTIONS`.

Specifically, you want these options `--ws --wsaddr <host to bind> --wsport <port> --wsapi <api modules to enable> --wsorigins <CORS origins to accept>`
