### ISSUE TITLE
istanbul-start.sh failing 

### ISSUE THREAD

**Issue by romisalve** [Consensys-Incorporated/quorum#665]
Hi, 

I was following the quorum 7nodes example and when I tried to run istanbul-start.sh, the console show for all the 7 nodes: "Node X is not yet listening on tm.ipc
                                          Node X is not yet listening on http"     
I tried to search for the logs, and it says: ./constellation-start.sh: line 15: constellation-node: command not found on every log of the type of "constellationX.log". Then, on the logs of the type "tesseraX.log" it says: HV000028: Unexpected exception during isValid call.

What should i do??

Thank you!

┆Issue is synchronized with this [Trello card](https://trello.com/c/iV8s3VsD)

**Comment by prd-fox** [comment]
Are you running on the local machine, or inside Docker or Vagrant?
If you are using Constellation, then first you need to download or install it and make it available on the `PATH`. If you want to run Tessera, then please provide the full output of the log so we can investigate further.

**Comment by romisalve** [comment]
I am running on a Centos virtual machine and I wanted to set the 7nodes quorum example locally on this machine. 
I did not want to use Constellation, I tried to run Tessera using Istanbul. 

The images "Pantalla 1"  through "Pantalla 5"
![Pantalla 1](https://user-images.githubusercontent.com/21060405/55083585-8cd12c80-5082-11e9-87c8-85227fb32204.PNG)
![Pantalla 1](https://user-images.githubusercontent.com/21060405/55083635-9bb7df00-5082-11e9-93b6-63875687d2bb.PNG)
![pantalla 2](https://user-images.githubusercontent.com/21060405/55083637-9bb7df00-5082-11e9-9e2d-d85362675ad6.PNG)
![pantalla 3](https://user-images.githubusercontent.com/21060405/55083639-9c507580-5082-11e9-9ca2-28c24f44e56e.PNG)
![pantalla 4](https://user-images.githubusercontent.com/21060405/55083641-9c507580-5082-11e9-8c3c-2a548fdd6c4f.PNG)
![pantalla 5](https://user-images.githubusercontent.com/21060405/55083642-9c507580-5082-11e9-9c3a-035abca4a3cd.PNG)
![pantalla 5](https://user-images.githubusercontent.com/21060405/55083692-affbdc00-5082-11e9-81dd-97203878373b.PNG)






 are screenshots of my procedure. I would appreciate any help. Thank you!!

**Comment by fixanoid** [comment]
@romisalve the log says there is an issue with launching Tessera. If all you see is just that error, it might have to do with DB config in the tessera config file or even permissions for the DB. I don't think we have see this issue before tho.

Have you built Tessera locally yourself?

**Comment by romisalve** [comment]
Yes, actually I didn't build it myself, but I know it was built locally. What do you suggest?

**Comment by fixanoid** [comment]
@romisalve if you are on Slack, please message me (also fixanoid) so we could take a look at this live.

**Comment by fixanoid** [comment]
Please reopen if this is still an issue.

**Comment by manjesh127** [comment]
Tessera is taking a long time to start.  Look at the Tessera logs in qdata/logs/ for help diagnosing the problem.
Waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc
Node 1 is not yet listening on http
Node 2 is not yet listening on tm.ipc
Node 2 is not yet listening on http
Node 3 is not yet listening on tm.ipc
Node 3 is not yet listening on http
Node 4 is not yet listening on tm.ipc
Node 4 is not yet listening on http
Node 5 is not yet listening on tm.ipc
Node 5 is not yet listening on http
Node 6 is not yet listening on tm.ipc
Node 6 is not yet listening on http
Node 7 is not yet listening on tm.ipc
Node 7 is not yet listening on http
Tessera is taking a long time to start.  Look at the Tessera logs in qdata/logs/ for help diagnosing the problem.
Waiting until all Tessera nodes are running...

**Comment by prd-fox** [comment]
Please open a new issue if you are having problems @manjesh127

**Comment by Mohammed-alzuharey** [comment]
Hi every one 
I have same problem of  @manjesh127
but Iam run locally 7nodes example locally on linux 
how to can help us @prd-fox 
Thanks

**Comment by SatpalSandhu61** [comment]
Hi @Mohammed-alzuharey , please don't post questions on a closed issue ticket. If you have an issue then please create a new ticket with all the details of your environment and the error you are seeing.
Thanks.

**Comment by Mohammed-alzuharey** [comment]
Sorry 
Ok @SatpalSandhu61 
Thanks
