### ISSUE TITLE
Partitioned node takes long time to reconnect and get missing blocks with Raft 

### ISSUE THREAD

**Issue by robvry** [Consensys-Incorporated/quorum#668]
#### System information

Geth version: 1.8.12-stable

OS & Version: Ubuntu 18.04.2

Branch, Commit Hash or Release: master

#### Expected behaviour
I am running the 7nodes example using Raft consensus in Docker, no changes to docker-compose.yml (7 nodes, 7 Tx Managers).  I send some public and/or private transactions from Node 1.  I then partition Node 2 (and Node 2 Tx Manager) from the network using docker container disconnect.  I then send more transactions from Node 1 (anywhere from 20 -100), and reconnect Node 2 (and Tx Manager) using docker container connect.  I expect Node 2 to quickly reconnect with its peers and commit the blocks it is missing.

#### Actual behaviour
When I reconnect Node 2/Node 2 Tx Manager (or any other node that has been partitioned), it takes approximately 15 minutes to catch-up and commit the blocks it is missing.  I thought it was due to the partitioned node now having a higher term.  I enabled PreVote in handler.go, built the docker image with the change in $home/quorum using docker image build ., and saw that the partitioned node no longer appeared to gain terms; however, it still took roughly 15 minutes to catch up to the correct block.

In any subsequent partition of the same node (assuming no other nodes had partitioned in that time), and the node reconnects and reaches current block state in approximately 5 seconds. 

#### Steps to reproduce the behaviour
As noted above, run 7nodes using docker-compose.yml with Raft consensus.  Open a geth console in one of the node containers and send some transactions (I sent mostly public transactions and modified the public-generate-events.js to change the value of public-contract.js in order to generate blocks).  After sending some transactions, partition one of the nodes and its Tx manager using docker container disconnect.  Send additional transactions to generate blocks while the node is partitioned.  Reconnect the partitioned node and wait for it to reach current block (I watched the log files for the partitioned nodes using docker container log -f).  Once it reaches the current block (around 15 minutes), partition the same node again, send some transactions, then reconnect the partitioned node.  It now takes only a few seconds for it to get back to the current block.

**Comment by fixanoid** [comment]
@robvry hey, thanks for the detailed issue. I'll test this later today, but we did have a change in the block fetcher for raft post v2.2.1 that may address it, see: https://github.com/jpmorganchase/quorum/pull/621/files

**Comment by robvry** [comment]
@fixanoid thanks, it looks like I have that block fetcher update in the code I'm using for the Docker image,  but I'll check again if you don't run into the same issue with your test.  Also, I haven't tried this using separate physical nodes, only with Docker containers, I'm don't think I mentioned that in the original post.

**Comment by fixanoid** [comment]
@robvry I've been testing with 7nodes config inside vagrant so far and I'm unable to replicate the issue. Node 6 (the one I keep bumping up and down) reconnects almost instantly and downloads missing blocks in a blink. In my test, I ran public-contract.js and private-contract.js, and the node was not part of the privateFor defined in the contract.

I've tried to vary if the transaction manager was up or down, the result seems to be the same so far and I'm on master of the quorum repo.

@trung any thoughts on why this may happen that'd be docker specific?

**Comment by trung** [comment]
@robvry what command did you use to reconnect the node to the network? i assume you provided `--ip` and `--alias` to `docker network connect` command

**Comment by robvry** [comment]
@trung No I did not provide the --ip or --alias to the command, although it doesn't look like it's an issue with networking.  Before I made a change and enabled PreVote, the partitioned node would reject the MsgHeartbeat msgs from the leader once it reconnected (usually until the partitioned node reached ~term 750, give or take a few terms).  Tomorrow I can provide some of the logs from the partitioned node and another node in the network once it reconnects.  I'm also trying to get Vagrant set up on my machine and verify that that is working for me, and I can try to pass the --ip and --alias tomorrow as well.  Thanks!

**Comment by trung** [comment]
`--ip` and `--alias` make sure node networking configuration is matched with ones originally specified in docker compose file. Node discovery and port binding are IP-specific.

**Comment by robvry** [comment]
@trung I just tried it out passing --ip when I reconnected the node and have success! Thank you for the help, and thanks @fixanoid !  I tried it out a few times and seems to be working each time, so I will close the issue and reopen if for some reason I run into it or something similar again.
