### ISSUE TITLE
Is it possible to add a new node(RAFT) without full sync?

### ISSUE THREAD

**Issue by melihbirim** [Consensys-Incorporated/quorum#681]
Hi there,

I am using latest version of the Quorum 2.2.3 and in RAFT consensus. 

I was wondering to add a node to the initial 6 node network with over 500K blocks. And I want this new node to be added right after raft.addPeer

How this can possible?

**Comment by fixanoid** [comment]
Hi @melihbirim 
After node is added and joins the net, it must sync the blocks and will do so automatically. That said, the node is operational and usable immediately after its connected into raft net.
