### ISSUE TITLE
Can not callback when deploy contract using web3.js 1.0！

### ISSUE THREAD

**Issue by yesidi** [Consensys-Incorporated/quorum#686]
var companyContract = new web3js.eth.Contract(abi);
        companyContract.deploy({
            data: bytecode,
            arguments: [logo, name, representative, contactPerson, companyAddress, contactPhone]
        })
        .send({
            from: acc,
            gas: 3000000
        }, function(error, transactionHash){ 
            console.log(error + "  " + transactionHash)
         })
        .on('error', function(error){  
            console.log('error' + error)
        })
        .on('transactionHash', function(transactionHash){
            console.log('transactionHash' + transactionHash)
        })
        .on('receipt', function(receipt){
           console.log(receipt.contractAddress) 
        })
        .on('confirmation', function(confirmationNumber, receipt){ 
            console.log('confirmationNumber' + confirmationNumber)   
         })
        .then(function(newContractInstance){
            console.log(newContractInstance.options.address) 
        })

only print: 
false  0xe4bf6142406946963696167b0f2dc4e956822d9c8d30fc933088f3479bbfd440

however, can not callback events: transactionHash, receipt, confirmation.   nothing happend.

and this contract deploy successed. why? help me.

**Comment by fixanoid** [comment]
@yesidi, please acquaint yourself with the available events for web3.eth.contract as described here: https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#contract-events.

From your list, only the `error` event exists.
