### ISSUE TITLE
How can I backup&restore all quorum data?

### ISSUE THREAD

**Issue by ssbg2** [Consensys-Incorporated/quorum#687]
Hi,I want to test data backup and restore,here is my backup operating steps：
1.use command 'geth export dd1.dmp' to export data.
2.use OS copy command to backup qdata/dd1/keystore.
But the dd1.dmp file size is very small.
Did I miss something?
Thank you!

System information
Version: 1.8.12-stable
Git Commit: a4580fc
Quorum Version: 2.2.1
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.6
Operating System: linux
GOPATH=/var/opt/golang
GOROOT=/usr/local/go

**Comment by fixanoid** [comment]
@ssbg2, at the moment, `geth import / export` functionality is unreliable with Quorum. Our recommendation in this space is to backup the contents of the entire datadir for the full back up and backing up wallet keys and nodekeys for when you expect to recover the node from other participants in your blockchain.
