### ISSUE TITLE
reseting geth data

### ISSUE THREAD

**Issue by felison692** [Consensys-Incorporated/quorum#688]
Hi there,
I need to delete all data of my geth node (because I want to resync all data again).
¿How can I do this in the easiest way?

thanks in advance

**Comment by SatpalSandhu61** [comment]
There are two ways to do it.
1) Use geth to delete the data using the "geth removedb" command.
```
geth [--datadir /location/of/data/directory] removedb
```
   Then restart geth to have it sync up.

2) Manually delete the chain data. To do this, delete the "geth/chaindata" directory, which will be in the data directory for the node.
