### ISSUE TITLE
Non-informative error log

### ISSUE THREAD

**Issue by Magicking** [Consensys-Incorporated/quorum#690]
Quorum doesn't return a message error clearly specifying the cause of an error (from a user standpoint) when the transaction manager fails to Quorum (e.g: 400 bad request, ...).

#### System information

Release: `2.2.3`

#### Expected behaviour

Helpful error message

#### Actual behaviour

invalid argument 0: json: cannot unmarshal non-string into Go value of type common.Hash

#### Steps to reproduce the behaviour

Send an externally signed private transaction with a privateFor set to a non-existent public key, Quorum will return the error above when Tessera send a 400 bad request.

**Comment by LuisOsta** [comment]
@Magicking What's the usual good error log format? and what would be good information to add?

**Comment by Magicking** [comment]
The issue is not about error log format but about a clear error message given back to the user.

From a user standpoint, you get the error from JSON/RPC, I would give the reason why Tessera failed to propagate its payload.

**Comment by Open-Rawi** [comment]
HI @Magicking , i couldn't reproduce the issue with the steps you provided , can you check if you are still seeing it.

this is what i see :

err creating contract Error: Non-200 status code: &{Status:400 Bad Request StatusCode:400 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Length:[73] Server:[Jetty(9.4.z-SNAPSHOT)] Date:[Sun, 23 Jun 2019 17:06:17 GMT] Content-Type:[text/plain]] Body:0xc4202705c0 ContentLength:73 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0xc421c9c200 TLS:<nil>}

**Comment by Magicking** [comment]
It looks like you are experiencing the same problem but in a different form
as the error you see is a passthrough text from your transaction manager
instead of a message informing you *why* the private transaction was not
transmitted by either the transaction manager or Quorum

**Comment by SatpalSandhu61** [comment]
I'm guessing this issue was being seen when using quorum.js. I was certainly able to reproduce it with quorum.js to get the `invalid argument 0: json: cannot unmarshal non-string into Go value of type common.Hash` error message.

I've raised a PR under the quorum.js repo to fix it: https://github.com/ConsenSys/quorum.js/pull/37
