### ISSUE TITLE
Build failed 

### ISSUE THREAD

**Issue by sc0Vu** [Consensys-Incorporated/quorum#691]
Hi there,

I try to build geth with last commit 78b689baea57720bd7ac47f4737371c9dc420fff but got error.

#### System information

~Geth version: `geth version`~

OS & GO version: OSX10.14.4 & go1.11.5 darwin/amd64 / go1.12.4 darwin/amd64 

Branch, Commit Hash or Release: `git status`

#### Expected behaviour

Build geth.

#### Actual behaviour

Failed to build.

#### Backtrace

Error log:
```BASH
# github.com/ethereum/go-ethereum/raft
raft/constants.go:13:17: undefined: raft.LEADER
raft/constants.go:14:17: undefined: raft.NOT_LEADER
raft/handler.go:396:4: ss.Initialize undefined (type *stats.ServerStats has no field or method Initialize)
raft/handler.go:501:37: pm.rawNode().RoleChan undefined (type raft.Node has no field or method RoleChan)
github.com/ethereum/go-ethereum/ethstats
github.com/ethereum/go-ethereum/cmd/utils
util.go:45: exit status 2
exit status 1
make: *** [geth] Error 1
```

I'd check the etcd library, there were no `LEADER` and `NOT_LEADER` in this library: [github.com/coreos/etcd/raft](https://github.com/coreos/go-etcd)

**Comment by fixanoid** [comment]
@sc0Vu could you describe your go version and process of building?

Also, raft lib used in Quorum is a 3.0: https://github.com/etcd-io/etcd/tree/release-3.0/client

**Comment by sc0Vu** [comment]
Thanks @fixanoid 

Go version: go1.11.5 darwin/amd64

I got the v3.0.0+incompatible version of  https://github.com/etcd-io/etcd, seems like I cannot compile etcd with this version?

**Comment by sc0Vu** [comment]
@fixanoid Somebody got this issue in another repo https://github.com/pingcap/tidb/issues/8947. It seems like a bug of go.

I try the solution in the thread, but it didn't work for me.
```BAH
rm go.sum
go clean -modcache
make
```

By the way, I can build after I use `govendor sync` instead of `go mod download`.
