### ISSUE TITLE
invalid memory address issue when sending private transaction

### ISSUE THREAD

**Issue by zmmwl** [Consensys-Incorporated/quorum#692]
Hi there,

#### System information
Geth
Version: 1.8.18-stable
Git Commit: f681cbf3ae657f12ef7436296e2d9a3839f899e5
Quorum Version: 2.2.3
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.8
Operating System: linux
GOPATH=
GOROOT=/opt/dev/golang/go1.10.8

#### Expected behaviour
transaction sending should be succeed by adding privateFor section.

#### Actual behaviour
The quorum node is crashed and failed to sending transaction
`DEBUG[04-26|10:14:55.005] Trie cache stats after commit            misses=0 unloads=0
DEBUG[04-26|10:14:55.007] Trie cache stats after commit            misses=0 unloads=0
DEBUG[04-26|10:14:55.007] Trie cache stats after commit            misses=0 unloads=0
DEBUG[04-26|10:14:55.007] Persisted trie from memory database      nodes=0 size=0.00B time=2.523µs  gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
DEBUG[04-26|10:14:55.007] Inserted new block                       number=38 hash=efed10…8f03b0 uncles=0 txs=0 gas=0 elapsed=1.834ms
INFO [04-26|10:14:55.007] Imported new chain segment               blocks=1 txs=0 mgas=0.000 elapsed=1.924ms   mgasps=0.000 number=38 hash=efed10…8f03b0 cache=0.00B
TRACE[04-26|10:14:55.007] Announced block                          hash=efed10…8f03b0 recipients=0 duration=2.729ms
TRACE[04-26|10:14:55.007] Received a final committed proposal      address=0x90ccABA53ed0C2979D4659692CA3B0EcC385FD70 state=Committed
TRACE[04-26|10:14:55.007] Catch up latest proposal                 address=0x90ccABA53ed0C2979D4659692CA3B0EcC385FD70 old_round=0  old_seq=38 number=38 hash=efed10…8f03b0
DEBUG[04-26|10:14:55.007] New round                                address=0x90ccABA53ed0C2979D4659692CA3B0EcC385FD70 old_round=0  old_seq=38 old_proposer=0x90ccABA53ed0C2979D4659692CA3B0EcC385FD70 new_round=0 new_seq=39 new_proposer=0xF0FA966E6EfA633080d1603E7dAea5176De87d82                                                                                                                                                    valSet="[0x90ccABA53ed0C2979D4659692CA3B0EcC385FD70 0xA02f4bB093989222608D25C6C57a5B40526F6796 0xF0FA966E6EfA633080d1603E7dAea5176De87d82]" size=3     IsProposer=false
INFO [04-26|10:14:55.007] 🔗 block reached canonical chain          number=31 hash=136439…d0a1bf
INFO [04-26|10:14:55.007] Commit new mining work                   number=39 sealhash=f04546…293f93 uncles=0 txs=0 gas=0 fees=0 elapsed=296.498µs
DEBUG[04-26|10:14:55.007] Reinjecting stale transactions           count=0
INFO [04-26|10:14:55.249] sending private tx                       data=6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029000000000000000000000000000000000000000000000000000000000000002a privatefrom= privatefor="[Uc952L7QFuk8R5sGtjpfHb9EM+X6pTFRixVa+XgPBjc=]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xab1620]

goroutine 987 [running]:
github.com/ethereum/go-ethereum/internal/ethapi.(*PublicTransactionPoolAPI).SendTransaction(0xc42026d300, 0x1238e00, 0xc421bff260, 0x9c22f710ffedff9a, 0x362cb1eed5190868, 0xebbaf624, 0x0, 0xc421bf0aa0, 0x0, 0x0, ...)
	/opt/dev/quorum/ws/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/internal/ethapi/api.go:1384 +0x830
reflect.Value.call(0xc42003f800, 0xc42021f4d0, 0x13, 0x1088d4d, 0x4, 0xc421a9dec0, 0x3, 0x4, 0xc421bff260, 0xc421a9dec0, ...)
	/opt/dev/golang/go1.10.8/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc42003f800, 0xc42021f4d0, 0x13, 0xc421a9dec0, 0x3, 0x4, 0x1, 0x1, 0xc42004e070)
	/opt/dev/golang/go1.10.8/src/reflect/value.go:308 +0xa4
github.com/ethereum/go-ethereum/rpc.(*Server).handle(0xc4209d1650, 0x1238e00, 0xc421780900, 0x123ee60, 0xc421766e60, 0xc421a9de60, 0xc420dedf38, 0x43f329, 0x8)
	/opt/dev/quorum/ws/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:313 +0x8fa
github.com/ethereum/go-ethereum/rpc.(*Server).exec(0xc4209d1650, 0x1238e00, 0xc421780900, 0x123ee60, 0xc421766e60, 0xc421a9de60)
	/opt/dev/quorum/ws/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:334 +0x1a6
github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest.func2(0xc42176ebd0, 0xc4209d1650, 0xc421668bd0, 0x123ee60, 0xc421766e60, 0xc4202710f8, 0x1, 0x1, 0x20000)
	/opt/dev/quorum/ws/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:204 +0xad
created by github.com/ethereum/go-ethereum/rpc.(*Server).serveRequest
	/opt/dev/quorum/ws/src/github.com/ethereum/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/rpc/server.go:199 +0x28c
`

#### Steps to reproduce the behaviour
Similar to 7node sample, I setup my 3node manually. 

genesis.json
`{
    "alloc": {
      "0x9affedff10f7229c680819d5eeb12c3624f6baeb": {
        "balance": "1000000000000000000000000000"
      },
      "0x5c8822ab6af840f8c3e52fe9a71c43f90672728e": {
        "balance": "1000000000000000000000000000"
      },
      "0x915779c113cffecac6583310d80a8def09546272": {
        "balance": "1000000000000000000000000000"
      }
    },
    "coinbase": "0x0000000000000000000000000000000000000000",
    "config": {
      "homesteadBlock": 0,
      "byzantiumBlock": 0,
      "chainId": 10,
      "eip150Block": 0,
      "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "eip155Block": 0,
      "eip158Block": 0,
      "isQuorum": true,
      "istanbul": {
        "epoch": 30000,
        "policy": 0
      }
    },
    "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f885f83f9490ccaba53ed0c2979d4659692ca3b0ecc385fd7094a02f4bb093989222608d25c6c57a5b40526f679694f0fa966e6efa633080d1603e7daea5176de87d82b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0",
    "gasLimit": "0xE0000000",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "nonce": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "timestamp": "0x00"
  }

`

After 3 transaction manage started up, I started 3 quorum node. All seems good. But quorum node will get down when I deploy below contract which from 7node example, I only modify privateFor value to mine. 

`a = eth.accounts[0]
web3.eth.defaultAccount = a;

// abi and bytecode generated from simplestorage.sol:
// > solcjs --bin --abi simplestorage.sol
var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"payable":false,"type":"constructor"}];

var bytecode = "0x6060604052341561000f57600080fd5b604051602080610149833981016040528080519060200190919050505b806000819055505b505b610104806100456000396000f30060606040526000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff1680632a1afcd914605157806360fe47b11460775780636d4ce63c146097575b600080fd5b3415605b57600080fd5b606160bd565b6040518082815260200191505060405180910390f35b3415608157600080fd5b6095600480803590602001909190505060c3565b005b341560a157600080fd5b60a760ce565b6040518082815260200191505060405180910390f35b60005481565b806000819055505b50565b6000805490505b905600a165627a7a72305820d5851baab720bba574474de3d09dbeaabc674a15f4dd93b974908476542c23f00029";

var simpleContract = web3.eth.contract(abi);
var simple = simpleContract.new(42, {from:web3.eth.accounts[0], data: bytecode, gas: 0x47b760, privateFor: ["Uc952L7QFuk8R5sGtjpfHb9EM+X6pTFRixVa+XgPBjc="]}, function(e, contract) {
	if (e) {
		console.log("err creating contract", e);
	} else {
		if (!contract.address) {
			console.log("Contract transaction send: TransactionHash: " + contract.transactionHash + " waiting to be mined...");
		} else {
			console.log("Contract mined! Address: " + contract.address);
			console.log(contract);
		}
	}
});
`

Does any one know this kind of issue? Thanks!

**Comment by zmmwl** [comment]
![1](https://user-images.githubusercontent.com/8197653/56780001-27529600-6810-11e9-827d-ca778029b12c.PNG)
![2](https://user-images.githubusercontent.com/8197653/56780007-2ae61d00-6810-11e9-954b-2e87364ca6e8.PNG)

seems communication issue with transaction manager through ipc file.

**Comment by zmmwl** [comment]
sorry it's my fault, I missed the export key word to set PRIVATE_CONFIG, which cause quorum node couldn't find ipc file that's the root cause of this issue. Please help close this issue. Sorry again.

**Comment by SatpalSandhu61** [comment]
Glad you resolved it.
