### ISSUE TITLE
How to fix the sync issues on Quorum??

### ISSUE THREAD

**Issue by muthu-param** [Consensys-Incorporated/quorum#695]
Hi there,

#### System information

Geth version: Geth/v1.8.18-stable-d715db38(quorum-v2.2.1)/linux-amd64/go1.9.2

OS & Version: Linux

Branch, Commit Hash : master / d715db38c4bf20d67e0991da2ea916455343df48

#### Actual behaviour
eth.syncing
false

We are using three AWS server, due to the overload of one server, I lost my geth connection in my servers. When I start geth again, my old block's is gone. It again starts with 0th blocks. While doing the geth sync mode am getting false.

**Comment by SatpalSandhu61** [comment]
What consensus mechanism are you using. Also, can you paste your geth command line and the genesis block here pls?

**Comment by muthu-param** [comment]
Hi @SatpalSandhu61,

We are using **RAFT** consensus mechanism.

**Geth Command line:** 

> PRIVATE_CONFIG=/home/ubuntu/alpha/tm.ipc nohup geth --datadir alpha/ --raft --rpc --port 21000 --rpcport 22000 --rpccorsdomain "*" --raftport 50401 --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --ws --wsaddr 0.0.0.0 --wsport 8546  --wsorigins "*" --wsapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft &

**Genesis block:**

`{
  "alloc": {
    "0x17fe0be7694fd6c81bca3953b796c5644665b170": {
      "balance": "200000000000000000000000000000000000"
    },
    "0x41a90b39b7e82c7272624233ee758b3f67dc889f": {
      "balance": "200000000000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0
  },
  "difficulty": "0x0",
  "extraData": "0x",
  "gasLimit": "0x2FEFD800",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}`

**Comment by SatpalSandhu61** [comment]
How large is your chain. There is a raft defect that was fixed in v2.2.2 where it fails to sync if the chain is out of sync by more than 8192 blocks (https://github.com/jpmorganchase/quorum/issues/614).

**Comment by muthu-param** [comment]
@SatpalSandhu61  My chain has less than 200 blocks. 

As per your command, it fails to sync if the chain is out of sync by more than 8192 blocks. How it will possible of out of sync more the 8192 blocks?. If it happens there is no security for the money or data. 

Plz, correct me if I am wrong.

**Comment by SatpalSandhu61** [comment]
It could be out of sync by 8192 (or more) blocks if the node has been down for long enough that the rest of the network has minted that many blocks (or if it's a new node)...

**Comment by muthu-param** [comment]
Plz, let me know, what is the root cast for these issues?

Kindly let me know, how you fixed these issues..?

**Comment by SatpalSandhu61** [comment]
It sounds like your node isn't actually attaching to the network and syncing. Are there any errors or warnings in the geth logs?
You can also try "raft" in the geth console to check that node is seeing all the peers and has joined as a validator or minter.

**Comment by fixanoid** [comment]
@Muthu-Divum please reopen if this is still an issue.
