### ISSUE TITLE
Block gas limit

### ISSUE THREAD

**Issue by Magicking** [Consensys-Incorporated/quorum#700]
It looks like the `2.2.2` patch imported this commit https://github.com/jpmorganchase/quorum/commit/e8f229b82ef99213f8f84b8a71f752b236024494, that changes the default target gas limit to `8,000,000` (ATOW: public ethereum mainnet) instead of the previous higher defined gas limit.

You now need with the `2.2.2+` version to use `--miner.gastarget XXX` and `--miner.gaslimit XXX` to set an other `gasLimit` per block.

Is this an intended behavior?
An update from `2.2.1` to `2.2.2` has the effect without setting this flag to reduce the `gasLimit` per block to the limit above.

**Comment by wenhuancai** [comment]
@Magicking 
I would like to temporarily fix this situation, it has affected my release of smart contract, how do I do

**Comment by jpmsam** [comment]
@wenhuancai you can increase the default low gas limit by setting these flags as suggested by @Magicking --miner.gastarget XXX and --miner.gaslimit XXX.
Since the default limits became configurable in 2.2.2+, we didn't adjust the lower limits but we are fixing that in https://github.com/jpmorganchase/quorum/pull/680

**Comment by wenhuancai** [comment]
i don't know how to set --miner.gastarget XXX and --miner.gaslimit XXX.
Is this place set up.(#PRIVATE_CONFIG=azdata/zdsi1/tm.ipc nohup $toolpath/geth --datadir azdata/dd1 $ARGS --permissioned --raftport $RAFPORT --rpccorsdomain "http://localhost:8181" --rpcport $RPCPORT --port $URLPORT --unlock 0 --password passwords.txt 2>>azdata/logs/1.log &
)
I tried it. It's wrong. The program can't communicate.
so,I tried other solutions.
	MinerGasCeil:  700000000,
	MinerGasCeil:  800000000,
  #680,
The script in the sample runs. and a new error has appeared
![image](https://user-images.githubusercontent.com/20059816/57754857-06e86e00-7722-11e9-9838-62f012d4058d.png)
The genesis.json is 
![image](https://user-images.githubusercontent.com/20059816/57754989-4e6efa00-7722-11e9-8242-f63b418f7fa1.png)

**Comment by SatpalSandhu61** [comment]
The "exceeds block gas limit" suggests that you are submitting a transaction with gas which exceeds the block gas limit. You need to either increase `gasLimit` in the genesis, or reduce the gas supplied for the transaction (ensuring it is still sufficient for the transaction to succeed).

This parameters suggested earlier should be added to the command line, e.g.:
```
PRIVATE_CONFIG=azdata/zdsi1/tm.ipc nohup $toolpath/geth --datadir azdata/dd1 $ARGS --permissioned --raftport $RAFPORT --rpccorsdomain "http://localhost:8181" --rpcport $RPCPORT --port $URLPORT --unlock 0 --password passwords.txt --miner.gastarget XXXX --miner.gaslimit XXXX 2>>azdata/logs/1.log &
```

**Comment by wenhuancai** [comment]
![image](https://user-images.githubusercontent.com/20059816/57762200-a3663c80-7731-11e9-9953-ff006eb8277a.png)
This one doesn't work

root@2880e441b23a:/home/anzheng# cat runscript.sh
PRIVATE_CONFIG=azdata/zdsi1/tm.ipc geth --miner.gastarget 3300000 --miner.gaslimit 80000000000 --exec "loadScript("$1")" attach ipc:azdata/dd1/geth.ipc
err creating contract Error: exceeds block gas limit
true
root@2880e441b23a:/home/anzheng# cat runscript.sh
PRIVATE_CONFIG=azdata/zdsi1/tm.ipc geth --exec "loadScript("$1")" attach ipc:azdata/dd1/geth.ipc
root@2880e441b23a:/home/anzheng#
Adding to this sample script also does not work

**Comment by wenhuancai** [comment]
root@2880e441b23a:/home/anzheng# cat runscript.sh 
PRIVATE_CONFIG=azdata/zdsi1/tm.ipc geth --miner.gastarget 3300000 --miner.gaslimit 80000000000 --exec "loadScript(\"$1\")" attach ipc:azdata/dd1/geth.ipc
err creating contract Error: exceeds block gas limit
true
root@2880e441b23a:/home/anzheng# cat runscript.sh 
PRIVATE_CONFIG=azdata/zdsi1/tm.ipc geth --exec "loadScript(\"$1\")" attach ipc:azdata/dd1/geth.ipc
root@2880e441b23a:/home/anzheng# 
Adding to this sample script also does not work

**Comment by SatpalSandhu61** [comment]
What is the gasLimit in your genesis?

**Comment by wenhuancai** [comment]
![image](https://user-images.githubusercontent.com/20059816/57766652-5175e480-773a-11e9-937e-c341b7538c6c.png)

**Comment by wenhuancai** [comment]
![image](https://user-images.githubusercontent.com/20059816/57849136-20b2af80-780d-11e9-82c0-f9992943aebf.png)
I printed out l to find a limit
![image](https://user-images.githubusercontent.com/20059816/57849181-3b852400-780d-11e9-90d9-7d3c1cef0cca.png)
Gas is max =5000？
Is there anything wrong with the way I write this？

**Comment by vasa-develop** [comment]
@wenhuancai did you solve the issue?
