### ISSUE TITLE
Vagrantfile -- not working behind http_proxy

### ISSUE THREAD

**Issue by hvram1** [Consensys-Incorporated/quorum#71]
Please add the following lines in the vagrant file . This will make this work within all corporate firewalls . 

> config.vm.box = "ubuntu/xenial64"
  if Vagrant.has_plugin?("vagrant-proxyconf")
      config.proxy.http     = ENV['HTTP_PROXY']
      config.proxy.https    = ENV['HTTPS_PROXY']
      config.proxy.no_proxy = "localhost,127.0.0.1"
  end

**Comment by patrickmn** [comment]
Previous issue: https://github.com/jpmorganchase/quorum/issues/23

The ENV approach is nice. We'll test and add if there are no issues.
