### ISSUE TITLE
contract creation code storage out of gas:

### ISSUE THREAD

**Issue by wenhuancai** [Consensys-Incorporated/quorum#710]
When the program starts, it is always displayed：
INFO [05-09|11:58:08.882] VM returned with error                   err="contract creation code storage out of gas".
![image](https://user-images.githubusercontent.com/20059816/57516553-88698600-7347-11e9-8347-84ad15168dc9.png)
But the picture shows that the contract was published。
INFO [05-10|11:58:08.882]At this point in time, the block is not increasing.
![image](https://user-images.githubusercontent.com/20059816/57516894-39702080-7348-11e9-8882-6c76c5d5b476.png)
Now the release contract has been a failure.

**Comment by wenhuancai** [comment]
![image](https://user-images.githubusercontent.com/20059816/57517478-843e6800-7349-11e9-9653-a99b2a9b0e40.png)
This is the code for the release contract

**Comment by fixanoid** [comment]
Hi @wenhuancai. Please provide some more detail: which version of Quorum? What was the smart contract?

As for the code in your 2nd sample, it looks like you instantiate `tx_parm` but only `transaction` var is being used, so data bit is ignored.

**Comment by wenhuancai** [comment]
thank you!
This smart contract is quorum-examples.
I found that I worked with version 2.2.1 yesterday，This version works fine.
But The latest version is wrong,
I think it's the problem 
[@700](https://github.com/jpmorganchase/quorum/issues/700)

**Comment by jpmsam** [comment]
@wenhuancai please update the gas limits as suggested in #700 and let us know if this is still an issue.
