### ISSUE TITLE
Getting 'Failed to start Ledger hub, disabling: libusb: unknown error [code -99]' while running init.sh

### ISSUE THREAD

**Issue by privin** [Consensys-Incorporated/quorum#72]
#### System information

Geth version: `1.5.9-stable`

OS & Version: OSX

Branch, Commit Hash or Release: `git status`

#### Expected behaviour

[*] Cleaning up temporary data directories
[*] Configuring node 1
[*] Configuring node 2 as block maker and voter
[*] Configuring node 3
[*] Configuring node 4 as voter
[*] Configuring node 5 as voter
[*] Configuring node 6
[*] Configuring node 7

#### Actual behaviour

[*] Cleaning up temporary data directories
[*] Configuring node 1
I0308 12:40:47.339045 node/config.go:445] Failed to start Ledger hub, disabling: libusb: unknown error [code -99]
I0308 12:40:47.342796 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd1/geth/chaindata
I0308 12:40:47.364423 ethdb/database.go:176] closed db:/vagrant/examples/7nodes/qdata/dd1/geth/chaindata
I0308 12:40:47.365311 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd1/geth/chaindata
I0308 12:40:47.399633 cmd/geth/chaincmd.go:132] successfully wrote genesis block and/or chain rule set: 8bb911238205c6d5e9841335c9c5aff3dfae4c0f6b0df28100737c2660a15f8d
[*] Configuring node 2 as block maker and voter
I0308 12:40:47.467341 node/config.go:445] Failed to start Ledger hub, disabling: libusb: unknown error [code -99]
I0308 12:40:47.471886 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd2/geth/chaindata
I0308 12:40:47.494898 ethdb/database.go:176] closed db:/vagrant/examples/7nodes/qdata/dd2/geth/chaindata
I0308 12:40:47.495900 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd2/geth/chaindata
I0308 12:40:47.531871 cmd/geth/chaincmd.go:132] successfully wrote genesis block and/or chain rule set: 8bb911238205c6d5e9841335c9c5aff3dfae4c0f6b0df28100737c2660a15f8d
[*] Configuring node 3
I0308 12:40:47.588897 node/config.go:445] Failed to start Ledger hub, disabling: libusb: unknown error [code -99]
I0308 12:40:47.591326 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default
I0308 12:40:47.592437 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd3/geth/chaindata
I0308 12:40:47.611397 ethdb/database.go:176] closed db:/vagrant/examples/7nodes/qdata/dd3/geth/chaindata
I0308 12:40:47.612307 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd3/geth/chaindata
I0308 12:40:47.653402 cmd/geth/chaincmd.go:132] successfully wrote genesis block and/or chain rule set: 8bb911238205c6d5e9841335c9c5aff3dfae4c0f6b0df28100737c2660a15f8d
[*] Configuring node 4 as voter
I0308 12:40:47.718636 node/config.go:445] Failed to start Ledger hub, disabling: libusb: unknown error [code -99]
I0308 12:40:47.722003 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd4/geth/chaindata
I0308 12:40:47.743173 ethdb/database.go:176] closed db:/vagrant/examples/7nodes/qdata/dd4/geth/chaindata
I0308 12:40:47.743996 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd4/geth/chaindata
I0308 12:40:47.776097 cmd/geth/chaincmd.go:132] successfully wrote genesis block and/or chain rule set: 8bb911238205c6d5e9841335c9c5aff3dfae4c0f6b0df28100737c2660a15f8d
[*] Configuring node 5 as voter
I0308 12:40:47.842876 node/config.go:445] Failed to start Ledger hub, disabling: libusb: unknown error [code -99]
I0308 12:40:47.844185 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd5/geth/chaindata
I0308 12:40:47.865765 ethdb/database.go:176] closed db:/vagrant/examples/7nodes/qdata/dd5/geth/chaindata
I0308 12:40:47.867094 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd5/geth/chaindata
I0308 12:40:47.902816 cmd/geth/chaincmd.go:132] successfully wrote genesis block and/or chain rule set: 8bb911238205c6d5e9841335c9c5aff3dfae4c0f6b0df28100737c2660a15f8d
[*] Configuring node 6
I0308 12:40:47.961862 node/config.go:445] Failed to start Ledger hub, disabling: libusb: unknown error [code -99]
I0308 12:40:47.964061 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default
I0308 12:40:47.965102 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd6/geth/chaindata
I0308 12:40:47.990171 ethdb/database.go:176] closed db:/vagrant/examples/7nodes/qdata/dd6/geth/chaindata
I0308 12:40:47.991111 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd6/geth/chaindata
I0308 12:40:48.032121 cmd/geth/chaincmd.go:132] successfully wrote genesis block and/or chain rule set: 8bb911238205c6d5e9841335c9c5aff3dfae4c0f6b0df28100737c2660a15f8d
[*] Configuring node 7
I0308 12:40:48.088544 node/config.go:445] Failed to start Ledger hub, disabling: libusb: unknown error [code -99]
I0308 12:40:48.090904 cmd/utils/flags.go:613] WARNING: No etherbase set and no accounts found as default
I0308 12:40:48.092105 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd7/geth/chaindata
I0308 12:40:48.112309 ethdb/database.go:176] closed db:/vagrant/examples/7nodes/qdata/dd7/geth/chaindata
I0308 12:40:48.113170 ethdb/database.go:83] Allotted 128MB cache and 1024 file handles to /vagrant/examples/7nodes/qdata/dd7/geth/chaindata
I0308 12:40:48.148037 cmd/geth/chaincmd.go:132] successfully wrote genesis block and/or chain rule set: 8bb911238205c6d5e9841335c9c5aff3dfae4c0f6b0df28100737c2660a15f8d

#### Steps to reproduce the behaviour
By running init.sh
#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
hi @privin, can you please confirm that you ssh'd into the vagrant env? From your stacktrace it doesn't seem like you have.  Full instructions [here](https://github.com/jpmorganchase/quorum-examples#running).

**Comment by privin** [comment]
hi @tylobban Yes, its from vagrant...here's the command

ubuntu@ubuntu-xenial:/vagrant/examples/7nodes$ ./init.sh

**Comment by tylobban** [comment]
you should be in the quorum-examples dir instead.  please run `cd ~/quorum-examples/7nodes` and run try from there instead.

**Comment by privin** [comment]
A silly doubt @tylobban: when I do vagrant ssh, I dont see any  `~/quorum-examples/7nodes` directory.

ubuntu@ubuntu-xenial:~$ ls
go  go1.7.3.linux-amd64.tar.gz

**Comment by tylobban** [comment]
@privin are you sure you have followed the steps correctly? Perhaps remove the quorum-examples clone and start again.  You should see this:
![quorum-examples_ _ubuntu_ubuntu-xenial____ _ssh_ _140x42_and_quorum-examples_ _ubuntu_ubuntu-xenial____quorum-examples_7nodes_ _bash_ _80x24](https://cloud.githubusercontent.com/assets/17066496/23724590/3476733c-0445-11e7-9f33-e834c385743e.png)

**Comment by patrickmn** [comment]
Agree -- this sounds like a network connectivity issue during the provisioning of the Vagrant image. `vagrant destroy` followed by `vagrant up` should hopefully fix it.

**Comment by coeniebeyers** [comment]
What is the output of running `which geth` ?

**Comment by privin** [comment]
Thanks guys. It works by taking the fresh pull. Closing the issue.
