### ISSUE TITLE
 transaction to be stuck in pending state

### ISSUE THREAD

**Issue by wenhuancai** [Consensys-Incorporated/quorum#724]
I'm using version V2.2.3, and I'll loop through the test cases.Trading will be suspended between 15 and 20w after two tests.Pending num is 30000. After I restart the node, the 30000 data can be synchronized.
![image](https://user-images.githubusercontent.com/20059816/58299259-30378700-7e11-11e9-93c6-fc057ec8a866.png)
![image](https://user-images.githubusercontent.com/20059816/58299348-8ad0e300-7e11-11e9-88bd-df19e5c47d82.png)
Contracts are submitted all the time, but are not synchronized with other nodes，After I restart the node, the 30000 data can be synchronized.
I also got a new error on the other nodes,when that node restarts.
![image](https://user-images.githubusercontent.com/20059816/58299506-ebf8b680-7e11-11e9-9f61-fbe8c5dc4ed9.png)

**Comment by wenhuancai** [comment]
This phenomenon can be reproduced.I only have one node publishing contracts.The number of nodes currently publishing contracts is smaller than a few others.

**Comment by wenhuancai** [comment]
This phenomenon can be reproduced.I only have one node publishing contracts.The number of nodes currently publishing contracts is smaller than a few others.

**Comment by vsmk98** [comment]
HI @wenhuancai can you share the following details with us:
- Network details, how many nodes
- CPU and memory details for each node
- what is the value of --raft.blocktime when you are bringing up geth
- How are you executing the transactions

**Comment by wenhuancai** [comment]
（1）Linux c824fa16d246 4.15.0-50-generic 54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
（2） 1 physical id	: 0
      1 address sizes	: 43 bits physical, 48 bits virtual
(3)How to view (--raft.blocktime)
(4)use quorum-example:runscript.sh and public-contract.js
`
#！/bin/sh
while : 
do
	/home/data/runscript.sh /home/data/public-contract.js
	usleep 1000000
done
`

**Comment by libby** [comment]
@wenhuancai could you also check the p2p connections, and the raft peers from the geth console? 
```
geth attach geth.ipc
> admin.peers
> raft.cluster
```

**Comment by wenhuancai** [comment]
> admin.peers
[]
> raft.cluster
[{
    ip: "192.168.0.163",
    nodeId: "7fbe26306a6c3566987f6376449fc2e206433cc907e76fbe0ed82c4e78d3925cafe355fb3c5f10c157d840b3ec418e30c7574aa0787eba2b164b33e5ebd05fce",
    p2pPort: 51000,
    raftId: 2,
    raftPort: 51001
}, {
    ip: "192.168.0.166",
    nodeId: "fff07e37f9a23deaabe94f67ea62d36d66218470718beb98118d93d0c7be0fc7203416119fb436a2d8adab2bb7792ad515ac38dd9821d09ce8d9ee1c282b4cfd",
    p2pPort: 51000,
    raftId: 3,
    raftPort: 51001
}, {
    ip: "192.168.0.50",
    nodeId: "b49bb7877b9ef815e299212fa05964d3e2e5f31f9b5b8640ce165c97755b90c5120c853b141735716e4bc01da2f129db2ca69a08baa6b1efe05381ff64194aaa",
    p2pPort: 51000,
    raftId: 4,
    raftPort: 51001
}, {
    ip: "192.168.0.53",
    nodeId: "c4ccc779d9cd3da0b9279fb2ba41f26964105bbdb8c831109803d3e105b2a0ae4d962b23eb36ab12278e1bbc63a4b34fb8aef6a3cf77b08f2572ae18036449cf",
    p2pPort: 51000,
    raftId: 5,
    raftPort: 51001
}, {
    ip: "192.168.0.61",
    nodeId: "f049cfe1c790a40903eafdbec309ff38b7b95f7cded9f80c345177174cfe4386cce2fb46842d6602ebb31302ec1b77cc94e43a8af8b6610b416c595f8e9494b9",
    p2pPort: 51000,
    raftId: 1,
    raftPort: 51001
}]
The data of this node does not match with other nodes, and there is no consensus.If you restart it, it will return to normal.
The problem is I only have this node reentry data, which is the master node.Why is there less data than other nodes, and why is it discarded

**Comment by wenhuancai** [comment]
> admin.peers
[]
> raft.cluster
[{
    ip: "192.168.0.163",
    nodeId: "7fbe26306a6c3566987f6376449fc2e206433cc907e76fbe0ed82c4e78d3925cafe355fb3c5f10c157d840b3ec418e30c7574aa0787eba2b164b33e5ebd05fce",
    p2pPort: 51000,
    raftId: 2,
    raftPort: 51001
}, {
    ip: "192.168.0.166",
    nodeId: "fff07e37f9a23deaabe94f67ea62d36d66218470718beb98118d93d0c7be0fc7203416119fb436a2d8adab2bb7792ad515ac38dd9821d09ce8d9ee1c282b4cfd",
    p2pPort: 51000,
    raftId: 3,
    raftPort: 51001
}, {
    ip: "192.168.0.50",
    nodeId: "b49bb7877b9ef815e299212fa05964d3e2e5f31f9b5b8640ce165c97755b90c5120c853b141735716e4bc01da2f129db2ca69a08baa6b1efe05381ff64194aaa",
    p2pPort: 51000,
    raftId: 4,
    raftPort: 51001
}, {
    ip: "192.168.0.53",
    nodeId: "c4ccc779d9cd3da0b9279fb2ba41f26964105bbdb8c831109803d3e105b2a0ae4d962b23eb36ab12278e1bbc63a4b34fb8aef6a3cf77b08f2572ae18036449cf",
    p2pPort: 51000,
    raftId: 5,
    raftPort: 51001
}, {
    ip: "192.168.0.61",
    nodeId: "f049cfe1c790a40903eafdbec309ff38b7b95f7cded9f80c345177174cfe4386cce2fb46842d6602ebb31302ec1b77cc94e43a8af8b6610b416c595f8e9494b9",
    p2pPort: 51000,
    raftId: 1,
    raftPort: 51001
}]
This node can no longer agree with other nodes，It will return to normal after restarting
The problem is I only have this node reentry data, which is the master node.Why is there less data than other nodes, and why is it discarded

**Comment by wenhuancai** [comment]
Sorry, I accidentally turned this problem off. How do I open this problem

**Comment by vsmk98** [comment]
@wenhuancai, I see that admin.peers is [] currently which means the p2p connection between nodes is not established properly. Wanted to check if the network connected properly when you brought up all the nodes. 
Also can you add `--raftblocktime 250` to geth start command and rerun the tests and let us know the results?

**Comment by libby** [comment]
@wenhuancai can your run [add-p2p-nodes.sh](https://github.com/jpmorganchase/quorum-examples/blob/add-p2p-nodes/examples/7nodes/add-p2p-nodes.sh)  in https://github.com/jpmorganchase/quorum-examples/pull/176/commits/8889387131555b74c02de0672c6f48fe15c7c37c 
* modify the script to point at your `tmp.ipc` and `geth.ipc` 
```
echo "$ADD_PEERS" | while read -r addPeer; do 
  PRIVATE_CONFIG=qdata/c1/tm.ipc geth --exec $addPeer attach ipc:qdata/dd1/geth.ipc  
done
```
Afterward `>admin.peers` should be connect and could you rerun your tests?

**Comment by wenhuancai** [comment]
![image](https://user-images.githubusercontent.com/20059816/58605565-d3cddf00-82ca-11e9-969a-92595def49c6.png)
@libby   can see the other nodes.The master node num is 150435.other is 150437
![image](https://user-images.githubusercontent.com/20059816/58605613-fcee6f80-82ca-11e9-922a-96ba646695e5.png)
![image](https://user-images.githubusercontent.com/20059816/58605724-65d5e780-82cb-11e9-8c5a-2281eb0e4a67.png)
Contracts can be published, but they are all in the trading pool, with no blocks generated and no synchronization

**Comment by wenhuancai** [comment]
@vsmk98  Do I need to clear all the data?Retest?

**Comment by vsmk98** [comment]
Its better to clear the data and rerun the tests with higher blocktime

**Comment by wenhuancai** [comment]
You think that the time of raft was too fast, resulting in the fact that 15w-20w would not be packaged into blocks @vsmk98

**Comment by vsmk98** [comment]
@wenhuancai what I have seen is in resource constrained environment, 50ms blocktime leads to frequent leader election and can result in nodes going out of sync in raft. 250ms works better.

**Comment by libby** [comment]
@wenhuancai also if the p2p layer is disconnect then transaction submitted to a node will remain in the txpool in a pending state, as they will not be propagated to the other nodes. If you get in that state again, can you reconnect the p2p layer make sure all the nodes see each other, and then submit a transaction to test. All nodes should have the same peer count when you run `net`.

**Comment by wenhuancai** [comment]
@libby  The beginning has been reconnected.Just now, I saw The master node num is （150435 turn to 150437）.But the data in the trading pool still does not generate blocks
I have cleared the data now and need to wait for another time

**Comment by wenhuancai** [comment]
add-p2p-nodes.sh ，Can I call that script if net is not equal?Or only if admin.peer = []？
@libby

**Comment by libby** [comment]
@wenhuancai yes you can call the script anytime, it is idempotent. I update it right now to execute on all 7 nodes (if you are running the 7 nodes example). Make sure that it adds peers to each node that you are running, and afterward check `net` and `peerCount` should display the same number of peers on each node. 
```
echo "$ADD_PEERS" | while read -r addPeer; do 
  for i in {1..7}; do 
    PRIVATE_CONFIG=qdata/c$i/tm.ipc geth --exec $addPeer attach ipc:qdata/dd$i/geth.ipc  
  done
done
```

**Comment by wenhuancai** [comment]
There's another problem. This is the second time.
All nodes are communicating normally.
Contracts can be published, but not returned（success）.
1.tar.gz is the log.
[1.tar.gz](https://github.com/jpmorganchase/quorum/files/3236509/1.tar.gz)
![image](https://user-images.githubusercontent.com/20059816/58625954-2082db80-8306-11e9-8085-7963a58d51fd.png)
![image](https://user-images.githubusercontent.com/20059816/58625981-309abb00-8306-11e9-9e50-2ed38ee4cd83.png)
But the data was synchronized successfully，

**Comment by vsmk98** [comment]
@wenhuancai you mean the contract addresses were not returned post deployment?

**Comment by wenhuancai** [comment]
Yeah, it's stuck there all the time

**Comment by wenhuancai** [comment]
There is still that phenomenon. @vsmk98 .It's back to normal after rebooting.

**Comment by amalrajmani** [comment]
@wenhuancai can we connect on slack and discuss more about this issue?

**Comment by wenhuancai** [comment]
Sure. How can I contact you

**Comment by amalrajmani** [comment]
follow this link https://clh7rniov2.execute-api.us-east-1.amazonaws.com/Express/
also get Slack installed and join quorum.
You can post issues #development chat

**Comment by fixanoid** [comment]
Closed via slack. Pleasere open if the issue persists.

**Comment by YazzyYaz** [comment]
Hi, I'm running into a similar issue where my transactions get stuck in a pending state and Truffle errors out after 750s of waiting.

When I type in `net`, I get 1 Peer count which is the bootnode I'm connecting to.

I'm currently running a node that's syncing with an existing Quorum network that someone else built and connecting to it via the bootnode.

Another weird behavior I saw is that yesterday, same issue happened, both with contract deployment and transferring ETH from my account. 4 transactions pending. Only today where they submitted.

My question is trying to understand why this is the case and how to speed up the submission of transactions from the txpool.

**Comment by fixanoid** [comment]
@YazzyYaz could you please open new issue so we could get some details? At minimum, we'd need to look at truffle config, genesis, and node start parameters. Thank you.
