### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by wenhuancai** [Consensys-Incorporated/quorum#725]
If I use a previous version, how do I upgrade.
I found that the bin file directory would have all sorts of problems with direct substitution;
old version is  1.7.2

**Comment by vsmk98** [comment]
@wenhuancai for upgrade, the suggested steps are:
1. Bring down the node
2. Upgrade the geth to the desired version 
3. bring the node back up
Can you tell me the issues you are facing here?

**Comment by wenhuancai** [comment]
1)old version: 2.0.2  ,now version:2.2.3
test:After recording data with the old version, connect with the new version node
result: error message, unable to connect to the new version node, the new version node judged the other 4 nodes as unhealthy nodes
2))old version: 2.0.2  ,now version:2.2.3
test:After data entry with the old version, stop the current version node and replace it with the new version node to load the current data
result:：
raft2019/05/24 10:37:34 applied(155580) is out of range [prevApplied(155804), committed(155807)]
panic: applied(155580) is out of range [prevApplied(155804), committed(155807)]

The upgrade method:
To replace the directory:build/bin/

**Comment by vsmk98** [comment]
If I understand correctly, you have upgraded only one node in the network to 2.2.3 and rest continue to be on 2.0.2. If this is the case, please refer to the compatibility matrix https://docs.goquorum.com/en/latest/FAQ/ 
Version 2.0.2 is not compatible with 2.2.3 and hence you will have to upgrade all nodes to 2.2.3

**Comment by wenhuancai** [comment]
Ok, let me retest that.

**Comment by Krish1979** [comment]
Please reopen issue if further support is required.
