### ISSUE TITLE
Unable to send first transaction to node in 7node example

### ISSUE THREAD

**Issue by gunjan07** [Consensys-Incorporated/quorum#73]
#### System information

Geth version: `geth version` 
1.5.6-stable

OS & Version: Linux

Branch, Commit Hash or Release: 
jpmorganchase/quorum

#### Expected behaviour
err creating contract Error: Non-200 status code: &{Status:500 Internal Server Error StatusCode:500 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Date:[Wed, 08 Mar 2017 15:46:21 GMT] Server:[Warp/3.2.8]] Body:0xc42090da40 ContentLength:-1 TransferEncoding:[chunked] Close:false Uncompressed:false Trailer:map[] Request:0xc42087fd10 TLS:<nil>}

#### Actual behaviour
Unlocking account and sending first transaction
Contract transaction send: TransactionHash: 0xbfb7bfb97ba9bacbf768e67ac8ef05e4ac6960fc1eeb6ab38247db91448b8ec6 waiting to be mined...
true

#### Steps to reproduce the behaviour
./start.sh in 7node example

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
hi @gunjan07, can you please confirm that you ssh'd into the vagrant env? From your geth version it doesn't seem like you have.  Full instructions [here](https://github.com/jpmorganchase/quorum-examples#running).

**Comment by gunjan07** [comment]
Worked with the new Vagrant Up command ..
THanks
