### ISSUE TITLE
geth attach new-node-1/geth.ipc - new-node-1/geth.ipc: connect: no such file or directory

### ISSUE THREAD

**Issue by shivamanmadha** [Consensys-Incorporated/quorum#732]

**Comment by shivamanmadha** [comment]
PRIVATE_CONFIG=ignore geth --datadir new-node-1 --nodiscover --ipcpath --networkid 31337 console --raft --raftport 50401 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 2>>node.log &

I am able to see the process below:

root     13415 12723  0 04:24 pts/3    00:00:00 geth --datadir /tmp/quorum/new-node-1 --nodiscover --ipcpath /tmp/quorum/new-node-1 --networkid 31337 console --raft --raftport 50401 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000

geth attach new-node-1/geth.ipc
Fatal: Unable to attach to remote geth: dial unix new-node-1/geth.ipc: connect: no such file or directory

**Comment by SatpalSandhu61** [comment]
I can see that you have actually overridden the default path to the ipc file with the command line option `--ipcpath /tmp/quorum/new-node-1`. That option gives the *full path* to the file... so in your case you now need to use:
```
geth attach /tmp/quorum/new-node-1
```

I suggest you use the following on the geth startup command line: `--ipcpath /tmp/quorum/new-node-1/geth.ipc`

**Comment by shivamanmadha** [comment]
root@test-vm:/tmp/quorum# geth attach /tmp/quorum/new-node-1
Fatal: Unable to attach to remote geth: dial unix /tmp/quorum/new-node-1: connect: connection refused

root@test-vm:/tmp/quorum# geth attach /tmp/quorum/new-node-1/geth.ipc
Fatal: Unable to attach to remote geth: dial unix /tmp/quorum/new-node-1/geth.ipc: connect: no such file or directory

root@test-vm:/tmp/quorum# geth attach --ipcpath /tmp/quorum/new-node-1/geth.ipc
Incorrect Usage: flag provided but not defined: -ipcpath

attach [command options] [arguments...]

The Geth console is an interactive shell for the JavaScript runtime environment
which exposes a node admin interface as well as the Ðapp JavaScript API.
See https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console.
This command allows to open a console on a running geth node.

ETHEREUM OPTIONS:
  --datadir "/root/.ethereum"  Data directory for the databases and keystore

API AND CONSOLE OPTIONS:
  --jspath loadScript  JavaScript root path for loadScript (default: ".")
  --exec value         Execute JavaScript statement
  --preload value      Comma separated list of JavaScript files to preload into the console

flag provided but not defined: -ipcpath

And i am not able to see the geth.ipc  in new-node-1

**Comment by shivamanmadha** [comment]
PRIVATE_CONFIG=ignore geth --datadir new-node-1 --nodiscover --ipcpath /tmp/quorum/new-node-1 --networkid 31337 console --raft --raftport 50401 --rpc --rpcaddr 192.168.195.186 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 2>>node.log &

**Comment by SatpalSandhu61** [comment]
You haven't corrected your geth node startup command. It should be:
```
PRIVATE_CONFIG=ignore geth --datadir new-node-1 --nodiscover --ipcpath /tmp/quorum/new-node-1/geth.ipc --networkid 31337 console --raft --raftport 50401 --rpc --rpcaddr 192.168.195.186 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 2>>node.log &
```

As per my earlier comment, you need: `--ipcpath /tmp/quorum/new-node-1/geth.ipc`

**Comment by shivamanmadha** [comment]
root@test-vm:/tmp/quorum# PRIVATE_CONFIG=ignore geth --datadir new-node-1 --nodiscover --ipcpath /tmp/quorum/new-node-1/geth.ipc --networkid 31337 console --raft --raftport 50401 --rpc --rpcaddr 192.168.195.186 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 2>>node.log &
[1] 23782

-----------------------------------------------
root@test-vm:/tmp/quorum/new-node-1# ls -lrt
total 12
drwx------ 2 root root 4096 Jun  4 17:17 keystore
-rw------- 1 root root   64 Jun  5 08:04 nodekey
-rw-r--r-- 1 root root    0 Jun  5 10:01 node.log
drwxr-xr-x 5 root root 4096 Jun  5 10:26 geth
-------------------------------------------------------
root@test-vm:/tmp/quorum/new-node-1# cd ..
root@test-vm:/tmp/quorum# geth attach --ipcpath /tmp/quorum/new-node-1/geth.ipc
Incorrect Usage: flag provided but not defined: -ipcpath

attach [command options] [arguments...]

The Geth console is an interactive shell for the JavaScript runtime environment
which exposes a node admin interface as well as the Ðapp JavaScript API.
See https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console.
This command allows to open a console on a running geth node.

ETHEREUM OPTIONS:
  --datadir "/root/.ethereum"  Data directory for the databases and keystore

API AND CONSOLE OPTIONS:
  --jspath loadScript  JavaScript root path for loadScript (default: ".")
  --exec value         Execute JavaScript statement
  --preload value      Comma separated list of JavaScript files to preload into the console

flag provided but not defined: -ipcpath


root@test-vm:/tmp/quorum# geth attach /tmp/quorum/new-node-1/geth.ipc
Fatal: Unable to attach to remote geth: dial unix /tmp/quorum/new-node-1/geth.ipc: connect: no such file or directory

I have made all the changes still geth.ipc not found.

**Comment by SatpalSandhu61** [comment]
No - don't pass that ipcpath parameter when you're trying to attach. That parameter should only be specified when you're starting a node process.
Also, don't start the node with the 'console' command line option. That won't work since you're running it in the background.
Finally, make sure the directory /tmp/quorum/new-node-1 exists and is initialised with geth data.
Then, follow these instructions *exactly* (running them from the same directory):
```
#Start the node
PRIVATE_CONFIG=ignore nohup geth --datadir new-node-1 --nodiscover --ipcpath /tmp/quorum/new-node-1/geth.ipc --networkid 31337 --raft --raftport 50401 --rpc --rpcaddr 192.168.195.186 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 2>>node.log &

#Connect a console to the node
geth attach new-node-1/geth.ipc
```

To be honest, I don't know why you're passing the '--ipcpath' parameter. You only need that if you're trying to place the ipc file in a separate directory from the rest of the data.
You can read about the command line options here:
https://github.com/ethereum/go-ethereum/wiki/Command-Line-Options

I strongly suggest you follow the quorum 7-nodes example and get familiar with quorum first:
https://github.com/jpmorganchase/quorum-examples

**Comment by shivamanmadha** [comment]
I have done the same as above but no luck. I m able to start the process without nohup but geth.ipc not created. 

PRIVATE_CONFIG=ignore nohup geth --datadir new-node-1 --nodiscover --ipcpath /tmp/quorum/new-node-1/geth.ipc --networkid 31337 --raft --raftport 50401 --rpc --rpcaddr xx.xx.xx.xx --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 2>>node.log &

![image](https://user-images.githubusercontent.com/37174328/59082694-005ca900-8912-11e9-82b8-0952bc1ad8fa.png)

**Comment by shivamanmadha** [comment]
using nohup ..its not running in the background.

**Comment by SatpalSandhu61** [comment]
Closing this issue as I can see you've also raised the question on Slack
(plus this is not a Quorum issue, but a usage mistake).
