### ISSUE TITLE
Raft is undefined

### ISSUE THREAD

**Issue by dmytronasyrov** [Consensys-Incorporated/quorum#733]
Suddenly 'raft' module starts to be undefined. Have spent already 2 days trying to figure it out. Quorum version - latest master.

<img width="761" alt="Screen Shot 2019-06-08 at 11 16 26" src="https://user-images.githubusercontent.com/1569896/59144333-27cd7780-89df-11e9-94fd-1a95b53d0a83.png">

`PRIVATE_CONFIG=ignore nohup geth --verbosity 5 --datadir /opt/blockchain/quorum/qdata --raft --networkid 10 --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --rpccorsdomain "*" --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --raftport 50400 --port 21000 --unlock 0 --password /opt/blockchain/quorum/passwords 2> /opt/blockchain/quorum/logs/geth.log`

**Comment by zzy96** [comment]
Hi, can you provide detailed steps to reproduce this issue?

**Comment by dmytronasyrov** [comment]
> Hi, can you provide detailed steps to reproduce this issue?

There are 3 nodes of Quorum starting with the Geth command above. No Tesseras or Constellations. All nodes have ntp synchronization and see each other in admin.peers. On the screenshot, there is raft:1.0 in instance modules.
Can you elaborate on things that can be a cause?

**Comment by fixanoid** [comment]
@dmytronasyrov thats very weird. Could you dump out running processies on the machine(s) and your attach command too? Thanks!

**Comment by dmytronasyrov** [comment]
<img width="1034" alt="Screen Shot 2019-06-17 at 11 14 06" src="https://user-images.githubusercontent.com/1569896/59588805-209a1e00-90f1-11e9-9e21-b2bb13a2cc69.png">
<img width="749" alt="Screen Shot 2019-06-17 at 11 15 06" src="https://user-images.githubusercontent.com/1569896/59588849-3871a200-90f1-11e9-94ba-d27a230cf82d.png">
<img width="754" alt="Screen Shot 2019-06-17 at 11 15 24" src="https://user-images.githubusercontent.com/1569896/59588862-3c052900-90f1-11e9-9e18-64727c7a1b49.png">

**Comment by jbhurat** [comment]
Thanks @dmytronasyrov for the info. Can you please provide the below information as well, 

- Are any other modules that are not working or is it just `raft`. Is the node operational, can you submit transactions 
- I see that there are not many processes running are you running in a dockerized environment. 
- How was Geth built and deployed
- Did the node crashed or was restarted

**Comment by SatpalSandhu61** [comment]
I notice you're attaching to port 1010/1011 with 'geth console'.
However, the geth process you gave command line information for is running on RPC port 8545.

Is it possible you're attaching to a geth process that was started without the 'raft' api?
Try `ps -ef | grep 1010` to see what you're attaching to.

**Comment by dmytronasyrov** [comment]
> Thanks @dmytronasyrov for the info. Can you please provide the below information as well,
> 
> * Are any other modules that are not working or is it just `raft`. Is the node operational, can you submit transactions
> * I see that there are not many processes running are you running in a dockerized environment.
> * How was Geth built and deployed
> * Did the node crashed or was restarted

1. Only raft. Yes, the node works fine.
2. https://github.com/PharosProduction/quorum/blob/master/Dockerfile
3. Please refer to dockerfile above. Dockerfile almost the same as in official Quorum repo. And I'm connecting with my local Geth installed with brew.
4. No. And the environment is a docker-compose in a bridge mode.

**Comment by dmytronasyrov** [comment]
> I notice you're attaching to port 1010/1011 with 'geth console'.
> However, the geth process you gave command line information for is running on RPC port 8545.
> 
> Is it possible you're attaching to a geth process that was started without the 'raft' api?
> Try `ps -ef | grep 1010` to see what you're attaching to.

1. Yes, 10010 is a remapped port from 8545 in docker-compose. I have tried to leave 8545 as a connection port but result is the same - raft is undefined.

<img width="776" alt="Screen Shot 2019-06-17 at 22 42 21" src="https://user-images.githubusercontent.com/1569896/59631772-5242d180-9151-11e9-8836-c932078ede7e.png">

2. Proper shot. I have tried to attach to with geth from within container A to container B. Raft module works! So the reason why raft doesn't work because I'm attaching with my local mac's geth into a container with raft. But how to specify that raft module is presented within such connection, then?

<img width="818" alt="Screen Shot 2019-06-17 at 22 47 28" src="https://user-images.githubusercontent.com/1569896/59632304-9aaebf00-9152-11e9-9929-1d731f913650.png">

**Comment by jbhurat** [comment]
Are you using a different `geth` binary when connecting from outside the container. Can you also paste the output of `geth help | grep -i "RAFT"`

**Comment by dmytronasyrov** [comment]
> Are you using a different `geth` binary when connecting from outside the container. Can you also paste the output of `geth help | grep -i "RAFT"`

Yes, I'm connecting using Geth installed from Homebrew on my local mac with no Raft module inside. But I'm wondering why during 'geth attach' it shows me that Raft module is available?

**Comment by jbhurat** [comment]
When you attach to a running `geth` process, it queries the modules loaded in that process and displays them during attach. As the `geth` binary is installed from Homebrew it does not have support for RAFT and hence the `raft is not defined` message. 

Whenever we do new [releases](https://github.com/jpmorganchase/quorum/releases) we distribute `geth` binaries. You can download `geth` binary from there to resolve this issue

**Comment by fixanoid** [comment]
To add, you can also use web3js / quorumjs wrapper to access this api through nodejs or you can simply hit them with curl.

**Comment by abhib3012** [comment]
Hello,

On the [releases](https://github.com/jpmorganchase/quorum/releases)  page, there are only AMD64 builds. How to get an ARM64 build?

Thanks.
