### ISSUE TITLE
Metamask transactions keep stack at the txpool of a Quorum Private Network

### ISSUE THREAD

**Issue by xaviermaltas** [Consensys-Incorporated/quorum#745]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.7.2-stable-0905eda4`

OS & Version: Ubuntu 16.04

Branch, Commit Hash or Release: `HEAD detached at v2.2.1`

#### Actual behaviour and Steps to reproduce the behaviour
My project repository -> https://github.com/xaviermaltas/quorumPrivateNetwork5Nodes

I'm using a 5 nodes example of a Quorum private network ( https://github.com/bacen/quorum-examples/tree/master/examples/5nodesRTGS ) with new keys. I have initialized the system using the instructions `./raft-init` and `./raft-start`. 

![Screenshot from 2019-06-19 12-26-27](https://user-images.githubusercontent.com/46923947/59758188-a652d080-928d-11e9-9c03-0f2b5a87dacb.png)

After that I use the command `geth attach ipc:"qdata/dd1/geth.ipc` to open the Geth console and check the values of the network. (If you test it, you will see that there are 4 peers at the net and the initial number of blocks it's 0. Command to see all the information -> `web3`). It's also required for unlocking a geth account -> `personal.unlockAccount(eth.accounts[0])`.

![Screenshot from 2019-06-19 12-29-11](https://user-images.githubusercontent.com/46923947/59758285-ddc17d00-928d-11e9-9276-826583c280da.png)

Then, I deploy a Truffle project with 2 contracts using `sudo truffle migrate --reset --compile-all --network quorumNet`. At the Geth console it's available to see that the number of blocks have changed from 0 to 4.

![Screenshot from 2019-06-19 12-31-30](https://user-images.githubusercontent.com/46923947/59758444-3b55c980-928e-11e9-8955-1a49afa5f5d7.png)

This Truffle Project contains a Votation Distrubuted Application with a Web App using Metamask plugin. (To bring up the web app use the command `npm start`. Introduce `ethereum.enable()` at the browser to connect Metamask with a private Network. 
![Screenshot from 2019-06-19 12-34-03](https://user-images.githubusercontent.com/46923947/59758734-e1a1cf00-928e-11e9-86a2-55de58792820.png)
Must add a new Custom RPC
![Screenshot from 2019-06-19 12-34-45](https://user-images.githubusercontent.com/46923947/59758742-e6668300-928e-11e9-9142-236566907ab2.png)
).
Using the web application and select a 'candidate' and press the 'Vote' button, the web app will interact with the contract and this will generate a transaction for being introduce to the blockchain.
![Screenshot from 2019-06-19 12-37-55](https://user-images.githubusercontent.com/46923947/59758840-1ca40280-928f-11e9-9c64-85ed98530833.png)

The transaction is generated correct as the Quorum-Truffle guidelines, but transactions keep stack at the `txpool` of the network (able to check using again `web3`).
![Screenshot from 2019-06-19 12-38-54](https://user-images.githubusercontent.com/46923947/59758897-38a7a400-928f-11e9-9ed2-d92e32de53ce.png)

#### Expected behaviour
The transaction must be mined by all the nodes at the network and must be introduced to the Blockchain as a new block. (Increasing the number of blocks)

**Comment by fixanoid** [comment]
@xaviermaltas I've tried the source repo on my quorum-examples project and it appears to work correctly. Is it possible that the nodes lost connectivity to each other?

**Comment by xaviermaltas** [comment]
Hi @fixanoid ,

Could you show me what have you done (if it is step by step, would be perfect) to make work correct the quorum-examples project with my source repository ? (Using the 7nodes example or 5nodesRTGS example?) 

I would be so grateful.

Thank you,
Kind Regards.

**Comment by zzy96** [comment]
@xaviermaltas Can you try Settings -> Advanced -> Reset Account and resend transactions? Sometimes MetaMask has an issue with account nonce out of sync.

**Comment by fixanoid** [comment]
@xaviermaltas please reopen if this is still an issue.

**Comment by xaviermaltas** [comment]
Thanks for the recommendation @zzy96, but I have tried and haven't get any result.

Hi @fixanoid, I still have the same issue.

**Comment by fixanoid** [comment]
@xaviermaltas as I said previously, the UI with MetaMask seemed to have worked the first time. If you'd like, we can follow up on the Slack. Thanks,
