### ISSUE TITLE
geth --preload does not load script.js

### ISSUE THREAD

**Issue by coeniebeyers** [Consensys-Incorporated/quorum#75]
#### System information

Geth version: `geth version`
Geth
Version: 1.5.0-unstable
Git Commit: 8c47c29f37bf8976f1f8c3f29ec677adaac5b640
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.3
OS: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: Windows/Linux/OSX
Ubuntu 16.03

Branch, Commit Hash or Release: `git status`
commit 8c47c29f37bf8976f1f8c3f29ec677adaac5b640

#### Expected behaviour
geth --preload "script.js" will load the script

#### Actual behaviour
geth --preload "script.js" doesn't load the script

#### Steps to reproduce the behaviour
geth --preload "script.js" does not load the script, however once geth has started, `>loadScript('script.js')` does load the script

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
@coeniebeyers sorry for the really late response on this.  This may be related to https://github.com/ethereum/go-ethereum/issues/2893.  Confirming that this is an issue that will be fixed.

**Comment by patrickmn** [comment]
This should be solved as of Quorum 2.0.0
