### ISSUE TITLE
Cannot see payload of private transaction on node7 version 2.2.4

### ISSUE THREAD

**Issue by obbaeiei** [Consensys-Incorporated/quorum#751]
Hi there,

#### System information

Geth version: `Geth/node7-raft/v1.8.18-stable-30d4d724(quorum-v2.2.4)/linux-amd64/go1.11.11`

OS & Version: OSX

Branch, Commit Hash or Release: `origin/master`

#### Expected behaviour
Setting up by docker as raft consensus
https://github.com/jpmorganchase/quorum-examples/blob/master/README.md
And follow this example
https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes

Execute into node 1 and see 
````
> private.get()
42
````

Execute into node 7 and see 
````
> private.get()
42
````

#### Actual behaviour
Execute into node 1 and see 
````
> private.get()
42
````

Execute into node 7 and see 
````
> private.get()
0
````

#### Steps to reproduce the behaviour
Follow these guide

Setting up by docker as
https://github.com/jpmorganchase/quorum-examples/blob/master/README.md
And follow this example to execute the contract
https://github.com/jpmorganchase/quorum-examples/tree/master/examples/7nodes

#### Backtrace

````
[backtrace]
````

**Comment by obbaeiei** [comment]
related to https://github.com/jpmorganchase/quorum/issues/291

**Comment by prd-fox** [comment]
Hey. I just tore down my docker setup and ran the steps, to keep it fresh. I wasn't able to reproduce this issue. Have you edited the scripts in any way, for your own testing?

**Comment by obbaeiei** [comment]
Hi.
I didn't edited anything. Sorry for not being clear enough about step to reproduce.

I'm following this steps

- git clone https://github.com/jpmorganchase/quorum-examples
- cd quorum-examples
- QUORUM_CONSENSUS=raft docker-compose up -d
- docker exec -it quorum-examples_node1_1 geth attach /qdata/dd/geth.ipc
- loadScript('/examples/private-contract.js')
- // waiting for address
- var address = "0x1932c48b2bf8102ba33b4a6b545c32236e342f34"; //replace with above address
- var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"type":"constructor"}];
- var private = eth.contract(abi).at(address)
- private.get()
> 42

Then. 
- docker exec -it quorum-examples_node7_1 geth attach /qdata/dd/geth.ipc
- var address = "0x1932c48b2bf8102ba33b4a6b545c32236e342f34"; //replace with above address
- var abi = [{"constant":true,"inputs":[],"name":"storedData","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"x","type":"uint256"}],"name":"set","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"retVal","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"initVal","type":"uint256"}],"type":"constructor"}];
- var private = eth.contract(abi).at(address)
- private.get()
> 0 // expected 42

I have checked privateFor in private-contract.js that is matching between private-contract.js and tm7.pub.

**Comment by prd-fox** [comment]
Thanks for the extra info.

Doing the above works for me, some there is some discrepancy somewhere!

A few things to try:
1. Resetting the entire thing, to show it is not just a one-time blip:
    - stop and remove all the docker containers
    - run all the steps again

1. Are the block numbers the same on each node? After connecting to node 1 and 7, run `eth.blockNumber` and verify they are the same. If so, run `eth.getBlock(eth.blockNumber).hash` and see if they are the same.

1. Run using IBFT. To see if this is a raft only issue, use IBFT and see if the same occurs
    - change `QUORUM_CONSENSUS=raft docker-compose up -d` to `docker-compose up -d`

**Comment by obbaeiei** [comment]
Thanks for response.

2. they are the same.
3. It happens only raft consensus.

**Comment by prd-fox** [comment]
Very strange. There should be no difference between IBFT and Raft, at least, no difference once a block has been minted. 

Did you try deleting the containers and relevant images and recreating the chain?
Also, which OS are you using?

**Comment by prd-fox** [comment]
Hi @obbaeiei,

I'm going to close this issue due to inactivity. If you have an update to my above questions, then please re-open the ticket.

Thanks!
