### ISSUE TITLE
raft.removePeer() does not work for dead nodes

### ISSUE THREAD

**Issue by MaxBinnewies** [Consensys-Incorporated/quorum#753]
Hello,

I am trying to set-up quorum for use in our application. I am using "quorum-maker" to set up three nodes on three VMs. Everything seems to work fine.

However, I am wondering what to do if a node ever becomes broken, so that it can't even be restarted. As we are looking to go into production soon, we really want to have a plan for this, so that a dead node doesn't kill the cluster forever. Eventually dead nodes will outnumber healthy ones and thus prevent consensus.

As such I am looking for a way to permanently remove a node from the network to replace it with a new one. Someone pointed me to "quorum-js", which can call raft.removePeer(raftId). But that only seems to work for nodes that are still alive.

Any help would be much appreciated. Thanks,
Max

#### System information

Geth version: Not sure, I am using the latest "quorum-maker"

OS & Version: Linux + OSX

#### Expected behaviour

raft.removePeer() removes a dead peer from the network.

#### Actual behaviour

It can only remove peers that are still alive. There currently does not seem to be a way to remove dead nodes from the cluster.

#### Steps to reproduce the behaviour

I ran the following experiment:

- I set up a local cluster of five quorum nodes with "quorum-maker"
- I run a couple of transactions to make sure everything works
- Then I call web3.quorum.raft.removePeer(5) for nodes 3, 4, 5
- Only after that, I stop the docker containers for nodes 3, 4, 5
- I try to run transactions again and it works (2/2 nodes are available)
- The logs indicate that these three nodes have been removed from the network, after that they are not mentioned anywhere in the gethLogs.

Now the problem:

- I remove the old cluster completely and start a new one, again with 5 nodes
- I again run a few transactions to ensure everything works.
- But this time, I stop the three docker containers first, like when the machines die for some reason and can't be recovered.
- Now I run raft.removePeers() for the three nodes (note: I have tried this a few times now, sometimes all three calls are successful, sometimes one or more of them gets stuck in execution, but neither works)
- Transactions do not work now, blocks can not be mined. (only 2/5 nodes are available)
- Geth keeps logging the following multiple times per second: 
INFO [06-27|04:18:19.203] peer is currently unreachable            peer id=3
INFO [06-27|04:18:19.206] peer is currently unreachable            peer id=4
INFO [06-27|04:18:19.207] peer is currently unreachable            peer id=5

I ran the whole thing twice, with the same result.

#### Backtrace

````
[backtrace]
````

**Comment by vsmk98** [comment]
Hi @MaxBinnewies - as per Raft, for any transaction to be committed the leader requires (n/2 + 1) confirmations from the peers in the network. Hence in a 5 node network for any transactions to be confirmed ( block creation, adding peer or removal of peer) will require at least 3 confirmation. A 5 node network can tolerate a failure of 2 nodes. 
In your scenario, if you stop the docker containers for  say node 4 and 5 and then do `removePeer` for these nodes, it should work fine. After this you can stop the container for node 3 and the network should still be working fine.
However when you stop 3 nodes without the changing raft cluster, the majority of the nodes are down and the leader node will not be able to commit any transactions (including removePeer) as its not receiving majority confirmations.

**Comment by MaxBinnewies** [comment]
Oh yeah,
that actually works. :-) Thanks, mate! I have been stuck on removing a peer for a few days now^^

Is it possible to return the status of what happened? Right now I am just getting a null response, no matter if the removal was successful or not.
So maybe a boolean flag indicating whether it was removed and a message field. I think a message telling people that the node can't be removed because we don't have quorum would go a long way here.
Or is that too difficult because it's async?

Thanks,
Max

**Comment by MaxBinnewies** [comment]
Actually I have another problem with removePeer().
I had some issue with a new node, so I went through the remove-resync-cycle a few times until I got raftId 10 & 11. These seem to be stored as hex, as indicated in the gethLogs:

2019-06-30 23:33:30.340051 W | rafthttp: health check for peer a could not connect: dial tcp 172.16.12.6:22003: connect: no route to host
2019-06-30 23:33:30.354121 W | rafthttp: health check for peer b could not connect: dial tcp 172.16.12.8:22003: connect: connection refused

removePeer(10) does not seem to remove it, and removePeer(a), removePeer('a'), removePeer("a") are not accepted. The call itself just returns null, like all other calls to removePeer

Interestingly, when I do raft.cluster() it shows the ID as decimal. However, that function also confirms that 10 & 11 are still around after removePeer(10). To me it seems likely that this is related to the hex-output of the raftId in the logs.

**Comment by vsmk98** [comment]
@MaxBinnewies can you please share the raft.cluster output in the current state and also share the number of nodes which are active at that point? removePeer takes raft id as (decimal) as input. so raft.removePeer(10) should work fine as long as majority nodes are there

**Comment by MaxBinnewies** [comment]
oh... I removed the whole cluster as it was broken.

**Comment by abhayar** [comment]
@MaxBinnewies  raft.removePeer(5) , here 5 is raftid you wish to remove from cluster.  You will always get null response from  raft.removePeer() after removal of node .
