### ISSUE TITLE
Issue when geth is pushed with large number of transactions

### ISSUE THREAD

**Issue by subhasisbanik** [Consensys-Incorporated/quorum#754]
I am running a web3j layer to push public transactions sequentially to a 10 peer quorum network continously with 8 core 15GB RAM and 100GB SSDper node.
Now after approx 50k txns per node, I observe that the geth stops responding with contract addresses(i.e. transaction confirmation) though there are no errors in log.
I have to stop and start geth to make it up and running.
Now with that maintenance, after a total of 2.6million txns, I observed that the hdd is filled completely and hence geth stops.
Can anyone help with this behavior of geth and any possible resolutions around it?

**Comment by SatpalSandhu61** [comment]
Can you give more information on the environment:
- Geth version: `geth version`
- OS & Version: Windows/Linux/OSX
- Branch, Commit Hash or Release: `git status`
- Consensus mechanism being used
- Genesis block

Also:
- Can you check exactly where the HDD space is being used & let us know.
- What is the size of the transactions?
- What logging level are you using (if you have verbose logging then the logs may use rather a lot)?
- Can you clarify what you mean by 'pushing txns continuously'... how fast are they being submitted? 
- When you restarted geth, did you restart all nodes and did you take any other action?

**Comment by subhasisbanik** [comment]
Details:
Geth version: **2.2.4**
OS & Version: **Ubuntu 16.04**
Branch, Commit Hash or Release: **origin/master**
Consensus mechanism being used: **Raft**
Genesis block : **Could you please clarify?**
Also:

Can you check exactly where the HDD space is being used & let us know: **Out of 100GB I have seen a folder in datadir called, raft-wal to use 60GB**
What is the size of the transactions? How to I find that? **I am mining a smart contract which needs 6000000 gas.**
What logging level are you using (if you have verbose logging then the logs may use rather a lot)? **No have set verbosity to 1**
Can you clarify what you mean by 'pushing txns continuously'... how fast are they being submitted? **They are being transferred 3 txns per sec.**
When you restarted geth, did you restart all nodes and did you take any other action? **Yes restarted all the nodes and no I did not take any  other action than restarting geth**

Answers to your questions are in bold @SatpalSandhu61

**Comment by subhasisbanik** [comment]
Update:

Considerations:
1. Geth is started with the command below:

```
#!/bin/bash
set -u
set -e
echo "[*] Starting Ethereum node"

export ARGS="--nodiscover --verbosity 5 --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints"

export PRIVATE_CONFIG="/data/node/datadir/tm.ipc"

nohup geth --datadir /data/node/datadir $ARGS --raftport 50401 --rpcport 22000 --port 21000 --identity 'QUORUM01' --unlock 0 --password passwords.txt > /data/node/datadir/logs/node.log 2>&1&

echo "node configured. See 'datadir/logs' for log
```s."

2. Have used static-nodes.json with all the nodes in there

There are 2 issues currently being faced in the network:
1. One of the nodes has faced an out of memory though there is 30GB ram in the machine
2. All the nodes in their healthy state is not able to maintain the peer, i,e. loosing peers randomly
3. None of the nodes are able to mine transactions after point 1
4. Stop starting node mentioned in point 1, gives 
"Pooled new future transaction            hash=a26a80…4f58af from=0x511Fc8de7B2670453809926d303Af5C3b7D6f90c to=nil"
5. Stop starting all nodes, results in all nodes not mining, some nodes not letting RPC into it.


Please help!!!

**Comment by SatpalSandhu61** [comment]
Is this the same system in the start of this ticket? Did the issue happen after the HDD filled up?
If it's a different system or a different issue then you should raise a separate ticket. (I notice it has verbosity set to 5 whereas you said you were using a value of 1).

**Comment by subhasisbanik** [comment]
Actually we have set up multiple machines with different CPU config and hdd sizes. 
We have now set --gcmode=archive and found that HDD is not getting filled up but the above issue comes up.

**Comment by SatpalSandhu61** [comment]
Ok, the other issue is now addressed in ticket 768, so I'll close this ticket.
