### ISSUE TITLE
Quorum doesn't pick nodes from `static-nodes.json`

### ISSUE THREAD

**Issue by ali92hm** [Consensys-Incorporated/quorum#76]
#### System information

Geth version: `geth version`
`Version: 1.5.0-unstable`

OS & Version: Windows/Linux/OSX
`Linux: Ubuntu 16.04.2 LTS`

Branch, Commit Hash or Release: `git status`
`master`
Git Commit: 6d0bd810484f4c56f7c9aebc229e1bdc56832ced

#### Expected behaviour
When `<datadir>-static-nodes.json` is present, geth should try to connect to those nodes.

#### Actual behaviour
Geth 1.5 does not try to connect to `<datadir>-static-nodes.json`as result of a bug. Here is [issue on Go-Ethereum](https://github.com/ethereum/go-ethereum/issues/3329) which is fixed in the later versions.

Rebasing with Go-Ethereum should fix this problem, but I'm not expecting this rebase to happen anytime soon. I just thought of opening this issue so people wont waste their time.

**Comment by tylobban** [comment]
Thanks! Yes we will be upgrading geth so will circle back here once that's done.

**Comment by patrickmn** [comment]
This should be solved as of Quorum 2.0.0

**Comment by ali92hm** [comment]
Thank you @patrickmn
