### ISSUE TITLE
Head state missing, repairing chain

### ISSUE THREAD

**Issue by xuzhitong** [Consensys-Incorporated/quorum#764]
version:v1.8.18-stable-5a80e7a1(quorum-v2.2.3)/linux-amd64
operator system:centos 7.8
I created a private chain using quorum with raft on two nodes.I started the chain using the command:
node1:
geth --datadir "./" --nodiscover --networkid 333 --ipcdisable --port 20000 --rpc --rpcport 50000 --raft --raftport 40000 console
node2:
geth --datadir "./" --nodiscover --networkid 333 --ipcdisable --port 20001 --rpc --rpcport 50001 --raft --raftport 40001 console
The chain works fine at first and I deployed some contracts on it.When I reopen the terminal and restart the two node's chain,I found the blockNumber in both of the two nodes has been changed from 22 to 0,and I saw the WARN info printing on the console:
WARN [07-02|14:41:32.480] Ethash used in full fake mode 
INFO [07-02|14:41:32.480] Initialising Ethereum protocol           versions="[63 62]" network=333
WARN [07-02|14:41:32.486] Head state missing, repairing chain      number=39 hash=c841cf…075b0f
INFO [07-02|14:41:32.490] Rewound blockchain to past state         number=0  hash=c23b4e…8b1b71
I found a similar issue on the Ethereum github:
 https://github.com/ethereum/go-ethereum/issues/19124
Have the issue been fixed or it would be another issuse?

**Comment by vsmk98** [comment]
In the geth start command, please add "--gcmode archive". This will ensure that any block data is immediately written to disk and the above issue will not happen.

**Comment by jayboy-mabushi** [comment]
@xuzhitong hi did you fix this issue? I am getting the same thing
