### ISSUE TITLE
Out of Memory Issue in Quorum

### ISSUE THREAD

**Issue by dwaipayabasu** [Consensys-Incorporated/quorum#768]
Hello Team, I am getting an Out of Memory exception while running a Quorum network in AWS. Please note that this is a private network and outside attack is not possible. 

Details are given below - 
Geth Version: 1.8.18-stable
Git Commit: d10680f97f3942ada5954f96b4468719c68a330b
Quorum Version: 2.2.4
Consensus: RAFT
RAM: 30 gb
SWAP: none
vCPU: 16 
Running Public txn only 

Parameters: 
export ARGS="--nodiscover --verbosity 5 --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints"

export PRIVATE_CONFIG="/data/node/datadir/tm.ipc"

nohup geth --datadir /data/node/datadir $ARGS --raftport 50401 --rpcport 22000 --port 21000 --identity 'QUORUM01' --unlock 0 --password passwords.txt > /data/node/datadir/logs/node.log 2>&1&

Total Number of nodes: 10
Total number of successful Txn: ~800,000, after that it started failing with out of memory and the network never get recovered.

**Comment by fixanoid** [comment]
Hi @dwaipayabasu could you please upload the log of the node failing?

**Comment by fixanoid** [comment]
Please reopen if you encounter this issue.
