### ISSUE TITLE
Issue with Private Contract Deloyment

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#77]
#### System information

Geth version: `geth version`
1.5.0-unstable-85327f74

OS & Version: Windows/Linux/OSX
Ubuntu 16.04.1 LTS

Branch, Commit Hash or Release: `git status`
Master
#### Expected behavior
Private Contract Deployment should succeed.

#### Actual behavior
Behavior is inconsistent, it succeeds after 4-5 attempts. When it fails I see error in constellation log file as unknown recipient. Log it attached here with.

#### Steps to reproduce the behavior
I have 6 Nodes each node having two accounts and are configured as Voter & Block maker.
I am trying to deploy contract from node 6 as private to Node 1,2,3,4,5

Constellation log with the error information is attached here with for your reference.
[constellation6.txt](https://github.com/jpmorganchase/quorum/files/850864/constellation6.txt)

Please advise.

**Comment by patrickmn** [comment]
Please see https://github.com/jpmorganchase/quorum/issues/64

**Comment by paliwalg** [comment]
Now putting more sleep internal while starting 1st constellation node and later, I got the contract deployed as private.
Now I am trying to perform a private transaction from the private contract. I do receive transactionHash as a result, but I don't see transaction to be added in the block. Contract address remains null.
I don't see any error in any of the logs.
I have attached the contract code and configuration files for your reference

[SimpleCustomer.txt](https://github.com/jpmorganchase/quorum/files/852298/SimpleCustomer.txt)
[SimpleCustomerFactory.txt](https://github.com/jpmorganchase/quorum/files/852299/SimpleCustomerFactory.txt)

[init.txt](https://github.com/jpmorganchase/quorum/files/852302/init.txt)
[start.txt](https://github.com/jpmorganchase/quorum/files/852303/start.txt)

Thanks

**Comment by patrickmn** [comment]
Noting the new issue you created: https://github.com/jpmorganchase/quorum/issues/78
