### ISSUE TITLE
Geth loosing peers and not mining contracts

### ISSUE THREAD

**Issue by subhasisbanik** [Consensys-Incorporated/quorum#778]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`: 1.8.18-stable

OS & Version: Windows/Linux/OSX -Ubuntu 16.04

Branch, Commit Hash or Release: `git status` - head

#### Expected behaviour
Quorum Geth mining transactions

#### Actual behaviour
Quorum Geth loosing peers and adding posted transactions to pending transactions

#### Steps to reproduce the behaviour
Set up 10 Quorum nodes with Tessera 0.9 and prepare web3j quorum layer to post public contract mining transactions synchronously in a loop.
Now after running every 1 crore of transactions, geth looses peers and needs to be restarted with the check that all the nodes are at the same block height. 
But now after around 6 crore transactions, geth has lost peers, every node is at different block height and checking logs, I found out that it is complaining of "dial error". Also I see that there are huge number of pending transactions.

Please help!!

**Comment by fixanoid** [comment]
@subhasisbanik could you post the logs of the nodes and privacy manager? Thanks

**Comment by subhasisbanik** [comment]
node.log for 1 node:

TRACE[07-17|06:46:42.249] Dial task done                           task="staticdial 7a6b492998776d67 18.221.122.73:0"
TRACE[07-17|06:46:42.249] New dial task                            task="staticdial 7c82eef801efd83c 3.14.128.157:0"
TRACE[07-17|06:46:42.249] New dial task                            task="staticdial afe4f0aff53208b4 3.15.3.50:0"
TRACE[07-17|06:46:42.249] New dial task                            task="staticdial f9f5d0b7a2d931ce 18.191.174.252:0"
TRACE[07-17|06:46:42.249] New dial task                            task="staticdial 4f43dd6d7dab3782 3.17.77.231:0"
TRACE[07-17|06:46:42.249] New dial task                            task="staticdial 1da658db05ee982e 18.219.207.106:0"
TRACE[07-17|06:46:42.249] New dial task                            task="staticdial f06a880f6fbcddc4 18.222.121.204:0"
TRACE[07-17|06:46:42.249] New dial task                            task="staticdial bbd04d4004728871 18.221.24.59:0"
TRACE[07-17|06:46:42.249] Dial error                               task="staticdial bbd04d4004728871 18.221.24.59:0"       err="dial tcp 18.221.24.59:0: connect: connection refused"
DEBUG[07-17|06:46:42.249] Can't resolve node                       id=0x8bff30         err="discovery is disabled"
TRACE[07-17|06:46:42.249] Dial task done                           task="staticdial bbd04d4004728871 18.221.24.59:0"
TRACE[07-17|06:46:42.249] Dial error                               task="staticdial 4f43dd6d7dab3782 3.17.77.231:0"        err="dial tcp 3.17.77.231:0: connect: connection refused"
DEBUG[07-17|06:46:42.250] Can't resolve node                       id=0x8bff30         err="discovery is disabled"
TRACE[07-17|06:46:42.250] Dial task done                           task="staticdial 4f43dd6d7dab3782 3.17.77.231:0"
TRACE[07-17|06:46:42.249] Dial error                               task="staticdial f06a880f6fbcddc4 18.222.121.204:0"     err="dial tcp 18.222.121.204:0: connect: connection refused"
DEBUG[07-17|06:46:42.250] Can't resolve node                       id=0x8bff30         err="discovery is disabled"
TRACE[07-17|06:46:42.250] Dial task done                           task="staticdial f06a880f6fbcddc4 18.222.121.204:0"
TRACE[07-17|06:46:42.249] Dial error                               task="staticdial f9f5d0b7a2d931ce 18.191.174.252:0"     err="dial tcp 18.191.174.252:0: connect: connection refused"
DEBUG[07-17|06:46:42.250] Can't resolve node                       id=0x8bff30         err="discovery is disabled"
TRACE[07-17|06:46:42.250] Dial task done                           task="staticdial f9f5d0b7a2d931ce 18.191.174.252:0"
TRACE[07-17|06:46:42.249] Dial error                               task="staticdial 1da658db05ee982e 18.219.207.106:0"     err="dial tcp 18.219.207.106:0: connect: connection refused"
DEBUG[07-17|06:46:42.250] Can't resolve node                       id=0x8bff30         err="discovery is disabled"
TRACE[07-17|06:46:42.250] Dial task done                           task="staticdial 1da658db05ee982e 18.219.207.106:0"
TRACE[07-17|06:46:42.249] Dial error                               task="staticdial afe4f0aff53208b4 3.15.3.50:0"          err="dial tcp 3.15.3.50:0: connect: connection refused"
DEBUG[07-17|06:46:42.250] Can't resolve node                       id=0x8bff30         err="discovery is disabled"
TRACE[07-17|06:46:42.250] Dial task done                           task="staticdial afe4f0aff53208b4 3.15.3.50:0"
TRACE[07-17|06:46:42.249] Dial error                               task="staticdial 7c82eef801efd83c 3.14.128.157:0"       err="dial tcp 3.14.128.157:0: connect: connection refused"
DEBUG[07-17|06:46:42.250] Can't resolve node                       id=0x8bff30         err="discovery is disabled"
TRACE[07-17|06:46:42.250] Dial task done                           task="staticdial 7c82eef801efd83c 3.14.128.157:0"
TRACE[07-17|06:46:42.250] New dial task                            task="wait for dial hist expire (29.998338875s)"
INFO [07-17|06:46:42.641] synchronizing with peer                  peer id=8                                                                hash=b5ed2e…1be92a
WARN [07-17|06:46:42.641] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:42.641] failed to synchronize with peer          peer id=7a6b492998776d6707fc05e7612314186a5c47217ca44c72e5b2c6ef99a0dbb8
INFO [07-17|06:46:43.157] synchronizing with peer                  peer id=9                                                                hash=b5ed2e…1be92a
WARN [07-17|06:46:43.157] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:43.157] failed to synchronize with peer          peer id=f9f5d0b7a2d931ced80edd567c1843a4881536360755aaf5a2836d5fdee96c25
raft2019/07/17 06:46:43 INFO: 1 [term: 228607] received a MsgVote message with higher term from a [term: 228608]
raft2019/07/17 06:46:43 INFO: 1 became follower at term 228608
raft2019/07/17 06:46:43 INFO: 1 [logterm: 144583, index: 3737249, vote: 0] cast MsgVote for a [logterm: 148626, index: 4071905] at term 228608
INFO [07-17|06:46:43.657] synchronizing with peer                  peer id=2                                                                hash=b5ed2e…1be92a
WARN [07-17|06:46:43.657] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:43.657] failed to synchronize with peer          peer id=bbd04d4004728871625232d16c70389e021cb37e3e0faa56b9b0afe3e89b69d1
INFO [07-17|06:46:44.158] synchronizing with peer                  peer id=10                                                               hash=b5ed2e…1be92a
WARN [07-17|06:46:44.158] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:44.158] failed to synchronize with peer          peer id=4f43dd6d7dab37822fcb2f71c47f4c5accf32b31112e6eaa79180e2ca2947c64
raft2019/07/17 06:46:44 INFO: 1 [term: 228608] received a MsgVote message with higher term from 6 [term: 228609]
raft2019/07/17 06:46:44 INFO: 1 became follower at term 228609
raft2019/07/17 06:46:44 INFO: 1 [logterm: 144583, index: 3737249, vote: 0] cast MsgVote for 6 [logterm: 148626, index: 4071905] at term 228609
INFO [07-17|06:46:44.658] synchronizing with peer                  peer id=7                                                                hash=b5ed2e…1be92a
WARN [07-17|06:46:44.658] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:44.658] failed to synchronize with peer          peer id=afe4f0aff53208b45645c237a7e359b85405196dc2a9514188967afd3ca3d588
INFO [07-17|06:46:45.158] synchronizing with peer                  peer id=5                                                                hash=b5ed2e…1be92a
WARN [07-17|06:46:45.159] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:45.159] failed to synchronize with peer          peer id=daa5b2a8bdbf15005126e2e63835ebf13bb6ffa9b576c840ea00b41ad200fe28
raft2019/07/17 06:46:45 INFO: 1 [term: 228609] received a MsgVote message with higher term from 7 [term: 228610]
raft2019/07/17 06:46:45 INFO: 1 became follower at term 228610
raft2019/07/17 06:46:45 INFO: 1 [logterm: 144583, index: 3737249, vote: 0] cast MsgVote for 7 [logterm: 148626, index: 4071905] at term 228610
INFO [07-17|06:46:45.659] synchronizing with peer                  peer id=6                                                                hash=b5ed2e…1be92a
WARN [07-17|06:46:45.659] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:45.659] failed to synchronize with peer          peer id=7c82eef801efd83cf2463c37e79c95ceeae0f3499f0784bfddc891076a256b3f
INFO [07-17|06:46:46.159] synchronizing with peer                  peer id=3                                                                hash=b5ed2e…1be92a
WARN [07-17|06:46:46.159] Synchronisation failed, retrying         err="peer is unknown or unhealthy"
INFO [07-17|06:46:46.159] failed to synchronize with peer          peer id=1da658db05ee982efdb25adfc9cbeb64263ff84efc1f383a655f100463f1a0e3
raft2019/07/17 06:46:46 INFO: 1 [term: 228610] received a MsgVote message with higher term from 7 [term: 228611]

**Comment by subhasisbanik** [comment]
Also 1 correction, we had not used tessera as we did not have the requirement for private txns.

**Comment by fixanoid** [comment]
@subhasisbanik the log shows that you have a connectivity issue between the nodes. The node is unable to connect to any of its peers. If the number of nodes are unable to interconnect, then a consensus is not possible, thus txns would not propagate.

How are the nodes configured and whats the network between them?

**Comment by subhasisbanik** [comment]
These are AWS machines and I have specifically opened all inbound ports so that there isn't any connectivity issue. Also I did telnet to those machines which this log states issue with and was successful.
Also I have noticed this trend with geth loosing peers in 2 days or so. I used to restart geth with checking same block height but now the situation is different where the block height is different.

**Comment by fixanoid** [comment]
https://github.com/jpmorganchase/quorum/pull/775 might be related here. Could you build Quorum node from that pull and replace the binaries to see if it helps?

**Comment by subhasisbanik** [comment]
Is the fixed version pushed to the main branch?

**Comment by fixanoid** [comment]
Yes, it was merged today.

**Comment by fixanoid** [comment]
@subhasisbanik were you able to build the new client and test it with the issue you are having?

**Comment by fixanoid** [comment]
@subhasisbanik please reopen if this is still an issue.
