### ISSUE TITLE
Block sealing failed  and Failed to decode message from payload 

### ISSUE THREAD

**Issue by AUQIB92** [Consensys-Incorporated/quorum#779]
please help
I m getting this error
Block sealing failed err=unauthorized
ERROR[07-17|22:08:43] Failed to decode message from payload address=0x80A13E1aa941569081c696525e38B6a65d1c8603 err="unauthorized address"

My environment

Geth
Version: 1.8.3-unstable
Git Commit: c7547381b2ea8999e423970d619835c662176790
Architecture: amd64
Network Id: 1
Go Version: go1.10.4
Operating System: linux ubuntu 16.04
GOPATH=
GOROOT=/usr/lib/go-1.10

**Comment by fixanoid** [comment]
@AUQIB92 likely, your IBFT configuration isn't entirely correct. This error may show up when the initial validators in the genesis block is different from the one present on the network. We have an in depth guide to assist you here: https://docs.goquorum.com/en/latest/Getting%20Started/Getting-Started-From-Scratch/#quorum-with-istanbul-bft-consensus.
