### ISSUE TITLE
How to debug quorum codes  with IDE

### ISSUE THREAD

**Issue by jiebanghan** [Consensys-Incorporated/quorum#780]
I created the quorum nodes environment in Linux and run the 7nodes examples smoothly, I just want to be clear how the codes run when geth is running. by the way I have compiled geth with go build -gcflag='all -N -l.
So I decideed use the goland remote debug function to solved the problem. when I run the raft-start.sh to run all the nodes and then I run
In terminal 1 run 
`geth attach ipc:qdata/dd1/geth.ipc`
 to attach to node 1
then I use 
`dlv attach $PID --headless=true --api-version=2  --accept-multiclient --log --listen=:2345`
 to attach the pid of the geth1 or the  geth which is attaching.
then I run the remote debug of goland to listen the server's 2345 port. but the program can't stop when I set some breakpoints.
how to solve stop the breakpoint or how to remote debug the geth codes? thank you very much.

**Comment by jbhurat** [comment]
Hi @jialinpeng, we take a different approach when debugging `geth` code. The steps we follow are
- In `raft-start.sh` comment the `geth` startup for node 1, which is `PRIVATE_CONFIG=qdata/c1/tm.ipc nohup geth --datadir qdata/dd1 $ARGS --permissioned --raftport 50401 --rpcport 22000 --port 21000 --unlock 0 --password passwords.txt 2>>qdata/logs/1.log &`
- Start the network
- In your ide, add a new Debug configuration using the below options
  - Name: `<Meaningful name for the debug config>`
  - Package path: `<path to geth>`
  - Environment: `PRIVATE_CONFIG=<full path of qdata/c1/tm.ipc>`
  - Program arguments: `<geth arguments that were commented in step1 above>`
  - Save the debug configuration
  - Add breakpoints and debug `geth`

**Comment by jbhurat** [comment]
The above steps were verified in Intellij with go plugin installed. I believe they should work for goland as well.

**Comment by jiebanghan** [comment]
thank you very much .

**Comment by jiebanghan** [comment]
hi , @jbhurat you mean you use the 7nodes example and just In raft-start.sh comment the geth startup for node 1, which is PRIVATE_CONFIG=qdata/c1/tm.ipc nohup geth --datadir qdata/dd1 $ARGS --permissioned --raftport 50401 --rpcport 22000 --port 21000 --unlock 0 --password passwords.txt 2>>qdata/logs/1.log & ?
and beyond that is there  nothing modified in 7nodes example?  thank you .

**Comment by jbhurat** [comment]
yes, that's correct

**Comment by jiebanghan** [comment]
thank you very much.

**Comment by jiebanghan** [comment]
It does works.

**Comment by jbhurat** [comment]
Thanks for confirming

**Comment by jiebanghan** [comment]
hi , @jbhurat thank you very much for the suggestion. However, I have  anther sutition here. The machine the geth located is a remote machine and not my pc, althouth I  can run such as intellij or goland in remote host , it is very slow actually.So I use goland remote debug  which can connected the remote geth at  my local pc, but it usually run slowly and usually static. So would you please give me some suggestions  for the remote geth which  is  at the remote machine?

**Comment by jiebanghan** [comment]
thank you very much .

**Comment by jbhurat** [comment]
Hi @jiebanghan, I believe the issue is more to do with remote debugging golang code in general. There have been some improvements on this front in golang v1.11.x and golang v1.12.x, more details can be found here https://blog.golang.org/debugging-what-you-deploy.

Please note that Quorum does not support golang v1.12.x yet

**Comment by jiebanghan** [comment]
thank you @jbhurat  very much.
