### ISSUE TITLE
Raft - upgrade to v3.3.13 and addition of learner node feature 

### ISSUE THREAD

**Issue by amalrajmani** [Consensys-Incorporated/quorum#790]
currently quorum is using an old version of raft library(v3.1.0).
We should upgrade quorum's Raft library to latest v3.3.13 ( https://github.com/etcd-io/etcd/releases/tag/v3.3.13 ) as there are numerous improvements and some new features(like learner node) in raft library. 
We should also enhance quorum to support adding learner node and promoting learner node to peer node.

**Comment by shun-tak** [comment]
Excellent update! I think this can also resolve #180

**Comment by fixanoid** [comment]
❤️
