### ISSUE TITLE
Raft cluster null after starting a single node cluster

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#795]
#### System information

Geth version: 
Version: 1.8.18-stable
Quorum Version: 2.2.4
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.3
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

OS & Version: 
Alpine 1.9.3

Branch, Commit Hash or Release:
Release 2.2.4 / 2.2.3

#### Expected behaviour
Raft cluster should not be [null]

#### Actual behaviour
Raft cluster is [null]

#### Steps to reproduce the behaviour
1. Start a single quorum node (permission-nodes and static-nodes should have a single entry)
2. Stop the quorum node
3. Start the quorum node again
4. raft.cluster of the node is [null]

Note : The setup is dockerized and node is stopped by stopping the docker container and started by starting the docker container

**Comment by trung** [comment]
@preetgsanand In order for Raft cluster to be up, it needs a leader. A leader is elected based on a quorum (majority). And we would need at least 3 nodes to form a quorum. 

So if you try to start a Raft network with 1 or 2 nodes, the cluster will be unavailable until a third node is added.

**Comment by trung** [comment]
In the same setup, there seems a bug in which the node is no longer a leader after a restart. Hence transactions are not minted.

**Comment by trung** [comment]
Fix of https://github.com/jpmorganchase/quorum/issues/642 causing this issue
