### ISSUE TITLE
Transaction goes to pending state. when "isQuorum" is set to false.

### ISSUE THREAD

**Issue by geethagurram21** [Consensys-Incorporated/quorum#802]
**Genesis File:**

{
	"alloc": {
		"0xWallet-Id-Here": {
		  "balance": "300000000000000000000000000000000000000"
		}
	},

	"config": {
		"homesteadBlock": 0,
		"byzantiumBlock": 123456,
		"constantinopleBlock":0,
		"chainId": 10,
		"eip150Block": 0,
		"eip155Block": 0,
		"eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
		"eip158Block": 0,
		"isQuorum": false
	},
	"coinbase": "0x0000000000000000000000000000000000000000",
	"difficulty": "0x0",
	"extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
	"gasLimit": "0xE0000000000",
	"mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
	"nonce": "0x0",
	"parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
	"timestamp": "0x00"
}

**Transactions Done:**

eth.sendTransaction({from:eth.coinbase, to: eth.accounts[1], value: 1, gas:21000})

Transactions go to pending state after **21 Transactions**

Can anyone please tell me what is the mistake.

**Comment by SatpalSandhu61** [comment]
I can reproduce this issue with Raft. Will investigate further.
For the moment, if possible please use `isQuorum: true` as a work-around.
Alternatively, use one of the other consensus mechanisms - it appears to work fine with Istanbul.

**Comment by geethagurram21** [comment]
with isQuorum: true , the nodes are working perfectly fine. But i want to know what is the problem with isQuorum: false in raft consensus.

**Comment by jpmsam** [comment]
Raft will only work in Quorum mode due to some checks that we have to disable, please refer to PR #811 for more details.
