### ISSUE TITLE
Account Lock issue

### ISSUE THREAD

**Issue by nurASingh** [Consensys-Incorporated/quorum#805]
Hi there,

We are facing an account lock issue on quorum nodes.
Please find the details below 

#### System information

Quorum version: 2.2.2

OS & Version: Ubuntu

Tessera : 0.0.8

#### Expected behavior
When I unlock the quorum coinbase account with  personal.unlockAccount(#coinbase,"password",0) using web3js
This supposes to be unlocked for an infinite time. 

But when we send a transaction using web3j from java services it throws an error that transaction can not be mined. Once we investigate we can see that account is locked, after unlocking the account manually again it works fine.

This happens on a regular basis once we reached 100000 blocks on chain.

#### Actual behaviour
It gets locked after some times. We started facing this issue recently which was working fine for a couple of months. We have crossed more than 100000 blocks in our chain. Can this be an issue?

#### Steps to reproduce the behavior
1. Unlock account once using web3j for infinite time ( account, passwprd , 0)
2. Perform the transactions, works fine till a couple of days
3. The transaction can not be mined error from service
4. Check account from geth console and unlock again
5. Perform the transaction again, works fine.

**Comment by prd-fox** [comment]
I will try to reproduce this issue on my end. I doubt it has anything to do with the number of blocks, although I will still try both under and over the 100k mark.

Is there any chance that the Quorum process was restarted? This would re-lock the accounts.

**Comment by nurASingh** [comment]
No, Quorum nodes are running for months.

**Comment by prd-fox** [comment]
Ok.

Can you paste the exact error message you receive? Does this happen on multiple nodes or only on a single node?
Lastly, for now, are you able to reproduce this in a completely separate environment? i.e. new nodes, new machines, different accounts, different blockchain? Additionally, if you are able to, are you able to test with version 2.2.5 (latest release) to see if the issue still persists?

**Comment by zhjzcbm** [comment]
检查一下是否是因为异步问题，可能是先执行了交易再执行解锁。

Check to see if this is due to asynchrony, perhaps the transaction was executed before the unlock was performed

**Comment by prd-fox** [comment]
I haven't been able to reproduce this issue using the steps provided, and haven't heard back on the extra information requested.

Another idea may be that `personal.lockAccount` was accidentally called.

I will close this for now. If you are able to get back with the requested information, then please feel free to reopen or submit a new issue.
