### ISSUE TITLE
raft minter exchanging cause underpriced transaction get stuck

### ISSUE THREAD

**Issue by xuzhitong** [Consensys-Incorporated/quorum#812]
Geth version: Geth
Version: 1.8.18-stable
Git Commit: 5a80e7a1badd2e99f05baf18d2c8e00fed488746
Quorum Version: 2.2.3
Architecture: amd64

OS & Version: ubuntu16.04

I created a private chain using raft  over three nodes and deployed a simple contract on it.Then I  wrote the web3 server and client application.The client will receive message from another server and call the contract method continuously.When the chain run some hours ,I found the chain get stuck and the web3 client return "replacement transaction underpriced" error for every transaction.When I checked the chain state from the node which the web3 client connected to ,I found the raft minter has changed to another node and there is pending transaction in the old minter node.
```
> 
> txpool
{
  content: {
    pending: {
      0x47ba8aAB8fd55DC8B31abD0b90F79208FB3c21A6: {
        508: {...}
      },
      0xb0ED69b0e402C31F3f6Aa82D503759608569A014: {
        720: {...}
      }
    },
    queued: {}
  },
  inspect: {
    pending: {
      0x47ba8aAB8fd55DC8B31abD0b90F79208FB3c21A6: {
        508: "0x89fAF6205B0eD909b742c2fb3ABeA7D46fF1fbE3: 0 wei + 6000000 gas × 0 wei"
      },
      0xb0ED69b0e402C31F3f6Aa82D503759608569A014: {
        720: "0x89fAF6205B0eD909b742c2fb3ABeA7D46fF1fbE3: 0 wei + 6000000 gas × 0 wei"
      }
    },
    queued: {}
  },
  status: {
    pending: 2,
    queued: 0
  },
  getContent: function(callback),
  getInspect: function(callback),
  getStatus: function(callback)
}

> eth.pendingTransactions
[{
    blockHash: null,
    blockNumber: null,
    from: "0x47ba8aab8fd55dc8b31abd0b90f79208fb3c21a6",
    gas: 6000000,
    gasPrice: 0,
    hash: "0xdca85234482a39f7300a5caebddb598099cd23994f21d283e257c1a73c28cf99",
    input: "0xbbea1cd500000000000000000000000000000000000000000000000000000000000000a0fa79371b343df21a30fd010ef99d8dd40000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e046f4fa4c55151c2c6a4badd0cd54493d000000000000000000000000000000000000000000000000000000000000000000000000000000000000016cf6049a45000000000000000000000000000000000000000000000000000000000000000531303030300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000011313536353233343732333830342e706e67000000000000000000000000000000",
    nonce: 508,
    r: "0xe7e13a6df9d1368e895ab9cf80aa796d5bee9859c78bd6dbb643093340fd11ac",
    s: "0x3309374bc1261ebf7dc8d7040fa52afeb2146b80f843f9b7ebe82b227a755749",
    to: "0x89faf6205b0ed909b742c2fb3abea7d46ff1fbe3",
    transactionIndex: 0,
    v: "0x1c",
    value: 0
}]
> raft
{
  cluster: [{
      ip: "10.100.9.83",
      nodeId: "54ed93475cafc97fb6ba6f30943812222007d7135dac5efb565a45b1c73a74f02f1a940cf61caaecc93938cf09c3728b67350300313412687babed3c0e4b93ec",
      p2pPort: 20001,
      raftId: 1,
      raftPort: 40001
  }, {
      ip: "10.100.9.68",
      nodeId: "325d8bb603bfffd10c8be13a75e5a691fcc634242a8c5909da31b65de82107dd00d68c1275cbc99378f306438d491b83f849fa424419e567e5b02d3c90d767c1",
      p2pPort: 20002,
      raftId: 3,
      raftPort: 40002
  }, {
      ip: "127.0.0.1",
      nodeId: "e23073e4ff828007d9dd247cddb9b9136cda409aad53cd8a64f44ff3200c65ad196632aa73d3025f4d51bc2dd10b24dc64a8b196c310ae1eb46ec972648c44e8",
      p2pPort: 20000,
      raftId: 2,
      raftPort: 40000
  }],
//the old leader is the local node which web3 client connected to
  leader: "54ed93475cafc97fb6ba6f30943812222007d7135dac5efb565a45b1c73a74f02f1a940cf61caaecc93938cf09c3728b67350300313412687babed3c0e4b93ec",
  role: "verifier",
  addPeer: function(),
  getCluster: function(callback),
  getLeader: function(callback),
  getRole: function(callback),
  removePeer: function()
}
```
All the subsequent transaction return the error "replacement transaction underpriced".I tried to overwrite the pending transaction by add the gas price but return "Gas price not 0".I still can't make it clear what caused the issue,but the chain is always stuck until i restart the geth client.Will someone please help to check the issue.Thanks very much!

**Comment by xuzhitong** [comment]
I  tried another account to call contract method,but the chain has no responding.I checked the raft minter node's log and found it didn't mint new block.
```
INFO [09-04|04:23:27.314] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|05:23:27.314] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|06:23:27.314] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|07:23:27.171] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|08:23:27.171] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|09:23:27.172] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|10:23:27.172] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|11:23:27.176] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|12:23:27.172] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-04|13:23:27.171] Regenerated local transaction journal    transactions=0 accounts=0
```

**Comment by SatpalSandhu61** [comment]
Could you also supply your genesis block config please, in order for me to investigate. Thanks.

**Comment by xuzhitong** [comment]
> Could you also supply your genesis block config please, in order for me to investigate. Thanks.

{
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0,
    "byzantiumBlock": 0,
    "chainId": 10,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip158Block": 0,
    "isQuorum": true
  },
  "difficulty": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0xE0000000",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00",
  "alloc": {}
}

**Comment by fixanoid** [comment]
@xuzhitong its possible to clear the nodes pending txn log by bringing it down and deleting transactions.rlp as described here: https://ethereum.stackexchange.com/questions/1774/geth-how-to-clear-queued-transactions. This isn't an ideal situations and we are investigating a possible fix.

**Comment by xuzhitong** [comment]
> @xuzhitong its possible to clear the nodes pending txn log by bringing it down and deleting transactions.rlp as described here: https://ethereum.stackexchange.com/questions/1774/geth-how-to-clear-queued-transactions. This isn't an ideal situations and we are investigating a possible fix.

Thanks,but I think it's unable to solve my issue.When I restart the geth which web3 client connected to,the pending transactions will be cleaned up automatically. I think there are two issues (may be cause by the same reason) in my chain:
1、When "replacement transaction underpriced" happened,there is no method to recover except restarting the geth.
2、When raft leader changed from web3 server node to another,the chain stop mint new block.
I have restarted the chain and it works fine now. I also set the log level to trace . If the issue happen next time I can catch more infomations.

**Comment by xuzhitong** [comment]
@SatpalSandhu61 I have reproduced the issue and I found very much trace from log on the web3 server node (ip is 10.100.9.72) as below:
```
sed"
DEBUG[09-06|11:02:33.136] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:02:33.136] Dial task done                           task="staticdial c220459013634dae 10.100.9.68:0"
TRACE[09-06|11:02:33.136] New dial task                            task="wait for dial hist expire (14.326371ms)"TRACE[09-06|11:02:33.151] Dial task done                           task="wait for dial hist expire (14.326371ms)"
TRACE[09-06|11:02:33.151] New dial task                            task="staticdial 9b535e89972f0186 10.100.9.83:0"     TRACE[09-06|11:02:33.152] Dial error                               task="staticdial 9b535e89972f0186 10.100.9.83:0"     err="dial tcp 10.100.9.83:0: connect: connection refused"DEBUG[09-06|11:02:33.152] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:02:33.152] Dial task done                           task="staticdial 9b535e89972f0186 10.100.9.83:0"
TRACE[09-06|11:02:33.152] New dial task                            task="wait for dial hist expire (29.98403521s)"
DEBUG[09-06|11:02:53.043] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s 
TRACE[09-06|11:03:03.136] Dial task done                           task="wait for dial hist expire (29.98403521s)"
TRACE[09-06|11:03:03.137] New dial task                            task="staticdial c220459013634dae 10.100.9.68:0"
TRACE[09-06|11:03:03.138] Dial error                               task="staticdial c220459013634dae 10.100.9.68:0"     err="dial tcp 10.100.9.68:0: connect: connection refused"DEBUG[09-06|11:03:03.138] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:03:03.139] Dial task done                           task="staticdial c220459013634dae 10.100.9.68:0"
TRACE[09-06|11:03:03.139] New dial task                            task="wait for dial hist expire (13.428701ms)"
TRACE[09-06|11:03:03.152] Dial task done                           task="wait for dial hist expire (13.428701ms)"
TRACE[09-06|11:03:03.153] New dial task                            task="staticdial 9b535e89972f0186 10.100.9.83:0"
TRACE[09-06|11:03:03.154] Dial error                               task="staticdial 9b535e89972f0186 10.100.9.83:0"     err="dial tcp 10.100.9.83:0: connect: connection refused"DEBUG[09-06|11:03:03.154] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:03:03.154] Dial task done                           task="staticdial 9b535e89972f0186 10.100.9.83:0"
TRACE[09-06|11:03:03.154] New dial task                            task="wait for dial hist expire (29.984883729s)"
DEBUG[09-06|11:03:13.044] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
INFO [09-06|11:03:20.085] Regenerated local transaction journal    transactions=2 accounts=2   
```
Now the raft leader is changed to node which ip is "10.100.9.83".When I send a new transaction by another account,there is not any block trace printed in the leader node's log except:
```
DEBUG[09-06|11:14:21.631] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:14:21.631] Dial task done                           task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"
TRACE[09-06|11:14:21.631] New dial task                            task="wait for dial hist expire (29.999994842s)"
DEBUG[09-06|11:14:28.932] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[09-06|11:14:48.932] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[09-06|11:14:51.631] Dial task done                           task="wait for dial hist expire (29.999994842s)"
TRACE[09-06|11:14:51.631] New dial task                            task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"
TRACE[09-06|11:14:51.635] Dial error                               task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"     err="dial tcp 10.100.9.74:0: connect: connection refused"
DEBUG[09-06|11:14:51.635] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:14:51.635] Dial task done                           task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"
TRACE[09-06|11:14:51.635] New dial task                            task="wait for dial hist expire (29.999983834s)"
DEBUG[09-06|11:15:08.933] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[09-06|11:15:21.635] Dial task done                           task="wait for dial hist expire (29.999983834s)"
TRACE[09-06|11:15:21.636] New dial task                            task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"
TRACE[09-06|11:15:21.637] Dial error                               task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"     err="dial tcp 10.100.9.74:0: connect: connection refused"
DEBUG[09-06|11:15:21.637] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:15:21.637] Dial task done                           task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"
TRACE[09-06|11:15:21.637] New dial task                            task="wait for dial hist expire (29.999993794s)"
DEBUG[09-06|11:15:28.933] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[09-06|11:15:48.933] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[09-06|11:15:51.637] Dial task done                           task="wait for dial hist expire (29.999993794s)"
TRACE[09-06|11:15:51.638] New dial task                            task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"
TRACE[09-06|11:15:51.638] Dial error                               task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"     err="dial tcp 10.100.9.74:0: connect: connection refused"
DEBUG[09-06|11:15:51.639] Can't resolve node                       id=0x8bf2b0         err="discovery is disabled"
TRACE[09-06|11:15:51.639] Dial task done                           task="staticdial 267fc38a08ad1dbe 10.100.9.74:0"
TRACE[09-06|11:15:51.639] New dial task                            task="wait for dial hist expire (29.999990045s)"
DEBUG[09-06|11:16:08.934] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0
                         
```                
Any suggestions?

**Comment by xuzhitong** [comment]
#775 may be  the same problem.I will to update the bin for test again.

**Comment by SatpalSandhu61** [comment]
Hi, I've been out for much of the last couple of weeks so just picking this up again.
I suspect you are correct and you may be facing the same issue as #775. What is possibly happening is that a network glitch is causing one of the nodes to drop; because the node is unable to rejoin the network, you only have 2 raft nodes, so minting is halted and transactions go into pending.
Did the issue go away when you tried the updated bin with the fix for #775?

Note that the reason you get "replacement transaction underpriced", instead of the transactions just becoming pending is perhaps because you are not correctly incrementing the account nonce. Make sure you are using the `pending` flag in getTransactionCount():
```
web3.eth.getTransactionCount(account address, 'pending')
```

**Comment by xuzhitong** [comment]
> Hi, I've been out for much of the last couple of weeks so just picking this up again.
> I suspect you are correct and you may be facing the same issue as #775. What is possibly happening is that a network glitch is causing one of the nodes to drop; because the node is unable to rejoin the network, you only have 2 raft nodes, so minting is halted and transactions go into pending.
> Did the issue go away when you tried the updated bin with the fix for #775?
> 
> Note that the reason you get "replacement transaction underpriced", instead of the transactions just becoming pending is perhaps because you are not correctly incrementing the account nonce. Make sure you are using the `pending` flag in getTransactionCount():
> 
> ```
> web3.eth.getTransactionCount(account address, 'pending')
> ```
Thanks your reply.The stuck issue has gone away while fix the bug #775.But the "replacement transaction underpriced" issue is still exist.My  code always used the pending flag in getTransactionCount():
```
    web3.eth.getTransactionCount(account,"pending",function(error,result){
        if (error){
            console.error('getTransactionCount error ',error);
            return;
        }
        var rawTx = {
            nonce: result,
            from: account,
            to: contractAddress,
            gas: 3000000,
            data: encodeAbi
        };
```
It happened while the two transactions almost the same time came in.I'm not sure how the "getTransactionCount" works.I guess in some cases like：
when the first transaction has not gone into the 'pending' state and the second came in.
Can it return the correct nonce?

**Comment by SatpalSandhu61** [comment]
If you submit multiple transactions in parallel then unfortunately you can still end up with a duplicate nonce. This is a known issue with upstream ethereum too. There's a good discussion on this [here](https://ethereum.stackexchange.com/questions/39790/concurrency-patterns-for-account-nonce).

**Comment by SatpalSandhu61** [comment]
Given that you've solved the issue with transactions becoming stuck, is it ok if we close this ticket?
