### ISSUE TITLE
"Stack too deep" issues

### ISSUE THREAD

**Issue by stanta** [Consensys-Incorporated/quorum#817]
We have a lot of "Stack too deep" issues in our project  (because we build project with large structures), and looks to move from classical EVM to something else. This issues really depends on number of DUP commands limit.  It have sense for miner's economy limitations in public Ethereum, but no senses for corporate applications.

https://github.com/jpmorganchase/quorum/blob/7e87e403407fcb3b3c417739eef2fe1dae923add/core/vm/opcodes.go#L171

Seems as you copypasted that code from original EVM, but do you plan to remove this and same restrictions in Quorum?

**Comment by fixanoid** [comment]
Hi @stanta. Generally, we'd like to remain as close as possible to the original go-ethereum client as to avoid conflicted merges when we upgrade. That said, we are not opposed to modifications that make sense in private setting vs public and we welcome contributions in this space.

**Comment by geethagurram21** [comment]
We are also facing the same issues, does anyone have a solution for this issue

**Comment by Open-Rawi** [comment]
Hi @stanta , @fixanoid , this requires changes not only in EVM but in solidity or other compilers which complies into (new) EVM. it will also break other existing tools (such as security/code scanner, optimisers etc). hence i don't recommend this change but rather find a work around.
@stanta  may i know how i can reproduce this issue, let me find a work-around for you.

**Comment by ricardolyn** [comment]
@stanta any update about this? thank you
