### ISSUE TITLE
Not able to mine transactions

### ISSUE THREAD

**Issue by vasa-develop** [Consensys-Incorporated/quorum#818]
#### System information

**Geth version: `geth version`**

WARN [09-13|22:33:19.148] Sanitizing cache to Go's GC limits       provided=1024 updated=666
Geth
Version: 1.8.18-stable
Git Commit: 664c2ab20af384c5b350aabf5f6307327d8de09e
Quorum Version: 2.2.5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.10.1
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
OS & Version: Windows/Linux/OSX

**Branch, Commit Hash or Release: `git status`**

commit 664c2ab20af384c5b350aabf5f6307327d8de09e
Author: Nguyen Kien Trung <trung.n.k@gmail.com>
Date:   Tue Aug 27 15:17:59 2019 -0400

    p2p/enode, p2p/discv5: fix URL parsing test for go 1.11.13 (#810)

#### Other Details

- I have set up a custom network on 5 quorum nodes(constellation), on 5 different ubuntu 16.10, t2.medium machines on AWS, using the 7nodes example. 

- Consensus used: Istanbul PBFT

#### Expected behaviour
Should able to deploy the contracts (mining the transactions) 

#### Actual behaviour

I can't share the contract here, but I will try to provide as much detail as I can.

There are 3 observations:

1. 
When I try to deploy the contract using truffle, with the following config, I get the following errors:

**Config**
```
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks: {
    development: {
      host: "NODE_1_IP",
      port: 22000,
      network_id: "*", // Match any network id
      gasPrice: 0,
      gas: 4600000
    }
  }
}

```

**Error Stack Trace**

![err2](https://user-images.githubusercontent.com/28847087/64899045-2dee8680-d6a7-11e9-9c4a-d41bbd900522.png)

2.
When I try to deploy the contract on Remix, with `gasLimit: 3000000`, I don't get the `out of gas error`. But now somehow, the new block is not mined. Below is the stack trace pic.

![err1](https://user-images.githubusercontent.com/28847087/64898932-b7ea1f80-d6a6-11e9-98c5-b7f684b6a8ef.png)

3.
When I run the same contract on a 7 nodes example, hosted on a single ubuntu 16.10, t2.medium machine, **it works**. 

#### Steps to reproduce the behavior

The code for the 5 quorum nodes is public:
- https://github.com/vasa-develop/quorum-pbft-1 
- https://github.com/vasa-develop/quorum-pbft-2
- https://github.com/vasa-develop/quorum-pbft-3
- https://github.com/vasa-develop/quorum-pbft-4
- https://github.com/vasa-develop/quorum-pbft-5

Use these repos to set up a network of 5 nodes on different machines and then try to deploy a contract, using truffle.

#### What I have already tried to fix the issue

I have already tried the fixes mentioned in #700 , but still no luck. 

@jpmsam @fixanoid Let me know if you need any other details.

**Comment by fixanoid** [comment]
@vasa-develop is the genesis you are using been generated using istanbul-tools or have you reused one from quorum-examples? Are blocks increasing in your setup?

**Comment by vasa-develop** [comment]
@fixanoid 

>  is the genesis you are using been generated using istanbul-tools or have you reused one from quorum-examples?

I reused the genesis from the quorum-examples. Can you point where I can find the steps/instructions to generate genesis from the [Istanbul-tools](https://github.com/jpmorganchase/istanbul-tools/)?

> Are blocks increasing in your setup?

No. The blocks are not increasing.
Here is a trace.

![err-quorum](https://user-images.githubusercontent.com/28847087/65031366-c5313380-d95e-11e9-8e33-cc8f49018afc.png)

**Comment by vasa-develop** [comment]
This can be the possible issue: https://github.com/jpmorganchase/istanbul-tools/pull/8

**Comment by vasa-develop** [comment]
This can be a possible issue: https://github.com/jpmorganchase/istanbul-tools/pull/8 

I will try setting up the network using the [Getting Started Docs](https://github.com/jpmorganchase/quorum/blob/50429f8cd3d11e045dd00a5c6d0b8eaa37072155/docs/Getting%20Started/Creating-A-Network-From-Scratch.md) and see if it works or not.

**Comment by jbhurat** [comment]
Hi @vasa-develop, are you able to deploy the contracts after starting the network using the Getting Started Docs?

**Comment by vasa-develop** [comment]
@jbhurat Yes, but right now I'm having issues in sending transactions. The transaction nonce doesn't seem to increase after I send the transaction, so it works for only `nonce=0`.

**Comment by jbhurat** [comment]
I see that you closed this issue. Does it mean its working for you now?

**Comment by vasa-develop** [comment]
@jbhurat  Nope, I opened a new issue here: https://github.com/jpmorganchase/quorum/issues/822
