### ISSUE TITLE
Failed to decode message from payload    address=0xxxxx err="unauthorized address"

### ISSUE THREAD

**Issue by ghb-1234** [Consensys-Incorporated/quorum#828]
I use quorumengineering/tessera:0.10.0 and quorumengineering/quorum:2.2.5 to generate config(such as tm.key、tm.pub、nodekey、address), https://github.com/getamis/istanbul-tools generate genesis extraData，everything seems ok，but quorum node log occur **ERROR 'Failed to decode message from payload   address=0xxxxxxxxxxxxxxxx err="unauthorized address"'**.  The unauthorized address is quorum node coinbase. I operate with below shells:

step1: generate tm.key,nodekey,enode
> #!/bin/bash
> for i in `seq 1 $1`
> do
>   echo "loop: $i"
>   docker run -it --rm -v $(pwd)/keys:/keys quorumengineering/tessera:0.10.0 -keygen -filename /keys/tm$i
>   docker run -it --rm --entrypoint=bootnode -v $(pwd)/enodes:/configs quorumengineering/quorum:2.2.5 --genkey=/configs/nodekey$i
>   docker run -it --rm --entrypoint=bootnode -v $(pwd)/enodes:/configs quorumengineering/quorum:2.2.5 --nodekey=/configs/nodekey$i --writeaddress >> $(pwd)/enodes/nodeid$i
> done

step2: assemble static-nodes.json
> #!/bin/bash
> echo "[" > ./static-nodes.json
> for i in `seq 1 $1`
> do
>     sep=`[[ $i -lt $1 ]] && echo ","`
>     nodeid=$(cat -A ./enodes/nodeid$i | cut -c 1-128)
>     echo "  \"enode://${nodeid}@172.16.239.$((10+$i)):21000?discport=0&raftport=50400\"${sep}" >> ./static-nodes.json
> done
> echo "]" >> ./static-nodes.json

step3: assemble istanbul-genesis.json
> #!/bin/bash
> cat > ./istanbul-genesis.json <<EOF
> {
>   "alloc": {
> EOF
> 
> cat > ./config.toml <<EOF
> vanity = "0x00"
> validators = [
> EOF
>     for i in `seq 1 $1`
>     do
>       echo "loop $i"
>       ACCOUNT=$(docker run -it --rm -v $(pwd)/passwords.txt:/password.txt -v $(pwd)/keystore:/keystore quorumengineering/quorum:2.2.5 --password password.txt --keystore keystore account new | sed -n 2p | cut -c 11-50)
>       \mv keystore/UTC-* keys/key$i
>       sep=`[[ $i -lt $1 ]] && echo ","`
> cat >> ./config.toml <<EOF
> "0x${ACCOUNT}"${sep}
> EOF
> 
> cat >> istanbul-genesis.json <<EOF
>     "0x${ACCOUNT}": {
>       "balance": "1000000000000000000000000000"
>     }${sep}
> EOF
>     done
>     echo "]" >> ./config.toml
> 
> istanbul extra encode --config ./config.toml > extra.txt
>   
> cat >> istanbul-genesis.json <<EOF
>   },
>   "coinbase": "0x0000000000000000000000000000000000000000",
>   "config": {
>     "homesteadBlock": 0,
>     "byzantiumBlock": 0,
>     "constantinopleBlock":0,
>     "chainId": 10,
>     "eip150Block": 0,
>     "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
>     "eip155Block": 0,
>     "eip158Block": 0,
>     "isQuorum": true,
>     "istanbul": {
>       "epoch": 30000,
>       "policy": 0
>     }
>   },
>   "difficulty": "0x1",
>   "extraData": "$(cat extra.txt | cut -c 30-)",
>   "gasLimit": "0xE0000000",
>   "mixhash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
>   "nonce": "0x0",
>   "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
>   "timestamp": "0x00"
> }
> EOF

step4: docker-compose.yml

> version: "3.6"
> x-quorum-def:
>   &quorum-def
>   restart: "on-failure"
>   image: "${QUORUM_DOCKER_IMAGE:-quorumengineering/quorum:2.2.5}"
>   expose:
>     - "21000"
>     - "50400"
>   healthcheck:
>     test: ["CMD", "wget", "--spider", "--proxy", "off", "http://localhost:8545"]
>     interval: 3s
>     timeout: 3s
>     retries: 10
>     start_period: 5s
>   entrypoint:
>     - /bin/sh
>     - -c
>     - |
>       UDS_WAIT=10
>       for i in $$(seq 1 100)
>       do
>         set -e
>         if [ -S $${PRIVATE_CONFIG} ] && \
>           [ "I'm up!" == "$$(wget --timeout $${UDS_WAIT} -qO- --proxy off 172.16.239.10$${NODE_ID}:9000/upcheck)" ];
>         then break
>         else
>           echo "Sleep $${UDS_WAIT} seconds. Waiting for TxManager."
>           sleep $${UDS_WAIT}
>         fi
>       done
>       DDIR=/qdata/dd
>       rm -rf $${DDIR}
>       mkdir -p $${DDIR}/keystore
>       mkdir -p $${DDIR}/geth
>       cp /examples/enodes/nodekey$${NODE_ID} $${DDIR}/geth/nodekey
>       cp /examples/static-nodes.json $${DDIR}/static-nodes.json
>       cp $${DDIR}/static-nodes.json $${DDIR}/permissioned-nodes.json
>       cat $${DDIR}/static-nodes.json
>       GENESIS_FILE="/examples/istanbul-genesis.json"
>       NETWORK_ID=$$(cat $${GENESIS_FILE} | grep chainId | awk -F " " '{print $$2}' | awk -F "," '{print $$1}')
>       GETH_ARGS_istanbul="--emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full"
>       geth --datadir $${DDIR} init $${GENESIS_FILE}
>       geth \
>         --identity node$${NODE_ID}-istanbul \
>         --datadir $${DDIR} \
>         --permissioned \
>         --nodiscover \
>         --verbosity 5 \
>         --networkid $${NETWORK_ID} \
>         --rpc \
>         --rpccorsdomain "*" \
>         --rpcvhosts "*" \
>         --rpcaddr 0.0.0.0 \
>         --rpcport 8545 \
>         --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,istanbul \
>         --port 21000 \
>         --password /examples/passwords.txt \
>         ${QUORUM_GETH_ARGS:-} $${GETH_ARGS_istanbul}}
> x-tx-manager-def:
>   &tx-manager-def
>   image: "${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.10.0}"
>   expose:
>     - "9000"
>     - "9080"
>   restart: "no"
>   healthcheck:
>     test: ["CMD-SHELL", "[ -S /qdata/tm/tm.ipc ] || exit 1"]
>     interval: 3s
>     timeout: 3s
>     retries: 20
>     start_period: 5s
>   entrypoint:
>     - /bin/sh
>     - -c
>     - |
>       DDIR=/qdata/tm
>       rm -rf $${DDIR}
>       mkdir -p $${DDIR}
>       DOCKER_IMAGE="${QUORUM_TX_MANAGER_DOCKER_IMAGE:-quorumengineering/tessera:0.10.0}"
>           cp /examples/keys/tm$${NODE_ID}.pub $${DDIR}/tm.pub
>           cp /examples/keys/tm$${NODE_ID}.key $${DDIR}/tm.key
>           TESSERA_VERSION=$$(unzip -p /tessera/tessera-app.jar META-INF/MANIFEST.MF | grep Tessera-Version | cut -d" " -f2)
>           echo "Tessera version (extracted from manifest file): $${TESSERA_VERSION}"
>           V08=$$(echo -e "0.8\n$${TESSERA_VERSION}" | sort -n -r -t '.' -k 1,1 -k 2,2 | head -n1)
>           V09AndAbove=$$(echo -e "0.9\n$${TESSERA_VERSION}" | sort -n -r -t '.' -k 1,1 -k 2,2 | head -n1)
>           TESSERA_CONFIG_TYPE="-09"
>           case "$${TESSERA_VERSION}" in
>               "$${V09AndAbove}")
>                   TESSERA_CONFIG_TYPE="-09"
>                   ;;
>           esac
>           echo Config type $${TESSERA_CONFIG_TYPE}
>           cat <<EOF > $${DDIR}/tessera-config-09.json
>           {
>             "useWhiteList": false,
>             "jdbc": {
>               "username": "sa",
>               "password": "",
>               "url": "jdbc:h2:./$${DDIR}/db;MODE=Oracle;TRACE_LEVEL_SYSTEM_OUT=0",
>               "autoCreateTables": true
>             },
>             "serverConfigs":[
>             {
>               "app":"ThirdParty",
>               "enabled": true,
>               "serverAddress": "http://$$(hostname -i):9080",
>               "communicationType" : "REST"
>             },
>             {
>               "app":"Q2T",
>               "enabled": true,
>               "serverAddress": "unix:$${DDIR}/tm.ipc",
>               "communicationType" : "REST"
>             },
>             {
>               "app":"P2P",
>               "enabled": true,
>               "serverAddress": "http://$$(hostname -i):9000",
>               "sslConfig": {
>                 "tls": "OFF"
>               },
>               "communicationType" : "REST"
>             }
>             ],
>             "peer": [
>                {
>                    "url": "http://txmanager1:9000"
>                },
>                {
>                    "url": "http://txmanager2:9000"
>                },
>                {
>                    "url": "http://txmanager3:9000"
>                },
>                {
>                    "url": "http://txmanager4:9000"
>                },
>                {
>                    "url": "http://txmanager5:9000"
>                }
>             ],
>             "keys": {
>               "passwords": [],
>               "keyData": [
>                 {
>                   "config": $$(cat $${DDIR}/tm.key),
>                   "publicKey": "$$(cat $${DDIR}/tm.pub)"
>                 }
>               ]
>             },
>             "alwaysSendTo": []
>           }
>       EOF
>           cat $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
>           java -Xms128M -Xmx128M -jar /tessera/tessera-app.jar -configfile $${DDIR}/tessera-config$${TESSERA_CONFIG_TYPE}.json
> services:
>   node1:
>     << : *quorum-def
>     hostname: node1
>     ports:
>       - "22000:8545"
>     volumes:
>       - ./vol1:/qdata
>       - .:/examples:ro
>     depends_on:
>       - txmanager1
>     environment:
>       - PRIVATE_CONFIG=/qdata/tm/tm.ipc
>       - NODE_ID=1
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.11
>   txmanager1:
>     << : *tx-manager-def
>     hostname: txmanager1
>     ports:
>       - "9081:9080"
>     volumes:
>       - ./vol1:/qdata
>       - .:/examples:ro
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.101
>     environment:
>       - NODE_ID=1
>   node2:
>     << : *quorum-def
>     hostname: node2
>     ports:
>       - "22001:8545"
>     volumes:
>       - ./vol2:/qdata
>       - .:/examples:ro
>     depends_on:
>       - txmanager2
>     environment:
>       - PRIVATE_CONFIG=/qdata/tm/tm.ipc
>       - NODE_ID=2
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.12
>   txmanager2:
>     << : *tx-manager-def
>     hostname: txmanager2
>     ports:
>       - "9082:9080"
>     volumes:
>       - ./vol2:/qdata
>       - .:/examples:ro
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.102
>     environment:
>       - NODE_ID=2
>   node3:
>     << : *quorum-def
>     hostname: node3
>     ports:
>       - "22002:8545"
>     volumes:
>       - ./vol3:/qdata
>       - .:/examples:ro
>     depends_on:
>       - txmanager3
>     environment:
>       - PRIVATE_CONFIG=/qdata/tm/tm.ipc
>       - NODE_ID=3
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.13
>   txmanager3:
>     << : *tx-manager-def
>     hostname: txmanager3
>     ports:
>       - "9083:9080"
>     volumes:
>       - ./vol3:/qdata
>       - .:/examples:ro
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.103
>     environment:
>       - NODE_ID=3
>   node4:
>     << : *quorum-def
>     hostname: node4
>     ports:
>       - "22003:8545"
>     volumes:
>       - ./vol4:/qdata
>       - .:/examples:ro
>     depends_on:
>       - txmanager4
>     environment:
>       - PRIVATE_CONFIG=/qdata/tm/tm.ipc
>       - NODE_ID=4
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.14
>   txmanager4:
>     << : *tx-manager-def
>     hostname: txmanager4
>     ports:
>       - "9084:9080"
>     volumes:
>       - ./vol4:/qdata
>       - .:/examples:ro
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.104
>     environment:
>       - NODE_ID=4
>   node5:
>     << : *quorum-def
>     hostname: node5
>     ports:
>       - "22004:8545"
>     volumes:
>       - ./vol5:/qdata
>       - .:/examples:ro
>     depends_on:
>       - txmanager5
>     environment:
>       - PRIVATE_CONFIG=/qdata/tm/tm.ipc
>       - NODE_ID=5
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.15
>   txmanager5:
>     << : *tx-manager-def
>     hostname: txmanager5
>     ports:
>       - "9085:9080"
>     volumes:
>       - ./vol5:/qdata
>       - .:/examples:ro
>     networks:
>       my-quorum-net:
>         ipv4_address: 172.16.239.105
>     environment:
>       - NODE_ID=5
> networks:
>   my-quorum-net:
>     name: my-quorum-net
>     driver: bridge
>     ipam:
>       driver: default
>       config:
>       - subnet: 172.16.239.0/24

step5: docker-compose up -d

step6: docker logs -f  xxx_node1_1
![err_1569383357845](https://user-images.githubusercontent.com/19897979/65567961-b49a4200-df8a-11e9-8613-7fcba742b3e5.png)
what cause th proplem?  Can't I use alloc addresses the same with validators ?

**Comment by ghb-1234** [comment]
@fixanoid pls help

**Comment by prd-fox** [comment]
Hi @im-Angry.

From looking at your scripts, it looks like the issue is you have used the user keys (generated from `geth account new` as the inputs to the Istanbul `extradata` generation.

Instead, it should be the address generated from each of the nodes `nodekey`s. This is a bit tricker, as it isn't a function that Istanbul-tools provides. 
In the past I have used Metamask to import the `nodekey` file and have it tell me then address. Alternatively, you can let `istanbul-tools` generate the whole lot for you, nodekeys and genesis file. From there, edit the genesis file to add in funds for the accounts you generated using `geth account new`.
