### ISSUE TITLE
Quourm Raft - generate different FROM address when externally signing transaction 

### ISSUE THREAD

**Issue by ThomasRalee** [Consensys-Incorporated/quorum#829]
Hi there,

#### System information
Geth version: `2.2.5`
Tessera version: `0.10`

#### Expected behaviour
Transaction **from** address should remain the same as the one used to sign the transaction.

#### Actual behaviour
Transaction **from** address changed to random address when transaction passes.

#### Steps to reproduce the behaviour
1) Follow this [script](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/samples/send-private-txn-quorum.js/send-externalSigningTemplate.js) on a fresh network on a RAFT network

##### Contract deployment
- sendRawRequest with following raw hash
```
0xf8a180808347b76094e57bbc9b321b442fac24484597849f27fc0d2ac880b84043ad0e5f1d211475cc4353cfd629ff326f247f33fa53b63f0eb99393ecb50677cb6945e5db37dd3bdd7f7e9b562cb529a59c29884f5fb5b315e0e36be080bed625a0035f9bb8cb3ba1692a1a00cc755103015e0000011610bb2c3fa847f94f8dd3e0a039c46dccc3f32c08fca480979d047f307d4f9bd49e17f6a087e16969b73bc533
```
- using web3's `accounts.recoverTransaction` function it on the raw hash returns the correct account  - `0xf06EF8a63C8669Bbc526Ff23595232F26f31a176`
- on the transaction `0x0e734648bddf614fc68393d12441950d4ae18aec93b105e79822f7d02f5472cb` i am getting a different `from` address

```
eth.getTransaction('0x0e734648bddf614fc68393d12441950d4ae18aec93b105e79822f7d02f5472cb');
{
  blockHash: "0xa9a525c2210afad45bbbf768d05da024196d090853c57d3172330ea3ee649c1f",
  blockNumber: 1,
  from: "0x38cadb6639c2af233a6b513b400f2d2326ea2a02",
  gas: 4700000,
  gasPrice: 0,
  hash: "0x0e734648bddf614fc68393d12441950d4ae18aec93b105e79822f7d02f5472cb",
  input: "0xdc308e9c0e335fc659261eb6753e269b1de8dd0037d2f4fd5263996dbae2322ae394a332348b8ee8bc00afd0121a2f74e54bbcd486d8c6eabdd77a85308b20fd",
  nonce: 0,
  r: "0x446eea4dd87cb9061d4d99ed36bbe560a868348d52522b7dcb3fe71b9a685b28",
  s: "0x6ac26aefed996169eb1aab391c8761488440bd2e00f201a3fec07e0073032c0e",
  to: null,
  transactionIndex: 0,
  v: "0x25",
  value: 0
}
```

##### Contract function call
- sendRawRequest with following raw hash
```
0xf8a180808347b76094e57bbc9b321b442fac24484597849f27fc0d2ac880b840dd36b0beac0124632b1bdee9d4d20f2a34fd77b9024fcb2e594d8e4fad529299f4ce11f4544fc04afb15db50c4eb4fb490ad53f740fbc417d6742c2243a7e1e725a0377147a41dd87a8241fff7679a046d7960c4c9879914e1f6b5aa5928d1a64c1aa026412cb4cd9ceb2b495751d54eb5d1a41c49b1b22d8060c62fecdf9b5b603093
```
- using web3's `accounts.recoverTransaction` function it on the raw hash returns the correct account  - `0x5339595D50b2d462101dEf869A9bEf60b014f7F7`
- on the transaction `0x05c90baeb227e1209c94cca57c4c645dd2287e7a217e9ef2516ba32b51101455` i am getting a different `from` address
```
eth.getTransaction('0x05c90baeb227e1209c94cca57c4c645dd2287e7a217e9ef2516ba32b51101455')
{
  blockHash: "0x95f8636414afd02d6cc4f8530403e87118f766e77f266ef2e6440007d1bba214",
  blockNumber: 3,
  from: "0xece3e7034b1f4ebf88f999cf905202ea241b9770",
  gas: 4700000,
  gasPrice: 0,
  hash: "0x05c90baeb227e1209c94cca57c4c645dd2287e7a217e9ef2516ba32b51101455",
  input: "0xdd36b0beac0124632b1bdee9d4d20f2a34fd77b9024fcb2e594d8e4fad529299f4ce11f4544fc04afb15db50c4eb4fb490ad53f740fbc417d6742c2243a7e1e7",
  nonce: 0,
  r: "0x377147a41dd87a8241fff7679a046d7960c4c9879914e1f6b5aa5928d1a64c1a",
  s: "0x26412cb4cd9ceb2b495751d54eb5d1a41c49b1b22d8060c62fecdf9b5b603093",
  to: "0xe57bbc9b321b442fac24484597849f27fc0d2ac8",
  transactionIndex: 0,
  v: "0x25",
  value: 0
}
```
Will bring this issue to Quourm's Development channel for help, will update.

**Comment by nicolae-leonte-go** [comment]
Can you please confirm that you are using the correct dependencies as mentioned in the corresponding [package.json?](https://github.com/jpmorganchase/quorum-examples/blob/master/examples/7nodes/samples/send-private-txn-quorum.js/package.json)

  "dependencies": {
    "quorum-js": "^0.3.0",
    "web3": "1.0.0-beta.36"
  }

**Comment by ThomasRalee** [comment]
Hi Nicolae, sorry for the late reply. I am running it with my own nodes and i am using:
```
"ethereumjs-tx": "^2.1.1",
"quorum-js": "^0.3.1",
"web3": "^2.0.0-alpha.1"
```
I can confirm this => `web3.accounts.recoverTransaction(txHash)` works on both methods in retrieving the correct accounts through its Private Key
```
// ethereumjs-tx
const tx = new EthereumTx(rawTransaction);
  tx.sign(Buffer.from(node.WALLET_KEY, 'hex'));
```
```
// web3
web3.eth.accounts.signTransaction({
    nonce,
    to: contractAddress,
    gasLimit: '0x47b760',
    gasPrice: "0x0",
    data: encodedABI,
  }, node.WALLET_KEY)
```
