### ISSUE TITLE
Quorum stops working after block 5422.

### ISSUE THREAD

**Issue by pccr10001** [Consensys-Incorporated/quorum#831]
#### System information

Geth version: 2.2.4 / 2.2.5

OS & Version: Ubuntu 16.04

#### Expected behaviour

Everything works.

#### Actual behaviour

After block 5422, geth won't seal any blocks.

#### Steps to reproduce the behaviour

I uploaded the nodes data [here](https://transfer.sh/3dEws/quorum_crash.tar.xz).

* File contents
    * 5421 -> worked fine
    * 5422 -> worked fine.
    * 5422_failed -> sent 1tx and failed.

* genesis.json
```json=
{
  "alloc": {
    "d3ba28a1d4c8d4dd68e2428247d8719a538aa4f9": {
      "balance": "1000000000000000000000000000"
    },
    "4a5de9eb9e9c9a53f494f9edc0fc5841b9db1f2f": {
      "balance": "1000000000000000000000000000"
    },
    "88b2d72458a07dfde207fa710337e90b75253d61": {
      "balance": "1000000000000000000000000000"
    },
    "a4191635479270b221eae35e90edd4d8f91611db": {
      "balance": "1000000000000000000000000000"
    },
    "7bd36ef508a216460dffb7cbc3ffebcd505af1c0": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x1",
  "gasLimit": "0xE0000000",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x5d8c97fc",
  "config":{
    "chainId": 10,
    "eip150Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "isQuorum": true
  },
  "extraData": "0x",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578"
}
```

#### Backtrace

```

```

**Comment by jbhurat** [comment]
Hi @pccr10001, I reviewed the logs and see that there are a large number of errors like `VM returned with error                   err="invalid opcode 0xb7"` and `VM returned with error                   err="stack underflow (0 <=> 11)"` these suggests issues with contract code that you are trying to create. Is it possible to fix those and see if it resolves block sealing issues

**Comment by pccr10001** [comment]
Hi @jbhurat I just want to append some data to the transaction, that isn't contract code, did it cause the problem?
I will test simple "send transactions", and report here.

**Comment by pccr10001** [comment]
Hello @jbhurat 
I tested 2 scenarios: 
* contract tx: [link](https://transfer.sh/lNjlH/quorum_crash.tar.xz)
```sol=
pragma solidity ^0.5.1;

import "./Ownable.sol";

contract DataContract is Ownable {

    string private content;

    constructor(string memory _content) public {
        content = _content;
    }

    function getContent() public view returns (string memory) {
        return content;
    }

    function destroy() public onlyOwner {
        selfdestruct(msg.sender);
    }

}

```
* simple send tx: [link](https://transfer.sh/ghlYy/quorum_crash.tar.xz)

And it still failed when block number at 5422.

**Comment by jbhurat** [comment]
I see the below messages in the logs, 
`INFO [10-01|03:49:29.300] Imported new chain segment               blocks=1 txs=1 mgas=0.729 elapsed=2.921ms     mgasps=249.421 number=5422 hash=7c265b…97fede cache=0.00B
INFO [10-01|03:49:29.300] persisted the latest applied index       index=5428
INFO [10-01|03:49:29.300] Not minting a new block since there are no pending transactions 
INFO [10-01|03:49:37.083] TX failed, will be removed               hash=5dc35a…4dc995 err="gas limit reached"
INFO [10-01|03:49:37.084] Not minting a new block since there are no pending transactions 
`
Can you try with increased gas limit

**Comment by jbhurat** [comment]
Can you also paste `geth` startup parameters

**Comment by pccr10001** [comment]
`geth` startup command
```bash=
geth --datadir /qdata/dd --rpcport 23001 --port 24001 --raftport 25001 --identity master-1 --raft --rpc --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,clique,raft,istanbul --ws --wsaddr 0.0.0.0 --wsorigins=* --wsapi eth,web3,quorum,txpool,net --wsport 26001 --unlock 0 --password /qdata/passwords.txt --networkid 10 --bootnodes "$bootnodes"
```

`gas limit reached` caused on transfering 0 wei to another account, it succeeded for 5421 times and it always stopped at block 5422.

**Comment by pccr10001** [comment]
This is a failed tx, it caused crash on block 5422.
```json=
{
  blockHash: "0xfacf82d13b8afc8c4f28b4508eee7f2978e8640bc28d3679529992a30225053e",
  blockNumber: 1,
  from: "0x88f9b82462f6c4bf4a0fb15e5c3971559a316e7f",
  gas: 1000000000,
  gasPrice: 0,
  hash: "0xed1bcbde1a015f3c169a10d937c350a1a344b9f9e86d52f2048b1287808cd4a2",
  input: "0x0075754e5ea2863064c185aacf066b7fdfa833acb4af3e705b1a0afe636fbee1b6c02440753df6e344b2d0c4f5f792646bc6f714392bbb5cb48cad406f49c93493",
  nonce: 0,
  r: "0xf3f79472732e45ec5589d2f2aa1474641a2febebc399ddd95083b16ec7d7c87f",
  s: "0x41c8a0fbcb0876c82666c5842c6a00d497d8d176a9466b1fdcc9111381a7ddce",
  to: null,
  transactionIndex: 0,
  v: "0x1b",
  value: 0
}
```

This is a working tx, I used estimateGas function in web3j to setup `gasLimit` value and it's working now.
```json=
{
  blockHash: "0x08a046542106b584a6cecb1bc5c9b2b8c832d456a033b13152f0228cae0f7506",
  blockNumber: 2,
  from: "0x88f9b82462f6c4bf4a0fb15e5c3971559a316e7f",
  gas: 25356,
  gasPrice: 0,
  hash: "0xfaa6db59d36a32677f6a0275d20dacdd5340a09b37b33fc0d9ebb7943e8a31d1",
  input: "0x00ee9eea4e905bb3e383fbf8c920d4c848fc98319958e11a2a3bc99a7a638b5d4c39f9428de1a7c7d69144ce3a52c159fe9a014d81cd82e515a3a05e49b4ac95f8",
  nonce: 1,
  r: "0x6863df923196de669ca1476ec367077e37262955d57deaa64f77d3381a2f791f",
  s: "0x799789b70f43c715e5945e9f700fbeff8170d27fa84784d45d39c0efa21b3850",
  to: null,
  transactionIndex: 0,
  v: "0x1b",
  value: 0
}
```

**Comment by jbhurat** [comment]
Sorry didn't understand the previous comment. Does it work after you use `estimateGas()`

**Comment by pccr10001** [comment]
Yes, I changed the fixed `gasLimit` value to `estimateGas()` output, and everything works.
Thanks for helping me.
