### ISSUE TITLE
Send private transaction failed with istanbul tools generate artifacts

### ISSUE THREAD

**Issue by ghb-1234** [Consensys-Incorporated/quorum#834]
I make an image with dockerfile:

_**FROM quorumengineering/quorum:2.2.5 as builder1
FROM quorumengineering/tessera:0.10.0
RUN "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.10/main" > /etc/apk/repositories
RUN apk --update add python curl bash jq && rm -rf /var/cache/apk/*
COPY --from=builder1 /usr/local/bin/geth /usr/local/bin/geth
COPY --from=builder1 /usr/local/bin/bootnode /usr/local/bin/bootnode
ADD istanbul /usr/local/bin/istanbul
ADD entrypoint.sh /entrypoint.sh
RUN chmod u+x entrypoint.sh
EXPOSE 8545 8546 30303 30303/udp 9000 9080
ENTRYPOINT /entrypoint.sh**_

I start 3 nodes with k8s, and use geth attach command to open JavaScript console，create and unlock the account with personal api, send public transaction, everything is ok。 But when i send private transaction to another node, the current node seem to be destoryed, and err occur :
![20191004023815](https://user-images.githubusercontent.com/19897979/66155446-37d62a80-e652-11e9-9fa0-f0762f41e95f.png)
eth output before send private transaction:
![p1](https://user-images.githubusercontent.com/19897979/66266190-29576100-e854-11e9-8f1b-339a75defb2b.png)
eth output after send private transaction:
![p2](https://user-images.githubusercontent.com/19897979/66266246-8b17cb00-e854-11e9-8a33-c24c8a5da1a5.png)
The private contract is from quorum-examples, just change the privateFor parameter with another node tm.pub. 
What's wrong with it, could you give me some ideas ? @vasa-develop @fixanoid

**Comment by ghb-1234** [comment]
my entrypoint shell as below：
[104-entrypoint.txt](https://github.com/jpmorganchase/quorum/files/3694107/104-entrypoint.txt)
reference: https://github.com/jpmorganchase/quorum/issues/828
@prd-fox

**Comment by prd-fox** [comment]
You need to add the location of the Tessera socket file when starting geth.

i.e. `PRIVATE_CONFIG=<location of tessera socket file> nohup geth ...`

I think it would be better to return an error instead of crashing, but at least that is the cause.
