### ISSUE TITLE
not allow to create smart contracts

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#837]
Hi,
¿Is it possible to limit the smart contract creation to some accounts? We want only one user could create smart contracts.
And also, ¿is it possible to limit who can add peers to a quorum network?

thanks in advance

**Comment by prd-fox** [comment]
Hi,

Yes, this is now possible with the latest release (`v2.3.0`), thanks to the new smart-contract based permissioning that was added.

1. Yes, you can both limit who can create contracts and who can send transactions to existing contracts.
2. You can limit which organisations are part of the network, but adding new nodes is handled by each organisation individually.

Please look at http://docs.goquorum.com/en/latest/Permissioning/Overview/ for more details, and if there are any outstanding questions after that, please open a new ticket :)

Note: this permissioning system is classed as a "beta release", so please only use it in a testing environment for now.

**Comment by dvgoyeneche** [comment]
As I read, in this release you can limit who can create contracts in an organization, but we need that any account coud create any contracts in the network, only the authorized one.

thanks
