### ISSUE TITLE
How does block maker chooses transactions and put them in a block ?

### ISSUE THREAD

**Issue by paliwalg** [Consensys-Incorporated/quorum#84]
In Ethereum world, the factors that decide which transaction will be added in a block depends upon when the transaction is submitted and its gas price. The transactions with higher gas price are picked first.
If the blocked is almost full then the lower price transaction can also be added into the bock.

In Quorum we have block maker and voter and there is no reward system or mining concept.
Can you please help understand how exactly it happens in Quorum.

Thanks
-Gourav

**Comment by tylobban** [comment]
Hi, Quorum sorts by Priority and Nonce. We followed the same strategy for nonce and we included priority rather than the gas price to prioritize voting  transactions:
 
https://github.com/jpmorganchase/quorum/blob/master/core/quorum/block_voting.go#L117

**Comment by paliwalg** [comment]
Thanks Tyrone, so what happens if the transaction doesn’t fit into the block because of block gas limit. Does block maker tries to fit smaller\cheaper transaction in that block ?

**Comment by tylobban** [comment]
correct:
https://github.com/jpmorganchase/quorum/blob/master/core/quorum/block_maker.go#L87

**Comment by oleiba** [comment]
Hi, what exactly is a transaction priority?
Is it determined as a configured transaction property upon its creation? If so what prevents a sender from always giving his transactions high priority?
Or is it derived from other things (such as how much time a transaction was kept out of a block) ?
