### ISSUE TITLE
Constellation, how to get the hex value of the transaction input

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#841]
¿How can I connect constellation to get the hash of a transaction input?

var Tx = require('ethereumjs-tx');
 var privateKey = new Buffer('e331b6d69882b4cb4ea581d88e0b604039a3de5967688d3dcffdd2270c0fd109', 'hex')
  var rawTx = {
   nonce: '0x00',
   gasPrice: '0x09184e72a000', 
   gasLimit: '0x2710',
   to: '0x0000000000000000000000000000000000000000', 
   value: '0x00', 
   ****// This data should be the hex value of the hash returned by Quorum's privacy transaction manager after invoking storeraw api****
   data: '0x7f7465737432000000000000000000000000000000000000000000000000000000600057'
 }
  var tx = new Tx(rawTx);
 tx.sign(privateKey);
  var serializedTx = tx.serialize();
  //console.log(serializedTx.toString('hex'));
 //f889808609184e72a00082271094000000000000000000000000000000000000000080a47f74657374320000000000000000000000000000000000000000000000000000006000571ca08a8bbf888cfa37bbf0bb965423625641fc956967b81d12e23709cead01446075a01ce999b56a8a88504be365442ea61239198e23d1fce7d00fcfc5cd3b44b7215f
  web3.eth.sendRawPrivateTransaction('0x' + serializedTx.toString('hex'), {privateFor: ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]}, function(err, hash) {
   if (!err)
     console.log(hash); // "0x7f9fade1c0d57a7af66ab4ead79fade1c0d57a7af66ab4ead7c2c2eb7b11a91385"
 });

**Comment by dvgoyeneche** [comment]
How to invoke Storeraw api for constellation

**Comment by prd-fox** [comment]
Duplicate issue of https://github.com/jpmorganchase/quorum.js/issues/22, will reply there.
