### ISSUE TITLE
Unable to Add new nodes in Existing Raft Network

### ISSUE THREAD

**Issue by rajatkeshar2** [Consensys-Incorporated/quorum#842]
Hi there,

I am trying to add new node in existing Raft Cluster geting some panic while synchronizing the blocks/transactions.

**Curent Cluster Size:** 6 Nodes
**Current Numbers of Blocks in Cluster:** 4711791 

#### System information

Version: 1.8.18-stable
Git Commit: 26d381511ed249a919d87ed3de1f305e278ac29b
Quorum Version: 2.2.5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.9.7
Operating System: linux

#### Expected behaviour

New node(node7) should be connected in the network and sync all the blocks and transactions.

#### Actual behaviour

Node doesn't join the existing cluster. It gets connected and starts syncing but fails RPC server after synchronize all the blocks/transactions with following logs.

![image](https://user-images.githubusercontent.com/46245745/66571634-427e4b80-eb8d-11e9-88ca-e109eadfd42e.png)

I have also tried to restart node again but getting the same logs.

#### Steps to reproduce the behaviour

1. Create a new node.
2. add this new Node to RAFT cluster using raft.addPeer.
3. add peers by using admin.addPeer.
4. Starting new node.

After starting the node It is syncing all the blocks/transactions, When all the blocks and transactions are synced RPC server is breaked and getting the above logs.

Please let me know how can I resolve this Issue.

**Comment by jbhurat** [comment]
Hi @rajatkeshar2, can you provide your `geth` startup options and gensis config

**Comment by rajatkeshar2** [comment]
Hi @jbhurat, Thanks for reply. 

**genesis.json file:**

{
  "alloc": {
    "8c0e9dde25ec2e611817b7b6abd2d38b6adce379": {"balance": "1000000000000000000000000000"},
    "d0c8afe5dc81082b4d6bf8a576c45d01d4682132": {"balance": "1000000000000000000000000000"},
    "5991512bd1860ff5d447d0a224e0a26a596460c6": {"balance": "1000000000000000000000000000"},
    "1e2bd31d65917b083d697c68d79362d4fc654010": {"balance": "1000000000000000000000000000"},
    "7317608e09e0f2fea0aa624b50546a4f73c856c4": {"balance": "1000000000000000000000000000"}
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "config": {
    "homesteadBlock": 0,
    "byzantiumBlock": 1,
    "chainId": 12,
    "eip150Block": 1,
    "eip155Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip158Block": 1,
    "isQuorum":true
  },
  "difficulty": "0x02BC",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x2540BE3FF",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "nonce": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}

**geth startup options:**

ARGS="--nodiscover --verbosity 5 --networkid $NETWORK_ID --raft --raftjoinexisting $RAFT_ID --rpc --rpcaddr 0.0.0.0 --rpcapi raft,admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints"

PRIVATE_CONFIG=node/tesseraConfig/tm.ipc nohup geth --datadir node $ARGS --raftport 22004 --rpcport 22000 --port 22001 --unlock '0x04db945c34db4c869962efdcead3186ba5d06635' --password password.txt 2>>logs/${node}.log &

**Comment by jbhurat** [comment]
I tried reproducing the issue with the above configuration with a little over 10,000 blocks and the new node sync'd just fine. I see that in your network there are 4711791 blocks, I am trying to go upto similar height and see if I can reproduce it.

**Comment by rajatkeshar2** [comment]
Hi @jbhurat, This Issue is occurring when the network is having more than 1.5-2.0M block .

**Comment by jbhurat** [comment]
Hi @rajatkeshar2, I tried to create a network as close to yours to reproduce the issue. I created a 6 node raft cluster and generated 1.8M blocks. I then added the 7th node by following the instructions mentioned in [adding additional node](https://docs.goquorum.com/en/latest/Getting%20Started/Creating-A-Network-From-Scratch/#adding-additional-node). The 7th sync'd just fine and I was able to create more blocks and see that the block propagated to the new node as well.

Did you check the above link and let me know if you followed the instructions mentioned there

**Comment by jbhurat** [comment]
Can you confirm if the issue doesn't happen at low block heights. Also, is it reproducible by you every time

**Comment by rajatkeshar2** [comment]
Hi @jbhurat, we are following the same process for adding a new node as you have shared the above link.
Issue is not happening at the low block height It only happens when the block height is more than 2.0M. I have created two networks and this issue is reproducing in both of them when we have higher numbers of blocks in network.

**Comment by melihbirim** [comment]
I had the same problem with a new node joining the network in RAFT consensus when  RAM of newly added node can't stand the block height and try to use swap. Would be good if you increase your RAM and try again. Also you can try to use --gcmode archive and --syncmode fast if you are not using private transactions.

**Comment by jbhurat** [comment]
Hi @rajatkeshar2, I tried with over 2.2M blocks but still could not reproduce the issue. The new node was able to sync just fine and new blocks were created and propagated just fine. Can you write down the steps you are taking to add the new node. Also, can you check if the new node has enough resources and is not running out of resources when syncing

**Comment by rajatkeshar2** [comment]
Hi @jbhurat, we are using 8 GB of RAM configuration and following the same steps for node configuration as you have shared the link.
1. generateKeyPair
2. createAccount
3. generateEnode and configuring inside static-nodes.json
4. generateTesseraConfig
5. generateRaftId => raft.addPeer
6. addPeers
7. Init datadir with genesis.json
8. starting node.

**geth startup options:**

ARGS="--nodiscover --verbosity 5 --networkid $NETWORK_ID --raft --raftjoinexisting $RAFT_ID --rpc --rpcaddr 0.0.0.0 --rpcapi raft,admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints"

PRIVATE_CONFIG=node/tesseraConfig/tm.ipc nohup geth --datadir node $ARGS --raftport 22004 --rpcport 22000 --port 22001 --unlock '0x04db945c34db4c869962efdcead3186ba5d06635' --password password.txt 2>>logs/${node}.log &

Initially everything is working fine syncing all the blocks are fine but, after syncing all the blocks the above crashes is happning.
And crashes is not happens when we have low blocks in the network.

**Comment by jbhurat** [comment]
Hi @rajatkeshar2, I have so far been unable to reproduce the issue you are facing. Are there any other error messages before `request index is older than the existing snapshot`. Is it possible to upload the complete log file of this node

**Comment by rajatkeshar2** [comment]
Hi @jbhurat, I have attached log file.
[node8.log](https://github.com/jpmorganchase/quorum/files/3793335/node8.log)

**Comment by jbhurat** [comment]
Hi @rajatkeshar2 thanks for the logs. I can see that the log snapshot and the applied raft state is out of sync which is causing the issue. Is it possible to delete the raft directories from your data directory and see if that helps.

**Comment by rajatkeshar2** [comment]
Hi @jbhurat , thanks for the support. I think there was some cache problem. I could be able to resolve this issue by increasing the hardware configuration, RAM size from 8GB to 16GB and  2CPU to 4CPU. After increasing the hardware configuration I am able to sync all the blocks/transactions without any issue.
Thanks

**Comment by jbhurat** [comment]
Glad it worked for you after increasing the hardware configuration. I am marking this ticket as resolved
