### ISSUE TITLE
invalid opcode 0x1c

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#846]
Hi there,

We get invalid opcode 0x1c in our transactions.  Any idea?

Thanks!

**Comment by SatpalSandhu61** [comment]
That opcode is a recent addition to geth in the Constantinople release. You need to add the following to your genesis to enable Constantinople `"constantinopleBlock":0`.

**Comment by fixanoid** [comment]
And reinit the chain after adding it to the genesis.

**Comment by dvgoyeneche** [comment]
is it possible to change the genesis after 8000 blocks?

**Comment by fixanoid** [comment]
Yes. Modify the genesis, shut down the nodes, rerun geth init on each node
and finally start them back up.

**Comment by dvgoyeneche** [comment]
Thanks, you can close this thread
