### ISSUE TITLE
Logs in private transactions (using tessera)

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#847]
Hi there,

We are using tessera as privacy manager, we execute a transaction that emits logs.
In the transaction details we don´t get any log

Is this normal?

**Comment by fixanoid** [comment]
@dvgoyeneche the logs should be available on the participating nodes. Can you share details of what you are trying to do? Thanks

**Comment by fixanoid** [comment]
@dvgoyeneche please reopen if this is still relevant. Thanks!
