### ISSUE TITLE
deploy private contract

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#848]
Hi there,

Imagine we have 3 quorum nodes and we deploy a contract private for this 3 nodes.
After that, we add a 4th node in the network.
¿What can we do in this 4th node to execute the private contract we deployed previously?

thanks in advance

**Comment by fixanoid** [comment]
Hey @dvgoyeneche at the moment, it is not possible to share an existing private contract with a new participant, tho a feature enabling this is likely to be released by year end.

At the moment, our recommendation is to destroy the previous contract and re-create it with new participants list.
