### ISSUE TITLE
Two minters possible in a 3-node network in Raft resulting in fork

### ISSUE THREAD

**Issue by humannyty** [Consensys-Incorporated/quorum#852]
#### System information

Geth
Version: 1.8.18-stable
Git Commit: c894c2d
Quorum Version: 2.2.5
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.12
Operating System: linux

#### Expected behaviour
Forks should never be possible in Raft. If a node gets partitioned away from the other two nodes in a 3-node network then we expect it to be unable to mint blocks. 

#### Actual behaviour
When one of the nodes got partitioned, it lags behind the other nodes, as expected. However, submitting transactions to the partitioned node still results in blocks being minted. The other two nodes also continue to mint blocks. Thus, we end up with two minters. Blocks produced by the partitioned node are rejected by the other nodes with the error message ```` Someone else mined invalid block; ignoring block=f6f431…283a64 ````. 

We believe this may be a consequence of speculative minting combined with unfortunate interleaving of messages caused by temporary network partitions.

#### Steps to reproduce the behaviour
We are currently trying to reproduce this; we have observed this once in production at a fairly high block height (~36000).

#### Backtrace
We do not have detailed logs for the point of divergence but after they have diverged, the following error is printed repeatedly:
````
2098 INFO [10-14|08:56:50.606|raft/persistence.go:53]                 persisted the latest applied index       index=35988
2099 INFO [10-14|08:56:50.606|raft/minter.go:139]                     Handling InvalidRaftOrdering             invalid block=f6f431…283a64 current head=81b94e…4f5bc8
2100 INFO [10-14|08:56:50.606|raft/minter.go:146]                     Someone else mined invalid block; ignoring block=f6f431…283a64
````

**Comment by humannyty** [comment]
Possibly linked to issue #850

**Comment by jpmsam** [comment]
Correct, we are investigating both to confirm.

**Comment by zzy96** [comment]
Hi @Mansoor-AR 

> Forks should never be possible in Raft. If a node gets partitioned away from the other two nodes in a 3-node network then we expect it to be unable to mint blocks.

In our Raft docs, we explained [a race scenario](https://docs.goquorum.com/en/latest/Consensus/raft/#chain-extension-races-and-correctness) when it is possible to have two minters at the same time. However, only one minter's block will be accepted and the other will be ignored as `Non-extending block` & `Handling InvalidRaftOrdering`. Therefore, this is as expected.

There is indeed an issue around Raft node is hanging under high transaction load. After that, some of its raft entries are not applied after restart. This leads to issues like forking/ raft applied is out of range. We will find a fix for that.

**Comment by humannyty** [comment]
Hi @zzy96, thanks for the reply but this is not a similar case as the race scenario you reference. In this case we observed both minters confirming blocks (including increasing the blockNumber returned by web3.eth.blockNumber). I thought that this is not expected: speculative blocks shouldn't affect the blockNumber, right?

**Comment by zzy96** [comment]
Yes you are right. Speculative blocks will not affect `blockNumber`. Block is updated only through `InsertChain` which comes from actual raft entries. The description looks like the network is actually partitioned and the problem is not only two minters but two raft leaders :cold_sweat:

May I check a few things:

* Is the network under heavy load?
* Is any node ever hanged and restarted?
* Is there any raft leadership change log?

**Comment by robinbryce** [comment]
PI think the best we can say for this incidence is 'probably yes' to all.
* heavy load: yes probably, any attempt to exec into the quorum pod was fairly sluggish (~1-5s).
* hanged / restarted: restarted yes, on purpose with the goal of observing leadership change. hanged not that we saw at the time.
* is there any raft leadership change log ? Observed at the time but now lost :-(

We don't have great/any logs. But @Mansoor-AR and I caught this 'live' and at that time we deliberately restarted the partitioned verifier. It became 'a' minter. We then restarted the original minter and it remained the minter. Both 'minters' extended their chains. The check for minter status, via geth attach geth.ipc on each node, was scripted but there was a small (~1s ish) window between asking each respective node its raft.role due to how unresponsive the cluster was in general at that time.

**Comment by zzy96** [comment]
Thanks for the information. One point I feel confusing is why a verifier can become a minter after restart... If that node still connects to others, it should never be elected as leader and start minting. If it doesn't have the connection, it will also not get enough votes. I think I need more information from you like raft leadership change logs after the node restarted to understand the issue.

Also, may I know how do you send transactions to node, through geth console or RPC endpoint?

**Comment by robinbryce** [comment]
Transactions are sent to the rpc end point. I've added curated restart logs to #850 I can upload a tar ball of everything we have if you like.

**Comment by humannyty** [comment]
We have observed another case of this. The logs that @robinbryce added to #850 show a node minting 7 blocks that are different from the other two nodes in a 3-node network. The relevant logs are here: https://github.com/jpmorganchase/quorum/issues/850#issuecomment-543233011
We are not sure yet if #852 and #850 represent two different issues or are the same but being instantiated differently.

**Comment by humannyty** [comment]
I have observed this issue again, this time in a 5 node network. I think I may have pinpointed this to incorrect packing of transactions in a block. At the time of the fork, the forked node simply ends up packing more transactions into the block than the other nodes. Then, for some reason, it refuses to discard its block. 
I have the live forked network running for the next few hours. Please let me know in case you want me to run some diagnostics.

**Comment by humannyty** [comment]
Another fork in the 5-node network. Summary: 1 node creates a block x with _many_ transactions while the other 4 nodes mine blocks x to x+4000 with one transaction in each block (the latter is representative of our workload and what we roughly expect to see). Then, instead of rolling back block x, the forked node continues mining for **many hours** without noticing that it has been forked. 
We have detailed logs available (output of eth.getBlock) for all blocks from the fork onwards in case you need to see them.
Could it be that the consensus is being done on transactions and not on blocks? This is the opposite of what the Quourum Raft docs say but would explain this weird forking

**Comment by jbhurat** [comment]
Hi @Mansoor-AR, can you please post the logs. Also, is it possible to get access to the network.

**Comment by humannyty** [comment]
Hi @jbhurat here are the logs: [Drive](https://drive.google.com/file/d/1AqgDY1h_0Y55jh-QnRE-Z7Z20Il9YxvV/view?usp=sharing)
As you will see there, the s2 node forks at block number 117131; nodes s1 and s0 are in sync.
Could you please email support AT jitsuin.com ? We can discuss how to get you connected to our network there.

**Comment by jbhurat** [comment]
Thanks @Mansoor-AR for the `eth.getBlock()` output from the 3 nodes. Is it also possible to send the `geth` logs for these 3 nodes as well. 
I also sent an email to the support to get access to the network. It would be great if you could provide that.

**Comment by humannyty** [comment]
@jbhurat We'll get back to you soon. We think we also have a somewhat reproducible way of inducing the fork. Details should be with you tomorrow.

**Comment by zzy96** [comment]
@Mansoor-AR Please try with the latest master and see if it is running fine.

**Comment by humannyty** [comment]
Hi @zzy96 when is the next release coming? We have some reservations about switching to Master but can do if the release is some ways away. Thanks for all the help!

**Comment by zzy96** [comment]
> Hi @zzy96 when is the next release coming? We have some reservations about switching to Master but can do if the release is some ways away. Thanks for all the help!

It will be soon. Perhaps within this week.

**Comment by robinbryce** [comment]
Just to close the loop, we have been running almost continuously since taking this fix and quorum has been rock solid. Thanks very much.
