### ISSUE TITLE
Stuck in "Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s'

### ISSUE THREAD

**Issue by ghb-1234** [Consensys-Incorporated/quorum#857]
I use quorumengineering/quorum:2.2.5  and  quorumengineering/tessera:0.10.0 to start up 3 quorum nodes with istanbul consensus  in centos7.  It run wery well at the beginning, after sometime it can't generate block,  seems to suck in someplace, geth console output:  "**Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s** "
The static-nodes.json、tessera-config.json、istanbul-genese.json file in below：
[qdata.zip](https://github.com/jpmorganchase/quorum/files/3738576/qdata.zip)
Some screenshot here:
geth log：
![p1](https://user-images.githubusercontent.com/19897979/66998820-7f0af380-f107-11e9-9741-bba1ab8dccfa.png)
geth console：
![p2](https://user-images.githubusercontent.com/19897979/66998872-96e27780-f107-11e9-8847-93f02484be7f.png)
![p3](https://user-images.githubusercontent.com/19897979/66998889-9a75fe80-f107-11e9-8168-15d89b3f8764.png)
![p4](https://user-images.githubusercontent.com/19897979/66998902-9fd34900-f107-11e9-93d2-048559099c96.png)
I can't figure out what happened,  @prd-fox  @jbhurat

**Comment by zzy96** [comment]
Can you check if the other two nodes are healthy and running? Looks like it cannot get confirmations from all 3 nodes for block 13 and stuck in `Catch up round`.

Also, it is recommended to use 3f+1 nodes since a 3 nodes network doesn't prevent any Byzantine Failure.

**Comment by jbhurat** [comment]
Hi @im-Angry, as @zzy96 suggested, looks like 1 or more nodes are not healthy. Can you check if they are healthy and there is a connectivity between those. As in a 3 node network node failure (byzantine node) is not tolerated. Please plan to have atleast 4 nodes which can tolerate a failure of 1 node

**Comment by ghb-1234** [comment]
The other two nodes are running and healthy, but they once both printed **TRACE[10-17|08:41:44.845] Dial error   task="staticdial 056b815a57d67aaf 10.233.92.92:21000"  err="dial tcp 10.233.92.92:21000: connect: connection refused"** in geth log, did this cause the istanbul consensus broken ?

**Comment by zzy96** [comment]
If a node loses connection to others, the network will not be able to reach consensus. Please check if `admin.peers` return something for all nodes.
