### ISSUE TITLE
modify block generation time in quorum with IBFT

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#861]
Hi there,

¿How can we configure quorum to set the block generation time?  (by time or by transacions)

Thanks in advance

**Comment by prd-fox** [comment]
Hello,

You may set `--istanbul.blockperiod <time in seconds>` for the block generation period. Make sure that all nodes have the same value for this, even non-validator nodes, as it is used in the consensus to determine if a block is valid, not just the generation time.

If setting a value of 10 seconds or higher, please also set the IBFT timeout period to be higher, with `--istanbul.requesttimeout <number of milliseconds>`.

See here for a reference to this information: http://docs.goquorum.com/en/latest/Consensus/ibft/ibft-parameters/
