### ISSUE TITLE
quorum --permissioned flag files

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#862]
Hi there,

¿Is it mandatory to have in all our nodes the files static-nodes.json, permission-config.json and permissioned-nodes.json?

In a new node who wants to join the network, ¿which files must we copy?

Thanks in advance

**Comment by SatpalSandhu61** [comment]
The permission-config.json file is only needed if you are using smart contract based permissions. See docs [here](http://docs.goquorum.com/en/latest/Permissioning/Overview/).

The permissioned-nodes.json is only needed if you have enabled permissioning using the `--permissioned` command line flag. See docs [here](http://docs.goquorum.com/en/latest/Getting%20Started/running/#permissioned-networks).

If you want to add a new node then follow the instructions [here](http://docs.goquorum.com/en/latest/Getting%20Started/Creating-A-Network-From-Scratch/) for the relevant consensus mechanism you are using.

**Comment by SatpalSandhu61** [comment]
Can I suggest that you ask general questions like this on our Slack forum?
They are usually easier to answer in a chat context and you'll get a much quicker response.
Also, in many cases you'll find that the question has already been asked and answered.

You can join the Quorum workspace on Slack by using the following link:
https://clh7rniov2.execute-api.us-east-1.amazonaws.com/Express/

Thanks.
