### ISSUE TITLE
Permission service APIs returning null data upon restart of the node 

### ISSUE THREAD

**Issue by vsmk98** [Consensys-Incorporated/quorum#865]
#### System information

Geth version: Quorum 2.3.0

OS & Version: Linux/OSX

#### Expected behaviour
When starting the node with new permissions feature, sometimes it's observed the permission apis (e.g. `quorumPermission.orgList` or `quorumPermission.nodeList` or `quorumPermission.acctList`) does not display any data. This is observed intermittently

#### Actual behaviour
The apis should display proper data as per the permissions model

#### Steps to reproduce the behaviour
Bring up the node in IBFT consensus and with new permissions feature. Once the node is up and running with new permissions feature, restart the network.

**Comment by zzy96** [comment]
PR was merged.
