### ISSUE TITLE
error in debug.traceTransaction 

### ISSUE THREAD

**Issue by minggo1981** [Consensys-Incorporated/quorum#867]
#### System information

Geth version: `geth 2.2.5`

OS & Version: Centos 7

#### Actual behaviour
debug.traceTransaction("0x8fa2d94942c557604b0aecfedc19faa3b86be6f490ffc020d054955d3f9ade6f",{tracer:"callTracer"})
{
  error: "VM in read-only mode. Mutating opcode prohibited",
  from: "0xcfda975d9e9562608b277d293eceb37b8aaf112b",
  gas: "0x1411e",
  gasUsed: "0x1411e",
  input: "0x5d9ec2100000000000000000000000000000000000000000000000000000000000000001",
  time: "6.61275ms",
  to: "0xb05f72ef477853aebfd93cf76c118bdb887996a3",
  type: "CALL",
  value: "0x0"
}

**Comment by zzy96** [comment]
Hi @minggo1981 

This error means you are trying to update a public contract's state from a private transaction. Please check your actual transaction.

**Comment by prd-fox** [comment]
Creating and updating the `simplestorage` contract, then tracing it gives the same output, when it should succeed.
