### ISSUE TITLE
ethclient: "invalid hex log data" when using FilterLogs

### ISSUE THREAD

**Issue by stevenroose** [Consensys-Incorporated/quorum#87]
https://github.com/ethereum/go-ethereum/issues/3328

Also affects Quorum. Geth fixed it, could we cat a backport? Thanks

**Comment by patrickmn** [comment]
Would you like to take a stab at a PR?

**Comment by stevenroose** [comment]
I prefer not to. I guess it makes sense to await v1.6 and then try to
rebase Quorum to it. For now I could do with the same patch that fixed this
error before (see my comment on the issue).
