### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0x7855fb]

### ISSUE THREAD

**Issue by kumarsatish2012** [Consensys-Incorporated/quorum#870]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth version`

OS & Version: Windows/Linux/OSX

Branch, Commit Hash or Release: `git status`

#### Backtrace

````
[backtrace]
````

**Comment by SatpalSandhu61** [comment]
In order to assist with investigation, please populate **all** the details in the issue description above.

**Comment by fixanoid** [comment]
Please open a new ticket with sufficient details. Thanks.
