### ISSUE TITLE
Multiple nodes in Quorum for fault-tolerance

### ISSUE THREAD

**Issue by AhirBudhnya** [Consensys-Incorporated/quorum#874]
Hello there,

Is there any documentation to state how can we have redundant nodes configured in Quorum network so that even if a single node goes down, the data in blockchain is still retrievable by the app?

Thanks

**Comment by jpmsam** [comment]
Nodes are replicated so the app should be able to read the state from any of the available nodes. We'll be working on documenting a configuration for the private transaction manager but that isn't Quorum specific.
Please join our slack channel for any other questions.

**Comment by AhirBudhnya** [comment]
Kindly let me know the link to the slack channel.

**Comment by SatpalSandhu61** [comment]
You can join using this link: https://clh7rniov2.execute-api.us-east-1.amazonaws.com/Express/

**Comment by AhirBudhnya** [comment]
Thanks for the link.
