### ISSUE TITLE
https connection to unlockAccount (web3)

### ISSUE THREAD

**Issue by dvgoyeneche** [Consensys-Incorporated/quorum#878]
Hi there,
We are using web3 in a machine to send transactions to a quorum node. First of all we need to unlock the account in the quorum node using a password. We invoke web3.eth.personal.unlockAccount typing a password.
Is This password sent in plain text from our machine to the quorum node? How can we secure this connection?

thanks in advance

**Comment by jbhurat** [comment]
Hi @dvgoyeneche, we are currently working on supporting _https_ for rpc api's and this should be released in an upcoming release. 
You can also front the _geth_ nodes with a reverse proxy and terminate ssl on the proxy

**Comment by jbhurat** [comment]
Closing this issue for now. Please open another issue if you have any other concerns
