### ISSUE TITLE
Failed RLPx handshake

### ISSUE THREAD

**Issue by lifenglibao** [Consensys-Incorporated/quorum#879]
Hi there,

#### System information
CPUs: 2
Memory: 8GB
Harddisk: 50GB

Geth version: `geth version`
1.8.18-stable-f8091444

OS & Version: Windows/Linux/OSX
Ubuntu 18.04.3 LTS

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
i have 3 nodes (A,B,C),  these 3 nodes should be able to connect to each others, but now, A,B can do trx with each other, C node always can not receive trx, and block number is 0, can see these 3 nodes in admin.peers.

#### Steps to reproduce the behaviour

![image](https://user-images.githubusercontent.com/6213184/68934250-4aa35980-07d1-11ea-9fd9-cedd488c7d65.png)

![image](https://user-images.githubusercontent.com/6213184/68934282-5f7fed00-07d1-11ea-88b0-1f0bb6880948.png)

---------start.sh----------
ARGS="--gcmode archive --nodiscover --verbosity 5 --networkid $NETWORK_ID --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --ws --wsaddr 0.0.0.0 --wsapi db,eth,net,web3,personal,txpool,admin --emitcheckpoints $QUORUM_GETH_ARGS"
PRIVATE_CONFIG=data/tm.ipc nohup geth --datadir data $ARGS --permissioned --raftport 7117 --rpcport 8200 --port 8107 --wsport 8201 --wsorigins "*" --unlock 0 --password passwords.txt 2>>data/logs/geth.log &

is anything wrong with my setting?
#### Backtrace

````
[backtrace]
````

**Comment by jbhurat** [comment]
Hi @lifenglibao, can you paste your `genesis.json` and `geth` startup arguments for all the 3 nodes

**Comment by lifenglibao** [comment]
> Hi @lifenglibao, can you paste your `genesis.json` and `geth` startup arguments for all the 3 nodes

Hi,here is my genesis.json file
![image](https://user-images.githubusercontent.com/6213184/69004052-cc1cf800-0947-11ea-9acd-10c78286cef1.png)

here is my geth startup file

```
#!/bin/bash
set -u
set -e

function usage() {
  echo ""
  echo "Usage:"
  echo "    $0 [tessera | tessera-remote | constellation] [--tesseraOptions \"options for Tessera start script\"]"
  echo ""
  echo "Where:"
  echo "    tessera | tessera-remote | constellation (default = tessera): specifies which privacy implementation to use"
  echo "    --tesseraOptions: allows additional options as documented in tessera-start.sh usage which is shown below:"
  echo ""
  ./tessera-start.sh --help
  exit -1
}

privacyImpl=tessera
tesseraOptions=
while (( "$#" )); do
    case "$1" in
        tessera)
            privacyImpl=tessera
            shift
            ;;
        constellation)
            privacyImpl=constellation
            shift
            ;;
        tessera-remote)
            privacyImpl="tessera-remote"
            shift
            ;;
        --tesseraOptions)
            tesseraOptions=$2
            shift 2
            ;;
        --help)
            shift
            usage
            ;;
        *)
            echo "Error: Unsupported command line parameter $1"
            usage
            ;;
    esac
done

NETWORK_ID=$(cat genesis.json | tr -d '\r' | grep chainId | awk -F " " '{print $2}' | awk -F "," '{print $1}')

if [ $NETWORK_ID -eq 1 ]
then
	echo "  Quorum should not be run with a chainId of 1 (Ethereum mainnet)"
    echo "  please set the chainId in the genensis.json to another value "
	echo "  1337 is the recommend ChainId for Geth private clients."
fi

if [ "$privacyImpl" == "tessera" ]; then
  echo "[*] Starting Tessera nodes"
  ./tessera-start.sh ${tesseraOptions}
elif [ "$privacyImpl" == "constellation" ]; then
  echo "[*] Starting Constellation nodes"
  ./constellation-start.sh
elif [ "$privacyImpl" == "tessera-remote" ]; then
  echo "[*] Starting tessera nodes"
  ./tessera-start-remote.sh ${tesseraOptions}
else
  echo "Unsupported privacy implementation: ${privacyImpl}"
  usage
fi

echo "[*] Starting Ethereum nodes with ChainID and NetworkId of $NETWORK_ID"
QUORUM_GETH_ARGS=${QUORUM_GETH_ARGS:-}
set -v
ARGS="--gcmode archive --nodiscover --verbosity 5 --networkid $NETWORK_ID --raft --rpc --rpcaddr 0.0.0.0 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --ws --wsaddr 0.0.0.0 --wsapi db,eth,net,web3,personal,txpool,admin --emitcheckpoints $QUORUM_GETH_ARGS"
PRIVATE_CONFIG=data/tm.ipc nohup geth --datadir data $ARGS --permissioned --raftport 7117 --rpcport 8200 --port 8107 --wsport 8201 --wsorigins "*" --unlock 0 --password passwords.txt 2>>data/logs/geth.log &
set +v

echo
echo "Node configured. See 'data/logs' for logs, and run e.g. 'geth attach data/geth.ipc' to attach to the Geth node."
echo "To test sending a private transaction from Node to other Node, run './runscript.sh private-contract.js'"

exit 0

```

**Comment by lifenglibao** [comment]
all 3 nodes are using same genesis.json and startup file.

**Comment by jbhurat** [comment]
Hi @lifenglibao, thanks for the info. Can you try changing the IPs specified in `static-nodes.json` and `permissioned-nodes.json` from public to IPs to local internal IPs

**Comment by jbhurat** [comment]
Hi @lifenglibao, were you able to try the above suggestion.

**Comment by lifenglibao** [comment]
> Hi @lifenglibao, were you able to try the above suggestion.

Hi, you mean change public ips to 127.0.0.1? 
eg, public ip is 123.123.123 , static-nodes.json and permissioned-nodes.json change to 127.0.0.1?

**Comment by jbhurat** [comment]
Are these nodes running in AWS or other cloud provider

**Comment by lifenglibao** [comment]
> Are these nodes running in AWS or other cloud provider

A and B node in AWS (in same server), C node not in AWS

**Comment by jbhurat** [comment]
Any reason why node C is not in AWS. Also, can you verify if the connectivity is fine between the AWS server and node C. 
Also, can you paste your `static-nodes.json` and `permissioned-nodes.json`

**Comment by lifenglibao** [comment]
> Any reason why node C is not in AWS. Also, can you verify if the connectivity is fine between the AWS server and node C.
> Also, can you paste your `static-nodes.json` and `permissioned-nodes.json`

static-node.json

```
[
  "enode://a46bf45717a1680056c325b0b163378b94ccca200b85c71eb0be78c9f867629478f1ba8d5a997b1285a44b0b4b3ea9928beeb88f7a5b3d85d503d396bdf6add8@18.141.65.41:8107?discport=0&raftport=7117",
  "enode://3c681479a13de663f050715871bd9c3920bc9e85af181933d84d6e484fe8d19bfb276b3ad3451386ea3f3593e04bd9d333e06115ca7c1ecf1a0eb1c6f32d496c@18.139.142.56:8107?discport=0&raftport=7117",
  "enode://2dd42a048be2396a31e3e4f1df502dfeefb4c9d4d92d10d561d74e6ab0763738ae9d93e9da46e1ed02daa4bffa31c632de1744880fe6e135902117c3c954243b@52.163.231.173:8107?discport=0&raftport=7117"
]
```

permissioned-nodes.json same with static-node.json

**Comment by lifenglibao** [comment]
> Any reason why node C is not in AWS. Also, can you verify if the connectivity is fine between the AWS server and node C.
> Also, can you paste your `static-nodes.json` and `permissioned-nodes.json`

the reason why node C is not in AWS, because node C is others company's node.

**Comment by jbhurat** [comment]
Thanks @lifenglibao for the info, I think the issue could be network related. Can you confirm if node C can see the nodes running on AWS. Also, can you post `admin.peers` output from all the 3 nodes

**Comment by jbhurat** [comment]
We also noticed that the IP/ports are accessible to us. Is it Ok for us to connect to the geth console and debug

**Comment by lifenglibao** [comment]
> Thanks @lifenglibao for the info, I think the issue could be network related. Can you confirm if node C can see the nodes running on AWS. Also, can you post `admin.peers` output from all the 3 nodes

here are C node admin.peers

```
[{
    caps: ["eth/62", "eth/63"],
    enode: "enode://3c681479a13de663f050715871bd9c3920bc9e85af181933d84d6e484fe8d19bfb276b3ad3451386ea3f3593e04bd9d333e06115ca7c1ecf1a0eb1c6f32d496c@18.139.142.56:60536",
    id: "b6fbcc9eafedbed4f05d2b9c6154e380a80355e40270cd35e58737993216364c",
    name: "Geth/v1.8.18-stable-f8091444(quorum-v2.3.0)/linux-amd64/go1.11",
    network: {
      inbound: true,
      localAddress: "10.0.0.4:8107",
      remoteAddress: "18.139.142.56:60536",
      static: false,
      trusted: false
    },
    protocols: {
      eth: {
        difficulty: 120334602224,
        head: "0x55e131a03cb5f58fbe0864439d053def403701373e572713df04880b8479fa0e",
        version: 63
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    enode: "enode://a46bf45717a1680056c325b0b163378b94ccca200b85c71eb0be78c9f867629478f1ba8d5a997b1285a44b0b4b3ea9928beeb88f7a5b3d85d503d396bdf6add8@18.141.65.41:37552",
    id: "d7fd8ffff7835d04cf892e10b59300b76b390c94f744e9dcd7ea878161ffeb53",
    name: "Geth/v1.8.18-stable-f8091444(quorum-v2.3.0)/linux-amd64/go1.11",
    network: {
      inbound: true,
      localAddress: "10.0.0.4:8107",
      remoteAddress: "18.141.65.41:37552",
      static: false,
      trusted: false
    },
    protocols: {
      eth: {
        difficulty: 120334602224,
        head: "0x55e131a03cb5f58fbe0864439d053def403701373e572713df04880b8479fa0e",
        version: 63
      }
    }
}]

```

A node admin peers

```
[{
    caps: ["eth/63"],
    enode: "enode://2dd42a048be2396a31e3e4f1df502dfeefb4c9d4d92d10d561d74e6ab0763738ae9d93e9da46e1ed02daa4bffa31c632de1744880fe6e135902117c3c954243b@52.163.231.173:8107?discport=0&raftport=7117",
    id: "5255e67dd0eaa94bb7eed55e9a163d2695992878e1a708c801ea489cc8190581",
    name: "Geth/v1.8.18-stable-f8091444(quorum-v2.3.0)/linux-amd64/go1.11",
    network: {
      inbound: false,
      localAddress: "172.168.0.135:60536",
      remoteAddress: "52.163.231.173:8107",
      static: true,
      trusted: false
    },
    protocols: {
      eth: {
        difficulty: 815808419621,
        head: "0xd28280add2f81f4a6a4404eb374a3fb4501b80f4ffb48dd255de439de5cd4898",
        version: 63
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    enode: "enode://a46bf45717a1680056c325b0b163378b94ccca200b85c71eb0be78c9f867629478f1ba8d5a997b1285a44b0b4b3ea9928beeb88f7a5b3d85d503d396bdf6add8@18.141.65.41:52376",
    id: "d7fd8ffff7835d04cf892e10b59300b76b390c94f744e9dcd7ea878161ffeb53",
    name: "Geth/v1.8.18-stable-f8091444(quorum-v2.3.0)/linux-amd64/go1.11",
    network: {
      inbound: true,
      localAddress: "172.168.0.135:8107",
      remoteAddress: "18.141.65.41:52376",
      static: false,
      trusted: false
    },
    protocols: {
      eth: {
        difficulty: 120334602224,
        head: "0x55e131a03cb5f58fbe0864439d053def403701373e572713df04880b8479fa0e",
        version: 63
      }
    }
}]
```

B node admin peers

```
[{
    caps: ["eth/63"],
    enode: "enode://2dd42a048be2396a31e3e4f1df502dfeefb4c9d4d92d10d561d74e6ab0763738ae9d93e9da46e1ed02daa4bffa31c632de1744880fe6e135902117c3c954243b@52.163.231.173:8107?discport=0&raftport=7117",
    id: "5255e67dd0eaa94bb7eed55e9a163d2695992878e1a708c801ea489cc8190581",
    name: "Geth/v1.8.18-stable-f8091444(quorum-v2.3.0)/linux-amd64/go1.11",
    network: {
      inbound: false,
      localAddress: "172.168.0.18:37552",
      remoteAddress: "52.163.231.173:8107",
      static: true,
      trusted: false
    },
    protocols: {
      eth: {
        difficulty: 1239658055163,
        head: "0x22a052a8831521d4ab647264faa215d3d40d1f8175f5b301792b44369ee95c1c",
        version: 63
      }
    }
}, {
    caps: ["eth/62", "eth/63"],
    enode: "enode://3c681479a13de663f050715871bd9c3920bc9e85af181933d84d6e484fe8d19bfb276b3ad3451386ea3f3593e04bd9d333e06115ca7c1ecf1a0eb1c6f32d496c@18.139.142.56:8107?discport=0&raftport=7117",
    id: "b6fbcc9eafedbed4f05d2b9c6154e380a80355e40270cd35e58737993216364c",
    name: "Geth/v1.8.18-stable-f8091444(quorum-v2.3.0)/linux-amd64/go1.11",
    network: {
      inbound: false,
      localAddress: "172.168.0.18:52376",
      remoteAddress: "18.139.142.56:8107",
      static: true,
      trusted: false
    },
    protocols: {
      eth: {
        difficulty: 120334602224,
        head: "0x55e131a03cb5f58fbe0864439d053def403701373e572713df04880b8479fa0e",
        version: 63
      }
    }
}]

```

**Comment by lifenglibao** [comment]
now i found when i go to geth console, have many block into our node, should not be like this i think.
`blockNumber: 93036,`

and when i deploy a contract, show me

`err creating contract Error: insufficient funds for gas * price + value`

**Comment by jbhurat** [comment]
Thanks for the latest `admin.peers` output from the 3 nodes. I see that the difficulty is non-zero now on all the 3 nodes, which means that the nodes are syncing now. Can you confirm that. Also, is `err creating contract Error: insufficient funds for gas * price + value` a new issue that you are seeing now on all the 3 nodes

**Comment by lifenglibao** [comment]
> Thanks for the latest `admin.peers` output from the 3 nodes. I see that the difficulty is non-zero now on all the 3 nodes, which means that the nodes are syncing now. Can you confirm that. Also, is `err creating contract Error: insufficient funds for gas * price + value` a new issue that you are seeing now on all the 3 nodes

Hi, the 3 nodes all are ok now, i don't know why, i used to clean up the db and raft state.

**Comment by jbhurat** [comment]
Hi @lifenglibao, glad to hear that the network is working fine. It would be great if you could let us know if there was anything else that was done here, other than cleaning up the db and raft state. 

I am closing this ticket. Please open a new ticket if you have any other issues
