### ISSUE TITLE
How to query bootnode to get its enode?

### ISSUE THREAD

**Issue by jaguarg** [Consensys-Incorporated/quorum#88]
Hi, 

I am looking for a way to query the bootnode to get its enode ? 

#### System information

Geth version: `geth version`
Version: 1.5.0-unstable

OS & Version: Windows/Linux/OSX
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)

Branch, Commit Hash or Release: `git status`
HEAD detached at v1.0.2

#### Backtrace

````
[backtrace]
````

**Comment by hermanjunge** [comment]
You can't, it is supposed to be its `private key`. The only thing you can do is a terminal dump of the `nodekey` files, or see the command option in the machine with `ps aux`.

Can you provide us more info of your use case to help you better?

**Comment by ghost** [comment]
Did you try from the console?

```
 admin.nodeInfo.enode
```

**Comment by tylobban** [comment]
hi @jaguarg, did you make progress here? Check out [this ](https://github.com/jpmorganchase/quorum/blob/master/docs/running.md#setup-bootnode)information on bootnodes which may help.

**Comment by jaguarg** [comment]
Hi @hermanjunge , 
I would like to try to run  `admin.nodeInfo.enode`

How would I go about a connecting a geth console to the bootnode ? 

Thx

**Comment by tylobban** [comment]
Hi @jaguar, that isn't possible.  If you are just trying to get the bootnode enode url then follow the instructions from my previous comment.  You can also see [this ](https://github.com/ethereum/go-ethereum/wiki/Setting-up-private-network-or-local-cluster#setup-bootnode)page for further info on bootnodes.
