### ISSUE TITLE
What if the nodes run out of space?

### ISSUE THREAD

**Issue by michelpf** [Consensys-Incorporated/quorum#888]
Hi there,

We are planning run on production a project, and a interesting scenario came to us.

Imagining in the future our nodes run out of space, what is the best approach to scale that? 

The straightforward solution, from my team, is to create new nodes and deploy new contracts to the new nodes and run transactions specifically on them. But there are other ways to deal with that?

Thank you so much.

**Comment by fixanoid** [comment]
Hi @michelpf this is a common scenario you need to monitor for. Generally, people set up monitoring systems to alert them when space and memory drop to critical so you could take action.

In terms of replication, any node on the same chain will contain the same contracts and info as part of being on the same blockchain, minus private transactions and state. For that, please read our documentation https://docs.goquorum.com/ in detail -- ptm configurations allows for replicating DBs or replicating all messages to a fail-over node. Thanks!
