### ISSUE TITLE
i use we3j-quorum send private tx in muti thread,some tx will  never back

### ISSUE THREAD

**Issue by bigstar119** [Consensys-Incorporated/quorum#89]
[test.zip](https://github.com/jpmorganchase/quorum/files/905088/test.zip)
[fdQuorumChain.zip](https://github.com/jpmorganchase/quorum/files/905091/fdQuorumChain.zip)

#### System information

Geth version: `geth version`
quorum1.1.0
constellation0.0.1
OS & Version: Windows/Linux/OSX
ubuntu14

#### Expected behaviour
i use we3j-quorum send private txs in muti thread,i think every tx will be done and give right result

#### Actual behaviour
i use we3j-quorum send private tx in muti thread,some tx will  never back.
#### Steps to reproduce the behaviour

i think this problem may caused by the tx`s nonce,but i make the nonce property empty,i think quorum will deal with the nonce for me..
test.zip is my java testcase please see the com.neusoft.demo.testcase.SimpleStorageTestCase.increate()
fdQuorumChain.zip is my private chain set

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
Hi @bigstar119, this looks to be related to the upstream geth [issue ](https://github.com/ethereum/go-ethereum/issues/2950) around duplicate nonces.  We have seen this in high throughput scenarios.  As a work around, you could either try sending transactions single threaded from multiple accounts, or you can manage the nonce incrementing yourself by setting the nonce when [sending](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_sendtransaction) the transaction.  Please let us know if either of those work?

**Comment by bigstar119** [comment]
hi, i follow your advice.but only sending transactions single threaded from multiple accounts is good. manage the nonce myself is not work ,and  if two application use the same account to send tx no one can manage the nonce Correctly. the nonce made me headache in mutithread scenarios. wish this bug can fixed near futrue..  
and also  is quorum support send private RawTransaction now ? because make a lot of account and unlock them on the node it's too troublesome!!!

**Comment by patrickmn** [comment]
Not currently, but it should be a small change. I've created an issue to track it: https://github.com/jpmorganchase/quorum/issues/90

**Comment by patrickmn** [comment]
The nonce issue should be fixed as of Quorum 2.0.0
