### ISSUE TITLE
Quorum node on restart points to block 0

### ISSUE THREAD

**Issue by geethagurram21** [Consensys-Incorporated/quorum#891]
Geth version:  Geth/v1.8.18-stable-16bfe64d(quorum-v2.2.4)

OS & Version: Linux

####**Expected behaviour**

After node restarts should point to the latest block

####**Actual behaviour**

After node restarts node points to block 0 but the node contains details of the latest block in the network
![Screenshot from 2019-11-25 13-41-13](https://user-images.githubusercontent.com/49491353/69523220-550be300-0f89-11ea-8061-402df8815bed.png)
This image shows the data contained in block number 793

but eth.blockNumber  gives result 0.

**Comment by geethagurram21** [comment]
The genesis file is attached below.
[genesis.json.docx](https://github.com/jpmorganchase/quorum/files/3885434/genesis.json.docx)

**Comment by zzy96** [comment]
Hi @geethagurram21

I assume you are shutting down the node non-gracefully and running raft in `gcmode=full`. It is fixed in v2.2.5 https://github.com/jpmorganchase/quorum/pull/727. Please upgrade.

**Comment by geethagurram21** [comment]
Thank you,
gcmode=full works well and also the issue is sorted in the latest release of Quorum
