### ISSUE TITLE
"make all" fails

### ISSUE THREAD

**Issue by lyonnee** [Consensys-Incorporated/quorum#909]
OS & Version: OSX

nipoerdeMacBook-Pro:quorum nipoer$ make all
build/env.sh go run build/ci.go install
build/ci.go:61:2: use of internal package github.com/ethereum/go-ethereum/internal/build not allowed
make: *** [all] Error 1

**Comment by SatpalSandhu61** [comment]
You need to ensure that the quorum code is cloned into a directory with the correct path under your $GOROOT, so that Go imports work correctly, i.e. the code should be checked out to: `$GOPATH/src/github.com/ethereum/go-ethereum/`.

**Comment by lyonnee** [comment]
> You need to ensure that the quorum code is cloned into a directory with the correct path under your $GOROOT, so that Go imports work correctly, i.e. the code should be checked out to: `$GOPATH/src/github.com/ethereum/go-ethereum/`.

My gopath path is configured properly，and I can input this command to open the project directory。
`cd $GOPATH/src/github.com/ethereum/go-ethereum/`.

**Comment by zzy96** [comment]
Hi @LyonNee, can you check your go version? v1.11.13 would be the best fit for Quorum now.

**Comment by LyonNee** [comment]
nipoerdeMacBook-Pro:build nipoer$ go version
go version go1.13.4 darwin/amd64

**Comment by lyonnee** [comment]
> Hi @LyonNee, can you check your go version? v1.11.13 would be the best fit for Quorum now.

nipoerdeMacBook-Pro:build nipoer$ go version
go version go1.13.4 darwin/amd64

**Comment by zzy96** [comment]
Please downgrade to go 1.11.x and try again. Quorum currently does not support build for higher go version.

**Comment by lyonnee** [comment]
> Please downgrade to go 1.11.x and try again. Quorum currently does not support build for higher go version.

Now use 1.11.13 version solved just an error，but also have a new problems。
`nipoerdeMacBook-Pro:quorum nipoer$ make all
build/env.sh go run build/ci.go install
util.go:168: package listing failed: exit status 1
build github.com/ethereum/go-ethereum/cmd/bootnode: cannot find module for path github.com/coreos/go-systemd/journal`

**Comment by lyonnee** [comment]
I think in the readme should prompt developers needed to use the go version.

**Comment by zzy96** [comment]
Can you make sure no local changes in your Quorum repository? `github.com/coreos/go-systemd/journal` should sit in the vendor folder. If this still doesn't work, please give the Quorum version you are using as well.

---

Update: Actually I tried locally on OSX and both go 1.11.13 and 1.13.5 can successfully build Quorum.

**Comment by davidpatalejos** [comment]
Actually I have the same problem on (Linux ubuntu 18.04). I try to do make all command and I have an error. I have checked my go version and it is 1.11.13
My error 

--util.go:45: exit status 2
exit status 1
Makefile:29: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by lyonnee** [comment]
> Can you make sure no local changes in your Quorum repository? `github.com/coreos/go-systemd/journal` should sit in the vendor folder. If this still doesn't work, please give the Quorum version you are using as well.
> 
> Update: Actually I tried locally on OSX and both go 1.11.13 and 1.13.5 can successfully build Quorum.

I input the command to get on the making of the latest version,and use the default branch.
`git clone https://github.com/jpmorganchase/quorum.git`

**Comment by lyonnee** [comment]
> Can you make sure no local changes in your Quorum repository? `github.com/coreos/go-systemd/journal` should sit in the vendor folder. If this still doesn't work, please give the Quorum version you are using as well.
> 
> Update: Actually I tried locally on OSX and both go 1.11.13 and 1.13.5 can successfully build Quorum.

你是中国人吗？能给个微信号不或者qq？

**Comment by zzy96** [comment]
> > Can you make sure no local changes in your Quorum repository? `github.com/coreos/go-systemd/journal` should sit in the vendor folder. If this still doesn't work, please give the Quorum version you are using as well.
> > Update: Actually I tried locally on OSX and both go 1.11.13 and 1.13.5 can successfully build Quorum.
> 
> 你是中国人吗？能给个微信号不或者qq？

可以用中文。`make all`不成功挺奇怪的，你可以尝试build一下Ethereum的repo吗，用他们release/1.8的branch

**Comment by lyonnee** [comment]
> > > Can you make sure no local changes in your Quorum repository? `github.com/coreos/go-systemd/journal` should sit in the vendor folder. If this still doesn't work, please give the Quorum version you are using as well.
> > > Update: Actually I tried locally on OSX and both go 1.11.13 and 1.13.5 can successfully build Quorum.
> > 
> > 
> > 你是中国人吗？能给个微信号不或者qq？
> 
> 可以用中文。`make all`不成功挺奇怪的，你可以尝试build一下Ethereum的repo吗，用他们release/1.8的branch

go-ethereum这个项目编译没有任何问题

**Comment by lyonnee** [comment]
> > > > Can you make sure no local changes in your Quorum repository? `github.com/coreos/go-systemd/journal` should sit in the vendor folder. If this still doesn't work, please give the Quorum version you are using as well.
> > > > Update: Actually I tried locally on OSX and both go 1.11.13 and 1.13.5 can successfully build Quorum.
> > > 
> > > 
> > > 你是中国人吗？能给个微信号不或者qq？
> > 
> > 
> > 可以用中文。`make all`不成功挺奇怪的，你可以尝试build一下Ethereum的repo吗，用他们release/1.8的branch
> 
> go-ethereum这个项目编译没有任何问题



> > > Can you make sure no local changes in your Quorum repository? `github.com/coreos/go-systemd/journal` should sit in the vendor folder. If this still doesn't work, please give the Quorum version you are using as well.
> > > Update: Actually I tried locally on OSX and both go 1.11.13 and 1.13.5 can successfully build Quorum.
> > 
> > 
> > 你是中国人吗？能给个微信号不或者qq？
> 
> 可以用中文。`make all`不成功挺奇怪的，你可以尝试build一下Ethereum的repo吗，用他们release/1.8的branch

我并没有找打你说的1.8版本，我现在用的release/2.4.  go-ethereum用的是release/1.9.9的.
go-ethereum执行make all没有报错。  但是quorum还是编译不过 ，还是刚刚的报错
`nipoerdeMacBook-Pro:quorum-2.4.0 nipoer$ make all
fatal: not a git repository (or any of the parent directories): .git
build/env.sh go run build/ci.go install
util.go:168: package listing failed: exit status 1
build github.com/ethereum/go-ethereum/cmd/bootnode: cannot find module for path github.com/coreos/go-systemd/journal
exit status 1
make: *** [all] Error 1`

**Comment by zzy96** [comment]
@LyonNee

release/1.8是指go-ethereum的版本，目前Quorum还是基于geth 1.8的，所以想确认一下你编译go-ethereum 1.8是否也存在问题。
从报错的这个module path来说coreos确实是Quorum因为raft而引入的，我目前没有办法重现你遇到的问题，不过有一些建议你可以尝试一下：
1）把报错的`github.com/coreos`从Quorum的vendor里面移到GOPATH的src下
2）只运行`make geth`因为你应该也不太需要编译其他的工具

**Comment by zzy96** [comment]
> Actually I have the same problem on (Linux ubuntu 18.04). I try to do make all command and I have an error. I have checked my go version and it is 1.11.13
> My error
> 
> --util.go:45: exit status 2
> exit status 1
> Makefile:29: recipe for target 'all' failed
> make: *** [all] Error 1

This looks more like a make/gcc problem. Can you try building go-ethereum 1.8 and see if you have the same error?

**Comment by davidpatalejos** [comment]
> > Actually I have the same problem on (Linux ubuntu 18.04). I try to do make all command and I have an error. I have checked my go version and it is 1.11.13
> > My error
> > --util.go:45: exit status 2
> > exit status 1
> > Makefile:29: recipe for target 'all' failed
> > make: *** [all] Error 1
> 
> This looks more like a make/gcc problem. Can you try building go-ethereum 1.8 and see if you have the same error?

I have solved the problem now. I used this [link](https://stackoverflow.com/questions/43580131/exec-gcc-executable-file-not-found-in-path-when-trying-go-build ) and applied the command "apt-get install build-essential".

Thank you. Maybe it could be the same solution to fix the first problem.

**Comment by lyonnee** [comment]
> @LyonNee
> 
> release/1.8是指go-ethereum的版本，目前Quorum还是基于geth 1.8的，所以想确认一下你编译go-ethereum 1.8是否也存在问题。
> 从报错的这个module path来说coreos确实是Quorum因为raft而引入的，我目前没有办法重现你遇到的问题，不过有一些建议你可以尝试一下：
> 1）把报错的`github.com/coreos`从Quorum的vendor里面移到GOPATH的src下
> 2）只运行`make geth`因为你应该也不太需要编译其他的工具

我的1.8版本的go-ethereum都编译失败了，
`build github.com/ethereum/go-ethereum/build: cannot find module for path github.com/Azure/azure-storage-go
make: *** [all] Error 1`
而且这个库我没有找到

**Comment by lyonnee** [comment]
> @LyonNee
> 
> release/1.8是指go-ethereum的版本，目前Quorum还是基于geth 1.8的，所以想确认一下你编译go-ethereum 1.8是否也存在问题。
> 从报错的这个module path来说coreos确实是Quorum因为raft而引入的，我目前没有办法重现你遇到的问题，不过有一些建议你可以尝试一下：
> 1）把报错的`github.com/coreos`从Quorum的vendor里面移到GOPATH的src下
> 2）只运行`make geth`因为你应该也不太需要编译其他的工具

第一个尝试：我现在已经把`github.com/coreos`这个目录copy出来，现在的路径是`$GOPATH/src/github.com/coreos`
但是编译还是有问题。
第二个尝试：'make geth'编译还是编译不过，报错信息还是一样
`nipoerdeMacBook-Pro:quorum nipoer$ make geth
build/env.sh go run build/ci.go install ./cmd/geth
usr/local/go/bin/go install -ldflags -X main.gitCommit=877f85208e1db88e25398553a8a65c894032771c -s -v ./cmd/geth
build github.com/ethereum/go-ethereum/cmd/geth: cannot find module for path github.com/coreos/go-systemd/journal
util.go:45: exit status 1
exit status 1
make: *** [geth] Error 1`

**Comment by zzy96** [comment]
## Summary

For the issue reporter, suggested the following methods but no success:
- build the project under `$GOPATH/src/github.com/ethereum/go-ethereum/` or under a non-`$GOPATH`
- build use both go 1.11.13 & 1.13.4
- build after copy the error path `github.com/coreos/go-systemd/journal` to `$GOPATH/src`
- build after `unset GOBIN`

Here is the snapshot of issue reporter's go env
```
nipoerdeMacBook-Pro:go_project nipoer$ ls $GOPATH
bin	pkg	src
nipoerdeMacBook-Pro:go_project nipoer$ go env
GOARCH="amd64"
GOBIN="/Users/nipoer/Documents/go_project/bin"
GOCACHE="/Users/nipoer/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/nipoer/Documents/go_project"
GOPROXY="https://goproxy.io"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
```

Also, go-ethereum release/1.8 branch build is failing for the issue reporter. Therefore, it shouldn't be a Quorum specific issue.

---

Update: This issue has been resolved by unset GOPROXY.

**Comment by lyonnee** [comment]
> ## Summary
> For the issue reporter, suggested the following methods but no success:
> 
> * build the project under `$GOPATH/src/github.com/ethereum/go-ethereum/` or under a non-`$GOPATH`
> * build use both go 1.11.13 & 1.13.4
> * build after copy the error path `github.com/coreos/go-systemd/journal` to `$GOPATH/src`
> * build after `unset GOBIN`
> 
> Here is the snapshot of issue reporter's go env
> 
> ```
> nipoerdeMacBook-Pro:go_project nipoer$ ls $GOPATH
> bin	pkg	src
> nipoerdeMacBook-Pro:go_project nipoer$ go env
> GOARCH="amd64"
> GOBIN="/Users/nipoer/Documents/go_project/bin"
> GOCACHE="/Users/nipoer/Library/Caches/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="darwin"
> GOOS="darwin"
> GOPATH="/Users/nipoer/Documents/go_project"
> GOPROXY="https://goproxy.io"
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD=""
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> ```
> 
> Also, go-ethereum release/1.8 branch build is failing for the issue reporter. Therefore, it shouldn't be a Quorum specific issue.

谢谢， 我的问题已经解决了，是我自己之前设置过的goproxy.io的代理导致找不到对应的包。我删除了我的代理，就能正常使用了

**Comment by icodezjb** [comment]
my go version 1.11.13 or 1.13.5
```
git clone https://github.com/jpmorganchase/quorum.git
cd quorum
make all
```
the error:
```
build/env.sh go run build/ci.go install ./cmd/geth
build/ci.go:62:2: use of internal package github.com/ethereum/go-ethereum/internal/build not allowed
Makefile:15: recipe for target 'geth' failed
make: *** [geth] Error 1
```

i have solved it by this cmd

`go env -w GO111MODULE=off`

**Comment by icodezjb** [comment]
Best Practise (for goland IDE build indices)

os: deepin linux
go: version > 1.11
ide: goland

set `GO111MODULE=off` in goland and console

```bash
mkdir -p $GOPATH/src/github.com/ethereum
cd $GOPATH/src/github.com/ethereum/
git clone https://github.com/jpmorganchase/quorum.git go-ethereum 
cd go-ethereum
make all
```

last just open goland
