### ISSUE TITLE
user create Account send tx meets Account doesn't exist problem

### ISSUE THREAD

**Issue by bigstar119** [Consensys-Incorporated/quorum#91]
#### System information

Geth version: `geth version`
quorum1.1.0
constellation0.0.1
OS & Version: Windows/Linux/OSX
ubuntu14
Branch, Commit Hash or Release: `git status`

#### Expected behaviour
user create Account  if unlocked  can send private tx Successfully

#### Actual behaviour
user create Account and unlocked, but can not  send private tx . i get the error is **Account doesn't exist**

#### Steps to reproduce the behaviour
in genesis.json I define a account eg.
"0x6661517bd48a3aa90bd03f802ca0ccc734da835e": {
      "balance": "1000000000000000000000000000"
    }
i put this account in the node1 and unlocked the account on node start.after that i use we3j-Quorum send a private tx, the fromAddress is "0x6661517bd48a3aa90bd03f802ca0ccc734da835e". this is good.

next  i use the personal.newAccount("neusoft") and personal.unlockAccount("0x7764291432de4c361d6a806f0c9f9638d6565852","neusoft") command ,create and unlocked another account ,this account is a user create Account. then i send a private tx, the fromAddress is "0x7764291432de4c361d6a806f0c9f9638d6565852" this time i got an error message is:
**Account doesn't exist.**

why the error??  is that means Quorum do not support user create Account? 

#### Backtrace

````
[backtrace]
````

**Comment by coeniebeyers** [comment]
what is the ether balance of "0x7764291432de4c361d6a806f0c9f9638d6565852"? I've found that if there isn't enough ether at the from address you get the "Account doesn't exist error"

**Comment by bigstar119** [comment]
hi. you are right . i send some ether to account "0x7764291432de4c361d6a806f0c9f9638d6565852" every thing fine ,thank you for the answer.

**Comment by rynobey** [comment]
I see that this issue is closed, but is this the desired behaviour? Perhaps the error message could be updated? It looks like this was fixed in go-ethereum (issue #824).
