### ISSUE TITLE
How could quorum prevent P2P connections from other nodes?

### ISSUE THREAD

**Issue by luoyhang003** [Consensys-Incorporated/quorum#915]
I have already known about the quorum node permissioning strategy implemented by smart contract. But I am still confused about P2P communications. How could quorum prevent P2P connections from other nodes?

Cause we know P2P protocol is an open protocol. How could node refuse connections from other IPs or machines? I think the smart contract cannot achieve this goal.

**Comment by fixanoid** [comment]
Hi @luoyhang003 when permission system is enabled, before any connection is established a check occurs if the connecting node is permitted to access the chain. See https://github.com/jpmorganchase/quorum/blob/master/p2p/permissions.go

**Comment by luoyhang003** [comment]
Thx. @fixanoid 

I saw a function called `doEncHandshake` at https://github.com/jpmorganchase/quorum/blob/85e22579951107af91fce755be536942a76e34d1/p2p/server.go#L229

Maybe this function could verify the signature signed by the other node's private key before the connection established. Is that right?

Could this connection check apply to RPC accessing control? In other word, is there any strategies Quorum supports to permit or ban a RPC request?
