### ISSUE TITLE
3 node network setup issues

### ISSUE THREAD

**Issue by HolyMichael** [Consensys-Incorporated/quorum#916]
#### System information

Geth version: 1.8.18-stable-5cb92ceb

OS & Version: Linux

quorum:2.3.0

#### Expected behaviour

Deploying a 3 node network, expecting the nodes to communicate and begin building and propagating blocks

#### Actual behaviour

The nodes get stuck doing voting rounds

#### Steps to reproduce the behaviour

Use docker to contain the nodes.
Use istanbul-tools to generate the files for 3 nodes
Generate a permissioned-nodes.json file listing all the nodes
Distribute the generated files accordingly trough the nodes
Initiate geth
`geth --datadir setup/data init setup/genesis.json`
Launch geth with the following arguments
```
            nohup geth --datadir setup/data \
              --permissioned \
              --verbosity 5 \
              --networkid 1337 \
              --rpc \
              --nodiscover \
              --rpcaddr 0.0.0.0 \
              --rpcport 8545 \
              --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,istanbul,quorum \
              --emitcheckpoints --istanbul.blockperiod 1 --mine --minerthreads 1 --syncmode full \
              --port 30300
```

Additional information added as attachment:
[node2 info.txt](https://github.com/jpmorganchase/quorum/files/3972979/node2.info.txt)
[node0 info.txt](https://github.com/jpmorganchase/quorum/files/3972980/node0.info.txt)
[node0.log](https://github.com/jpmorganchase/quorum/files/3972981/node0.log)
[node1.log](https://github.com/jpmorganchase/quorum/files/3972982/node1.log)
[node2.log](https://github.com/jpmorganchase/quorum/files/3972983/node2.log)
[node1 info.txt](https://github.com/jpmorganchase/quorum/files/3972984/node1.info.txt)
[genesis.txt](https://github.com/jpmorganchase/quorum/files/3973008/genesis.txt)

EDIT [1]:
[docker-compose.txt](https://github.com/jpmorganchase/quorum/files/3973411/docker-compose.txt)

**Comment by prd-fox** [comment]
Hey. According to the files provided, the peers are not connecting to each other. Are you able to provide your docker commands also?

**Comment by HolyMichael** [comment]
Hello, here it goes, I'll also edit it into the initial post
[docker-compose.txt](https://github.com/jpmorganchase/quorum/files/3973397/docker-compose.txt)

**Comment by jbhurat** [comment]
Hi @HolyMichael, as discussed in slack, I setup a network with a similar configuration as yours and it works just fine. I have attached my configuration files 


[docker-compose1.yml.txt](https://github.com/jpmorganchase/quorum/files/3975284/docker-compose1.yml.txt)
[docker-compose2.yml.txt](https://github.com/jpmorganchase/quorum/files/3975285/docker-compose2.yml.txt)
[docker-compose3.yml.txt](https://github.com/jpmorganchase/quorum/files/3975286/docker-compose3.yml.txt)
[istanbul-genesis.json.txt](https://github.com/jpmorganchase/quorum/files/3975292/istanbul-genesis.json.txt)
[permissioned-nodes.json.txt](https://github.com/jpmorganchase/quorum/files/3975294/permissioned-nodes.json.txt)

and starting my containers using `docker-compose -f docker-compose1.yml -p node1 up -d` followed by `docker-compose -f docker-compose2.yml -p node2 up -d` and then `docker-compose -f docker-compose3.yml -p node3 up -d`

**Comment by fixanoid** [comment]
Please reopen if the issue persists
