### ISSUE TITLE
Incorrect Usage. flag provided but not defined: -raft

### ISSUE THREAD

**Issue by psaren** [Consensys-Incorporated/quorum#918]
I follow the docs [Creating-A-Network-From-Scratch#adding-privacy-transaction-manager](https://docs.goquorum.com/en/latest/Getting%20Started/Creating-A-Network-From-Scratch/#adding-privacy-transaction-manager) in step  
`9. Start your node by first creating a script as below and then starting it:`
```
$ vim startnode1.sh
... paste below commands. It will start it in the background.
#!/bin/bash
PRIVATE_CONFIG=ignore nohup geth --datadir new-node-1 --nodiscover --verbosity 5 --networkid 31337 --raft --raftport 50000 --rpc --rpcaddr 0.0.0.0 --rpcport 22000 --rpcapi admin,db,eth,debug,miner,net,shh,txpool,personal,web3,quorum,raft --emitcheckpoints --port 21000 >> node.log 2>&1 &

$ chmod +x startnode1.sh 
$ ./startnode1.sh
```
and i got this error in node.log:  
`Incorrect Usage. flag provided but not defined: -raft`  
#### System information
Ubuntu 18.04.3 LTS
Geth version: `geth version`
```
$ geth version
Geth
Version: 1.9.9-stable
Git Commit: 017449971e1e9e220efcd97d3313a0e27f47003b
Architecture: amd64
Protocol Versions: [64 63]
Go Version: go1.13.4
Operating System: linux
GOPATH=
GOROOT=/build/ethereum-Bq7Cjd/.go
```
OS & Version: Windows/Linux/OSX
Ubuntu 18.04.3 LTS
Branch, Commit Hash or Release: `git status`

#### Expected behaviour
run ./startnode1.sh and work correctly!

#### Actual behaviour
run ./startnode1.sh and get incorrect message in node.log!

#### Steps to reproduce the behaviour
The docs [Creating-A-Network-From-Scratch#adding-privacy-transaction-manager](https://docs.goquorum.com/en/latest/Getting%20Started/Creating-A-Network-From-Scratch/#adding-privacy-transaction-manager) steps 1-8 is good for me!
But in step 9, i meet the error!

**Comment by zzy96** [comment]
Hi @psaren, looks like you are running Ethereum 1.9.9 geth not Quorum geth... Please check your PATH configuration.
