### ISSUE TITLE
geth restore network with import command failed

### ISSUE THREAD

**Issue by six-days** [Consensys-Incorporated/quorum#920]
Hi there,
I run a Quorum Network with ibft, then I want backup my Network useing export command,like:
& geth export enode.bin --datadir enode

with the same genesis config,i init network with command like:
& geth --datadir inode init genesis.json

then, I import the backup file with command like:
& geth import enode.bin  --datadir inode
but failed, the error message see "Actual behaviour"

#### System information

Geth version: 1.8.18-stable-51e1f635

OS & Version: OSX

#### Expected behaviour
Restore network

#### Actual behaviour
& geth import enode.bin  --datadir inode
INFO [12-26|10:28:26.663] Maximum peer count                       ETH=25 LES=0 total=25
INFO [12-26|10:28:26.671] Allocated cache and file handles         database=/Users/linjingjing/Documents/project/soft/fromscratchistanbul/enode/geth/chaindata cache=768 handles=5120
INFO [12-26|10:28:26.720] Disk storage enabled for ethash caches   dir=/Users/linjingjing/Documents/project/soft/fromscratchistanbul/enode/geth/ethash count=3
INFO [12-26|10:28:26.720] Disk storage enabled for ethash DAGs     dir=/Users/linjingjing/.ethash                                                      count=2
INFO [12-26|10:28:26.721] Loaded most recent local header          number=0 hash=386b55…1bb15a td=1 age=13h46m20s
INFO [12-26|10:28:26.721] Loaded most recent local full block      number=0 hash=386b55…1bb15a td=1 age=13h46m20s
INFO [12-26|10:28:26.721] Loaded most recent local fast block      number=0 hash=386b55…1bb15a td=1 age=13h46m20s
INFO [12-26|10:28:26.722] Importing blockchain                     file=enode.bin
ERROR[12-26|10:28:26.723] 
########## BAD BLOCK #########
Chain config: {ChainID: 10 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 IsQuorum: true Constantinople: 0 TransactionSizeLimit: 64 MaxCodeSize: 24 Engine: istanbul}

Number: 1
Hash: 0xff334828b7f34cc950c3ecd1274047702ab3d2d34bc9a4a5fb806a5cdf74ea14

Error: extra-data too long: 192 > 32
##############################
 
ERROR[12-26|10:28:26.723] Import error                             err="invalid block 31: extra-data too long: 192 > 32"
INFO [12-26|10:28:26.723] Blockchain manager stopped 
Import done in 2.058977ms.

**Comment by zzy96** [comment]
Hi @six-days,

This error is because ethash consensus is used to verify an IBFT block. Quorum does not support import chain command now due to different consensus, customized genesis, and private state.
