### ISSUE TITLE
Missing trie node error

### ISSUE THREAD

**Issue by bulgakovk** [Consensys-Incorporated/quorum#926]
#### System information

Geth version: `Geth/v1.9.10-unstable-3bb6815f-20191225/darwin-amd64/go1.13.5`

OS & Version: OSX

Branch, Commit Hash or Release: `e9e69d6e`

#### Expected behaviour
`state.New()` should return a new state from a given block hash when `full` database directory provided. 

#### Actual behaviour
Getting `panic: missing trie node <block hash>`

#### Steps to reproduce the behaviour
I completely synced a tesnet chain with following command: `geth --datadir /Users/kirill/geth/data --syncmode full --goerli`. Then started this util: https://github.com/bulgakovk/go-ethereum/commit/8ee6485ec0a432e0e8ed4acee38ce6d8055fc492. The code contains latest know at that moment hash but I also tried with genesis.

#### Backtrace

````
[backtrace]
````

**Comment by prd-fox** [comment]
Hi @bulgakovk 

The version stated there is for the the upstream repository, not for Quorum.

Did you mean to create an issue there, or did you try to sync the Goerli Testnet using Quorum?

**Comment by bulgakovk** [comment]
@prd-fox Hey sorry for confusing you. Looks like I created an issue in a wrong tab.
