### ISSUE TITLE
Approach for upgrading geth for Quorum

### ISSUE THREAD

**Issue by davebryson** [Consensys-Incorporated/quorum#93]
Currently there are multiple touch points between the quorum code base and geth, making upgrading to the latest geth a bit of a task.   Are there any plans to streamline this in the future (code refactor, etc...) to reduce the amount of work needed to stay inline with geth?  I see this as becoming increasingly important with the growing EntEth Alliance interest in quorum.

**Comment by tylobban** [comment]
Hi @davebryson, absolutely.  We are currently in the process of determining the geth release to upgrade to and are in discussions around what will make future upgrades easier.  Of course all input from the community is welcome!

**Comment by davebryson** [comment]
@tylobban Thanks for the response.  Good to hear.   I'm working my way through the codebase to get a better understanding of all the touch points.  Obviously if geth had a bit more of pluggable approach for consensus, things would be much simpler.  Are there current factors with the code base that prevent migrating to 1.6?

**Comment by tylobban** [comment]
@davebryson our focus has been on getting some enhancements into the current Quorum codebase (you would have seen a bunch of PRs being merged recently) before upgrading geth so honestly we still need to do a full review of 1.6, but we know that it has breaking API changes so effort required for sure. BTW, not sure if you've seen [this](https://github.com/ethereum/go-ethereum/pull/3817 ) pluggable consensus PR that's coming?

**Comment by davebryson** [comment]
@tylobban Wow! I missed that recent geth change.  Very nice!
