### ISSUE TITLE
Bad block error when syncing blocks on new nodes after increasing maxCodeSize

### ISSUE THREAD

**Issue by vdamle** [Consensys-Incorporated/quorum#942]
#### System information

Geth version: `1.8.18`
OS & Version: Linux
Branch, Commit Hash or Release: Quorum 2.3.0

#### Expected behaviour

New nodes added to a chain which is reconfigured to run with `maxCodeSize: 128` should be able to sync blocks from existing nodes, which may have had failed contract deployment txn due to size exceeding the previous `maxCodeSize`

#### Actual behaviour

New nodes reject blocks from existing nodes which have a failed contract deployment txn with `BAD BLOCK` error with reason: `Error: invalid gas used`

#### Steps to reproduce the behaviour

* Start a quorum chain with default `maxCodeSize` (no overriding genesis config)
* Deploy contract which exceeds the code size - this is rejected by nodes as expected
* Reconfigure the chain by adding `maxCodeSize` in genesis config (ex: 128kb) and `geth init` all nodes to reinitialize genesis. Now the chain runs fine and can accept contracts upto the new `maxCodeSize`
* Add a new node to the chain. This node will be configured with `maxCodeSize: 128` from the start. When this node syncs blocks from the chain, it rejects the block with the failed contract deployment. Below is an example log and transaction receipt for the failed txn:

```
ERROR[02-10|16:37:32.196]
########## BAD BLOCK #########
Chain config: {ChainID: 649600883 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 IsQuorum: true Constantinople: <nil> Engine: istanbul}
Number: 12851
Hash: 0x6f6aa1ed44525cae2fa02d5732238a4f5c163ec2452517f47c7b4f34021245d7
        &{[] 1 27255314 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [57 208 119 134 132 81 172 183 208 250 154 150 148 101 168 71 242 53 251 64 98 175 242 121 162 200 238 71 126 130 240 240] [194 2 89 117 123 109 202 73 192 102 247 3 153 163 232 58 73 237 193 68] 27255314}

Error: invalid gas used (remote: 505000000 local: 27255314)
```

```
> eth.getTransactionReceipt("0x39d077868451acb7d0fa9a969465a847f235fb4062aff279a2c8ee477e82f0f0")
{
  blockHash: "0x6f6aa1ed44525cae2fa02d5732238a4f5c163ec2452517f47c7b4f34021245d7",
  blockNumber: 12851,
  contractAddress: "0xc20259757b6dca49c066f70399a3e83a49edc144",
  cumulativeGasUsed: 505000000,
  from: "0x38aeb4b2ace5bce0cbda2351f7d5f7da19bc3f51",
 ...
  status: "0x0",
  to: null,
  transactionHash: "0x39d077868451acb7d0fa9a969465a847f235fb4062aff279a2c8ee477e82f0f0",
}
```

#### Backtrace

none

**Comment by vsmk98** [comment]
Hi @vdamle, I am able to reproduce this error and working on a fix. Will revert back.

**Comment by vdamle** [comment]
thanks for looking at this, @vsmk98 ! Curious to understand how you handle gas calculation in the state processor since `maxCodeSize` config does not have a block number associated with it.

**Comment by vsmk98** [comment]
Hi @vdamle . agree with you. Please refer to PR created for this. The changes add a `maxCodeSizeChangeBlock` to `genesis.json`. This will track the block number when the `maxCodeSize` was changed.

**Comment by jpmsam** [comment]
Fixed by https://github.com/jpmorganchase/quorum/pull/947
