### ISSUE TITLE
Quorum Faucet Support

### ISSUE THREAD

**Issue by zscole** [Consensys-Incorporated/quorum#948]
Basic question, but has faucet support been officially deprecated from Quorum client? If so, what's the recommended best-practice for distributing ETH within a "public" test network?

**Comment by fixanoid** [comment]
Hi @zscole. Technically, faucet remains a part of geth fork and should be working, tho we haven't tested it: https://github.com/jpmorganchase/quorum/blob/master/cmd/faucet/faucet.go

That said, implementing a basic faucet with Quorum would be straight forward -- allocate an account with a gazillion of eth and come up with a creative way to disburse it.

**Comment by jpmsam** [comment]
@zscole Faucet isn't currently supported on Quorum since it depends on the light client. We'll look into adding support in a future release so that there isn't a need to maintain account/s for distributing ether for gas.

Please feel free to post further questions to our slack channel.
