### ISSUE TITLE
How to build quorum node from source?

### ISSUE THREAD

**Issue by hejianhui** [Consensys-Incorporated/quorum#953]
Hello, how to build your project from source? I have found build guide
 https://github.com/jpmorganchase/quorum/wiki/Getting-Set-Up 

but it does not work.

You can see error information below.

And another question: In the source code, I can see go imports like 

```
 import "github.com/ethereum/go-ethereum/consensus/istanbul"
```

but there's no folder named istanbul in go-ethereum/consensus. This directory is only in quorum. So I've change project directory `jpmorganchase/quorum` into `ethereum/go-ethereum` to read source code.

What should I do if I want to compile the project successfully?
#### System information

Geth version: `latest`

OS & Version: Linux(WSL)

Branch, Commit Hash or Release: `v2.4.0`

#### Expected behaviour
make success 

#### Actual behaviour
```
build/env.sh go run build/ci.go install
build command-line-arguments: cannot load github.com/ethereum/go-ethereum/swarm/version: module github.com/ethereum/go-ethereum@latest found (v1.9.11), but does not contain package github.com/ethereum/go-ethereum/swarm/version
Makefile:29: recipe for target 'all' failed
make: *** [all] Error 1

```

#### Steps to reproduce the behaviour
```
git clone https://github.com/jpmorganchase/quorum
cd quorum
make all
```
#### Backtrace

````
[backtrace]
````

**Comment by jbhurat** [comment]
Hi @hejianhui, 
I just tried the above _Steps to reproduce the behavior_ using go version 1.11.x and it worked fine. Can you let me know what is your go version and whether `jpmorganchase/quorum` directory in `GOPATH`

**Comment by fixanoid** [comment]
Please reopen when further details are available. Thanks
