### ISSUE TITLE
Unable to init genesis with maxCodeSizeChangeBlock after upgrading to 2.5.0

### ISSUE THREAD

**Issue by vdamle** [Consensys-Incorporated/quorum#965]
#### System information

Geth version: `1.8.18`
OS & Version: Linux
Branch, Commit Hash or Release: Quorum 2.5.0

#### Expected behaviour

A node which is running with `maxCodeSize` genesis config in quorum `2.4.0` or earlier should allow the addition of `maxCodeSizeChangeBlock` and a re-init of the genesis config after upgrade to `2.5.0`, as implemented in https://github.com/jpmorganchase/quorum/pull/947

#### Actual behaviour

`geth init` fails with the error: `Fatal: Failed to write genesis block: mismatching max code size change fork block in database`

#### Steps to reproduce the behaviour

* Deploy a contract larger than default `maxCodeSize` on a Quorum node running on `2.4.0`. Deployment fails and a failed txn is included in the block
* Reconfigure a Quorum node running on `2.4.0` (for example) with `maxCodeSize:128`, restart the node and note down the block number at which the chain started again
* Deploy contract the previous contract again, deployment succeeds
* Upgrade node to `2.5.0`, attempt to reconfigure the chain with `maxCodeSizeForkBlock:<n>` with `n` being the block at which updated code size took effect. `geth init` fails with the following error:

```
INFO [04-08|21:22:42.746] Maximum peer count                       ETH=25 LES=0 total=25
INFO [04-08|21:22:42.764] Allocated cache and file handles         database=/qdata/ethereum/geth/chaindata cache=16 handles=16
INFO [04-08|21:22:43.073] Persisted trie from memory database      nodes=1 size=152.00B time=11.391µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
Fatal: Failed to write genesis block: mismatching max code size change fork block in database (have <nil>, want 16, rewindto 15)
```

#### Backtrace

N/A

**Comment by vdamle** [comment]
For a quorum node running with a version < `2.5.0` , `maxCodeSizeChangeBlock` is `nil` (unsupported configuration in `2.4.0` and earlier). This scenario is not excluded in the check for incompatibility [here](https://github.com/jpmorganchase/quorum/blob/4c9740bfaa187c12ec24a33a975c7302591be0e1/params/config.go#L410-L412)

The check, I believe, should only be made if `head` has passed a non-nil `maxCodeSizeChangeBlock`

**Comment by vsmk98** [comment]
Hi @vdamle , yes agree. The current changes only allow change of `maxCodeSizeChangeBlock` along with `maxCodeSize` in genesis. If a network has been running on `maxCodeSize` different from default, it does not allow init. Will revert back. Thanks

**Comment by vdamle** [comment]
@vsmk98 - thanks for taking a look! I have tested a fix in our pipeline and ran the upgrade with the fix for an error we hit in a customer environment. I have put out a PR for it, let me know what you think

**Comment by vdamle** [comment]
For reference, here is the chain config after upgrading from `2.4` to `2.5` (`maxCodeSizeChangeBlock` is `nil`). #966 addresses this

```
geth attach /gethipc/geth.ipc
Welcome to the Geth JavaScript console!
instance: Geth/v1.8.18-stable-806e9eaf(quorum-v2.5.0)/linux-amd64/go1.10.1
coinbase: 0x784422d8cb92661bc2b54254117e6dcc1b965008
at block: 156 (Wed, 08 Apr 2020 20:23:56 UTC)
 datadir: /qdata/ethereum
 modules: admin:1.0 debug:1.0 eth:1.0 istanbul:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0
> admin.nodeInfo
{
  enode: "enode://d4d16b00455b44e3b629ec22dce61013c0d0f246de6341de1b279d444dc146395bf4fa8b4cedc44727506a5e19376c61f581d8651e097382253c772c1fbccf53@127.0.0.1:30303?discport=0",
  enr: "0xf894b84021df0f6e0413aa5b5e1cc841268134bef51716fcd2495230c5b76abf4e22e2e60c41c55ed80fd68d2cde854022a69e092453269d5239ba223f756fb0cb4b1ed40183636170cbca88697374616e62756c40826964827634826970847f00000189736563703235366b31a103d4d16b00455b44e3b629ec22dce61013c0d0f246de6341de1b279d444dc146398374637082765f",
  id: "ab0268b17517385e74de7ad1784422d8cb92661bc2b54254117e6dcc1b965008",
  ip: "127.0.0.1",
  listenAddr: "[::]:30303",
{"alloc":{"b70e446c921cb37c747db5b6ed846fe400c114c1":{"balance":"1000000000000000000000000000"}},"coinbase":"0x0000000000000000000000000000000000000000  name: "Geth/v1.8.18-stable-806e9eaf(quorum-v2.5.0)/linux-amd64/go1.10.1",
  plugins: {},
  ports: {
    discovery: 0,
    listener: 30303
  },
  protocols: {
    istanbul: {
      config: {
        byzantiumBlock: 0,
        chainId: 592006929,
        constantinopleBlock: 0,
        eip150Block: 0,,
        eip150Hash: "0x0000000000000000000000000000000000000000000000000000000000000000",
        eip155Block: 0,
        eip158Block: 0,
        homesteadBlock: 0,
        isQuorum: true,
        istanbul: {...},
        maxCodeSize: 128,
        txnSizeLimit: 0
      },
      consensus: "istanbul",
      difficulty: 159,
      genesis: "0x247b750a3e552813503288b4630a405f38c6e82859953ca05134b9dce85db6f3",
      head: "0x165650538710321fb311cebe1b430441477ed60fcedff957b6666b2039d1c95d",
      network: 592006929
    }
  }
}
```

**Comment by vsmk98** [comment]
Changes merged with master.
