### ISSUE TITLE
Notification of failed private transactions to sender

### ISSUE THREAD

**Issue by humannyty** [Consensys-Incorporated/quorum#967]
#### System information
I have a question/concern about the consistency of state in case of private contracts using Tessera and the notification of transaction failures. 

Consider this private contract visible to Alice, Bob and Charlie, initially deployed by Alice:

```

pragma solidity ^0.6.0;

contract checkInContract {
  uint public checkins;

  constructor() public {
    checkins = 0;
  }
  function checkIn() public {
    checkins = checkins + 1;
  }
  function resetCheckIns() public {
    if(checkins < 1)
        revert();
    checkins = 0;
  }
}
```

Now, suppose Alice executes the following transactions:

```
checkinContract.checkIn({from:eth.accounts[0],privateFor:[“Bob’s key”]});
checkinContract.resetCheckIns({from:eth.accounts[0],privateFor:[“Bob’s key”,”Charlie’s key”]});
```

In this case, the second transaction would succeed for Alice and Bob but will fail for Charlie. However, Alice isn’t informed that Charlie’s execution has failed. Thus, the state of Alice and Charlie has gone out of sync. 
 
We would like to avoid such situations and inform the sender when one of the recipients is unable to process a tx. Is there an inbuilt mechanism that we can utilise for this? If not, are there standard solutions? It seems like a problem that many must have encountered before us.

This is related to issue #377 but is more specific since we only want to propagate information about failures and not ensure consistency of storage on different nodes.

#### Expected behaviour
Notification sent to Alice, and possibly Bob, about failed transaction on Charlie.

#### Actual behaviour
Charlie silently fails while Alice and Bob succeed.

#### Steps to reproduce the behaviour
Cause any transaction to revert on a subset of recipients

**Comment by jpmsam** [comment]
Hi @Mansoor-AR It is similar to #377 and currently that isn't part of the core protocol but we are looking to enhance Quorum with a configuration that allows the participants to know that the transaction failed. As of today, you can reference my suggestion https://github.com/jpmorganchase/quorum/issues/377#issuecomment-390216350 for an off-chain design and the [FAQ](http://docs.goquorum.com/en/latest/FAQ/) with two other guarantees we have 1) Tessera fails the transaction on the sender node if it doesn't receive an ack from all the other participants and 2) EVM is deterministic. As important, we don't assume that all recipients of the transaction, even to the same contract, are always the same. That is described in our [white paper.](https://github.com/jpmorganchase/quorum/blob/master/docs/Quorum%20Whitepaper%20v0.2.pdf)

**Comment by robinbryce** [comment]
What sort of priority is assigned to this enhancement ? The EVM will revert for things like array out of bounds. And revert is an ACK. This is a contract bug to be sure. But with public contracts the system inherently protects us against this - there is no divergent state. With divergent state, and specifically where privateFor recipients change from transaction to transaction, those sorts of (application) bugs could be very damaging.

To be clear, where the application needs this level of assurance, the current approach is to call eth_storageRoot for each recipient and check that the root has changed ?

**Comment by jpmsam** [comment]
> What sort of priority is assigned to this enhancement ? 

It's a priority with a few other security features. Currently targeting the release after our upstream [geth upgrade ](https://github.com/jpmorganchase/quorum/pull/960)which is in testing. 

>To be clear, where the application needs this level of assurance, the current approach is to call eth_storageRoot for each recipient and check that the root has changed ?

To check whether the root matches for all participants or not. [This project](https://github.com/miguelmartinezinf/consistency-checker) by a third party developer, not maintained by the quorum team, can be used as a starting point with caution not to disclose the parties of a contract unless that is acceptable by the use-case.

**Comment by robinbryce** [comment]
Ah, ok, Thanks for that. It will be really good to see the geth upgrade!

> To check whether the root matches for all participants or not

Does it have to match ? Isn't it likely that the private state will commonly (almost inevitably) diverge and so not match. Even if some notion of 'current values' are consistent, the path to reach those values can be different on different nodes.

If we are looking for *just* confirmation that a transaction occured on a node, what do we miss if we only check that the state root changed ?

**Comment by jpmsam** [comment]
>If we are looking for just confirmation that a transaction occured on a node, what do we miss if we only check that the state root changed ?

That works if you only care that the transaction occurred. `eth.storageRoot` allows you to check the root for a specific contract and optionally on a block. You can review our [API](http://docs.goquorum.com/en/latest/Getting%20Started/api/#json-rpc-privacy-api-reference) documentation for details.

**Comment by robinbryce** [comment]
Ok, great. Thanks very much
