### ISSUE TITLE
Extra data for IBFT

### ISSUE THREAD

**Issue by JSedlmeir92** [Consensys-Incorporated/quorum#969]
Hi there,

I noted that after release 2.5, there must have been a commit which modifies the way the extra data in the IBFT genesis block is handled. Until yesterday, I was able to successfully launch Quorum with IBFT and to deploy contracts. However, when I tried today it did not work anymore. When I checked out 685f59fb5e08bf9d26fa2b8a1effbb03355b7c4f, i.e. release 2.5, everything worked again. 

If helpful, I can share the way I generate the extra data (the tool provided in the IBFT repo did not work for me, so I wrote my own Python code...).

**Comment by jbhurat** [comment]
Hi @JSedlmeir92,

Can you let me know the commit which did not work for you. I checked out master and it worked just fine for me. Can you also post your `extradata` generated from the python code and I can verify if it is valid or not.
Also, please post your network topology and the logs and I will try to see what the issue is. 
Regarding `istanbul-tools` what issue are seeing with it. I am able to build it just fine, you can also download the binary from https://dl.bintray.com/quorumengineering/istanbul-tools/ and see if you see better results

**Comment by JSedlmeir92** [comment]
Hi Jitendra, 

 

actually I did not check which commit it was, I just cloned the current state of the repository yesterday evening. When I checked out v2.5, everything still worked, so it must be some commit since. 

 

I generate my extradata as follows (I spent a long time trying until it finally worked, it is a bit of a mess…)

 

***

 

import rlp

 

old_string = "f841"

new_string = "b841"

for i in range(0, 65):

    old_string = old_string + "80"

    new_string = new_string + "00"

 

vanity = "0x0000000000000000000000000000000000000000000000000000000000000000"

seal = []

for i in range(0, 65):

    seal.append(0x00)

 

committed_seal = []

 

validators = []

for address in addresses:

    validators.append(int("0x" + address, 16))

 

extra_data = vanity + rlp.encode([validators, seal, committed_seal]).hex()

 

extra_data = extra_data.replace(old_string, new_string)

 

***

 

For example, for 2 validators with addresses “0xbd7401337df404baf38db75985b81df7ee47eb97” and “0xe0c23e94e9534cffee5fccb7ae935da7c90ec775”, my extra data is "0x0000000000000000000000000000000000000000000000000000000000000000f86fea94bd7401337df404baf38db75985b81df7ee47eb9794e0c23e94e9534cffee5fccb7ae935da7c90ec775b8410000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0"

 

Unfortunately I did not save the geth logs, but I remember it just saying “invalid extra data”. 

 

Thanks a lot for sending the link to the Istanbul-tools binary – unfortunately, I cannot download it via wget or curl – do you know how to do this?

 

Best, 

Johannes

 

Von: Jitendra Bhurat <notifications@github.com> 
Gesendet: Freitag, 10. April 2020 15:30
An: jpmorganchase/quorum <quorum@noreply.github.com>
Cc: JSedlmeir92 <johannes.sedlmeir@fit.fraunhofer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jpmorganchase/quorum] Extra data for IBFT (#969)

 

Hi @JSedlmeir92 <https://github.com/JSedlmeir92> ,

Can you let me know the commit which did not work for you. I checked out master and it worked just fine for me. Can you also post your extradata generated from the python code and I can verify if it is valid or not.
Also, please post your network topology and the logs and I will try to see what the issue is.
Regarding istanbul-tools what issue are seeing with it. I am able to build it just fine, you can also download the binary from https://dl.bintray.com/quorumengineering/istanbul-tools/ and see if you see better results

**Comment by jbhurat** [comment]
Try downloading using wget using the following command `wget -O istanbul.tar.gz https://bintray.com/quorumengineering/istanbul-tools/download_file\?file_path\=istanbul-tools_v1.0.2_linux_amd64.tar.gz`

`invalid extra data format` error is returned when the block header is verified as part of the `istanbul` consensus. Unfortunately it is difficult to know what the issue was unless we know the `extradata` that was being verified or have access to the logs

**Comment by JSedlmeir92** [comment]
Thank you very much for the information w.r.t. the download link – it worked for me and I can confirm that I get the same extra data from the Istanbul tool as from my Python script. 

 

I just run a setup of Quorum with IBFT again with the same settings as yesterday, with the latest state of the Quorum repository. Suprisingly, now everything works again. However, I do not think it was a coincidence because I use fully automatic startup scripts with randomized accounts and I encountered the error three times yesterday so the probability that e.g. my extra data generation did not work occasionally is very small. 

 

I will run the startup from time to time anyway, so if the problem occurs again I will let you know and give you the logs from the beginning.

 

Thanks for your time and have a nice Easter 

Johannes

 

Von: Jitendra Bhurat <notifications@github.com> 
Gesendet: Freitag, 10. April 2020 20:37
An: jpmorganchase/quorum <quorum@noreply.github.com>
Cc: JSedlmeir92 <johannes.sedlmeir@fit.fraunhofer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [jpmorganchase/quorum] Extra data for IBFT (#969)

 

Try downloading using wget using the following command wget -O istanbul.tar.gz https://bintray.com/quorumengineering/istanbul-tools/download_file\?file_path\=istanbul-tools_v1.0.2_linux_amd64.tar.gz <https://bintray.com/quorumengineering/istanbul-tools/download_file/?file_path\=istanbul-tools_v1.0.2_linux_amd64.tar.gz> 

invalid extra data format error is returned when the block header is verified as part of the istanbul consensus. Unfortunately it is difficult to know what the issue was unless we know the extradata that was being verified or have access to the logs

**Comment by JSedlmeir92** [comment]
Tried again today, now it is surprisingly working again. I will let you know if the problem occurs again.
