### ISSUE TITLE
Automatically recover private transaction contents after data loss

### ISSUE THREAD

**Issue by bigstar119** [Consensys-Incorporated/quorum#97]
#### System information

Geth version: `geth version`
quorum1.1.0
constellation0.0.1
OS & Version: Windows/Linux/OSX
ubuntu14
Branch, Commit Hash or Release: `git status`

#### Expected behaviour
i test quorum`s recovery ability,i delete the quorum work dir and constellation work dir, simulate hard disk failure. i wish when i config quorum and constellation  the same as before, and connect to the net
all tx and data will recovery success

#### Actual behaviour
when i config quorum and constellation  the same as before, and connect to the net , public tx and data 
recovery success,private tx recovery failed
#### Steps to reproduce the behaviour
1. create 3 nodes , deploy a private tx between node1 and node3
2. set contract`s storedData to 11.  node1 and node3 can both read this value.node2 can not.
pragma solidity ^0.4.0;

contract simplestorage { 
    uint public storedData; 
    function simplestorage(uint initVal) { 
        storedData = initVal; 
    } 
    function set(uint x) { 
        storedData = x; 
    } 
     function increase(uint x) { 
        storedData = storedData+x; 
    } 
    function get() constant returns (uint retVal) { 
        return storedData; 
        
    } 
}

3. stop node1 ,delete node1`s quorum work dir and constellation work dir.
4. rebuild node1's  config and workdir,  start node1 wait node1 connect the net and sync block finished.
5. send a private tx from node3 ,set storedData to 12 . node3 can read result is 12. i wish node1 can read result is 12 also ,but node1 can not.
6. i think node1`s constellation can not recover private tx automatic like public tx ,so can not  read result.

#### Backtrace

````
[backtrace]
````

**Comment by patrickmn** [comment]
There is currently no such automatic recovery measure, though what you describe is exactly what we'd like to have. Currently, you should back up the constellation work dir in case of failure, or add redundancy to your transactions (e.g. always send to two constellation nodes.)

We do have as part of the Constellation API a method that asks peers to re-transmit their payloads to you, and in the near future we plan to release a tool using it, then once we are comfortable that that process is robust, it can be made automatic like you describe. (The main concern is making sure all transactions are re-transmitted, even if your peers sent hundreds of thousands or millions, and doing so in a way that doesn't burden those nodes.)

**Comment by bigstar119** [comment]
thank you for the answer. i just wish private tx and data can recover automaticly like the public tx and data,even if shit happens like hard disk failure. we only need reconfig the node and let node connect the net all tx and data will recover  as before..  i think this is a  common futrue of blockchian.

**Comment by Krish1979** [comment]
This issue of data recovery after data loss is addressed in Tessera  - our strategic privacy manager solution.
