### ISSUE TITLE
Gas Limit

### ISSUE THREAD

**Issue by rohitgkr** [Consensys-Incorporated/quorum#98]
#### System information

Geth version: `geth version`
Version: 1.5.0-unstable
OS & Version: Windows/Linux/OSX
Linux - Ubuntu
Branch, Commit Hash or Release: `git status`
6d0bd810484f4c56f7c9aebc229e1bdc56832ced
#### Expected behaviour
N/A

#### Actual behaviour
N/A

#### Steps to reproduce the behaviour
Since gas price is set to zero in Quorum per design I would like to know if there is a recommended gas limit value either based on design or experience. Gas limit in genesis block in 7nodes is quite high - 0x2FEFD800 so I believe 804247552 transactions will try to be squeezed into each block. I see a parallel here to a database page fragmentation. 

When I submit a transaction and specify from/to/value is the limit here the gas limit for the transaction? In Nethereum this is always set to a default gas limit of 90000. Should I be calling estimate gas and settings the gas limit to the returned value explicitly? If gas limit is instead the block gas limit, should I instead call getBlock("latest") and use the gas limit from the latest block to submit in the sendTransaction call? It appears that estimate gas is the way to go? Thanks.

#### Backtrace

````
[backtrace]
````

**Comment by tylobban** [comment]
hi @rohitgkr,

> if there is a recommended gas limit value either based on design or experience

This is going to be use case specific so there's no real general recommendation.  You can adjust this to your use case requirements.

> is the limit here the gas limit for the transaction?

That's right.

> It appears that estimate gas is the way to go? 

Yes. The gas limit is for the transaction, not the block. You can estimate the gas before calling or just leave it to the default gas value of 90000 (assuming your transaction doesn't require more than that).

**Comment by rohitgkr** [comment]
Thanks @tylobban.
It appears that [higher gas value ](https://github.com/ethereum/go-ethereum/issues/1590) in estimate call would help. I thought Quorum doesn't take gas price per transaction into account as there is no minimg reward scheme. However if Quorum still uses transaction gas price is it just being used as a block fragmentation criterion? So if block gas is 10K and currently 8K is the cumulative gas used by transactions in that block & a new transaction gas limit is 4K then it will be pending & go into a new block. Also it would appear that the higher the rate of block making (max time threshold) the quicker the receipt throughput. But it appears that block fragmentation will then be high and lead to longer block traversal time (using eth.filter APIs. Can you please confirm this and suggest any metrics/tips if any performance tests have been run? If not I may do some experiments at my end. Cheers.

**Comment by tylobban** [comment]
> I thought Quorum doesn't take gas price per transaction into account as there is no minimg reward scheme. However if Quorum still uses transaction gas price is it just being used as a block fragmentation criterion?

Quorum uses the gas limit as a mechanism to stop infinite execution and to limit the number of transactions that are included in one block. 

> So if block gas is 10K and currently 8K is the cumulative gas used by transactions in that block & a new transaction gas limit is 4K then it will be pending & go into a new block.

Yes.

> Also it would appear that the higher the rate of block making (max time threshold) the quicker the receipt throughput. But it appears that block fragmentation will then be high and lead to longer block traversal time (using eth.filter APIs. Can you please confirm this and suggest any metrics/tips if any performance tests have been run? If not I may do some experiments at my end

It would be great if you can run those experiments.  For very high block making rates consider using our [RAFT](https://github.com/jpmorganchase/quorum/blob/master/raft/doc.md) consensus as it only generates blocks when there are pending transactions. The block time should be adjusted based on your use case and the receipt requirements for a transaction.
