### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by danijel88** [Consensys-Incorporated/quorum#985]
Hi there,

Please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `1.9.3`

OS & Version: Windows

Branch, Commit Hash or Release: `git status`

#### process_begin: CreateProcess(NULL, git describe --tags --abbrev=0 @^, ...) failed.
Makefile:153: pipe: No error
process_begin: CreateProcess(NULL, which hub, ...) failed.
Makefile:181: pipe: No error
process_begin: CreateProcess(NULL, which jfrog, ...) failed.
Makefile:184: pipe: No error
process_begin: CreateProcess(NULL, which jq, ...) failed.
Makefile:187: pipe: No error
build/env.sh go run build/ci.go install
process_begin: CreateProcess(NULL, sh C:\Users\BoksanD\Desktop\Development\quorum\build\env.sh go run build/ci.go install, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:24: all] Error 2

#### git clone https://github.com/jpmorganchase/quorum.git
cd quorum
make all

Can someone tell me what I'm doing wrong ?

#### Backtrace

````
[backtrace]
````

**Comment by robinbryce** [comment]
I think you need to follow these instruction to build on windows natively: https://github.com/ethereum/go-ethereum/wiki/Installation-instructions-for-Windows

Othewise, try WSL. Also, try the quorum technical-support slack channel for questions like this

**Comment by fixanoid** [comment]
Hi @danijel88, per @robinbryce advice -- thats the correct way of building Quorum/geth on Windows. The other ways you may build is via quorum-examples.
