### ISSUE TITLE
Fail to send private transaction via PublicTransactionPoolAPI.SendTransaction

### ISSUE THREAD

**Issue by shiqinfeng1** [Consensys-Incorporated/quorum#986]
Hi there,

I tested the deployment of private contracts through the QUORUM NETWORK plug-in of remix, but it failed. I traced the code and found that it implements the deployment contract through PublicTransactionPoolAPI.SendTransaction. Within the function SendTransaction, it is first converted to a transaction structure by tx: = args.toTransaction (), then the transaction is set to a private transaction through SetPrivate (), and finally signed . But it failed because the transaction has not been signed before being set as a private transaction, where the V value of the transaction is nil. So, should it be set as a private transaction after signing?

PS: The code set as private transaction is as follows:
```
func (tx *Transaction) IsPrivate() bool {
	if tx.data.V == nil {     // Because V = nil, SetPrivate fails.
		return false
	}
	return tx.data.V.Uint64() == 37 || tx.data.V.Uint64() == 38 
}
func (tx *Transaction) SetPrivate() {
	if tx.IsPrivate() {
		return
	}
        ...
```

I think the correct sequence is to sign first, and then set it as a private transaction. In the signature function, chainID == 1 to determine whether it is a private transaction.

#### System information

Geth version:  all

OS & Version: OSX

Branch, Commit Hash or Release: `git status`

#### Expected behaviour
send private transaction success.

#### Actual behaviour
send private transaction fail.

#### Backtrace

````
[backtrace]
````

**Comment by zzy96** [comment]
Hi @shiqinfeng1 , `eth_sendTransaction` supports private transaction and you may validate that by sending a private transaction from geth console. Calling `SetPrivate()` before signing is not intuitive but basically it is just let the keystore wallet to decide which signer to use.

(Refer to accounts/keystore/keystore.go)
```
// SignTx signs the given transaction with the requested account.
func (ks *KeyStore) SignTx(a accounts.Account, tx *types.Transaction, chainID *big.Int) (*types.Transaction, error) {
	// Look up the key to sign with and abort if it cannot be found
	ks.mu.RLock()
	defer ks.mu.RUnlock()

	unlockedKey, found := ks.unlocked[a.Address]
	if !found {
		return nil, ErrLocked
	}

	// start quorum specific
	if tx.IsPrivate() {
		log.Info("Private transaction signing with QuorumPrivateTxSigner")
		return types.SignTx(tx, types.QuorumPrivateTxSigner{}, unlockedKey.PrivateKey)
	} // End quorum specific

	// Depending on the presence of the chain ID, sign with EIP155 or homestead
	if chainID != nil {
		return types.SignTx(tx, types.NewEIP155Signer(chainID), unlockedKey.PrivateKey)
	}
	return types.SignTx(tx, types.HomesteadSigner{}, unlockedKey.PrivateKey)
}
```

Do you see any other error message when deploying from Remix? I think there are other issues to do with the deployment failure.

**Comment by shiqinfeng1** [comment]
The error of remix is ​​that it does not follow the envisaged process and causes out of gas.
When I trace the code flow, the following log output is normal.

```
log.Debug ("sending private tx", "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
data, err = private.P.Send (input, args.PrivateFrom, args.PrivateFor)
log.Debug ("sent private tx", "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
```

But when executing the following judgment in wallet.SignTx(), tx.IsPrivate () is false.

```
if tx.IsPrivate () {
    log.Info ("Private transaction signing with QuorumPrivateTxSigner")
    return types.SignTx (tx, types.QuorumPrivateTxSigner {}, unlockedKey.PrivateKey)
} // End quorum specific
```

One of my doubts is that in  `PublicTransactionPoolAPI.SendTransaction ()` , after executing  `tx: = args.toTransaction ()` , tx.R, tx.S, tx.V are all nil, and you cannot use  `tx.SetPrivate ()`  to set private transactions . Resulting in `tx.IsPrivate () == false` .

**Comment by shiqinfeng1** [comment]
> The error of remix is ​​that it does not follow the envisaged process and causes out of gas.
> When I trace the code flow, the following log output is normal.
> 
> ```
> log.Debug ("sending private tx", "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
> data, err = private.P.Send (input, args.PrivateFrom, args.PrivateFor)
> log.Debug ("sent private tx", "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
> ```
> 
> But when executing the following judgment in wallet.SignTx(), tx.IsPrivate () is false.
> 
> ```
> if tx.IsPrivate () {
>     log.Info ("Private transaction signing with QuorumPrivateTxSigner")
>     return types.SignTx (tx, types.QuorumPrivateTxSigner {}, unlockedKey.PrivateKey)
> } // End quorum specific
> ```
> 
> One of my doubts is that in `PublicTransactionPoolAPI.SendTransaction ()` , after executing `tx: = args.toTransaction ()` , tx.R, tx.S, tx.V are all nil, and you cannot use `tx.SetPrivate ()` to set private transactions . Resulting in `tx.IsPrivate () == false` .

hi，@zzy96,  Do you mean that private transaction will be signed before replacing the payload? Then tx.Data.V has value.

**Comment by zzy96** [comment]
> The error of remix is ​​that it does not follow the envisaged process and causes out of gas.
> When I trace the code flow, the following log output is normal.
> 
> ```
> log.Debug ("sending private tx", "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
> data, err = private.P.Send (input, args.PrivateFrom, args.PrivateFor)
> log.Debug ("sent private tx", "privatefrom", args.PrivateFrom, "privatefor", args.PrivateFor)
> ```
> 
> But when executing the following judgment in wallet.SignTx(), tx.IsPrivate () is false.
> 
> ```
> if tx.IsPrivate () {
>     log.Info ("Private transaction signing with QuorumPrivateTxSigner")
>     return types.SignTx (tx, types.QuorumPrivateTxSigner {}, unlockedKey.PrivateKey)
> } // End quorum specific
> ```
> 
> One of my doubts is that in `PublicTransactionPoolAPI.SendTransaction ()` , after executing `tx: = args.toTransaction ()` , tx.R, tx.S, tx.V are all nil, and you cannot use `tx.SetPrivate ()` to set private transactions . Resulting in `tx.IsPrivate () == false` .

`tx.SetPrivate()` sets `tx.data.V` to 37 even if V is nil, so `tx.IsPrivate()` will be true after `tx.SetPrivate()` is called. If you see `tx.IsPrivate()` as false, I think most likely because `args.PrivateFor` is nil and `tx.SetPrivate()` is never called.

**Comment by bmcd** [comment]
Can we take a step back and get some info to reproduce the error:

- Version of Quorum and Tessera
- Genesis config
- Does this happen with a specific contract? Can you share contract code that has this issue?
- Does it work when deploying non-privately? (uncheck the private transaction checkbox before deploying)
- Are you manually inputing privateFrom/For into the dropdown menus or is remix pulling these public keys directly from tessera?
- What is the exact error message you see in remix?

Thanks!

**Comment by shiqinfeng1** [comment]
hi @zzy96 ,  "tx.SetPrivate() sets tx.data.V to 37 even if V is nil,"  ---- This is not to be particularly correct.  You can see the code below（in `PublicTransactionPoolAPI) SendTransaction()` )：

```
  if args.IsPrivate() {
		tx.SetPrivate()
	}
```
In my case,  `tx.SetPrivate()`  is called, because of args.IsPrivate() is true. But `tx.SetPrivate()`  sets fail, due to V is nil. You can look at the code I listed for the first time.

Because `setPrivate ()` fails,  `SignTx ()`  does not use  `types.QuorumPrivateTxSigner {}` to sign, but uses `types.HomesteadSigner {}` to sign. I want to rule out whether this cause the contract deployment failure, or there may be other reasons .

Thanks!
PS:  Are you Chinese? Maybe we can talk more about quorum, my WeChat: 15951886304. 



---------------------------------------------
hi @bmcd87，

+ Version of Quorum and Tessera
    quorum：forked from v2.5.0 
    tessera: 0.10.4 

+ Genesis config

```
{
  
  "config": {
    "homesteadBlock": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "chainId": 43882,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip158Block": 0,
    "maxCodeSize": 35,
    "maxCodeSizeChangeBlock" : 0,
    "isQuorum": true
  },
  "alloc": {
    "0x11fbb909ea0e8e0882ba86a00fb9a968e26f5656": {
      "balance": "1000000000000000000000000000"
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "difficulty": "0x0",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0xE0000000",
  "nonce": "0x0",
  "mixhash": "0x00000000000000000000000000000000000000647572616c65787365646c6578",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "timestamp": "0x00"
}
```

+ Does this happen with a specific contract? Can you share contract code that has this issue?
 Has nothing to do with the specific contract.
```
pragma solidity >=0.4.22 <0.7.0;

/**
 * @title Storage
 * @dev Store & retreive value in a variable
 */
 
contract Storage {

    uint256 number;

    event fall(uint a);
    /**
     * @dev Store value in variable
     * @param num value to store
     */
    function store(uint256 num) public {
        number = num;
    }

    /**
     * @dev Return value 
     * @return value of 'number'
     */
    function retreive() public view returns (uint256){
        return number;
    }
    fallback() external {
        emit fall(555);
        return ;
    }
}
```

+ Does it work when deploying non-privately? (uncheck the private transaction checkbox before deploying)
 it works well when deploying non-privately. 

+ Are you manually inputing privateFrom/For into the dropdown menus or is remix pulling these public keys directly from tessera?
I picked pubkey from pulling public keys.

+ What is the exact error message you see in remix?
"The contract code couldn't be stored, please check your gas limit."

Additional logs:
```
if args.IsPrivate() {
		tx.SetPrivate()
	}
	fmt.Printf("[TEMP DEBUG] After Set Transaction To Private: %v\n",tx.String())
	var chainID *big.Int
	if config := s.b.ChainConfig(); config.IsEIP155(s.b.CurrentBlock().Number()) && !tx.IsPrivate() {
		chainID = config.ChainID
	}
	// /Quorum

	signed, err := wallet.SignTx(account, tx, chainID)
	if err != nil {
		fmt.Printf("[TEMP DEBUG] SignTx Fail",err)
		return common.Hash{}, err
	}
	fmt.Printf("[TEMP DEBUG] After SignTx. signed: %v\n",signed.String())
```
output:
```
[TEMP DEBUG] After Set Transaction To Private:
	TX(8ac81fd96615b2b988f546a0ed69fcfb4e7242f3a665847f8fa50b9b6f510568)
	Contract: true
	From:     [invalid sender: invalid sig]
	To:       [contract creation]
	Nonce:    2
	GasPrice: 0x0
	GasLimit  0x989680
	Value:    0x0
	Data:     0xd53f3b10...cc4538f62dd5689
	V:        0x0
	R:        0x0
	S:        0x0
	Hex:      f84d0280839...b06a95cc4538f62dd5689808080

[TEMP DEBUG] After SignTx. signed:
	TX(0db511c2c4729cef8b6bacc20d6ab30dc00aef008ad6a701adec4feb27fe47b5)
	Contract: true
	From:     11fbb909ea0e8e0882ba86a00fb9a968e26f5656
	To:       [contract creation]
	Nonce:    2
	GasPrice: 0x0
	GasLimit  0x989680
	Value:    0x0
	Data:     0xd53f3b1062ccabde1...538f62dd5689
	V:        0x2adcd
	R:        0x58c114b82ea7866ced5611c25e05ad6a7721c42f9d611a07af5777fcb483c381
	S:        0x35ff410d2910a9d39925bc6f50e1bb4fa266ba5c97ad3d9c3b87031469d9ae21
	Hex:      f890028...b87031469d9ae21
```


```
INFO [05-06|03:06:04.104] sending private tx                       data=608060405234801561001057600080fd5b50610101806100206000396000f3fe6080604052348015600f57600080fd5b506004361060355760003560e01c80636057361d146071578063b05784b814609c576036565b5b7f49b8f12f5938921633d6bdb926ee8c5f2ebd3af8662dd2a512421753b6275f0561022b6040518082815260200191505060405180910390a1005b609a60048036036020811015608557600080fd5b810190808035906020019092919050505060b8565b005b60a260c2565b6040518082815260200191505060405180910390f35b8060008190555050565b6000805490509056fea2646970667358221220ca1f3bc73b26d4bb5cefe60143f9156aeec4877f9db4e0ddc7489706f3f72bb164736f6c63430006060033 privatefrom="4g9VDawGMK/HB6x1BpJZxnseiWZUkr3jNzucZF+oWg4=" privatefor="[rw3jsUK8DQgB5JsRRa6ygbpdTNMPLUzYabihK4ywUgc=]"
INFO [05-06|03:06:05.016] sent private tx                          data=d53f3b1062ccabde194d5e82e88477ada7bfde2660860361a075b4d280927ac85a8383ecdc83919232fbd2e1347e0932680b8d69d4bb06a95cc4538f62dd5689                                                                                                                                                                                                                                                                                                                                                                                                                                                                   privatefrom="4g9VDawGMK/HB6x1BpJZxnseiWZUkr3jNzucZF+oWg4=" privatefor="[rw3jsUK8DQgB5JsRRa6ygbpdTNMPLUzYabihK4ywUgc=]"
TRACE[05-06|03:06:05.056] Pooled new future transaction            hash=0db511…fe47b5 from=0x11fBB909EA0E8e0882Ba86a00fB9A968e26f5656 to=nil
TRACE[05-06|03:06:05.057] Promoting queued transaction             hash=0db511…fe47b5
TRACE[05-06|03:06:05.057] Promoting queued transaction             hash=0db511…fe47b5
TRACE[05-06|03:06:05.058] Broadcast transaction                    hash=0db511…fe47b5 recipients=1
INFO [05-06|03:06:05.059] VM returned with error                   err="invalid opcode 0xd5"
TRACE[05-06|03:06:05.066] Broadcast transactions                   id=7377201041fd85db conn=inbound count=1
INFO [05-06|03:06:05.059] Submitted contract creation              fullhash=0x0db511c2c4729cef8b6bacc20d6ab30dc00aef008ad6a701adec4feb27fe47b5 to=0x706357D0E1c2393858f65740d07F2bD09885507C
INFO [05-06|03:06:05.067] QUORUM-CHECKPOINT                        name=TX-CREATED                                              tx=0x0db511c2c4729cef8b6bacc20d6ab30dc00aef008ad6a701adec4feb27fe47b5 to=0x706357D0E1c2393858f65740d07F2bD09885507C
INFO [05-06|03:06:05.075] Generated next block                     block num=4 num txes=1
DEBUG[05-06|03:06:05.081] Trie cache stats after commit            misses=0 unloads=0
DEBUG[05-06|03:06:05.085] Trie cache stats after commit            misses=0 unloads=0
INFO [05-06|03:06:05.086] 🔨  Mined block                           number=4 hash=bbb6b4b3      elapsed=27.6517ms
INFO [05-06|03:06:05.091] QUORUM-CHECKPOINT                        name=TX-ACCEPTED                                             tx=0x0db511c2c4729cef8b6bacc20d6ab30dc00aef008ad6a701adec4feb27fe47b5
```

**Comment by shiqinfeng1** [comment]
hi @bmcd87 ， I tried to modify the code （PublicTransactionPoolAPI.SendTransaction()）like this:

```
        tx := args.toTransaction()
	var chainID *big.Int
	if config := s.b.ChainConfig(); config.IsEIP155(s.b.CurrentBlock().Number()) {
		if !isPrivate {
			chainID = config.ChainID
		}else{
			chainID = big.NewInt(1)
		}
	}

	signed, err := wallet.SignTx(account, tx, chainID)
	if err != nil {
		return common.Hash{}, err
	}
	if isPrivate {
		signed.SetPrivate()
	}
```

In KeyStore.SignTx (...), modify to:

```
// start quorum specific
if tx.IsPrivate() || chainID.Cmp(big.NewInt(1)) == 0 {
	log.Info("Private transaction signing with QuorumPrivateTxSigner")
	return types.SignTx(tx, types.QuorumPrivateTxSigner{}, unlockedKey.PrivateKey)
} // End quorum specific
```
No errors were reported after the modification, but I ’m not sure if the modification was actually correct.

**Comment by bmcd** [comment]
I'm a little confused. Are you:

A: forking and modifying the Quorum code to try to solve this deployment failure

or

B: forking and modifying the Quorum code for some other reason (like adding a feature) and the deployment failure is the result of those changes

If it's A, I would say let's consistently reproduce this on an unmodified version of quorum, isolate the issue, and then figure out the steps to solve it. (I am able to deploy your contract just fine, both in public and private contracts)

If it's B, I think you're might have to just revert your changes and then slowly add them back in to see which part specifically is causing the issue. I don't know how much we're able to help debug your fork. It's a little hard to see what specific problem you're trying to solve with your code changes.

**Comment by shiqinfeng1** [comment]
I'm sorry I didn't mention that I made some cryptographic-related changes. I thought it would not affect the results.
I will use the unmodified version v2.5.0 to compare and test, and then tell you the results. thanks for your suggestion！

**Comment by shiqinfeng1** [comment]
This problem has been solved and it was caused by my own modification. The problem is with SetPrivate (), because my V-value calculation method is: `sig [64] + 35 + chianID * 4`. thank you for the help.
