### ISSUE TITLE
Exceed gas block limit

### ISSUE THREAD

**Issue by sushant1431** [Consensys-Incorporated/quorum#99]
Currently I am getting this issue while making transactions:
exceed gas block limit 
I get this error only after Quorum is running for more than approx. 10 hours.
Initially i can perform as many transactions as i want but this issue arises only after approx 10 hours.

Herewith attached genesis.json  file I am using.

Configuration:
[genesis.json.txt](https://github.com/jpmorganchase/quorum/files/928508/genesis.json.txt)

geth 1.5.0 unstable

**Comment by tylobban** [comment]
Hi, please can you provide some more info: are you continually publishing transactions throughout those 10 hours? If so, at some steady rate? What are the transactions doing? Please send through the log at the point of failure. Thanks.

**Comment by sushant1431** [comment]
Hi, No we didn't make any transactions throughout 10 hours, Currenty I don't have log since we just reinitialized the quorum. will provide you the logs as soon as it again throw the error.

**Comment by tylobban** [comment]
Thanks. In the mean time please provide geth version

**Comment by sushant1431** [comment]
geth version: 1.5.0-unstable-6d0bd810

**Comment by tylobban** [comment]
ah, this issue was actually fixed in 1.0.3.  Can you download the [latest ](https://github.com/jpmorganchase/quorum/releases/tag/v1.1.0)release and retest please?

**Comment by sushant1431** [comment]
oh ok, currently we are using 1.0.2 quorum. will update to 1.0.3 & let you know if still face the same issue. btw below are the logs which i get after crashing



[constellation_importer.log.txt](https://github.com/jpmorganchase/quorum/files/933018/constellation_importer.log.txt)
[importer.log.txt](https://github.com/jpmorganchase/quorum/files/933019/importer.log.txt)

JsonRpc = {"jsonrpc":"2.0","id":1,"method":"eth_sendTransaction","params":[{"from":"0x63de0e7e52a34debea83466adbcaf811b161fa9a","gas":"0x895440","to":"0x12b66bb1e465088543f62d6260ef37204a5962b8","data":"0x74fcc97050504f313439323538383734323230370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000104d6f6c64696e67204d616368696e657300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002632204d6f6c64696e67204d616368696e65732061732070657220502e4f2e204e756d6265722e0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002c7b2266696c6553686131504f223a2268617368222c2266696c65536861314c6f43223a226c6348617368227d0000000000000000000000000000000000000000","privateFor":["B2m1Up3QkLZgL/0Y4hfj+SJRh4Nn3Z8urmYj3MGoeGw=","I42lywKHlcPCFVAHFezRM0aoObVMdHfUW802WMbF9SQ=","i3+WhR2GTBbg5XP4icGK2dkRX+HRIUcAg160yeQ/Qmw=","A9CEl6M1gpguGl1FYyXmUkGiTkyGr8XlRNc9bBIPTGA="]}]}
Ethereum Resp = {"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"Exceeds block gas limit"}}
initialisePurchaseResult is {}
(node:57703) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 204): TypeError: Cannot read property 'length' of undefined

**Comment by sushant1431** [comment]
Issue of "exceed gas block limit"  has been resolved after upgrading to quorum version 1.1.0, But today noted following behavior:
-  Out of 5 nodes, one one was stopped automatically and "geth.ipc" for that particular node was missing.

**Comment by tylobban** [comment]
Hi, glad to hear that issue is resolved. Can you provide more details on this node5 issue? Is it stopped immediately or after some time? Are there any exceptions in the log (qdata/logs)?

**Comment by sushant1431** [comment]
Hi @tylobban, that issue occur after approx 10 hours, But after re-initializing all the quorum nodes, this issue didn't reproduce again. Will get back to you if face the same issue. 

Thanks so much for helping out in this issue.

**Comment by tylobban** [comment]
Ok please do, thanks.
