### ISSUE TITLE
web3.eth.sendRawPrivateTransaction is not a function

### ISSUE THREAD

**Issue by ghost** [Consensys-Incorporated/quorum#991]
Hi,

I am getting error function not found while executing sendRawPrivateTransaction in JS file for submitting transaction.

#### System information

Geth version: 1.8.18-stable

OS & Version: OSX

Branch, Commit Hash or Release: `git status`

#######My smart contract code:

pragma solidity ^0.5.0;

contract Meme {
  string memeHash;

  constructor(string memory _initVal) public {
    memeHash = _initVal;
  }

  function set(string memory _memeHash) public {
    memeHash = _memeHash;
  }

  function get() public view returns (string memory) {
    return memeHash;
  }
}

##### My app.js file code through which I am trying to submit the private transactions from node1 to node7 (I am using quorum 7 node sample network on vagrant)

const Tx =  require('ethereumjs-tx') 
const Web3 = require('web3')
const web3 = new Web3('http://localhost:22000')

const account1 = '0xed9d02e382b34818e88B88a309c7fe71E65f419d'

const privateKey1= Buffer.from('E.........................................F1','hex')

const contractAddress = '0x9AC8A5eFC282aFab3B2a7286704F232767645733'
const ABI = [{"constant":false,"inputs":[{"name":"_memeHash","type":"string"}],"name":"set","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function"},{"constant":true,"inputs":[],"name":"get","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[{"name":"_initVal","type":"string"}],"payable":false,"stateMutability":"nonpayable","type":"constructor"}]

const contract = web3.eth.Contract(ABI, contractAddress)

const data = contract.methods.set('QmWTVJgoPXfmJodjMtgZQ9f2vjGQM2HDFsVSUMzxwzkzj7').encodeABI()

web3.eth.getTransactionCount(account1, (err, txCount) => {

    console.log ('txCount: ',txCount)
    
    //Build the transaction
    const txObject = {
        nounce: web3.utils.toHex(txCount),
        gasLimit: web3.utils.toHex(800000),
        gasPrice: web3.utils.toHex(web3.utils.toWei('0','gwei')),
        to: contractAddress,
        value: '0x00',
        data: data
    }

    //Sing the transaction
    const tx = new Tx(txObject)
    tx.sign(privateKey1);
    const serializedTransaction = tx.serialize()
    const raw = '0x' + serializedTransaction.toString('hex')

    //Broadcast the transaction
    web3.eth.sendRawPrivateTransaction(raw, {privateFor: ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]}, function(err, hash) {
        if (!err)
          console.log(hash); 
        else
          console.log(err);
      });

})

#### Expected behaviour
Transaction should be processed successfully and value should be updated on node1, node7 only.

#### Actual behaviour
Getting function not found.

#### Steps to reproduce the behaviour
http://docs.goquorum.com/en/latest/Getting%20Started/api/

If possible, please share latest example of connecting and submitting transactions using API so I can connect UI.

**Comment by chris-j-h** [comment]
Judging by the version number you are using `go-ethereum` and not `quorum`. `sendRawPrivateTransaction` is a quorum-only API.  

Make sure that [quorum has been installed correctly](http://docs.goquorum.com/en/latest/Getting%20Started/Installing/) and is available on your `PATH`.  

When quorum is installed correctly the output of `geth version` should be something like (note the `Quorum Version: 2.x` line):
```shell
Geth
Version: 1.9.7-stable
Git Commit: 9339be03f9119ee488b05cf087d103da7e68f053
Git Commit Date: 20200504
Quorum Version: 2.6.0
Architecture: amd64
Protocol Versions: [64 63]
Network Id: 1337
Go Version: go1.13.10
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

**Comment by ghost** [comment]
> Judging by the version number you are using `go-ethereum` and not `quorum`. `sendRawPrivateTransaction` is a quorum-only API.
> 
> Make sure that [quorum has been installed correctly](http://docs.goquorum.com/en/latest/Getting%20Started/Installing/) and is available on your `PATH`.
> 
> When quorum is installed correctly the output of `geth version` should be something like (note the `Quorum Version: 2.x` line):
> 
> ```shell
> Geth
> Version: 1.9.7-stable
> Git Commit: 9339be03f9119ee488b05cf087d103da7e68f053
> Git Commit Date: 20200504
> Quorum Version: 2.6.0
> Architecture: amd64
> Protocol Versions: [64 63]
> Network Id: 1337
> Go Version: go1.13.10
> Operating System: linux
> GOPATH=
> GOROOT=/usr/local/go
> ```

Hi, 

Sorry, I had mention the wrong version number of geth. 

Geth version I am using is 1.8.18

**Comment by SatpalSandhu61** [comment]
Version 1.8.18 is also a version of upstream geth (go-ethereum), not qourum.
As commented by Chris above, if you're using quorum then the output of `geth version` will contain a line containing `Quorum Version`.

**Comment by ghost** [comment]
Geth
Version: 1.8.18-stable
Git Commit: 685f59fb5e08bf9d26fa2b8a1effbb03355b7c4f
Quorum Version: 2.5.0
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1337
Go Version: go1.11.13
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.11.13.linux.amd64


I am using vagrant to run 7nodes example. I am able to interact with the nodes with command line and able to send the transaction. Below is sample command which working fine.

Adoption.deployed().then(function(instance) { return instance.adopt(1, {privateFor: ["ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="]}); })

But, I am getting error while integrating UI with node using APIs as mentioned in initial comments. Kindly help.

**Comment by chris-j-h** [comment]
The quorum-specific APIs are available on the geth js console (when you do `geth attach geth.ipc`). 

However these APIs are not available in `web3.js`.    Instead use [`quorum.js`](https://github.com/jpmorganchase/quorum.js/) which extends `web3.js` to allow use of these APIs in js code.  [Here's an example of how to extend `web3` with `quorum.js`.](https://github.com/jpmorganchase/quorum.js/blob/master/7nodes-test/extension.js)
