### ISSUE TITLE
Tessera is taking a long time to start. Look at the Tessera logs in qdata/logs/ for help diagnosing the problem.

### ISSUE THREAD

**Issue by mbritel** [Consensys-Incorporated/quorum#999]
Hi,

I've got this error using the quorum-wizard on Ubuntu machine and I don't know why. 
I've added the rwx access for Tessera and Geth but I still have the same error.

Thanks for your help !

```
Tessera is taking a long time to start. Look at the Tessera logs in qdata/logs/ for help diagnosing the problem.
Waiting until all Tessera nodes are running...
Node 1 is not yet listening on tm.ipc
Node 1 is not yet listening on http
Node 2 is not yet listening on tm.ipc
Node 2 is not yet listening on http
Node 3 is not yet listening on tm.ipc
Node 3 is not yet listening on http
Node 4 is not yet listening on tm.ipc
Node 4 is not yet listening on http
Node 5 is not yet listening on tm.ipc
Node 5 is not yet listening on http
Node 6 is not yet listening on tm.ipc
Node 6 is not yet listening on http
Node 7 is not yet listening on tm.ipc
Node 7 is not yet listening on http
Tessera is taking a long time to start. Look at the Tessera logs in qdata/logs/ for help diagnosing the problem.
Waiting until all Tessera nodes are running...
```

**Comment by jbhurat** [comment]
Hi @mbritel, can you post the contents from your log files

**Comment by mbritel** [comment]
Hi I have this in my log files: javax/xml/bind/annotation/XmlElement
I m using openjdk version "11.0.7" 2020-04-14.

Thank you!

**Comment by jbhurat** [comment]
I believe you are using Tessera version 0.10.2 or earlier. Can you try using jdk 8 and see if resolves your issues. You can take a look at the java version requirements here https://github.com/jpmorganchase/tessera#prerequisites

**Comment by mbritel** [comment]
Nothing changed, I still have the same problem.

**Comment by jbhurat** [comment]
Is it still failing for the same reason? What is the tessera and java version you are using

**Comment by mbritel** [comment]
Yes I still have the same reason. Tessera version: 0.10.2 while java version is openjdk version "1.8.0_252"

**Comment by jbhurat** [comment]
Is there anything else in the logs

**Comment by mbritel** [comment]
I still have: javax/xml/bind/annotation/XmlElement
Do you think I have to install manually Tessera or cloning the repo is enough?

**Comment by jbhurat** [comment]
Are you using Tessera binary from your PATH, or the one downloaded from `quorum-wizard` is being used

**Comment by mbritel** [comment]
I am using the one downloaded from quorum-wizard

**Comment by jbhurat** [comment]
Can you confirm if the terminal window where you are running the start script to run the network has jdk 8 in the path

**Comment by mbritel** [comment]
Hello again,

Yes, I've already checked that.

![image](https://user-images.githubusercontent.com/61880713/81945724-c0f90b00-95fe-11ea-8692-7b098d4927d0.png)

**Comment by jbhurat** [comment]
Closing the issue as it is being discussed on slack and as suggested on slack, please use vagrant or docker on Windows
